### ISSUE TITLE
Contact point for Node ES module interop

### ISSUE THREAD

**Issue by bmeck** [Microsoft/ChakraCore#1002]
I am running the Node interop with ES modules in https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md . I'm trying to find a good way to contact Yong Qu (or maybe someone else?) about some gotchas, but could not find social media or email location.

In particular getters and non-object values:

```js
// commonjs
module.exports = {
  get y() {/*...*/}
}
```

```js
import x,{y} from 'commonjs';
console.log(x)
console.log(y) // does perform getter
```

and

```js
// commonjs
module.exports = ()=>{}
```

```js
import fn,{call} from 'commonjs';
fn();
call(); // throws, not a function
```

Have had a some calls w/ TC39/Node/WHATWG, now contacting engines.

**Comment by bterlson** [comment]
If you'd prefer email probably easiest if you email me and I'll forward as necessary!
