### ISSUE TITLE
bn.js performance issues

### ISSUE THREAD

**Issue by indutny** [Microsoft/ChakraCore#1020]
It looks like [bn.js](https://github.com/indutny/bn.js) is running 6x slower on a Chakra than it does on V8, or IonMonkey (or whatever it is called now). My suspicion is that it may be related to the integer/double representations and conversions between them.

See: https://github.com/indutny/bn.js/issues/146

**Comment by MikeHolman** [comment]
From the linked thread, it looks like this is an issue in IE but not Edge? We might be able to help you find a workaround if the perf issue is blocking, but codebases are very different now between Edge and IE, so backporting perf optimizations isn't really feasible.

**Comment by indutny** [comment]
@MikeHolman you're absolutely right! Sorry, I forgot to update this issue. Any help would be very appreciated, it would be great to help @bergr01 mitigate this!

**Comment by bergr01** [comment]
@MikeHolman @indutny 

Perhaps I spoke too soon when I said Edge wasn't having this issue.
I finally got the Edge-based login into my app working (this was pending a fix to a separate third party library), and now I can see that the call to mR.redPow(obj.privateExponent) from indutny/bn.js  takes 39 (yes, you've read that correctly, 39) seconds during the login process. The snippet of our JS code is as follows:

    console.warn('Data length', data.length)
    var m = new BN(data)
    console.warn('1', new Date())
    console.warn('Obj.modulus length', obj.modulus.length)
    var mR = m.toRed(BN.mont(obj.modulus))
    console.warn('2', new Date())
    console.warn('obj.privateExpo length', obj.privateExponent.length)
    var tmp = mR.redPow(obj.privateExponent)
    console.warn('2.5', new Date())

yields

Data length 256
1 Thu May 26 2016 13:57:33
Obj.modulus length 79
2 Thu May 26 2016 13:57:33
obj.privateExpo length 79
2.5 Thu May 26 2016 13:58:12

while the corresponding output from Chrome-based login:

Data length 256
rsa.js?d373:291 1 Thu May 26 2016 14:04:03
rsa.js?d373:292 Obj.modulus length 79
rsa.js?d373:294 2 Thu May 26 2016 14:04:03
rsa.js?d373:295 obj.privateExpo length 79
rsa.js?d373:297 2.5 Thu May 26 2016 14:04:06

i.e. 3 seconds, instead of 30+

**Comment by MikeHolman** [comment]
Hmm, ok. I don't think I'm seeing the same perf that you are. I tried doing some profiling with your original benchmark, and I see most time is in bigMulTo, likely exasperated by the mul in the inner loop overflowing int32, causing us to fall back to float math. I spent a bit of time trying to optimize this, but wasn't able to get anything faster than the current implementation. However, I suspect Chrome will not be too graceful with handling this either, so I'd be surprised if this is the issue.

For me, on IE11 I see 1.4 seconds per iteration and on Edge I see ~0.5 seconds. Given this disparity between my data and yours, I'm wondering if you are running test under debug mode? Under debug mode, a lot of optimizations are disabled, and I do see this taking a long time.

**Comment by indutny** [comment]
@MikeHolman don't have any explanation for numbers, but I can explain what happens with floats.

bn.js stores bignums using 26-bit limbs, because:

* They can be multiplied in JS without the loss of precision
* It is a compact way to store big numbers

**Comment by akroshg** [comment]
I believe the slowness happened due to F12 is opened. @indutny could you verify the scenario by clicking the **'Disconnect debugger'** button under the **Debug** tab of F12?

**Comment by indutny** [comment]
@akroshg I'd love to, but I don't have any Windows machine at hand.

**Comment by bergr01** [comment]
Sorry folks, looks like F12 developer tools being open is the culprit for me too - lesson learned! Chrome doesn't seem to have this sort of deterioration when its F12 console is open. With developer console closed, the login for me is now not taking anywhere near as long as the 30+ seconds I mentioned earlier!

**Comment by akroshg** [comment]
@bergr01 as @MikeHolman mentioned there are few optimizations disabled when F12 is opened. However you can still have the F12 opened and not go to debug mode. As I mentioned earlier, click on the **Disconnect Debugger** button under **Debug** tab of F12 - this will not degrade the performance.
@bergr01 will you close this issue if there is no further action needed?

**Comment by bergr01** [comment]
Happy for the issue to be closed, not sure if I have the privileges - @indutny  can you please do the honours?

**Comment by indutny** [comment]
Thank you everyone!
