### ISSUE TITLE
Wasm interpreter for unaligned memory load

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1042]
In the official test suite address.wast the unaligned memory load give bad results.
We didn't want to regress asm.js which doesn't allow unaligned load so we will have to create a different path for wasm that needs to check the alignment.

**Comment by DemiMarie** [comment]
Can this be handled using memcpy?

**Comment by arunetm** [comment]
@Cellule I can take care of this one if this is still not done.

**Comment by Cellule** [comment]
@arunetm Sure, if you want to take a stab at it. you can test your fix with address.wast in the official test suite with -nonative vs -forcenative

**Comment by arunetm** [comment]
https://github.com/Microsoft/ChakraCore/pull/1494 fixes this

**Comment by arunetm** [comment]
The PR has been merged. We can mark this one as done.
