### ISSUE TITLE
Fix hardcoding of max process address space on Linux

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#1059]
The max address space for a process is hardcoded on Linux. We should find a better mechanism of obtaining this information so that the GC can function correctly.

**Comment by xanlpz** [comment]
Should we close this now? I don't think we can do much better on Linux.

**Comment by dilijev** [comment]
@digitalinfinity any update on this?

**Comment by obastemur** [comment]
@xanlpz Thanks for the effort on this. IMO we may close this for now.
