### ISSUE TITLE
Assertion failure in tests when changeHeap is not correctly implemented

### ISSUE THREAD

**Issue by Shiney** [Microsoft/ChakraCore#1062]
In https://github.com/Shiney/ChakraCore/tree/AsmJsChangeHeapAssertionFailure

I have added a new version of the asmjs test relink.js with a small change to one of the constants to make it not match the expected change heap function.

https://github.com/Shiney/ChakraCore/commit/3d7ee3e40a5645b174cd902448e7cf62f258dfa3

https://github.com/Shiney/ChakraCore/blob/AsmJsChangeHeapAssertionFailure/test/AsmJs/relinkFail.js
https://github.com/Shiney/ChakraCore/blob/AsmJsChangeHeapAssertionFailure/test/AsmJs/relinkFail.baseline
https://github.com/Shiney/ChakraCore/blob/AsmJsChangeHeapAssertionFailure/test/AsmJs/rlexe.xml

Running the test with e.g.

runtests -x64debug -dirs asmjs 

Causes an assertion failure as shown below.

2>ASSERTION 40948: (D:\dev\ChakraCore\ChakraCore\lib\Runtime\Base\FunctionBody.c
pp, line 1485) this->GetFunctionProxy() == this
2> Failure: (this->GetFunctionProxy() == this)

Also getting the same issue when trying to implement #65

**Comment by MikeHolman** [comment]
I just tried to repro on release/1.6 bits and seems that the bug is gone.
