### ISSUE TITLE
Wiki needs a help page on how to run tests.

### ISSUE THREAD

**Issue by nojvek** [Microsoft/ChakraCore#1068]
Thanks for Ian's help on getting me unblocked, but for outsiders a how to run tests page would be very helpful.

**Comment by ianwjhalliday** [comment]
@nojvek pointed out it would be useful to have information such as:

- how tests are organized by `rlexedirs.xml` and `rlexe.xml` files
- adding a new test
- clarifying that *.js files do not automatically turn into tests
- baselines vs no baselines vs exit code check only
- where rl log files go
- techniques for capturing output from and iterating quickly on failing tests

**Comment by dilijev** [comment]
Good plan. This issue would be a good opportunity for us to use issues and a PR on the wiki repo http://github.com/Microsoft/ChakraCore-wiki to review the addition. :)

**Comment by dilijev** [comment]
Closing this issue as it has been migrated to https://github.com/Microsoft/ChakraCore-wiki/issues/7
