### ISSUE TITLE
In Windows 10 (build 14332) window.clipboardData.setData does not work as expected.

### ISSUE THREAD

**Issue by takahiroyoshi** [Microsoft/ChakraCore#1071]
This is the story of IE 11 on Windows 10(build 14332), IE 11 does not show any prompt when I use window.clipboardData.setData even though the settings in 
“Allow Programmatic clipboard access” is "prompt".

The test page is:
http://www.broadband-xp.com/test/ie11/clipboard.html

If I change the settings in “Allow Programmatic clipboard access” from the default value of "prompt" to "enabled", it works. But if I change the settings back to "prompt", IE does not show a prompt but clipboard copying fails silently.

---

Repro code:

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=Shift_JIS">
<title>test</title>
<script>
function a(){
var b=window.clipboardData.setData("text","This is a test. Sucess!");
if(b){
	alert("success");
}else{
	alert("fail");
}
}
</script>
</head>
<body bgcolor=#FFFFFF>
<input type=button onClick="a();" value="Copy to Clipboard">
</body>
</html>
```

**Comment by dilijev** [comment]
Works in IE 11 on 10586 - I would expect that hasn't regressed in a later build since we only do servicing for IE 11 and not updates.

Assuming that this bug is targeting Edge (which hosts the current version of Chakra), I will add that it does not seem to work as intended in Chrome either. I wonder if the spec semantics have changed and the code shouldn't work as-is and just happens to work in IE due to legacy behavior?

**Comment by takahiroyoshi** [comment]
That's right. It works in IE on Build 10586. So it is a regression, I believe, even though I do not know why the regression happens. Anyway, the prompt is surpressed, and never shown to the user in spite of IE's settings in Build 14332.

**Comment by dilijev** [comment]
Thanks for confirming.

IE is a different product than Edge, so this issue wouldn't be considered a regression unless it worked in a previous version of Edge (it is possible this code never worked in Edge as you intended; it also does not work in Chrome).

**Comment by takahiroyoshi** [comment]
I know that IE is a different product than Edge.

First I try to report this bug at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
But I was suggested to report this bug here.

If this is not an appropriate forum to post, please let me know.

I know that this code never worked in Microsoft Edge.

**Comment by dilijev** [comment]
@takahiroyoshi Okay, I'm glad we're on the same page. Thanks for reporting this to us. We will triage this and figure out how to route the issue in case it is not a problem in the ChakraCore engine.

**Comment by dilijev** [comment]
Assigning @abchatra for triage.

**Comment by dilijev** [comment]
@bterlson Do you have any context on the behavior of window.clipboardData.setData ?

**Comment by bterlson** [comment]
All I know is that it's a nascent API that Edge doesn't support. It should continue to work in IE, however, so if it is broken that is definitely an issue. However it seems very unlikely to be a chakra issue. @takahiroyoshi can you link to the connect bug you filed? I'm curious if whoever directed you here had some thoughts on why it could be a Chakra issue.

**Comment by takahiroyoshi** [comment]
Actually I have never filed it. But when I tried to post the bug at
https://developer.microsoft.com/ja-jp/microsoft-edge/platform/issues/new/
and select "Javascript Language/Chakra" as the Category,
both the title field and "steps to reproduce the issue" filed are disabled.
And I see the link to this github site.

![report_ie11_bug](https://cloud.githubusercontent.com/assets/3334552/15949510/13bc79b2-2ee3-11e6-9007-0f1287e47e6b.jpg)

So I thought every bug report concerning JavaScript of IE11 or Microsoft Edge should be posted here.

**Comment by abchatra** [comment]
@takahiroyoshi window.clipboard is a DOM feature. Select HTML/DOM: Events ... as the category. This issue does not belong to Chakra

**Comment by takahiroyoshi** [comment]
Ok. Thank you for pointing me to the right place.
I re-posted this issue at
https://developer.microsoft.com/ja-jp/microsoft-edge/platform/issues/7844941/

Thank you all.
