### ISSUE TITLE
Checking arguments.length slow

### ISSUE THREAD

**Issue by iskiselev** [Microsoft/ChakraCore#1083]
Checking arguments.length slow with Chakra. Here is sample page:
```
<html>
<body>
<script>
var start = Date.now();

function one(a){
}

function two(a,b){
}

function route(a,b){
   switch (arguments.length) {
   case 1:
     return one(a);
   case 2:
     return two(a,b);
   }
}

for (var i = 0; i<1000000; i++) {
  route(1,2);
}

document.write(Date.now() - start);
</script>
</body>
</html>
```
My results:
- Edge: ~380ms
- Chrome: ~20ms
- Firefox: ~3ms

**Comment by kg** [comment]
Maybe do something to make sure the loop isn't being optimized out? Like return a result from ```one``` and ```two```, then sum the results up and check them at the end. That way the times are at least comparable.

**Comment by iskiselev** [comment]
Updated test:
```
<html>
<body>
<script>
var start = Date.now();

function one(a){
  return a;
}

function two(a,b){
  return b;
}

function route(a,b){
   var argc = arguments.length | 0;
   switch (argc) {
   case 1:
     return one(a);
   case 2:
     return two(a,b);
   }
}

var sum = 0;
for (var i = 0; i<1000000; i++) {
  var r = Math.random();
  if (Math.random() > .5) {
    sum += route(r,-r);
  } else {
    sum += route(r);
  }
}

document.write("sum: " + sum + "<br>time: " + (Date.now() - start));
</script>
</body>
</html>
```
My results:

Edge: ~400ms
Chrome: ~80ms or ~270ms
Firefox: ~17ms

**Comment by bterlson** [comment]
Curious how adding a "use strict" to the top of your script will impact this. Strict mode arguments object is much more lightweight.

**Comment by iskiselev** [comment]
@bterlson, thank you. It was last piece of issue in sq/JSIL#978. In strict mode it is totally awful:
Edge: __~1380ms__
Chrome: ~65ms or ~250ms
Firefox: ~17ms

**Comment by satheeshravi** [comment]
This issue will be fixed in https://github.com/Microsoft/ChakraCore/pull/1023. This is a WIP item.

**Comment by ianwjhalliday** [comment]
Curious that strict mode is even worse

**Comment by akroshg** [comment]
@ianwjhalliday it seems we create the actual arguments object in a normal path and later we unmap them. Look for `ConvertToUnmappedArguments`

**Comment by pleath** [comment]
Yes, that’s a known badness. We do want to fix it, for this and other reasons.

--Paul

**Comment by satheeshravi** [comment]
@iskiselev , this issue is fixed. Can you please try with the latest binary and close this issue?

**Comment by iskiselev** [comment]
@satheeshravi, thank you for info. As soon as new build will be published to https://www.myget.org/feed/chakracore-preview/package/nuget/Microsoft.ChakraCore I'll check it.

**Comment by satheeshravi** [comment]
@iskiselev We currently don't publish binaries built from master branch. The fix is in master branch. You can build privately and verify. Sorry about the inconvenience.

**Comment by EdMaurer** [comment]
@iskiselev did [@satheeshravi's change](https://github.com/Microsoft/ChakraCore/issues/1135) address your issue?

**Comment by iskiselev** [comment]
I could confirm that issue is resolved now.

**Comment by satheeshravi** [comment]
Thanks!
