### ISSUE TITLE
rlexe.xml tags: add support for new build architecture and type terms

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#110]
Tests use legacy build architecture and type terms for exclusion tags:
- `exclude_amd64`
- `exclude_chk`
- `exclude_fre`

[`test/runtests.cmd`](https://github.com/Microsoft/ChakraCore/blob/master/test/runtests.cmd) uses the new terms as input but shims them to the old terms for the exclusion tags.  It would be nicer to change all the rlexe.xml files to use the new terms and remove the shim from `runtests.cmd`.

New tags should be:
- `exclude_x64`
- `exclude_debug`
- `exclude_test`

----

@dilijev: Update 12/18/2016

Due to the pervasive use of the old tag names across multiple dev branches and both internally and externally, the initial work item here should be to add support for the new tags, and ensure that we continue to support the old tags.

At the time of the PR which adds support, all of the existing uses of the old terms should be updated to the new terms. New tests added via other branches which do not yet support the new terms will still use the old terms, so supporting both for a time is necessary.

This means any place we would exclude either the old or new tag, we must exclude both. For example, we must exclude BOTH `exclude_x64` (new) and `exclude_arm64` (old), and never only one of them.

At some point in the future (when all active development branches support the new terms), we will deprecate the use of the old terms and remove support for them. At that time, all remaining uses of the old terms will be replaced with the new terms and support will be dropped from the scripts.

See follow-up work item #2240.

**Comment by tcare** [comment]
We'll need an internal workitem for this as well.

**Comment by dilijev** [comment]
@tcare Was there an internal workitem created for this? I'm planning to bring in #1300 so I'll end up doing that work.

**Comment by tcare** [comment]
Not that I know of. Doubt we would track that internally.

**Comment by dilijev** [comment]
@tcare ok thanks.

**Comment by dilijev** [comment]
I'm assigning this to @RexSong to track it.
