### ISSUE TITLE
SCRIPT70: Permission denied

### ISSUE THREAD

**Issue by vumanimdabe** [Microsoft/ChakraCore#1100]
Hi when I have an web app which calls js scripts on different domains when i run the app in doesn't load any of those scripts when I use Microsoft Edge debug tools, it shows "SCRIPT70: Permission denied" for all unloaded scripts. FYI this only happens on Microsoft Edge 25.10586.0.0
Thanks.

**Comment by dilijev** [comment]
Can you provide a simplified example project? Also this sounds like it might be an Edge issue, not a Chakra issue.

**Comment by vumanimdabe** [comment]
Hi there, Thanks for the reply. The site opens using flash, after which it integrates the [nemid ](https://www.nemid.nu/dk-en/)login window inside an iframe for authentication. During the process it accesses scripts located at different domains some mine and other belong to the nemid client. Everything seems to work perfectly across other browsers except for Edge, when i debug using dev tools on Edge i get the error message stated above. I'm not sure if that's clear enough.

**Comment by dilijev** [comment]
Could you provide a set of source code files, a URL, and/or screenshots? Please detail expected versus actual behavior for the specific case that the source code represents.

**Comment by dilijev** [comment]
@vumanimdabe Were you by any chance redirected here after trying to file a bug at https://developer.microsoft.com/ja-jp/microsoft-edge/platform/issues/new/ which seemed to indicate that any issues with Javascript should be directed to this GitHub repo? The text there is somewhat confusing, see recently opened issues that we redirected back to that page:
https://github.com/Microsoft/ChakraCore/issues/1129#issuecomment-225494725
https://github.com/Microsoft/ChakraCore/issues/1071#issuecomment-225054502

That said based on the info you've provided I'm not sure if this is an issue with Chakra, Flash, or some DOM API exposed through Javascript misbehaving. It would be great if you could provide a little more info so we could route this bug.

/cc @ianwjhalliday

**Comment by ianwjhalliday** [comment]
This sounds like it might be a security feature of Edge that needs to be acknowledged in the website, but I'm not deeply familiar with the web site security features of IE/Edge.  @Yongqu might know who to talk to.

**Comment by vumanimdabe** [comment]
@dilijev yes i was redirected here after trying to file a bug on Microsoft Edge, @ianwjhalliday initially I also thought this to be a security feature on Edge  because this is how the app runs

- Flash client hosts NemID in an iframe
- NemID hosts DanID in an iframe
- DanID executes some JavaScript (which works), and that cases NemID to execute some JavaScript (which fails in Edge). 
**DanID/NemID** being the Denmark Login Client

**Comment by Yongqu** [comment]
Hi @vumanimdabe Thanks for the description, but unfortunately it is hard to tell what's wrong from this description. having a repro would be really nice. Is this a regression from IE? Does your scenario works in IE11? Please note that IE/edge does not support CORS script element at this time, and without a repro it is hard for me to tell what is wrong. 
Can you share the url for your Microsoft Edge bug? how was it redirect to here?
thanks

**Comment by vumanimdabe** [comment]
@Yongqu the problem is repro the error. It does work on IE 11

**Comment by Yongqu** [comment]
@vumanimdabe Thanks for verifying that in IE11. Can you help answer the other questions? having a repro would be really helpful.

**Comment by EdMaurer** [comment]
Looks like this thread has gone cold. @vumanimdabe, is this still an issue?

**Comment by vumanimdabe** [comment]
@EdMaurer this was a security issue on Microsoft edge it has been resolved on their next release, I got a preview of the next windows 10 release and tested it, it works fine. thanks
