### ISSUE TITLE
WScript LoadScript memory leak

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1102]
At https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp#L271
We preallocate `fullPathNarrow` to a buffer with `_MAX_PATH`, however the method `NarrowStringToWideDynamic` does a malloc and replaces that buffer.
We need to free the buffer returned by the helper call.

Also, we should check if the helper failed ie: `IfFailGo(Helpers::NarrowStringToWideDynamic(fullPathNarrow, &fullPath))`

**Comment by jianchun** [comment]
It is fixed in "Linux" branch. No more "fullPath": https://github.com/Microsoft/ChakraCore/blob/linux/bin/ch/WScriptJsrt.cpp#L257

**Comment by Cellule** [comment]
Alright thanks, I'll consider this closed then assuming we'll merge back to master sometime soon
