### ISSUE TITLE
Wasm unreachable EmitInfo

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1112]
Create a new type Unreachable for EmitInfo.
Unreachable is valid for typecheck.
If 1 statement is unreachable in a block all the following statement has to be unreachable (not really important at first, shouldn't happen in real code)

Also, this will allow to correctly invalidate the following
```js
function () : i32 {
  if (cond) {
    return 0;
  } else {
    call something // Right now, the IfElse block will yield void and we will assume unreachable when checking for the function return value
  }
}
```

**Comment by commonlisp** [comment]
There may be an overlap between this issue and an outstanding issue of type checking expressions (c.f. closed PR #735) such as xor (i32.const 1) (return (f32.const 0.0)) and if-else expressions with non-yielding control flow and yielding expressions. We have a pending fix for that which I'll rebase on the current WebAssembly.
