### ISSUE TITLE
Javascript keydown events not firing after .fadein()

### ISSUE THREAD

**Issue by possumdelight** [Microsoft/ChakraCore#1129]
After fading in a modal div, the document looses focus causing keydown and keyup events to no longer fire.  This behavior is specific to Edge.  IE, Chrome, and Firefox do not have this problem.

They key events begin firing again if you click somewhere on the modal div or page, or if you use $(document).focus(); to reset focus on the page.

Some example code from my project:
-------------------------------------------------------------

$('#modal-AjaxCommunicating').fadeIn();

--------------------------------------------------------------

            // Close modal dialog by pressing enter or escape
            $(document).keyup(function (e) {
                if (e.keyCode == 13 || e.keyCode == 27) {
                    if ($('#modal-AjaxCommunicating').is(':visible')) {
                        $('#modal-AjaxCommunicating').fadeOut();
                    }
                }
            });

**Comment by DigiTec** [comment]
Hum, I haven't yet tried to reproduce the issue you are seeing, but this wouldn't fall under Chakra unfortunately. It would, however, fall into the Microsoft Edge issue tracker. 

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

Would you mind reopening your issue there? Also, if it is possible to supply a more complete repro of some sort that would be super helpful. Once you post on the edge platform issues you are likely to be contacted fairly quickly to help nail down this issue.

**Comment by possumdelight** [comment]
Hmm.  That's how i would up here.  When i clicked on the issue type as javascript, it forced me here.  I'll look again.

**Comment by possumdelight** [comment]
Yea.  If you try and submit an issue here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/new/

It says "For JavaScript Language / Chakra issues, please use Chakra's GitHub."  and will not allow you to go further.

**Comment by ianwjhalliday** [comment]
That text is confusing.  It should clarify that DOM API issues should be filed under HTML/DOM and javascript language semantics and built-in API issues should be filed here on ChakraCore.

@DigiTec @bterlson do you guys know how we can get that text changed?

**Comment by dilijev** [comment]
Yes, @possumdelight please try that form again and try to file the issue under HTML/DOM

**Comment by dilijev** [comment]
@possumdelight in your bug report to them, also include additional info about what version of Windows 10 you're using (is it an insider build? what build number?) You can start `cmd` and read the header message or use the run box to run `winver` to find out the OS build number.

**Comment by possumdelight** [comment]
Thank you for the responses.  I will hop back over there and do it now.

**Comment by dilijev** [comment]
Thanks @possumdelight -- closing this issue as External.
