### ISSUE TITLE
node-mssql unable to connect to azure db

### ISSUE THREAD

**Issue by matejv1** [Microsoft/ChakraCore#1157]
Hi,

is node-mssql already supported on ChakraCore? I'm unable to connect to Azure DB (simple select example). It will just crash an app - no part of it will work anymore - I need to restart / redeploy to run/debug.

**Comment by dilijev** [comment]
Sounds like this is an issue related to Node-ChakraCore. @kunalspathak  could confirm. You might want to move this issue report to https://github.com/nodejs/node-chakracore

**Comment by kunalspathak** [comment]
Thanks for reporting @matejv1 . Could you please open an issue in nodejs/node-chakracore? Also, please provide repro steps.
