### ISSUE TITLE
Implement selected console.* methods in ch.exe (since it is a console host after all)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1175]
Opened this issue to track discussion of adding things like this outside of the PR #1168 where `console.log` is added.

@obastemur suggested it might be nice to add other common `console` methods.

Most likely candidate is `console.error` but I don't know that this team has any real use for that since `ch.exe` is mostly used for testing and we look for any output being different.
- [x] Map `console.log` to `WScript.Echo` to unblock common use case (#1168)
- [ ] (If/when needed:) Provide a complete implementation of `console.log` including formatting and full specification of the API.

**Comment by Cellule** [comment]
Are you referring to 
https://msdn.microsoft.com/en-us/library/hh696634.aspx
or
https://nodejs.org/api/console.html
As in, do we want our host to be more like node or more like the browser ?

**Comment by ianwjhalliday** [comment]
I don't see a strong use case for this

**Comment by dilijev** [comment]
@ianwjhalliday Yes, it's definitely low-priority. Just wanted to track discussion on this particular issue outside of the PR.

**Comment by dilijev** [comment]
@Cellule - that's a good distinction to make. I hadn't considered it. There are a lot of methods in both lists that seem clearly excessive considering that ch.exe is a host intended mainly for testing, and they are uncommon in that scenario. For more complex coding, we'll have Node-ChakraCore, which obviously implements Node's set of console methods.

**Comment by dilijev** [comment]
Per discussion in #1168 also want to track adding a complete implementation of `console.log` which goes beyond the basics provided by `WScript.Echo` in the future (when/as needed).

**Comment by agarwal-sandeep** [comment]
@dilijev do we plan to do more work here?

**Comment by Cellule** [comment]
So far we've been doing well with the current implementation of console.log that we have.
The extra little bits would be nice, but I don't think it is blocking anyone since we now have template literals to do some formatting.

**Comment by dilijev** [comment]
Yeah I think we will add/have been adding these methods as needed -- a perpetually open issue to track this generically is not necessary at this point.
