### ISSUE TITLE
[Question] How many threads exist simultaneously if ChakraCore executes interpreter only (build with /p:BuildJIT=False)?

### ISSUE THREAD

**Issue by lyh-kernel** [Microsoft/ChakraCore#1179]
As title. I build ChakraCore with /p:BuildJIT=False. I am wondering how many threads exist simultaneously if I execute ".\Build\VcBuild.NoJIT\bin\x64_release\ch.exe test.js"?. I noticed there are _beginthreadex and WaitForSingleObject calls in wmain. Does it mean that the max number of threads is 2 during execution?

Thanks

**Comment by digitalinfinity** [comment]
Hi @lyh-kernel, sorry for the late response on this question. The number of simultaneous threads in the case of the NoJIT build can actually be greater than 2. We have at least one additional thread for concurrent garbage collection, and up to 2 more threads if the GC decides that we need to parallelize the mark step. I think there is also another thread created for background parsing. 
Curious- does the number of threads make a difference in your scenario?

**Comment by dilijev** [comment]
Closing question as answered, but feel free to comment if you'd like to discuss further.

**Comment by lyh-kernel** [comment]
Hi @digitalinfinity . I would like to port ChakraCore to other target but such target has no full support of multithread.
My current version of ChakraCore is #f5d756e. If I do the following things:

1. Use /p:BuildJIT=False in the command line
2. #define ENABLE_CONCURRENT_GC 0 in lib/Common/CommonDefines.h just like on Linux
3. Invoke ExecuteTestWithMemoryCheck directly rather then use _beginthreadex to create another thread in bin/ch/ch.cpp just like on Linux

Is it means that the ChakraCore would be single thread (only main thread) version. If not, it there any way to compile ChakraCore as a single thread program?

Thanks
