### ISSUE TITLE
[RegExp] Match updated spec for `/\w/iu` and `/\W/iu`

### ISSUE THREAD

**Issue by mathiasbynens** [Microsoft/ChakraCore#1181]
Now that https://github.com/tc39/ecma262/pull/525 has landed, `\u017F` (LATIN SMALL LETTER LONG S) and `\u212A` (KELVIN SIGN) are word characters for `/iu` patterns.

Expected vs. actual behavior:

``` js
/\w/iu.test('\u017F') // true
/\w/iu.test('\u212A') // true
/\W/iu.test('\u017F') // false, actual: true
/\W/iu.test('\u212A') // false, actual: true
/\W/iu.test('s')      // false
/\W/iu.test('S')      // false
/\W/iu.test('K')      // false
/\W/iu.test('k')      // false
```
#### See also
- V8: https://bugs.chromium.org/p/v8/issues/detail?id=5145
- JavaScriptCore: https://bugs.webkit.org/show_bug.cgi?id=159055
- SpiderMonkey: https://bugzilla.mozilla.org/show_bug.cgi?id=1281739
- regexpu-core: https://github.com/mathiasbynens/regexpu-core/issues/8

**Comment by dilijev** [comment]
Related to #517

**Comment by dilijev** [comment]
Just to clarify, I'm seeing in the following in ChakraCore for expected vs. actual behavior:

``` js
/\w/iu.test('\u017F') // true, actual: false ***
/\w/iu.test('\u212A') // true, actual: false ***
/\W/iu.test('\u017F') // false, actual: true
/\W/iu.test('\u212A') // false, actual: true
/\W/iu.test('s')      // false
/\W/iu.test('S')      // false
/\W/iu.test('K')      // false
/\W/iu.test('k')      // false
```

**Comment by mathiasbynens** [comment]
The expected behavior you’ve outlined is correct.

One minor correction, though:

> Since sharp s and kelvin are word characters

They’re not (as far as `\w` goes in JavaScript), but with the `i` flag set they canonicalize to `S` and `K` which are.

**Comment by dilijev** [comment]
@mathiasbynens Oh, I see. That makes sense. I still think the simplest / most efficient way to get this behavior is to add them to the char set we use for `\w` when both /i and /u flags are set.
