### ISSUE TITLE
URL constructor doesn't allow credential

### ISSUE THREAD

**Issue by CnSimonChan** [Microsoft/ChakraCore#1196]
The code `new URL("http://username:password@127.0.0.1:80/jsonrpc")` throws `A security problem occurred.` on Edge (14.14372).

The standard never mentions about disallowing credential in URLs, and the code above runs successfully in Firefox (48) and Chrome (52) and returns `username` and `password` without problem.

I'm porting an extension from Chrome, it relies on this API to parse URL and make requests.

**Comment by dilijev** [comment]
The URL class is defined by the Edge host. Marking as external. I'll see how we can route this bug.

**Comment by Yongqu** [comment]
Seems like a regression. Can you file create an issue at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ so we can track that? thanks.

**Comment by CnSimonChan** [comment]
OK, here it is: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8004284/

**Comment by dilijev** [comment]
Thanks @CnSimonChan - closing as External.
