### ISSUE TITLE
Add auto code-review checks: tabs, trailing whitespace, etc.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#12]
@tcare has suggested adding an auto-code-review service via chakrabot account for this type of issue rather than blocking PRs on non-functional issues.

Details:

We don't want to block builds by having an extra check for style. What we would like to have instead is an auto code-review bot that will make comments about that sort of thing, and which the author has the freedom to ignore if necessary. Not all such style changes are worth making, and it's difficult to make a good logic for style that should always be applied.

For anything that would potentially be a build-breaking check (which would require almost unanimous agreement on the team), I would prioritize like this based on likelihood of consensus:

1. Tabs
2. Trailing whitespace
3. Blank line at end of file
4. Other style (very unlikely to get unanimous approval)

We already have some necessary style checks as build-breaking checks (where necessary pertains to environment compatibility or legal requirements):

* [EOL Check] EOL characters must be checked into git as `\n` and not `\r\n` for platform compatibility.
* [Copyright Check] The Copyright header on each file must match the header required by Microsoft legal.

---

Labeled as "Accepting PRs" because maybe the community knows of a tool we could deploy to help us with this. It might not be a change that makes it into this repo's source but it might still be helpful.

**Comment by dilijev** [comment]
See comments in https://github.com/Microsoft/ChakraCore/pull/473
I'll copy them below.

**Comment by dilijev** [comment]
I had an OCD moment on tabs recently and checked myself: #425. It's not worth the time to bring in a small change like that. At some point, say around the time we implement an auto code-review system, it would be appropriate to do a pass over the whole code base and fix issues that the system would flag.

**Comment by EdMaurer** [comment]
Investment in whitespace tooling is below the bar at this point.
