### ISSUE TITLE
String.prototype.lastIndexOf broken

### ISSUE THREAD

**Issue by polygonplanet** [Microsoft/ChakraCore#120]
String.prototype.lastIndexOf is broken when passed with the Unicode characters and second argument specified.

```javascript
'abcあい'.lastIndexOf('あい', 1)
```

expected: -1
actual: 3

According to [ECMA 21.1.3.9](http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.lastindexof) - the `position` argument is used for the end of the string to look *left* from - ie, it is indeed spec-compliant behavior for `'abcあい'.lastIndexOf('あい', n)` to return `-1` when `n` is less than `'abcあい'.indexOf('あい')`.

**Comment by goyakin** [comment]
Looks like we aren't taking `position` into account when the `searchString` argument has at least two characters and contains non-ASCII characters.

If anyone wants to work on this, the fix would be in [JavascriptString::EntryLastIndexOf](https://github.com/Microsoft/ChakraCore/blob/4e4d4f00f11b2ded23d1885e85fc26fcc96555da/lib/Runtime/Library/JavascriptString.cpp#L1104).

**Comment by ljharb** [comment]
[es5-shim test cases](https://github.com/es-shims/es5-shim/blob/master/tests/spec/s-string.js#L248-L264) - same bug applies to `indexOf` ([tests](https://github.com/es-shims/es5-shim/blob/master/tests/spec/s-string.js#L233-L246))

**Comment by goyakin** [comment]
@ljharb `indexOf` tests pass for me both on Edge and using `ch.exe`.

**Comment by ljharb** [comment]
Cool, it's possible the indexOf bug is in an older Edge version or a different engine. Thanks for checking :-)
