### ISSUE TITLE
Intl.DateTimeFormat doesn't format minutes and seconds properly in IE 11 and Edge

### ISSUE THREAD

**Issue by laskoviymishka** [Microsoft/ChakraCore#1223]
Related to _https://github.com/angular/angular/issues/9524_
Seems like there is issue with Intl.DateTimeFormat.
When you try to format date with only minutes and/or seconds it ignore it and format as default.
It seems like there is only hour + minutes + seconds pattern support properly.
Here plnkr to describe issue: _http://plnkr.co/edit/OyjNyyb1fJhB1thtuEnA?p=preview_

Version:
IE 11.0.9600.18350 
Edge 25.10586.00

**Comment by dilijev** [comment]
Confirmed that the formats look wrong in Edge 38.14372.0.0 and IE.

For what it's worth, in Chrome, Edge, and IE, I'm seeing 7PM instead of 6AM. I'm thinking that has to do with the timezone you have set on your own machine versus where we are, since 7PM is correct for the given UTC date in the Pacific timezone.

**Comment by gary-b** [comment]
There is also a problem when retrieving the hours without the minutes:
new Intl.DateTimeFormat('ar', {hour: '2-digit', hour12: false}).format(new Date(2015,05,1,9,0,0))
>"‎٠٩‎:‎00"

Note that the minutes have been brought back anyway, and there are a mix of numeral systems present. If you actually request the minutes however:

new Intl.DateTimeFormat('ar', {hour: '2-digit', hour12: false, minute:'2-digit'}).format(new Date(2015,05,1,9,0,0))
>"‎٠٩‎:‎٠٠"

The inconsistency in numeral systems is gone.

If I run this first code snippet on Chrome:
new Intl.DateTimeFormat('ar', {hour: '2-digit', hour12: false}).format(new Date(2015,05,1,9,0,0))
>"٠٩"

I just get the hour.

Microsoft Edge 38.14393.0.0
Version 54.0.2840.71 m

**Comment by dilijev** [comment]
This issue is External to ChakraCore. We'll route it internally to the right folks. Thanks for reporting it!

**Comment by catrosu** [comment]
Hi. Just wondering if there are any plans to fix this anytime soon as the bug still exists in latest version. Thank you

**Comment by dilijev** [comment]
Unsure, however there is a work item in progress to use ICU as a globalization option in ChakraCore (although this will not affect Edge, which will continue to use Windows Globalization).

**Comment by SantaUA** [comment]
Does there is some solution exist now ?

**Comment by dilijev** [comment]
Work on ICU is tracked in: https://github.com/Microsoft/ChakraCore/issues/2919

Related to https://github.com/Microsoft/ChakraCore/issues/2916 and https://github.com/Microsoft/ChakraCore/issues/2915.

Removing the External tag. Will investigate whether there is something we can do on our end to fix this issue regardless of i18n engine (WinGlob or ICU).

**Comment by dilijev** [comment]
Tracking as part of #3644

**Comment by dilijev** [comment]
FYI @jackhorton
