### ISSUE TITLE
default constructor creation for derived class is not spec compliant

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#1228]
As per [spec](https://tc39.github.io/ecma262/#sec-runtime-semantics-classdefinitionevaluation), if derived class doesn't have constructor, it should create a constructor something like this -
```js
constructor(... args){ super (...args);}
```
Instead we do something like this -
```js
constructor(){ super (...arguments);}
```
`...arguments` part loads argumentsObject on heap which is not performance efficient.

**Comment by kunalspathak** [comment]
FYI - @akroshg , @suwc

**Comment by ianwjhalliday** [comment]
Is the use of rest and spread optimized in this case or do they also add perf overhead that may be avoidable somehow?

**Comment by kunalspathak** [comment]
> Is the use of rest and spread optimized in this case 

Probably. See #1230
