### ISSUE TITLE
[Discussion] Does Chakra expose parser information?

### ISSUE THREAD

**Issue by zoryn** [Microsoft/ChakraCore#125]
Does Chakra exposes parser information?

For example, assuming I have script like this:

```javascript
function foo(x, y) {
    return x + y;
}
```
I want to be able to get argument names ("x" and "y").

Alternatively, assuming I have script like bellow and already ran it and got "f1" as a value. Can I get argument names of f1 from runtime?

```javascript
var f1 =function foo(x, y) {
    return x + y;
}
```

**Comment by pleath** [comment]
We don’t have a back door for extracting this kind of information, no, but there’s a very good front door in the form of “foo.toString”. Converting a function object to a string will give you back the original source, and from there you can scan past the “function” keyword and optional name to pull out all the names of the formal parameters.

--Paul

**Comment by zoryn** [comment]
Thanks for your response! This is what I was thinking as well, just wanted to check if there is a better way not involving regex or manual string parsing.
