### ISSUE TITLE
Use specific strong return types for JavascriptOperators::GetOwnPropertyKeys() et al

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#1252]
Upon reviewing #1202 (see https://github.com/Microsoft/ChakraCore/pull/1202#discussion_r69828994) @Yongqu @tcare and I decided we should strongly type the return types of APIs used exclusively internal to the runtime rather than using `Var`.

Motivation comes from `JavascriptOperators::GetOwnPropertyKeys`.  Code review raised concern about assuming the return value is always a `JavascriptArray*` and that callers should handle the case this isn't true.  It is always true however and so far most of the callers have made this assumption and merely Asserted it, rather than handling the alternative in release builds.

Clearly there is unnecessary cognitive overhead when working with `Var` return types on APIs we know to have guarantees on the type of their result values.  We should use specific return types for these APIs and only generalize to Var when necessary e.g. when the API is used as a JIT helper.

This issue recommends changing the following APIs and their dependencies to use `JavascriptArray*` for their return type rather than `Var`:

 - `JavascriptOperators::GetOwnPropertyNames`
 - `JavascriptOperators::GetOwnPropertySymbols`
 - `JavascriptOperators::GetOwnPropertyKeys`

Also #1251 `JavascriptConversion::ToPropertyKey` should return `void` instead of `BOOL`.

**Comment by jordonwii** [comment]
I likely won't have time for a few days, but I can take this one (and #1251), since they spun off of my PR.

**Comment by ianwjhalliday** [comment]
It's yours, have at :)

**Comment by ianwjhalliday** [comment]
*they're yours
