### ISSUE TITLE
Wasm f64.promote/f32 /w SSE1

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1268]
f64.promote/f32 with SSE 1 on x86 currently asserts.

**Comment by MikeHolman** [comment]
There will be a lot of cases where non-sse2 will fail for wasm (SSE2 was considered a requirement for asm.js). I think we shouldn't surface WebAssembly object to non-sse2 machines for now (and maybe ever).

**Comment by Cellule** [comment]
That sounds like a good idea for the time being, it'll make it easier to push features faster. We can revisit support for SSE2 at a later time.
