### ISSUE TITLE
Add native tests for new JSRT APIs

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1269]
https://github.com/Microsoft/ChakraCore/pull/1254 adds new JSRT APIs. Should add native tests for the following as per #1224 

```
JsInitializeModuleRecord
JsParseModuleSource
JsModuleEvaluation
JsSetModuleHostInfo
JsGetModuleHostInfo
```

@Yongqu @akroshg

**Comment by akroshg** [comment]
Over the time we have added few tests in the jsrtAPITest.cpp file.
