### ISSUE TITLE
Date.UTC should return NaN with < 2 arguments

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1318]
Currently, the spec says this behavior is implementation defined. We have decided that means to default these parameters to zero. All other implementations simply return NaN. I think we should align if possible and update the spec to mandate this behavior. Are there compelling reasons to keep our current behavior? It'd be a compat break for UWP/etc. but this behavior doesn't seem particularly useful so hopefully it's not used...

See also https://github.com/whatwg/javascript/issues/31

**Comment by dilijev** [comment]
I'll take a crack at this. :)

**Comment by claudepache** [comment]
> Date.UTC should return NaN with <= 2 arguments (?)

... with < 2 arguments (??)

**Comment by bterlson** [comment]
Uhh yeah, title is wrong (and so is PR). @claudepache you rock.

**Comment by dilijev** [comment]
@bterlson Yes, I was wondering about this aspect when I compared behavior with Chrome. The PR is easy to fix. I'll await concensus before making fixes.

**Comment by dilijev** [comment]
Note: TC39 did not reach a consensus on this and may not have a further decision for a while (see https://github.com/whatwg/javascript/issues/31). Still it seems worth changing to the implementation currently provided by the other browsers (return NaN for 0 or 1 argument).

**Comment by ianwjhalliday** [comment]
Agreed

**Comment by bterlson** [comment]
Agreed.
