### ISSUE TITLE
Regex/BoiHardFail.js fails on Fedora Debug Builds

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#1334]
Test does pass on test builds. On debug builds, we hit the following assert:

ASSERT [THREAD ] at ../../pal/src/thread/pal_thread.cpp.2858: Expression: status == 0, Description: pthread_getattr_np call failed

**Comment by digitalinfinity** [comment]
Note that this test passes on Ubuntu

**Comment by obastemur** [comment]
#1508 has fixed this one.

**Comment by obastemur** [comment]
P.S. Maybe we should set a lower FD limits on our CI since the fail here wasn't Fedora specific. It could perfectly fail with a similar FD limit on Ubuntu too. (default FD limit for Fedora 1024, Ubuntu 4096)
