### ISSUE TITLE
Update `Object.getOwnPropertyDescriptors` with spec changes

### ISSUE THREAD

**Issue by ljharb** [Microsoft/ChakraCore#1342]
Per https://github.com/tc39/ecma262/pull/593 - if the result of `[[GetOwnPropertyDescriptor]]` is undefined, it should *not* be stored on the returned descriptors object.

**Comment by ianwjhalliday** [comment]
> it should not _not_ be stored

@ljharb double not intentional or typo?  That is to clarify, you are saying it should be stored on the returned descriptors object?

fyi @jordonwii

**Comment by ljharb** [comment]
Typo, sorry - updated.

`undefined` descriptors must not be present on the return of `Object.getOwnPropertyDescriptors`.

**Comment by ianwjhalliday** [comment]
@ljharb cool

@jordonwii want to take this?

**Comment by jordonwii** [comment]
@ianwjhalliday Yep - it should be a straightforward change.
