### ISSUE TITLE
date.toLocaleString shows duplicate 月‎ character when 'month' is specified as 'long'

### ISSUE THREAD

**Issue by FireSlash** [Microsoft/ChakraCore#1351]
```
// IE11 / Edge
new Date().toLocaleString( 'Ja-JP',{ month: 'long', day: 'numeric' } );
"7月‎月‎27‎日"

// Chrome / Firefox
new Date().toLocaleString( 'Ja-JP',{ month: 'long', day: 'numeric' } );
"7月27日"
```
The second 月‎ is redundant.

This affects both IE11 and Edge. There are various permutations of this bug across Japanese and Chinese.

**Comment by bterlson** [comment]
I'm not seeing this in Edge 14 (and vaguely recall this getting fixed but I'm not finding the bug). What version of Edge are you testing with?

**Comment by FireSlash** [comment]
This was tested against Edge 13.

If this is already resolved in 14 then I'll go ahead and close this (and make a mental reminder to test against dev versions before filing bug reports)

Thanks!
