### ISSUE TITLE
ArchLinux undeclared identifier min / max

### ISSUE THREAD

**Issue by WebReflection** [Microsoft/ChakraCore#1352]
ArchLinux usually builds out of the box whatever other distro can build.

In this case there is a good old problem about undeclared identifier via mbstring
````sh
src/cruntime/mbstring.cpp:183:20: error: use of undeclared identifier 'min'
            ret += min(count, strlen((const char*)string));
```

It seems to be something related to the `clang` version which is currently `version 3.8.0 (tags/RELEASE_380/final)`.

Following the `uname`:
Linux localhost 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

All dependencies have been installed. Any way we can solve this?
AFAIK ArchLinux is the second most popular distro after Ubuntu, it would be great.

Thanks for any sort of hint or fix.

**Comment by obastemur** [comment]
@WebReflection are you using the `linux` branch or `master` AFAIK this problem was solved in `linux` branch

**Comment by WebReflection** [comment]
I've completely missed the `git checkout linux` point of [this list](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux)

I'll try again this evening and eventually reopen but I'm sure it'll be fine if it's something known.

Thank you.
