### ISSUE TITLE
Implement TypedArray updates to index handling

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1391]
[ECMAScript unified the handling](https://github.com/tc39/ecma262/pull/410) of indexes across all the TypedArray and related data structures. A number of minor semantics have changed.

**Comment by akroshg** [comment]
Isn't this the one what @ianwjhalliday is fixing?

**Comment by ianwjhalliday** [comment]
This looks like a superset of what I fixed.

I can revisit this later, or someone from the language team can pick this up and continue from my changes.

**Comment by dilijev** [comment]
Adding references to other issues mentioned: #2014 #2016

**Comment by dilijev** [comment]
Fixed by #2289, reverted by #2350

**Comment by atulkatti** [comment]
The PR #2350 only reverted some changes that may cause integer overflow. However, other spec changes for issue #1391 have not been reverted. So this issue can be closed.
