### ISSUE TITLE
[Slow] [Linux Branch] {x64,x86} x {debug,test} Test failure: TypedArrayPrototype

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1397]
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28linux%29#builds-with-slow-tests

```
16:19:06 1>ERROR: Test failed to run correctly: pass not found in output file ():
16:19:06 1>    ch.exe    -DumpOnCrash -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- -dynamicprofilecache:profile.dpl.UnnamedTest1675   -es6tostringtag -ES6ObjectLiterals -ES6Species -args summary -endargs D:\j\workspace\daily_slow_x8---e1770805\test\es6\ES6TypedArrayExtensions.js >testout1615 2>&1
16:19:06 1>ERROR: name of output file: D:\j\workspace\daily_slow_x8---e1770805\test\es6\testout1615; size: 350; creation: Fri Aug  5 16:14:58 2016, last access: Fri Aug  5 16:14:58 2016, now: Fri Aug  5 16:14:59 2016
16:19:06 1>ERROR: bad output file follows ============
16:19:06 1>*** Running test #12 (11): %TypedArrayPrototype%[@@toStringTag] behavior
16:19:06 1>Test threw exception: assert.throws failed: expected: TypeError 'this' is not a typed array object, actual: <no exception>: %TypedArrayPrototype%[@@toStringTag] throws TypeError if called with no parameter
16:19:06 1>FAILED
16:19:06 1>Summary of tests: total executed: 67; passed: 66; failed: 1
16:19:06 1>ERROR: end of bad output file  ============
```

How to repro locally: https://github.com/Microsoft/ChakraCore/wiki/Jenkins-Repro-Steps#windows-daily

**Comment by obastemur** [comment]
IMO the test failure here is related to how qsort is implemented.

See https://github.com/Microsoft/ChakraCore/blob/master/test/es6/ES6TypedArrayExtensions.js#L1434

Option A) implement cross platform qsort?
Option B) Accept this malformed test result applies to Windows only?

**Comment by ianwjhalliday** [comment]
The spec allows this sort to be implementation defined since the comparefn is inconsistent according to the rules specified in https://tc39.github.io/ecma262/#sec-array.prototype.sort

So we don't necessarily have to do option A.  On the other hand we don't have a nice solution to make a test OS specific at this level of granularity.  Maybe we need one, or maybe this particular test is not worthwhile.

**Comment by obastemur** [comment]
> So we don't necessarily have to do option A

@ianwjhalliday on (specs && logical part) side, I agree with you. 

IIRC qsort on unix etc. has deeper issues than not being compatible. Besides, now CC is cross platform, consistency on these stuff would (IMHO) improve UX/DX though.

For now #1455 is merged with a (optional/maybe) TODO comment on it.

@dilijev Thanks for bringing this and @ianwjhalliday Thanks for the review and details on spec!
