### ISSUE TITLE
[Question] Integration to node.js

### ISSUE THREAD

**Issue by Junkern** [Microsoft/ChakraCore#140]
The roadmap contains a point about the inclusion of ChakraCore to node.js. 
Do you already have a more specific ETA for that?

**Comment by mathiasrw** [comment]
:+1:

**Comment by kunalspathak** [comment]
We have sent out the PR few minutes back at nodejs/node#4765 . 
You can try the binaries from [here](https://github.com/Microsoft/node/releases).
