### ISSUE TITLE
Date.parse for dates like "Wed Jul 20 23:31:54 +0000 2016"

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1402]
Spidermonkey and V8 both support date formats like the in the subject.

Twitter is using this format on their mobile site with some UA strings so we should support it as well

**Comment by dilijev** [comment]
Is this something which we should expect could be added to the spec at some point?

**Comment by bterlson** [comment]
@dilijev Indeed, there is work toward such a thing: https://github.com/mrrrgn/proposal-date-time-string-format.

**Comment by bterlson** [comment]
@dilijev I wouldn't say this is "pending" anything or "spec changed" anything, yet. I didn't clarify but this bug is coming from the Edge folks who are seeing it in the wild. We should add support for this regardless of where the proposal ends up (and, certainly, the proposal should include this format).

**Comment by dilijev** [comment]
@bterlson fair enough. Compatibility is enough of a tag. I just wanted to track if this was related to an ES Spec change (possibly future).

**Comment by itszero** [comment]
Hello, do we have any plan to fix this in ChakraCore? Thanks.

**Comment by dilijev** [comment]
@itszero Unfortunately we're focusing hard on other priorities right now. I'll bring this up with the team and see if we can assign someone to it and dedicate it to a milestone.

**Comment by JeTmAn1981** [comment]
I'd like to help with this issue, but I'm not sure what part of the codebase actually needs updating.  Is there a main date parsing function that could be updated?

**Comment by obastemur** [comment]
@JeTmAn1981 bunch of the related stuff are under  `lib/Runtime/Library/DateImplementation`. Good luck! 👍

**Comment by JeTmAn1981** [comment]
Thanks, I had already poked around and landed on the DateImplementation, specifically the UtcTimeFromStrCore function which seemed to contain string parsing code.  I'm working on a refactor of some of that code which I'll need to complete in order to understand it properly before I could attempt to introduce additional functionality.  I'll submit the initial refactoring once I get it to past the tests.

**Comment by JeTmAn1981** [comment]
Does anyone have tips for the best ways to test out my code changes?  How can I run the tests that just cover the code I've made changes to before running the entire test suite (which takes quite a long time to run on my machine)?  I know there's a date folder in the test directory, but I don't know how best to use that data.  I can run something like the DateParse.js test script but that just produces an output of the testing results and I don't have any way of knowing how much of that output is actually correct.  Should I run the tests with the original binary and then diff the output results?

**Comment by dilijev** [comment]
You can run tests from a single directory like this:

`jenkins\testone.cmd x64 debug -dirs Date`

If you run a single test you can compare the output against the `.baseline` file listed for that test in rlexe.xml in each directory, in your example:

```
$ git grep -n -C 3 DateParse.js *.xml
test/Date/rlexe.xml-19-  </test>
test/Date/rlexe.xml-20-  <test>
test/Date/rlexe.xml-21-    <default>
test/Date/rlexe.xml:22:      <files>DateParse.js</files>
test/Date/rlexe.xml-23-      <baseline>DateParse_es5.baseline</baseline>
test/Date/rlexe.xml-24-      <!-- test is timezone-sensitive; remove exclude_jenkins after fix -->
test/Date/rlexe.xml-25-      <tags>exclude_jenkins</tags>
```

**Comment by suwc** [comment]
https://github.com/Microsoft/ChakraCore/pull/2044

**Comment by suwc** [comment]
Merged.
