### ISSUE TITLE
Function.prototype.call returns the function itself instead of the real return value

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/ChakraCore#1415]
I have convinced myself, that I am looking at an optimization issue in EdgeHTML 14. The most annoying part is, that it doesn't reproduce when the F12 tools are open.

I'm building an application including the new d3 version 4, angular2, and core-js' es6 modules (amongst other things). Everything is bundled with webpack. I have tried to reduce the problem by editing the webpack-generated JavaScript and removing some of the moving parts, but that seems to fix it. I'll try to describe my environment, some code snippets etc., but I wouldn't expect this to be easy to reproduce.

The problem appears in [the range function](https://github.com/d3/d3-scale/blob/master/src/continuous.js#L97), more exactly in the `range = slice.call(_)` assignment in the first branch. `slice` is imported from `array.js` and is just `Array.prototype.slice`.

The first three times this function gets called (when `arguments.length === 1`, an array with two elements), the `.call(_)` returns the expected copy of that array. The fourth time, `range` gets `function slice() { [native code] }` assigned instead.

With webpack in the picture, here is what the browser actually executes:

``` js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__array__ = __webpack_require__(22);

// […]

  scale.range = function(_) {
    return arguments.length ? (range = __WEBPACK_IMPORTED_MODULE_2__array__["a" /* slice */].call(_), rescale()) : range.slice();
  };
```

or my debug version:

``` js
  scale.range = function (_) {
      var result;
      if (arguments.length) {
          console.log('change!');
          console.log(range);
          range = __WEBPACK_IMPORTED_MODULE_2__array__["a" /* slice */].call(_);
          console.log(range);
          result = rescale();
      }
      else {
          result = range.slice();
      }
      return result;
  };
```

I have rerouted `console.log()` and `console.error()` to append the logs to a DOM element, so I have a chance to see what happened when I open the F12 tools after things blew up. The log is:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
change!
0,1
278.3333333333333,0
change!
0,1
0,885
change!
0,1
278.3333333333333,0
change!
0,1
function slice() { [native code] }
```

Continuing the program executing then runs into an exception when the `range` function is called without arguments:

```
TypeError: Object doesn't support property or method 'slice'
  at scale.range (…)
  at …
```

I have verified, that the webpack imported `slice` function is always the same.
I have tried to inline the webpack infrastructure, but that fixes the problem.
The same code works beautifully in Chrome.
The code works (much slower) when the F12 are open.

Help!

**Comment by dilijev** [comment]
@Tragetaschen would you mind providing a jsfiddle or some other mechanism by which we can run the full repro to confirm the issue (and later confirm whether we have fixed it)?

**Comment by Tragetaschen** [comment]
I was hoping for 'yeah, that's known problem x and a solution is in flight', but the second best thing is 'looks like an actual bug' so the time for the next steps is well spent.

I'll do my best to reduce it tomorrow.

**Comment by dilijev** [comment]
@Tragetaschen also, can your provide the OS version e.g. 10.0.x.y, Edge version e.g. 38.x.0.0, and EdgeHTML version e.g. 14.x?

**Comment by Tragetaschen** [comment]
OS:  1607 / 14393.51
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

This is WEIRD!
I have reduced the problem somewhat to the following entry point snippet from my webpack build:
```js
var platform_browser_dynamic_1 = __webpack_require__(184);
var AppComponent_1 = __webpack_require__(929);

var continuous = __webpack_require__(54)["a"]; // 1
var s = continuous().range([1, 0]); // 2
for (var i = 0; i < 96; ++i) // 3
    s.range();
platform_browser_dynamic_1.bootstrap(AppComponent_1.AppComponent, []); // 4
s.range([1, 0]); // 5
```

`var continuous` at (1) is d3's `continuous.js` default export, my AppComponent is as bare as it can get (see below), the call at (5) is my sentinel, that screws up the internal state or doesn't.

In that setup, all parts are still required:
When I remove the `range`-call at (2), it doesn't break.
When I do less than 96 calls to `range()` in (3), it doesn't break.
When I move the bootstrap call (4) to other positions (e.g. before the `for` loop or after (5)), it doesn't break. That means initiating the angular 2 `bootstrap` is currently a requirement to trigger this.

**Attachments**
```js
var __decorate = ... // TypeScript's standard function
var core_1 = __webpack_require__(0);
var AppComponent = (function () {
    function AppComponent() {}
    AppComponent = __decorate([
        core_1.Component({
            selector: 'app',
            template: '<div>Hello World</div>',
        })
    ], AppComponent);
    return AppComponent;
    var _a;
}());
exports.AppComponent = AppComponent;
```

**Comment by Tragetaschen** [comment]
It doesn't get better:

```js
// [...] webpack module infrastructure
var continuous = __webpack_require__(54)["a"];
var s = continuous().range([1, 0]);
for (var i = 0; i < 1000; ++i)
    s.range();
s.range([1, 0]);
```

I'm able to remove remove the `bootstrap` call at (4) (which kind-of removes the Angular dependency). Then, I have to increase the loop at (3) to 1000 to make it fail reliably.

I tried to narrow down that number, but when I thought I had a good pair I noticed that with each refresh of the page I get a different result: With a loop counter of 600, sometimes the sentinel at (5) breaks and sometimes it doesn't (about 50/50).

**Comment by Tragetaschen** [comment]
I have created https://github.com/Tragetaschen/ms-edge-d3-scale-issue-1415

I'm able to either fail (1000 iterations) or succeed (100 iterations) depending on what is active in `main.js`.

I have tried to reproduce this without without relying on `vendor.js` and webpack's `CommonsChunkPlugin`, but apparently, this file split seems to be a requirement as well.

**Comment by dilijev** [comment]
This sounds like it could be something weird happening with JIT, code size, or hosting.

Maybe @pleath and @yongqu could weigh in?

**Comment by Tragetaschen** [comment]
OS: 1511 / 10586.494
 Microsoft Edge 25.10586.0.0
 Microsoft EdgeHTML 13.10586

The application breaks the same as on my 1607 machine. I didn't fully verify that it's actually the same problem, though. On that machine, there is Firefox, that works just fine with my application.

**Comment by dilijev** [comment]
@Tragetaschen Thanks for the additional info!

**Comment by Tragetaschen** [comment]
How is this going to go forward?

I know it's a complicated thing to ask, but I would greatly appreciate a ball park estimate. I need to make a decision regarding my application how I'm going to proceed, and the decision varies depending on whether it's "a KB number on a Patch Tuesday" or "in the next OS update".

**Comment by dilijev** [comment]
Can't say for sure until we address the severity of the issue. Is it possible to re-write portions of your app to work around this issue?

**Comment by Tragetaschen** [comment]
If I have to (read "next OS update", I'll inline (parts of) the d3 code instead of letting it run through webpack. This seemed to circumvent this bug when I started to reduce the issue to the reproduction. This still is a sword of Damocles situation, though :)

**Comment by dilijev** [comment]
This looks to be a JIT issue. We are investigating.

**Comment by ccantill** [comment]
We've just spent most of today hunting this bug too. A quick workaround is to put the following snippet at the top of your page:

```
<script>
    Function.prototype.call = function(t) {
        return this.apply(t, Array.prototype.slice.apply(arguments, [1]));
    }
</script>
```

Whatever breaks 'call' seems to not affect 'apply'.

**Comment by rajatd** [comment]
@Tragetaschen, I'm looking into this right now. I was able to repro the issue on the OS build you were trying it on. However, it seems fixed in ChakraCore master. I'm trying to figure out what fixed it and when.

**Comment by rajatd** [comment]
Never mind that, it does repro in latest ChakraCore. I'm investigating.

**Comment by rajatd** [comment]
Ok, figured out the issue after some heavy-duty reducing - it is an issue in the inliner of the JIT when the target of a .call has a getter. We were ending up inlining the getter instead of its return value. 
@ccantill the issue does not repro with your snippet because of some restrictions on the inlining of .apply and its target.

I am hoping to have a fix out shortly.

**Comment by Tragetaschen** [comment]
That's awesome.

Any chance for a backport to 1607 or 1511? Any address for a bribery cake?

**Comment by EdMaurer** [comment]
This one will only flow out to future flights.

**Comment by dkent600** [comment]
@EdMaurer  What does that mean "This one will only flow out to future flights.".  Is that a reference to some release date?

**Comment by dilijev** [comment]
Closed because it was fixed in #1598 and there's nothing more to be done here. Only in future flights means Windows Insider Previews and future official releases will include this fix but already-released versions of Windows will not be patched (patches to released versions of Windows are typically security fixes only).

**Comment by jharris4** [comment]
I've just spent 2 full days debugging this exact issue with a d3 webpack-built app running in Edge 38.14393.0.0.

I tracked it down to d3-scale's setter function, which does this:

**Comment by jharris4** [comment]
So I guess there isn't a workaround for this issue other than getting a newer version of Edge?

What version of Edge will have #1598 incorporated?

**Comment by dilijev** [comment]
This is already present in Insider flights and will be available in the next major update to Windows 10 (RS2).

**Comment by jharris4** [comment]
Thanks, I actually download Windows 10 Preview and verified that Edge 15 does not exhibit the bug.

In case anyone's interested, I'm using the following in my code to fix the issue with Edge <= 14:

```
if (window && window.navigator && window.navigator.userAgent && /Edge\/1[0-4]\./.test(window.navigator.userAgent)) {
  // Fix for bug in Microsoft Edge: https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-246424339
  console.log('Applying function.call fix for Microsoft Edge <= 14');
  Function.prototype.call = function(t) {
    return this.apply(t, Array.prototype.slice.apply(arguments, [1]));
  };
}
```

**Comment by sberney** [comment]
I am running Edge 20.10240.17146, and am experiencing what I believe is a related issue: [one](https://github.com/systemjs/systemjs/issues/1182#issuecomment-297124028), [two](https://github.com/aurelia/framework/issues/227#issuecomment-297122244).

My project is closed source and depending on what exactly the program is doing, involving between 40,000 and 150,000 lines of JS code, so I'm not exactly sure what to suggest for repro. But if you haven't taken a look at the Aurelia thread before (two), there may be repro material there.

**Comment by dilijev** [comment]
@sberney Is there something preventing you from updating to the latest version of Windows 10?

**Comment by sberney** [comment]
It's not just my machine -- this was reported to me by QA and other channels. As far as I am aware, I have the latest version of Windows 10 Enterprise, although not the Developer Preview. (We can't ask our clients to install that.)

**Comment by digitalinfinity** [comment]
Hi @sberney- can you use the workaround provided by @ccantill (https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-246424339)?

**Comment by jharris4** [comment]
@sberney @digitalinfinity Better to use the modified version of the workaround that only applies it to Edge <= 14 as mentioned here: https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-287888807

**Comment by dilijev** [comment]
@sberney: My apologies. I didn't realize this would be deployed to machines running various versions of Windows 10. FWIW, Windows 10 Build 10240 is the first release of Windows 10 (1507). Since then we have released 1511 (November Update aka TH2), 1607 (Anniversary Update aka RS1), and the Creators Update aka RS2 -- rolling out now. So, you could update quite a bit farther along than the version you currently have installed and still not be on Insider builds. If you were able to get everyone updated to the Creators Update, where the bug has been fixed, you would be all set.

However, we understand that your app may be deployed and used by people using various versions of Edge and Windows 10, and it's not feasible to expect everyone to be updated to the latest version of Windows 10, especially in Enterprise environments. Therefore, we recommend using the workaround described above.

**Comment by sberney** [comment]
Thanks for the feedback; I've added the workaround.

@digitalinfinity I can't say it works definitively on every build until some bureaucracy happens, but I do believe it will work without issue.

These things are so hard to debug! I have to say, it doesn't make sense to me that a bug so big would not be patched. Thanks.

**Comment by mjoyce91** [comment]
Can confirm that the solution provided by @jharris4 resolves this issue for me in Microsoft Edge version number:

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

For me, the issue was having multiple d3 visualizations responding and recalculating based on changes. The more visualizations there were, the sooner the site would crash.

Thanks!
