### ISSUE TITLE
Add build and test logs archival for Linux and OSX Jenkins tasks

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1424]
Windows tasks archive build and test logs:
https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/x64_debug/

Linux and OS X don't have their jobs configured to collect logs from the correct locations so we're seeing no saved logs:
https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/shared_ubuntu_linux_debug/

**Comment by obastemur** [comment]
@dilijev the links are dead. A bit more detail on this please.

**Comment by dilijev** [comment]
@obastemur Sorry about that, you can look at any recent jobs from those configs. Updated above to point to the jobs' main pages.

As for the ask here, see: https://github.com/Microsoft/ChakraCore/blob/master/netci.groovy#L84

Basically it would be helpful to archive build and test logs for easier analysis of build failures. Currently we only have this configured for Windows builds. We need to set up an archival string which does the right thing for *nix/clang-based build and test outputs.

**Comment by obastemur** [comment]
@dilijev not sure what was this about. Close?

**Comment by obastemur** [comment]
Reminder, we have couple of other CIs we collect everything.

**Comment by dilijev** [comment]
Updated the links.

Logs can be archived from jenkins runs to make it easier to diagnose issues. We only do this on Windows. We should probably also do this for xplat builds.

**Comment by dilijev** [comment]
Note list of collected logs here:

![image](https://user-images.githubusercontent.com/494055/33053571-1bc79722-ce29-11e7-90b3-91bb745fb063.png)

No collected logs here:

![image](https://user-images.githubusercontent.com/494055/33053576-26986532-ce29-11e7-9374-242d686c62b3.png)

**Comment by obastemur** [comment]
how about https://github.com/CCRobot/TestResults/branches ?

**Comment by obastemur** [comment]
I'm going to close this one as we have some sort of log history for xplat. Improvements welcome
