### ISSUE TITLE
Wasm: Trunc/Nearest ChakraFull build failure

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1427]
It seems `trunc` and `round` are not available in the version of `math.h` we use in ChakraFull. See `GetNonTableMethodAddress` in JnHelperMethod.cpp
#1316 
I will be disabling the feature until we resolve the issue.

**Comment by arunetm** [comment]
This one is done. https://github.com/Microsoft/ChakraCore/pull/1519
We can close this issue.
