### ISSUE TITLE
documentation is broken

### ISSUE THREAD

**Issue by dimant** [Microsoft/ChakraCore#1428]
https://developer.microsoft.com/en-us/windows/iot/docs/StartCoding.htm and a whole bunch of other IoT doc pages are PageNotFound :(

**Comment by munyirik** [comment]
cc @ivorb
The site was reorganized and that broke a lot of links (and the old links don't redirect). Which page has that broken link?

The new link to IoT samples is: https://developer.microsoft.com/en-us/windows/iot/samples 
The new link to IoT docs is: https://developer.microsoft.com/en-us/windows/iot/Docs

**Comment by dimant** [comment]
I find it very difficult to find the docs I am looking for in the URL you
shared. Where do I find the new location for this information:
https://developer.microsoft.com/en-us/windows/iot/win10/lightningproviders

thanks,
Diman

**Comment by munyirik** [comment]
@msalehmsft where's the new page for lightning providers?

@ivorb could you fix the link? If I search for 'lightning' on the main page the first link is the broken link.

**Comment by obastemur** [comment]
@dimant thanks for reaching out and @munyirik thanks for following up.

Opened a new issue at https://github.com/ms-iot/content/issues/956

Closing this one from here as it is not related to ChakraCore.
