### ISSUE TITLE
compilation failed for code page issues

### ISSUE THREAD

**Issue by humeafo** [Microsoft/ChakraCore#1429]
chakra compilation failed on chinese version of windows 10 with vs2015 update3, following errors shown:

lib\Runtime\Library\JavascriptPromise.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

this can be seen in:

https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/JavascriptPromise.cpp

line 54:

// 3. Let promise be ? OrdinaryCreateFromConstructor(NewTarget, "%PromisePrototype%", «[[PromiseState]], [[PromiseResult]], [[PromiseFulfillReactions]], [[PromiseRejectReactions]], [[PromiseIsHandled]] »).

the "»" symbol make the compilation failed

so you can save the file encoded in UTF-8 or just remove the  "»" symbol

**Comment by ianwjhalliday** [comment]
I vote for removing the chevron symbol.
@humeafo have you made this change already and verified it works?  Feel free to submit a PR for it.

**Comment by humeafo** [comment]
yes, I tested after removing it then build succeeded. another solution maybe replace "»"  with ascii ">>".
