### ISSUE TITLE
ch.exe crashes when running "ch.exe -Dump:Encoder ..\..\..\..\test\benchmarks\Octane\pdfjs.js"

### ISSUE THREAD

**Issue by mcfi** [Microsoft/ChakraCore#143]
I observed ch.exe crashes when running "ch.exe -Dump:Encoder ..\\..\\..\\..\test\benchmarks\Octane\pdfjs.js". The crashes consistently happen regarding x64debug and x86debug builds.

**Comment by ianwjhalliday** [comment]
@LouisLaf

**Comment by mcfi** [comment]
Since I cannot send pull requests, I just paste the simple diff for fixing the issue. The fix does not cause any regression on unit tests. Please see below.

--- a/lib/Backend/Encoder.cpp
+++ b/lib/Backend/Encoder.cpp
@@ -547,7 +547,6 @@ void Encoder::TryCopyAndAddRelocRecordsForSwitchJumpTableEntries(
```C++
     }

     BYTE * jmpTableStartAddress = codeStart + codeSize - totalJmpTableSizeInBytes;
-    JitArenaAllocator * allocator = this->m_func->m_alloc;
     EncoderMD * encoderMD = &m_encoderMD;

     jumpTableListForSwitchStatement->Map([&](uint index, BranchJumpTableWrapper * branchJumpTableWrapper) -> void
@@ -575,8 +574,6 @@ void Encoder::TryCopyAndAddRelocRecordsForSwitchJumpTableEntries(BYTE *codeStart
         }

         jmpTableStartAddress += (jmpTableSizeInBytes);
-
-        BranchJumpTableWrapper::Delete(allocator, branchJumpTableWrapper);
     });

     Assert(jmpTableStartAddress == codeStart + codeSize);
```
