### ISSUE TITLE
Duplicate function declarations in blocks should throw early error in sloppy mode

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#144]
```js
{
    function foo() { }
    function foo() { }
}
```

Expected: Early syntax error. Actual: no error, second function wins always near as I can tell.

Duplicate function names are allowed at top level but not in blocks. Spidermonkey [came across web compat issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1235590) trying to implement this, so are going to go more slowly. V8 has it in Canary and will test out these semantics in their Beta channel. Hopefully if all goes well there we can fix this bug without worry.

**Comment by ajklein** [comment]
We ran into another compat issue with foxnews.com (serving Akamai's media player): https://code.google.com/p/chromium/issues/detail?id=579395

**Comment by ianwjhalliday** [comment]
Thanks @ajklein. @bterlson sounds like we should leave ChakraCore as is and TC39 should amend the spec.

**Comment by bterlson** [comment]
@ianwjhalliday Depends. I tend to think that not throwing an error here is bad for many reasons. If we are forced to support it due to web compat then we have no choice, but let's wait and see what data @syg's telemetry finds. Also perhaps Canary has telemetry enabled (@ajklein)? But I think it's safe to add ye olde pending TC39 consensus label :)

**Comment by bterlson** [comment]
Consensus is we must allow duplicate func decls in blocks sloppy mode. tc39/ecma262#400 proposes a spec fix for this, but this issue can be closed!
