### ISSUE TITLE
Windows 10 SDK version for ARM

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1448]
In our wiki to build arm we point to https://dev.windows.com/en-US/downloads/windows-10-sdk to download the sdk.
First of all, that page only show the latest SDK which we don't use, ChakraCore uses SDK 10.0.10240.0 (https://github.com/Microsoft/ChakraCore/blob/master/Build/Chakra.Build.Default.props#L6) and latest is 10.0.14393.0.
Not having the exact sdk version will make the compiler complain.

Also, when looking in the archive page https://developer.microsoft.com/en-us/windows/downloads/sdk-archive, I can't find the version we're using.
The versions I can find are
- 10.0.14393.0 (August 2016)
- 10.0.10586.0 (November 2015)
- 10.0.26624.0 (July 2015)

Where does version 10.0.10240.0 come from ?
I think we should either update our Wiki page to point directly to the right version of the sdk that we use and/or update the version that we use for something more recent.

**Comment by dilijev** [comment]
> 10.0.26624.0 (July 2015)

Where the heck did this version string come from...? Maybe it's a mistake in documentation, because I'd expect the version to match the July 2015 Windows 10 version (10.0.10240.0).

**Comment by Cellule** [comment]
@dilijev 
You're right, the July 2015 version is 10.0.10240.0
I tried to install it and everywhere it said `10.0.26624.0`, but once installed I checked and the install path is `C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0`
This is probably a problem in the Windows documentation.
Is there a way to report that?

Also, we probably should mention it in our wiki and point to the archive page instead

**Comment by ianwjhalliday** [comment]
I think 26624 might be the phone version, TH1 on mobile.  They may not have been able to sync version numbers until TH2, since TH1 mobile didn't make it to market.  This is just a guess though.

**Comment by dilijev** [comment]
@ianwjhalliday my understanding of the mobile versus desktop build number unification was that the 14000s were chosen as a number which was ahead of both systems' current numbers so they wouldnt go back, in which case 26xxx doesn't track, but I could be mistaken about that.

**Comment by Cellule** [comment]
I updated the wiki to point to the archive page and indicate that we should use version of July 2015 to avoid confusion with the version number
