### ISSUE TITLE
[FeatureRequest] Strong Mode

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/ChakraCore#146]
The V8 team have started looking in to a "Strong Mode" subsection of JavaScript (https://developers.google.com/v8/experiments). I was wondering if there are any plans to include this is in ChakraCore?

**Comment by ljharb** [comment]
big -1 unless it gains progress in the TC39 standards process. We wouldn't want another `Object.observe` on our hands.

**Comment by bterlson** [comment]
Strong Mode is very interesting, but is not something we would plan to include without seeing more work on prototypes and, especially, standardization. Strong Mode seems a long way off from this as yet AFAICT.

**Comment by SamuelEnglard** [comment]
Reasonable issues

**Comment by abchatra** [comment]
I am closing this issue for now until we have more concrete data on prototype\standardization.
