### ISSUE TITLE
Class expressions should be allowed in a member expression without parenthesizing

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1465]
```js
print(class foo { }.toString());
```
Actual: Syntax Error
Expected: `"class foo { }"`

**Comment by ianwjhalliday** [comment]
Appears that it is actually the call syntax that is causing the error.
`print(class foo { }.toString);`
parses fine and behaves correctly (printing the toString function object)

**Comment by ianwjhalliday** [comment]
Not sure why but the parser was written to explicitly disallow call syntax following a class expression.  Perhaps a copy paste error. Very easy fix. #1468
