### ISSUE TITLE
for-of loop incorrectly recognizes Expression grammar for iterable expression; should be AssignmentExpression

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#147]
See tc39/test262#473

For example this should be a `SyntaxError`:

```javascript
for (let x of 0, []) { }
```

**Comment by nicolo-ribaudo** [comment]
If none is working on this issue, I can do it.

**Comment by caitp** [comment]
Suggest renaming this issue to specify "for-of" loops, to avoid confusing those of us who see this in email and worry about someone possibly landing something that breaks the web =)

**Comment by ianwjhalliday** [comment]
Oops, thanks for catching that @caitp. Fixed

**Comment by ianwjhalliday** [comment]
@nicolo-ribaudo it's yours. Let me know if you have any questions about the parser.
