### ISSUE TITLE
What type is JsSourceContext on Unix?

### ISSUE THREAD

**Issue by Fishrock123** [Microsoft/ChakraCore#1474]
https://github.com/Microsoft/ChakraCore/wiki/JsSourceContext

```
typedef DWORD_PTR JsSourceContext;
```

is `DWORD_PTR` just `void *` or something?

**Comment by obastemur** [comment]
It depends to the ARCH, on x64 it is `unsigned int64`

See https://github.com/Microsoft/ChakraCore/blob/master/pal/inc/pal_mstypes.h#L331

**Comment by obastemur** [comment]
Alternative approach to finding a typedef in the code base is that; What we have on cross platform is equivalent to ones given on MSDN.
