### ISSUE TITLE
ENABLE_BACKGROUND_PARSING should probably be undefined

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#1478]
It appears that all of the code to support parallel parsing is compiled in. Is it supposed to be? My guess is no.

**Comment by Cellule** [comment]
It looks like we do
```
#if ENABLE_BACKGROUND_PARSING
```
and it is defined to either `0` or `1`.
I think the code is correctly removed for nojit build.

**Comment by curtisman** [comment]
The parallel parsing code wasn't under #if before.    It was added for the xplat effort so that we don't have to port it to Linux for now.  I don't think the #if will disable all of the code associated with background parsing.

**Comment by dilijev** [comment]
Looks like this question is answered, so I'm closing it. I think any work items related to this are already tracked in the xplat effort.
