### ISSUE TITLE
[JSRT] Use int index in JsGetIndexedProperty & co.

### ISSUE THREAD

**Issue by liminzhu** [Microsoft/ChakraCore#1486]
Array iteration is a fairly common action in JSRT and right now the way it's handled is kind of ugly, especially in [JsGetIndexedProperty](https://github.com/Microsoft/ChakraCore/wiki/JsGetIndexedProperty) and friends where I have to use  a JsValueRef typed index. This leads to extra JsIntToNumber calls from time to time. It'd nice if we can expose new APIs with just int index.

**Comment by dilijev** [comment]
Do you think this should be targeted at [Milestone 1.3](https://github.com/Microsoft/ChakraCore/milestone/2) or is it not necessary for it to go in before the release?

**Comment by liminzhu** [comment]
Not necessarily needed for 1.3. I just want to get this on our backlog.

**Comment by agarwal-sandeep** [comment]
@liminzhu do we plan to do more work for this?

//cc @kfarnung  @dilijev

**Comment by liminzhu** [comment]
Don't think anything is scheduled for the immediate future, but would still like to leave this open as a backlog item.

**Comment by rhuanjl** [comment]
@liminzhu I'd be happy to have a go at this sometime in the next week or two if wanted?

Thinking a JsGetIntIndexedProperty and a JsSetIntIndexedProperty or something like that? (names are ugly but can't see another option with JsGetIndexedProperty already taken).

**Comment by liminzhu** [comment]
Thx for offering to help @rhuanjl ! 

So I actually give it a little more thought. Though the current API is kind of inconvenient, it is easy to write a helper if I have to use it often, which leads me to believe it's not worth it to bloat the API surface for convenience alone.

I take a look at the [underlying implementation](https://github.com/Microsoft/ChakraCore/blob/2a25773b7b881cce292696acadb3ed09ab4859fd/lib/Jsrt/Jsrt.cpp#L2364) which also uses a var instead of an int so a naive implementation that takes an int instead will have to wrap it into a var and offers no perf upside as well. 

I'm going to close this issue until there's reason to reopen it.

**Comment by rhuanjl** [comment]
I was aware that OP_GetElementI used a Var index but...

There are some relevant internal ways of indexing via an int e.g.
https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/JavascriptArray.cpp#L2850-L2867

Would take a few lines of code to do right but could probably make a faster method if this is a slow path for anyone - but maybe not worth it really - happy to write the code if you decide you do want it.
