### ISSUE TITLE
Create label that indicates and encourages a new contributor to take on the issue

### ISSUE THREAD

**Issue by rwaldron** [Microsoft/ChakraCore#151]
This was originally mentioned by @caitp [here](https://github.com/Microsoft/ChakraCore/issues/27#issuecomment-172001001) and @bterlson added the "Accepting PRs" label, but I think an additional label that both indicates _and_ encourages a new contributor to dig in would be a helpful distinction. There are many different ways this label is written, a quick ask on Twitter came up with:

- starter
- easy win
- first-timers-only (which has a website: http://www.firsttimersonly.com)
- easy, moderate, hard (which is actually three labels)
- your-first-pr (this was recommended by @ashleygwilliams who I regard as a leader "opening up" open source)

And many others.

**Comment by dilijev** [comment]
@rwaldron as for http://www.firsttimersonly.com, it links to http://up-for-grabs.net/ which we're a part of (using the `Accepting PRs` label): http://up-for-grabs.net/#/tags/chakra. I'm personally open for changing the name of that label or adding a new one. It's fairly easy to update the label that is used for that website.

**Comment by ljharb** [comment]
("good first task" is another possibility). I think that "Accepting PRs" and something like "your-first-pr" should be two separate labels - because there's a difference between the skill level required.

huge +1 for this idea

**Comment by ashleygwilliams** [comment]
completely agree that `PRs-welcome` and `your-first-pr` should be separate.
i also recommend defining them in `CONTRIBUTING.md`, a la https://github.com/npm/docs/blob/master/CONTRIBUTING.md

some reasoning behind the `your-first-pr` label:

- positive, not negative. not all people new to open source are new to programming. `beginner` is, sadly a perjorative term in the industry still.
- works for both new to project and new to OSS in general.
- using a pronoun makes it relatable, unlike `good-first-task` which isn't outwardly focused, could be construed as an internal label among existing contributors.
- no judgement. good/bad/etc regardless of tone convey judgement, which can dissuade beginners, who fear making mistakes

**Comment by dilijev** [comment]
@ashleygwilliams good points. Thanks for the feedback and suggestions.

**Comment by dilijev** [comment]
I looked into adding multiple labels to our listing on http://up-for-grabs.net/ and it doesn't look like that's supported right now. I opened a question there to ask how they recommend proceeding. https://github.com/up-for-grabs/up-for-grabs.net/issues/344

**Comment by dilijev** [comment]
CC @ianwjhalliday

**Comment by ianwjhalliday** [comment]
Sounds like a good idea.  Not sure what sorts of issues will be best for starters.  Minor syntax parsing issues in the front-end certainly.  Semantic error checking sometimes.  Minor bugs with trace and dump output. Runtime API bugs that are fairly obvious.

There are also then trivial issues that come up, house keeping stuff, or nice to haves like rename changes (e.g. #110).  Such issues to me don't feel substantial enough for someone looking to cut their teeth, but maybe they are still worthwhile to call out?  They would expose a new comer to building and running tests, and doing the PR dance with collaborators to get a change merged.

@ashleygwilliams @rwaldron what do you think about trivial issues?  Maybe I'm looking too far ahead and these sorts of issues are exactly what is good for a new comer?

**Comment by ashleygwilliams** [comment]
hey @ianwjhalliday i'd say try a few and see how it goes. often the need for a label emerges from experience. no need to make that label til you feel the pain of its absence IMO.

**Comment by ashleygwilliams** [comment]
fwiw, those "chores" are great first prs. remember: a first pr is often about the pr process and not the change itself.

**Comment by ianwjhalliday** [comment]
That makes sense.  I've added a `Your first PR` label and described this and the `Accepting PRs` label in CONTRIBUTING.md.  See PR #154.

Let me know what y'all think.

**Comment by rwaldron** [comment]
@ianwjhalliday @dilijev thanks for giving this as much attention as you did today! The new label and contributing.md notes hit the spot for me, but I'll defer to @ashleygwilliams (who knows more about executing on these plans than I do)

**Comment by ashleygwilliams** [comment]
:100: i think this is awesome (i left some notes on the PR w/language nits)

would like to reiterate how excellent the whole chakracore team has been about accessibility and inclusivity issues. not just great reactions to suggestions like this, but your pre-emptive work to make this a safe space. :clap: :clap: :clap:

**Comment by liminzhu** [comment]
Absolutely love the idea of another label indicating easy tasks for starters :+1: .

**Comment by ianwjhalliday** [comment]
@rwaldron @ashleygwilliams thanks for the gratitude.  We've been getting a lot of positive interest and a wonderfully warm welcome from the community.  It has been absolutely amazing and encouraging.  I for one am glad to be here.

I'll wrap up this issue shortly.

**Comment by ianwjhalliday** [comment]
Alright, we've got the new label and few issues labeled with it, and the CONTRIBUTING.md file is updated.  Thanks everyone for the good ideas!
