### ISSUE TITLE
WeakMap remove `.clear()`?

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/ChakraCore#1539]
Are there any plans to remove [`.clear()` from `WeakMap`](https://github.com/Microsoft/ChakraCore/blob/1f1164cd1bd38f91c2c42b1d10e16f8b9aa6a5b4/lib/Runtime/Library/JavascriptWeakMap.h#L66) to make the implementation compliant with the specification?  Other engines have removed it and aligned to the final spec.  Having deprecated/removed API isn't a zero sum game as it maintaining the feature in perpetuity can have future consequences and developers can latch onto functionality that they shouldn't.  Wouldn't it be better to "break" anyone mistanklingly using this API now than in 10 years.

I would have also assumed by the nature of the ECMAScript WeakMap that there could be an optimisation by not having to track the pointers in the map directly in the WeakMap to support clear, making the GC algorithm/detection more efficient.

**Comment by bterlson** [comment]
I didn't think this was actually exposed to script so it might be dead code? Can't confirm at the moment though...

**Comment by ianwjhalliday** [comment]
This `Clear` method is not exposed to JavaScript.  It is used by the WeakMap finalizer to remove all of its references from the key objects when the WeakMap itself is garbage collected.
