### ISSUE TITLE
[cross-platform] Improve '--no-icu' option

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#1549]
We now have `--no-icu` option to compile ChakraCore without `icu` dependency.

At the moment, ChakraCore `no-icu` option fails on unicode tests and the expectation is to make them passing.

Steps to reproduce:

```
./build.sh --no-icu --debug
test/runtests.py -d
```

**Comment by obastemur** [comment]
Remaining test cases;

```
es6/unicode_idDeferParseFunctions_utf8.js
es6/classes_bugfixes.js [ 2 fails ]
es6/unicode_6_identifiers_utf8.js
es6/normalize.js
Strings/unicode_toUpperCase_toLowerCase.js
```

**Comment by obastemur** [comment]
#4285 fixes `Strings/unicode_toUpperCase_toLowerCase.js` and makes `no-icu` testable.

**Comment by jackhorton** [comment]
Closing this since we have --no-icu in CI now.
