### ISSUE TITLE
External script using

### ISSUE THREAD

**Issue by oguzhankarsli** [Microsoft/ChakraCore#1557]
Hi, 
I'm working on ChakraCore, I aim that  using external script library which are like jquery.js, underscore.js,angular.js... 
Before external script loads to context or any variable, after running script use this library. 
Can my coding  invoke external library function?  How can I code this case,
help me please??

**Comment by obastemur** [comment]
We have a similar implementation under ChakraCore cli. See our LoadScript implementation from https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp#L237

**Comment by oguzhankarsli** [comment]
Thank you. I forgot to define our development language. We are using C# language. 
Please give me an example about this implementation with C# language. Is it possible with C#.

**Comment by obastemur** [comment]
@oguzhankarsli closing this for now. Feel free to open / comment if you have other questions. Thanks for bringing this up.
