### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by hiyelbaz** [Microsoft/ChakraCore#1560]
On Microsoft Edge, make a request to a http server (vert.x for me) and close the browser, you will get "An existing connection was forcibly closed by the remote host" exception. There is no issue with other browsers.

If you make two requests from seperate tabs and close just one tab nothing happens.
If you make two requests from seperate tabs and close Windows Edge you get two exceptions.

Can be related with non-closed connections on process exit.

**Comment by digitalinfinity** [comment]
Hi @hiyelbaz, thank you for reporting this issue. However, this sounds like an Edge issue, not a ChakraCore issue- can you please open an issue with them using the tool at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/.
