### ISSUE TITLE
OSX Non-Static CI Tests

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1562]
@digitalinfinity @obastemur 

@obastemur mentioned [here](https://github.com/Microsoft/ChakraCore-wiki/pull/12#discussion_r77953975) that `--static` is no longer required for OSX builds. Should I go ahead and add the non-static version of OSX builds to our CI checks?

@mmitche Just want to double check that we won't cause capacity issues if we double the load of OSX builds?

**Comment by mmitche** [comment]
Nope you're good

**Comment by obastemur** [comment]
Why don't we combine static and shared testing ? Once we compile for static or shared, the compile time for the other is lesser. 

- compile for static
- test
- compile for shared
- test

Otherwise; I'm afraid we will end-up having 100 checks around :)

**Comment by dilijev** [comment]
@obastemur I tend to agree with your concern about the seemingly rapid expansion of testing. I'm not sure I like having the two semantically different checks on the same check, but I see your point about reducing the runtime by a lot overall. Initially I think I'd like to keep them separate.

**Comment by obastemur** [comment]
@dilijev curious if there is any technical reason for it?

**Comment by dilijev** [comment]
@obastemur 
1. We already have a precedent for multiple builds: Linux and Linux (static)
2. Being able to quickly identify the build config which causes an issue is more valuable than the small amount of extra machine time we'll be using by having additional builds (I think @mmitche would agree but since he manages those resources I'll let him confirm).
3. It gets much more difficult to quickly track issues unique to one or the other if they are in the same build (only possible by looking into the logs directly).
4. Even though they look similar now, our priorities could change which would require us to add those builds back anyway.

Game theory TL;DR: No cost to keep them, potentially more cost if we get rid of them.

**Comment by obastemur** [comment]
Using current testing design we are already unable to test many build flags. I'm not saying lets test everything together. However we may better separate the tests for other flags.

At the moment, we reset CMake cache among the static and shared builds as well as other related flags. IMO, separating shared and static builds no longer useful

**Comment by tcare** [comment]
@obastemur can you provide an example?

I agree that identifying the config quickly is paramount. I don't like to pre-optimize too much here, if we have a need to conserve build resources or we have a case we don't cover with the separated config then we can create a combined one.

**Comment by obastemur** [comment]
We have multiple `icu` options. Soon other archs (x86, arm, arm64..) and JIT

x86, amd64, arm, arm64
interpreterOnly, both, both, ?
static/shared
test/release/debug
icu_sys/no_icu/embedded
osx/ubuntu

I calculate over 250 runs for the cases above under the current approach.

Using the proposed approach below, the number reduces to 40+ runs. (and we cover wider set of tests)

**Debug_x64
Test[x64][Static][ICU-SYS] -> Test[x64][Shared][ICU-SYS] -> Test[x64][Static][ICU-Static]

Sampling with a bash script;
```
ERR_CHECK() { if [ $? != 0 ]; then; exit 1; fi; }
echo "Testing Static SYS_ICU"
./build.sh --static --debug --icu=.... --arch=x86_64
ERR_CHECK
./test/runtests.sh
ERR_CHECK
rm -rf BuildLinux
echo "Testing Shared SYS_ICU"
./build.sh --shared --debug --icu=.... --arch=x86_64
ERR_CHECK
./test/runtests.sh
ERR_CHECK
rm -rf BuildLinux
echo "Testing Static Embed_ICU"
./build.sh --static --debug --embed-icu --arch=x86_64
ERR_CHECK
./test/runtests.sh
```

Total running time is also better; 
- Do not clone multiple times
- Do not wait for the same resource for utilization or to reset

** `rm -rf BuildLinux` is not necessarily needed due to `cache cleaning` approach we have with our CMake script. However,  we may fail to clean the cache over time and miss a critical problem.

*** This also changes the organization for error reporting to current vulnerable places (i.e. other arch and JIT) We work on these new parts and it is expected to have more failure on these comparing to `static/shared` differences. So, separating them into different test groups makes more sense to me.

**Comment by obastemur** [comment]
We were discussing this offline with @digitalinfinity and @jianchun 

It is okay if we totally skip testing [static/shared] [icu_sys/embed/non] on each debug/test/release options. Instead static with `test`, shared with `debug` etc. approach sounds sufficient for Jenkins.

We will have the rest covered under nightly tests. As of the `non-static` `osx` CI tests, we may better enable it for current `osx-static-test` run. So the actual `osx-static-test` run will be `osx-shared-test` and we won't be testing `static` `test` runs on macOS.

Any concerns on this?

**Comment by dilijev** [comment]
@obastemur I see the concern about 250 builds. I think we can distill a set of builds which is really valuable for each PR and run each specific configuration individually in the dailies, although I still concede that 250 is pushing beyond a reasonable maximum.

If we really intend to support all of those build permutations, we should make sure we support them whether we chain multiple configurations into a single build or not, especially in dailies.

The PR checks are intended to detect likely problems, so if we can reduce the set of builds on a PR to the set most likely to detect all classes of problems, I'm okay with that.

**Comment by dilijev** [comment]
To be clear, I propose this:

PR checks: minimal set of builds likely to detect problems (chaining multiple configs per build task or not is simply a matter of configuration)

Daily checks: ALL build permutations should be exercised (chained or not)

**Comment by tcare** [comment]
^^ Agree with Doug.

Unless we have a problem with lots of checkins breaking a combination of build configurations, they are safe to be run as nightly. Chaining some of the less common ones is also fine.

We can also just run some configurations for branches that are likely to break them e.g. xplat.

**Comment by dilijev** [comment]
@tcare for the moment, cross-plat work is stable enough and we have the checks in master so xplat work will continue directly against master unless there is a need to split it off again. We should be planning the future of checks for master rather than a special case branch, until the need for such a branch is clear.

**Comment by obastemur** [comment]
@dilijev @tcare can we close this now?
