### ISSUE TITLE
F12 dev tools for ChakraCore

### ISSUE THREAD

**Issue by Kureev** [Microsoft/ChakraCore#1563]
Hey,

I'm wondering if it's possible to use F12 debug tool for debugging a desktop application (OSX) with ChakraCore on board

**Comment by dilijev** [comment]
F12 Dev Tools are a part of Edge and are designed for debugging web pages in Edge. If you just need to debug the JavaScript in a desktop application, there might be other options available. Can you tell us more about the desktop application you're running?

**Comment by dilijev** [comment]
@agarwal-sandeep who is working on Jsrt Debugging APIs who might have some context.

**Comment by Kureev** [comment]
@dilijev I'm just playing around with ChakraCore (building a simple bridge to manipulate OS X UI using JS). Would be nice if at some point it'll be possible to use some external tools for debugging JS code in apps with embedded ChakraCore.

**Comment by dilijev** [comment]
We're interested in improving this as well, although we don't have a firm plan of the exact approach. Ideally, we'd like something like the debugging experience for any other executable (e.g. by using lldb and enabling it via a plugin to have specific knowledge about the JS frames). If you work hard enough to understand what the engine is doing, a normal debugger can still be useful as long as you have the debug symbols from the binaries you're linking against.

But that's an engine-execution-level debugging experience (which is more useful for developing Chakra than for debugging JS code assuming there are no bugs in the engine which are getting in the way), so it's definitely understandable to want a script-level debugger. Again, no firm plans for that.

**Comment by pallammadhukar** [comment]
Hi,
Is this is possible now "external tools for debugging JS code in apps with embedded ChakraCore in Desktop application?"

I am trying to debug Javascript of windows desktop application in Windows Machine?

Thanks,
Pallam
