### ISSUE TITLE
JsCallFunction's arguments offset(?)

### ISSUE THREAD

**Issue by Kureev** [Microsoft/ChakraCore#1572]
Hello, world!

I'm experiencing a bit weird behavior. My case is about invoking a callback function:
```js
Native.foo(function bar(p) {
  return p;
});
```
As you may guess, `Native` is a host object with a custom `foo` function as a callback parameter. I want to invoke this function with a text "test":

```objc++
JsValueRef foo(JsValueRef callee, bool isConstructCall, JsValueRef *arguments, unsigned short argumentCount, void *callbackState) {
  JsValueRef val;
  JsValueRef undefined;
    
  JsGetUndefinedValue(&undefined);
  const char *text = "test";
  JsPointerToStringUtf8(text, sizeof(text), &val);
    
  JsValueRef args[] = { undefined, val };
  JsErrorCode error = JsCallFunction(arguments[1], args, sizeof(args) / sizeof(*args)+1, &result);
}
```
This code works on my OS X, although I don't get why I need to access arguments from index 1 (what's wrong with 0?) and supply index 0 (it should be a JsValueRef with a proper value) for my `args` object that I construct to pass into callback function. It took me quite a while to grasp what I do wrong (there is a pretty big room for documentation improvements).

**Comment by liminzhu** [comment]
Index 0 is for thisArg like when you call [Function.prototype.call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call). It was documented in the [remarks](https://github.com/Microsoft/ChakraCore/wiki/JsCallFunction#remarks) for `JsCallFunction`. I am adding a similar remark entry for [JsNativeFunction](https://github.com/Microsoft/ChakraCore/wiki/JsNativeFunction).

**Comment by Kureev** [comment]
Thanks for this clarification!

Although I tried to find some info about it (fn's `arguments` parameter), but no luck so far. Is it an engine-specific thing (to pass `thisArg` as a first one) or a standard I'm not aware of? I assume that the reason of my confusion is a "standard" behavior of this object in the browser: arguments[0] returns me a first parameter I passed into the function, not `thisArg`.

**Comment by liminzhu** [comment]
Np!

Native binding is engine-specific, though other engines may do similar things. JsCallFunction is just mimicking Func.proto.call so taking a thisArg makes sense if you think about it that way. I totally see how you got confused though, I had the same confusion when I first played around JSRT so I added that remark that I pointed you to.
