### ISSUE TITLE
[Question] Making host object model available in JS

### ISSUE THREAD

**Issue by talentimo** [Microsoft/ChakraCore#1573]
How does one use the Jsrt API to connect to an external object model?  The Chakra Edge version has minimal support for this in that it allows a COM object (in a VARIANT) as a value, however this appears to have been removed from ChakraCore and I can't see any equivalent object interface.  I see a few references in the ChakraCore source code to hooks for calling hosted objects, but these appear not to be used in the current version.

I have a technical application that has made use of the old IE JS engine. We have a large object model implemented as a set of COM objects.  I would prefer to update to ChakraCore for obvious reasons, but I need the ability to use external objects.  A COM interface would be great but any equivalent object structure is fine.  Am I missing something?

**Comment by liminzhu** [comment]
Thanks for asking @talentimo . As you said we removed the COM interface projection in ChakraCore as in general we leave all Windows platform specifics behind in Chakra. However, you can still use [external](https://github.com/Microsoft/ChakraCore/wiki/JsCreateExternalObject) [objects](https://github.com/Microsoft/ChakraCore/wiki/JsGetExternalData) to project your object model (though you may have to change some of your code this way). Check out the code [sample](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/OpenGL%20Engine) (esp. this [file](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp)) to see how opengl stuff is projected into JS-land. 

An alternative is to [update](https://msdn.microsoft.com/en-us/library/dn903710.aspx) your old IE JS engine with the latest Chakra if you/your clients are on Windows 10. You get the same language support (ES6, ES7, etc.) and performance as ChakraCore, but you'll rely on Windows updates to update Chakra.

**Comment by dilijev** [comment]
Looks like this question is answered. Closing this issue.
