### ISSUE TITLE
Wrong string encoding/decoding

### ISSUE THREAD

**Issue by Kureev** [Microsoft/ChakraCore#1589]
Hi again,

I think I found a bug:

```c++
const char *initialString {"989F2EAE-123B-44E5-B437-7E3BB923A611"};

std::cout << "Initial string is: " << initialString << "\n";

JsValueRef uuid;
JsPointerToStringUtf8(initialString, sizeof(initialString), &uuid);

char *decodedString;
size_t length;
JsStringToPointerUtf8Copy(uuid, &decodedString, &length);

std::cout << "Decoded string is: " << decodedString << ", length is: " << length << "\n";
```

On my machine, the output is:
```
Initial string is: 989F2EAE-123B-44E5-B437-7E3BB923A611
Decoded string is: 989F2EAE, length is: 8
```

Seems it shrinks initial input while converting. I'd like to send a PR, could you be so kind to point me the place where I can fix it (I'm not familiar with ChakraCore yet)?

**Comment by liminzhu** [comment]
`strlen` instead of `sizeof` would give you the correct length in the `JsPointerToStringUtf8`.

**Comment by Kureev** [comment]
<details>
![image](https://cloud.githubusercontent.com/assets/2273613/18603543/bcbaed46-7c72-11e6-85a3-1861c98b6a36.png)
</details>

Indeed, sorry
