### ISSUE TITLE
xplat: enable jit on OSX

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#1595]
I read that __register_frame/__deregister_frame on OSX works differently than Linux. On Linux they take full ".eh_frame", but on OSX they take 1 FDE. Needs to verify and fix accordingly to turn on jit on OSX.
#1591 builds with `--no-jit` and runs `disable_jit` test variant on OSX.

**Comment by jianchun** [comment]
@obastemur

**Comment by jianchun** [comment]
@obastemur Let me try to tackle this first.

**Comment by jianchun** [comment]
@obastemur already started, assign back

**Comment by obastemur** [comment]
JIT is enabled on OSX, closing.
