### ISSUE TITLE
xplat: Fix absolute addressing issue [clang] [x86]

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#1596]
Code signed PIE but used in Js::ScriptContext::ProfileModeDeferredParsingThunk::RecyclableObject::CallInfo

**Comment by jianchun** [comment]
Is that "script profile mode" which we turned off? If so we may try fix some ifdef to not use it.

**Comment by obastemur** [comment]
> Is that "script profile mode" which we turned off? If so we may try fix some ifdef to not use it.

@jianchun no actually. This **was** an xcode compile time issue on macos side. 

Since then we made some code cleanup and general updates. 
This issue no longer exist.
