### ISSUE TITLE
window.location.origin cannot be accessed

### ISSUE THREAD

**Issue by ask4answers** [Microsoft/ChakraCore#1600]
IE version 11.0.10240.17113 (Update versions: 11.0.35 (KB3185319)) - window.location.origin can no longer be accessed (it works on an earlier build). We use it to construct links on our app so obviously they no longer work.

**Comment by liminzhu** [comment]
Hi @ask4answers. This repo is for the development and discussion of the ChakraCore JavaScript engine. Please file any Edge/IE issue using the [EdgeHTML issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).
