### ISSUE TITLE
Feature Request: Implement char16_t and char32_t functions.

### ISSUE THREAD

**Issue by kphillisjr** [Microsoft/ChakraCore#1614]
## OverView

This is mainly a request to implement a some new language features found in the C++ 2011 and C 2011 specifications. These data types are useful in  cases where the application embedding the JavaScript Runtime is C++11 aware. These data types can also be used to help access standardised methods to convert between data types. The current Wide character (wchar_t) [1] is a redefinition away from whatever the current environment supports. This could cause unexpected behavior because platforms can expect this data type to generally range anywhere from 8-bits to 32-bits. This generally leads to a lot of portability problems. This Feature request is fairly straight forward in Implementation on platforms implementing the current standard, and can be safeguarded when on a platform not supporting these features.

[1] [Wikipedia: Wide character](https://en.wikipedia.org/wiki/Wide_character)
### UTF-16 charaters sequences ( char16_t )

If `__STD_UTF_16__` is defined, The native c/c++ library definition for char16_t is used. If `__STD_UTF_16__` is not defined, this data type will instead be defined as int16_t.
### UTF-32 character (char32_t)

If `__STD_UTF_32__` is defined, The native c/c++ library definition for char32_t is used. If `__STD_UTF_32__` is not defined, this data type will instead be defined as int32_t.
## New Error Code

**JsErrorNotSupported** is a generic error code for when the current Chakra runtime cannot handle the request due to the build options. For example error is returned when the c/c++ library does not support the char32_t and/or char16_t data types, and an application tries to call a function that expects these data types.
## New Functions

There is a lot of new functions in this request. In general these functions are simply a one to one map to the original function with the main difference being that these functions expect char16_t (for UTF-16 Functions), and char32_t (for UTF-32 functions).

| Original Function | UTF-16 Function [1] | UTF-32 Function [2][3] |
| --- | --- | --- |
| JsRunScript | JsRunScriptUtf16 | JsRunScriptUtf32 |
| JsSerializeScript | JsSerializeScriptUtf16 | JsSerializeScriptUtf32 |
| JsRunSerializedScript | JsRunSerializedScriptUtf16 | JsRunSerializedScriptUtf32 |
| JsGetPropertyIdFromName | JsGetPropertyIdFromNameUtf16 | JsGetPropertyIdFromNameUtf32 |
| JsDiagEvaluate | JsDiagEvaluateUtf16 | JsDiagEvaluateUtf32 |
| JsParseScript | JsParseScriptUtf16 | JsParseScriptUtf32 |
| JsParseScriptWithAttributes | JsParseScriptWithAttributesUtf16 | JsParseScriptWithAttributesUtf32 |
| JsStringToPointer | JsStringToPointerUtf16 | JsStringToPointerUtf32 |
| JsPointerToString | JsPointerToStringUtf16 | JsPointerToStringUtf32 |
| JsGetPropertyNameFromId | JsGetPropertyNameFromIdUtf16 | JsGetPropertyNameFromIdUtf32 |
1. UTF-16 Functions return JsErrorNotSupported only when the C/C++ Library does not define `__STD_UTF_16__`. By default support for these functions are enabled as long as the C/C++ library has char16_t support.
2. UTF-32 Functions are disabled by default.
3. UTF-32 Support can be enabled if the C/C++ library defines `__STD_UTF_32__`, and the Chakra library is built with UTF-32 support enabled.

**Comment by digitalinfinity** [comment]
Thanks @kphillisjr! cc @jianchun @obastemur @curtisman @liminzhu who have also been thinking about how to evolve the JSRT string APIs. The current thinking involves adding support for just Utf8 strings (so a caller would pass in a byte array representing the utf8 encoded string). Are there platforms where this would not be ideal? Are there particular scenarios you have in mind where, for instance, UTF-32 strings would be the most convenient way of interacting with JSRT?

**Comment by obastemur** [comment]
Indeed it is a nicely detailed issue, Thanks @kphillisjr 

IIRC, the core advantage of UTF16 over UTF8 is supporting code points outside of the BMP. IMHO, they are rare and a third party library or API can take care of the UTF8 <-> UTF16/32 conversions.

However, the problem we might have right now can be tricky. Curious; if the current interface would behave to those rare code points properly on xplat. AFAIK, we don't have such issue on Windows. 

So, on XPLAT, where and how the app would fail would be my question?

**Comment by kphillisjr** [comment]
@digitalinfinity
> Are there platforms where this would not be ideal?

Not really... It should be possible to use these functions with a copy of ICU, and possibly implementing functions to convert to the native wchar_t data type.

> Are there particular scenarios you have in mind where, for instance, UTF-32 strings would be the most convenient way of interacting with JSRT?

Most developers will use the UTF-16/UTF-8 api. The UTF-32 API is for cases where the developer use CJK Unified Ideographs[1].

@obastemur
> So, on XPLAT, where and how the app would fail would be my question?

I do not believe there is any major problems on XPLAT. The solution is to use the ICU Project[2]. Also if You did not know the ICU Project joined the Unicode Consortium[3].... Actually this would probably be the best solution since all platforms could use the ICU to convert the from char16_t or char32_t to the native copy of wchar_t.

[1] [Wikipedia: CJK Unified Ideographs](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs)
[2] [ICU - International Components for Unicode](http://site.icu-project.org/)
[3] [The Unicode Blog: ICU joins the Unicode Consortium](http://blog.unicode.org/2016/05/icu-joins-unicode-consortium.html)

**Comment by obastemur** [comment]
> I do not believe there is any major problems on XPLAT. The solution is to use the ICU Project[2]

Actually we use it and have a very good coverage. Yet, I'm not as confident as CC Unicode support on Windows as it is battle tested there. (CC - Edge / Global Windows Users)

The problem I have pointed out is slightly related to public API. Our current XPLAT interface accepts UTF8 and we might miss-place couple of things because of an unsupported encoding.

I'm not sure if we have any short term intention for going beyond char16 though. FWIW, we would like to extend our capability on handling utf8 better and better.

**Comment by kphillisjr** [comment]
@obastemur 
> Actually we use it and have a very good coverage. Yet, I'm not as confident as CC Unicode support on Windows as it is battle tested there. (CC - Edge / Global Windows Users)

Truthfully, the only reason CC Unicode has extreme confidence is that CC only runs in little endian mode.

> The problem I have pointed out is slightly related to public API. Our current XPLAT interface accepts UTF8 and we might miss-place couple of things because of an unsupported encoding.

Generally speaking the misplaced items are most likely going to happen when converting between big endian and little endian.

> I'm not sure if we have any short term intention for going beyond char16 though. FWIW, we would like to extend our capability on handling utf8 better and better.

Truthfully char32_t is meant to be an internal API, and can be used in places where you  need to convert between UTF-8 and UTF-16.

**Comment by kphillisjr** [comment]
I just realised that I forgot to mention standardized functions that will help simplify some of the current compatibility issues.

Function | Header File | Standard | Description
------------ | ------------- | ------------- | -------------
c16rtomb | uchar.h | C11/C++11 | Convert from char16_t to multi-byte character.
c32rtomb | uchar.h | C11/C++11 | Convert from char32_t to multi-byte character.
mbrtoc16 | uchar.h | C11/C++11 | Convert from Multi-byte characters to char16_t.
mbrtoc32 | uchar.h | C11/C++11 | Convert from Multi-byte characters to char32_t.
mbtowc   | wchar.h| C99/C11/C++11 | Convert from multi-byte character to wchar_t.
wctomb   | wchar.h| C99/C11/C++11 | Convert from wchar_t to multi-byte character.

NOTE: To get a general idea as to where the the C++ language support status is, you can look at the C++ Reference website on the page entitled "[C++ Compiler Support](http://en.cppreference.com/w/cpp/compiler_support)".  Also This table can be used to figure out where the C++11 support stands between platforms/compilers...

Compiler | C++ Library | Platform(s)
------------ | ------------- | -------------
Visual Studio 2015 | N/A | Windows 
clang 3.3 | Varies[1] | Linux, Windows, OSX.
GCC 4.8.1 | N/A [2]| Linux, Windows, OSX.
Intel C++ 15.0 |  N/A [3] | Linux, Windows, OSX

[1] Clang can handle C++11, but the C++ ABI could cause problems depending on system configuration. For full C++11 support a system needs the minimum library versions of libstdc++ from gcc 4.8.1, or libc++abi version 3.3.

[2] This should work fine as long as your using the bundled C++ Library.
[3] This should work, but I would still check this compiler's Documentation. Most likely this has the same restrictions as Clang does.

**Comment by dilijev** [comment]
This discussion has stalled, so I'm closing it. Thank you for the detailed suggestion. For now we're planning on focusing on evolving ChakraCore to handle UTF-8 more cleanly as it is the most common data format seen on the web and a generally more compact encoding and keeping our internal (and externally observable) UTF-16 behavior as needed to support spec semantics.

/cc @kfarnung @agarwal-sandeep
