### ISSUE TITLE
Phase detection

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/ChakraCore#1628]
It would be nice if ChakraCore could detect phases of program execution and optimize accordingly.

I may be working on this for an academic project.

**Comment by liminzhu** [comment]
Would you mind elaborating more on what you mean by phases of program execution and giving an example of such optimization?

**Comment by DemiMarie** [comment]
By phases, I mean periods of time in which a program does similar things.
The optimizations that I am thinking of include recompiling code, such that
"serially monomorphic" code (code where a call site is polymorphic, but not
within the same period of time) is fast.

**Comment by liminzhu** [comment]
I see, this is an interesting idea @DemiMarie. The way ChakraCore is implemented - it uses a profiling interpreter that collects information while executing scripts, such as frequency of certain code paths (# of runs of functions, loop body, etc). The JIT compiler compiles hot code paths into native code based on assumptions made from collected info, and bails out back to the interpreter if such assumptions are invalidated. So in a way, if the program is within a "phase" of doing similar things (such as executing the same loop body), ChakraCore already knows and has a bunch of optimizations.

Specifically to the optimization you pointed out, the profiling interpreter/JIT compiler would take care of that. ChakraCore also has polymorphic inline cache, which stores the type information at call site for fast access. As polymorphic suggests, the inline cache even works when dealing with multiple types (given there aren't too many of them).

If you have more ideas for optimizations, we certainly welcome that 😄.

**Comment by MikeHolman** [comment]
@liminzhu I suspect we don't do a great job in cases like this, as we will eventually fall back to pretty generic version of such functions.

@DemiMarie I think this is an interesting idea, but it is a hard tradeoff to make so it would be good to see some cases where we are deficient today and phase detection would significantly improve code quality. But the mechanics are basically all available in the engine if you wanted to do this as an academic project. I guess the basic idea would be after some number of some certain types of bailout you decide there has been a phase change, reset some profile data so the interpreter will profile as monomorphic, and then trigger a rejit.

**Comment by dilijev** [comment]
This discussion has stalled, so I'm closing it. We are happy to reconsider this type of optimization if it targets a real-world use case where we are deficient.
