### ISSUE TITLE
Chrome can reconstruct Edge (javascript) Ranges, but not vice versa

### ISSUE THREAD

**Issue by gidmeister2** [Microsoft/ChakraCore#1632]
I have written code that saves information about a javascript range, and another routine that uses that information to re-create that range.
I find that when I save a range in Microsoft Edge, Google Chrome can reconstruct it.
However, the converse is not true.
When I save a range in Chrome, Microsoft Edge cannot reconstruct it.
My code does work.  If I use it in Edge exclusively, I can save and recreate ranges.  Likewise in Chrome exclusively.  And as I said, it can take a range that was saved in EDGE, and reconstruct it in Chrome, so it works partly cross-browser.  But only partly.  You can't do the reverse.  I'll add more info later.

**Comment by bterlson** [comment]
Are you talking about [this Range](https://developer.mozilla.org/en-US/docs/Web/API/range)? If so this is a browser API. You can search for an existing bug or file a new one on the [Edge bug tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).

**Comment by dilijev** [comment]
Hi @gidmeister2, following up with this issue - have you opened this bug in the Edge bug tracker? If so, can you link it here?

In any case, I'll close this issue soon because there's no action to take on our end.

**Comment by dilijev** [comment]
This is an Edge bug. Closing as External.
