### ISSUE TITLE
Implement global.global

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1658]
Global.global (eg. window.global in the browser, or this.global in ch.exe/etc) got stage 3 today. Let's get an implementation going!

Spec: https://github.com/tc39/proposal-global

**Comment by ljharb** [comment]
Ping! This would be great to get implemented ASAP.

**Comment by ljharb** [comment]
Please hold off on implementing this until a final location for the value is decided.

**Comment by ljharb** [comment]
This has now been renamed to `globalThis`. Will there be another version of Edge that includes ChakraCore? If so, it'd be great to ship this ASAP.

**Comment by rhuanjl** [comment]
I see no one is assigned to this - I could do it if wanted? (Will wait on a member of the CC team saying yes before I start though figure it will be very small, bulk of the work will be the tests)

**Comment by pleath** [comment]
That sounds great. No one is working on it on our side.
