### ISSUE TITLE
Reduce the logic in the Copyright Check

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#166]
In `jenkins.check_copyright.sh`, see the following line:

```sh
xargs -I % sh -c "echo 'Check Copyright > Checking %'; python jenkins.check_copyright.py % > $ERRFILETEMP; if [ \$? -ne 0 ]; then cat $ERRFILETEMP >> $ERRFILE; fi"
```

In PR #51 @goyakin suggested modifying this line like so:

> Did you consider using `||` instead of the `if` condition at the end? You can do:
>
> `python jenkins.check_copyright.py % > $ERRFILETEMP || cat $ERRFILETEMP >> $ERRFILE`
>
> instead.

Additionally, in `jenkins.check_copyright.py`, @goyakin recommended the following change:

```python
for x in range(0,len(copyright_lines)):
```

> Since we're using `x` to retrieve the next item from regexes, why not iterate through regexes using `for regex in regexes:` instead?

**Comment by Francososa** [comment]
Can I claim this issue?

**Comment by dilijev** [comment]
@Francososa you got it.
