### ISSUE TITLE
Proxies cannot be added to WeakMaps

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#1662]
``` js
let p = new Proxy({}, {});
let wm = new WeakMap();
wm.set(p, 1);
print(wm.get(p));

/*
┌─────────────────────┬───────────┐
│ chakra              │ undefined │
│ chakra-es6          │           │
│ chakra-experimental │           │
├─────────────────────┼───────────┤
│ d8                  │ 1         │
│ jsc                 │           │
│ sm                  │           │
└─────────────────────┴───────────┘
*/
```

**Comment by Yongqu** [comment]
Do we have the same problem with Map? I kinda remember something in this area. Maybe @ianwjhalliday remembers?

**Comment by ljharb** [comment]
This seems like it constitutes an "is proxy" check, which i believe is supposed to be impossible. Is this perhaps an important enough bug to be backported to all shipping versions with Proxy?

**Comment by jlowcs** [comment]
Apparently, no issue with WeakSet, nor with Map. Only with WeakMap.

http://codepen.io/jlowcs/pen/BLYjkw

**Comment by bterlson** [comment]
@ljharb: open to arguments, but my intuition is that it's not.

**Comment by ljharb** [comment]
@erights and @tvcutsem may have thoughts. I don't have a strong opinion here but it seems troubling to have browser versions with broken security invariants.

**Comment by erights** [comment]
Can't do membranes!

**Comment by akroshg** [comment]
This is due to not handling the InternalProperty for proxy object. I don't see any harm of storing this internal property on the Proxy object itself. I tried that and it works. I just need to understand this more why we didn't do that before. I couldn't find out from the spec on such restriction (as long as it is not modifying the target object why it cares.).

**Comment by akroshg** [comment]
It is fixed.
