### ISSUE TITLE
Date.UTC(x) [single-argument case] semantics update

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1665]
Behavior implemented in https://github.com/Microsoft/ChakraCore/issues/1333 is that `Date.UTC(x)` and  `Date.UTC()` where `typeof x === number` returns NaN.

Spec semantics will be updated (see https://github.com/tc39/ecma262/pull/642) so that `Date.UTC()` returns NaN and `Date.UTC(2017) === Date.UTC(2017, 0)`.

* 0-argument case works according to spec.
* 1-argument case needs to be updated.

See:
https://github.com/tc39/ecma262/pull/642
https://github.com/Microsoft/ChakraCore/issues/1318 (issue)
https://github.com/Microsoft/ChakraCore/pull/1333 (PR)

/cc @bterlson

**Comment by bterlson** [comment]
I think it's the reverse isn't it? Date.UTC() currently returns Date.UTC(0, 0, ...) and should return NaN. Date.UTC(2017) currently returns the right thing.

**Comment by dilijev** [comment]
I may have misspoken. Let's just make it explicit with tests:

```js
assert(isNaN(Date.UTC()), "expected: Date.UTC() is NaN");
assert(!isNaN(Date.UTC(2017)), "expected: Date.UTC(2017) is not NaN");
assert(!isNaN(Date.UTC(2017, 0)), "expected: Date.UTC(2017, 0) is not NaN;");
assert(!isNaN(Date.UTC(2017, 0, 1)), "expected: Date.UTC(2017, 0, 1) is not NaN;");
assert(Date.UTC(2017) === Date.UTC(2017, 0), "expected: Date.UTC(2017) === Date.UTC(2017, 0)");
assert(Date.UTC(2017, 0) === Date.UTC(2017, 0, 1), "expected: Date.UTC(2017, 0) === Date.UTC(2017, 0, 1)");
```

Actual behavior:

```
PASS
FAIL: expected: Date.UTC(2017) is not NaN
PASS
PASS
FAIL: expected: Date.UTC(2017) === Date.UTC(2017, 0)
PASS
```

Expected: all PASS

**Comment by bterlson** [comment]
Yes ok sorry. Seems good, thank you!
