### ISSUE TITLE
JsRT: When calling resolve, the resolve function is thrown if JsSetPromiseContinuationCallback hasn't been called

### ISSUE THREAD

**Issue by robpaveza** [Microsoft/ChakraCore#167]
Example case: 

``` js
(function() {
    var resolve, reject;
    var p = new Promise(function(res, rej) { 
        resolve = res;
        reject = rej;
    });

    p.then(function(val) {
        echo('The result is ' + val); // 'echo' is host-provided to output to console
    });

    try {
        resolve(10);
    }
    catch (ex) {
        echo('Failed to resolve: ' + ex.toString());
        echo(typeof ex);
    }
})();
```

If this code is evaluated and `JsSetPromiseContinuationCallback` has not been called, the failure case (`catch` branch) is invoked, and the following is output:

```
Failed to resolve: function() {
    [native code]
}

function
```

The thrown thing appears to be the resolve function itself instead of a meaningful error.  A meaningful error should be thrown instead, e.g., `TypeError: Promises may not be executed because the host has not provided a continuation callback in which to enqueue pending tasks.`

**Comment by liminzhu** [comment]
I agree. The current error is not pointing people at the right direction. @Yongqu would you mind taking a look?

**Comment by Yongqu** [comment]
Agree. It's a good error to have.
