### ISSUE TITLE
[CI] [Jenkins] Ubuntu build occasionally fails on dependency issue

### ISSUE THREAD

**Issue by MikeHolman** [Microsoft/ChakraCore#1678]
A few time I've seen ubuntu_linux_release_static fail with this same error (and pass after rerunning):

```
Scanning dependencies of target Chakra.Runtime.Language
[ 57%] Built target Chakra.Parser
[ 57%] Building CXX object lib/Runtime/ByteCode/CMakeFiles/Chakra.Runtime.ByteCode.dir/OpCodeUtilAsmJs.cpp.o
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Runtime/Debug/TTSerialize.cpp:5:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Runtime/Debug/RuntimeDebugPch.h:7:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Runtime/./Runtime.h:7:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Common/Common.h:7:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Common/CommonMinMemory.h:7:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Common/CommonMin.h:7:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Common/CommonBasic.h:11:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/lib/Common/CommonPal.h:93:
In file included from /mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/pal/inc/rt/palrt.h:900:
[1m/mnt/j/workspace/Microsoft_ChakraCore/master/ubuntu_linux_release_static_prtest/pal/inc/safemath.h:47:10: [0m[0;1;31mfatal error: [0m[1m'type_traits' file not found[0m
#include <type_traits>
[0;1;32m         ^
```

**Comment by obastemur** [comment]
@MikeHolman IMHO, there is a bad VM in the pool (i.e. llvm support headers are missing) and we've been hitting to that VM from time to time. 

/cc @dilijev @mmitche

**Comment by dilijev** [comment]
@obastemur The VMs are dynamically generated, so it's not that there's a bad VM. What we know so far is that even on the machines where this happens, rebuilding immediately after on the same machine (by directly logging in) doesn't repro the issue. It seems more complex than bad configuration. @mmitche is still investigating.

@MikeHolman when you see a build fail with this can you post here or email a direct link to the build summary page to @mmitche and CC @boingoing and me?

/cc @boingoing

**Comment by mmitche** [comment]
@obastemur It's not a bad VM, it's been seen across a number of VMs and always succeeds on retry.  The weirdness of the error also seems to indicate some kind of corruption.

**Comment by obastemur** [comment]
Maybe a timing issue? Consider a fresh VM, do we install dependencies from scratch?

**Comment by mmitche** [comment]
We don't install anything from scratch, it's also not necessarily the first run on the machine.

**Comment by MikeHolman** [comment]
Here is an instance of the problem:

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_release_static_prtest/801/

**Comment by MikeHolman** [comment]
FWIW it seems like this is happening more often lately. Hit this yesterday on at least 4 different builds.

Also, not just happening on release build, looks like all Ubuntu flavors are hitting this. Here's another:
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_debug_static_prtest/799/

**Comment by mmitche** [comment]
@MikeHolman These VMs are almost always fresh, so something else is going on.  I'm spinning up a VM to run some continuous testing and try and track down the source of the instability.

**Comment by Penguinwizzard** [comment]
I hit this twice today so far; http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_release_static_prtest/824/ is another repro log.

**Comment by aneeshdk** [comment]
Seeing this error in http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_test_prtest/834/consoleFull#-20814844619119f5c-76e5-4da8-b294-eb427d612413

**Comment by Penguinwizzard** [comment]
Daily Ubuntu_linux_test build failed due to this http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/daily_ubuntu_linux_test/71/

**Comment by mmitche** [comment]
@MikeHolman I couldn't get this to repro in isolation on a VM, so I might clone the job that fails the most and then try to run it successively until it fails again to try to discover a pattern.

**Comment by obastemur** [comment]
@mmitche 

Same PR: 

Fail : https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_debug_static_prtest/974/console

Success: https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/ubuntu_linux_debug_static_prtest/975/consoleFull

There are some differences in the output, hope it helps to figure out

**Comment by mmitche** [comment]
I honestly have no idea what is going on.  Has this been seen on 14.04 btw?

**Comment by dilijev** [comment]
@mmitche I don't think we run any 14.04 builds

**Comment by dilijev** [comment]
See https://github.com/dotnet/dotnet-ci/pull/496
Thanks @mmitche

**Comment by Cellule** [comment]
+1 to get updates on the issue

**Comment by dilijev** [comment]
I think @mmitche's mitigation has mostly prevented us from seeing this issue (unless you happen to see it right before it retries. Since this is not a ChakraCore issue and @mmitche probably has it tracked on his end, maybe we should close this issue?

@mmitche is there a public issue open on your end we could track for updates?

**Comment by dilijev** [comment]
I think this issue is mostly mitigated and we know to contact @mmitche for further related issues. I'm closing this issue.
