### ISSUE TITLE
Replace all the instances of uintptr to uintptr_t

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#168]
Current usage of `uintptr` and `uintptr_t` separately fails on cross platform. 

Option 1) fix `uintptr` typedef for other platforms

Option 2) use only `uintptr_t`

Opinions ?

**Comment by jianchun** [comment]
Could you please specify the exact failures you saw?

**Comment by obastemur** [comment]
https://github.com/Microsoft/ChakraCore/pull/159 fixes `uintptr_t` problem on osx (ARM, ia32) while `uintptr` is defined separately and has the same issue. So options are given above. 

Is there any reason to use them separately ?

**Comment by jianchun** [comment]
I just discussed this with other people... Defining custom ```uintptr``` might be due to legacy reason (```uintptr_t``` wasn't available). We can consolidate to ```uintptr_t``` now.
