### ISSUE TITLE
using javascript source library

### ISSUE THREAD

**Issue by oguzhankarsli** [Microsoft/ChakraCore#1702]
When running scripts on chakracore, can chakracore use javascript library?

`var javascript = "src="/application/html/js/josdejong/mathjs/math.min.js"" +`
`"var parser = math.parser();" +` 
`"parser;"`

`Engine.EvaluateScriptText(javascript);`

It is possible?

**Comment by liminzhu** [comment]
You can expose a function like [this](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/JSRT%20Hosting%20Samples/C%2B%2B/ChakraCoreHost/ChakraCoreHost.cpp#L125) to JavaScript to execute the library code.

**Comment by dilijev** [comment]
Looks like this question is answered. Closing this issue.
