### ISSUE TITLE
Optimize deleting last property on an object

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#1713]
Today if we are in `PathTypeHandler` and we delete a property we go to `SimpleDictionaryTypeHandler`. Having a type in `SimpleDictionaryTypeHandler` is expensive both performance and memory wise when it comes to adding properties. Most of the time, it evolves new type when properties are added and it is less likely to get shared. Optimize so that if we are deleting last property then transition to previous type of `PathTypeHandler`.

**Comment by agarwal-sandeep** [comment]
Closing since this is complete and merged

**Comment by kunalspathak** [comment]
Fixes https://github.com/Microsoft/ChakraCore/pull/1897
