### ISSUE TITLE
The problem with document.write in iframe in Edge

### ISSUE THREAD

**Issue by CrazySquirrel** [Microsoft/ChakraCore#1718]
The document.write causing the error SCRIPT70: Permission denied if you use a few document.write inside iframe. This error occurs only in the Edge. In all other browsers this error is not observed.
For example:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SSP-558</title>
</head>
<body>
<script>
    document.write("1");
    document.write("2");
</script>
<script>
    var iframe = document.createElement("iframe");
    iframe.width = window.outerWidth;
    iframe.height = window.outerHeight;
    iframe.onload = function () {
        var doc = iframe.contentWindow.document;
        var script = doc.createElement("script");
        script.type = "text/javascript";
        script.text = [
            'document.write("1");',
            'document.write("2");'
        ].join("");

        doc.body.appendChild(script);
    };
    document.body.appendChild(iframe);
</script>
</body>
</html>
```
This code will display 12 on the page and in iframe, but it cause an error and displays only 1 inside iframe in Edge.

**Comment by CrazySquirrel** [comment]
There was found a solution. If you add window in front of document.write the error will not be caused.

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>SSP-558</title>
    </head>
    <body>
    <script>
        document.write("1");
        document.write("2");
    </script>
    <script>
        var iframe = document.createElement("iframe");
        iframe.width = window.outerWidth;
        iframe.height = window.outerHeight;
        iframe.onload = function () {
            var doc = iframe.contentWindow.document;
            var script = doc.createElement("script");
            script.type = "text/javascript";
            script.text = [
                'window.document.write("1");',
                'window.document.write("2");'
            ].join("");

            doc.body.appendChild(script);
        };
        document.body.appendChild(iframe);
    </script>
    </body>
    </html>

**Comment by dilijev** [comment]
This is an issue with Edge. Can you please open a new issue here with the category HTML/DOM? https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ 

Feel free to post on this thread the link to the issue you open.

**Comment by CrazySquirrel** [comment]
Ok, I open a new issue in the category HTML/DOM [issues#9291485](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9291485/)

**Comment by dilijev** [comment]
@CrazySquirrel Thanks! We'll monitor that issue. Closing this issue as External.
