### ISSUE TITLE
Add test to determine whether all ByteCode has been correctly regenerated.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1721]
The usual failure here is that bytecode for with-JIT varieties is regenerated but NoJIT bytecodes are omitted from the regeneration.

If any ByteCode is regenerated it's worth running a script to regenerate all ByteCode and ensure that there are no changes in ByteCode from the version included in the PR. For any build where no bytecode is regenerated, we can ignore this expensive step of regenerating all bytecodes.

Alternatively, we add one flavor of DisableJIT build to every PR, which would definitely catch this kind of issue without needing to add the entire matrix of DisableJIT builds. This would be a relatively inexpensive check to configure and run with the high value of not routinely breaking DisableJIT CI.

/cc @jianchun @tcare @boingoing 

---

@boingoing Work items:
- [ ] Create non-Daily Jenkins task for disablejit_x64_debug
- [ ] Enable PR check disablejit_x64_debug (optionally as both a PR and rolling build check, to match all other PR checks)

**Comment by jianchun** [comment]
How about:
- On Windows x86 debug, run a modified script that only try to regenerate `...bc.32b.h`. On Windows x64 debug, try to regenerate `...bc.64b.h`. Thus no new build is needed and the validation should be super cheap.
- I'm not sure if we can use above same "ch.exe" to generate "nojit" versions of those headers. If yes, that'll be great; if not, how above emit a failure if any bytecode header is updated but "nojit" version is not?

**Comment by dilijev** [comment]
@jianchun You need to build NoJIT bytecodes from NoJIT binaries, so that's a no-go.

Also, saying "if one is updated, all must be updated" will block a PR in the scenario that one was updated incorrectly and only one needed to be regenerated in a subsequent PR. I'd rather go with the "fail on actual failure" approach rather than an imperfect heuristic with extra maintenance cost.

Running one NoJIT build per PR is pretty cheap and costs no development effort except updating the Jenkins config.

**Comment by obastemur** [comment]
> Alternatively, we add one flavor of DisableJIT build to every PR, which would definitely catch this kind of issue without needing to add the entire matrix of DisableJIT builds. This would be a relatively inexpensive check to configure and run with the high value of not routinely breaking DisableJIT CI.

Curious; don't we already have the environments where JIT is disabled and executing the tests anyway ?

**Comment by jianchun** [comment]
> Curious; don't we already have the environments where JIT is disabled and executing the tests anyway ?

No we don't. Currently only OSX has JIT explicitly disabled. The other day I investigated why we didn't catch this problem on OSX, and the reason was we disabled `Intl` on xplat, so these prebuilt bytecodes are not used at all on xplat.

**Comment by obastemur** [comment]
>  we disabled Intl on xplat,

Yet another reason to enable it ? :)

**Comment by dilijev** [comment]
I like the simplicity of enabling disablejit_x64_debug. Added work items in the description above. /cc @boingoing

**Comment by dilijev** [comment]
@Cellule is this covered by the new verification test?

**Comment by Cellule** [comment]
Yes the tests that we have in the private repo should cover this.
Also the work items in this issue regarding nojit build has been done a long time ago if I recall

**Comment by dilijev** [comment]
Okay, I figured this was an old issue we'd already pretty much taken care of. Closing.
