### ISSUE TITLE
Static analysis of ChakraCore with PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [Microsoft/ChakraCore#177]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the ChakraCore project.

Here is the link to the article about it: http://www.viva64.com/en/b/0370/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by abchatra** [comment]
Thank you @SvyatoslavRazmyslov I am investigating.

**Comment by abchatra** [comment]
Fixed by #207
