### ISSUE TITLE
Proxy stringification doesn't work transparently

### ISSUE THREAD

**Issue by FremyCompany** [Microsoft/ChakraCore#1772]
In Edge (RS_ONECORE_WEBPLAT.14942) `''+new Proxy(window, {})` doesn't return `[object Window]` but `[object Object]` . That does work properly in Chrome.

Similar issue exists for all other dom types.

**Comment by dilijev** [comment]
@akroshg @tcare re: stringification of host objects -- is this an issue on the Edge side? We do have a reference to `[object Window]` in a baseline file:

`test/Array/array_splice5.baseline:1:window = [object Window]`

**Comment by tcare** [comment]
This is related to Edge support for WebIDL @@toStringTag support which is not available yet AFAIK.

**Comment by tcare** [comment]
Check with Travis for more info about this.
