### ISSUE TITLE
Memory related APIs in JSRT

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#179]
I would like to start a discussion for adding few Memory specific APIs in JSRT:

* JSRT currently has [JsSetRuntimeBeforeCollectCallback](https://github.com/Microsoft/ChakraCore/wiki/JsSetRuntimeBeforeCollectCallback) API that lets host set a callback that gets called **before** GarbageCollection happens. It would be good to have an equivalent `JsSetRuntimeAfterCollectCallback` API that will let host set a callback that gets called **after** GC happens.

* JSRT has [JsGetRuntimeMemoryUsage](https://github.com/Microsoft/ChakraCore/wiki/JsGetRuntimeMemoryUsage) API that retrieves memory usage of a runtime. It would be good to expose more details of memory usage metrics like total vs. used vs. available heap size, physical size, etc. 

A good example where these APIs can be useful would be to make native node add-ons like [gc-stats](https://www.npmjs.com/package/gc-stats) and [memwatch-next](https://www.npmjs.com/package/memwatch-next) work with node+chakracore.

**Comment by Cellule** [comment]
Regarding `JsSetRuntimeBeforeCollectCallback` I see no reason why we should/could not do it. We already have the callback mechanism for after garbage collection
We could change [lib/jsrt/jsrtRuntime.cpp#L93](https://github.com/Microsoft/ChakraCore/blob/9229c3387b695b2e2fb247681b26d6e6514bc6d1/lib/jsrt/jsrtRuntime.cpp#L93) to check for `Collect_End` and call an after `callback`.
Or we could change the callback to take an enum as an argument exposing the state of the GC, just like we do in our static method. That said, I don't think changing the api is the best course of action, but it's a possibility.

For `JsGetRuntimeMemoryUsage` I think it could be a could idea, I am not familiar with the data we already have at our disposition to make it happen, but as long as we're collecting data and not changing anything I don't see why we shouldn't expose this.

**Comment by kunalspathak** [comment]
That's right. Adding `JsSetRuntimeAfterCollectCallback` should be trivial. 

We could expose memory stats through mechanism present in [LogMemProtectHeapSize](https://github.com/Microsoft/ChakraCore/blob/master/lib/common/Memory/Recycler.cpp#L363).

@liminzhu , @robpaveza - Thoughts?

**Comment by liminzhu** [comment]
I like ```JsSetRuntimeAfterCollectCallback``` and it can close a gap between us and v8 (v8 has [AddGCEpilogueCallback](http://izs.me/v8-docs/classv8_1_1V8.html#a37aadf3536c772eb5bbf67fa7822679a)). The API addition seems very natural. 

For ```JsGetRuntimeMemoryUsage```, I have to admit ignorance on memory management. What information would be considered useful and how would someone use these information, in the context of JSRT in general, not memwatch-next?

**Comment by liminzhu** [comment]
Adding @Yongqu to discussion.

**Comment by kunalspathak** [comment]
> how would someone use these information, in the context of JSRT in general, 

Exposing memory usage information would help host to do better memory profiling and make decisions based on that.

**Comment by Yongqu** [comment]
The API was design for memory metering such that some kind of application manager can throttle the runtime's memory usage. I don't think we have profiler/debug helper style API builtins. We need to take a look from that perspective to see if anything need to be done there. Maybe my question is how can JSRT use these profiler information programmatically?

**Comment by kunalspathak** [comment]
[JsSetRuntimeMemoryLimit](https://github.com/Microsoft/ChakraCore/wiki/JsSetRuntimeMemoryLimit) is one JSRT API that can be used for throttling. So basically you could programmatically get memory usage and then throttle runtime memory if it exceeds certain threshold?

**Comment by Yongqu** [comment]
the two APIs, get and set, is a pair. yes you can do that.

**Comment by liminzhu** [comment]
What information would be useful in addition to used memory returned by [JsGetRuntimeMemoryUsage](https://github.com/Microsoft/ChakraCore/wiki/JsGetRuntimeMemoryUsage)?

**Comment by kunalspathak** [comment]
Most fields returned by [LogMemProtectHeapSize](https://github.com/Microsoft/ChakraCore/blob/master/lib/common/Memory/Recycler.cpp#L363) to start with.

**Comment by Yongqu** [comment]
It sounds like you are asking for a Debug object for various helper utilities. How does node solve this problem? I assume you can ask for more information like GC size, JIT code size, CollectGarbage() call etc.

**Comment by kunalspathak** [comment]
We just need memory related information like heap size, available physical memory, etc. v8 engine has [HeapStatistics](http://v8.paulfryzel.com/docs/master/include_2v8_8h_source.html#l05092) and [HeapSpaceStatistics](http://v8.paulfryzel.com/docs/master/include_2v8_8h_source.html#l05117) structures that node modules uses to extract heap specific information. If we could get some JSRT API extract some (if not all) information, we could support those native node modules in node+chakracore.

**Comment by Yongqu** [comment]
Adding a native method extension using JsCreateFunction might be better here.

**Comment by kunalspathak** [comment]
Sure, but we still need other GC specific information that can only be extracted from within ChakraCore. So I propose to have single API that would extract all the information (system memory, GC memory, etc.).

**Comment by liminzhu** [comment]
What would be 'all the information'? It would be kinda ugly if later we find that more information is needed and we have to either change API shape or add another similar API.

**Comment by EdMaurer** [comment]
Let's only add these APIs if there is a consumer. At present, I don't see a need.
