### ISSUE TITLE
JsRunScript() doesn't exist in Linux.

### ISSUE THREAD

**Issue by vbmacit90** [Microsoft/ChakraCore#1791]
Hi,
I have compiled ChakraCore in Linux but there is no function JsRunScript() in .so library. it is undefined! and it is declareted in ChakraCommonWindows.h how can we use in Linux?

Thanks for any advice...

**Comment by obastemur** [comment]
@vbmacit90 `JsRunScriptUtf8` is the temp. replacement on cross platform.

**Comment by vbmacit90** [comment]
is the JsStringToPointerUtf8Copy  replacement for JsStringToPointer  on cross platform too?

**Comment by obastemur** [comment]
Yes. Please keep in mind; these are temporary methods and soon we will update them. Updated versions will take a place in our documentation.

**Comment by obastemur** [comment]
Closing this one. Feel free to open if you continue to have the problem.

**Comment by vbmacit90** [comment]
Thank you for answers 
const char *script = "(()=>{return \'Hello world!\';})()";
    // Run the script.
    JsRunScriptUtf8(script, currentSourceContext++, "", &result);

    // Convert your script result to String in JavaScript; redundant if your script returns a String
    JsValueRef resultJSString;
    JsConvertValueToString(result, &resultJSString);

    // Project script result back to C++.
    char *resultWC;
    size_t stringLength;
    JsStringToPointerUtf8Copy(resultJSString, &resultWC, &stringLength);//**Crashing here

whats problem here @obastemur  ?

**Comment by obastemur** [comment]
What is the return value of `JSConvertToString` ? `JsNoError` ? and what crash says?
