### ISSUE TITLE
C++ language conformance changes (msvc /permissive-)

### ISSUE THREAD

**Issue by Rastaban** [Microsoft/ChakraCore#1800]
There is a new compiler switch in the next release of MSVC that makes the compiler less permissive (/permissive-)  There are three types of language conformance issues that are exposed in the Chakra codebase when building with /permissive-

1) Strict string conversion (this is also covered by the /Zc:strictStrings flag)

  The 'const' is not implicitly dropped by string literals, which means the following is not allowed:

  `char *str = "const string literal"; //error: cannot convert a 'const char*' to a 'char*'`

  This fix to to make str 'const char*'.  (This can have a domino effect depending on where str is used)

2) Fully qualified inline declarations members inside class

```
   struct A {
      void A::f() { } // Error: illegal qualified name in member declaration, remove redundant 'A::' to fix
   };
```

3) MSVC by default will allows name lookup in a dependent base.  This is disabled by /permissive-

```
    template <class T> struct B {
      void f();
    };

    template <class T> struct D
        : public B<T> //B is a dependent base because its type depends on the type of T in D<T>.
    {
        //One possible fix is to uncomment the following line.  If this were a type we should have 'using typename'...
        //using B<T>::f;

        void g() {
          f(); //Error: identifier not found, one possible fix is change it to 'this->f();'
        }
    };

    void h()
    {
       D<int> d;
       d.g();
    }
```

The MSVC compiler team uses the ChakraCore build as part of their tests, so we have already made the necessary changes in our own branch and are interested in submitting a pull request.

**Comment by dilijev** [comment]
I've encountered the third issue a lot when writing code that needed to compile in both GCC and MSVC, I didn't realize that was an issue of permissivity. It's good to see this change come to ChakraCore, it should help with portability of our code.

**Comment by dilijev** [comment]
Resolved by https://github.com/Microsoft/ChakraCore/pull/1802
