### ISSUE TITLE
WASM - f32.convert_u/i32 bugs

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1967]
The following tests are failing in jitted code
`test/WasmSpec/testsuite/conversions.wast` lines 266 & 268
`test/WasmSpec/testsuite/float_exprs.wast` lines 493 & 698-700

**Comment by Krovatkin** [comment]
i hope if we decide on PR #1960 it will fixes the issues in those test cases

**Comment by Cellule** [comment]
If you think it fixes the issues, you should uncomment those tests and regenerate the .wasm/.json files in your PR

**Comment by Krovatkin** [comment]
@Cellule will do!

**Comment by Cellule** [comment]
The tests in test/WasmSpec/testsuite/conversions.wast lines 266 & 268 haven't been reenabled

**Comment by Krovatkin** [comment]
dang! @Cellule i'm really sorry about that! let me fix this.
