### ISSUE TITLE
linux: GetVersionInfo from resource

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#197]
On Windows `AutoSystemInfo::GetVersionInfo` reads major/minor versions from module resource. It is used by `ByteCodeSerializer`, `SourceDynamicProfileManager` etc. to read jscript dll version info and store together with other data.

How do we make this cross-platform?

Can we change all the usage to use `CHAKRA_CORE_MAJOR_VERSION` etc. instead?

**Comment by dilijev** [comment]
See discussion here https://github.com/Microsoft/ChakraCore/issues/109

**Comment by kfarnung** [comment]
The relevant code is here:

https://github.com/Microsoft/ChakraCore/blob/7b32fe07fde7750bfd4ab2062063dbc70d6cebb3/lib/Common/Core/SysInfo.cpp#L547-L552

**Comment by agarwal-sandeep** [comment]
In ReleaseVersioningScheme bytecode serializer is dependent on guid and in EngineeringVersioningScheme buildDateHash, buildTimeHash takes care of versioning. Don't see a value in doing this right now.
