### ISSUE TITLE
linux: Switch from IsWindows8OrGreater to feature detection

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#198]
Instead of testing IsWindows8OrGreater, we should examine each usage and switch to enable/disable feature instead. That'll make code cleaner.

**Comment by obastemur** [comment]
@jianchun a bit more details on this ? (if this needs to remain open)

**Comment by jianchun** [comment]
@agarwal-sandeep This issue was opened from a PR comment. As long as `IsWindows8OrGreater` is still used in the codebase and shared by xplat code, it would still be better to get rid of it. Low priority though.

**Comment by agarwal-sandeep** [comment]
@jianchun all usage of IsWin8OrLater (which calls IsWindows8OrGreater) is guarded under _WIN32 so there is not dependency of this for xplat.

**Comment by jianchun** [comment]
@agarwal-sandeep Agree. I suppose the code has changed and it is no longer used for xplat.
