### ISSUE TITLE
linux: detect number of physical/logical CPU cores

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#200]
`AutoSysInfo` has code to detect physical/logical CPU cores. The code primarily cares about number of physical cores. Linux port currently uses PAL implementation. Need to verify if it works/suffices.

**Comment by obastemur** [comment]
`cpuid` is a processor instruction and specific to Intel x86. I can't think of a cross platform issue.

**Comment by obastemur** [comment]
I haven't check yet, is there anything specific done or needed for ARM ?

**Comment by jianchun** [comment]
This issue primarily refers to the number of cores, from [PAL code](https://github.com/dotnet/coreclr/blob/df70149df5440ac409a3792aa0eca5d27a105d8b/src/pal/src/misc/sysinfo.cpp#L121), and also [related GetLogicalProcessorInformation calls on Windows](https://github.com/Microsoft/ChakraCore/blob/linux/lib/common/core/SysInfo.cpp#L99).

Seems we are not using it on ARM, not sure either.

**Comment by agarwal-sandeep** [comment]
@obastemur @jianchun are we planning to do any work on this? //cc @dilijev @kfarnung
