### ISSUE TITLE
New JSRT API documentation

### ISSUE THREAD

**Issue by jcoffland** [Microsoft/ChakraCore#2002]
I see that the latest JSRT code ``master`` branch has a different API than what is documented in the [wiki](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Reference).  Notably ``JsStringToPointer()`` no longer exist but there are functions like ``JsCopyString()`` which use utf-8 instead.  This is really great but I cannot find documentation anywhere.

Could you either point me to the documentation or instructions on how to build the API docs from the source?

**Comment by jcoffland** [comment]
I was able to generate my own up to date documentation from the source using Doxygen.  Here's how.  First generate a default Doxygen configuration file with:

    cd ChakraCore
    doxygen -g Doxyfile

Then edit ``Doxyfile`` changing the following settings:

    PROJECT_NAME           = "Chakra Core"
    . . .
    OUTPUT_DIRECTORY       = "docs"
    . . .
    OPTIMIZE_OUTPUT_FOR_C  = YES
    . . .
    INPUT                  = "lib/Jsrt"

Finally generate the docs with:

    doxygen Doxyfile

This produces html docs with the interesting part starting at ``docs/html/files.html``.

**Comment by obastemur** [comment]
@jcoffland we have been tracking this issue at https://github.com/Microsoft/ChakraCore/issues/2002#issuecomment-260275216 

@alexgwolff any update?

**Comment by dilijev** [comment]
I'm assuming @obastemur meant to link to the related PR on the ChakraCore-wiki repo: https://github.com/Microsoft/ChakraCore-wiki/pull/13

**Comment by jcoffland** [comment]
@dilijev Thanks.  That makes a lot more sense now.

**Comment by dilijev** [comment]
Closing this issue since it's being tracked elsewhere.
