### ISSUE TITLE
TypedArray constructor throws TypeError for undefined argument

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2014]
Effectively, 'new Uint8Array(0)' and 'new Uint8Array()' and 'new Uint8Array(undefined)' should have the same behavior.

Converting from an internal issue.

This issue is not a spec deviation from ES 6.0. It's a spec change in ES 2017. In ES6, we were supposed to (and are correctly) throwing TypeError if length is undefined. 

ES 6.0 spec text:

22.2.1.2 %TypedArray% ( length )

This description applies only if the %TypedArray% function is called with at least one argument and the Type of the first argument is not Object.

%TypedArray% called with argument length performs the following steps:

Assert: Type(length) is not Object. 
1. If NewTarget is undefined, throw a TypeError exception. 
1. If length is undefined, throw a TypeError exception. 
1. Let numberLength be ToNumber(length). 
1. Let elementLength be ToLength(numberLength). 
1. ReturnIfAbrupt(elementLength). 
1. If SameValueZero(numberLength, elementLength) is false, throw a RangeError exception. 
1. Return AllocateTypedArray(NewTarget, elementLength).

Test case:

```js
new Uint8Array(0)
new Uint8Array()
new Uint8Array(undefined) // TypeError
```

**Comment by ianwjhalliday** [comment]
There is more to this.  Generally in the [`TypedArray(length)`](https://tc39.github.io/ecma262/#sec-typedarray-length) constructor overload the first argument is passed to `ToIndex` which should handle all cases for us, but our code was handling this manually and incorrectly (according to older spec).

This means null, booleans, and strings are also handled incorrectly.
