### ISSUE TITLE
[Legacy] Illegal argument to sizeof

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2026]
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#legacy-builds

`
lib\Runtime\Library\WebAssemblyTable.cpp(124): error C2070: 'unknown': illegal sizeof operand [lib\Runtime\Library\Chakra.Runtime.Library.vcxproj]
`
`
lib\Runtime\Library\WebAssemblyTable.cpp(124): error C2338: sizeof(m_maxLength) == sizeof(uint32) [lib\Runtime\Library\Chakra.Runtime.Library.vcxproj]
`

**Comment by geek-li** [comment]
seems same  error  like urs

**Comment by dilijev** [comment]
Fixed by #1990 and #2207
