### ISSUE TITLE
WASM - incorrectly validate function with return type with nothing in the type stack

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#2048]
`(module (func (result i32)))` validates when it shouldn't

**Comment by Cellule** [comment]
@arun-etm For some reason I can't assign this to you, but I'll keep track that you are working on it

**Comment by arunetm** [comment]
Thanks. :)
The handle "@arunetm" should work as that is the one that I actively use for PR's.

**Comment by Cellule** [comment]
It works for mentions, but it doesn't show in my list to assign... Seems like a GitHub bug

**Comment by Cellule** [comment]
This is correctly found invalid, deferred parsing was the source of the confusion on this one.

**Comment by arunetm** [comment]
Also, we correctly return "false" for WebAssembly.validate and a validation error will be thrown if the function is called into.
