### ISSUE TITLE
WASM: float32 NAN value representation in JIT

### ISSUE THREAD

**Issue by meg-gupta** [Microsoft/ChakraCore#2049]
We use double to store all FloatConstOpnd's in JIT.
While building a NAN float32 constant in IRBuilder we call:
`IR::FloatConstOpnd::New(constVal, TyFloat32, m_func), m_func);`

The function is declared as : 
`FloatConstOpnd *
FloatConstOpnd::New(FloatConstType value, IRType type, Func *func)`

where `FloatConstType` is double

The conversion instruction from float to double will turn a float 0x7fa00000 to 0x7fffc0000000 and then finally the value built will be 0x7fffc000.

This violates some tests in the spec.

**Comment by arunetm** [comment]
This problem change the bits for the nan's when some are stored and read back. not a problem for js as the read back value is still a nan. wasm nan's has a more stricter layout than js nan's making this a problem for wasm. 
Would it make sense to canonicalize wasm nan's? or should we fix the above issue with FloatConstOpnd?
@Cellule @MikeHolman

**Comment by obastemur** [comment]
I had spent some time on this. Actually we may even have a workaround PR fixing an issue on xplat. The bigger problem here is that nan is not a single signed/non-signed value. However internally we convert any `nan` value to a single representation and the rest of the solution behaves based on that constant.

**Comment by ThomsonTan** [comment]
Probably we need some special check before converting `FloatConstantOpnd` to float32 NaN?
