### ISSUE TITLE
Optimize async functions

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#2055]
There are known optimizations on the table for async functions especially around avoiding object allocation. Our implementation of async functions is significantly slower than other implementations. V8 has [recently implemented](https://codereview.chromium.org/2512103002/) an optimization that I think we could apply as well.

Now that we've got async functions shipped and stable let's use this issue to track our optimization work.

**Comment by dilijev** [comment]
This is a performance work item (and in particular not a performance-related bug) that will be targeted as we prioritize work around benchmarks and real-world use cases. Keeping this issue open doesn't seem to add much value.

/cc @kfarnung @agarwal-sandeep
