### ISSUE TITLE
About JsObject's reference and release

### ISSUE THREAD

**Issue by FettLuo** [Microsoft/ChakraCore#2072]
I created a object A, and added some member. 
JsCreateObject

created external object B, and set prototype with A. C is finalizeCallback.
JsCreateExternalObject, JsSetPrototype

do gc.
JsCollectGarbage

why not call finalizeCallback C?
I tryed to call JsRelease(B, count) too, count is return (uint)-1, but useless.

**Comment by FettLuo** [comment]
and
JsRunScriptUtf8("function event(obj){obj = null;}")

event_fn = JsGetProperty(global,"event")
JsCallFunction(event_fn,...)

JsCollectGarbage again
not skill call finalize callback of B

even JsDisposeRuntime is not effect too

**Comment by FettLuo** [comment]
Finally, B is called with JsRuntimeAttributeDisableBackgroundWork.
but at JsDisposeRuntime, why not GC?
How to release the external object or other js object?

**Comment by FettLuo** [comment]
btw, how to wait all object release done after dispose runtime?

**Comment by liminzhu** [comment]
Hi @FettLuo. A GC call is asynchronous, which is probably why you're not seeing the finalizer being called right away. There is no guarantee on when a GC call would finish. Also, GC can only happen during scripting so you can try running some random scripts a few times and see if the disposable object you created in the first place is being collected.

**Comment by FettLuo** [comment]
@liminzhu  谢谢，thank you
