### ISSUE TITLE
swb: tune JsUtil::QuickSort implementation

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#2074]
We brought back custom `JsUtil::QuickSort` in swb branch to solve the problem that system qsort routine does not update write barrier when array element contains WriteBarrierPtr fields.

We need to fine tune `JsUtil::QuickSort` performance. Current implementation does not work well with already sorted or many equal items array.

Moreover, @obastemur said xplat `qsort_r` is not reliable on some platforms (#2069). We might prefer custom reliable implementation on xplat too.

**Comment by obastemur** [comment]
Update: We have our custom qsort_r implementation on master.

**Comment by jianchun** [comment]
SWB branch uses a different code (JsUtils::QuickSort template) when write barrier is needed, thus not using qsort_r. This caused Array/arr_qsortr.js unit test failure. Excluded from xplat temporarily.
