### ISSUE TITLE
Setting an element outside the bounds of a frozen array does not throw an exception

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#2083]
Open the developer console for logs.

Call Object.freeze on an array and set an element outside of the array's bounds.
Expected result: An exception is thrown
Actual result: No exception is thrown

This does not repro when setting elements inside the bounds of the array.

        'use strict';

        var arr = ["one", "two", "three"];
        Object.freeze(arr);

        console.log("Initial arr.length: " + arr.length);

        try {
            console.log("Setting arr[0]...");
            arr[0] = "";
            console.log("No exception thrown when setting arr[0]");
        }
        catch(e) {
            console.log("Exception thrown when setting arr[0]");
        }
        console.log("arr[0] after setting - Expected: one, Actual: " + arr[0]);
        console.log("arr.length: " + arr.length);
        console.log();

        try {
            console.log("Setting arr[5]...");
            arr[5] = "";
            console.log("No exception thrown when setting arr[5]");
        }
        catch(e) {
            console.log("Exception thrown when setting arr[5]");
        }
        console.log("arr[5] after setting - Expected: undefined, Actual: " + arr[5]);
        console.log("arr.length: " + arr.length);

**Comment by dilijev** [comment]
I believe this is fixed by #2089. @ThomsonTan can you confirm and close this issue?

**Comment by ThomsonTan** [comment]
Yes, fix https://github.com/Microsoft/ChakraCore/pull/2089 had been fixed.
