### ISSUE TITLE
neither master nor release/2.0-pre build with VS2017 RC

### ISSUE THREAD

**Issue by matthargett** [Microsoft/ChakraCore#2096]
Both the in-solution build in react-native-windows and from the Developer Command Prompt for VS2017 RC, I get this message:

1>       "C:\Users\matt.hargett\Source\Repos\rnw-mh\ChakraCore\Build\Chakra.Core.sln" (Core\Bin\ChakraCore target) (1) ->
1>       "C:\Users\matt.hargett\Source\Repos\rnw-mh\ChakraCore\Build\..\bin\ChakraCore\ChakraCore.vcxproj.metaproj" (default target) (2) ->
1>       "C:\Users\matt.hargett\Source\Repos\rnw-mh\ChakraCore\lib\common\util\Chakra.Common.Util.vcxproj" (default target) (16) ->
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\matt.hargett\Source\Repos\rnw-mh\ChakraCore\lib\common\util\Chakra.Common.Util.vcxproj]
1>

**Comment by dilijev** [comment]
(Added to the Cross-platform milestone because that's the next milestone for the master branch.)

Note: release/2.0-pre branch and master will likely be merged at some point in this future.

**Comment by juancarlosbaezpozos** [comment]
I was able to build the chakracore x64 under visual studio 2017 with some fixes around the include paths and other tools. You must install: VC++ 2015 toolset, windows universal crt sdk, windows 10 sdk, windows 8.1 sdk, windows universal C runtime and retarget the solution except for the "platformAgnostic" project.

Include directories property must set to:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\atlmfc\include;$(IncludePath)

**Comment by curtisman** [comment]
@matthargett I believe the problem that you are seeing should be fixed by dff977ca86e9b32f2d2130cd0306dbde12830155

@juancarlosbaezpozos PR #3067 should help you avoid installing older toolset and 8.1 SDK. I have tried it with only VS2017 and WinSDK 10.0.15063.0 installed.

**Comment by dilijev** [comment]
Sounds like this has been resolved in master.

@juancarlosbaezpozos @matthargett Feel free to reopen if you have further difficulties.
