### ISSUE TITLE
String.prototype.toLowerCase and String.prorotype.toUpperCase built-ins should support unicode

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#21]
This is a [kangax](http://kangax.github.io/compat-table/es6/) [test case] (https://kangax.github.io/compat-table/es6/#test-String.prototype_HTML_methods)
```javascript
function foo(){
return "𐐘".toLowerCase() === "𐑀" && "𐑀".toUpperCase() === "𐐘";
}
print(foo());
```
Expected: true
Actual: false

**Comment by suwc** [comment]
https://github.com/Microsoft/ChakraCore/pull/253

**Comment by suwc** [comment]
Leave a comment
