### ISSUE TITLE
xplat: Missing ES6 Module functionality in Linux and macOS

### ISSUE THREAD

**Issue by Oceanswave** [Microsoft/ChakraCore#2112]
I'm using the master branch + PR #2056,  latest of a few moments ago.

The following methods seem to be missing from both 'nix and macOS:

 - JsInitializeModuleRecord
 - JsSetModuleHostInfo
 - JsParseModuleSource
 - JsModuleEvaluation

The following tests are passing in windows, but failing on ubuntu/osx CI builds:

Windows (Passing):
https://ci.appveyor.com/project/Oceanswave/baristacore/build/1.0.39

Linux/OSx (Failing):
https://travis-ci.org/BaristaLabs/BaristaCore/builds/179819739

**Comment by liminzhu** [comment]
Hey @Oceanswave . The module functionalities are experimental and Windows-only as you've noticed. We are waiting for the nodejs module story to crystalize and that may lead to some changes to our module interface.

**Comment by Oceanswave** [comment]
Thanks for the clarification @liminzhu. Looking forward to seeing module functionality solidify.

**Comment by liminzhu** [comment]
Np. 

Close as the issue is answered.

**Comment by Oceanswave** [comment]
Although there's an apparent dependency on the V8 implementation, I wouldn't quite say resolved as it would still be a plus to be able to have this functionality on xplat albeit experimental. It would be great if progress could be tracked - somewhat like the V8 tracking bug on ES6 modules here https://bugs.chromium.org/p/v8/issues/detail?id=1569

**Comment by liminzhu** [comment]
@Oceanswave sure I can leave this open and update progress in the future.

**Comment by Oceanswave** [comment]
Thank you!

**Comment by obastemur** [comment]
@Oceanswave Thanks!
