### ISSUE TITLE
Failed to initialize COM interfaces

### ISSUE THREAD

**Issue by noh626** [Microsoft/ChakraCore#212]
Hi,

Before I replace v8 in our server app with chakra core, I am going to test simple javascript. 

When I tried hello world sample, SEHException was occured in creating an context.

When native code debugging is enabled I can see it failed to initialize COM interface. 

AssertMsg(false, "Failed to initialize COM interfaces, verify correct version of globalization dll is used.");

This only happens to my work machine.

Anyone experienced this problem?

Thanks,

**Comment by ianwjhalliday** [comment]
@kunalspathak is tihs related to what you've been working on recently with Intl on Win7?

@noh626 what OS version are you using?

**Comment by ianwjhalliday** [comment]
Sounds likes #202

**Comment by noh626** [comment]
@ianwjhalliday Windows7 Pro

**Comment by ianwjhalliday** [comment]
Ah, okay yeah, definitely sounds like #202.  Could you try using the commit from PR #202 and see if that fixes it?

**Comment by ianwjhalliday** [comment]
And then there also seems to be a question of do we have a general problem with engine failures resulting cryptic error messages that could perhaps be improved @curtisman

**Comment by noh626** [comment]
@ianwjhalliday All right!  I am gonna try soon. I will let you know after then. Thanks!

**Comment by kunalspathak** [comment]
Yep, as #202 mentions, this happens if you don't have IE11 installed on your Win7 Pro machine. If you install IE11, this problem should go away automatically.

**Comment by noh626** [comment]
@ianwjhalliday @kunalspathak I just tried with the commit from #202 and could get it work. Thanks guys!

**Comment by ianwjhalliday** [comment]
Awesome, great to hear!
