### ISSUE TITLE
SlowTest-Fail: typedarray/samethread.js fails after #2016

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#2135]
New xplat CI found that `test/typedarray/samethread.js` fails after #2016 is being merged.

Repro: (on any distro or osx)

- Build [test-build]
- `test/runtests.py -t --include-slow test/typedarray`

Assigning this to @ianwjhalliday as [#2016] PR is the reason.

**Comment by obastemur** [comment]
@ianwjhalliday I have disabled this test temporarily on xplat slow tests. In order to reproduce the problem you might have to enable the test back -> https://github.com/Microsoft/ChakraCore/pull/2223/files

**Comment by Cellule** [comment]
Fixed in #2228 
@obastemur Can you confirm this fixed the issue on xplat as well?
