### ISSUE TITLE
Update usage of JsTTDGetSnapTimeTopLevelEventMove in xplat branch

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2161]
As mentioned in https://github.com/Microsoft/ChakraCore/pull/2001#issuecomment-263711770

/cc @jianchun @mrkmarron

**Comment by dilijev** [comment]
@jianchun @mrkmarron @kfarnung Is there any action to take on this issue now, or is it defunct?

**Comment by jianchun** [comment]
That should have been done, otherwise node-ChakraCore wouldn't build with latest. Others can confirm.

**Comment by kfarnung** [comment]
This is completed, closing.
