### ISSUE TITLE
linux: unix version of _mul128 to optimize Int64::Mul

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#217]
In #206, @obastemur has implemented unix version of _mul128 using inline assembly. Consider getting this in to optimize Int64::Mul.

> Prepared a unix/linux version of `__mul128` https://gist.github.com/obastemur/48125aacb960a5b66730

**Comment by obastemur** [comment]
I've been testing the solution on other platforms / compilers. What would be the best place (header file) to define linux/unix version of `__mul128` ?

**Comment by jianchun** [comment]
Since it will be used only by Int64Math.cpp and other code should probably just use Int64Math wrapper, maybe also put it in lib/common/common? (No strong opinion.)

**Comment by obastemur** [comment]
This was implemented while ago. Closing.
