### ISSUE TITLE
[x64 release] bin\ch\hostconfigflags.cpp(99): warning C6385: Reading invalid data from 'argv'

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2183]
`bin\ch\hostconfigflags.cpp(99): warning C6385: Reading invalid data from 'argv':  the readable size is 'argc*8' bytes, but '24' bytes may be read.`

git blame shows this was introduced a few months ago:

```
10cfef1f (Michael Holman 2016-09-02 20:36:55 -0700  99)         argv[i - 1] = argv[i];
```

Discovered when running code analysis on x64_debug build by following [these steps](https://github.com/Microsoft/ChakraCore/wiki/Jenkins-Repro-Steps#windows-release-builds).

Repros in x64_release on my machine. Not sure why it doesn't show up in Jenkins.

/cc @mmitche do you know why we would get different PreFAST errors locally versus on Jenkins?

**Comment by MikeHolman** [comment]
I'm not able to repro, and besides this is SAL warning in test only code so it doesn't seem worth investigating further.
