### ISSUE TITLE
[Discussion] [Meta] How to enable community contribution to the wiki.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#220]
Last night there was a brief discussion on Gitter about community contributions to the wiki. Even though the wiki is a git repo itself, GitHub does not allow pull requests to the wiki. We either allow everyone in the open to edit freely or restrict contributor access to contributors only, so the community cannot edit at all. As a point of order, it seems that the latter is the only option that really makes sense for us.

Ideally, we would have some system by which contributors can add or edit documentation subject to review.

Other projects get around this problem by having documentation under a docs directory. Example given was Roslyn's GitHub repo in particular this issue: dotnet/roslyn#7498.

I came up with the idea of hosting a mirror of the wiki's git repo on a GitHub repo. We could call it Microsoft/ChakraCoreWiki or Microsoft/ChakraCoreDocs. This would allow us to bypass all of the Jenkins checks and other test infrastructure and have an entire repo of text-only changes. We can periodically sync the changes to that repo to the Microsoft/ChakraCore/wiki.git.

Thoughts?

**Comment by Cellule** [comment]
I remember talking about this a while back, but I do think readme files in a doc folder is better suited since 
- it is source controlled
- it follows the version (ie: you can see matching doc for older versions) 
- it doesn't rely on Github's wiki
- you can search the code base for api methods or anything and find the doc (I'm not sure about this, does github search looks in the wiki ?)

**Comment by dilijev** [comment]
From what I can tell search on the github repo does not search the wiki. The wiki has a limited search to help you find pages but that's it.

In practice, I think documentation will lag behind the code. Keeping them perfectly in sync is not really necessary. Keeping that class of changes completely out of the source repo would seem to make sense to me.

Maybe we could have the docs directory be a submodule linked to the separately-hosted wiki? That way we have documentation roughly matching the source version that the documentation corresponded to. Still the above point applies.

**Comment by liminzhu** [comment]
Just saw this today...

I like the idea of a mirroring repo actually, mainly because it allows forks/PRs while keeping the perks of a wiki
* easy to view and navigate with sidebars  
* easy for collaborators to make small edits and previewing edits has been helpful for me

I know TypeScript did something similar with [TypeScript-wiki](https://github.com/Microsoft/TypeScript-wiki).

**Comment by dilijev** [comment]
@liminzhu Oh, excellent find. I like that there's a precedent. I'll discuss with @curtisman @tcare and @digitalinfinity and try to get this coordinated.

**Comment by dilijev** [comment]
I discussed offline with @EdMaurer and @bterlson and they agreed that the wiki mirror ChakraCore-wiki is a good idea. @EdMaurer expressed concern about the potential need for extra machinery to keep them in sync. I will discuss sync machinery needs (if any) with @tcare on Monday and then hopefully we can get this coordinated.

**Comment by dilijev** [comment]
@tcare For sync machinery there are a few possibilities to consider:

1. All edits to the wiki are done via the `ChakraCore-wiki` repo.
  1. All changes are reviewed as PRs.
  2. External changes will be reviewed as PRs.
  3. [hybrid] Any large changes will be reviewed as PRs and otherwise small edits can be committed directly (as now).
2. Edits to be reviewed are done via the `ChakraCore-wiki` repo, and other edits by the team are done directly in the `ChakraCore/wiki` site (as now).

Advantage to (2) is that for small edits we can have minimal friction in making simple changes and get them to appear right away. Disadvantage to (2) is that the `ChakraCore/wiki` and `ChakraCore-wiki` master branches may need to be merged occasionally to fully mirror changes.

Advantage to (1) is that the mirroring only needs to be done in one direction and there will never be conflicts when mirroring. Disadvantage to (1) is that even for small changes the author needs to propagate the changes to `ChakraCore-wiki` every time.

**Comment by dilijev** [comment]
@caitp I believe you were interested in making community contributions to the wiki when the discussion came up on Gitter. How does this solution sound?

**Comment by caitp** [comment]
:+1:

**Comment by dilijev** [comment]
I'm getting approvals and setting this set up within the next day or so.

**Comment by liminzhu** [comment]
Great to see this progressing :+1: . Do we know which model you mentioned before are we going for?

**Comment by dilijev** [comment]
I asked around about how the wiki was handled on coreclr and TypeScript and after discussions with those teams and various people on Chakra, we decided that the mirror repo wiki a la [TypeScript-wiki](https://github.com/Microsoft/TypeScript-wiki) is the least risky and least overhead option. Assuming no objections from legal, I'll get that set up tomorrow. Thanks for pointing me to the TypeScript example, @liminzhu :)

**Comment by dilijev** [comment]
To be more specific:

We will create the repo `ChakraCore-wiki` and mirror the wiki (https://github.com/Microsoft/ChakraCore/wiki) there.

We will allow our team to make changes directly to the wiki as they do now, to remove any friction for small edits. If someone wishes to have the changes reviewed, they can open a PR on `ChakraCore-wiki`. The PR and merge process via that repo will be much simpler and lower friction than code changes as well (as it is not subject to build checks).

All external contributions to the wiki will be done via PRs or Issues filed on `ChakraCore-wiki`

**Comment by dilijev** [comment]
Update: waiting on approvals.

**Comment by liminzhu** [comment]
A reminder to myself that once the mirror is created, I should add a [footer](https://github.com/Microsoft/TypeScript/wiki#want-to-contribute-to-this-wiki) in the wiki linking to the mirroring repo.

**Comment by dilijev** [comment]
@liminzhu Yep, TypeScripts example you linked is a good way to handle this. You can copy their [_Footer.md](https://github.com/Microsoft/TypeScript-wiki/blob/master/_Footer.md) and make the necessary changes for our project.

**Comment by dilijev** [comment]
Update: still working out details. Close to making it happen.

**Comment by dilijev** [comment]
The ChakraCore wiki clone is now live at: https://github.com/Microsoft/ChakraCore-wiki

I'll leave this issue open for a couple of days in case there are any follow-up questions or discussions to be had.

**Comment by dilijev** [comment]
Closing issue now as no more discussion seems to be taking place. Feel free to reopen if appropriate.
