### ISSUE TITLE
JavaScript Bug When Referencing Variable Storing Attribute Selector String

### ISSUE THREAD

**Issue by johndugan** [Microsoft/ChakraCore#2212]
I have an attribute selector stored as a string. I pass it as an argument to `querySelectorAll` as in the code below. An error is thrown. See screenshot.

```
const ITEM = '[data-showflex="container"]',
    STATECLASS = 'show';

function showAllItems() {
    document.querySelectorAll(ITEM).forEach((item) => item.classList.add(STATECLASS));
}
function hideAllItems() {
    document.querySelectorAll(ITEM).forEach((item) => item.classList.remove(STATECLASS));
}
```

![2016-12-15_1](https://cloud.githubusercontent.com/assets/1389303/21241851/3d128878-c2d7-11e6-88a0-7ea11a003259.png)

**Comment by dilijev** [comment]
Hi @johndugan, thanks for bringing up this issue. This looks like a bug with the DOM API `querySelectorAll` in Edge. Please open this issue on the Edge issue tracker as described [here](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

**Comment by dilijev** [comment]
Looks like @johndugan opened this issue on the Edge issue tracker:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10232708/

Thanks! Closing this issue.
