### ISSUE TITLE
pogo_training.ps1 using `-oopjit-` flag breaks POGO training for ChakraCore release builds

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2213]
In ChakraFull we POGO Test builds (rather than Release builds) because we need performance-optimized Test builds for testing purposes. The pogo_training.ps1 script is used to do the POGO training in ChakraFull as well. In the case of ChakraFull, extra parameters like `-oopjit-` work just fine.

We had not yet noticed the ChakraCore problem because we have not yet made a release of ChakraCore since these flags were added (they were not present in release/1.3, but the flag (currently -oopjit-) was added after OOP JIT was added to the code base to ensure we train without using OOP JIT.

OOP JIT is explicitly disabled by default in ChakraCore. Therefore, we can remove this additional flag for ChakraCore POGO, and move that flag into the appropriate automation specific to ChakraFull.

See discussion here: https://github.com/Microsoft/ChakraCore/pull/1793#issuecomment-267065346

/cc @matthargett

**Comment by ThomsonTan** [comment]
I am wondering whether OOP JIT is necessary for ChakraCore. I expect the typical scenario of ChakraCore doesn't care our OOP JIT like for TypeScript, so I suggest run ChakraCore PGO training with -oopjit-.

**Comment by Cellule** [comment]
Not only don't we care about oopjit on chakracore, but it is already turned off by default so this flag was already redondant

**Comment by dilijev** [comment]
@ThomsonTan yes, in ChakraFull, OOP JIT is turned on by default so adding a flag to disable it was necessary. Since it was redundant in ChakraCore, whoever added the flag probably expected that using the flag wouldn't be a problem, except they didn't realize we POGO ChakraCore Release builds, rather than Test builds. In practice, it was a problem. Now the flag has been moved to ChakraFull POGO automation and refactored out of this script, replaced with an optional script param in this script which allows the ChakraFull training automation to still pass this flag.
