### ISSUE TITLE
WASM: Linux Support

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2220]
Linux support would allow us to use a wider variety of static and dynamic analysis tools on the WASM code.

**Comment by Penguinwizzard** [comment]
Significantly improved with #2381; however, proper support depends on #2378.

**Comment by obastemur** [comment]
@Penguinwizzard #2473 might take care of this? We have some tests there not yet running on xplat. Added a xplat-todo there.

**Comment by obastemur** [comment]
Closing this one. Wasm is enabled on xplat. The state of wasm support is not as well as it is on Windows yet but there are other open items to track that and todo notes to complete.
