### ISSUE TITLE
Change ch.exe to comply with gnu getopt_long argument syntax

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#223]
http://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Options.html

ch.exe accepts both forward slash and a single dash for all switches recognized.  Reasonable given Chakra has been a Windows only project up until.

However, now that we are porting to linux and expect to later port to other POSIX platforms it feels like a good idea to consider conforming command line syntax to that of gnu gnu getopt_long syntax. *nix tools widely adhere to this syntax and it is reasonable to presume that *nix users are very comfortable with this syntax, to the point that using a tool that does not conform will be aesthetically jarring.

Functionally it may not be a problem for plugging ch.exe into scripts and other *nix tools, but it will probably frustrate many a user.  Perhaps it could also impose complication on scripts/tools so that they can support the windows-esque syntax.

I believe this is not a priority but something worth considering as the linux port comes online.

**Comment by ianwjhalliday** [comment]
@digitalinfinity @jianchun cc @bterlson

**Comment by obastemur** [comment]
+1

In addition to this, ch.exe can be extended for handling command line arguments (separate github issue?). This is disabled for now for release builds.

**Comment by tcare** [comment]
Yes!! I would love this. In fact I would love for many of our internal tools to adopt this. I was talking about this to some team members the other day. All my tools are now being written to conform to this format.

@obastemur typically we would use Test builds for that purpose. I think that issue may have been discussed elsewhere on here though, I don't remember the outcome.

**Comment by dilijev** [comment]
@obastemur The test builds include all of the flags as well as the performance of release. The release build removes those flags because they are unneeded and cause binary bloat to support them.

**Comment by ianwjhalliday** [comment]
Support for double dashes was added in #239.  We aren't going to redo how the switches work so that change feels like a good fix for this issue.  Closing this issue.
