### ISSUE TITLE
`NavigatorLanguage.language` property reports format language instead of Windows display language

### ISSUE THREAD

**Issue by mavsic** [Microsoft/ChakraCore#2235]
**Steps to reproduce:**

1. Go to Settings > Time & Language > Region & Language > Additional date, time, & regional settings > Change date, time, or number formats.
2. Choose any format other than "Match Windows display language". In my case format is Russian (Russia), and my display language is English (United States).
3. Run [this demo](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_language).

**Result:**  
`NavigatorLanguage.language` is `ru-RU` which is format language.

**Expected result:**  
`NavigatorLanguage.language` is `en-US` which is Windows display language.

**Comment by mavsic** [comment]
This repository might be a wrong place to report this issue. In that case I've also [opened a similar issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10254685/) in Microsoft Edge bug tracker.

**Comment by dilijev** [comment]
Thanks for filing that issue over on the Edge issue tracker. You're correct that this issue is external to ChakraCore. I'll tag and close this issue. We'll track the status of the Edge issue you opened.
