### ISSUE TITLE
Follow up #110: rlexe.xml tags: Remove support for old architecture and type terms.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2240]
Work item to follow up #110:

Summary:

At some point in the future (when all active development branches support the new terms), we will deprecate the use of the old terms and remove support for them. At that time, all remaining uses of the old terms will be replaced with the new terms and support will be dropped from the scripts.

Explanation:

At the moment, we have active development branches both internally and externally (for example, release/1.4) which will not support the new rlexe.xml tags added as a result of the #110 work item because it is too expensive to switch all active dev branches to the new terms, and it is much easier to make the change in the `master` branch in a backwards-compatible way, and wait until all branches without support are merged into master and active development stops on said branches.

Once all active development branches are ahead of the change to fix #110, we can remove support for the old terms by removing the logic from the scripts which supports the old terms and in the same PR, also rename all remaining instances of the old terms to the new terms.

---

The `Waiting` label will be removed when this work item becomes actionable.

/cc @ianwjhalliday @RexSong

**Comment by agarwal-sandeep** [comment]
@dilijev Should we do just #110 and close this?

**Comment by dilijev** [comment]
Yes, this is risky. #110 is enough.
