### ISSUE TITLE
raspberry-pi: ChakraCore ARMv7 build - linker out of memory

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#2262]
When compiling ChakraCore on Raspberry PI 2 B+ (clang 3.8 arm), linker fails with `out of memory` error.

A temporary solution is to `strip -x` the static lib files. However,  we need a proper solution here.

p.s.: This may not be a clang 3.8 for ARM issue. Cross compiling on a host with better resources don't show this problem.

**Comment by woachk** [comment]
You can try to add more swap space for the linker to not fail.
I don't really consider this as an project issue. :)

**Comment by obastemur** [comment]
@woachk see this issue is marked as 'Accepting PRs' . I would happily see your PR fixing this issue!

**Comment by woachk** [comment]
@obastemur it's simply that the project is too big to compile in whatever remains of 1GB of RAM after operating system usage. :)
Swap files can be used to continue the compilation, or simply making CMake error out with less than 2GB of RAM.

**Comment by obastemur** [comment]
https://github.com/Microsoft/ChakraCore/commit/6a8f26e fixes the memory usage issue.

In addition to limited memory, empty disk space was an issue too. I have 32 GB SD card and somehow forgot expanding the disk image. Following the steps below on Ubuntu MATE (armv8) took care of the problem.

First, you better check whether the disk was already expanded or not -> ```df -h```

If not;

IMPORTANT: I'm sharing the steps below to help others with similar problems. After running the steps below, I have continued to use my existing system without a problem. However, deleting partitions etc. are risky stuff and I don't take responsibility. If you follow the steps below, do it at your own risk!

```
$ > su
$ > fdisk /dev/mmcblk0
# lets delete the second partition
> d
> 2
# and recreate it using the max values (default values are the max ones)
> n
> p
> 2
> press enter couple of times
# it's time to write the changes
> w
# now reboot
> reboot
```

Once the system is restarted;

```
$ > su
$ > resize2fs /dev/mmcblk0p2
$ > reboot
```

next time you should see the changes by running ```df -h```

Closing the issue. @woachk thanks for the discussion.

**Comment by obastemur** [comment]
Another option;

I wanted to give a shot with a board with 512Mb RAM on it and this time I needed a swap file to boost the available memory on the system.

In order to create a 1Gb swap file on a Debian/Ubuntu etc.. (I assume it should also work for some others)

```
> su
> dd if=/dev/zero of=/var/swap_memory.img bs=1024k count=1024
> mkswap /var/swap_memory.img
> chmod 0600 /var/swap_memory.img
> swapon /var/swap_memory.img
```

Now, run ```free`` command and you will see the additional resources there.

**Comment by tibitoth** [comment]
@obastemur Is there any guide how to build ChakraCore for Raspberry Pi 3?
