### ISSUE TITLE
Assertion failure: "_cardTable" when memory address space is limited to 2GB

### ISSUE THREAD

**Issue by nth10sd** [Microsoft/ChakraCore#2268]
Save the following code as a python file, create an empty "empty.js" file, update the path of the chakracore binary and run it:

```
import os
import subprocess

def f1():
    import resource  # module only available on POSIX

    GB = 2**30  # Limit address space to 2GB
    resource.setrlimit(resource.RLIMIT_AS, (2*GB, 2*GB))

# Update the following line to your "ch" location
chakracoreShell = os.path.join(os.path.expanduser('~'), 'chakracore', 'BuildLinux', 'Debug', 'ch')
subprocess.check_output([chakracoreShell, 'empty.js'], preexec_fn=f1)
```
You will get the following assertion failure:
ASSERTION 79532: (/home/skywinlinvm/chakracore/lib/Common/Memory/RecyclerWriteBarrierManager.cpp, line 69) _cardTable
 Failure: (_cardTable)

The assertion failure still exists if the resource.RLIMIT_AS value is increased to 33*GB.

The assertion failure changes to "ERROR: ChakraRTInterface::JsCreateContext(runtime, &context) failed. JsErrorCode=0x20001 (JsErrorOutOfMemory)" if the resource.RLIMIT_AS value is increased to 34*GB.

The assertion failure goes away if the resource.RLIMIT_AS value is increased to 35*GB. Tested on Python 2.7.12 and Ubuntu Linux 16.04.1 LTS.

**Comment by nth10sd** [comment]
I had run this in a VM with 8GB RAM and the version of Ubuntu I have is a 64-bit version.

**Comment by obastemur** [comment]
@nth10sd Thanks for reporting this issue!
