### ISSUE TITLE
creating an object from JavaScriptFunction and invoke different function. 

### ISSUE THREAD

**Issue by oguzhankarsli** [Microsoft/ChakraCore#2271]
Hi,
i written a script file and c# codes which is runned script.
i wanna invoke  different function in javascript from C#.
How can i do it?  

c# code:   

```
var runtime = new JavaScriptRuntime();
var engine = Runtime.CreateEngine();

var script = FileHelper.ReadJavaScriptFromFile("script.js");
var javaScriptFunction = engine.EvaluateScriptText(script);
var javaScriptValue = javaScriptFunction.Invoke(Enumerable.Empty<JavaScriptValue>());
```

script.js file:

```
function abc(){
xyz();
mno();
}

function xyz(){

}

function mno(){

}
abc();
```

Example: 

```
javaScriptFunction.abc();
javaScriptFunction.xyz();
javaScriptFunction.mno();
```

Is this example possible ?

**Comment by EdMaurer** [comment]
See [this documentation.](https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore)

**Comment by alexgwolff** [comment]
You can try something like this
In this example I wanna use JSON.parse() and JSON.stringfy() from javascript.

### Get Global Object 
``` cs
JavaScriptValue global = JavaScriptValue.GlobalObject; 
```

### Get object JSON from Global Object 
``` cs
JavaScriptValue jsonObject = global.GetProperty(JavaScriptPropertyId.FromString("JSON"));
```

### Get parse function  - JSON.parse()
``` cs
JavaScriptValue parse = jsonObject.GetProperty(JavaScriptPropertyId.FromString("parse"));
```
### Get stringify  function - JSON.stringify()
``` cs
JavaScriptValue stringify = jsonObject.GetProperty(JavaScriptPropertyId.FromString("stringify"));
```

### Now use
``` cs
var json = parse.CallFunction(global, JavaScriptValue.FromString("{"json" : 1}"));
```
or
``` cs
JavaScriptValue anyObject;
var stringify = parse.CallFunction(global, anyObject);
```

In your case, you should add your script file in context
See [JSRT](https://github.com/Microsoft/ChakraCore/wiki/JsRunScript)

**Comment by MikeHolman** [comment]
Closing this as it seems to be answered, feel free to reopen if you are still having issues.
