### ISSUE TITLE
xplat: JsDiagEvaluate signature

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#2282]
Following up #2251, we plan to change `JsDiagEvaluate` signature to take `JsValueRef` string, and remove `JsDiagEvaluateUtf8`.

//cc: @liminzhu @agarwal-sandeep @obastemur

**Comment by obastemur** [comment]
@jianchun Thanks for opening this issue.

Better land this one before 2.0 release? I will send a PR next week to speed things a bit up on this.

**Comment by liminzhu** [comment]
Thanks for driving this guys 👍 . Would external arraybuffer also work as valid input?
