### ISSUE TITLE
Missing function Element.closest(selector)

### ISSUE THREAD

**Issue by ericf01** [Microsoft/ChakraCore#2286]
Every web browser I've tested other than MS Edge supports JavaScript statements of the form:
    variable = Element.closest(selector)

Example: :    var targetElem = this.nodeField.closest('div');   // Get field's closest containing div

The list of supporting browsers includes Mozilla, Chrome, and Safari on desktop, iOS, and Android, and IE 11 on Windows.  

However, executing the above JavaScript statement in MS Edge results in the following error:
SCRIPT438: Object doesn't support property or method 'closest'

This forces me to add a conditional function prototype for "closest" to my application so that it will run successfully on MS Edge, which I would much prefer not to do.

**Comment by dilijev** [comment]
Looks like this is an API defined by the DOM:
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

Please open this issue on Edge as described [here](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

**Comment by EdMaurer** [comment]
Not an issue in ChakraCore as indicated by dilijev.

**Comment by ericf01** [comment]
As requested by dilijev, I’ve opened new Issue #10320716  Edge Browser missing function Element.closest(selector) at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10320716/ 


 

I appreciate your response, and  apologize that it was not obvious to me that this is an Edge platform issue rather than a ChakraCore issue.

**Comment by digitalinfinity** [comment]
Thanks @ericf01- and no reason to apologize, it's not always obvious whether something is a Edge issue or a Chakra issue 😄 Thanks again for reporting the issue to both us and Edge!
