### ISSUE TITLE
Select with selectedIndex = -1 still shows the first option

### ISSUE THREAD

**Issue by DzmitryShylovich** [Microsoft/ChakraCore#2290]
**Current behavior**
As u can see on the screenshot http://prntscr.com/dotsln select has `selectedIndex` equals to -1 `value` is empty, but it shows the first option.
I can workaround it by explicitly calling `document.getElementById('test').selectedIndex = -1;`, but I can't write a test for it because select has all correct properties (`selectedIndex = -1`, `value = ''`).

**Expected behavior**
I think it should never be the case. If select has `selectedIndex` equals to `-1` then it should show a blank line, otherwise it should have `selectedIndex` equals to `0`.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/jZNAV8IMFO5dV4ypmAFE?p=preview
The repro includes angular 2 code, but it's irrelevant to the issue. At first I thought it's a bug in angular, but it works as expected in Chrome/Firefox.

**Browser:**
IE 9-11/Edge

**Comment by digitalinfinity** [comment]
Hi @DzmitryShylovich - thank you for opening this issue. However, this does not appear to be an issue in Chakra- this sounds like an Edge issue. Please open an issue on the Edge team by following these [steps](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

**Comment by DzmitryShylovich** [comment]
@digitalinfinity done. should I close this one?

**Comment by digitalinfinity** [comment]
Yes please- thanks again for reporting the issue!
