### ISSUE TITLE
Q: Nested Contexts -- Arbitrary depth? Different scripts?

### ISSUE THREAD

**Issue by sidkshatriya** [Microsoft/ChakraCore#2295]
On https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview
> Execution contexts are tied to a particular runtime and execute code within that runtime. Unlike runtimes, multiple execution contexts can be active on a thread at the same time. So a host can make a call into an execution context, that execution context can call back to the host, and the host can make a call into a different execution context.

This is followed by a diagram
<img src="https://github.com/Microsoft/ChakraCore/wiki/images/context.png">

- Is the nesting possible only 2 levels deep? Or can it be arbitrarily deep?
- Can the two contexts run _different_ scripts or do they need to run the same script? In other words, can a single chakracore runtime mimic a CPU which is running separate code streams with access to different data? Another way to ask: can a single chakracore runtime mimic non-premptive execution/green threads?

I'm trying to compare this with V8.

**Comment by obastemur** [comment]
@sidkshatriya AFAIK there is no soft limit on depth.

Context used to separate script A from script B (environment). They can't be executed simultaneously. (under the same Runtime)

**Comment by dilijev** [comment]
FYI @liminzhu

**Comment by liminzhu** [comment]
Apology for joining the party late @sidkshatriya . 

> Is the nesting possible only 2 levels deep? Or can it be arbitrarily deep?

Arbitrary depth. The graph may be kind of confusing. 

> Can the two contexts run different scripts or do they need to run the same script? In other words, can a single chakracore runtime mimic a CPU which is running separate code streams with access to different data? Another way to ask: can a single chakracore runtime mimic non-premptive execution/green threads?

Yes two contexts can run completely different scripts and a runtime represent a single thread of execution and has access to all affiliated contexts (although all the contexts are isolated from each other in principle for obvious security reason).

**Comment by dilijev** [comment]
Closing this question as answered.
