### ISSUE TITLE
IIFE parsing heuristics/performance could potentially be improved

### ISSUE THREAD

**Issue by toddreifsteck** [Microsoft/ChakraCore#2313]
We've seen a number of sites with significant impact in parsing from altering IIFEs to trigger immediate vs. deferred parsing.

@nolanlawson documented a few of these at [https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/], but we've seen many others while reviewing sites including Facebook, Office and PowerBI.

Investing some time to investigate this area of the Parser may be helpful given the growth in JS we continue to see on the web.

**Comment by EdMaurer** [comment]
Accounted for here: #2311
