### ISSUE TITLE
setTimeout(<string>) could be much faster when same <string> is used multiple times

### ISSUE THREAD

**Issue by toddreifsteck** [Microsoft/ChakraCore#2334]
Run the 'RUN LONG STRING' test from the following test page and it can be observed that Microsoft Edge could be faster at running this code.
https://github.com/toddreifsteck/webtests/blob/master/setTimeout/setTimeout.html

Per conversation with @pleath , it appears that the Chakra team has the power to optimize this without any work from the EdgeHtml team.

**Comment by agarwal-sandeep** [comment]
@pleath are we planning to do work for this?

**Comment by pleath** [comment]
This was done a while ago. Strings passed to the ScriptEngine entry point that parses setTimeout arguments get cached.
