### ISSUE TITLE
[xplat] Out of tree build support

### ISSUE THREAD

**Issue by humeafo** [Microsoft/ChakraCore#2338]
I'm building on macOSx, the command I used is:
some_dir/build.sh --xcode --static --icu=/usr/local/opt/icu4c/include --test-build -j=2

after some while console shows:
....
build files have been written to: ~/ChakraCore/BuildLinux/Test

obviously no out of tree build support is added, it's easy for cmake to build out of tree, it'd be more useful if building is default in current dir or there are options to specify the build dir location.

btw, BuildLinux may be changed to BuildMacosx ...

**Comment by obastemur** [comment]
@humeafo `--xcode` option is there to create XCode project. If you want to build Debug/Release etc. you may remove that argument and it should be done.

`Out-of-tree` : We set target build path from build.sh, if you want to provide a custom path option there, it should be fairly easy to contribute. Actually if you directly use our CMake / make stuff, you have all the out-of-tree etc. stuff out of the box but you may have to deal with other custom arguments manually.

You could contribute `custom build target path` support on build.sh though.
