### ISSUE TITLE
new ArrayBuffer((-1 >>> 0) + 1) should not throw RangeError in 64-bit

### ISSUE THREAD

**Issue by suwc** [microsoft/ChakraCore#2339]
Snippet: console.log(new ArrayBuffer((-1 >>> 0) + 1))
Expected output: ArrayBuffer { byteLength: 4294967296 }
Actual output: RangeError: Array length must be a finite positive integer

**Comment by liminzhu** [comment]
#### Chakra
RangeError: Array length must be a finite positive integer

#### SpiderMonkey
RangeError: invalid array length

#### V8 --harmony
RangeError: Array buffer allocation failed

**Comment by MikeHolman** [comment]
Nobody supports 4GB typed array, so this isn't really an issue.
