### ISSUE TITLE
ES Module: import error "Let/Const redeclaration"

### ISSUE THREAD

**Issue by Aqours** [Microsoft/ChakraCore#2347]
OS: Windows 10 Ver 1607 (14393.567)
Edge: 38.14393.0.0 (EdgeHTML: 14.14393)
Flags: Enable experimental JavaScript features [Ref](https://blogs.windows.com/msedgedev/2016/05/17/es6-modules-and-beyond/#9ezxJCRJPZxvBl1g.97)

Code-1
```html
// index.html
...
<script type='module' src='index.js'>
...

// index.js
import sum from './math.js';
console.log(sum(1, 2));

// math.js
export default function sum(a, b) { return a + b; }
```

It will report an error: Let/Const redeclaration.

Code-2
```html
// index.html
...
<script type='module' src='index.js'>
...

// index.js
import sum from './math.js';
console.log(sum(1, 2));

// math.js
function sum(a, b) {
    return a + b;
}
export default function (a, b) { return a + b; }
```

It will report an error: Let/Const redeclaration.

**Comment by dilijev** [comment]
Could you check if this repros on a recent preview build of Windows?
/cc @boingoing re: modules

**Comment by boingoing** [comment]
This looks like https://github.com/Microsoft/ChakraCore/pull/1292 which has been fixed and released via Windows Insider flights. The fix has not made it into a retail Windows release, yet, though. If you install a Windows Insider flight such as the recently released build 15002, this should be working as expected.

**Comment by Aqours** [comment]
Can I use Microsoft edge insider without Windows insider?

**Comment by dilijev** [comment]
@Aqours I think that is not possible, unfortunately.
