### ISSUE TITLE
Compiling on Visual Studio 2017 RC (apparently requires Win 8.1 SDK)

### ISSUE THREAD

**Issue by PaulGGriffiths** [Microsoft/ChakraCore#2348]
I'm receiving compiler errors on Visual Studio 2017.
Updated configuration Windows SDK Version to 10.0.14393.0.

```
1>------ Build started: Project: CoreManifests, Configuration: Release x64 ------
1>mc : error : Internal error - ErrorCode=3, SubErrorCode=4294967295, Message=
1>Performing Custom Build Tools
1>Done building project "CoreManifests.vcxproj" -- FAILED.
2>------ Build started: Project: Chakra.Jsrt.Core, Configuration: Release x64 ------
3>------ Build started: Project: Chakra.Runtime.Base, Configuration: Release x64 ------
3>RuntimeBasePch.cpp
3>f:\chakracore-master\lib\common\Core/EtwTraceCore.h(68): fatal error C1083: Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory
3>Done building project "Chakra.Runtime.Base.vcxproj" -- FAILED.
```

**Comment by digitalinfinity** [comment]
@PaulGGriffiths where did you install VS2017 from?

**Comment by PaulGGriffiths** [comment]
Visual studio.com is where i got it from.

Sent from my Windows Phone
________________________________

**Comment by digitalinfinity** [comment]
Sorry, what version? The RC?

**Comment by PaulGGriffiths** [comment]
Yes

Sent from my Windows Phone
________________________________

**Comment by dilijev** [comment]
Related to #2096

**Comment by juancarlosbaezpozos** [comment]
I was able to build the chakracore x64 under visual studio 2017 with some fixes around the include paths and other tools. You must install: VC++ 2015 toolset, windows universal crt sdk, windows 10 sdk, windows 8.1 sdk, windows universal C runtime and retarget the solution except for the "platformAgnostic" project.

Once installed the Include directories property must set to:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\atlmfc\include;$(IncludePath)

**Comment by Oceanswave** [comment]
On a clean VM with VS2017 RTM, I was able to build latest by including "Desktop Development with C++" and selecting the optional "Windows 8.1 SDK and UCRT SDK" package

**Comment by dilijev** [comment]
Sounds workable, but I wonder if we could make our solution compatible with VS 2017 without the Windows 8.1 SDK.

**Comment by tcare** [comment]
I think this is an issue in VS where it defaults to 8.1 SDK.

**Comment by curtisman** [comment]
#3067 should fix this.
