### ISSUE TITLE
Destructuring assignment target should obey const semantics

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#235]
The assignment target should obey `const` semantics.

Test262 bug es6id: 12.14.5.4
features: [const]

```js
const c = 1;

assert.throws(TypeError, function() {

({ a: c } = { a: 2 });

});
```

**Comment by akroshg** [comment]
We throw ReferenceError here.

**Comment by akroshg** [comment]
Closing this as it is similar to #355
