### ISSUE TITLE
exponentiation incorrect for inputs that produce subnormal numbers

### ISSUE THREAD

**Issue by michaelficarra** [Microsoft/ChakraCore#2353]
In Edge 14 on Windows 10, `Math.pow(2, -1074)` produces `0`, while on all other engines, it returns the subnormal double value `5e-324`. This is not the only set of inputs that causes this behaviour. It appears that all inputs which should produce a subnormal number instead produce `0`.

**Comment by obastemur** [comment]
I'm unable to observe this problem with ChakraCore `ch`. Result there is also `5e-324`

**Comment by dilijev** [comment]
Current flights of edge also produce `5e-324`

Closing as Fixed / No Repro.

**Comment by michaelficarra** [comment]
I've also confirmed that in a recent build of ChakraCore I also get `5e-324`. Looks like the problem has been fixed somewhere between the version included in Edge 14 and `master`. FWIW, I have not tested on a variety of architectures, so this problem may still exist in non-x86 architectures or on CPUs without `AutoSystemInfo::Data.SSE2Available`.
