### ISSUE TITLE
Error on ch.exe using -ES6Module

### ISSUE THREAD

**Issue by alexgwolff** [Microsoft/ChakraCore#2359]
I'm trying to use a simple JS file that includes this:

### moduleExport1.js

``` javascript
export function fnTest () { };
``` 
But I get this error 

### Console output

```
SyntaxError: Syntax error
        at code (moduleExport1.js:1:1)
````
### cmd 
> ch.exe -ES6Module moduleExport1.js

Any ideia?

**Comment by akroshg** [comment]
Please see usage as in 
https://github.com/Microsoft/ChakraCore/blob/master/test/es6/moduletest1.js#L5

So you need to create another file say test.js
and put 
```js
WScript.LoadScriptFile("moduleExport1.js", "module");
```
call 
```ch.exe -ES6Module test.js```

**Comment by alexgwolff** [comment]
Okay, this is working.
But i wanna use "import"
like here https://github.com/Microsoft/ChakraCore/blob/master/test/es6/passmodule.js

**Comment by akroshg** [comment]
You need to create another file which has your exports, and from a different file you can import those exports.
in your example 
**test.js**
```js
WScript.LoadScriptFile("test2.js", "module");
```

**test2.js**
```js
import {fnTest} from 'moduleExport1.js'
WScript.Echo(fnTest());
```

/cc @boingoing

**Comment by alexgwolff** [comment]
But use 'WScript.LoadScriptFile ' is always necessary? I ask this because doing an engine using the Chakra, and want to use the ' import ' but that will be declared in my 'main' script doesn't want to have another js file using 'WScript.LoadScriptFile ' or any other similar method

**Comment by akroshg** [comment]
For now that is only way it is supported from ch.exe. You can try WScript.LoadModule (some example can be found at core\test\es6 folder).

**Comment by akroshg** [comment]
Closing this issue.
