### ISSUE TITLE
es6 modules - problems with circular dependencies

### ISSUE THREAD

**Issue by delmarwichnieski** [Microsoft/ChakraCore#2373]
Hi all

this is my firts post

I'm having problems with circular dependencies
Microsoft Edge 39.15002.1001.0
Microsoft EdgeHTML 15.15002

Version 1607
Build SO 15002.1001

What is the right forum for edge support?

Could it be here?
If not, sorry!
If yes, could I send link from pastebindotcom with sample code?

Thank you very much

**Comment by digitalinfinity** [comment]
Hi @delmarwichnieski - welcome to the ChakraCore repo! It's not clear what your issue is so feel free to post a link to your sample code and we can give guidance. 

For future reference, if it's a JavaScript/Chakra issue, then this is the right forum. If it's an issue with Edge itself, you can follow the [instructions here](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) to file Edge issues.

**Comment by delmarwichnieski** [comment]
Sorry, the code is in pt-br. But the important parts are easy to understand.

index.html
http://pastebin.com/ZcfazmPB

main.js
http://pastebin.com/9Fp4fpUk

login.js
http://pastebin.com/FgcMC4TY

login.escola.js
http://pastebin.com/LiKQ5m5m

login.utils.js
http://pastebin.com/ukAT8aaM

ajax.js
http://pastebin.com/JZmapfeU


The problem occurs when I uncomment the 3rd line in the login.escola.js file.

If commented, everything is working perfectly.
![deltaescolarjs_working](https://cloud.githubusercontent.com/assets/5343722/21930983/ad2c8ea4-d977-11e6-8164-64cc3934ed29.png)


If uncommented, no js file is loaded.
![deltaescolarjs_not_working](https://cloud.githubusercontent.com/assets/5343722/21931052/155c81f0-d978-11e6-8820-c91c5dec2c02.png)

**Comment by digitalinfinity** [comment]
@boingoing @bterlson can one of you take a quick peek at this issue please?

**Comment by bterlson** [comment]
@delmarwichnieski do you see any errors in the console?

**Comment by delmarwichnieski** [comment]
@bterlson There are no errors in the console. I will test in 15007 and I will come back with new status.

**Comment by delmarwichnieski** [comment]
same issue with build 15007.

**Comment by bterlson** [comment]
@delmarwichnieski would it be possible to get a .zip of the repro? Email me (see my profile) or join us on gitter...

**Comment by delmarwichnieski** [comment]
@bterlson I sent to your email.
I'm running with Apache Lounge 2.4.25 x64 VC14 e PHP 7.1.0 x64 TS
Apache and php are working perfectly.
The php code is ok although it is not POO.
From the server comes JSON only.
This project is SPA, with fetch API, modules and template strings / template literals.
Everything is ok, the only problem is the circular reference between the modules.
When programming the first circular reference, no js file is loaded.

**Comment by delmarwichnieski** [comment]
This week, I will test build 15014 and also the new SystemJS 0.20.0 / es-module-loader 2.0.0 release at the same code, to see if I get any errors.

**Comment by delmarwichnieski** [comment]
I'm happy to announce that the code is working with SystemJS 0.20.0 and the plugin-babel 0.0.19. No erros in console.

![esmodules_systemjs_babel-plugin_01](https://cloud.githubusercontent.com/assets/5343722/22269400/54916ee6-e272-11e6-8fee-fd6151eff082.png)
![esmodules_systemjs_babel-plugin_02](https://cloud.githubusercontent.com/assets/5343722/22269405/5e414420-e272-11e6-98d4-e6e72ea343e7.png)

**Comment by delmarwichnieski** [comment]
The same problem with
Microsoft EdgeHTML 15.15031
Microsoft Edge 40.15031.0.0

**Comment by boingoing** [comment]
@suwc Is this fixed?

**Comment by suwc** [comment]
@boingoing this looks duplicate to what has been fixed in https://github.com/Microsoft/ChakraCore/pull/2822

**Comment by suwc** [comment]
@digitalinfinity yes, I will have to find out about that once I can confirm.

**Comment by suwc** [comment]
@boingoing @digitalinfinity 
I confirmed this has been fixed in our internal staging branch 16189.1002.170512-2143 (Microsoft Edge 41.16189.1002.0).
But 16199.rs_prerelease.17513-2252 (Microsoft Edge 41.16199.1000.0) doesn't contain the fix.
In other words, it may not be in flight yet.

**Comment by delmarwichnieski** [comment]
@boingoing @bterlson @suwc  @digitalinfinity 

An additional test that could be predicted, is the use of repeated circular imports, due to reuse.

[es-module-crash.zip](https://github.com/Microsoft/ChakraCore/files/1033264/es-module-crash.zip)




Similar to attachment

**Comment by delmarwichnieski** [comment]
@suwc @bterlson @boingoing  16215.1000 contains the fix?

**Comment by suwc** [comment]
@delmarwichnieski I will try it and get back to you.

**Comment by suwc** [comment]
@delmarwichnieski, This is fixed in 16215.rs_prerelease.170603-1840 (Microsoft Edge 41.16215.1000.0, Microsoft EdgeHTML 15.16215).
(Also es-module-crash.zip posted above has been tested and no repro after fix)

**Comment by suwc** [comment]
Fixed in https://github.com/Microsoft/ChakraCore/pull/2822
