### ISSUE TITLE
WScript.LoadScript variable name conflict assert

### ISSUE THREAD

**Issue by Cellule** [microsoft/ChakraCore#2385]
`const a = WScript.LoadScript("function a(){}");` causes assert

ASSERTION 26992: (c:\projects\chakra\core\lib\runtime\Language/InlineCache.inl, line 256) !isRoot || RootObjectBase::FromVar(object)->GetRootPropertyIndex(propertyId) == DynamicObject::FromVar(object)->GetTypeHandler()->InlineOrAuxSlotIndexToPropertyIndex(u.local.slotIndex, false)

Same happens with `let a`, but not with `var a`. We are fine when using `const a = eval("function a() {}")` where we throw a javascript error.

**Comment by MikeHolman** [comment]
Looks fixed
