### ISSUE TITLE
ChakraCore on ARM OpenWRT possible?

### ISSUE THREAD

**Issue by cumakeen** [Microsoft/ChakraCore#2394]
Heard about ChakraCore / ARM at a dev. meetup lastweek. Is there a particular plan on reducing memory consumption in a limited environment? Couldn't find much details online.

**Comment by obastemur** [comment]
@cumakeen IIRC not so many `arm` devices around for open-wrt (mostly MIPS).. 

So.. what is the origin of interest? How limited? (16?/32Meg flash / ram??)

**Comment by cumakeen** [comment]
16mb ram, armv7 chipset, no fpu. Flash storage is less restricted.

Interest; move our application to node v > 0.10.x

**Comment by obastemur** [comment]
@cumakeen hard to say yes/no or possible/impossible at this very moment. The arm work is experimental and we are focused on our upcoming cross platform release. Thanks for opening this. Surely we are going to take this issue into consideration prior to releasing our next cross platform roadmap.

Keep in touch!

Closing for now.
