### ISSUE TITLE
Strange String.fromCharCode behavior

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#2397]
```
var buffer = new ArrayBuffer(2);
var view = new Uint8Array(buffer);
view.fill(0);
view[0] = 65;
// view[1] -> 0

var str = String.fromCharCode.apply(null, view);

str += "B"

console.log(str.length); // -> OUTPUT: 3 -> B is included
console.log(str); // OUTPUT: `A`  -> char('A') + char(0) + char('B')

console.log(str.indexOf('B')); // OUTPUT: 2

str = [str, 'end'].join('-');
console.log(str); // OUTPUT: 'A' -> char('A') + char(0) + char('B') + "-" + "end"
console.log(str.length); // OUTPUT: 7
```

Spec (http://www.ecma-international.org/ecma-262/6.0/#sec-string.fromcharcode) says `Let length be the number of elements in codeUnits.`

Output(length) is matching to what spec says. However, see other cases above as the rest of it feels unexpected.

Shouldn't we, at some point drop char(0) ?

**Comment by obastemur** [comment]
We have a similar behavior with SM. V8 drops `char(0) and the rest` on string concat.

**Comment by dilijev** [comment]
In latest Chakra, Edge 38.14393, Firefox Nightly 56, and Chrome 56 - I'm seeing all the same behavior as defined by this modified test case:

```js
function assertEqual(a, b) {
    if (a !== b) {
        console.log(`Failed: expected ${b}, actual ${a}`);
    }
}

var buffer = new ArrayBuffer(2);
var view = new Uint8Array(buffer);
view.fill(0);
view[0] = 65;
// view[1] -> 0

var str = String.fromCharCode.apply(null, view);

str += "B"

assertEqual(str.length, 3); // B is included
assertEqual(str, 'A\x00B'); // char('A') + char(0) + char('B')

assertEqual(str.indexOf('B'), 2);

str = [str, 'end'].join('-');
assertEqual(str, 'A\x00B-end');
assertEqual(str.length, 7);

console.log('PASSED');
```

All print PASSED and no failures. So, I'm not sure what difference in behavior you're seeing. I think in JavaScript strings, we don't treat a null character `\x00` as a null terminator (truncating the string at that point), but instead we treat it as a character in the string. If we did treat it as a null terminator, I think that would be considered a bug.

**Comment by obastemur** [comment]
> I think in JavaScript strings, we don't treat a null character \x00 as a null terminator (truncating the string at that point), but instead we treat it as a character in the string. 

This is the part has confused me. I'm not sure if v8 version I had checked was the part of latest Chrome. If they all have the same behavior and this doesn't sound like an issue, I also don't see a reason to keep this open on CC repo though. 

It's just `char(0)` is NULL (ASCII) and having it represented in a JavaScript String as if it's just another char made me think there is something wrong there.

**Comment by ljharb** [comment]
If v8 is terminating on char 0, then please file a bug with v8 - null characters don't mean anything in JS.
