### ISSUE TITLE
Exponentiation operator should throw early syntax error for unary negation without parens

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#24]
As per exponentiation stage [3 spec] (http://rwaldron.github.io/exponentiation-operator/#unary-operators) -5**2 should be an early error. This is a spec update from [September TC39 meeting](https://esdiscuss.org/topic/september-tc39-meeting-notes).

**Comment by nicolo-ribaudo** [comment]
Isn't this issue fixed by 81356aaec1f268d4b2ca51d1c12fbc8799db9bf6?

**Comment by abchatra** [comment]
Yes, fixed by #427
