### ISSUE TITLE
Arrow function parameter destructuring "Use before declaration" error when parameter is only used in an inner function

### ISSUE THREAD

**Issue by erikdesjardins** [Microsoft/ChakraCore#2401]
Edge 39.15014.1000.0 / EdgeHTML 15.15014

These both error:
```js
(({ t }) => {
    (() => t)(); // "Use before declaration"
})({});

(([t]) => {
    (() => t)(); // "Use before declaration"
})([]);
```

But these don't:
```js
// normal function
(function({ t }) {
    (() => t)();
})({});

// referenced in outer function
(({ t }) => {
    t;
    (() => t)();
})({});
```

**Comment by akroshg** [comment]
Did you try with chakracore? @aneeshdk it seems this is fixed, can you clarify?

**Comment by BenMcGarry** [comment]
Do you know which version of Chakra is shipping with 15014?

**Comment by erikdesjardins** [comment]
Ah, yep, it works with ChakraCore v1.4.0, v1.3.2 and v1.2.3. I assumed that Edge would have one of those versions since they came out a month before 15014; sorry about that.

**Comment by akroshg** [comment]
@BenMcGarry I am not aware of that.
The latest Windows 10 insider preview should have the fix.
