### ISSUE TITLE
Can't build on VS2015 when paths have spaces , missing 'microsoft-scripting-chakra-instrumentationevents.h'

### ISSUE THREAD

**Issue by JohnathanNorman** [Microsoft/ChakraCore#2422]
following the instructions in the doc and I can't build. I also can't seem to find this header file in the repo. 

Severity	Code	Description	Project	File	Line	Suppression State
Error		0x2 trying to open file <Studio>.	CoreManifests	C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-master\manifests\mc	1	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.WasmReader	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Math	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.ByteCode	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Language	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Common.Core	C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-master\lib\Common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Debug	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Library	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Types	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.Base	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Common.Common	C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-master\lib\Common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Common.Memory	C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-master\lib\Common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Parser	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Backend	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Jsrt	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Jsrt.Core	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Jsrt.Core	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.JITServer	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	Chakra.Runtime.PlatformAgnostic	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	GCStress	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	ChakraCore	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	GCStress	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	ChakraCore	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	GCStress	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	ChakraCore	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	C1083	Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory	GCStress	c:\users\bill\documents\visual studio 2015\projects\chakracore-master\chakracore-master\lib\common\Core\EtwTraceCore.h	68	
Error	LNK1181	cannot open input file 'C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-master\Build\VcBuild\bin\x86_test\ChakraCore.lib'	NativeTests	C:\Users\bill\Documents\Visual Studio 2015\Projects\ChakraCore-master\ChakraCore-

**Comment by dilijev** [comment]
Since we all use VS 2015 (dev14) and build and test with the same, I'm going to assume this is not a build bug and is most likely a client config issue. I'm tagging this issue with Question so people can chime in to help.

Nothing jumps out at me as a possible explanation.

Which operating system are you using?

@tcare @boingoing Any idea what might be happening here?

**Comment by JohnathanNorman** [comment]
Windows 10 , Self hosting RS2 
 I’m simply downloading the zip from GitHub, setting my release and build (x64/release) and compiling.  Same issue on both my desktop and laptop. 
Both running VS 2015 enterprise.

**Comment by dilijev** [comment]
Alright, I'll also tag this as a Build Bug to get more attention until we can rule out an issue on our end.

**Comment by WickedA** [comment]
Unless I'm missing something, this looks like an issue related to how the build system handles paths with spaces. I can build ChakraCore just fine, either through Visual Studio or msbuild, from paths without spaces.

When the path has a space in it, on the other hand, I get the same errors @JohnathanNorman is:

```
mc : error : 0x3 trying to open file <Copy\Build\VcBuild\obj\x86_release\CoreManifests\>.
c:\chakracore - copy\lib\common\Core/EtwTraceCore.h(68): fatal error C1083: Cannot open include file: 'microsoft-scripting-chakra-instrumentationevents.h': No such file or directory
```

Build logs: [Visual Studio](https://gist.github.com/WickedA/15d04dc606599b42bba9dcb40b3ce86c), [MSBuild](https://gist.github.com/WickedA/3d07d4a8d91c18ec732cc1db98c57ed3).

**Comment by JohnathanNorman** [comment]
Yes that is the issue
 I changed directories and it works now.

**Comment by dilijev** [comment]
Good to know there's a workaround! I imagine we should be able to fix the build to work with paths with spaces.

**Comment by dilijev** [comment]
Removing question as this has been identified as a build bug and there is a fix in review.
