### ISSUE TITLE
Yield register change after reparse for debugger

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#2437]
If the debugger is attached while running a yielded function, it is possible to modify the YieldRegister while reparsing for debugger.
When resuming the yield, we use the incorrect register and read wrong data resulting in undefined behavior (crash in the repro code).

Repro Code
```js
function attach() {
  return new Promise(function (r) {
    WScript.Attach(r);
  });
}

async function mainTest() {
  for (let i = 0; i < 1; ++i) {
    await attach();
  }
}
mainTest();
```

**Comment by MikeHolman** [comment]
@agarwal-sandeep FYI
