### ISSUE TITLE
xplat: Although Python 2 is required, allow build.sh to take a path to a Python 2 binary in case `python` refers to Python 3.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2462]
From discussion in #2420 

Enable support environment configurations such that `python` will invoke a Python 3 binary. As long as they have a Python 2 binary installed, build.sh (which invokes jstoc.py) should still work, or provide reasonable instructions for enabling it to work which doesn't require rewriting the script.

This requires detecting whether `python` is a Python 2 binary. If so, use it. If not, ask the user to either ensure that `python` refers to a python 2 binary, or specify a path to a Python 2 binary as a parameter of build.sh, so that they don't necessarily have to modify their environment to enable building ChakraCore.

If the parameter is present, confirm that it is a python 2 binary and if so, use it. Otherwise, fall back on the above logic.

**Comment by dilijev** [comment]
@greysAcademicCode might be interested in tackling this issue.

**Comment by greysAcademicCode** [comment]
The logic should probe both `python` and `python2` commands while looking for the required python 2.x executable.

**Comment by dilijev** [comment]
True. Although, depending on the system it might also be py2 versus py3 instead of python2 and python3 (or maybe that's just on Windows -- my Ubuntu VM has them at python2 and python3).

**Comment by greyltc** [comment]
FYI--
[python 2.x is EOL in 2020](https://www.python.org/dev/peps/pep-0373/)
and
[Ubuntu 18.04 LTS and children won't ship with a 2.x installed](https://wiki.ubuntu.com/Python)

Why not move this project to python3 now and be done with 2.x altogether?

**Comment by dilijev** [comment]
2020 is still a fair ways off, but I see your point. I don't have a strong opinion on it other than inertia and engineering time maybe being better spent in other places. @obastemur thoughts?

**Comment by dilijev** [comment]
For the purposes of this issue, making this change to the script will enable easily switching the requirement to python 3 later, so this work will not be counterproductive no matter what the ultimate decision is on version requirement.

**Comment by dilijev** [comment]
As a separate work item, updating the rest of the python scripts to be compatible with both python 2 and python 3 is a good goal for now.

**Comment by obastemur** [comment]
> FYI--
python 2.x is EOL in 2020
and
Ubuntu 18.04 LTS and children won't ship with a 2.x installed
Why not move this project to python3 now and be done with 2.x altogether?

Wasn't that also part of the 12.04 / 14.04 LTS .... plans ? https://wiki.ubuntu.com/Python/FoundationsQPythonVersions 

Once default `python` on Debian/Ubuntu LTS (or candidate) is no longer running our python scripts we may update/fix them or ask for help :)

**Comment by agarwal-sandeep** [comment]
@dilijev don't see a value until some scenario is blocked. We should close this issue.
