### ISSUE TITLE
Operators/instanceof.js timed out on OS X (might consider marking test as Slow)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2463]
https://ci.dot.net/job/Microsoft_ChakraCore/job/release_1.3/job/osx_osx_debug_static_prtest/9/consoleFull#1955843533c7453dd6-bf4f-4ae9-9fca-50f9ec7ab19e

```
[933/1601 60.16] Failed -> Operators/instanceof.js 
19:02:18 
ERROR: Test timed out!
19:02:18 /Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/release_1.3/osx_osx_debug_static_prtest/BuildLinux/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -forceNative -off:simpleJit -bgJitDelay:0 -dynamicprofileinput:profile.dpl.1088 /Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/release_1.3/osx_osx_debug_static_prtest/test/Operators/instanceof.js
```

**Comment by obastemur** [comment]
Finished running the same config ~2000 times and avg was ~4secs. I would like to consider this as a temporary CI slowdown. We had similar problems in the past with the macOS CI.

@dilijev Thanks for opening this. Closing for now. If it repeats on the same test case, we may have more reasons to suspect from something else.
