### ISSUE TITLE
ChakraCore support to Windows 8.1 store apps

### ISSUE THREAD

**Issue by pallammadhukar** [Microsoft/ChakraCore#2464]
Hi Team,

Do you have plans to support chakracore for Windows 8.1 store apps,

Thanks,
Pallam Madhukar

**Comment by pallammadhukar** [comment]
Hi ChakraCore Team,

We have existing Windows 8.1 applications and we wanted to run those applications on windows 8 .1and windows 10. For windows 10 we are using Chakra engine and we ideal for windows 8.1. Please suggest me?

Thanks,
Pallam Madhukar

**Comment by liminzhu** [comment]
You can embed ChakraCore on Win8.1 store apps similar to using Chakra on Win10. There are some APIs that are Chakra-only though, e.g. JsStartDebugging and JsProjectWinrtNamespace.

**Comment by dilijev** [comment]
Looks like this question is answered. Closing.
