### ISSUE TITLE
Modification of a object inside javascript

### ISSUE THREAD

**Issue by angshuman** [Microsoft/ChakraCore#2466]
I have a C# object that I convert to javascript and pass it on to chakra. The javascript code can modify the object. For example

element.active = false;

Is it possible to get a notification of the change/or the new state of the object?

**Comment by pleath** [comment]
@bterlson am I right in thinking Object.observe is DOA? Sounds like that is exactly what @angshuman is looking for. Is there a recommended replacement? My first inclination is to have the JS add a setter to the object, if the goal is just to track the toggling of this one property.

**Comment by bterlson** [comment]
Object.observe is indeed dead, though it's questionable that is the best solution for this. Setters are the typical way if you know the keys users will be setting in advance. If you don't, proxies are the answer.

**Comment by angshuman** [comment]
Proxies look very interesting! Thanks. However is it possible in the C# land to create a proxy with a handler and pass it to the JS world?

**Comment by liminzhu** [comment]
@angshuman I don't think the [current API surface](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Reference) supports creating a proxy natively, but you can walk around this by calling,

``` 
JsRunScript("var p = new Proxy(target, handler);", ..., &myProxy);  
```
And this case you can get the handler to the proxy object in C#.

**Comment by dilijev** [comment]
Looks like this question is answered. Closing.
