### ISSUE TITLE
Symbol.for and strings with embedded nulls

### ISSUE THREAD

**Issue by mrkmarron** [Microsoft/ChakraCore#2471]
Symbol.for internally uses wcscmp for comparing contents of strings used as keys. Thus the following prints  `true` when it should be `false`:
```
console.log(Symbol.for('A\0Z') === Symbol.for('A\0z'))
```
Also verified that v8 prints `false`.

**Comment by ljharb** [comment]
Wait, that should print `true` everywhere. Null chars should not be special.

**Comment by mrkmarron** [comment]
The problem is that any chars after the \0 are ignored (perhaps my example was not very clear). Consider the following program:
```
console.log('A\0AA' === 'A\0ZZ'); //false
console.log(Symbol.for('A\0AA') === Symbol.for('A\0ZZ')) //true -- should be false

Symbol.for('B\0AA'); 
console.log(Symbol.for('B\0ZZ')); //Symbol(B AA) -- should be Symbol(B ZZ) 
```
In the last line the lookup incorrectly determines the keys `'B\0AA'`  and `'B\0ZZ'` are equal due to null char termination in wcscmp (which is being used for the key comparison).

**Comment by ljharb** [comment]
ahh thanks, i missed the capital Z vs lowercase z. Thanks for clarifying :-)
