### ISSUE TITLE
Support -v / --version in `ch` binary

### ISSUE THREAD

**Issue by mathiasbynens** [Microsoft/ChakraCore#2472]
There is currently no way to figure out the version of a given `ch` binary built in release mode:

```
$ ch -v
Error in opening file: -v: No such file or directory

$ ch --version
Error in opening file: --version: No such file or directory
```

Please consider making `-v` / `--version` (and possibly `-h` / `--help`) output something useful.

**Comment by dilijev** [comment]
Duplicate of https://github.com/Microsoft/ChakraCore/issues/109

**Comment by mathiasbynens** [comment]
Whoops, apologies! My GitHub issue-searching skills are lacking…

**Comment by dilijev** [comment]
@mathiasbynens - Note that `-?` displays help.

**Comment by mathiasbynens** [comment]
@dilijev Not in release mode builds, it seems:

```
$ ch -?
Error in opening file: -?: No such file or directory
```

`-h` / `--help` is a more conventional, less surprising argument name. Please consider changing it + supporting it in release mode builds :)

Anyway, I meant to say that `-?` (for test builds) doesn’t output any version information either.

**Comment by dilijev** [comment]
@mathiasbynens That's correct, we don't support any flags in release builds. That decision is because of configuration flags but run-mode flags like printing help or version info should probably be supported in both. Thanks for reminding that any change in this area should enable those flags for release builds as well.

**Comment by dilijev** [comment]
(Also `-?` is probably because of the convention of `/?` in windows cmd commands. We support the leading slash for parameters on Windows only as a legacy feature, so in that sense it still makes sense. There's no conflict with `-h`, `--help`, `-v`, or `--version` so we can add those.

**Comment by dilijev** [comment]
@tcare Believes that this is potentially misleading as the version being reported is really just the version of ch, not the version of ChakraCore that ch loads. At a minimum, we should report `ch version 1.4.1` at this time and do the right thing. Will discuss with others on the team for opinions about how to proceed before merging this.
