### ISSUE TITLE
[Question] Running wasm code in ch.exe?

### ISSUE THREAD

**Issue by d4nnyk** [Microsoft/ChakraCore#2475]
Does running wasm requires special build/runtime flags?

Running `ch.exe test.js` gives error like `ReferenceError: 'WebAssembly' is undefined`

**Comment by dilijev** [comment]
As per the [wasm tests](https://github.com/Microsoft/ChakraCore/blob/master/test/wasm/rlexe.xml), try the `-wasm` flag. @Cellule might have more context. I think it's not enabled by default yet.

**Comment by Cellule** [comment]
@dilijev is correct, at this time you need to pass the flag `-wasm` to add the global `WebAssembly` object in the script to make it available to you.
The pr #2447 is trying to make it on by default in master (needs to update test baseline files before it's ready to merge)

**Comment by d4nnyk** [comment]
`-wasm` was expected, but I tried only on release build.

Seems like on debug build it works, while release build it doesn't.

```
\x64_debug>ch.exe -wasm basic.js
function a[2]() { [native code] }
49
1121976320
1121976364
49
1121976320
1121976364
48
1121976319
1121976365
48
1121976319
1121976365
14336
```

```
\x64_release>ch.exe -wasm basic.js
Error in opening file '-wasm' : The system cannot find the file specified.
```

May be fix it?

**Comment by Cellule** [comment]
@d4nnyk Release builds do not support config flags. You can use test builds which has most debug/config option and optimized build.

**Comment by d4nnyk** [comment]
@dilijev  @Cellule Thank you for the info. I will use debug build as of now and wait for wasm to be enabled by default :)
