### ISSUE TITLE
Function.prototype.caller/arguments should be configurable

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#248]
Currently they are non-configurable.

Possible good candidate for "Your First PR"

**Comment by rhuanjl** [comment]
I was planning on making a PR for this but it appears to have been fixed by https://github.com/Microsoft/ChakraCore/pull/4651 (which also added a test for this issue)

**Comment by agarwal-sandeep** [comment]
@dilijev please double check this issue is closed

**Comment by dilijev** [comment]
Double checked a repro with @bterlson and it looks like we're all set.

```
## Source
print(Object.getOwnPropertyDescriptor(Function.prototype, 'caller').configurable)

#### ch-master-latest, jsvu-ch, jsvu-d8, jsvu-jsc, jsvu-sm
true
```
