### ISSUE TITLE
Crash/Assertion error when revoking proxy during proxy operation

### ISSUE THREAD

**Issue by anba** [Microsoft/ChakraCore#2483]
Version: cb7817bda7e4b265e7a7364641123e20204facfd
Platform: Ubuntu x64

Test case:
```js
var {proxy, revoke} = Proxy.revocable(() => {}, {
  get apply() {
    revoke();
  }
});

proxy();
```

Results in nullptr-crash resp. assertion error in debug mode:
```
ASSERTION 5592: (/home/andre/git/ChakraCore/lib/Jsrt/../Runtime/Types/RecyclableObject.inl, line 13) RecyclableObject::Is aValue is null
 Failure: (aValue != nullptr)
```

Similar issues are present for the other proxy traps.

**Comment by akroshg** [comment]
@anba, this is a good find. I'll work on this one.
