### ISSUE TITLE
Crash/Assertion error when changing class prototype during super-call with proxy

### ISSUE THREAD

**Issue by anba** [Microsoft/ChakraCore#2484]
Version: cb7817bda7e4b265e7a7364641123e20204facfd
Platform: Ubuntu x64

Test case:
```js
var proxy = new Proxy(function(){}, {});
class C extends proxy {
    constructor() {
        super(Object.setPrototypeOf(C, function(){}))
    }
}
Reflect.construct(C, [], proxy);
```

Results in nullptr-crash resp. assertion error in debug mode:
```
ASSERTION 5640: (/home/andre/git/ChakraCore/lib/Runtime/./Language/JavascriptOperators.inl, line 11) GetTypeId aValue is null
 Failure: (aValue != nullptr)
```

**Comment by akroshg** [comment]
There are two problems here when I investigated further. 
The Reflect.construct invokes the get trap for the proxy, which shouldn't happened.
second problem, the super tries to ```new``` the new.target which failed for proxy (and return nullptr).  According to spec we need to do the Constuct with new.target. 
I couldn't understand much about super. @suwc has more knowledge about this.

**Comment by suwc** [comment]
This is fixed by https://github.com/Microsoft/ChakraCore/pull/3080
(Reflect.construct is expected to reach the getPropertyTrap of the proxy because it needs to retrieve prototype object)
