### ISSUE TITLE
Built-in functions in Edge have 'prototype' properties

### ISSUE THREAD

**Issue by RByers** [Microsoft/ChakraCore#2494]
I'm not sure if this belongs here or in the Edge bug tracker.  
Built-in functions have a 'prototype' property in Edge, but no other browser (eg. `alert.hasOwnProperty('prototype')` is true in Edge, but false in every other browser).  

I think this is defined by [CreateBuiltinFunction](https://tc39.github.io/ecma262/#sec-createbuiltinfunction) which doesn't say anything about adding a property named `prototype`.

I ask just because I'm trying to measure the exposed API surface area differences between browsers, and this was confusing our tooling.

**Comment by dilijev** [comment]
@RByers `alert` is an API defined by the browser host, but this might still be because of the implementation of a hosting API we expose. While we check on that, can you reconfirm whether you also see this behavior for any built-in ECMA 262 functions like `Object.prototype.hasOwnProperty` itself?

Here's a test case I quickly threw together which you could extend.

```js
function hasOwnPropertyPrototype(fn) {
    return fn.hasOwnProperty('prototype');
}
function test(fn) {
    console.log(hasOwnPropertyPrototype(fn));
}

// Built-in functions should not have a prototype
test(Intl.Collator.toString);
test(Object.prototype.hasOwnProperty);
test(({}).hasOwnProperty);

// functions defined in-script should have a prototype
test(test);
```

Output:

```
false
false
false
true
```

**Comment by dilijev** [comment]
Adding external because it might be something which needs fixing in Edge.

If you wanted to, you could also [file an issue on Edge](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) so they can track this.

**Comment by RByers** [comment]
Thanks.  Yes the built-in functions are fine.  I should have thought to check that before guessing that this was a Chakra issue.  Filed [an Edge issue here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10885992/).

**Comment by curtisman** [comment]
With the Edge issue filed, I am closing this Chakra GitHub issue.
