### ISSUE TITLE
Assignment to new.target should be an early error

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#25]
Following test case is failing in [kangax](https://kangax.github.io/compat-table/es6/)
```javascript
var passed = false;
new function f() {
  passed = (new.target === f);
}();

try {
  Function("new.target = function(){};");
} catch(e) {
  return passed;
}
```

**Comment by suwc** [comment]
No repro.
@farzonl, you committed a fix for this on 10/8/15?

**Comment by farzonl** [comment]
not sure about the date, but the test case looks very similar to a bug I fixed. I don't have a chakracore dev environment atm or a way of reviewing the PR that fixed the issue, so i'm unable to confirm. wouldn't a 10/8 fix have made it into the th2 version of edge?

**Comment by abchatra** [comment]
I see its fixed in the latest bits as well. I will close the issue. We don't need to figure out the exact date. Thanks Farzon & Suwei.
