### ISSUE TITLE
Following "Embedding ChakraCore" and meet compile errors while building on windows

### ISSUE THREAD

**Issue by r12f** [Microsoft/ChakraCore#2510]
The error I met looks like following:
> chakracore.h(215): error C4430: missing type specifier - int assum
And it is because of the 
> chakracore.h(215): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> chakracore.h(215): error C2143: syntax error: missing ',' before '*'
> chakracore.h(273): error C2061: syntax error: identifier 'uint16_t'

The reason is because of the uint16_t is not defined in the following function in ChakraCore.h. 
```
    JsCopyStringUtf16(
        _In_ JsValueRef value,
        _In_ int start,
        _In_ int length,
        _Out_opt_ uint16_t* buffer,
        _Out_opt_ size_t* written);
```

The root cause of this issue is that, I am using Visual Studio 2015 and the _MSC_VER is 1900, so the following check will fail, and uint16_t will not be defined.
```
#if (defined(_MSC_VER) && _MSC_VER < 1900) || (!defined(_MSC_VER) && __cplusplus <= 199711L) // !C++11
typedef unsigned short uint16_t;
#endif
```

**Comment by r12f** [comment]
After changing the "_MSC_VER < 1900" to "_MSC_VER <= 1900", this issue is gone. Both the sample project and ChakraCore builds well.

The pull request is here: https://github.com/Microsoft/ChakraCore/pull/2511.

**Comment by dilijev** [comment]
@r12f Thanks!
