### ISSUE TITLE
Exit code -11 causing xplat tests to fail intermittently

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2517]
Example:

https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_debug_static_prtest/549/consoleFull#-1719471233c7453dd6-bf4f-4ae9-9fca-50f9ec7ab19e

Snippet:

```
[1261/1973 3.06] Failed -> WasmSpec/spec.js                           
14:45:31 /Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/master/osx_osx_debug_static_prtest/out/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- -dynamicprofilecache:profile.dpl.2492 -wasm -args testsuite-bin/f64.json -endargs /Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/master/osx_osx_debug_static_prtest/test/WasmSpec/spec.js
14:45:31 
14:45:31 Output:
14:45:31 ----------------------------
14:45:31 2395/2395 tests passed.
14:45:31 
14:45:31 ----------------------------
14:45:31 exit code: -11
```

(Test output is correct, it's only the exit code that's a problem.)

Tor reference -11 = 0xFFFFFFF5, but I haven't gone looking for the error code yet.

**Comment by jianchun** [comment]
Not sure if relevant, we found wasm code has software write barrier bugs. I'm working on fixing those issues.

**Comment by jianchun** [comment]
> I'm not sure I understand the issue. ScriptContext close shouldn't release any memory, and I don't understand why this would cause AV. It will decommit entry points, but not free them. I can believe that ours aren't getting cleaned up at that point. However, they still should be freed once there are no more recycler references to the FunctionBody.

@MikeHolman There is a release order dependency. FunctionEntryPointInfo cleanup needs to deregister debug data (only on xplat). Debug data exists in native code generator managed memory. ScriptContext close cleans up known FunctionBodies/EntryPointInfos then destroys native code generator. In your case the order doesn't guarantee -- When cleaning up your FunctionEntryPointInfo from finalizer, script context already closed and native code generator destroyed, but the FunctionEntryPointInfo cleanup still needs to read the (native code generator) released memory.

**Comment by MikeHolman** [comment]
Ah, I see. Ok I guess we should be registering the source info (and unregistering when it goes out of scope). Also, where exactly is the issue happening for unregistering debug data?

**Comment by jianchun** [comment]
> Ah, I see. Ok I guess we should be registering the source info (and unregistering when it goes out of scope). Also, where exactly is the issue happening for unregistering debug data?

https://github.com/Microsoft/ChakraCore/blob/e5ef2d118ad948afe51cd369a7117425ee914d23/lib/Common/Memory/amd64/XDataAllocator.cpp#L178 (search callers)

Don't know if there is unregistering code. I recall it is weakly referenced in sourceList.

P.S. Not sure if there are other features relying on this. E.g., script debugger updates all scriptContext->sourceList->FunctionBodies on debugger attach/detach.
