### ISSUE TITLE
Detect unhandled promise rejection

### ISSUE THREAD

**Issue by saschanaz** [microsoft/ChakraCore#2530]
http://www.ecma-international.org/ecma-262/7.0/#sec-host-promise-rejection-tracker

The following should log an error or warning on console:

```js 
new Promise((resolve, reject) => reject()) 
```

(Moved from [UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16665397-detect-unhandled-promise-rejection?tracking_code=4f4e218df62afae7db37fb5be5f4ff1c))

**Comment by liminzhu** [comment]
The spec reads as `implementation-defined` behavior. Edge & ch.exe don't give warning/error, Chrome (v8) throws, and Node 6 (also v8) gives warning. @bterlson is this supposed to be host-defined behavior or JS VM-defined behavior?

**Comment by bterlson** [comment]
There is no spec mandated work here. The promise rejection tracking is implementation defined. We could consider adding a rejection tracking mechanism to ch.exe. If this is a request for the dev tools (F12) to add rejection tracking capabilities, then this is out of scope for this repo I think.

**Comment by avonwyss** [comment]
A callback would seem appropriate (to match `JsSetPromiseContinuationCallback`), so that the host can decide whether and how to deal with these.

**Comment by albertogasparin** [comment]
Additionally, it would be great to trigger `unhandledrejection` and `rejectionhandled` events, like currently suggested by the html spec: 
https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections

**Comment by bterlson** [comment]
@albertogasparin assuming you're talking about precisely those events and in the browser, that's up to Edge to set up for us. If you file a uservoice request or similar, please post it here so others can pile on :)

**Comment by SaschaNaz** [comment]
There already is [a UserVoice request](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16665397-detect-unhandled-promise-rejection?tracking_code=4f4e218df62afae7db37fb5be5f4ff1c) which got 'Oops, wrong forum' response.

**Comment by bterlson** [comment]
@SaschaNaz gah, thank you. I will correct that presently!

**Comment by bterlson** [comment]
@SaschaNaz @albertogasparin the [uservoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16665397-detect-unhandled-promise-rejection?tracking_code=4f4e218df62afae7db37fb5be5f4ff1c) for the Edge side of things has been corrected. You can now spend your points there :)

**Comment by fatcerberus** [comment]
Throwing my hat in the ring to see this implemented, I've started to use async and await heavily and it gets confusing when an unforeseen error in an async function goes unnoticed.  I'd have to wrap every single async function in try/catch to make sure I see the errors, which is frustrating as I don't have to do that for sync code--it will just crash the process which is plenty noisy enough to find the bug. 😄 

Interestingly, when using the debugging API, uncaught rejections *are* intercepted, which suggests that the hooks to support this are already in place.  Even if it were just something as simple as "call a host callback on unhandled rejection" that would be great.

**Comment by rhuanjl** [comment]
Adding an extra voice to this discussion, per spec it sounds like the engine should call HostPromiseRejectionTracker (25.4.1.9 from the spec) when a promise is rejected, and then the host can choose what to do in that function) - however searching through chakra source I cannot see any exposed hook for this or any equivalent hook to allow a host that uses JSRT to define a rejection handler.

**Comment by bterlson** [comment]
@rhuanjl do note that we are conformant with 25.4.1.9 - the default implementation of that hook is to do nothing, and since it's unobservable to script whether that hook is actually used for anything, it may not actually exist in any given implementation. That API is only there to explain how hosts who choose to implement promise rejection tracking should do so.

**Comment by rhuanjl** [comment]
@bterlson I may have got this wrong - my initial read of 25.4.1.9 was that the engine i.e. ChakraCore should provide a hook for HostPromiseRejectionTracker such that a host (be that a browser or any other application using the engine) can implement a handler for it if they so wish.

My potential confusion comes down to reading "implementation" on the first line of the spec paragraph as "host" when I suppose it should be read as "engine" (in the context of my logic above).

**Comment by fatcerberus** [comment]
@rhuanjl I think in the context of the ES spec "implementation" should be read as "JavaScript implementation" - i.e. Chakra in this case.

**Comment by bterlson** [comment]
Indeed, "implementation" ~= "engine" ~= chakracore, and "host" ~= whatever is hosting the engine ~= Edge, Node, your own app, etc.

Regardless, the default implementation is to do nothing, which we presently comply with :-P

**Comment by bterlson** [comment]
Oh, I would also suggest always referring to the latest spec snapshot rendered here: https://tc39.github.io/ecma262.

**Comment by rhuanjl** [comment]
I'd be interested in creating an API within JSRT to respond to unhandled promise rejections, I would be quite happy to send a Pull Request for the below idea if it would be appreciated.

I was thinking it could be useful for a host to be able to choose to:
a) ignore them (as done now) - backwards compatibility and may be best for released products
b) have ChakraCore treat the unhandled promise rejection as an error and throw it
c) call a host defined API for it

My proposal would be to implement a JSRT function that allows a host to set any of the above 3 behaviours (option (a) would be set by default if the function is not called)

I understand from the above discussion that it is not required by spec to implement this behaviour and is not a priority of the team but would you be happy to welcome a PR to do this from an external contributor?

**Comment by bterlson** [comment]
@liminzhu any thoughts on @rhuanjl's proposal? I think this could be a welcome addition... perhaps worth looking at how NAPI handles this as well.

**Comment by liminzhu** [comment]
@digitalinfinity how do we handle `unhandledRejection` event in NodeChakraCore with the current set of APIs? Wonder if there's an existing solution.

**Comment by MSLaguana** [comment]
We do not, currently. At least not at the engine level. Some userspace libraries (such as zone.js) try to detect this from javascript, which doesn't always work properly. See https://github.com/Microsoft/ChakraCore/issues/3827 for some discussion of one case.

**Comment by fatcerberus** [comment]
It's possible to polyfill by monkey-patching the Promise constructor.  That doesn't work for async/await though, as async functions always use the native Promise.

**Comment by liminzhu** [comment]
Thanks @MSLaguana . It makes sense to me to expose a hook for `unhandledRejection` in the engine.

@bterlson are there any other cases/events we should consider? AFAIK there's at least `rejectionhandled`.

@agarwal-sandeep does the debugger need something like that as well?

**Comment by rhuanjl** [comment]
Just wanted apologise that I haven't followed this up with a PR yet, I spent some time looking into it and it appears to be a lot more complicated than I at first thought, I will try and give it some more time in the next week or two, and will hopefully be able to submit a PR at some point in the next month or so - I can't guarantee this though.

**Comment by rhuanjl** [comment]
OK, I think I've got a handle on this now, will aim to open the PR by the end of the weekend.

- [x] implement basic machinery for HostPromiseRejectionTracker
- [x] put in the hook for unhandledrejection
- [ ] put in the hook for rejectionhandled
- [ ] track the implementation through ch
- [ ] write tests

Not yet sure how to go about tracking the change through ch - intending to add it as a command line option so will have to figure out how that works.

**Comment by rhuanjl** [comment]
@saschanaz HostPromiseRejection tracking is now in CC master, I've no idea of the release schedule for when this will make it to a release also would take the Edge team implementing the feature in Edge for it to track through to there; but I've done what I can here CC now has the hook for this.

**Comment by rhuanjl** [comment]
This was implemented some time ago, and was shipped in version 1.10.
