### ISSUE TITLE
Question: Binding properties to C++?

### ISSUE THREAD

**Issue by simply-jos** [Microsoft/ChakraCore#2546]
Is creating a Proxy via JsDefineProperty really the only way to do this? That seems really inefficient, accessing the get/set members of the proxy each time, dispatching a function call, etc?

Am I wrong in assuming that it's using the Proxy backbone, and it's handled more efficiently internally?

Or is this something that would traditionally be done lower level than JSRT? Am I wrong in using only JSRT?

**Comment by liminzhu** [comment]
Hey @simply-jos thanks for posting the issue! 

I'm not sure why you need proxy. You can call `JsSetProperty`/`JsDefineProperty` directly to bind properties natively. If you want to expose a native object to JS, you can use `JsCreateExternalObject` which binds your c++ object to an opaque object in JS. You can bind methods to the object to do more interesting things. If these are not what you need, a short code sample helping me understand what you're trying to do would be appreciated.

**Comment by simply-jos** [comment]
Oh okay, if that binds them directly, that's good to know.

But what about binding something like an array or map, where you don't necessarily know which property is going to be accessed? To be more specific, overriding the [] operator and any key iterators.

**Comment by liminzhu** [comment]
@simply-jos not 100% percent sure the ask here so could appreciate a bit more clarification. If you have a native array and want to expose it as a JS array, you need to create an array in JS, iterate the native array and `JsSetIndexedProperty` for each element.

**Comment by simply-jos** [comment]
I'm asking if there's a way to override the [] operator and dot operator to return arbitrary values.

**Comment by caitp** [comment]
@simply-jos there must be some way, as it's required by web APIs (https://heycam.github.io/webidl/#idl-indexed-properties / https://heycam.github.io/webidl/#idl-named-properties), e.g. HTMLAllCollection

**Comment by simply-jos** [comment]
Yerr, I was hoping it could be done through JSRT. Thanks! I can consider this closed at this point.
