### ISSUE TITLE
Move WinRTDate code from DateUtilities.cpp

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#255]
lib/common/common/DateUtilities.cpp has some WinRTDate utilities that seems not used in ChakraCore. Consider move them.

**Comment by jianchun** [comment]
Similarly, ```NumberUtilities::DblFromDecimal``` seems not used in ChakraCore. Consider move as well.

**Comment by obastemur** [comment]
@jianchun Do we still have this issue?

**Comment by curtisman** [comment]
e28a2ad5957703471bf4c71839a3c4d0fbd1a6dc removed the unused WinRTDate stuff from DateUtilties.cpp
`NumberUtilities::DblFromDecimal` not moved yet.

**Comment by dilijev** [comment]
`NumberUtilities::DblFromDecimal` is used internally. Can move out of ChakraCore but not a high priority. This cleanup is nice-to-have but this issue is low value. Closing.

// @kfarnung @agarwal-sandeep
