### ISSUE TITLE
Printing object from Object.assign throws TypeError

### ISSUE THREAD

**Issue by kunalspathak** [microsoft/ChakraCore#2556]
```js
var x = Object.create(null, { A: {value: 1, enumerable: true} });
console.log(x);
```

```cmd
ch.exe e:\temp\test.js
TypeError: String expected
   at Global code (e:\temp\http.js:2:1)

```

**Comment by agarwal-sandeep** [comment]
For above test Firefox and Edge shows "{A: 1}" in console when using console.log(x) (Chrome throws TypeError). All throw Type Error when using alert(x);

Check console.log implementation to see how they get "{A:1}" even though JSON.stringify(x) throws. More of a feature for ch.exe EchoCallback.

**Comment by rhuanjl** [comment]
Current behaviour is now the same as other engines - confirmed with eshost, closing as nothing to do.
