### ISSUE TITLE
Cannot create a list of objects

### ISSUE THREAD

**Issue by ravisharma1987** [Microsoft/ChakraCore#2561]
Hello, 
I have a piece of code where I need to create a list of empty objects with the keys from -8 to 8 and values for these keys needs to be {value: i} objects. For the most part, the code works fine until suddenly the edge browser stops the creation of the object lists. 

Normally the object always has keys from -8, -7, -6 .... 0 .... +6, +7, +8 with corresponding objects. 
But after the (kind of) crash the map only has 1 key as 8 with corresponding value. 

I suspect it is a bug in the Chakra Engine. See picture below: 

![image](https://cloud.githubusercontent.com/assets/1917561/23067233/946a82a0-f51e-11e6-8a41-0bdf7614b8ff.png)

Please keep in consideration that this happens only in case of extremely fast execution scenarios like dragging an object for continuous calculations.

**Comment by liminzhu** [comment]
@ravisharma1987 thanks for the report! That's a weird issue and I find it hard to repro... @LouisLaf maybe someone on the JIT team can look into it a bit?

**Comment by ravisharma1987** [comment]
@liminzhu Hi, So finally I figured it out myself. The chakra-engine is not crashing if I keep the for loop index always positive. So It seems to me that the problem only happens when I have a for loop with negative indices.

**Comment by curtisman** [comment]
@ravisharma1987 I am unable to repro locally with the snippet of code above with SnapDistance == 8.
Can you provide a small repro that will demonstrate the problem.
Also what version of Edge are you using?

**Comment by LouisLaf** [comment]
@ravisharma1987, we can't make progress on this without a repro.  Please let us know if you're unable to provide one.  Thanks.

**Comment by MikeHolman** [comment]
Closing for now, since bug isn't actionable without a repro. Please reopen if this is still an issue/you can provide a repro.
