### ISSUE TITLE
ChakraCore vs Edge security

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Microsoft/ChakraCore#2565]
Is it true that ChakraCore provides the same level of security as the Edge browser? Are there any additional precautions that should be taken when running scripts with ch.exe?

**Comment by Penguinwizzard** [comment]
I wouldn't advise running untrusted code in ch. The ch.exe wrapper adds a number of calls that are useful in running test suites; among these are calls that allow reading arbitrary files from your filesystem (as bound by user permissions). This would allow a malicious script to upload files from your system to the internet.

**Comment by dennis-yemelyanov** [comment]
Thank you. Didn't realize ch.exe was adding file system functions. Then if I build my own tool that calls into ChakraCore APIs and only exposes a couple of methods (written in C# and supposedly secure), would that be good enough for untrusted code?

**Comment by liminzhu** [comment]
Yep, ChakraCore by itself is a sandboxed environment. It's usually the host environment which due its own requirement exposes methods like fs access and network methods that require extra security.

**Comment by dennis-yemelyanov** [comment]
Cool, thank you for confirming.
