### ISSUE TITLE
Stackoverflow checks (interrupts) in loops by default in ch.exe

### ISSUE THREAD

**Issue by Krovatkin** [Microsoft/ChakraCore#2572]
By default, ChakraCore inserts stackoverflow checks into loop headers even though there doesn't seem to be any logic in ChakraCore, taking advantage of these "interrupts". 

This simple testcase triggers this behaviour

```javascript
function AsmModule() {
    "use asm";
    function f1(){
    var x=0;
	while((x|0) < (2147483640|0)) {
	x=x+1|0;
	}
	return (x)|0;
    }
    return f1
}
var f1 = AsmModule();
f1();
```

```
ch.exe -maic:0 -dump:encoder
```

A stackoverflow check inserted in a loop header.
```
212F8D50056  $L1: >>>>>>>>>>>>>  LOOP TOP  >>>>>>>>>>>>>
 212F8D50056   s23(rax).u64 = MOV     0x020AF8BC0A88 (&StackLimit).u64
 212F8D50060           CMP            (rsp).i64, [s23(rax).u64 <0x020AF8BC0A88 (&StackLimit)>].i64
 212F8D50063           JLE            $L9
```

We were wondering if this behaviour could be disabled by default since these checks are worth a couple %s in asm.js/wasm emscripten worloads? @LouisLaf @dilijev 
We have a PR w/ change (https://github.com/Microsoft/ChakraCore/pull/2569)

fyi: @arunetm

**Comment by MikeHolman** [comment]
I noticed this as well when looking at wasm codegen last week. Given how tight some of these loops are, I wonder if it's worth investing in work for loop unrolling.

**Comment by dilijev** [comment]
Since #2569 addresses this, should this issue still remain open?

**Comment by MikeHolman** [comment]
No, we can close this.

**Comment by Krovatkin** [comment]
@MikeHolman fyi @arunetm   
> I noticed this as well when looking at wasm codegen last week. Given how tight some of these loops are, I wonder if it's worth investing in work for loop unrolling.

We once gauged how much loop unrolling could give us for loops w/ a very simple "payload".  It didn't seem much if I remember correctly. I've recently come across an article by a Java perf guy where loop unrolling was used in combination w/ lock coarsening and loop unrolling made things whooping **6x** faster! Shame, that JS is single-threaded. 

https://shipilev.net/jvm-anatomy-park/1-lock-coarsening-for-loops/
