### ISSUE TITLE
Calling to [resolve] function inside the Promise constructor function will crash if you call from JSRT API

### ISSUE THREAD

**Issue by JohnMasen** [Microsoft/ChakraCore#2585]
I'm working on a dotnetcore project which adds scripting feature to dotnet applications.
while working on support expose a `Task<T>` dotnet function to a JavaScript which returns a Promise instance.
I've managed to map an `Action<Action<T>,Action<String>>` as the Promise constructor, call to the first argument `Action<T>` will be translated to a JSCallFunction call to the javascript "resolve" anonymouse function.
The problem is JSCallFunction is a prototype call, it requires thisArg be the first parameter. I tried many objects, all triggered dotnetcore runtime fatal exception.
what I've tried:
1. the external javascript object act as my a dotnet class
2. the GlobalObject
3. the Promise instance created from Promise construct call
4. Undefined
5. Null
6. Promise function(I know it's not an object, just try my luck)
I've checked the JavaScriptvalue mapped to `Action<T>` is not disposed, I can call `AddRef()` on that with success result.

**Comment by JohnMasen** [comment]
something is wrong with the GitHub editor. all '<T>' are disappeared, 'Task' should be 'Task<T>'.
Action<Action,Action  should be 'Action<Action<T>,Action<String>>'
can't edit previous post

**Comment by JohnMasen** [comment]
it's disappearing again, preview function is still not working.
'Action<Action,Action>' should be Action《Action《T》,Action《String》》

**Comment by dilijev** [comment]
Angle brackets are rendered as HTML tags, so it would make sense if they're disappearing. Try putting code inside of \` like `Action<T>`

**Comment by dilijev** [comment]
@liminzhu

**Comment by JohnMasen** [comment]
thanks dilijev, I've removed the unnecessary comments to leave the question more clear.

**Comment by JohnMasen** [comment]
Update: 
I found the problem is how to set the thisArg while calling to an anonymous method passed from javascript.

**Comment by JohnMasen** [comment]
Update:
not about the thisArg either, seems about threading. Still digging up.

**Comment by JohnMasen** [comment]
That's it , I found it's related to GC, haven't figure out if it's related to .NET GC or chakracore GC. anyway Promise function is fine.
