### ISSUE TITLE
Intl.Collator('generic') fails

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#2604]
```js
Intl.Collator('generic');
```
gives following error.

```cmd
RangeError: Locale 'generic' is not well-formed
   at Global code (e:\temp\ic.js:1:1)
```

This is happening because `Windows.globlalization.dll` [here](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Base/WindowsGlobalizationAdapter.cpp#L363) returns false and `Intl.js` [here](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L289) throws. I tried debugging and it is the code inside `Bcp47Langs.dll` that returns it false. May be because it treats `'generic'` as special tag and so call it as not well-formed. I didn't notice anything special about `'generic'` in spec. Also this works in Edge, so might worth investigating why it doesn't work in `ch.exe`. This breaks `node-chakracore` while running `eslint` rules.

**Comment by dilijev** [comment]
@kunalspathak It looks like it doesn't work in Edge 15063. When did you last observe it working in Edge?

![image](https://cloud.githubusercontent.com/assets/494055/26083091/8930fd02-3988-11e7-8c14-9b9a60c7e90f.png)

**Comment by dilijev** [comment]
```
> es -its -h d8,sm,ch-1.2.3,ch-1.4.2,ch-dev,node,node-ch -e "Intl.Collator('generic')"
## Source
print(Intl.Collator('generic'))

┌──────────┬─────────────────────────────────────────────────┐
│ d8       │ [object Object]                                 │
│ sm       │                                                 │
├──────────┼─────────────────────────────────────────────────┤
│ ch-1.2.3 │                                                 │
│ ch-1.4.2 │ RangeError: Locale 'generic' is not well-formed │
│ ch-dev   │                                                 │
│ node-ch  │                                                 │
├──────────┼─────────────────────────────────────────────────┤
│ node     │ Collator {}                                     │
└──────────┴─────────────────────────────────────────────────┘
```

**Comment by dilijev** [comment]
'generic' is "potentially" a valid language tag as supported by the [RFC 5646](https://tools.ietf.org/html/rfc5646) grammar for language tags under the production: 

```
 language      = 2*3ALPHA            ; shortest ISO 639 code
                 ["-" extlang]       ; sometimes followed by
                                     ; extended language subtags
               / 4ALPHA              ; or reserved for future use
               / 5*8ALPHA            ; or registered language subtag    // <-- here
```

It appears that WinGlob believes this is not a valid language tag. This could be because "generic" is not a registered language subtag under WinGlob.

Since IMO Intl errors should not be gated on the contents of the Intl database, we should simply recognize the grammar of possibly valid tags for the purposes of determining errors. If the WinGlob database does not contain this tag, then the resulting locale set would be empty.

This issue can now be observed more directly via use of the `Intl.getCanonicalLocales` API.

```
> es -its -h sm,d8,node,ch-intl* -e "Intl.getCanonicalLocales('generic')[0]"
## Source
print(Intl.getCanonicalLocales('generic')[0])

┌─────────────┬─────────────────────────────────────────────────┐
│ d8          │ generic                                         │
│ sm          │                                                 │
│ node        │                                                 │
├─────────────┼─────────────────────────────────────────────────┤
│ ch-intl-gcl │                                                 │
│             │ RangeError: Locale 'generic' is not well-formed │
└─────────────┴─────────────────────────────────────────────────┘

> es -its -h sm,d8,node,ch-intl* -e "Intl.getCanonicalLocales('generic-latn-us')[0]"
## Source
print(Intl.getCanonicalLocales('generic-latn-us')[0])

┌─────────────┬─────────────────────────────────────────────────────────┐
│ d8          │ generic-Latn-US                                         │
│ sm          │                                                         │
│ node        │                                                         │
├─────────────┼─────────────────────────────────────────────────────────┤
│ ch-intl-gcl │                                                         │
│             │ RangeError: Locale 'generic-latn-us' is not well-formed │
└─────────────┴─────────────────────────────────────────────────────────┘
```

**Comment by dilijev** [comment]
Tracking as part of #3644
