### ISSUE TITLE
Expression-body arrow function parameter destructuring "Use before declaration" error when parameter is only used in an inner function

### ISSUE THREAD

**Issue by erikdesjardins** [Microsoft/ChakraCore#2606]
#2401 still happens for expression-body (but not block-body) arrow functions.

Reproduced with Chakra 1.4.0 and 1.4.1 (from the github releases).

```js
// works: block
(({ x }) => {
	(() => x)();
})({});
console.log('A done');

// works: block with return (behaviourally equivalent)
(({ x }) => {
	return (() => x)();
})({});
console.log('B done');

// fails: expression
(({ x }) =>
	(() => x)() // "Use before declaration"
)({});
console.log('C done');
```

**Comment by jods4** [comment]
I stumbled upon this today with Edge 14.4393. 
It impacts Aurelia framework, see aurelia/bootstrapper#59.
I came up with the following minimal repro:
```js
function g(cb) { return g() }
let f = ({ x }) => g(() => x);
f({ x: 42 }); // should return 42 but throws "use before declaration".
```
As noted by OP the bug is quite specific. Not having nested lambdas, or using a block instead of an expression after the arrow makes it go away.

Code above works in Firefox.

**Comment by RReverser** [comment]
Same issue here on latest Edge and ChakraCore 1.4.3, although I thought it's specific to Promises:

```javascript
let f = ({ data }) => Promise.resolve().then(() => {
  console.log(data);
});

f({
  data: [1,2,3]
}).catch(err => console.log(err.stack));
```

```
ReferenceError: Use before declaration
   at Anonymous function (d:\chakra-bug.js:2:3)
```

**Comment by BenMcGarry** [comment]
Was #2998 the fix for this issue?

**Comment by aneeshdk** [comment]
@BenMcGarry https://github.com/Microsoft/ChakraCore/pull/2998 should fix this issue. Does it still repro?
