### ISSUE TITLE
Consider hiding the definition of JsRef

### ISSUE THREAD

**Issue by davisp** [Microsoft/ChakraCore#2607]
I'm guessing this is a C vs. C++ type system issue but given that the definition of JsRef is available and defined as void*, the C compiler (at least, LLVM 8.0.0 on OS X 10.12.2, though I believe its part of the C spec) will happily convert void* pointers without complaint (even using -Wall -Werror like I do).

I personally tripped on this when trying to use JsCallFunction which takes a JsValueRef* for the argument list. I happened to miss the `*` in the docs and assumed the args were a JsValueRef that was a JavaScript array (rather than a C array of JsValueRef values). It turns out that due to the void* definition that this doesn't trigger any sort of compiler warning though it does trigger segfaults!

A basic example:

```C
    JsValueRef func = get_func();
    int argc;
    JsValueRef args = get_args(&argc);
    JsValueRef result;

    // Both of these compile fine
    JsCallFunction(func, argv, argc, result);
    JsCallFunction(func, &argv, argc, result);
```

**Comment by liminzhu** [comment]
Hey @davisp thanks for the feedback! I understand your pain here, but I'm not sure we can just hide type definition in a C API (it would be weird to just do it for JsRef as well imo).

**Comment by dilijev** [comment]
Also, IIRC all instances of `T*` in API params where T is typedef'd to `void*` should be `_Out_` params, right? That's probably a fair hint as to the usage.

**Comment by davisp** [comment]
@liminzhu I worded that a bit wrong. I was thinking to just make it a struct typedef that never gets defined. Ie, instead of `typedef void* JsRef` we'd have `typedef struct _js_ref JsRef` and you'd never define the actual struct (assuming that in C++ land you're really using classes instead).

@dilijev All of them except JsCallFunction as far as I know.

Also to be clear this isn't a high priority or anything. Just something I tripped over by not reading the docs closely enough and then it was a confusing debug session till I realized my mistake.

**Comment by dilijev** [comment]
@davisp They are actually treated as `void*` internally and the actual type is determined dynamically by inspecting that value (for example, we encode JavaScript Numbers directly in the number the pointer represents, otherwise it is assumed to be a JavaScript String or Object type and its vtable tells us what we need to know).

**Comment by davisp** [comment]
I wouldn't think this is high enough priority to add if we're looking at breaking the API compatibility. And this might all be fixed by a simple note that the parameter is an array of JsValueRef's in the docs for JsCallFunction given that's the only place (that I know of) that uses this as an input parameter.

**Comment by dilijev** [comment]
@davisp Thanks for the feedback, I think we can definitely update the documentation to make this clearer.

**Comment by liminzhu** [comment]
Made a doc change.

https://github.com/Microsoft/ChakraCore/wiki/JsCallFunction/_compare/776013002b865aea72628d7ddb14d7a73b9ab870

**Comment by dilijev** [comment]
Thanks for that, @liminzhu! I think we should leave this page open until we investigate the `struct` approach discussed above and decide if that's something we can pursue.

**Comment by liminzhu** [comment]
sgtm

**Comment by xiaoyinl** [comment]
Maybe I am wrong or misunderstand your point, but I think if you have `typedef struct _js_ref JsRef`, you can only write `JsRef *localVariable;`, but not `JsRef localVariable;`?

**Comment by dilijev** [comment]
I think it would look something like this (in C to demonstrate the fact that this change would still be C-compatible):

```c
#include <stdio.h>

typedef struct _js_ref JsVal;
typedef JsVal *JsRef;
extern JsRef x; // you can get a JsRef by calling another API of course.
JsRef y = NULL;

void foo(JsRef input, JsRef *output) {
	// impl
}

int main(void) {
	foo(x, &y);
	printf("Hello");
	return 0;
}
```

https://ideone.com/xaVQEf
