### ISSUE TITLE
Object.prototype should be an immutable prototype exotic object

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#261]
You should not be able to change its prototype with `Object.setPrototypeOf`, `__proto__`, or any other means. See also: https://github.com/tc39/ecma262/pull/308.

**Comment by dilijev** [comment]
@bterlson I'm wondering if you can help me understand this bug a bit better with actual/expected behavior?

I've tried the following:

```js
Object.__proto__ // function () {}
Object.prototype // Object {}
Object.setPrototypeOf(Object, {'a': 2})
Object.prototype // Object {} // no change
Object.__proto__ // Object {a: 2} // changed
```

And this succeeds with the same behavior (modulo differences in printed strings in the interactive console in both Canary and Edge).

**Comment by ljharb** [comment]
`Object.setPrototypeOf(Object.prototype, {})` should fail silently in sloppy mode and throw in strict mode, as should any other mechanism of changing `Object.prototype`'s `[[Prototype]]`.

**Comment by dilijev** [comment]
@ljharb Thanks for the clarification. Looking into it further now.

**Comment by dilijev** [comment]
@ljharb In sloppy mode, that statement causes the error message `Cyclic __proto__ value` in both Canary and Edge. I assume this is due to another issue. Is there another possibility that would avoid that error message, or is the goal here to silently fail and not report any error message at all?

**Comment by ljharb** [comment]
Oh sure. Set it to Object.create(null) or a cross-realm value instead, my mistake.

**Comment by bterlson** [comment]
Just to be clear, here's a code sample:

```js
var obj = Object.create(null);
Object.setPrototypeOf(Object.prototype, obj);
// or...
Object.prototype.__proto__ = obj;
```

Expected: TypeError in all modes
Actual: No TypeError

Do note that the type error is not dependent on mode (can you confirm @ljharb?).

**Comment by ljharb** [comment]
Confirmed - in both https://tc39.github.io/ecma262/#sec-object.setprototypeof and https://tc39.github.io/ecma262/#sec-set-object.prototype.__proto__ step 4 will return `false`, and step 5 should throw a `TypeError`.

(It's unfortunate that the `[[SetPrototypeOf]]` method doesn't point to https://tc39.github.io/ecma262/#sec-immutable-prototype-exotic-objects but that's where step 4 returns false)

**Comment by dilijev** [comment]
Thanks @bterlson and @ljharb. I think I understand the requirements much better now.

Earlier @ljharb had said:
>should fail silently in sloppy mode and throw in strict mode

And @bterlson said:
>Expected: TypeError in all modes

Is it that TypeError is not thrown in sloppy mode in general, or was one of these statements in error?

**Comment by bterlson** [comment]
I believe @ljharb was mistaken - it should be a TypeError in all modes. He confirms this in his most recent comment.

**Comment by ljharb** [comment]
@dilijev yes, my mistake. mode is irrelevant here (i thought it mattered for `__proto__` assignment, but i'm wrong)

**Comment by dilijev** [comment]
Okay, thanks for your patience in bringing me up to speed, here. :)
