### ISSUE TITLE
Marking experimental JSRT APIs

### ISSUE THREAD

**Issue by liminzhu** [Microsoft/ChakraCore#2611]
We have a bunch of experimental APIs in JSRT (debugging, module, string-related ones, etc) and we should find an appropriate way to mark them as experimental. An obvious solution is to clarify in documentation, but do we want to do something extra, like hiding them behind a flag which JSRT devs should explicitly flip?

**Comment by jaredwy** [comment]
+1 to hiding them behind a flag until they are ready.

**Comment by liminzhu** [comment]
Added a remark in reference page for the time being, e.g. https://github.com/Microsoft/ChakraCore/wiki/JsRun/_compare/911d4140b7b84aaf33704b3ea9ddabb06827d75d.
