### ISSUE TITLE
[Question] Speaking at Reactive2017?

### ISSUE THREAD

**Issue by hleumas** [Microsoft/ChakraCore#2620]
Hello folks!

You are doing amazing job with ChakraCore. Particularly time traveling debugger really got me.

I read this piece:
https://github.com/nodejs/node-chakracore/blob/xplat/TTD-README.md

I would love to invite somebody from your team to speak at [ReactiveConf 2017](https://reactiveconf.com), on 26–27 of October in Bratislava.

What do you think?

**Comment by panarasi** [comment]
Here is time travel debugging with React Native - http://blog.nparashuram.com/2016/08/time-travel-debugging-with-reactnative.html

**Comment by dilijev** [comment]
@liminzhu @bterlson @aruneshchandra @sethgaurav

**Comment by digitalinfinity** [comment]
@mrkmarron

**Comment by aruneshchandra** [comment]
@panarasi would be a good candidate for this.

**Comment by panarasi** [comment]
I spoke to @ryanjsalva and either him or me could do the talk. I think @mrkmarron should also be at the conference, since he is the one who did all the hard work.

**Comment by hleumas** [comment]
Sounds great! Of course, we will provide VIP tickets for all folks from the team who wants to come.

**Comment by liminzhu** [comment]
@panarasi let me know if you do end up speaking and have a recording available for sharing publicly. Could be something fun for https://github.com/Microsoft/ChakraCore/wiki/Resources.

**Comment by panarasi** [comment]
@liminzhu I did cover this at ReactConf 2017 [link](https://www.youtube.com/watch?v=iMLpUVZseEg) at around 19 minutes

**Comment by liminzhu** [comment]
Closing this as we'll have Ryan speaking at ReactiveConf.
