### ISSUE TITLE
ES6 `let let` and `const let` declarations are supposed to be a syntax error

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#263]
_Originally this issue mentioned only the syntax error for `for (let let ...` but the issue actually applies to all `let` and `const` declarations containing a variable named `let`.  See the general static semantics rule here: https://tc39.github.io/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors_

---

```javascript
for (let let = 0; false; ) { } // should be early syntax error on identifier named let
for (let let in { }) { } // ditto
for (let let of { }) { } // ditto
// and likewise when destructuring patterns are used
```

I think this was at one time decidedly not going to be an error because we thought about this case and intentionally implemented it so that it would parse.

In any case it no longer matches the spec.  Spec says it should be an error.

We need to make sure we disallow the name 'let' in an arbitrary destructuring too.

https://tc39.github.io/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors
https://tc39.github.io/ecma262/#sec-for-in-and-for-of-statements-static-semantics-early-errors

Ported issue from internal VSO bug [5055638](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems?_a=edit&id=5055638)

**Comment by AlexElting** [comment]
I'm taking a stab at this. I implemented a solution last night, I just need to write and run the tests.

Correct me if I'm wrong, but looking through the specs it seems like this is not just limited to `for ()` statements. The `LexicalDeclaration` is a `Declaration`, so this rule applies when `let` or `const` are used to declare in script bodies as well as in `for()`.

In a way this makes `let` this weird sort of quasi-keyword. You're allowed to use it as an identifier except when it's declared with `let` or `const`.

**Comment by ianwjhalliday** [comment]
@AlexElting awesome!  Yes, the change applies to all let/const declarations.  I don't know the reason this changed in the spec but I agree that it is strange that it turns `let` into a strange quasi-keyword.

@bterlson do you recall why this change was made during ES6?

I'll update the issue title and description to reflect the general bug
