### ISSUE TITLE
JSRT: Promises, continuation callback and garbage collection

### ISSUE THREAD

**Issue by dmunch** [Microsoft/ChakraCore#2638]
I just started playing with promises and implemented a simple continuation callback like the one documented in the [JavaScript Runtime Overview](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#promises). While at first everything worked smoothly I quickly ran into cryptic stack traces from inside ChakraCore. 

Luckily I've seen those before and I knew that garbage collection might be involved. Adding an `JsAddRef(task, NULL)` into the `PromiseContinuationCallback` paired with a `JsRelase(task, NULL)` inside the while-loop indeed solved the issue. 

Now my two questions:
- Is this expected behavior? From my limited understanding it seems like it could be, since nobody else might hold a reference to the task.
- If this is expected behavior, wouldn't it be advisable to include the calls to `JsAddRef` and `JsRelease` into the example?

Thanks a lot!
Daniel

Edit: I was using cb7817bda7e4b265e7a7364641123e20204facfd from 21. January. Haven't tried with a stable or more recent release yet.

**Comment by dilijev** [comment]
@liminzhu

**Comment by liminzhu** [comment]
Thanks for opening the issue @dmunch ! This is certainly the right thing to do. I made an [edit](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-(JSRT)-Overview/_compare/3523ae78f98becf70011e683204e42e6e45e3ed8) to the doc just now and will open an issue to fix that in the samples.

**Comment by dmunch** [comment]
Great! Thanks for the fast reply!

**Comment by liminzhu** [comment]
Quick report that the samples were fixed https://github.com/Microsoft/Chakra-Samples/commit/bef33332de2ac026b68e35ad8250b094b9207c43.
