### ISSUE TITLE
Fetching normalized specifier from JsModuleRecord?

### ISSUE THREAD

**Issue by coreh** [Microsoft/ChakraCore#2662]
When a `JsModuleRecord` is initialized, the host provides a string representing the normalized specifier for that module. Is there a way to retrieve that information later with only the `JsModuleRecord` handle? I couldn't figure out how to do that with the current APIs.

The parent module gets passed into the `FetchImportedModuleCallback`, so it would greatly simplify the lookup code if that information was exposed somehow. (Right now I'm considering using `JsSetModuleHostInfo` with `JsModuleHostInfoKind_HostDefined`, and storing a string with the path there, but I'm unsure on how to even free these resources later on, since modules don't seem to expose a GC callback function like regular JS objects)

Thanks in advance

**Comment by boingoing** [comment]
We don't have a mechanism for retrieving the module specifier from a ```JsModuleRecord``` in ChakraCore. You could store a string in the module record as you propose but handling the lifetime would be tricky. 

I think the intention of the design is for the host to "know" which module corresponds to which root module record. The host should have passed a specifier so we expect the host to keep a mapping from specifier to ```JsModuleRecord``` but I do realize that has an impact on flexibility of host design.

I'm not sure exactly how easy it would be but it seems possible to add a method to fetch the specifier from a ```JsModuleRecord```. Something like:
```c++
CHAKRA_API JsGetModuleSpecifier(_In_ JsModuleRecord requestModule, _Outptr_result_maybenull_ JsValueRef* specifier);
```

**Comment by coreh** [comment]
That indeed sounds like a nice API for retrieving that info.

I've forked the repo and added the method:

https://github.com/Microsoft/ChakraCore/compare/master...coreh:add/JsGetModuleSpecifier

If you'd like I can write tests and open a PR.

**Comment by boingoing** [comment]
Looks right to me. Let's ask @curtisman about the API impact before going to the effort of putting together tests.

**Comment by coreh** [comment]
It looks like this API might be far less useful than I originally believed: Passing anything other than the exact same specifier provided to the `FetchImportedModuleCallback` into `JsInitializeModuleRecord()` seems to result in a null pointer dereference error later on, with the parent module failing to find a child module.

I'm not sure if this is by design or a bug, since the `JsInitializeModuleRecord`'s documentation refers to the specifier as the ["host normalized specifier"](https://github.com/Microsoft/ChakraCore/blob/9fd82f1319a61a5dbaa7bf7c671942e8f043b5cf/lib/Jsrt/ChakraCore.h#L82), which makes me assume some sort of normalization or resolution could take place, e.g. by trasnforming `./foo` into something like `C:\Users\coreh\Projects\bar\foo.js`.

**Comment by dilijev** [comment]
Looks like this question is answered. Are there any follow up Tasks that should be created?
