### ISSUE TITLE
Atomics.store throws "TypeError: The operation is not supported on this typed array type"

### ISSUE THREAD

**Issue by brion** [Microsoft/ChakraCore#2672]
Testing cross-compiled code using emscripten's pthreads/SharedArrayBuffer mode in Edge on Windows Insider build 15048, I found that code that runs in Firefox and Safari tech previews fails here due to a TypeError being thrown in Atomics.store():

Simplified code:

```
var s = new SharedArrayBuffer(65536);
var u = new Uint32Array(s);
Atomics.store(u, 0, 1234);
```

Live example: https://jsfiddle.net/yejks8ja/

This works in Firefox Developer Edition and Safari Technical Preview, but fails in Edge (requires Experimental JS Features flag on) with "TypeError: The operation is not supported on this typed array type"

**Comment by akroshg** [comment]
This should work. I'll take a look.

**Comment by akroshg** [comment]
Hmm, typedarray checks were failing even though they are typedarray, that is because the virtual table is set differently for count 2**16.

**Comment by akroshg** [comment]
@brion thanks for reporting that.
