### ISSUE TITLE
Super should be an error in arrow functions outside classes

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#2673]
```js
(() => { super.x }))
```

Expected: Early SyntaxError
Actual: No Error

**Comment by jaredwy** [comment]
This for me on current master fails in the parser as I would expect.

https://github.com/Microsoft/ChakraCore/blob/master/lib/Parser/Parse.cpp#L12009 bails out here with a syntax error.

**Comment by bterlson** [comment]
@jaredwy sorry I missed this reply for so long!

You are correct, the initial test file is wrong. It should be an early error is the issue (and should occur when the arrow function is parsed, not when it is called.

Can you confirm that the updated repro doesn't behave per spec (i.e. that it doesn't throw)?

**Comment by curtisman** [comment]
Current master (e8ed687a93f85f584acbef995ad09b5fa76dfb35) output syntax error as expected.

    SyntaxError: Invalid use of the 'super' keyword
            at code (super.js:1:15)`
