### ISSUE TITLE
pal: pthread_getattr_np result ignored

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#2676]
In `GetCurrentThreadStackLimits` (pal_thread.cpp),

```
#elif HAVE_PTHREAD_GETATTR_NP
    status = pthread_getattr_np(currentThreadHandle, &attr);
    _ASSERT_MSG(status == 0, "pthread_getattr_np call failed");
#else
#   error "Dont know how to get thread attributes on this platform!"
#endif

    status = pthread_attr_getstack(&attr, &stackend, &stacksize);
    _ASSERT_MSG(status == 0, "pthread_attr_getstack call failed");

    void* stackbase = (void*) ((char*) stackend + stacksize);

    pthread_attr_destroy(&attr);
```

The code path is problematic when "pthread_getattr_np" fails. It continues to read from invalid `attr` and may return invalid results, and `pthread_attr_destroy` on invalid `attr` can AV.

When it fails with `status != 0`, should bail cleanly.

This is found on a node test on Linux with chakracore debug build: `node test/sequential/test-child-process-emfile.js`. The test intentionally triggers error EMFILE, which causes `pthread_getattr_np` to fail. According to http://man7.org/linux/man-pages/man3/pthread_getattr_np.3.html:
```
       In addition, if thread refers to the main thread, then
       pthread_getattr_np() can fail because of errors from various
       underlying calls: fopen(3), if /proc/self/maps can't be opened; and
       getrlimit(2), if the RLIMIT_STACK resource limit is not supported.

```

**Comment by jianchun** [comment]
@obastemur

**Comment by obastemur** [comment]
This is no different than any other system call is failing. I suspect your environment state while running those tests. Are you able to repro? if you do, could you please share the debugger call tree dump?

If we want to do something here anyway, IMO our only option is to fail early.

**Comment by jianchun** [comment]
I've reproed this on 2 different Ubuntu systems. Just sync to https://github.com/jianchun/node-chakracore/tree/getstack, clean build it, run `out/Release/node test/sequential/test-child-process-emfile.js`.

**Comment by obastemur** [comment]
The changes introduced on your branch push ChakraCore to consume more handle. Once again, this is no different than any other system call is failing. On Windows, ChakraCore wasn't expecting these to fail. 

That particular test case limits env. to `ulimit -n 64`.. So, even if we fix/cache the one, we will eventually have a problem with another system call.

That case is especially useful to demonstrate an application with so many child nodes. However fixing that particular test case won't make big difference. I'm planning to introduce a similar test plan to ChakraCore through CCRobot so we may start testing the core and catch the issues with different flags.

#2679 fixes this particular issue but I expect more to come. Opening a separate issue to track the problem. The caching approach on #2679 may work for some but for others we may/will have harder times.

**Comment by obastemur** [comment]
Opened #2680

**Comment by jianchun** [comment]
> The changes introduced on your branch push ChakraCore to consume more handle.

@obastemur Could you explain what change in my branch impacted handle consumption? (I'd assume my changes increased GC frequency and probability to hit this as GC queries stack range for stack scan.)

**Comment by obastemur** [comment]
Most of the PAL calls opens a file handle and GC process is now (MTed). Let's say your changes made those threads more active simultaneously and we reached beyond the max handle limit at a particular time.

**Comment by obastemur** [comment]
Fix is merged
