### ISSUE TITLE
ES6 modules not working in some cases

### ISSUE THREAD

**Issue by herrernst** [Microsoft/ChakraCore#2681]
I've found a case where trying to load ES6 modules doesn't work reliable: Most of the time, nothing happens, although the source files are requested from server. Sometimes it does work though, maybe it's some race condition. Here's a test case to reproduce:
http://rawgit.com/herrernst/msedge-es6module-bug/master/index.html
I've tested with the "Microsoft Edge on Win 10 Preview (15.15014)" VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by akroshg** [comment]
adding few folks @boingoing @suwc

**Comment by suwc** [comment]
This is at least partially due to https://github.com/Microsoft/ChakraCore/issues/2702, but there might be other issues.
