### ISSUE TITLE
`WScript.LoadScriptFile` search relative to the script location

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#269]
Right now, `WScript.LoadScriptFile` will search relative to the current working directory.
After the discussion in #244, I believe this was an oversight and this makes running test files without `rl` more difficult than it should be.
Unless someone as a valid use case to use current working directory, we should change it to use the current script's location.

**Comment by agarwal-sandeep** [comment]
@Cellule   https://github.com/Microsoft/ChakraCore/commit/3c743fd807924004e0054b58fecde145033c6d60 implemented this.

//cc @kfarnung @dilijev
