### ISSUE TITLE
Jenkins: Add "modern" configuration to run builds under Server 2016 and VS 2017

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2690]

**Comment by dilijev** [comment]
@mmitche is VS 2017 supported on Jenkins images?

**Comment by mmitche** [comment]
@dilijev Yeah, there are a number.  Look for the latest-dev15* images

**Comment by dilijev** [comment]
Superceded by https://github.com/Microsoft/ChakraCore/issues/4566
