### ISSUE TITLE
Object destructuring issue: Initializer on shorthand should not throw syntax error

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#27]
Following should parse
```javascript
var x = 10;
({x = 10} = {});
```
Actual: Syntax error

Refer OS bug [3887967] (https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=3887967)

**Comment by caitp** [comment]
these sorts of frontend fixes are probably good first bugs, if you want to attract volunteer contributors to work on actual language features.

I'm hoping I can encourage some local youth to tackle some of these bugs.

**Comment by kepta** [comment]
Hey, I'm a newbie. 
Can I work on this bug and also get some help on how to tackle thing bug ?

**Comment by abchatra** [comment]
@kepta absolutely. Tracing from the parser is the easiest thing to do. Add breakpoint at Parser::Parse. Also look at the call sites of IsES6DestructuringEnabled. That code amounts to destructuring related. 

See [this](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore) for building instructions. Let me know if you have more questions.

**Comment by ianwjhalliday** [comment]
@kepta also take a read through [test/runtests.cmd](https://github.com/Microsoft/ChakraCore/blob/master/test/runtests.cmd) to learn how to run tests.  Of particular note, consider providing the options `-dirs es6 -variant interpreter` to reduce the number of tests run to those surrounding the new language features and running them against front end, so you can have quicker code, build, test, debug loops.

So for example, after building x64 debug in VS, cd to the test directory and execute `runtests.cmd -x64debug -dirs es6 -variant interpreter` to run tests appropriate for this bug.

Of course once you're satisfied with your change you'll want to run all tests to make sure nothing broke by accident (run all tests by only specifying the build flavor, e.g. `runtests.cmd -x64debug`).

**Comment by akroshg** [comment]
This is fixed.
