### ISSUE TITLE
linux: Implement SmartFPUControl for cross-platform

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#270]
#252 (https://github.com/Microsoft/ChakraCore/commit/5e560731bd5cc383e07710122550a6dcbcea4ad2) temporarily made SmartFPUControl no-op on non-Windows systems. With fix of #260, we may need to implement it.

**Comment by agarwal-sandeep** [comment]
@jianchun do we plan to do any work for this? //cc @dilijev @kfarnung
