### ISSUE TITLE
Enable SharedArrayBuffer test262 tests in ch.exe

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#2714]
The Agent API enables testing of shared array buffers in console APIs. See test262 docs for [$262.agent](https://github.com/tc39/test262/blob/master/INTERPRETING.md#host-defined-functions). Note that these could be exposed as any shape and adapted by the harness. I'm open to alternatives.

See Also: https://github.com/tc39/test262/pull/839

**Comment by leirocks** [comment]
#3230
