### ISSUE TITLE
Implement Rest/Spread of Properties

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#2718]
Proposal text: https://github.com/sebmarkbage/ecmascript-rest-spread

Example:

```
let { x , ... y } = { x: 1, y: 2, z: 3 };
console.log(x); // { x: 1 }
console.log(y); // { y: 2, z: 3 }
```

Currently stage 3, will likely get stage 4 soon and will be included in ES2018. Already has hundreds of test262 tests as well.

**Comment by kfarnung** [comment]
The proposal redirects to the same proposal as #3406, so closing as a duplicate.
