### ISSUE TITLE
How do you return a string or struct from a callback to JavaScript?

### ISSUE THREAD

**Issue by DA40** [Microsoft/ChakraCore#272]
New to ChakraCore so have been playing with the ChakraCoreHost sample to get a feel for how things work. This shows how to use DefineHostCallback to create a callback to which the JavaScript provides some data, but not the reverse.  For example, how do you return a string or struct from the callback to JavaScript?
Thanks.

**Comment by ianwjhalliday** [comment]
A `JsNativeFunction` callback always returns a `JsValueRef`.  Use the JSRT APIs which create `JsValueRef` values to return what you need to return.  E.g. `JsCreateObject` (and `JsDefineProperty`), or `JsCreateArray`, or `JsBoolToBoolean`, etc.

**Comment by DA40** [comment]
Thanks to your help, Ian, I was easily able to implement this test callback:

JsValueRef CALLBACK GetString(JsValueRef callee, bool isConstructCall, JsValueRef *arguments, unsigned short argumentCount, void *callbackState)
{
	std::wstring	str(L"Got this from GetString");
	JsValueRef	stringValue;

	IfFailThrow(JsPointerToString(str.c_str(), str.size(), &stringValue), L"invalid argument");
	return stringValue;
}

**Comment by ianwjhalliday** [comment]
Awesome, glad to hear it @DA40.
