### ISSUE TITLE
Implement Async Generators

### ISSUE THREAD

**Issue by bterlson** [microsoft/ChakraCore#2720]
Proposal is here: https://github.com/tc39/proposal-async-iteration
Basic idea is a combination of an async function and a generator - essentially a generator you can `await` within.

There are already a number of test262 tests and v8 has an implementation we can compare against.

**Comment by zbraniecki** [comment]
SpiderMonkey also has it implemented - https://bugzilla.mozilla.org/show_bug.cgi?id=1331092

**Comment by benjamingr** [comment]
Any update on this?

**Comment by bterlson** [comment]
@benjamingr no update to share yet, but I'll be sure to update this issue (and [the roadmap](https://github.com/Microsoft/ChakraCore/wiki/Roadmap)) when I do!

**Comment by zbraniecki** [comment]
This has been accepted into ES2018. With support in SpiderMonkey, V8 and jsc, it would be great to get this in ChakraCore soon.

**Comment by rektide** [comment]
I don't know ChakraCore teams standard practice, but it would be SUPER HELPFUL to have a Platform Status thing to track.

**Comment by rhuanjl** [comment]
Is there any update on this feature/plan for when it will be implemented?

**Comment by ciscoo** [comment]
@rhuanjl See the link posted by @BobChao87 

It is currently marked as `UNDER CONSIDERATION` and:

> **Roadmap Priority: High** — We intend to begin development soon.

So to answer your question, no idea when really, but soon. 🤷‍♂️

**Comment by falsandtru** [comment]
Why does no one still implement or schedule this feature?

**Comment by rhuanjl** [comment]
Would an external contribution be welcome here?

(Not certain I could manage this but could give it a try if an external PR would be welcome)

**Comment by EdMaurer** [comment]
Yes, it would, but this feature is thought to require a good amount of effort.

**Comment by rhuanjl** [comment]
Aware that this will be sizeable but i’ll make a start and see how it goes.

I’ll aim to have a PR ready to submit by mid-December but I can’t promise anything.

Please let me know by updating here if someone internally is scheduled to work on it (and hence I should stop).

**Comment by rhuanjl** [comment]
I've made a start on this and, there's one thing I'm curently unsure how to do - at the moment `await` and `yield` share an opcode as Generators can only have `yield` and async functions can only have `await` so the difference is handled by the method which calls the generator/async function as it knows what its called and hence what can be done.

I need a way to detect from where I called into the async generator whether it has `yield`ed or `await`ed. 

My current guess is that the easiest way would be to add a JavascriptBoolean property to the ResumeYieldData struct and then in the ByteCodeEmitter detect specifically the case of an AsyncGenerator using await (which i can do) and when that is detected insert some bytecode immediately before the Op_Yield to access that property and set it to true.

I'm trying to work out how to do this but I don't understand how to access specific properties or fields from byte code, I'm also unsure if the funcInfo->yieldRegister points to the relevant instance of ResumeYieldData OR if it actually points to the Var data property of it. Please could someone point me in the right direction?

**Comment by rhuanjl** [comment]
I think I'm nearly there with async generator functions - will aim to open a PR this weekend.

I have not touched for-await-of or Symbol.asyncIterator yet, I will endeavour to do those in a later PR. I want to submit what I've done on async generator functions before doing the other aspects of this feature as it's going to be over 1000 lines as it is.

**Comment by rhuanjl** [comment]
So when the asyncGenerator yields there are three possible cases:
1. await
2. yield
3. yield*

Points 1 and 2 would both return to the same place with an object that had { value : something, done : false }

Point 3 would come in at the same place with an arbitrary object provided by the next value.

For point 3 - add a boolean value to the ResumeYieldData struct to specifically detect this (still working on this point)

For point 1 vs point 2 omit the done value from the yielded object if it's an await (condition check in the byte code emitter for async generator await around the emission of byte code for the done value) - so after ruling out yield* can use JavascriptOperators::HasProperty to test if it was yield or await.

**Comment by rhuanjl** [comment]
@EdMaurer you were right it was a lot of effort; but I had several free weekends and needed something to do :) Hopefully someone has time to review it.

**Comment by zenparsing** [comment]
Thanks so much @rhuanjl! We'll make sure it gets a look. I can't wait to get this in!

**Comment by rhuanjl** [comment]
Well this now is implemented behind a feature flag.

I assume it needs TTD and profiler support before it's enabled, is there anything else it needs?

Also please point me in the right direction if a PR would be welcome for the remaining points. (not sure where to start with the profiler or TTD)

**Comment by rhuanjl** [comment]
This was enabled by #6456
