### ISSUE TITLE
ChakraCore-based Browser for MacOS coming soon?

### ISSUE THREAD

**Issue by shyamalschandra** [Microsoft/ChakraCore#2728]
Hi, I have a quick question. Has anyone in the open source community taken ChakraCore and integrated it with a GUI for a MacOS browser for Safari and below? Anyone know?

**Comment by MikeHolman** [comment]
No one from chakra team is working on this. Don't know about anyone else. I'd be very interested in seeing the results from such an experiment though.

**Comment by liminzhu** [comment]
Close as this question seems to be answered already. Feel free to re-open otherwise.
