### ISSUE TITLE
Poor Error Handling

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/ChakraCore#2731]
I am getting poor error information when a script does not compile properly; I do get better error line numbers and information in Edge and Chrome, just not using ChakraCore via .net; can this be improved at all (echo in example below is a delegate to a Console.WriteLine)?

Following code:
```
var x = 0;
var y = 2;
console.log( x + y );

var g = 'this is a little 'test' to see what happens';
echo( g );
```

Gives this error:
`ChakraScriptRunnerScript failed at col: 0, line: 0, because: Expected ';'`

I would expect to see something like I see in Edge:
`Expected ';' test.html (9,28)`

I am using code based on the 'hosting' sample at:
[https://github.com/Microsoft/Chakra-Samples/tree/master/Chakra%20Samples/JSRT%20Win32%20Hosting%20Samples/Edge%20JSRT%20Samples/C%23](url)

My error reporter is:
```
        private string ReportScriptException( int firstLineNumber, JavaScriptValue exception )
        {
            JavaScriptPropertyId sourceName = JavaScriptPropertyId.FromString( "source" );
            JavaScriptValue sourceValue = exception.GetProperty( sourceName ) : JavaScriptValue.Invalid;

            JavaScriptPropertyId messageName = JavaScriptPropertyId.FromString( "message" );
            JavaScriptValue messageValue = exception.GetProperty( messageName ) : JavaScriptValue.Invalid;

            JavaScriptPropertyId lineName = JavaScriptPropertyId.FromString( "lineNumber" );
            JavaScriptValue lineValue = exception.GetProperty( lineName ) : JavaScriptValue.Invalid;

            JavaScriptPropertyId colName = JavaScriptPropertyId.FromString( "col" );
            JavaScriptValue colValue = exception.GetProperty( colName ) : JavaScriptValue.Invalid;

            JavaScriptPropertyId stackName = JavaScriptPropertyId.FromString( "stack" );
            JavaScriptValue stackValue = exception.GetProperty( stackName ) : JavaScriptValue.Invalid;

            string source = sourceValue.IsValid && sourceValue.ValueType != JavaScriptValueType.Undefined ? sourceValue.ToString() : string.Empty;
            string message = messageValue.IsValid && messageValue.ValueType != JavaScriptValueType.Undefined ? messageValue.ToString() : string.Empty;
            string stack = stackValue.IsValid && stackValue.ValueType != JavaScriptValueType.Undefined ? stackValue.ToString() : string.Empty;
            double line = lineValue.IsValid && lineValue.ValueType != JavaScriptValueType.Undefined ? lineValue.ToDouble() : string.Empty;
            double col = colValue.IsValid && colValue.ValueType != JavaScriptValueType.Undefined ? colValue.ToDouble() : string.Empty;

            return $"ChakraScriptRunnerScript failed at col: {col}, line: {line}, because: {message}\r\nStack: {stack}";

```

**Comment by obastemur** [comment]
> I would expect to see something like I see in Edge:
Expected ';' test.html (9,28)

Can you gist share the html file too ? Wondering what 9,28 corresponds to.

**Comment by coderangerdan** [comment]
Just a simple wrapper; line 9 points to the error line (line 5 without html tags):
https://gist.github.com/coderangerdan/01597ef3399170c524889610ce11e853

**Comment by coderangerdan** [comment]
I have also just built ChakraCore and run the script above with ch.exe and I do get a correct line and column number in the error:
```
SyntaxError: Expected ';'
        at code (test.js:5:28)
```

So not quite sure where the error is being lost; or how best to track it down.

**Comment by coderangerdan** [comment]
I debugged into ch.exe and i found the problem; i was looking at the JS Property "lineNumber" and "col" when Chakra uses "line" and "column" as per "PrintException" function in [https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp](url)

Apologies for this, i will create PR for fixing the hosting sample.
