### ISSUE TITLE
How to specify TTD log location when using --record instead of -TTRecord:[dir]?

### ISSUE THREAD

**Issue by dan-silver** [Microsoft/ChakraCore#2737]
Hello,

I previously used time travel debugging in visual studio code with the -TTRecord:log option. After installing the latest nightly build, I'm seeing this command is deprecated and I should use --record instead.  I run this command and it looks successful, but I have no idea where the logs are being saved to.  How can I configure the log directory? I checked the command list in the help menu, but I'm not seeing anything there.

Thank you,
Dan

**Comment by mrkmarron** [comment]
Hi Dan, we updated the log output to give both an out-of-the-box result and allow for programmatically controlling the output location. 

We have hooked up the logger to output to `./_diagnosticTraces/[name]` on common error [events](http://aka.ms/nodettd), like assert failures or unhandled exceptions, in Node. It should also write a trace if you exit the program with a ctrl-c. We updated the trace replay/debug commands as well which are described more in the link.

You can also explicitly write a trace to a location from within your code using the method `global.emitTTDLog([path])`. This call assumes you have already created the directory given by [path].

Hopefully this solves the issue, if not please let me know.

Thanks,
Mark

**Comment by dan-silver** [comment]
Ah! Thank you for the link!

It took a few failed attempts, but eventually the logs are saving:

![image](https://cloud.githubusercontent.com/assets/1266893/24275332/e2df2232-0feb-11e7-98c9-f684426dbf6e.png)

![image](https://cloud.githubusercontent.com/assets/1266893/24275371/24693328-0fec-11e7-9c9d-6c7284911430.png)


And success when I have an error thrown in a setInterval call.

![image](https://cloud.githubusercontent.com/assets/1266893/24275442/a44bcf60-0fec-11e7-91d2-d0bb3daac175.png)


I'll close the issue, thanks again for your help.
