### ISSUE TITLE
Remove [[Enumerate]] and associated reflective capabilities

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#274]
At the January TC39 meeting and subsequent conversations we got consensus on removal of the [[Enumerate]] MOP operation and the associated Reflect.enumerate and proxy trap `enumerate`. A PR implementing this consensus is here: https://github.com/tc39/ecma262/pull/367.

**Comment by goyakin** [comment]
https://github.com/tc39/test262/pull/496

**Comment by abchatra** [comment]
@Yongqu 
This is failing following ESNext kangax test case as well

```js
print((function()
{
var passed = true;
var proxy = new Proxy({}, {
  enumerate: function() {
    passed = false;
  }
});
for(var key in proxy); // Should not throw, nor execute the 'enumerate' method.
return passed;
})());
```
Expected: true
Actual:Exception.

**Comment by abchatra** [comment]
Removing 1.2 milestone due to backward compatibility concern. Please fix this in Master.
