### ISSUE TITLE
`1e+19.toString(2)` is displayed exponentially, but should be written out

### ISSUE THREAD

**Issue by littledan** [Microsoft/ChakraCore#2751]
The output given by ChakraCore is `1.00010101100011100100011000001001000100111101(e+63)`, but in three other engines, the correct answer of `1000101011000111001000110000010010001001111010000000000000000000` is provided. The [spec](https://tc39.github.io/ecma262/#sec-tostring-applied-to-the-number-type) states that with *n* (the base-10 exponent) between 0 and 21, the written out version should be used, rather than the exponential version.

**Comment by xiaoyinl** [comment]
@littledan [Section 20.1.3.6](https://tc39.github.io/ecma262/#sec-number.prototype.tostring) says if the radix is not 10, "the precise algorithm is implementation-dependent", but it should be a generalization of 7.1.12.1. I wonder how it's generalized. For example, it seems v8 and SpiderMonkey never use exponential notation when the radix isn't 10, even though the base 10 exponent is larger than 21, like this:

```
9.2323e+28.toString(2)
"1001010100100111111001011101100101000010011011010101000000000000000000000000000000000000000000000"
```

Should Chakra match this behavior too?

**Comment by bterlson** [comment]
@littledan any improvements to the spec in terms of reflecting reality is very helpful :)
