### ISSUE TITLE
Test "NumberFormatOptionsImplSpecific-Win10.js" failed on Windows Server 2012 R2

### ISSUE THREAD

**Issue by KarenHuang2016** [Microsoft/ChakraCore#2769]
**Environment:** Windows Server 2012 R2 + VS2017 + Chakra master branch latest revision aeb7117
**Repro steps:**
1. git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2. Open a VS 2015 x86 command prompt and browse to D:\Chakra\src
3. msbuild /m /p:Platform=x86 /p:Configuration=Test Build\Chakra.Core.sln /t:Rebuild
4. pushd test
5. runtests -x86test

**Test "NumberFormatOptionsImplSpecific-Win10.js" run failed as below:**
*** Running test #1 (0): Test Valid Options - Formatting Currency with Significant Digits
Test threw exception: assert.areEqual failed: expected: USD 123 actual: USD 123: currency code: USD
FAILED
*** Running test #2 (1): Test Valid Options - Formatting Percentage with Significant Digits
Test threw exception: assert.areEqual failed: expected: 12,300 % actual: 12,300 %: style: percent
FAILED
Summary of tests: total executed: 2; passed: 0; failed: 2

**This test passed on Win10 but failed on Windows Server 2012 R2**. Could you please take a look at this? Thanks in advance!

**Comment by dilijev** [comment]
That's correct. That test is tagged in the rlexe.xml in that directory as `exclude_winBlue` (which Server 2012 R2 is equivalent to for our purposes). Please pass `-nottags exclude_winBlue` to the test runner.

**Comment by KarenHuang2016** [comment]
@dilijev, thanks for your patient explanation! I will change the way to run test.
