### ISSUE TITLE
RegExp: Implement dotall (/s) flag

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2787]
https://github.com/mathiasbynens/es-regexp-dotall-flag

See implementation of e.g. `ignoreCase` (`/i`) flag.

FYI @bterlson

**Comment by dilijev** [comment]
Unassigned @sarahdonofrio so someone else can claim this. @sarahdonofrio: please let us know if you want to pick up this issue in the future.

**Comment by rhuanjl** [comment]
I'll give this a go, doesn't look too complex.
