### ISSUE TITLE
XPlat: AsmJs/MathBuiltinsCall.js fails on some linux/osx builds with some flags.

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2788]
Unfortunately this isn't something that I've been able to test easily so far, but enabling this test caused Jenkins to flag errors on some platforms. The test is disabled before #2730 by the -simdjs flag, and afterwards by the exclude_xplat tag. Errors include things such as "ceil(NaN) == 0" and end-of-precision differences from the baseline on some values, which may be a result of the wrong print tail end precision rounding flag.

**Comment by MikeHolman** [comment]
Closing as fixed, since we are no longer excluding the test and CI is passing.
