### ISSUE TITLE
 [proposed label: Question] Is the native C stack really known to the garbage collection system?

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#2836]
The JSRT overview appears to say that the garbage collector may clean up JsRef's that are on the native application's heap if JsAddRef has not been called for them, but it is not clear to me if the stack that is being referred to is only the javascript runtime stack, or if it includes local variables that are created in C.    If it does not include the native stack, then it would seem that JsAddRef and JsRelease bookkeeping needs to be done for any C variables containing a JsRef if one does not want the garbage collector to clean them before the function exits.  This does, of course, run somewhat counter to what the documentatoin appears to say about the garbage collector not trying to  clean up references on the stack, but I cannot see how it would be able to identify references that were native C local variables.  If local C variables are in fact safe from being clearned, how does the garbage collector know not to touch them?

**Comment by kfarnung** [comment]
I'm by no means the expert, but here's my understanding of the GC.  Stack pointers are scanned in `Recycler::ScanStack()` by finding the stack bounds for the thread context and then scanning that segment of memory for valid pointers to GC memory.  Any objects pointed to on the stack are then marked and maintained.

https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/Memory/Recycler.cpp#L1678

@digitalinfinity @curtisman Can you confirm my understanding?

**Comment by digitalinfinity** [comment]
Hi @markt - Chakra has a conservative garbage collector. In general, the stack is scanned conservatively (with some very limited exceptions). From the perspective of a JSRT user however, the only way to guarantee that a JsRef is not collected is to pin it using JsAddRef and JsRelease. While the GC will indeed mark the object if it sees it on the stack, stack slots are not always obvious- the compiler for example can reuse stack locations in cases where it knows that a variable is dead. So while things *can* be kept alive from the stack, in terms of reasoning about the lifetimes of objects, its much simpler to think about JsAddRef and JsRelease, from the following perspective- calling JsAddRef means that the value *will not* be collected, and calling JsRelease means that the value *may* be collected. Hope that helps clear things up.

**Comment by markt-** [comment]
@kfarnung , @digitalinfinity, thank you for your response.  I'm far less concerned about how long it will take the GC to clean things up after they are not on the stack than I am the possibility that the GC would clean things up that are on C's native stack before a function has exited.   Does the GC work by waking across the stack bounds and for each entry on the stack that has a value that corresponds to the address of a known javascript value, marking that javascript value as not yet freeable?   It's the only way I can see it working, but I don't want to make the assumption before I get too far into writing my application.... it might appear to work for a while, but if I were wrong about this, I could experience a sudden crash for no obvious reason.  Similarly, I want to avoid having to wrap every local variable with jsaddref/jsrelease calls simply to avoid the off-chance that the GC would clean up what it referred to before the function exits.

**Comment by digitalinfinity** [comment]
@markt- The GC will start from the top of the stack as determined by the current stack pointer register and scan till it gets to the stack base as determined by the thread metadata. It'll read 4/8 bytes at a time depending on the pointer size of the process, and then for each possible pointer, it'll lookup to see whether this is a GC allocated object or not. If it is, it'll mark it. So in general, if a javascript value is on the stack, you're fine.

That being said, I would still recommend JsAddRef/JsRelease calls to deal with cases where you think that a local is being alive from the stack but the compiler has reused that address for something else leading to unexpected crashes. Otherwise you'll have to be very careful about guaranteeing that the locals you care about are indeed on the stack at the points you expect them to be alive.

**Comment by markt-** [comment]
Awesome... Good to know that my assumptions were correct.
