### ISSUE TITLE
[TTD] Support Time Travel Debug Record and Replay in the same session

### ISSUE THREAD

**Issue by panarasi** [Microsoft/ChakraCore#2837]
Currently, Time Travel Debugging requires that the user first record the session, and then replay it. ChakraCore can be used for debugging React Native applications and can also [take advantage of](http://blog.nparashuram.com/2016/08/time-travel-debugging-with-reactnative.html) Time Travel Debugging. 
For making this scenario even better, it would be awesome if we could record and replay during the same debug session.

**Comment by kfarnung** [comment]
Ping @mrkmarron 

I know we've made a bunch of improvements in dev inner loop TTD for node-chakracore. I think these would also be applicable to ChakraCore.

VS Code extension for node-chakracore TTD: https://marketplace.visualstudio.com/items?itemName=ttd-trace-tools.node-chakracore-time-travel-debugger

**Comment by mrkmarron** [comment]
+1 Yes, the support we have for inner-loop TTD in Node should also work for the React case as well.

**Comment by dilijev** [comment]
@mrkmarron is it fair to say we can close this issue now?

**Comment by mrkmarron** [comment]
Yes, I think we can do that.
