### ISSUE TITLE
Click event on link changes window.getSelection() object

### ISSUE THREAD

**Issue by ejg** [Microsoft/ChakraCore#2857]
I am seeing this issue in Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393 on a Windows 10 Pro Version 1607 machine. The OS Build is 14393.1066.  The Processor is AMD Athlon(tm) || X2 B24, 3.0GHz.

The problem does not occur on Edge/Win Enterprise, Edge/Win Home or another Edge/Win Pro machine (same version/build as Win Pro above, different Processor: Pentium((R) Dual-Core CPU E6600@3.06GHz 3.07 GHz).

There is a codepen here: http://codepen.io/ejg/pen/YVyJBv

On the problem machine, when I click the submit Button the endOffset of the range is 5 and the parentNode is the span. When I click the submit Link, the endOffset of the range is 1 and the parentNode is the body.

![edge-win-pro-problem](https://cloud.githubusercontent.com/assets/213104/25285155/466e015e-2687-11e7-8b3b-7a5bd6b0b772.png)

All the other machines, for both button and link, the endOffset is 5 and the parentNode is the span. 

![edge-win-enterprise-works](https://cloud.githubusercontent.com/assets/213104/25285182/54d5515c-2687-11e7-8e10-a1df925f9d50.png)

**Comment by dilijev** [comment]
`window` APIs are implemented in Edge. Could you open an issue on the Edge Issue Tracker and post a link back here? See instructions here: https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues

**Comment by dilijev** [comment]
Also would it be possible for you to confirm whether this repros in the Creator's Update or the latest Insiders build?

**Comment by curtisman** [comment]
Closing as this is not a ChakraCore issue.
