### ISSUE TITLE
Interrupt callback

### ISSUE THREAD

**Issue by debdattabasu** [Microsoft/ChakraCore#2858]
Hi. 
First of all, thank you for an awesome piece of software. :)
My use case requires the Chakracore runtime to call back into the host code every once in a while( could be based on number of executed instructions or elapsed time), in order to run cpu use checks, etc. I could use DisableExecution, but it is too big a weapon for my needs. :D

Is there a way to make this happen inside Chakracore? I do have the option of instrumenting the javascript code with esprima or similar and add the instructions myself. However, there could be a vastly more efficient way to do this inside the runtime itself. What are your thoughts on this? 

Regards.

**Comment by pleath** [comment]
Thanks for the compliment, @debdattabasu . 

I would recommend looking at the abstract InterruptPoller class defined in core\lib\Runtime\Base\ThreadContext.h. An implementation of InterruptPoller can call back to the host on the thread that is executing script at an interval of its own choice. (The implementation in Edge uses it to support user interruption of hung scripts.) Currently, ChakraCore makes calls to InterruptPoller on garbage collection (see the call to ThreadContext::CheckScriptInterrupt in ThreadContext::ExecuteRecyclerCollectionFunction) and stack probe (see the call to ThreadContext::CheckInterruptPoll in ThreadContext::ProbeStackNoDispose).

Is this what you're looking for?

**Comment by debdattabasu** [comment]
@pleath Hi. I tried to get this to work today. I increased the frequency of interrupt polling to poll once every stack probe, and also changed shouldQcMoreFrequently to always return true (temporary hack). 

I ran a test case code where I checked interrupt pattern. It is exactly what I need. Is there a way I can integrate it into JSRT as JsSetInterruptCallback(or something else? need your inputs on the api), and issue a pull request? 

Regards

**Comment by pleath** [comment]
Good. I'm glad this meets your needs. @liminzhu, what's your view on the JSRT API that @debdattabasu is proposing?

**Comment by liminzhu** [comment]
Sorry to chime in late. This seems to be a useful feature. My only concern (and probably why we don't have the API now) is that the engine would be in a not so well-defined state when those callbacks are called there (e.g. I can't imagine calling JsRunScript in the middle of script execution would work well) so we're basically handing developers a weapon to shoot themselves unless we can clearly define what can/cannot be done during those callbacks. 

I think once we have that, this is an awesome change b/c other than the case @debdattabasu mentioned, I can imagine having an application that requires running JS on the UI thread, and I can use those callbacks to do some UI work and make sure my UI is responsive and won't just hang on JS.

**Comment by kfarnung** [comment]
Not quite the same thing, but V8 has a mechanism for interrupting long-running JS:  http://v8.paulfryzel.com/docs/master/classv8_1_1_isolate.html#a971b6094ecc6c7f55eb6f58a71a8afd3

This API is used by the inspector implementation for nodejs in order to run code on the main thread.  I believe the implementation under the hood would be relatively similar.  From what I've seen it just waits for the next stack probe and then calls back at that point.

**Comment by dilijev** [comment]
Looks like this question is answered. Are there any follow up Tasks that need to be created?
