### ISSUE TITLE
How thread-safe is the jsrt api?

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#2879]
While  I realize that each thread would rightly require its own runtime context, I notice that many of the Jsrt functions require a context to already be set before calling... this is not itself a big problem, but what would happen if in one thread I set the current context before calling one jsrt function, but then after setting the context but before the function could actually execute, the thread gets preempted by another thread which may set a different context before invoking a jsrt function of its own on that thread... when control returns to the original thread, since the context is not passed as a parameter to most jsrt functions, would the first thread be trying to execute the function with the second thread's context?   If so, how can this be mitigated?

**Comment by obastemur** [comment]
Could you be more precise? From what I read, you sound like, if it's possible that a runtime does something on Thread-2 while you've been using the same Thread-2 for another runtime? Not concurrently...

Perhaps others will answer this better but as long as you set the (correct) current context prior to API calls, things should be just fine.

**Comment by markt-** [comment]
Let's say for simplicity that I have two threads in the same process that both want to make jsrt api calls. 
 Each thread has its own JsRuntimeHandle and JsContextRef that was created for them.  The first thread goes on to sets its own context correctly and then attempts to invoke a jsrt function that requires a current context to be set.  Assuming, however, that the thread got preempted after it set the context, but before the jsrt function was actually called, and the second thread were to set its own context from its own runtime and invoke a different jsrt function, when the scheduler returns control to the first thread, it will want to continue with doing its own jsrt call, but because the thread got interrupted by another thread which set its own context, wouldn't the current context still be referring to that belonging to the second thread's runtime?    I realize that if I'm always setting the current context correctly before every jsrt api call, the chances of this happening are pretty low at any given time, but over the course of possibly many millions of calls with several different threads running concurrently (each with their own completely separate runtime), the chances it is going to happen seem to asymptotically approach certainty the more time goes by.    The reason this seems to be a problem is that many jsrt functions require a currently set context, and because the context is not a parameter to the functions, it appears like it might be a global variable, and therefore subject to thread contention.

**Comment by kfarnung** [comment]
The context is maintained in a thread local variable.  Calling JsSetCurrentContext on each thread will set that thread local variable.  When the OS switches between threads, the context will be maintained and each JsRT method will use the appropriate context.

**Comment by markt-** [comment]
Would that suggest that I do not even need to call JsSetCurrentContext before doing every API call if I am guaranteed to only have one context per thread?   I can create a context right after making the thread's runtime, call JsSetCurrentContext, and forget about it until the runtime is dispiosed?   That's pretty convenient.

**Comment by kfarnung** [comment]
The one gotcha is if the runtimes are allowed to switch threads, for instance if you pick up a runtime from a pool and run code using a thread pool thread.  If you're creating thread/runtime pairs and keeping them consistent then the context will be maintained for the lifetime of the thread.

**Comment by obastemur** [comment]
> The context is maintained in a thread local variable. Calling JsSetCurrentContext on each thread will set that thread local variable. 

@kfarnung @markt- 
Since we talk about multiple threads / contexts / runtimes, there are exceptions and maybe the most important one is that; If there was another context assigned to a particular thread, and that context was active, once you try to alter it, this method(`JsSetCurrentContext`) will return an error value.

> Would that suggest that I do not even need to call JsSetCurrentContext before doing every API call if I am guaranteed to only have one context per thread?

@markt- 

Well, maybe not before every single API call but I would reserve a place for `JsSetCurrentContext` calls and closely watch its return value. In case of a `new` thread, you should call `JsSetCurrentContext` prior to everything else (once is enough), especially, if you haven't created the runtime under the actual thread.

**Comment by kfarnung** [comment]
@obastemur Thanks for clarifying!

**Comment by liminzhu** [comment]
Close as this question seems to be answered already. Feel free to re-open otherwise.
