### ISSUE TITLE
bugs with non-lazy operators

### ISSUE THREAD

**Issue by alexlamsl** [Microsoft/ChakraCore#2899]
See https://github.com/nodejs/node-chakracore/issues/223

[Last case](https://github.com/nodejs/node-chakracore/issues/223#issuecomment-298456449) was tested under `node-chakracore 8.0.0-nightly20170429a043cb86fe`

**Comment by aneeshdk** [comment]
For the expression false * (parseInt_1 &= -1) we use a temporary register to hold the result of the & operation and never assign it back to the register which holds the actual function expression. But if I remove the multiplication part (false *),  the & operation directly assigns the results to the function expression register.

**Comment by digitalinfinity** [comment]
@aneeshdk if someone wanted to pick this up as their first PR, where would they need to make the code change? In ByteCodeGenerator?

**Comment by aneeshdk** [comment]
Yes the bytecode in both cases are different. In the not working case,
    0000   LdFuncExpr           R6 

  Line   6: switch ([ (false * (parseInt_1 &= -1), 0), (parseInt_1 && a++) ]) {
  Col   17: ^
    0006   ProfiledNewScArray   R7 = uint:2  <0> 
    000b   And_A                R8  R6  R4 

In the working case,

0000   LdFuncExpr           R5 

  Line   6: switch ([ ((parseInt_1 &= -1), 0), (parseInt_1 && a++) ]) {
  Col   17: ^
    0006   ProfiledNewScArray   R6 = uint:2  <0> 
    000b   And_A                R5  R5  R3 

We will have to see why in the first case we are not using the same register which holds the function expression. I would start looking into the BytecodEmitter.

**Comment by EdMaurer** [comment]
What does this issue impact?

**Comment by alexlamsl** [comment]
Just adding a note here - although at first sight it doesn't look like someone would write out those corner cases above, minifications like `uglify-js` will generate those expressions, whether as intermediate expressions or the final form.

Therefore this bug basically renders minified JavaScript unusable for any platforms based on ChakraCore, and remains so to this date.

**Comment by alexlamsl** [comment]
I can confirm the example in https://github.com/nodejs/node-chakracore/issues/223 affects Edge 16 as well as `node-chakracore` 8.10.0

**Comment by rhuanjl** [comment]
Minimal report of what appears to be the underlying issue in both of these cases:
```js
(function Math_1()
{
    Math_1 <<= 0;
    print(Math_1);
}
)()
```

eshost results of this code:
```
#### JavaScriptCore, SpiderMonkey, V8 --harmony
function Math_1()
{
    Math_1 <<= 0;
    print(Math_1);
}

#### Chakra
0
```

**Comment by pleath** [comment]
Isn't this a corner case, either with or without minifcation? I'd be surprised if many scripts were trying to modify a function expression in this way. In any case, it should be a very simple fix. The byte code generator is aware that a given symbol is the name of a function expression. It's just a matter of checking.

**Comment by alexlamsl** [comment]
@pleath in the name of saving bytes, many unspeakable transformations can happen.

That being said, this is not the only issue that causes all the `node-chakracore`/Edge errors/crashes I observe during testing (FWIW in comparison, IE8~11 all working fine). Just the one that happens most often thus prevent any meaningful progress in debugging further.

**Comment by pleath** [comment]
Are you saying that certain common minifications create assignments to immutable bindings?

**Comment by alexlamsl** [comment]
@pleath since our users tend to file helpful reports like "my code breaks - you go fix it" (and when asked, "my code is precious and private, so you are not allowed to read it"), we have a fuzzer which generates permutations of code snippets in order to stress test `uglify-js`.

While this particular pattern isn't too common (but has been encountered in the wild), the fuzzer tends to generate failure cases of the same kind most of the time, i.e. until the bug is fixed it's quite difficult to see other types of failures.

**Comment by pleath** [comment]
@alexlamsl That makes sense. I just wanted to make sure this wasn't something that a lot of people were writing deliberately or having written for them by a production minifier.

**Comment by rhuanjl** [comment]
I've tried to make a fix for this but can't work out what condition is safe to check, anything I try that evaluates to true in the case when the value should not be overwritten seems to segfault when it should be overwritten - is there anything I can look at for an overview of how these conditions work? OR is this being handled internal now?

**Comment by irinayat-MS** [comment]
EmitAssignment checks sym->GetIsFuncExpr. I'm experimenting with doing the same check in Emit for all knopAsg* nodes.

**Comment by alexlamsl** [comment]
@irinayat-MS thanks for the fix :+1:
