### ISSUE TITLE
TypedArray constructors do not perform proper super-call to %TypedArray% 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#29]
As per ES spec [22.2.4.1](http://tc39.github.io/ecma262/#sec-typedarray)

We should be loading super from the current function [[prototype]] slot. Instead we always assume super is %TypedArray%. Similarly, we do not pass new.target into %TypedArray% since we do not properly call Construct abstract operation. We need some refactoring in TypedArray constructors to support this behavior.

``` javascript
Uint8Array.__proto__ = Math.sin
new Uint8Array(64);
```

Expected: TypeError 
Actual: No Error

Duplicate OS bug [50260238](https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=5026038)

**Comment by DemiMarie** [comment]
Why is `__proto__` of built-ins writable to begin with?

**Comment by bterlson** [comment]
I think this bug is incorrect - we don't get the constructor prototype from Uint8Array.__proto__ but instead Uint8Array.prototype, which is non-configurable.
