### ISSUE TITLE
AsmJs Templatized jit broken without -simdjs

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#2905]
When running templatized jit without `-simdjs` we incorrectly calculate the stack size required.
`int32 stackSize = asmInfo->GetTotalSizeinBytes();` returns `0` in `FunctionEntry::ApplyTemplate`.

Since we don't ship templatized jit it's not urgent, but we should fix this.

**Comment by EdMaurer** [comment]
Low impact - we don't ship this.
