### ISSUE TITLE
Poor format template choice when specifying hour12 and minute with DateTimeFormatter

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#2915]
```js
new Date("1986-06-13T15:31:28-04:00").toLocaleString("en", {minute: "numeric", hour12: false});
```

Chakra: ‎6‎/‎13‎/‎1986‎ ‎12‎:‎31‎:‎28‎ ‎PM
Chrome: 31
Expected: at least something that doesn't include the date which was not asked for.

**Comment by LeaVerou** [comment]
Not just Chrome. Firefox and Safari also print 31.

**Comment by LeaVerou** [comment]
Also, same output when using `{minute: "numeric", hour12: false}`.

**Comment by dilijev** [comment]
Yeah this one is **definitely** a bug :)
I'll investigate.

**Comment by dilijev** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11907541/ is a duplicate.

Copying repro from that bug:
http://dabblet.com/gist/b6de7ba8792d88137f143f26a1d64a12

**Comment by dilijev** [comment]
Adding note from @LeaVerou's tweet that `hour12: false` is not respected. I don't have a repro showing this yet.

**Comment by dilijev** [comment]
Tracking as part of #3644
