### ISSUE TITLE
Add testing for no-arg invocation of ch

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2944]
As shown in #2937, this isn't currently tested in our CI, so I'm going to add a test case for it (and any infra support needed for that)

**Comment by dilijev** [comment]
@Penguinwizzard I like the idea of adding support for tests of various invocations of our test host. It's good to have to ensure things keep working correctly. As long as the infra support is being added, more nice-to-have test are for example `ch --help` `ch --version` `ch -?`

**Comment by Penguinwizzard** [comment]
Yeah; although it'd be nice, the added value is very little compared to the needed increase in testing complexity.
