### ISSUE TITLE
assertion "size > ScopeSlots::FirstSlotIndex" failure - modules with Promise.resolve

### ISSUE THREAD

**Issue by willportnoy** [Microsoft/ChakraCore#2949]
Run the following code:

[promiseVoidModule.zip](https://github.com/Microsoft/ChakraCore/files/988285/promiseVoidModule.zip)

Get this output:

script start
script after
ASSERTION 8052: (Repos\ChakraCore\lib\Runtime\Language\JavascriptOperators.cpp, line 6939) size > ScopeSlots::FirstSlotIndex
 Failure: (size > ScopeSlots::FirstSlotIndex)
FATAL ERROR: ch.exe failed due to exception code c0000420

**Comment by dilijev** [comment]
@suwc @boingoing

**Comment by akroshg** [comment]
There is no promise required, below code can also reproduce.
```js
export class Service {
    method() {
        return Service.Resolved;
    }
 }

```
@suwc can you take a look as the ```module``` does not seems to support ```class``` properly.
We are storing the class symbol to scope slot instead of module slot.

**Comment by akroshg** [comment]
@willportnoy thanks for taking time and reporting the issue.

**Comment by akroshg** [comment]
Module with class syntax, assigning to @tcare
