### ISSUE TITLE
[macOS] Crash while invoking JsCreateContext

### ISSUE THREAD

**Issue by dumganhar** [Microsoft/ChakraCore#2953]
I followed the wiki page (https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore) to build a static library for macOS. But after my app launched,  it crashed in like which in https://github.com/Microsoft/ChakraCore/pull/1173 .
Therefore, I had to build it to shared library. But I got another crash in `JsCreateContext`.
The full crash stack is:
![screen shot 2017-05-10 at 16 41 21](https://cloud.githubusercontent.com/assets/493372/25890290/8b866e58-359f-11e7-901d-b66caa7e4d7b.png)
![screen shot 2017-05-10 at 16 41 44](https://cloud.githubusercontent.com/assets/493372/25890301/949f098c-359f-11e7-8d2c-60e80aa3860a.png)
My mac device is: macOS sierra 10.12.14, MacBook Pro (Retina, 15-inch, Early 2013)
I uses the source in `release/1.4` branch and build it as shared library in DEBUG mode.
Could you help me to resolve this issue? Thanks.

**Comment by obastemur** [comment]
@dumganhar Use `release/2.0` and see if the problem persists.

If not, can you send me a sample project? you may compress the project files (no need to send chakracore lib) and drag & drop here.

BTW; I suspect there is a problem with project settings. If you share them, that could also help too.

**Comment by dumganhar** [comment]
@obastemur, this issue is fixed in release/2.0 branch.
Thanks for looking at this issue. I closed it.

**Comment by obastemur** [comment]
@dumganhar I saw good friend `cocos2d` on your screenshot. Are you guys trying ChakraCore as a replacement?

**Comment by dumganhar** [comment]
@obastemur , thanks for focus on what i'm doing.
Yep,  I'm trying to add a wrapper for JS Engines in Cocos2d-x. 
The wrapper will support `Spidermonkey`, `v8`, `javascriptcore` and `chakracore`.
Currently, I couldn't said it's a replacement. it's just a test now.
We will try to compare these four JS engines and find the best performance for our game engine.


Since iOS cannot support JIT, we only have to use `Spidermonkey` or `built-in Javascriptcore`.
And we have the choice of `v8` or `Spidermonkey` for Android.
Desktop platforms should use one of these JS engines, the wrapper will be really easily for switching JS engines without user's code change. 

Good to know that `ChakraCore`'s performance is the best on some tests done by others.
We will try to compare them too.

BTW, I have some question about ChakraCore.
* When will ChakraCore support mobile platforms (iOS, Android)?
* Will ChakraCore support bytecode mode which execute code without JIT since iOS can't support it?

**Comment by obastemur** [comment]
> When will ChakraCore support mobile platforms (iOS, Android)?
> Will ChakraCore support bytecode mode which execute code without JIT since iOS can't support it?

ChakraCore (on cross platform) no-jit has necessary work is ready for ARM targets. There are some bugs to fix though.

**Comment by dumganhar** [comment]
Good to know you have schedule for this.
