### ISSUE TITLE
jobProcessorCS assertion failure while collecting PerfView trace

### ISSUE THREAD

**Issue by willportnoy** [Microsoft/ChakraCore#2955]
I was collecting a system-wide trace using PerfView, and this assertion fails

        Assert(!jobProcessorCS || !jobProcessorCS->IsLocked());

with this call stack:

>	ChakraCore.dll!Js::FunctionProxy::GetAuxPtrWithLock(Js::FunctionProxy::AuxPointerType e) Line 116	C++
 	ChakraCore.dll!Js::FunctionBody::GetLoopHeaderArrayWithLock() Line 3020	C++
 	ChakraCore.dll!Js::FunctionBody::GetLoopNumberWithLock(const Js::LoopHeader * loopHeader) Line 3837	C++
 	ChakraCore.dll!JsLoopBodyCodeGen::GetDisplayName(wchar_t * displayName, unsigned int sizeInChars) Line 289	C++
 	ChakraCore.dll!CodeGenWorkItem::OnAddToJitQueue() Line 133	C++
 	ChakraCore.dll!NativeCodeGenerator::AddToJitQueue(CodeGenWorkItem * const codeGenWorkItem, bool prioritize, bool lock, void * function) Line 3396	C++
 	ChakraCore.dll!NativeCodeGenerator::GenerateLoopBody(Js::FunctionBody * fn, Js::LoopHeader * loopHeader, Js::EntryPointInfo * entryPoint, unsigned int localCount, void * * localSlots) Line 687	C++
 	ChakraCore.dll!GenerateLoopBody(NativeCodeGenerator * nativeCodeGen, Js::FunctionBody * fn, Js::LoopHeader * loopHeader, Js::EntryPointInfo * info, unsigned int localCount, void * * localSlots) Line 83	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::DoLoopBodyStart(unsigned int loopNumber, Js::LayoutSize layoutSize, const bool doProfileLoopCheck, bool isFirstIteration) Line 6129	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProfiledLoopBodyStart<0,1>(unsigned int loopNumber, Js::LayoutSize layoutSize, bool isFirstIteration) Line 5776	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_ProfiledLoopBodyStart<0,1>(const unsigned char * ip) Line 5749	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessProfiled() Line 51	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3512	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, Js::RecyclableObject * function, unsigned int flags, const Js::AuxArray<unsigned int> * spreadIndices) Line 3914	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, unsigned int flags) Line 446	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 83	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_TryCatch(const Js::OpLayoutBr * playout) Line 6568	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 373	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, Js::RecyclableObject * function, unsigned int flags, const Js::AuxArray<unsigned int> * spreadIndices) Line 3903	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, unsigned int flags) Line 446	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 83	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > * playout, Js::RecyclableObject * function, unsigned int flags, const Js::AuxArray<unsigned int> * spreadIndices) Line 3903	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > * playout, unsigned int flags) Line 446	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 86	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > * playout, Js::RecyclableObject * function, unsigned int flags, const Js::AuxArray<unsigned int> * spreadIndices) Line 3914	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<0> > > * playout, unsigned int flags) Line 446	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 86	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, Js::RecyclableObject * function, unsigned int flags, const Js::AuxArray<unsigned int> * spreadIndices) Line 3914	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > >(const Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<0> > > * playout, unsigned int flags) Line 446	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::ProcessUnprofiled() Line 83	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::Process() Line 3487	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction * function, Js::ArgumentReader args, void * returnAddress, void * addressOfReturnAddress, const bool isAsmJs) Line 2029	C++
 	ChakraCore.dll!Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout * layout) Line 1766	C++
 	ChakraCore.dll!Js::LocalCallFunction(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args, bool doStackProbe) Line 1348	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallFunction<1>(Js::RecyclableObject * function, void *(*)(Js::RecyclableObject *, Js::CallInfo) entryPoint, Js::Arguments args) Line 1364	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallRootFunctionInternal(Js::Arguments args, Js::ScriptContext * scriptContext, bool inScript) Line 730	C++
 	ChakraCore.dll!Js::JavascriptFunction::CallRootFunction(Js::Arguments args, Js::ScriptContext * scriptContext, bool inScript) Line 693	C++
 	ChakraCore.dll!JsCallFunction::__l2::<lambda>(Js::ScriptContext * scriptContext, TTD::TTDJsRTActionResultAutoRecorder & _actionEntryPopper) Line 2255	C++
 	ChakraCore.dll!ContextAPIWrapper::__l2::<lambda>(Js::ScriptContext * scriptContext) Line 217	C++
 	ChakraCore.dll!ContextAPIWrapper_Core<1,_JsErrorCode <lambda>(Js::ScriptContext *) >(ContextAPIWrapper::__l2::_JsErrorCode <lambda>(Js::ScriptContext *) fn) Line 171	C++
 	ChakraCore.dll!ContextAPIWrapper<1,_JsErrorCode <lambda>(Js::ScriptContext *, TTD::TTDJsRTActionResultAutoRecorder &) >(JsCallFunction::__l2::_JsErrorCode <lambda>(Js::ScriptContext *, TTD::TTDJsRTActionResultAutoRecorder &) fn) Line 214	C++
 	ChakraCore.dll!JsCallFunction(void * function, void * * args, unsigned short cargs, void * * result) Line 2271	C++

**Comment by dilijev** [comment]
@Penguinwizzard this looks like it might be your kind of trace :)

**Comment by curtisman** [comment]
I believe this is fixed by @leirocks already?

**Comment by leirocks** [comment]
yes, it should be fixed in that commit. if you hit it in latest chakracore again, please re-activate or let me know
