### ISSUE TITLE
Intl: We do not correctly reject duplicate variant subtags in language tags.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2961]
See: https://tc39.github.io/ecma402/#sec-isstructurallyvalidlanguagetag

> The IsStructurallyValidLanguageTag abstract operation verifies that the locale argument...
> * ...
> * does not include duplicate variant subtags...

```
>es -is -h ch-dev,d8,sm,node,node-ch -e "Intl.DateTimeFormat.supportedLocalesOf(['de-gregory-gregory'])"

## Source
print(Intl.DateTimeFormat.supportedLocalesOf(['de-gregory-gregory']))

#### d8, node
RangeError: Invalid language tag: de-gregory-gregory

#### sm
RangeError: invalid language tag: de-gregory-gregory

#### node-ch
[ 'de' ]

#### ch-dev
de
```

Expect to throw:

`RangeError: Invalid language tag: de-gregory-gregory`

**Comment by dilijev** [comment]
This bug is low severity. This is an instance of "Edge is more lenient" but in a way that people testing against other browsers will encounter an issue and we will not see this being a problem in practice.

**Comment by dilijev** [comment]
Futhermore since this is a case of the spec being more strict than BCP 47 tag validation, the underlying i18n libraries do not detect this. We would have to detect this in native code or library JS code, and it will involve doing our own parsing of language tags which will be slower. Maybe it won't be meaningfully slower, but it's still something to consider in the cost of fixing this bug.

**Comment by zbraniecki** [comment]
Or we should loosen the spec to conform to BCP47 closer :) I'd be in favor of that actually.
