### ISSUE TITLE
Intl: Investigate different behavior between engines on CanonicalizeLocaleList

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#2964]
CanonicalizeLocaleList is an internal operation used by many Intl APIs and exposed more or less directly through `Intl.getCanonicalLocales`.

https://tc39.github.io/ecma402/#sec-canonicalizelocalelist
https://tc39.github.io/ecma402/#sec-intl.getcanonicallocales

See test cases with multiple possible outputs added in https://github.com/Microsoft/ChakraCore/pull/2818

**Comment by jackhorton** [comment]
I think as far as investigations are concerned, I am happy to call this done. There is a good amount of literature in test/Intl/GetCanonicalLocales.js at this point describing the differences in behavior, and as of Intl-ICU, we ~match V8's behavior.

**Comment by dilijev** [comment]
SGTM 👍

**Comment by dilijev** [comment]
Looks like there's a warning leftover:

test/Intl/GetCanonicalLocales.js:122:            // TODO (doilij): Investigate what is correct/allowable here (Microsoft/ChakraCore#2964)

Next time you're in the area, can you remove that?

**Comment by jackhorton** [comment]
I suppose. With that being said, the issue isn't exactly _fixed_, I just think its at a state where we don't need to care about it. There were active discussions during the last Intl meeting about the variability of the behavior here across engines.
