### ISSUE TITLE
JsRunScript not available on OSX build

### ISSUE THREAD

**Issue by rogeru** [Microsoft/ChakraCore#2965]
I am trying to use ChakraCore on a C# .netcore console app on the Mac.

So I built ChakraCore on OSX as dynamic library (libChakraCore.dylib) but got an error when calling the API `JsRunScript`. Looking a Jsrt.cpp the API `JsRunScript` (and some related ones) are within a _WIN32 preprocessor `ifdef`.

Out of curiosity I moved the API out of the ifdef. Not only does it find the API now, it even successfully executes the javascript :).

What is the reason `JsRunScript` is only enabled for windows?

As side question, I was not able to load the static lib (libChakraCoreStatic.a). Where should the static lib be placed and what should DllImport specify?

**Comment by kfarnung** [comment]
For cross platform you should use [`JsParse`](https://github.com/Microsoft/ChakraCore/wiki/JsParse) and [`JsRun`](https://github.com/Microsoft/ChakraCore/wiki/JsRun).  The other APIs use Windows-specific types, so they are not cross platform compatible.

I'm not familiar with .Net Core on Mac, but on Windows you aren't able to load a static library (*.a on Mac, *.lib on Windows).  You should be using a dynamic library (*.dylib on Mac, equivalent to *.dll on Windows) for this purpose.

**Comment by rogeru** [comment]
Thanks, works great with `JsRun`.

**Comment by kfarnung** [comment]
Thanks for the confirmation!  Out of curiosity, what was the reason to try and load the static library from .NET Core?

**Comment by rogeru** [comment]
There is no reason. Dynamic library works fine. Just followed the first Hello World example on chakra-samples that shows building a static library.

**Comment by kfarnung** [comment]
Ok, thanks for the follow up!

**Comment by kfarnung** [comment]
I'll close this issue, but don't hesitate to open another one if you run into any issues.
