### ISSUE TITLE
Is there a way to create js object (JsValueRef) from JSON string through ChakraCore API?

### ISSUE THREAD

**Issue by dumganhar** [Microsoft/ChakraCore#2978]
I uses the latest code in `release/2.0` branch. Commit id:
```
commit 34c3ab15197056f15ec2aaac7c4843ba5855e13f
Merge: 796a580c fb42d22b
Author: Rajat Dua <radua@microsoft.com>
Date:   Tue May 16 14:04:44 2017 -0700

    [MERGE #2976 @rajatd] Fix linux builds in 2.0

    Merge pull request #2976 from rajatd:fix-linux-build-2.0
```

I didn't find anything about how to create a js object(JsValueRef) from JSON string through ChakraCore API.
There is an API in spidermonkey, v8, javascriptcore to achieve that, but I could not find anything in ChakraCore. Am I missing something?

In SpiderMonkey, we get:
```c++
JS_PUBLIC_API(bool)
JS_ParseJSON(JSContext* cx, JS::HandleString str, JS::MutableHandleValue vp);
```

In V8, we have:
```c++
static V8_WARN_UNUSED_RESULT MaybeLocal<Value> Parse(
      Local<Context> context, Local<String> json_string);
```

In JavascriptCore, there is:
```c++
JS_EXPORT JSValueRef JSValueMakeFromJSONString(JSContextRef ctx, JSStringRef string) CF_AVAILABLE(10_7, 7_0);
```

But how to do it in `ChakraCore`?
Is there a API for doing this?

Currently, a workaround is:
* Getting a global `JSON` object
* Getting the `parse` property of `JSON` object
* Passing json string to `JsCallFunction` and return the result

But unfortunately,  I got crash in `Type::GetLibrary`, the crash stack is:
![screen shot 2017-05-17 at 15 41 49](https://cloud.githubusercontent.com/assets/493372/26143410/654f8cc4-3b17-11e7-85f1-46cb0069a513.png)
![screen shot 2017-05-17 at 15 41 23](https://cloud.githubusercontent.com/assets/493372/26143414/6944c2cc-3b17-11e7-97da-4fe9e4b16481.png)

**Comment by jianchun** [comment]
ChakraCore doesn't have native JSON APIs. I'd do the same. Your crash stack doesn't seem to have JSON frames? Is there a way to reproduce/investigate? Probably you ran into some other issue.

**Comment by dilijev** [comment]
Looks like this question is answered. Are there any follow up Tasks that need to be created?
