### ISSUE TITLE
WeakMap + HostObject === Sadness (TypeError when using HostObject with WeakMap)

### ISSUE THREAD

**Issue by stefanpenner** [Microsoft/ChakraCore#2983]
```js
let map = new WeakMap();
map.set(window.location, '1'); // TypeError: WeakMap.prototype.set: 'key' is not an object
```

source: https://github.com/emberjs/ember.js/issues/15249

cc @jdalton / @nolanlawson

**Comment by dilijev** [comment]
@stefanpenner Assuming your repro should have a string as the second param to `set`, I repro'd this issue.

```
let map = new WeakMap();
map.set(window.location, '1'); // TypeError: WeakMap.prototype.set: 'key' is not an object
```

However, this seems specific to `window.location` and thus is an Edge issue. Can you please reopen this as an Edge issue following the instructions [here](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) and post a link here to the issue you open so we can track it?

**Comment by dilijev** [comment]
@tcare: @akroshg Believes this might be an issue that needs to be solved with a combined effort of Edge and Chakra.

**Comment by stefanpenner** [comment]
@dilijev unfortunately I cannot file an issue, my microsoft account is in some strange state that wont let me log in :(.

I'll try to figure it out later this week...

**Comment by nolanlawson** [comment]
No worries, I opened an issue on Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12112572/

FWIW you can also easily file an issue using #EdgeBug on Twitter: https://blogs.windows.com/msedgedev/2016/08/11/edgebug-twitter/

**Comment by jdalton** [comment]
Thank you ❤️ !
