### ISSUE TITLE
Generator function default parameter value initializers should be evaluated when the generator function is called not at first next() call

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#300]
Currently default parameter value initializers are evaluated on the first call to `next()` on the resulting generator object from a call to a generator function.  The ES spec says they should be evaluated on the call to the generator function itself, before it returns the generator object.

E.g.

``` javascript
let x = 0;
function* gf(a = x = 1) { }
let g = gf();
print(x); // should print 1, not 0
```

One simple solution might be to put a yield between the default parameter initializers and the body in the bytecode and then in the generator function call stub, call next() once, then return the generator object.

**Comment by ljharb** [comment]
If I've modified `%IteratorPrototype%.next`, wouldn't that be observable?

**Comment by ianwjhalliday** [comment]
We would call the generator next function directly for this purpose. Indeed we'd only do it this way if we can guarantee no observable effects. I believe this is possible but haven't explored the idea in depth.

**Comment by abchatra** [comment]
@ianwjhalliday Any update on this issue?

**Comment by ianwjhalliday** [comment]
No, have not had and still do not have time to look into this yet.  If someone else can take it up that would be great.  @aneeshdk?

**Comment by aneeshdk** [comment]
https://github.com/Microsoft/ChakraCore/pull/2941
