### ISSUE TITLE
[Question] Is there a JSRT api for comparing magnitude of js values?

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#3005]
While I can see that there is JsEquals and JsStrictEquals for comparing two js values for equality, I can't find any mechanism in the jsrt api for comparing two values' magnitude, either lexicographically or numerically, as applicable to the underlying type.  Without resorting to writing a one-liner function in javascript and calling it from the native language each time I require it, how can I compare two js values in ways other than simply equality?

**Comment by liminzhu** [comment]
Right now there's no direct function to compare magnitude and writing that one-liner function is the proper way to do it unfortunately. If you know the type of the value for sure, you can convert JsValueRef to proper type natively (e.g. `JsNumberToInt`) and compare.
