### ISSUE TITLE
[Disabled Test] test/Date/xplatInterval.js disabled in Jenkins. Is this by design?

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3010]
See `test\Date\rlexe.xml`

`test/Date/xplatInterval.js` is marked `exclude_jenkins` with no explanation. It does use `Date` but it doesn't seem to be timezone sensitive at first glance. Is this another instance of #319 or something else?

Please update the test so that it can run in Jenkins or explain in a comment in the `rlexe.xml` why it cannot.

**Comment by obastemur** [comment]
@dilijev I had explained this a bit on email before. We have custom xplat low level internal implementations. Their success observed on xplat CI to not to create noise on Jenkins.

See also https://github.com/Microsoft/ChakraCore/blob/master/test/Date/xplatInterval.js#L6 

This implementation proved to be stable enough now. I will enable this test for Jenkins too and close this item after.

Thanks for tracking this.
