### ISSUE TITLE
Unused "JD_PRIVATE" conditional compilation macro is mentioned in the sources

### ISSUE THREAD

**Issue by ddv239** [Microsoft/ChakraCore#3024]
It is never defined and should be eliminated.

**Comment by dilijev** [comment]
Hi @ddv239, this macro is defined by internal build configurations. Closing as Won't Fix

**Comment by ddv239** [comment]
Can you be more specific? I looked at the Chakra sources in VSO and found this was not used. I suspect your statement is wrong.

**Comment by dilijev** [comment]
This won't affect ChakraCore since it is not defined in ChakraCore build, but I was worried about the potential for internal build configurations to be affected. See email thread.

**Comment by dilijev** [comment]
After discussion, it appears that the original purpose of this macro is now defunct. Thanks for pointing this out and helping to clean it up.
