### ISSUE TITLE
[Disabled Tests] test/switchStatement/rlexe.xml: Disabled -testtrace cases to eliminate maintenance headache

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3037]
Either remove or fix/update these tests.

**Comment by LouisLaf** [comment]
Please fix this.  I do not like having unittests that contain bytecode offsets or enums, as they constantly break when these values change.  Let's see if we can easily fix this or delete the tests if they don't appear to provide a lot of value.

**Comment by Penguinwizzard** [comment]
Fixed in ad9a12ab247ac1f48d91ecb8de9499af517a5aa4.
