### ISSUE TITLE
Incorrect parsing of arrow function followed by a division

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#3039]
```js
x=>{}/print(1)/+print(2)
```

Actual: prints 1 and 2
Expected: Syntax Error (arrow function is not allowed syntactically in this position)

Also has this nice ASI hazard that is maybe more worrying:

```js
x=>{}
/print(1)/+print(2)
```

Actual: Prints 1 and 2
Expected: Just print 2 (`/print(1)/` gets parsed as a regexp literal)

**Comment by curtisman** [comment]
Fixed already in 1.6
