### ISSUE TITLE
Finalizer callback for context

### ISSUE THREAD

**Issue by marktjsonar** [Microsoft/ChakraCore#3059]
While one can attach external data to a context, it would be convenient if one could also define a finalizer callback function that would be invoked when the context is no longer needed by a runtime (or when its owning runtime has been disposed) as well as examine to see if a finalize callback is set for a context.

The incentive for this request comes from when I tried adding an external object with a finalize callback to the context's global object, and when the runtime was disposed, its finalizer callback was never invoked... but I imagine this has something to do with it being off of the global object, although this may also be a bug. #

**Comment by liminzhu** [comment]
@curtisman do you know if this is a bug?

@markt- if you still want to attach a finalizer to the context, you can use [JsSetObjectBeforeCollectCallback](https://github.com/Microsoft/ChakraCore/wiki/JsSetObjectBeforeCollectCallback) on the context which is a JsRef. The difference between finalizer and JsObjectBeforeCollectCallback is that the original object may not be available in the finalizer callback whereas it is available in the latter case.

**Comment by curtisman** [comment]
@liminzhu This is not a bug.  We don't have a callback when a context is being collected.

@markt - Instead of `JsSetObjectBeforeCollectCallback`, a better way would be to create `JsCreateExternalObject` to hold your data, and set that object on the context `JsSetContextData`.

**Comment by markt-** [comment]
@curtisman I was actually initially trying exacly that, but when the runtime was disposed, my callback on the external object was not called.  I am not sure if this was because the program itself was shutting down, but even so, I would expect that a finalizer should still be called.

**Comment by liminzhu** [comment]
Close for inactivity. Feel free to open if this becomes an issue.
