### ISSUE TITLE
using jsrt api, defining a named function in one script and calling the function's toString() in another script produces garbage

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#3060]
If I call JsRun on a script that defines a named function, and then I later call JsRun on a script that attempts to convert that identifier to a string via the functions toString() method, the resulting string is nonsense more often than not.    Perhaps I am doing something wrong here, but I cannot imagine what.  The program I am encountering this with is not any more complex than a simple read-eval-print loop.

If I first have a script like "function a() { return 1; }" and then later have a script like "a.toString()", more often than not, the resulting string will not contain the body of the function.  

Having a script which calls a named function works entirely normally, even if the toString() call with the same function produces garbage.  The only apparent side effect is that the body of the function is not being converted properly to a string, but given that this can sometimes cause a crash, the issue is probably quite serious.    If I call the named function's toString() method within the same script that defined it, then the issue does not ever arise.

Of course, if it turns out that I'm just doing something wrong or have made a bad assumption, then I'm quite happy to try and fix my own code.

When built as a Debug library, it fails catastrophically on a line in the code that reads: `Assert(pFuncBody->IsEval());`

Here is the crashlog:
```
Js::ScriptFunction::FormatToString (this=0x7ffff7eacd20, inputString=0x7ffff7e89dc0)	
Js::ScriptFunction::EnsureSourceString (this=0x7ffff7eacd20)	
Js::JavascriptFunction::EntryToString (function=0x7ffff7e9a040, callInfo={Count = 1, Flags = Js::CallFlags::CallFlags_Value, unused = 0, static ksizeofCount = 24, static ksizeofCallFlags = 8, static kMaxCountArgs = 16777215})	
amd64_CallFunction ()	
Js::JavascriptFunction::CallFunction<true> (function=0x7ffff7e9a040, entryPoint=0xd337a0 <Js::JavascriptFunction::EntryToString(Js::RecyclableObject*, Js::CallInfo, ...)>, args={Info = {Count = 1, Flags = Js::CallFlags::CallFlags_Value, unused = 0, static ksizeofCount = 24, static ksizeofCallFlags = 8, static kMaxCountArgs = 16777215}, Values = 0x7fffffffccf8})	
Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffcb80, playout=0x7ffff7fa50f1, function=0x7ffff7e9a040, flags=2, spreadIndices=0x0)	
Js::InterpreterStackFrame::OP_CallI<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffcb80, playout=0x7ffff7fa50f1, flags=0)	
Js::InterpreterStackFrame::ProcessUnprofiled (this=0x7fffffffcb80)	
Js::InterpreterStackFrame::Process (this=0x7fffffffcb80)	
Js::InterpreterStackFrame::InterpreterHelper (function=0x7ffff7eacd80, args={<Js::Arguments> = {Info = {Count = 0, Flags = Js::CallFlags::CallFlags_None, unused = 0, static ksizeofCount = 24, static ksizeofCallFlags = 8, static kMaxCountArgs = 16777215}, Values = 0x7fffffffd1c0}, <No data fields>}, returnAddress=0x7ffff4a40f02, addressOfReturnAddress=0x7fffffffd198, isAsmJs=false)	
Js::InterpreterStackFrame::InterpreterThunk (layout=0x7fffffffd1b0)	
?? ()	
?? ()	
amd64_CallFunction ()	
```
First I ran a script with JsRun containing "function a() { return 1 }",  and then later, in the same context, a script that caused the crash when executing with JsRun just contained "a.toString()"

**Comment by digitalinfinity** [comment]
Hi @markt- sorry for the trouble- can you share a representative snippet that exhibits this issue please? At first hand, it sounds like it could be that you're not pinning the function in question- you can do so using JsAddRef to make sure that the garbage collector does not prematurely collect it. If that's not the issue, the repro code can help us make further progress

**Comment by markt-** [comment]
Do JsRun on a script containing a named function definition: eg: "function a() { }"   It does not matter if it is the only thing in the script, the named function definition can occur anywhere.   

Do another JsRun within the same context on a second script that tries to call that function's toString() method.

I would expect toString() to display the function body as defined in the first script, and if the first script tries to do make a toString() call on the function in the same script that it is defined in, then calling its toString() always seems to work perfectly find when calling it later.

In this simple example, the first script returns undefined (as it should) so calling JsAddRef on the result of the JsRun doesn't make any difference, even when I postpone a JsRelease on it until after the JsRun that calls the function's toString().

Again, as long as everything is in a single script, it works fine... and I've only ever observed the issue with function definitions.  Other globally defined values seem fine.
