### ISSUE TITLE
Generator length property is inconsistently configurable (+ assert failure in debug build)

### ISSUE THREAD

**Issue by natashenka** [Microsoft/ChakraCore#3065]
The length property of a generator is configurable if you call get OwnPropertyDescriptor, but if you configure the property with a getter and setter, only the setter gets called. If the property is accessed, the read-only length value is returned, even if the setter has been called. This is because the generator class overrides GetProperty for the length property, but not SetProperty. I believe the standard says that this property be configurable, but regardless it should be consistent (either configurable is true, and you can set the getter and setter, or it is false and you can't).

```
The following code shows the problem:


function getSloppyGenerator() {
  return function* f(x) {};
}

function test(testFunction) {
  testFunction(getSloppyGenerator());
}


function testReconfigureAsAccessorProperty(f) {
  print(f.length);
  var length = 2;
  print(Object.getOwnPropertyDescriptor(f, "length").configurable)
  Object.defineProperty(f, 'length', {
    get: function() { return length; },
    set: function(v) { print("in set"); length = v; }
  });
  print("set");
  f.length = 3;
  print("get " + f.length);

}


test(testReconfigureAsAccessorProperty);

```

This prints:

1
true
set
in set
get 1

So configurable is true, the setter gets called, but the getter doesn't. It also triggers an assert in the Debug build:

ASSERTION 5843: (/home/user/test_everywhere/ChakraCore/lib/Runtime/./Language/CacheOperators.inl, line 362) objectWithProperty->IsWritable(propertyId) || (isRoot && RootObjectBase::FromVar(objectWithProperty)->IsLetConstGlobal(propertyId)) || JavascriptFunction::IsBuiltinProperty(objectWithProperty, propertyId)
 Failure: ( objectWithProperty->IsWritable(propertyId) || (isRoot && RootObjectBase::FromVar(objectWithProperty)->IsLetConstGlobal(propertyId)) || JavascriptFunction::IsBuiltinProperty(objectWithProperty, propertyId))

**Comment by dilijev** [comment]
Repro'd difference and crash (ch-dev-dbg quit early) using a slightly modified repro case:

```
> eshost -its test.js
## Source
function getSloppyGenerator() {
  return function* f(x) {};
}

function test(testFunction) {
  testFunction(getSloppyGenerator());
}

function testReconfigureAsAccessorProperty(f) {
  print(f.length);
  var length = 2;
  print(Object.getOwnPropertyDescriptor(f, "length").configurable)
  Object.defineProperty(f, 'length', {
    get: function() { print("in get"); return length; },
    set: function(v) { print("in set"); length = v; }
  });
  print("set 3");
  f.length = 3;
  print("get " + f.length);
}

test(testReconfigureAsAccessorProperty);

print("DONE");


┌────────────┬────────┐
│ d8         │ 1      │
│ sm         │ true   │
│ node       │ set 3  │
│            │ in set │
│            │ in get │
│            │ get 3  │
│            │ DONE   │
├────────────┼────────┤
│ ch-dev-rel │ 1      │
│ ch-1.4.4   │ true   │
│ ch-master  │ set 3  │
│ ch-1.2.3   │ in set │
│ ch-1.5.0   │ get 1  │
│ ch-1.3.2   │ DONE   │
│ node-ch    │        │
├────────────┼────────┤
│ ch-dev-dbg │ 1      │
│            │ true   │
│            │ set 3  │
└────────────┴────────┘
```

Confirmed crash in x64_debug build from master:

```
1
true
set 3
ASSERTION 25692: (C:\d\Chakra\core\lib\Runtime\Language/CacheOperators.inl, line 362) objectWithProperty->IsWritable(propertyId) || (isRoot && RootObjectBase::FromVar(objectWithProperty)->IsLetConstGlobal(propertyId)) || JavascriptFunction::IsBuiltinProperty(objectWithProperty, propertyId)
 Failure: (objectWithProperty->IsWritable(propertyId) || (isRoot && RootObjectBase::FromVar(objectWithProperty)->IsLetConstGlobal(propertyId)) || JavascriptFunction::IsBuiltinProperty(objectWithProperty, propertyId))
FATAL ERROR: ch.exe failed due to exception code c0000420
```
