### ISSUE TITLE
Assertion Failure in Parsing

### ISSUE THREAD

**Issue by natashenka** [Microsoft/ChakraCore#3076]
The attached file causes an assert to fire in the Debug build.

[parseassert.txt](https://github.com/Microsoft/ChakraCore/files/1042546/parseassert.txt)

ChakraCore/out/Debug/ch parseassert.txt 
ASSERTION 8981: (/home/user/test_everywhere/ChakraCore/lib/Parser/Parse.cpp, line 722) !this->m_deferringAST
 Failure: (!this->m_deferringAST)
Illegal instruction (core dumped)

**Comment by dilijev** [comment]
@natashenka It looks like this repro is incomplete -- there are missing module files and the fail function is not present in the repro. Could you provide the full set of repro files?

**Comment by natashenka** [comment]
The repro should work exactly as is, with the missing modules and the undefined method. Are you trying this on the Linux build, it's possible it's a Linux-only problem.

**Comment by MikeHolman** [comment]
I'm having no problem with repro. Looks like bug with defer parsing module import calls.

@suwc Can you take a look?

**Comment by dilijev** [comment]
I was able to repro with a recent debug build on Linux. Trying to figure out why it didn't repro on Windows.

**Comment by suwc** [comment]
Fix merged. Thanks!
