### ISSUE TITLE
Chakracore build break on VS2013 RC

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#309]
I cloned chakracore on a machine that has VS2013 12.0.21005.1 REL. The build fails because VS2013 doesn’t support `constexpr` that was recently added by @leirocks in 5619992ce85358277b744bd8317ba8546d83d654. This is also mentioned in [compatibility table](https://msdn.microsoft.com/library/hh567368.aspx#corelanguagetable) and mentioned [here](http://herbsutter.com/2013/09/09/visual-studio-2013-rc-is-now-available/#comment-13540).

This is supported starting [November 2013 CTP](https://www.microsoft.com/en-us/download/details.aspx?id=41151) update. Our wiki page 

Since wiki page that talks about [building chakracore](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore) simply list VS2013 as prerequisite but doesn't mention specific version.

I am opening this issue to discuss the guidelines we should have for contributors regarding adding new C++ language features while still maintaining the prerequisite of Visual Studio.
* If we want contributors to use latest and greatest C++ language features, we should update our wiki page to point the right Visual studio version pre-requisite containing those language features.
* If want to stick to language features available in RC versions of Visual Studio 2013/2015, then we should point it out in code reviews.

Whatever we decide, we should have some pre-checks build task that verify chakracore builds correctly with VS 2013 and VS 2015 that is mentioned on wiki page. This will help to catch these issues instantly.

**Comment by leirocks** [comment]
I can remove constexpr if we can’t use it, just move the calculation into the template definition. The only reason I use it is about readability.

Thanks,
Lei

**Comment by kunalspathak** [comment]
Sure, we can remove it, but this issue is more about how to handle these things in future.

**Comment by curtisman** [comment]
We already have daily build to check:
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#legacy-builds
To check all the configuration pre-check in requires a lot of machine resource. 
It's ok to detect and fix it quickly for these configurations.

**Comment by kunalspathak** [comment]
@mmitche , it seems that November 2013 update in not installed on Jenkins Win7 build machines that's why legacy builds are failing.

@curtisman  - Thanks for clarifying, but we should decide on what should be the guidelines here. @liminzhu, can you please take care of necessary documentation?

**Comment by leirocks** [comment]
I submitted a PR to remove constexpr usage  #310

**Comment by dilijev** [comment]
@mmitche Is it possible to update the Win7 machines to the latest Dev12 (with November 2013 update)?

How much use do those machines get outside of our team? Would it be unreasonable for us to ask for configuration changes to more closely model the setup we're anticipating and would like to support on behalf of the community?

**Comment by ianwjhalliday** [comment]
Should we bother to continue supporting VS 2013 without the update? It would be nice to have as close to full C++11 support as reasonable.

**Comment by liminzhu** [comment]
@kunalspathak, looks like @leirocks is removing ```constexpr```. Is Nov13 update still required?

**Comment by kunalspathak** [comment]
@liminzhu,  not now, but might need in future if someone adds new c++ language features.

**Comment by mmitche** [comment]
@dilijev For sure.  Want to make those changes yourself?

**Comment by dilijev** [comment]
@kunalspathak is this still an issue?

**Comment by kunalspathak** [comment]
Haven't tried. Assuming there are no issues, let us close this one and re-open if someone find out build breaks on VS2013.

**Comment by dilijev** [comment]
Agreed. Closing as Fixed / No Repro.
