### ISSUE TITLE
Intl: Date.toLocaleString doesn't handle 'timeZoneName' option correctly

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/ChakraCore#3096]
[test1.txt](https://github.com/Microsoft/ChakraCore/files/1047865/test1.txt)

Options aren't handled properly.

(And bug reporting should allow .js files?)

**Comment by kfarnung** [comment]
@BobFrGit We usually recommend just embedding directly into the report.

``` javascript
const dtOptions = {
    timeZone: "America/New_York",
    timeZoneName: "short",
    hour12: false,
};

function dx() {
    try {
        console.log(`Version ${JSON.stringify(process.versions)}`);
        const dt = new Date();
        const dsa = dt.toLocaleString('en-US', dtOptions);
        return dsa;
    }
    catch(e) {
        console.log(`Error ${e}`);
        debugger;
    }
}

console.log(dx());

// Should produce 6/2/2017, 09:51:49 EDT
```

**Comment by BobFrGit** [comment]
Will embed ...  

just tried

```
new Date().toLocaleString('en-US', {timeZone: "America/New_York", timeZOneName:"short", hour12:false});
```
and it worked! Or seemed to. I then noticed the uppercase O in timeZoneName and fixed it.

```
 new Date().toLocaleString('en-US', {timeZone: "America/New_York", timeZoneName:"short", hour12:false});
```
and that failed!

**Comment by kfarnung** [comment]
Thanks, looks like something weird is going on, I'll let someone with more experience chime in, but I ran some tests:

```
eshost -ts -e "new Date().toLocaleString('en-US', {timeZone: 'America/New_York', timeZoneName:'short', hour12:false})"
┌──────────┬────────────────────────┐
│ sm       │ 6/2/2017, 14:50:32 EDT │
│ node     │                        │
├──────────┼────────────────────────┤
│ ch-1.5.0 │                        │
│ ch-1.2.3 │ Error: undefined       │
│ ch-1.3.2 │                        │
│ ch-1.4.4 │                        │
│ node-ch  │                        │
└──────────┴────────────────────────┘

eshost -ts -e "new Date().toLocaleString('en-US', {timeZone: 'America/New_York', timeZOneName:'short', hour12:false})"
┌──────────┬──────────────────────────────┐
│ sm       │ 6/2/2017, 14:52:07           │
│ node     │                              │
├──────────┼──────────────────────────────┤
│ ch-1.5.0 │ ?6?/?2?/?2017? ?14?:?52?:?07 │
│ ch-1.3.2 │                              │
│ ch-1.2.3 │                              │
│ ch-1.4.4 │                              │
├──────────┼──────────────────────────────┤
│ node-ch  │ ‎6‎/‎2‎/‎2017‎ ‎14‎:‎52‎:‎07 │
└──────────┴──────────────────────────────┘
```

**Comment by BobFrGit** [comment]
This is case where the laxity of JavaScript made the typo invisible until I noticed the lack of "EDT" in the output string. (As an aside, perhaps the standard could also have a "presentation" flag to determine if bidi markings should be included)

**Comment by dilijev** [comment]
re: "presentation" flag: Standards discussion should be directed to TC39. You can bring casual questions and suggestions like this on IRC at freenode #tc39 to determine if there's interest. /cc @bterlson

**Comment by dilijev** [comment]
`timeZOneName` (note typo) would be ignored since it's an unrecognized option, so

`eshost -ts -e "new Date().toLocaleString('en-US', {timeZone: 'America/New_York', timeZOneName:'short', hour12:false})"`

Shows the same behavior as:

`eshost -ts -e "new Date().toLocaleString('en-US', {timeZone: 'America/New_York', hour12:false})"`

Interesting that an option we explicitly try to handle is throwing an error. There's definitely a bug.

The error message isn't very helpful either:

```
> cat a.js
print(new Date().toLocaleString('en-US', {timeZone: 'America/New_York', timeZoneName:'short', hour12:false}));

> ch a.js
Error
   at Global code (e:\d\chakraext\core\a.js:1:1)
```

I'll look into it.

**Comment by dilijev** [comment]
@veler I suspect there's an error in Intl.js but we don't have good error messages for that. Is there any work in progress that would make debugging built-ins easier?

**Comment by BobFrGit** [comment]
Just as an FYI I reformed and am now doing it the "right" way. Embarrassed that I did the hack thing with localeString but glad to have found bugs for you
```
            const dt = new Date();
            const n2 = (n) => ("0" + n).substr(-2);
            const n3 = (n) => ("00" + n).substr(-3);
            return {
                y: dt.getFullYear(),
                m: n2(dt.getMonth()),
                d: n2(dt.getDate()),
                hms: `${n2(dt.getHours())}:${n2(dt.getMinutes())}:${n2(dt.getSeconds())}.${n3(dt.getMilliseconds())}`
            };
```

**Comment by BobFrGit** [comment]
One more thought. If I write the localeString to a .txt file many programs would be confused by a bidi marker. More reason for making it optional, perhaps require an explicit bidi option.

**Comment by veler** [comment]
@dilijev , the main way consist to use console.log or breakpoint in the JavaScript. That is the way I used to debug and check the behavior step by step.

**Comment by dilijev** [comment]
Not a regression so moving to 1.7

**Comment by dilijev** [comment]
Date.toLocaleString is failing in platform.formatDateTime via
DateTimeFormatting::IDateTimeFormatter2::formatUsingTimeZone when the IDateTimeFormatter2 was created with a formatter string which contains `{timezone.abbreviated} | {timezone.full}` which are the values we inject into the formatter string when `timeZoneName: "short" | "long"` respectively. For some reason formatting with those values is causing WinGlob to throw an exception, despite those being valid formatter values according to the documentation. https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.DateTimeFormatting.DateTimeFormatter

**Comment by dilijev** [comment]
The test case passes in Edge and jshost... so that's interesting. I'll need to figure out what's different there.

**Comment by dilijev** [comment]
@BobFrGit I had assumed you saw this behavior in Edge. Out of curiosity what kind of app were you writing?

**Comment by BobFrGit** [comment]
I was using Node / UWP with Chakra and compared with behavior to Node w/V8. I'm guessing you'd see this behavior in Edge but haven't tried it client-side.

**Comment by dilijev** [comment]
@BobFrGit okay, thanks.

**Comment by dilijev** [comment]
This issue doesn't repro in Edge or WinGlob and has never worked in ChakraCore as far as I can tell.

#2919 is underway as a rewrite of Intl to use ICU instead of WinGlob and that effort targets all platforms. 

Therefore, this issue is neither high priority or high severity. Moving to backlog.


Tracking under meta-issue #3644 for WinGlob compat issues.

**Comment by BobFrGit** [comment]
Understand -- I programmed around it for now. It's part of the larger philosophical question of how to move ahead when people depend on accidental properties of the current implementation.
