### ISSUE TITLE
Update Math.random to use xorshift128+

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#31]
Chakra implements [LCG] (https://en.wikipedia.org/wiki/Linear_congruential_generator) algorithm for Math.random. Firefox has switched to [XorShift128+] (http://vigna.di.unimi.it/ftp/papers/xorshiftplus.pdf). Chrome used to implement MWC1616 and they have switched to xorshift128+ as well. This is a request to update Chakra Math.random implementation to use xorshift128+. Xorshift128+ is an improvement over LCG even though it still is not cryptographically secure. The same algorithm across all browsers serves well on interoperability story. 

http://jandemooij.nl/blog/2015/11/30/testing-math-random-crushing-the-browser/
https://bugzilla.mozilla.org/show_bug.cgi?id=322529
http://v8project.blogspot.com/2015/12/theres-mathrandom-and-then-theres.html

**Comment by esnard** [comment]
Safari now uses Xorshift128+ too:
https://bugs.webkit.org/show_bug.cgi?id=151641

**Comment by Yaffle** [comment]
```
return advance() / (std::numeric_limits<uint64_t>::max() + 1.0);
```
(see https://bugs.webkit.org/attachment.cgi?id=266302&action=diff#Source/WTF/wtf/WeakRandom.h_sec1 )

a little strange conversion of uin64 to double:
1) you will get `1` sometimes;
2) distances between numbers are not equal


https://github.com/v8/v8/blob/085fed0fb5c3b0136827b5d7c190b4bd1c23a23e/src/base/utils/random-number-generator.h#L93
V8 will have only random 52 bits, seems

and only mozilla implemented conversion correctly.

**Comment by Yaffle** [comment]
```
double get()
{
  return advance() / (std::numeric_limits<uint64_t>::max() + 1.0);
}
```
(see https://bugs.webkit.org/attachment.cgi?id=266302&action=diff#Source/WTF/wtf/WeakRandom.h_sec1 )
Will they have `1` sometimes in Safari and not equal distance between values?


```
https://github.com/v8/v8/blob/085fed0fb5c3b0136827b5d7c190b4bd1c23a23e/src/base/utils/random-number-generator.h#L98 and  - will they have only 52 random bits in V8 ?

**Comment by Ivoz** [comment]
For reference for anyone, current generator is [here](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Math/JavascriptMath.cpp#L1022-L1088) in the code, which is the 5DEECE66D LCG.

**Comment by dilijev** [comment]
Specifically here: [JavascriptMath.cpp#L1023](https://github.com/Microsoft/ChakraCore/blob/6649f328269d6ccf5e567dd52d4f89411bfaef26/lib/Runtime/Math/JavascriptMath.cpp#L1023)

**Comment by suwc** [comment]
https://github.com/Microsoft/ChakraCore/pull/145
