### ISSUE TITLE
Connect the repo to Reviewable

### ISSUE THREAD

**Issue by mayaware** [Microsoft/ChakraCore#3105]
Please connect this repo at https://reviewable.io/repositories so that all PRs get linked to reviews. Thanks!

**Comment by MikeHolman** [comment]
People are free to use reviewable for their reviews (and some do), but many people use vanilla GitHub or other tools so we don't want to codify reviewable into our check-in process. I believe you can review using reviewable on any PR even without us linking the repo.

**Comment by dilijev** [comment]
Yes, we used to have this set up but disabled it due to many people finding it annoying when they would rather use a separate tool and not have the Reviewable message show up on every PR.
