### ISSUE TITLE
Where is the simplejit compiler

### ISSUE THREAD

**Issue by penhoi** [Microsoft/ChakraCore#3106]
I want to dump the jit-code generated by Chakracore for security research. I read that Chakracore has two compilers which are SimpleJIT and FullJIT. Currently, i can dump the code generated by FullJIT, when i insert a hook into Func::Codegen() just after line 297. However, i cannot dump the jit-code generated by SimpleJIT because i failed to find this compiler! 

So i want to know whether this code base provides this SimpleJIT compiler? If this is true, could you tell me where it is. Thanks! 

By the way, my modification is based on branch release/2.0 whose latest commit is 039006b8f4b62eb9d4812241377cf6a38e3c073e.

**Comment by pleath** [comment]
Hi, @penhoi. The SimpleJIT logic is not in a separate piece of source. It's the common JIT source run with different options. If you want to dump the simple JIT IR output, you can add -dump:simplejit to your command line along with whichever phase(s) you're interested in. So, for instance, -dump:simplejit -dump:irbuilder -dump:lowerer will dump the simple JIT IRBuilder and Lower output, and -dump:simplejit -dump:backend will dump all the simple JIT phases.

**Comment by penhoi** [comment]
Thank you @pleath .
I have two questions:
First one, why the SimpleJIT works in a manner as FullJIT, i.e. lifting javascript code (or AST) to IR and then lowering IR code to machine code? What is the difference between them.

The second one is that i got almost the same logs when running the following commands. I thought log2 and log3 should be different!
./ch -bgjit- -dump:backend chconst.js > chconst.js.log1
./ch -bgjit- -off:simplejit -dump:backend chconst.js > chconst.js.log2
./ch -bgjit- -on:simplejit -dump:backend chconst.js > chconst.js.log3
./ch -bgjit- -dump:simplejit -dump:backend chconst.js > chconst.js.log4

**Comment by MikeHolman** [comment]
Simple JIT doesn't always run. I think we'll often skip directly to full JIT (but I'm not sure exactly what the heuristics are). I think `-off:fulljit` might help you if you only want simple JIT. Also, you might be interested in `-mic:1` (interpret functions only once before triggering JIT) and `-bgjit-` (disable background JIT,).

I believe the main differences are that inlining and our global optimizer are disabled under simple JIT.

**Comment by pleath** [comment]
As you've probably seen, the advantage of simple JIT is faster jitting at the expense of lower code quality. The code is intended to be an intermediate state that a function enters while we're waiting to see if it's worthwhile to JIT it fully.

Try adding -dump:simplejit to commands 2 and 3 and see if there's a difference.

**Comment by dilijev** [comment]
Closing this Question as Answered
