### ISSUE TITLE
Bail on not NativeArray Inifinite rejit

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#3127]
Right now if we bailout on not NativeArray we don't properly update the profile info which causes to rejit with the same type and bailout infinitely.
We have a workaround that caps the number of rejits to 50, but still doesn't solve the source of the problem.

Repro case
for loop body case:
`ch.exe -mic:1 -off:simplejit -bgjit- -wasm -args --start 2 --end 4 -endargs test/wasm/limits.js`

for function case:
`ch.exe -mic:1 -off:simplejit -bgjit- -wasm -off:jitloopbodies -args --start 2 --end 4 -endargs test/wasm/limits.js`

**Comment by dilijev** [comment]
@Cellule is this still planned for 1.8 or should we move it to 1.10?

**Comment by sigatrev** [comment]
This should be fixed. Running on latest I see:
`Rejit Reason,                             Count
FailedEquivalentTypeCheck,                    1
FailedEquivalentFixedFieldTypeCheck,          2
ArrayCheckHoistDisabled,                      3
ExpectingNativeArray,                         2
LdLenIntSpecDisabled,                         3
NoProfile,                                    2
TOTAL,                                       13`

**Comment by MikeHolman** [comment]
We've done a bunch of work improving infinite bailouts. Closing as fixed.
