### ISSUE TITLE
support for [...document.querySelectorAll(selector)].forEach() and for(let element of document.querySelectorAll(selector)){}

### ISSUE THREAD

**Issue by delmarwichnieski** [Microsoft/ChakraCore#3139]
ChakraCore could soon support, after 16215+ these wonderful codes for attaching event handlers

export function setEvent(selector, event, callBack){
	[...document.querySelectorAll(selector)].forEach(function(element){
		element.addEventListener(event, callBack);
	});
}

and

export function setEvent2(selector, event, callBack){
	for(let element of document.querySelectorAll(selector)){
		element.addEventListener(event , callBack, false);
	}
}

More than one good way to replace JQuery $(selector) .on(event, function(){})

**Comment by dilijev** [comment]
@tcare IIRC this is related to Symbol.iterator support in Edge objects? Marking as External.

**Comment by tcare** [comment]
@delmarwichnieski There should be no changes on Chakra side to support these once Edge supports the relevant parts in WebIDL.

... by spec needs to query for @@iterator, so as long as we get that symbol defined we will use it.

**Comment by dilijev** [comment]
@delmarwichnieski: Please search for and upvote the relevant issues on the Edge issue tracker, or open a new issue (see https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) and post a link back here to the issue you open.

**Comment by curtisman** [comment]
Closing as this is not a ChakraCore issue.
