### ISSUE TITLE
Wasm/Asm.js, libavcodec port crash

### ISSUE THREAD

**Issue by MathieuPOUX** [Microsoft/ChakraCore#3165]
Hi,

We have built with emscripten [libavcodec](https://github.com/FFmpeg/FFmpeg/tree/master/libavcodec) to JS. Everything works fine with Chrome or Firefox but with Edge I get a crash as soon as video starts to be decoded by libavcodec.js. There is no other information that just one "access violation" report.
Following the step to reproduce it (crash always!).

1. Unzip [MonaTiny.zip](http://jazzmatazz.free.fr/MonaTiny.zip)
2. Run MonaTiny.exe
3. Open in microsoft edge [http://localhost/player/live.html](http://localhost/player/live.html)

Try with Firefox or Chrome, everything is fine.
We hope with impatiente a solution.
Thanks

**Comment by Cellule** [comment]
Thank you for reporting this.
I was able to reproduce In Edge 38.14393.1066.0 
I will check if this reproduce in the development version and then I will try to provide a workaround if possible.

**Comment by MathieuPOUX** [comment]
Thanks for your response, I look forward your workaround or fix.

**Comment by Cellule** [comment]
Good and bad news.
Good news: the bug doesn't reproduce in Windows Creator Update.
Bad news: I don't know yet what fixed the issue so it might be a little hard to find a good workaround

**Comment by MathieuPOUX** [comment]
It should mean that on next edge version this bug will disappear, we are right?

**Comment by Cellule** [comment]
Yes that's what it means. 
The Windows creator update is already being deployed. You can try to upgrade your version of Windows to see if the bug is really gone for you.

**Comment by MathieuPOUX** [comment]
Thanks! No pb for the workaround, the project is always experimental, we would say that requires Edge >= Creator Update.
