### ISSUE TITLE
ch.exe -v doesn't work correctly if path contains non-ascii characters

### ISSUE THREAD

**Issue by xiaoyinl** [Microsoft/ChakraCore#3178]
`PrintChakraCoreVersion()` in `bin/ch/ch.cpp` uses ANSI version of Windows APIs, like `GetModuleFileNameA`, `GetFileVersionInfoA`, etc., so if the current path contains non-ascii characters and the current code page doesn't support these characters, `GetFileVersionInfoA` fails even though the file is there.

![unicodetest](https://user-images.githubusercontent.com/16713498/27271829-fd8e24e6-5494-11e7-8036-115e268dcb04.png)

Maybe related to #2712.

**Comment by dilijev** [comment]
Yeah I noticed this while adding support for printing version number and in working on #2712. This should be fixed, but might take some work to factor out the ASCII versions of APIs.
