### ISSUE TITLE
How can i build ChakraCore for IOS?

### ISSUE THREAD

**Issue by tommyZZM** [Microsoft/ChakraCore#3179]
i tried `--arch=arm` and `--target=ios`, neither works

are there any roadmap for building for IOS ?

**Comment by EdMaurer** [comment]
There is no build configuration for iOS today. Some friends of the project have made it work on iOS, but there is not a PR or public fork at present.

**Comment by EdMaurer** [comment]
Friends who did the port: http://www.janeasystems.com/blog/node-js-meets-ios/

**Comment by tommyZZM** [comment]
related info with this issue~
https://github.com/janeasystems/node-mobile-react-demo/issues/2#issuecomment-333850770
https://github.com/janeasystems/nodejs-mobile

**Comment by obastemur** [comment]
And the open source repository! -> https://github.com/janeasystems/nodejs-mobile

**Comment by vovkasm** [comment]
May be its time to make PR? )
