### ISSUE TITLE
Date locale functions fail if Map is overridden

### ISSUE THREAD

**Issue by lpd-au** [Microsoft/ChakraCore#3189]
https://stackoverflow.com/a/44637643/646551

### Steps to reproduce

Run the following code using ch.exe:
```
// var earlyDateString = new Date().toLocaleString();
Map = {};
var dateString = new Date().toLocaleString();
```
### Expected result

dateString contains something like "‎20‎/‎06‎/‎2017‎ ‎5‎:‎46‎:‎36‎ ‎PM"

### Actual result
```
TypeError: Intl is not available.
   at Global code (e:\my downloads\cc_windows_1_5_2\bin\x64_release\test.js:3:1)
```
### Workaround

Uncomment the first line so Intl is initialised before Map is overridden.

### Other browsers

Google Chrome: Not affected
Mozilla Firefox: Not affected

**Comment by curtisman** [comment]
Probably regression from #2358

**Comment by dilijev** [comment]
Yep, looks like tainting affected the maps being used in the caches which caused Intl to fail to initialize. The fix is probably to expose a `platform.Map` and use `new platform.Map()` instead of `new Map()`.

**Comment by dilijev** [comment]
I have a fix. Will post the PR momentarily.
