### ISSUE TITLE
can't cleanup after JsSetPromiseContinuationCallback

### ISSUE THREAD

**Issue by willportnoy** [Microsoft/ChakraCore#3192]
I'd like some method to remove my non-null promise continuation callback from the JavaScriptContext.

However, I get a ``JavaScriptErrorCode.NullArgument`` if I call ``JavaScriptContext.SetPromiseContinuationCallback(null, IntPtr.Zero)``

I presume the argument validation is too strict?

**Comment by curtisman** [comment]
Hmm... probably.  I am curious what your scenario is that you need to clear the callback?

**Comment by willportnoy** [comment]
It's mostly in the spirit of paired initialization and cleanup operations.

In my particular case, I have an async method within a class instance Q that contains a queue for both promise and SynchronizationContext continuations, and the delegate for the promise continuation call callback has a target object of that class instance Q, but the JavaScriptContext has a longer lifetime than Q, so I want to detach my promise continuation callback delegate when the async method has drained the queue and all other pending operations have completed.
