### ISSUE TITLE
HasAnyWriteToFormals in deferparse

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#3194]
In the following test case

```js
function foo() {
  return function bar(a) {
    a = 4;
    console.log(arguments[0])
  }
}

foo()(2);
```

In the parser (Parse.cpp:1710), when we defer parse `foo` (or -force:deferparse) it looks like we incorrectly set `m_currentNodeFunc->sxFnc.SetHasAnyWriteToFormals(true);` to `foo`.

I am not entirely sure of the implication of this. It looks like we use that flag to do `arguments` optimization. Maybe we are missing some optimization opportunities because of this.

**Comment by rajatd** [comment]
@pleath, do you happen to have more context on this?
