### ISSUE TITLE
`{get}` should be a valid object literal

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#320]
We currently throw a syntax error for the following case:

```js
let get = 1;
let obj = { get };
```

**Comment by dilijev** [comment]
If this is a parser front-end issue and non-blocking I recommend adding "Accepting PRs"

**Comment by ianwjhalliday** [comment]
I have a fix already, I'm just finishing writing tests.

**Comment by ianwjhalliday** [comment]
:cake:
