### ISSUE TITLE
FOR OF loop works on Chrome and Firefox but not on Microsoft Edge 40.15063.0.0

### ISSUE THREAD

**Issue by Benqzq** [Microsoft/ChakraCore#3229]
I have a Wordpress Website (formen.co.il) In which I use a page builder. The page builder for some odd reason adds `<br>` tags to buttons added with it. To remove these added br tags with Js, I added a custom.js file, to which I added the following Js code:

```
for (const element of document.querySelectorAll(".elementor-button-link br")) {
	element.style.display = "none";
}
```

I have tested the site from latest Chrome, Firefox and from **Edge 40.15063.0.0** as well.

In my Chrome and Firefox check it seems the code works and remove the br tags but in Edge they keep appear: The buttons are still "taller" because of them and they appear in DOM.

You could test this yourself, for example, in [](http://formen.co.il/beard-clearing/), if you navigate to the footer of the site "צור קשר" and "לקריאת התקנון".

![1](https://user-images.githubusercontent.com/13021900/27565409-cdd9586c-5ae6-11e7-8908-a85e6b1f478f.PNG)

![2](https://user-images.githubusercontent.com/13021900/27565411-d0481a52-5ae6-11e7-86d7-d424e7d93de5.PNG)

**Comment by akroshg** [comment]
@Benqzq thanks for reporting this. I believe this issue is fixed.
This was happening as the for..of was not supporting the DOM objects as iterable objects.
If you try with latest Edge (From the Windows Insider program) - you should be able to see the correct result.
