### ISSUE TITLE
Question/bug: functions created by JsCreateNamedFunction when converted to string simply show the function name

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#3241]
When invoking toString() on a native method, I would think one generally expects to see something like the following, if the function were called 'foo':

"function foo() { [native code] }"

If a function is created via JsCreateNamedFunction, however, invoking toString() on it only gives back:

"foo"

Was this by any chance intended behavior?  Is there some other way to generate a native code method that still shows its name when its toString() method is called?

**Comment by liminzhu** [comment]
Hi @markt-. It's a bug https://github.com/Microsoft/ChakraCore/issues/586 on our end. I'll defer to @atulkatti who is the assignee of the bug.
