### ISSUE TITLE
ChakraCore on android is viable ?

### ISSUE THREAD

**Issue by luciancaetano** [Microsoft/ChakraCore#3270]
Does ChakraCore have a build for android, is it really efficient and works well for android without bugs or performace?
Well I would very much like to use this engine in a desktop / android project, but I have this doubt, because in the case of the controller I would have to choose either v8 or JavaScriptCore.

**Comment by obastemur** [comment]
@luciancaetano It is not officially supported and the current level is mostly keeping the code base reasonably close to something working.

See also #3179 (It is for iOS but similar answer applies to this issue as well)
