### ISSUE TITLE
[JSRT]  JsNativeFunction arguments[0] yields undefined instead of globalObj when called as property of globalObj

### ISSUE THREAD

**Issue by liminzhu** [Microsoft/ChakraCore#3276]
Not documented on the [header](https://github.com/Microsoft/ChakraCore/blob/d3b6d103bbfa6207d18b74cbf77ca9a48455b8e6/lib/Jsrt/ChakraCommon.h#L694), but if it's the same as `JsCallFunction` then `arguments[0]` should be `this`. The behavior only seems right if in strict mode. Is this a bug or intended? 

```cpp
#define _JSRT_
#include "ChakraCore.h"
#include <assert.h>
#include <string>
#include <iostream>

using namespace std;

void setCallback(JsValueRef object, const wchar_t *propertyName, JsNativeFunction callback, void *callbackState)
{
	JsPropertyIdRef propertyId;
	JsGetPropertyIdFromName(propertyName, &propertyId);
	JsValueRef function;
	JsCreateFunction(callback, callbackState, &function);
	JsSetProperty(object, propertyId, function, true);
}

JsValueRef CALLBACK func(JsValueRef callee, bool isConstructCall, JsValueRef *arguments, unsigned short argumentCount, void *callbackState)
{
	JsValueRef undefined, global;
	JsGetUndefinedValue(&undefined);
	JsGetGlobalObject(&global);
	assert(arguments[0] == undefined);  // SUCCESS
	assert(arguments[0] == global);        // FAIL
	return JS_INVALID_REFERENCE;
}

int main()
{
	JsRuntimeHandle runtime;
	JsContextRef context;
	JsValueRef result;
	unsigned currentSourceContext = 0;

	JsCreateRuntime(JsRuntimeAttributeNone, nullptr, &runtime);
	JsCreateContext(runtime, &context);
	JsSetCurrentContext(context);

	JsValueRef g;
	JsGetGlobalObject(&g);
	setCallback(g, L"func", func, nullptr);

	wstring script = L"func()";
	JsRunScript(script.c_str(), currentSourceContext++, L"", &result);

	return 0;
}
```

**Comment by pleath** [comment]
Are you saying the expectation is that arguments[0] will match the first actual parameter or “this”? It should be the first actual parameter.

-- Paul

**Comment by liminzhu** [comment]
`This`. 

If I pass in `f(1)`, I get 2 items in `arguments` and `arguments[0]` is still undefined. If I set `f` as a property of another object `o`, `arguments[0]` and `o` are the same. Both lead me to believe this should be `this` without looking at the implementation.

**Comment by liminzhu** [comment]
@curtisman ?

**Comment by curtisman** [comment]
Can't we just document our current behavior?

**Comment by liminzhu** [comment]
Fixed https://github.com/Microsoft/ChakraCore/wiki/JsNativeFunction/_compare/4d68aa3edcbc55ede275befeb234fa94c689a0f7
