### ISSUE TITLE
Add ETW support

### ISSUE THREAD

**Issue by MikeHolman** [Microsoft/ChakraCore#328]
Currently ChakraCore disables ETW because of reliance on private manifests. I think we should look into making new instrumentation manifests for ChakraCore to enable ETW support.

**Comment by mjsabby** [comment]
Any updates on this?

**Comment by digitalinfinity** [comment]
Resolved with Microsoft/ChakraCore#1986. FYI @mrkmarron. @mjsabby, please feel free to give a recent ChakraCore binary a try and see if it works for you. We can tackle further issues with ETW as separate issue now that the instrumentation manifest is in GitHub.

**Comment by siam-abdullah** [comment]
I am using ChakraCore(1.4) in managed code(C#) using JSRT api. I am trying to get the ETW events but It looks it is not working for me. Does ETW work for 1.4 version  or is their any flag do i need to enable ?

**Comment by Funkwai** [comment]
I would like to enable ETW for profiling the stack frames of both JavaScript and C/C++ code at runtime, to find out which part of a program is a hotspot or bottleneck.

can you tell me simple instruction how to enable ETW to log the event? (I'm new to Windows development environment) I built ChakraCore for x64 with ENABLE_JS_ETW from VS 2107 and run a command line "ch.exe" in my use case, do I have to register the handle through TRACELOGGING_DEFINE_PROVIDER in ChakraCore like ETW introduction at https://channel9.msdn.com/Events/Build/2017/P4099?
