### ISSUE TITLE
.gitattributes missing

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3305]
Discovered in #3303

Restoring the .gitattributes caused a bunch of tests to start failing -- probably baselines which were checked in since .gitattributes changed. See: https://ci2.dot.net/job/Microsoft_ChakraCore/job/release_1.6/job/x64_debug_prtest/341/

See https://github.com/dilijev/ChakraCore/tree/gitattr for the commit to restore .gitattributes.

/cc @tcare

**Comment by tcare** [comment]
Note that we need to do this for ChakraFull too.. which is more work since it never had a .gitattribues.

**Comment by dilijev** [comment]
This has caused some CI issues, so I'll fix it now.
