### ISSUE TITLE
xplat: Enable JIT for debugging

### ISSUE THREAD

**Issue by helloqirun** [Microsoft/ChakraCore#3352]
I compiled ChakraCore using the official build guide. 
On ubuntu 16.04, ch crashes with the following test case.
I also noticed that if we slightly change the code (using a proper indentation), the Seg fault will be gone.
The hashtag of my chakracore build is 
commit cb9c8271c8c9e2a0daec635504b5279168d92f1b

$ ~/chakracore/ChakraCore/out/Release/ch abc.js
Segmentation fault (core dumped)
$ cat abc.js
```
function
run
()
{}
WScript.Attach(run)
WScript
    .
Detach
(
run
)
```

**Comment by obastemur** [comment]
This is not Linux specific.

```
ASSERTION 7721: (/.../lib/Runtime/./Base/FunctionBody.h, line 874) this->GetState() != CleanedUp
 Failure: (this->GetState() != CleanedUp)
Illegal instruction: 4
```
