### ISSUE TITLE
Fix asm.js in ES6 Modules

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#3355]
Currently asm.js has numerous problems in es6 modules.
- [ ] Support reparsing without asm.js on validation error (currently throws)
```js
WScript.LoadModule(`
function asmModule() {
  "use asm"
  function x(v) {
    v = v | 0;
    return v | 0;
  }
}`);
```
- [ ] Add support for asm.js module in default export
```js
WScript.LoadModule(`
export default function AsmDefaultExport() {
  "use asm"
  function x(v) {
    v = v | 0;
    return v | 0;
  }
  return x;
}`)
```
- [ ] Fix nullptr A/V in JSRT api when trying to use asm.js in module (can repro with `ch` or `jshost -jsrt`)
```js
WScript.LoadModule(`
function AsmModule() {
  "use asm"
  function x(v) {
    v = v | 0;
    return v | 0;
  }
  return x;
}`)
```

**Comment by EdMaurer** [comment]
I'm inclined to close this. Won't folks just use wasm now?

**Comment by Cellule** [comment]
We've explicitly disabled asm.js in es6 modules in #3546.
I think it's fine to close for now.
