### ISSUE TITLE
Jsrt documentation is incorrect

### ISSUE THREAD

**Issue by flingenfabriken** [Microsoft/ChakraCore#3367]
Hello,

the documentation for _FetchImportedModuleFromScriptCallBack_ is copy and pasted from _NotifyModuleReadyCallback_. Could this be fixed with correct documentation? This would be very helpful.

You can check yourself: https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L70-L83

**Comment by dilijev** [comment]
@liminzhu Can you also ensure the wiki is updated with this fix?

**Comment by liminzhu** [comment]
Apology for not seeing this earlier @flingenfabriken @dilijev . I will make a PR on this.

**Comment by flingenfabriken** [comment]
I cannot even find a reference to it actually being used in ChakraCore other than there being a getter and a setter.

**Comment by liminzhu** [comment]
We used it to implement module support in our ch host https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp#L312.

**Comment by liminzhu** [comment]
Fixed by https://github.com/Microsoft/ChakraCore/pull/4581
