### ISSUE TITLE
Super property reference in global scope should be an early syntax error

### ISSUE THREAD

**Issue by bterlson** [microsoft/ChakraCore#3371]
Is presently a runtime reference error. `super()` has the proper error, however.

```js
super.foo
```
Expected: Early syntax error
Actual: Runtime reference error

**Comment by tcare** [comment]
I had a go at this, but it revealed some other cases that we miss that are non-trivial (eval in bad places :()

I'll come back to this when I have less feature work.

**Comment by rhuanjl** [comment]
This has been fixed for some time.
