### ISSUE TITLE
Properties of the global object created from function declarations in indirect eval should be configurable

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#3375]
```js
(0, eval)('function f() { }');
print(JSON.stringify(Object.getOwnPropertyDescriptor(this, 'f')));
```

Expected:  {"writable":true,"enumerable":true,"configurable":true}  
Actual:  {"writable":true,"enumerable":true,"configurable": *false*} 

See [EDI](https://tc39.github.io/ecma262/#sec-evaldeclarationinstantiation)'s exclusive use of CreateMutableBinding.

**Comment by akroshg** [comment]
this should be fixed by #3722
