### ISSUE TITLE
Implement Object Rest & Spread

### ISSUE THREAD

**Issue by bterlson** [microsoft/ChakraCore#3406]
The proposal is stage 3 and will very likely be in ES2018. Object rest and spread are very useful tools (especially in some ecosystems like React) and idioms from it are becoming more common (eg. shallow copy via `let copy = { ... otherObj };`)

Specification text: https://github.com/tc39/proposal-object-rest-spread

**Comment by dilijev** [comment]
Do any engines or compilers support this currently?

**Comment by bterlson** [comment]
Babel, TypeScript, Chrome, Firefox all implement. Not sure about JSC.

**Comment by dilijev** [comment]
Oh I see it in the proposal now, my bad: https://github.com/tc39/proposal-object-rest-spread#transpilers

**Comment by sabrehagen** [comment]
If somebody can point me to the relevant location, I'm happy to take a look.

**Comment by styfle** [comment]
PR is being reviewed now which will soon make it Stage 4 https://github.com/tc39/ecma262/pull/1048

**Comment by styfle** [comment]
Stage 4 and merged 🎉 
It is in the [EcmaScript 2018 spec](https://tc39.github.io/ecma262/2018/#sec-object-initializer) 👈

**Comment by sethbrenith** [comment]
Yes, this is in progress, so I'd recommend choosing a different feature to work on, but thanks for your interest!

**Comment by styfle** [comment]
@sethbrenith @tcare We are all looking forward to this feature, thanks! 👍 

Even though there are only 8 upvotes on this issue, there are over 400 upvotes on [MS Edge UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/31257100-spread-operator-for-object-literals).

![uservoice](https://user-images.githubusercontent.com/229881/41982486-87399736-79f9-11e8-89fa-5f9cecd74b54.png)

So you have quite the fanbase here 😄

**Comment by chicoxyzzy** [comment]
Isn't it implemented already? https://github.com/Microsoft/ChakraCore/pull/5498

**Comment by chicoxyzzy** [comment]
O_O how did I unassigned someone?

**Comment by sethbrenith** [comment]
@chicoxyzzy No worries about unassigning. Object spread and rest are implemented, but not yet enabled by default, so I'd personally prefer to leave the issue open until they're enabled. A feature that exists in the code but is inaccessible doesn't seem like it should be marked as complete.

**Comment by styfle** [comment]
> This feature is still experimental and needs additional work

See this comment for more info: https://github.com/Microsoft/ChakraCore/pull/5268#issuecomment-411438657

**Comment by sethbrenith** [comment]
Perf looks fine compared to other engines, at least based on a very simple test.

```javascript
(function () {
	var obj = { a: 1, b: new Date(), c: [] };
	var now = Date.now();
	var sum = 0;
	for (var i = 0; i < 1e6; ++i) {
		sum += {i, ...obj}.i;
	}
	print(Date.now() - now);
	var now = Date.now();
	for (var i = 0; i < 1e6; ++i) {
		let {["b"]:b, ...x} = obj;
		sum -= x.a;
	}
	print(Date.now() - now);
})();
```

```
>eshost -h * \scripts\spread.js
#### jsvu-sm
470
217

#### ch-local-build
411
397

#### jsvu-d8
624
521

#### jsvu-jsc
806
734
```

**Comment by styfle** [comment]
@sethbrenith The quote about "additional work" needed was from @MSLaguana 

It looks like you are both "members" so I assume you have discussed what work is needed to move this forward. Can you give an update here? 😄

**Comment by sethbrenith** [comment]
Yes, there's still some work to do on this feature. In particular, we need to update our internal fuzzing tools so that they exercise object spread and rest, so we get some additional test coverage. We also need to verify interaction with the debug tools.

**Comment by rhuanjl** [comment]
I assume this can be closed now? https://github.com/microsoft/ChakraCore/pull/6130

**Comment by sethbrenith** [comment]
Good point, thanks
