### ISSUE TITLE
[JSRT] Default implementation for promise continuation & timers

### ISSUE THREAD

**Issue by liminzhu** [Microsoft/ChakraCore#341]
Recent feedback I've heard about Chakra, which applies to ChakraCore as well. I think tracking the issue here would be beneficial to confused users and serve as a good link for the future. 

> In the three most recent projects I’ve seen or used Chakra, everyone is re-implementing timers and promise continuation queues etc. when hosting. It would be great if there were default implementations that could be plugged in.

The current state of the world is, 
- Promise continuation - To use promises in scripts, JSRT users need to supply a [JsPromiseContinuationCallback](https://github.com/Microsoft/ChakraCore/wiki/JsPromiseContinuationCallback) specifying the task-queuing mechanism because it is very host-specific. If all you want is a working implementation, we have code snippet in [documentation](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#promises) or [sample](https://github.com/Microsoft/Chakra-Samples/blob/master/Chakra Samples/JSRT Universal Windows Apps Hosting Samples/C%2B%2B/JsRT_UWP_Sample/ChakraHost.cpp#L8) that you can copy from. 
- Timers - this again is a host-specific thing and we do not provide default implementation. There might be some copy-able code in ch.exe.

**Comment by liminzhu** [comment]
@curtisman @Yongqu

**Comment by agarwal-sandeep** [comment]
@liminzhu this seems like adding some kind of event loop inside the engine which becomes very host and platform specific. We should improve the samples and update the wiki. //cc @dilijev @kfarnung.

**Comment by liminzhu** [comment]
This was done.

[Sample (promise)](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L14)
[Sample (timer)](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L237)
[Sample (event loop)](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L129)
[Wiki (promise)](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#promises)

**Comment by pallammadhukar** [comment]
Hi @liminzhu 

Thanks for providing sample and documentation for promise. Sorry to post here on closed thread. But I felt my query is related to this. Following is my query:

We tried promise sample. It is working for global promise's. But if the promise is defined inside some JS function then the resolve/reject callback is not executing. This is because we have not executed the queued callbacks after dynamic function invoke.

1. Why do we need queue for promise continuation. Can't we execute the task(resolve/reject callback) then and there(inside promise continuation callback)?

2. We also observed that if the queue is static then it is working and not static is giving EngineExecutionException. Please Exaplain?

**Comment by pallammadhukar** [comment]
Hi @liminzhu , I have update code in chakra code sample for global/function scope issue. You can download [here](https://1drv.ms/u/s!Arbpd1gqlZBnhZNrMNmnnWg_Lvh9CA).

You can observe the different behavior when you comment/uncomment line no 136 in ChakraHost.cs file. 

Actually we do not want to control the promise continuation callback in host, For us javascript promise's needs to be called automatically. Can we achieve by removing the promise continuation callback registration?

**Comment by liminzhu** [comment]
Hey sorry @pallammadhukar I've been away so I will take a look at your code sample once I'm back in office if you're not in a hurry (others feel free to look at it while i'm gone ofc). 

For the promise continuation callback, you cannot have promise supported by removing the callback altogether. As a JS engine we have to be spec-compliant and not inventing things that are not supposed to be in the JS engine. The enqueue job thing is one such case that if we provide an implementation, we deviate from the spec and also like I said before we cannot possible provide a task queue that satisfy requirements of all possible JS hosts. That's way this functionality is meant to provided by the host to the JS engine.
