### ISSUE TITLE
validity property of type ValidityState is missing tooShort property

### ISSUE THREAD

**Issue by Eccenux** [Microsoft/ChakraCore#3410]
Both IE and Edge is missing `tooShort` property of `validity` property.

See [ValidityState specification](https://www.w3.org/TR/html5/forms.html#validitystate) and [compare with MSDN](https://msdn.microsoft.com/en-us/library/hh772951(v=vs.85).aspx).

Meaning of `tooShort` from spec:

>  Suffering from being too short
> 
>  When a control has a value that is too short for the form control `minlength` attribute (input `minlength`, textarea `minlength`).

**Comment by dilijev** [comment]
@Eccenux If you haven't already, please open your issue on the Edge issue tracker. https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues

**Comment by curtisman** [comment]
Closing as this is not a ChakraCore issue.

**Comment by Eccenux** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13022509/
