### ISSUE TITLE
[linux] Implement GetCurrentThreadStackBounds

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#344]
A stub API- GetCurrentThreadStackBounds- is defined in CommonPal currently. We need to implement it to replace instances in the code where we rely on the Win32 specific-NtTeb to get the current thread's stack base and limit. One possible implementation for this API would be to use the NtTeb approach on Windows and pthread_attr_getstack on platforms with pthread support. It's unclear if we can do this without using pthread_attr_get_np though.

**Comment by xanlpz** [comment]
It seems the code already does what is described here (NTCurrentTeb on Windows, GetCurrentThreadStackLimits with pthread_attr_get_np on Linux). Is anything missing?

**Comment by obastemur** [comment]
There is not much to do here. Closing
