### ISSUE TITLE
Got a message JSStringToPointer could not be located in jscript9

### ISSUE THREAD

**Issue by oferch** [Microsoft/ChakraCore#3441]
Hello,

I've developed COM component based on chakra engine.
I'm building it one a machine where IE11 is installed. I link with jsrt.lib
When I'm running it on another machine with IE11 installed it works fine, but when I come to register it on a machine with IE10 I get the following Error "The Procedure entry point JsStringToPointer could not be located in JSCRIPT9.dll"

Doesn't IE10 engine support that? Is it something else?
Any assistance would be appreciated.

Best,

Ofer

**Comment by MikeHolman** [comment]
That's not supported in IE10.

**Comment by oferch** [comment]
Should that be the same between IE10 & IE11? I didnt see any comment sin documentation about that (only about differences between edge and IE)
So basically I should Link against the ChakraCore, and make Sure I have the right version?

**Comment by liminzhu** [comment]
To be clear JSRT hosting interface for Chakra is available since IE11 ([documentation](https://docs.microsoft.com/en-us/scripting/chakra-hosting/hosting-the-javascript-runtime)). ChakraCore on the other hand goes all the way back to support Windows 7 SP1.
