### ISSUE TITLE
[linux] Add coloring to the Output class

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#346]
Output::DirectPrint relies on Win32 Console APIs to change the color to be used while printing to the Console. We should use a cross-platform approach here- perhaps ANSI control characters? @dilijev any ideas here?

**Comment by dilijev** [comment]
There's a list of ANSI escape sequences for reference [here](http://ascii-table.com/ansi-escape-sequences.php) (there's a whole section on the colors).

Windows console supports ANSI color sequences. I just tried the following to make sure:

```
@echo [1;31;47m hello [0m
```

To try that you'll have to use something like vim to enter the escape character before each `[`. In vim enter the escape character by entering insert mode and then doing ^v^[ or ^v027.

I've also created this gist: https://gist.github.com/dilijev/6e025d37ff646e33a0e2 where you might be able to copy out the text including the escape character.

**Comment by dilijev** [comment]
I think it's a good idea to use ANSI sequences instead of Windows console APIs because it is supported on Windows and one less thing we will have to make a special case for in the xplat effort.

**Comment by ianwjhalliday** [comment]
How does that affect redirection of stdout and stderr to a file though?

**Comment by dilijev** [comment]
On Linux the redirect and pipe operators `>` and `|` eliminate the ANSI color sequences in-stream. You actually have to use a different command to capture a console session to actually capture them (so it's more of a pain if you actually want them).

On Windows it appears that the control sequences are included in the stream.

Funnily enough, my example uses bold red which didn't render as brighter red in echo but DID appear when I piped it through git's version of `cat`:

`ansi.cmd | cat`

So it seems the windows console's default handling of ANSI sequences isn't complete. I would imagine the msysgit package probably renders the sequences using the windows console APIs which the windows console commands don't seem to do completely.

**Comment by dilijev** [comment]
Screenshot for fun:

![image](https://cloud.githubusercontent.com/assets/494055/13187730/c30f2660-d701-11e5-9fd1-464eb1242b30.png)

**Comment by digitalinfinity** [comment]
@dilijev does windows support them on Window 8.1 and below? The ANSI sequence support might just be on Win10...

**Comment by dilijev** [comment]
I'll check. I may have been mistaken about the terminal emulators themselves trimming the escape sequences in those operators. Linux programs are able to detect when they are being directed to a non-console device.

I will try some experiments to find out the answers to that question and whether older windows versions support ANSI color sequences at all.

**Comment by dilijev** [comment]
Using windows server 2008 R2 (~= Windows 7 SP1), looks like no support for ANSI color escapes:

![image](https://cloud.githubusercontent.com/assets/494055/13192377/1295fe20-d720-11e5-8be8-73cc74f07c9a.png)

**Comment by dilijev** [comment]
Same result with Windows Server 2012 R2 (~= Windows 8.1).

So I guess it's new in Windows 10 and we can't rely on it if we support OSes before Windows 10.

**Comment by dilijev** [comment]
Okay I did a couple of experiments on Linux and determined that it is indeed the programs themselves not the redirection or pipe operators that decide about the color sequences.

I tested with a basic C program using printf and with a bash script using echo.

![image](https://cloud.githubusercontent.com/assets/494055/13192795/bdf8d1f8-d724-11e5-9d4f-2816895ff840.png)
