### ISSUE TITLE
isShared uninitialized in copy-ctor of JsTypeValueInfo

### ISSUE THREAD

**Issue by LouisLaf** [Microsoft/ChakraCore#3497]
The isShared bool is uninitialized in the copy-ctor.  It should be initialized to false since we make a new ValueInfo in it.  If it happens to be true, we will get unnecessary copies.

class JsTypeValueInfo : public ValueInfo
{
private:
    JITTypeHolder jsType;
    Js::EquivalentTypeSet * jsTypeSet;
    **bool isShared;**

public:
    JsTypeValueInfo(JITTypeHolder type)
        : ValueInfo(Uninitialized, ValueStructureKind::JsType),
        jsType(type), jsTypeSet(nullptr), **isShared(false)**
    {
    }

    JsTypeValueInfo(Js::EquivalentTypeSet * typeSet)
        : ValueInfo(Uninitialized, ValueStructureKind::JsType),
        jsType(nullptr), jsTypeSet(typeSet), **isShared(false)**
    {
    }

    JsTypeValueInfo(const JsTypeValueInfo& other)
        : ValueInfo(Uninitialized, ValueStructureKind::JsType),
        jsType(other.jsType), jsTypeSet(other.jsTypeSet)                   **<<<<<<<<<<<<<<<**
    {
    }

**Comment by dilijev** [comment]
Looks like this is fixed in #3503.
