### ISSUE TITLE
Arithmetic result exceeded 32 bits.

### ISSUE THREAD

**Issue by GangadharBommasani** [Microsoft/ChakraCore#3508]
We are trying to upload 5GB file on microsoft edge version Microsoft Edge 38.14393.1066.0 using java script  fromdata. 

const formData = new FormData();
formData.append("file", file, file.name);

Please note that we are not using chunk file reading . Directly giving file to browser. Is this issue with javascript or windows operating system? 

Same file size is working in Chrome and FireFox browser

**Comment by MikeHolman** [comment]
This is a question better directed at the Edge team, as FormData is a web API, not a JS API.

You can report issues with Edge here: http://issues.microsoftedge.com
