### ISSUE TITLE
Intl built-in functions have wrong names

### ISSUE THREAD

**Issue by goyakin** [Microsoft/ChakraCore#351]
[Test262 PR](https://github.com/tc39/test262/pull/505)

**Comment by dilijev** [comment]
@goyakin Could you be more specific about expected versus actual behavior in the situations that are incorrect?

**Comment by goyakin** [comment]
If I remember correctly, we differ in two ways:

  * Names of some functions, e.g. `Intl.Collator.supportedLocalesOf`, has the prefix `bound`
  * Getters **don't have** a name attached to them, e.g. `Intl.Collator.prototype.compare`
  * Bound functions returned from the getters **have** a name, e.g. `bound compare`
