### ISSUE TITLE
Lexical Declarations cannot appear after a label

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#352]
ChakraCore currently allows lexical declarations (let, const, class, function*) to appear after a label.  Labels can only prepend a Statement, not a Declaration, according to the ES spec.

See grammar at https://tc39.github.io/ecma262/#sec-ecmascript-language-statements-and-declarations

FunctionDeclaration gets an exception and is allowed, presumably for back-compat.  GeneratorDeclaration does not get the exception, however, and so it not allow. See [LabelledItem](https://tc39.github.io/ecma262/#prod-LabelledItem)

Async functions presumably will also be disallowed by way of being a HoistableDeclaration and not excepted by LabelledItem.

E.g. each of these lines should be a syntax error but are not currently:

``` javascript
a: let x;
b: const y = 0;
c: class z { }
d: function* w() { }
e: async function u() { } // pending finalization of async function spec
```

**Comment by goyakin** [comment]
Isn't `d: function w() { }` actually valid since the grammar for `LabelledItem` allows a function declaration?

**Comment by ianwjhalliday** [comment]
Yes, good catch.

But ugh, this means it is not allowed for GeneratorDeclaration specifically.  And presumably AsyncFunctionDeclaration later on.

I'll update the description

**Comment by ianwjhalliday** [comment]
This is notable: https://tc39.github.io/ecma262/#sec-labelled-function-declarations

**Comment by goyakin** [comment]
Test262 [test cases for IterationStatement](https://github.com/tc39/test262/pull/510)

**Comment by littledan** [comment]
Another case where a label is inappropriately allowed is a label immediately before the end of script, e.g., `eval("x:")` (which JSC, V8 and SpiderMonkey reject, but ChakraCore allows).
