### ISSUE TITLE
warning C4768: __declspec attributes before linkage specification are ignored

### ISSUE THREAD

**Issue by Rastaban** [microsoft/ChakraCore#3521]
Warning C4768 is an off by default warning in the latest MSVC compiler, which will turned on in the next major compiler release.  This warning is hit once in the ChakraCore project.

D:\Chakra\src\lib\Runtime\Base\ThreadContext.cpp(60): warning C4768: __declspec attributes before linkage specification are ignored

The line:

    _NOINLINE extern "C" void* MarkerForExternalDebugStep()

should be

    extern "C" _NOINLINE void* MarkerForExternalDebugStep()

**Comment by MikeHolman** [comment]
Code has changed and that declaration is no longer there
