### ISSUE TITLE
Should be a runtime TypeError to assign to a const variable, not an early SyntaxError

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#355]
Our implementation of const semantics no longer match the final semantics settled upon in the ES6 publication.  Const assignment used to be an early error but now the spec deems it a late runtime error.

const declarations are created in an environment record via [CreateImmutableBinding](https://tc39.github.io/ecma262/#sec-declarative-environment-records-createimmutablebinding-n-s)(name, true).  The second argument means that the binding is made "strict" which is important below.

Assignments to variables are evaluated via [PutValue](https://tc39.github.io/ecma262/#sec-putvalue).  E.g. step 1.f for simple assignment in https://tc39.github.io/ecma262/#sec-assignment-operators-runtime-semantics-evaluation

In the case of a variable assignment, PutValue calls into [SetMutableBinding](https://tc39.github.io/ecma262/#sec-declarative-environment-records-setmutablebinding-n-v-s) on the corresponding environment record.  SetMutableBinding throws if the S parameter is true in step 6.  For const variables this parameter will be true (see CreateImmutableBinding above).

E.g.
```javascript
print('hello'); // 'hello' should be printed
const x = foo(); // foo() should be called, then TypeError thrown
// Instead we throw a SyntaxError during parse.
```

**Comment by ianwjhalliday** [comment]
@pleath is this change going to be difficult or have any gotchas?

**Comment by suwc** [comment]
Pull request
https://github.com/Microsoft/ChakraCore/pull/557

**Comment by suwc** [comment]
PR merged
