### ISSUE TITLE
Missing headers in getResponseHeader Microsoft EdgeHTML 16.16257

### ISSUE THREAD

**Issue by ScottDuke** [Microsoft/ChakraCore#3559]
Not sure if this is the right place for this bug but was testing a client/api on Edge 16.16257 and noticed that when getting the headers from the ajax response using `request.getAllResponseHeaders();` would not return any custom headers. 
Was working ok in previous versions. 

[Example](http://www.test-cors.org/#?client_method=GET&client_credentials=true&client_headers=x-auth%3A%20test&server_enable=true&server_status=200&server_credentials=true&server_methods=get&server_headers=x-auth&server_expose_headers=x-auth&server_response_headers=x-auth%3A%20test&server_tabs=local)
Viewing the link in Chrome Version 60.0.3112.101 once you click 'Send request' button in the results can see the custom `x-auth` header.

```
XHR exposed response headers:
content-type: application/json
cache-control: no-cache
x-auth: test
expires: Mon, 21 Aug 2017 11:33:52 GMT
```

but when running the same example on Edge 16.16257 get the following result:
```
XHR exposed response headers: 
Cache-Control: no-cache
Content-Type: application/json
Expires: Mon, 21 Aug 2017 11:23:30 GMT
```

Microsoft EdgeHTML 15.15063
```
XHR exposed response headers: 
Cache-Control: no-cache
Content-Type: application/json
Access-Control-Allow-Origin: http://www.test-cors.org
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: x-auth
x-auth: test
X-Cloud-Trace-Context: 3fdf25c83c5e5aaa84e8fe49da94d6eb
Date: Mon, 21 Aug 2017 11:49:02 GMT
Server: Google Frontend
Expires: Mon, 21 Aug 2017 11:49:02 GMT
Content-Length: 978
```

**Comment by liminzhu** [comment]
Since this is most likely an EdgeHTML issue, can you open the same bug on the Edge issue tracker?
 See [instructions](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

**Comment by ScottDuke** [comment]
@liminzhu ok thanks, I've created the a bug on the Edge issue tracker.

**Comment by liminzhu** [comment]
@ScottDuke no problem. Closing the issue.
