### ISSUE TITLE
Enable WebAssembly on xplat

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#3561]
- [ ] Remove `exclude_xplat` tag from test folder `WasmSpec` and from individual tests in test folder `wasm`
- [ ] Fix failing tests
- [ ] Enable WebAssembly in release builds (remove `#if defined(_WIN32) || (defined(__clang__) && defined(ENABLE_DEBUG_CONFIG_OPTIONS))` in CommonDefines.h

**Comment by obastemur** [comment]
@Cellule any update on this?

**Comment by Cellule** [comment]
We haven't allocated any resources to fix the issues that we have yet.
We have recently disabled WebAssembly by default even on test builds.

**Comment by kasper3** [comment]
Is this scheduled for next quarter? If it's just about the build configuration / cmake issue, would be sad to see 2017 passing by without wasm support on unix.. :(

**Comment by digitalinfinity** [comment]
@kasper3 curious, do you have a specific use case in mind for WASM on Unix using ChakraCore?
