### ISSUE TITLE
Does Microsoft contribute to external Open-Source projects?

### ISSUE THREAD

**Issue by jcoffland** [Microsoft/ChakraCore#3593]
I ask because I have [an Open-Source project](http://camotics.org/) that has a significant, although niche, following.  I've built [a library that makes it easy to use both libv8 and ChakraCore](https://github.com/CauldronDevelopmentLLC/cbang/tree/master/src/cbang/js).  However, I cannot get ChakraCore to link properly on Windows 10 so I've had to abandoned ChakraCore support.  We are using JavaScript for producing tool paths for CNC machines and as you know desktop manufacturing is a big deal these days.

If Microsoft is expanding support for Open-Source then I think CAMotics would be a good fit.  Does Microsoft contribute to Open-Source?  Would it be possible to get some help maintaining the Windows port of CAMotics?

CC: @obastemur, @jianchun, @dilijev

**Comment by digitalinfinity** [comment]
Hi @jcoffland - Sorry to hear you had issues linking with ChakraCore on Windows 10- can you link to an issue on your repo tracking this? Folks here can certainly give suggestions or hints (or maybe even a PR) to help you get past your problem- however, if you're asking us to maintain the port ourselves, I'm sorry, I don't think we will be able to do that. Thanks again for trying ChakraCore out, and hopefully we can help you get your project working with it again!

**Comment by jcoffland** [comment]
@digitalinfinity, Thank you for the response.  I am asking for a more substantial commitment.  I know Microsoft is trying to expand its Open-Source presence.  Aren't there company programs where Microsoft gets more directly involved in particular Open-Source projects?

**Comment by digitalinfinity** [comment]
Hi @jcoffland - can you be more specific? What exactly do you envision in such a commitment?

**Comment by jcoffland** [comment]
Assuming there is interest, I would like to see direct participation in the development of the project.  Our [CNC control language](http://tplang.org/), which replaces the archaic [GCode](http://wikipedia.org/wiki/GCode) used by most CNC machines and 3D printers, would be of particular interest to ChakraCore.  It is a system for producing tool paths and performing [CAM](https://en.wikipedia.org/wiki/Computer-aided_manufacturing) operations from within Javascript.  It's a great example of ChakraCore usage that's not a browser or node.js.

**Comment by digitalinfinity** [comment]
Thanks @jcoffland. Microsoft does not have a general policy around contributing to open source projects. We do contribute to many different open source projects as they relate to the needs of our product teams. In this case, while we're happy to help you with specific issues you may have with ChakraCore, I don't see us directly participating in the development of your project. This is not a statement of interest or validity of your project, just an alignment to our business goals.

**Comment by jcoffland** [comment]
Ok, thanks.  Keep us in mind if you hear anything internally about Open-Source and Maker community outreach.  Per your earlier suggestion, I've created an issue in our repo for the ChakraCore problem I'm having in Windows 10.  https://github.com/CauldronDevelopmentLLC/CAMotics/issues/248  A PR would be appreciated.

**Comment by digitalinfinity** [comment]
Will do! Thanks for opening the issue in your repo, @jcoffland - I'll close the ChakraCore issue for now.
