### ISSUE TITLE
Intl: Number.tolocalestring output difference among platforms.

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#3595]
```
999.9996.toLocaleString().
 
*nix: 1,000
Windows: 1,000.00
```

- Investigate the difference (per sample and other potential FP numbers)

**Comment by dilijev** [comment]
This is known. It seems we use the user's settings from the environment to determine how to format. Unclear whether this should be considered a bug or reasonable behavior given the design of reading the user's settings for formatting in the default locale.

**Comment by obastemur** [comment]
> This is known. 

Do we have an open issue?

**Comment by dilijev** [comment]
There was an email thread but since it wasn't clear there was an actual issue besides a need to investigate, this is the first issue.

**Comment by dilijev** [comment]
Tracking this issue as part of #3364

**Comment by obastemur** [comment]
@dilijev I would like to keep this issue open and track it separate from other Intl issues. See my 'investigate..' notes on the description and email thread we had.

**Comment by dilijev** [comment]
@obastemur Sounds good.

**Comment by obastemur** [comment]
I took a look at this. The difference has nothing to do with xplat / Windows fp differences. It actually comes from Windows formatting hence no further investigation is needed for now. Having this issue on the Github history should be enough to recall the notes.
