### ISSUE TITLE
[1.7] daily_slow_x64_test failures in WASM tests

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3597]
```
14:52:07 4>Summary: wasm had 39 tests; 3 failures
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --start 4 --end 12 -endargs) exe) -- failed : exec time=4
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --end 4 -endargs) exe) -- failed : exec time=7
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --start 12 -endargs) exe) -- failed : exec time=54
```

Changes resulting in first occurrence of failure:
https://ci2.dot.net/job/Microsoft_ChakraCore/job/release_1.7/job/daily_slow_x64_test/37/changes

Started failing on 8/21

**Comment by Cellule** [comment]
Bug caused by change in the Wasm spec test harness.
Fix submitted at https://github.com/WebAssembly/spec/pull/552
Will apply the fix in our copy now to unblock our tests
