### ISSUE TITLE
JsGetProperty() doesn't work with object-coercibles

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3599]
In JavaScript, it's legal to do:
```js
var num = 812;
console.log(num.foo);  // undefined
console.log(num.toString());  // 812
```

This works because numbers are object coercible even though they are not real objects.  However, doing equivalent property reads with `JsGetProperty()` will return `JsErrorArgumentNotObject` without modifying the ref pointer passed in.  This actually caused a segfault for me because I assumed GetProperty would work for all object-coercibles but it turns out it doesn't.

Could this behavior be changed?

**Comment by obastemur** [comment]
I'm +1 on making this change. We might update the ref with 'undefined' similar to JS land.

Objections?

**Comment by liminzhu** [comment]
It does sound reasonable. We do this pretty much for all property-related APIs and APIs that mirror Object.xxx in JS (see all of them by searching `VALIDATE_INCOMING_OBJECT` in [jsrt.cpp](https://github.com/Microsoft/ChakraCore/blob/94db02055fb591e93d93bdfcac1628d9311b5bee/lib/Jsrt/Jsrt.cpp)). I wonder what our reason was when originally designing the APIs (maybe we were trying to be stricter in the native land) @curtisman  @akroshg ? If we were to change the behavior of JsGetProperty, we should change all of those APIs to be consistent.

Another thing that concerns me obviously is whether people could be relying on this semantics.

**Comment by fatcerberus** [comment]
Thinking about this some more, the current behavior makes sense in that there are no side effects by default, which is ideal when reading properties during debug processing.  Although there *could* still be side effects if the target object is a Proxy object...

**Comment by fatcerberus** [comment]
Update on the above: I actually ran into an issue while testing out the debug API where calling JsConvertToObject() caused JS execution to resume unexpectedly.  So I rescind my feature request, the current behavior makes more sense. :)
