### ISSUE TITLE
Class name in extends clause should be ReferenceError

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#36]
Adapted from test262
https://github.com/tc39/test262/blob/master/test/language/statements/class/name-binding/in-extends-expression-assigned.js

```
var x = (class x extends x {}); // expected: ReferenceError, actual: TypeError
```

The error seen looks like the following:

```
TypeError: Function is not a constructor
        at Global code (E:\dev\debugging\class\repro.js:1:1)
```

Details about the expected behavior can be found in [ECMAScript 2015 14.5.14](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-classdefinitionevaluation).

**UPDATE:** See [ES 2016 14.5.14](https://tc39.github.io/ecma262/2016/#sec-runtime-semantics-classdefinitionevaluation) and [ES 2017 14.5.13](https://tc39.github.io/ecma262/#sec-runtime-semantics-bindingclassdeclarationevaluation).

There is a scoping issue with the extends clause that is causing x to appear to be of an invalid type, rather than causing an error because of the attempt to reference the type which is being defined.

The following should also produce a `ReferenceError` when `eval("x")` is evaluated as the `extends` clause.

```
var x = (class x extends eval("x") {}); // expected: ReferenceError, actual: TypeError
```

See bug [4310932](https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=4310932)

**Comment by ianwjhalliday** [comment]
@dilijev I can help you with this Tuesday next week

**Comment by dilijev** [comment]
@ianwjhalliday Thanks, sounds good.
