### ISSUE TITLE
Add Issue and PR GitHub Templates

### ISSUE THREAD

**Issue by tcare** [Microsoft/ChakraCore#360]
GitHub now supports issue and PR templates: https://github.com/blog/2111-issue-and-pull-request-templates

Do we want to set some of these up? What would we want to put in them?

@abchatra

**Comment by dilijev** [comment]
Eh, it's extra overhead for anyone opening a pull request to think about, but on the other hand it will 'push' the most important point of CONTRIBUTING.md rather than requiring the user to 'pull' that info by checking out the file on their own.

I'm ambivalent.

**Comment by bterlson** [comment]
I say no, not until we have an actual problem that these features address. It's not worth the overhead (and I'm skeptical whether we'd ever settle on one PR and one issue template to rule them all).

**Comment by tcare** [comment]
Fine by me. We have the option at least :)
