### ISSUE TITLE
Finalizers on shutdown catch-22

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3601]
I would like all my native finalizers to run on shutdown, to free any non-memory resources they may be holding onto.  However my finalizers rely on being able to call back into JSRT to get the external data pointer from the object being finalized, and this fails with JsErrorNoCurrentContext as I've already set the context to JS_INVALID_REFERENCE.

This is a catch-22: `JsDisposeRuntime()` will fail and not run finalizers if I don't clear the current context first, however clearing the current context prevents the finalizers from accessing the external data pointer.

Is there a way to force immediate finalization of all objects?

**Comment by liminzhu** [comment]
The [JsFinalizeCallback](https://github.com/Microsoft/ChakraCore/wiki/JsFinalizeCallback) which is passed in for `JsCreateExternalObject` has a in-param for the external data pointer. Something like this would work.

```cpp
void CALLBACK finalizer(void* data)
{
       printf((char*) data); // LOL
       // do something to data
}

// somewhere else in code
JsValueRef v;
char* c = "LOL";
JsCreateExternalObject(c, finalizer, &v);
JsSetCurrentContext(JS_INVALID_REFERENCE);
JsDisposeRuntime(runtime);
```

**Comment by fatcerberus** [comment]
Thanks.  In my abstraction I currently use the same function signature for both native calls and finalizers but it'd be easy enough to change it so the pointer is passed into the finalizer directly.  I don't have any need to access the object being finalized other than for its host pointer, so this works out perfectly.

Thanks for the tip! 😺
