### ISSUE TITLE
TypedArray constructors should fail when the object argument contains an element not convertible to Number

### ISSUE THREAD

**Issue by goyakin** [Microsoft/ChakraCore#361]
[Test262 PR](https://github.com/tc39/test262/pull/509)

**Comment by dilijev** [comment]
@bterlson: is this still valid? Looks like @goyakin's test262 case isn't there anymore. /cc @MSLaguana

**Comment by dilijev** [comment]
test/built-ins/TypedArrays/object-arg-throws-setting-typedarray-property.js was removed in tc39/test262@1517615a2

**Comment by dilijev** [comment]
Removal of that test implies that that case should not throw. Verified with eshost:

```
>eshost -its -e "new Uint16Array([8, new Int8Array(1)])"
## Source
print(new Uint16Array([8, new Int8Array(1)]))

┌────────────┬──────────────────────┐
│ ch-1.4.4   │ 8,0                  │
│ d8         │                      │
│ ch-1.3.2   │                      │
│ sm         │                      │
│ ch-1.2.3   │                      │
│ ch-master  │                      │
│ ch-dev-rel │                      │
│ ch-1.5.0   │                      │
│ jsc        │                      │
│ ch-dev-dbg │                      │
├────────────┼──────────────────────┤
│ node-ch    │ Uint16Array [ 8, 0 ] │
│ node       │                      │
└────────────┴──────────────────────┘
```

**Comment by dilijev** [comment]
See https://tc39.github.io/ecma262/#sec-typedarray-object

**Comment by dilijev** [comment]
Talked with @MSLaguana and it looks like this is no longer a bug due to a spec change.

@bterlson can you confirm and reopen this bug if this is not the case?

**Comment by bterlson** [comment]
@dilijev agreed
