### ISSUE TITLE
JsStringToPointer() returns wchar_t but always encodes as UTF-16

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3622]
`JsStringToPointer` gets a pointer to a UTF-16 encoded string.  The pointer is specified in the function signature as `wchar_t*`, however `sizeof(wchar_t)` is 4 bytes on Unix platforms (Linux, macOS), in contrast to Windows where it's 2 bytes; this caused a segmentation fault on my end when I tried to walk the string through a `wchar_t` pointer.

If the function returns UTF-16 on all platforms, the signature should be changed to `uint16_t*` to prevent mishaps.

**Comment by jianchun** [comment]
That API is Windows only for backward compat. It is unavailable on Unix platforms (unavailable from ChakraCore.h). It is replaced with newer String APIs: JsCopyString/JsCopyStringUtf16.

**Comment by fatcerberus** [comment]
That explains the implicit declaration warnings from GCC.  I don't remember seeing that fact documented anywhere though?

**Comment by jianchun** [comment]
We had some effort but might not easily seen: https://github.com/Microsoft/ChakraCore/wiki/JsStringToPointer

**Comment by fatcerberus** [comment]
It's kind of inconvenient that I won't be able to get a pointer tied to the lifetime of the original string anymore, but I can easily adapt my code to use `JsCopyString()`.  That function is documented as experimental; does it exist in 1.7.1?

**Comment by fatcerberus** [comment]
I'll close since nothing needs to be fixed (other than my own code :)

**Comment by digitalinfinity** [comment]
Yup, JsCopyString is available in 1.7.1 (IIRC it was introduced in 1.5 but my memory is hazy 😄)
