### ISSUE TITLE
API to make a PropertyId directly from a JavaScript string

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3623]
Currently to create a property ID from a string passed in from JS, I have to do:
```c
JsCopyString(key_ref, key_string, ...);
JsCreatePropertyId(key_string, key_length, &prop_id);
```

`JsGetPropertyIdFromSymbol()` takes a JsValueRef as argument, but that only works for symbols.

**Comment by liminzhu** [comment]
Thanks for the feedback @fatcerberus . I am curious why you're creating propertyId from JS strings? Usually hosts know exactly what property they look for and create propertyId from a native string.

**Comment by fatcerberus** [comment]
My use case is admittedly off the beaten path.  My application, miniSphere, a JavaScript game engine, was originally based on Duktape.  Duktape has a stack-based API like Lua, and in order to avoid rewriting The entire engine when migrating to Chakra, I recreated the Duktape API.

In particular, my `jsal_get_prop()` function involves pushing a string onto the stack specifying the property to read.  Pushing something onto the stack means creating a JsValueRef from it, so by the time the property read happens, all I have access to is the value ref:
https://github.com/fatcerberus/minisphere/blob/chakra-js/src/shared/jsal.c#L557-L573

**Comment by liminzhu** [comment]
Thanks for sharing @fatcerberus . I think this is an API we could consider. Another use case can be when someone wants to iterate an object's properties natively and calls `JsGetOwnPropertyNames`, which returns a JsValueRef that contains an array of js strings. However, as you pointed out, there's a fairly easy workaround helper you can write to achieve the same goal, so I doubt this is something we'd immediately do unless there's more demand and a potential perf gain. Does that sound fair to you?

**Comment by fatcerberus** [comment]
Fair enough.  The main reason using the helper bothered me is that I'm copying a string seemingly unnecessarily when the JS engine could easily reuse the one it already has in its string table.  Admittedly I don't know what really goes on under the hood when creating a PropertyId though. :)

In reality though, we're talking about very short strings on average so the overhead of copying a string isn't a big deal most likely.

**Comment by liminzhu** [comment]
Yep this is essentially what I'm thinking when I say perf gain. If there's a scenario where the behavior you mentioned happens too often and/or simply costs too much, then it adds more weight to make a change now.

**Comment by fatcerberus** [comment]
@liminzhu Regarding that perf gain...

We noticed a huge performance regression in miniSphere's API across the board after switching from Duktape to ChakraCore.  Many calls became 2-3x slower for no obvious reason.  With some profiling, we tracked down the cause of the regression to excessive use of `JsCopyString`:
http://forums.spheredev.org/index.php/topic,1215.msg10552.html#msg10552

After applying the patch below, performance for us improved 20-25%:
https://github.com/fatcerberus/minisphere/commit/ed565a2f64d9767878e0793d79b995805223ec02

Trouble is, that involves calling `JsStringToPointer` which is deprecated outside of Windows.  Which brings me back to the proposal here... 😉

**Comment by rhuanjl** [comment]
Thought I'd comment on this briefly as I did a lot of the aforementioned profiling.

To run the helper shown above you have to do:
1. Find the length of the string: call JSCopyString with no buffer to get the length back (this does one UTf16->UTF8 conversion
2. Allocate a buffer
3. Call JSCopy String againg (second conversion)
4. Now call JsCreatePropertyId passing it the string  -> this converts UTF8 back to UTF16

Considering that ultimately all you're trying to do is find the value of a string already held in UTF16 format within the engine and pass it to JsGetPropertyIdFromName the above conversions and memory allocations seem very excessive.

I don't know how to submit a pull request - (sorry I'm new to the ways of github and in fact online collaboration in general) - I think the below code would work as this proposed api and from a few tests it takes 10-20% of the execution time that the helper takes.

`CHAKRA_API JSCreatePropertyIDFromJSString(
            _In_ JsValueRef stringValue,
            _Out_ JsPropertyIdRef *propertyId)
{
  const char16* str = nullptr;
  size_t strLength = 0;
  JsErrorCode errorCode = JsStringToPointer(stringValue, &str, &strLength);
  if (errorCode != JsNoError)
  {
    return errorCode;
  }
  return JsGetPropertyIdFromName(str, propertyId);
}`

**Comment by rhuanjl** [comment]
@liminzhu Further to the above I'd be happy to a) learn how to do a pull request and b) submit one

That is, if this API is wanted. I admit the only usage cases I can think of are
a) miniSphere due to the way its internals are built as Fat Cerberus mentioned above and
b) your suggestion of someone wanting to iterate an objects' own properties with JsGetOwnPropertyNames; if anyone's doing that a lot this API is worth providing for performance reasons.

**Comment by liminzhu** [comment]
Thanks for the input @fatcerberus @rhuanjl !

The perf gap between `JsCopyString` and `JsStringToPointer` is concerning to begin with. @obastemur are you aware of this?

**Comment by obastemur** [comment]
> The perf gap between JsCopyString and JsStringToPointer is concerning to begin with. @obastemur are you aware of this?

Nothing surprising here. ChakraCore stores string variables in multibyte format. `JsStringToPointer` simply returns a reference to whatever CC has in memory. No copy, no re-formatting.. nothing..

Well, `JsCopyString` does almost everything... re-format, copy... 

We've been doing some improvements to Jsrt and more to come. Yet, I wouldn't expect the performance of `JsStringToPointer`.

/cc @curtisman @digitalinfinity

**Comment by rhuanjl** [comment]
Does this issue: https://github.com/Microsoft/ChakraCore/issues/3790
replace this one? @obastemur

**Comment by obastemur** [comment]
@rhuanjl yes. Thanks for tagging.
