### ISSUE TITLE
Number() casting precision bug

### ISSUE THREAD

**Issue by sebastienfi** [Microsoft/ChakraCore#3630]
If you run in the console the following command, you will get an incorrect result in Edge.

```javascript
Number("11275408829374972000")
```

The expected result is
```javascript
11275408829374972000
```

But Chakra's out is
```javascript
11275408829374971000
```
On the left side, Chrome console output, right side, Edge's.
![image](https://user-images.githubusercontent.com/5808108/29980886-edc075e0-8f4b-11e7-8268-590ce7dc9452.png)

Please advise.

Ref: https://github.com/gatsbyjs/gatsby/issues/1704

**Comment by digitalinfinity** [comment]
Thanks for reporting- I can reproduce this in ch

**Comment by sigatrev** [comment]
JavaScript numbers are doubles, which have 52 bits of precision. The digit containing the discrepancy in your example is at the limit of that precision. According to section 7.1.12.1 of the spec, the least significant digit of the ToString conversion is not necessarily uniquely determined. While Chakra and V8 disagree on how to print that number to a string, they are both compliant with the spec in this case.

Both agree that
```javascript
Number("11275408829374972000") === Number("11275408829374971000")
```
and if asked to print

```javascript
Number("11275408829374971000")
```
Chrome will print
```javascript
11275408829374972000
```
