### ISSUE TITLE
Out of memory error when running ch in WSL

### ISSUE THREAD

**Issue by xiaoyinl** [Microsoft/ChakraCore#3631]
I was trying to build and run ChakraCore on Windows Subsystem for Linux. The code is from the master branch (2349c5f), built with `./build.sh --debug`. It's built successfully, but when I run `./ch <any js file>`, it immediately aborts with an error "Out of Memory". The call stack shows the problem is in function [X64WriteBarrierCardTableManager::Initialize()](https://github.com/Microsoft/ChakraCore/blob/9f18426ef556fef9273ee55e2b6b5c8e7f57d3be/lib/Common/Memory/RecyclerWriteBarrierManager.cpp#L241) in RecyclerWriteBarrierManager.cpp. At [line 279](https://github.com/Microsoft/ChakraCore/blob/9f18426ef556fef9273ee55e2b6b5c8e7f57d3be/lib/Common/Memory/RecyclerWriteBarrierManager.cpp#L279), `VirtualAlloc` returns nullptr, causing the process to print "Out of Memory" and abort.

My OS is Windows 10 Pro x64 Build 15063. The Linux distribution is Ubuntu 16.04.3 LTS.

**Comment by jianchun** [comment]
This is https://github.com/Microsoft/BashOnWindows/issues/597

**Comment by xiaoyinl** [comment]
Thank you @jianchun! I will try the latest insider preview.
