### ISSUE TITLE
Compile Error with Visual Studio 2017

### ISSUE THREAD

**Issue by Wiladams** [Microsoft/ChakraCore#3641]
A very simple fix, file: RuntimeThreadData.cpp should include "CommonPal.h" to pickup on the THREAD_LOCAL macro.

**Comment by dilijev** [comment]
We're not seeing an issue when we build with VS 2017 on our end.

Can you provide the error message you're seeing and other information about your environment so we can reproduce your failure and confirm we have fixed it?

**Comment by Wiladams** [comment]
This is as vanilla a setup as I can imagine.  And the following is the error message I received.



Severity Code Description Project File Line Suppression State
Error (active) E0020 identifier "THREAD_LOCAL" is undefined ch d:\repos\ChakraCore\bin\ch\RuntimeThreadData.cpp 34



I noticed the top of the file in question "RuntimeThreadData.cpp" only contains: #include "stdafx.h", so I can imagine how it could not pick up on the THREAD_LOCAL macro, as it's defined in the file "CommonPal.h", which obviously is not included.


Perhaps when you build it you use the command line, and it concatenates files?  I'm using the .sln file in the directory.  Everything else builds fine, it's just this one file missing the "CommonPal.h", or something else that might include it.



Setup:

Fairly fresh install of Windows 10: Microsoft Window [Version 10.0.15063]


Fairly fresh install of VS Professional 2017, Version 15.2 (26430.16) Release


Microsoft Visual Studio Professional 2017
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Professional
Visual Basic 2017   00369-60000-00001-AA508
Microsoft Visual Basic 2017
Visual C# 2017   00369-60000-00001-AA508
Microsoft Visual C# 2017
Visual C++ 2017   00369-60000-00001-AA508
Microsoft Visual C++ 2017
Visual F# 4.1   00369-60000-00001-AA508
Microsoft Visual F# 4.1
Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio
ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017
ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio
Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Cookiecutter   3.0.17114.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.
Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events
JavaScript Language Service   2.0
JavaScript Language Service
JavaScript Project System   2.0
JavaScript Project System
JavaScript UWP Project System   2.0
JavaScript UWP Project System
KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info
Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.
Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.
Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio
NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
Python   3.0.17114.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
Python - Django support   3.0.17114.1
Provides templates and integration for the Django web framework.
Python - IronPython support   3.0.17114.1
Provides templates and integration for IronPython-based projects.
Python - Profiling support   3.0.17114.1
Profiling support for Python projects.
SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript   2.2.2.0
TypeScript tools for Visual Studio
Visual C++ for Cross Platform Mobile Development (Android)   15.0.26228.00
Visual C++ for Cross Platform Mobile Development (Android)
Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development
Visual Studio Tools for Apache Cordova   15.113.6201.1
Visual Studio Tools for Apache Cordova
Visual Studio tools for CMake   1.0
Visual Studio tools for CMake
Visual Studio Tools for Unity   3.1.0.0
Visual Studio Tools for Unity
Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.



=============================== - Shaping clay is easier than digging it out of the ground.


________________________________

**Comment by Cellule** [comment]
CommonPal.h is used only in non-windows build.
The place where this is defined is in `lib\Common\CommonDefines.h` near the end.
`#define THREAD_LOCAL thread_local`

Can you try replacing `THREAD_LOCAL` with `thread_local` in `RuntimeThreadData.cpp` ?

**Comment by Wiladams** [comment]
Although I can change the code, I don't want to.  I want to be able to use whatever comes stock from the repot without having to change it.


I'm just reporting to you that you have a problem.


I suggest you fix the code if the usage of the macro is no longer what you believe should be used, and then I'll just pick up your changes.


-- William


=============================== - Shaping clay is easier than digging it out of the ground.


________________________________

**Comment by Cellule** [comment]
I am trying to understand why you are having this error to begin with.
As far as I can tell, the current code is as we intended.
The macro is defined in `CommonDefines.h` which is included in `stdafx.h`.

Can you try to build with `/showIncludes` on `RuntimeThreadData.cpp` (see image below) then build?
![image](https://user-images.githubusercontent.com/4157103/30128501-c03d6ce0-92f7-11e7-92fa-5aa35397879b.png)

In the output you should see a lot of output of all the files included by that cpp file. Can you verify if you see something like the following?
```
1>RuntimeThreadData.cpp
1>Note: including file: d:\projects\chakra\core\bin\ch\stdafx.h
1>Note: including file:  D:\projects\Chakra\core\Lib\Common\CommonDefines.h
```

**Comment by Wiladams** [comment]
How about this.  In the ch project, the stdafx.h file has the following.

#ifdef _WIN32
#include <windows.h>
#else
#include <CommonPal.h>
#endif // _WIN32

Which on Windows, will clearly mean the CommonPal.h file will not be included, and the THREAD_LOCAL macro will not get defined.

I'm not sure of the reasoning here, since CommonPal.h has some very Windows specific stuff in it as well.
#ifndef THREAD_LOCAL
#ifndef __APPLE__
#if defined(_MSC_VER) && _MSC_VER <= 1800 // VS2013?
#define THREAD_LOCAL __declspec(thread)
#else // VS2015+, linux Clang etc.
#define THREAD_LOCAL thread_local
#endif // VS2013?
#else // __APPLE__
#ifndef __IOS__
#define THREAD_LOCAL _Thread_local
#else
#define THREAD_LOCAL
#endif
#endif // __APPLE__
#endif // THREAD_LOCAL

It just seems obvious that THREAD_LOCAL is never going to be defined in my case, unless this CommonPal.h file is somehow included.

CommonDefines.h does NOT include CommonPal.h, so that's not going to help in this case.

CommonBasic.h does include CommonPal.h, but, that's not included by stdafx.h, which is the only '.h' file included by RuntimeThreadData.cpp (which is the original file reporting the error), so again, CommonPal.h isn't going to get included, and THREAD_LOCAL will NOT be defined, and that's exactly what the compiler error is indicating.

It's a simple fix.  Either change stdafx.h to always include CommonPal.h, or do something else that ensures THREAD_LOCAL gets defined within RuntimeThreadData.cpp

**Comment by Wiladams** [comment]
Oh yes, and THREAD_LOCAL is NOT defined in CommonDefines.h as you stated, unless you guys have local changes that are not currently reflected in the repo.

**Comment by Cellule** [comment]
I am terribly sorry about the confusion.
I was looking into a different branch that was missing a recent change.
This was introduced in #3553 where the define was moved from CommonDefines.h to CommonPal.h

However, that PR also changed stdafx.h to include `CommonPal.h` unconditionally.
https://github.com/Microsoft/ChakraCore/pull/3553/files#diff-05783da3b8bba4fa92445ddb47da7d51L36

From what you've been telling us, it sounds like you have only part of the change maybe ?
Can you verify that you are on the `master` branch with no local changes?

**Comment by Wiladams** [comment]
git branch 
Says: * master

I have made no other changes.

I will delete the copy, and git clone again (I just did this yesterday).

**Comment by fatcerberus** [comment]
Apparently there was a bad merge:
https://github.com/Microsoft/ChakraCore/commit/a824c652f7aab253af9f309e334b077a2ff432cc

Maybe you happened to clone it before the fix.

**Comment by Wiladams** [comment]
git clone
git branch [* master]
Open .sln file.  stdafx.h now has <CommonPal.h> unconditionally
Everything builds without error now
Thanks.  
Bottom line, my repo did not reflect all changes required to build out of the box.

Tagging releases might be good.  I'll check to see if that's the case.
