### ISSUE TITLE
Incorrect result as UTC+0000  for Date#toLocaleString 

### ISSUE THREAD

**Issue by mackva** [Microsoft/ChakraCore#3649]
`new Date(""2017-09-06T05:30:01.735"").toLocaleString();`

result in the Edge 20: "‎2017‎年‎9‎月‎6‎日‎ ‎5‎:‎30‎:‎01"  for JP local  - incorrect 
result in the Google Chrome 55 + IE 11: "‎2017/9/5 21:30:01"  for JP local  - correct

**Comment by dilijev** [comment]
If we're looking at the formatting, I agree that they are different, but not whether one is correct while the other is not. AFAIK, the Edge rendering is a correct rendering of date and time in Japan. The format with slashes is slightly more suspect but I imagine could also be correct. The differences in formats are in the i18n library (WinGlob versus ICU).

If we're talking about taking a date string without a timezone and rendering it in another timezone, that depends on whether the default timezone for the string should be local time or UTC, and (if the former) which default timezone your machine is in.

Could you clarify those points?

**Comment by dilijev** [comment]
Here's a relevant spec dive:

https://tc39.github.io/ecma262/#sec-date-value 4.b.ii.1.

> Let tv be the result of parsing v as a date, in exactly the same manner as for the parse method (20.3.3.2). If the parse resulted in an abrupt completion, tv is the Completion Record.

https://tc39.github.io/ecma262/#sec-date.parse 

> [...] parse interprets the resulting String as a date and time [...]. The String may be interpreted as a local time, a UTC time, or a time in some other time zone, depending on the contents of the String.

> The function first attempts to parse the format of the String according to the rules (including extended years) called out in Date Time String Format (20.3.1.16). If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats. 

https://tc39.github.io/ecma262/#sec-date-time-string-format

> When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as a local time.

In the example above, the timezone is absent, and it is a date-time form. Therefore, the string should be interpreted as being in local time.

------

Here's an example showing the output of all the various engines' console hosts (removing BiDi characters to normalize formatting):

```
## Source
print(new Date('2017-09-06T05:30:01.735Z').toLocaleString('en-us').replace(/[^a-z0-9:/ ]/ig, '')); // UTC
print(new Date('2017-09-06T05:30:01.735').toLocaleString('en-us').replace(/[^a-z0-9:/ ]/ig, '')); // local

┌──────────────────┬──────────────────────┐
│ ch-1.7.1         │ 9/5/2017 10:30:01 PM │
│ ch-master-latest │ 9/6/2017 5:30:01 AM  │
│ d8               │                      │
│ node             │                      │
│ node-ch          │                      │
│ sm               │                      │
└──────────────────┴──────────────────────┘
```

Chrome 60:

![image](https://user-images.githubusercontent.com/494055/30103899-e2acc158-92a8-11e7-9210-03b10a4908fd.png)

Edge 40.15063:

![image](https://user-images.githubusercontent.com/494055/30103923-f910b2b0-92a8-11e7-8540-9d5eab1bc19f.png)

It looks to me like everyone agrees. I'm not quite sure I understand what caused the inconsistent behavior you're seeing. For one thing, it looks like your versions of Chrome and Edge are both fairly out of date. It could be that they were inconsistent at that time. It looks like JavaScriptCore (Apple/Safari) from the beginning of this year treated both cases as UTC (printing 10PM for both), but I can't confirm whether that has been corrected.

**Comment by mackva** [comment]
>When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as a local time.

Thanks for the help.
