### ISSUE TITLE
(1d,P2) Intl-ICU: platform.resolveLocaleLookup

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3673]
* [x] Fallback logic
* [ ] Implement with ICU

**Comment by dilijev** [comment]
@jackhorton is this one?

**Comment by jackhorton** [comment]
Yep, not marked as done yet because Collator isn't in master.

**Comment by dilijev** [comment]
I think we can close things where the work is finished regardless of whether it landed in master.
