### ISSUE TITLE
Breakpoints can't be set in an ES module

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3701]
`JsDiagSetBreakpoint()` when called on a ES module returns JsErrorDiagUnableToPerformAction and the breakpoint is not honored.  Debugging ES modules seems to work otherwise, but I can't set breakpoints in them 😭

**Comment by agarwal-sandeep** [comment]
@fatcerberus can you provide a repro? It seems to be working in ch implemented debugger.
@boingoing FYI and to take a look once we have a repro.

**Comment by fatcerberus** [comment]
I'll try to reproduce it in isolation.  My module harness is pretty complicated because I support Babel-style interop with CJS so maybe something is going wrong on my end but I don't think so.  I can successfully set breakpoints in global code and require'd scripts but not in ES modules.

**Comment by fatcerberus** [comment]
False alarm, I was tracking script IDs improperly.  Chakra doesn't correctly track filenames for ES modules (see #3618) so I had to do it myself, and it seems I forgot to increment the script ID counter for the root module.
