### ISSUE TITLE
Segmentation fault inside OP_GetElementI

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#3715]
Getting segmentation fault when running `npm prune` on `body-parser` module. 
Ref: https://github.com/expressjs/body-parser/pull/233#issuecomment-328359075 

Debugged this a bit and noticed something wrong inside `OP_GetElementI()`.

![image](https://user-images.githubusercontent.com/12488060/30350884-838230bc-97cd-11e7-9c7f-9650b4326166.png)

Repro steps:
1. clone `body-parser`
2.  `npm install`
3. `npm prune`

**Comment by kunalspathak** [comment]
Works well on windows.

**Comment by Penguinwizzard** [comment]
Crash no longer repros (build issues prevent precise determination of fix).
