### ISSUE TITLE
Follow-up #2751: For Number#toString with a radix other than 10, never switch to exponential display

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3739]
Follow-up to #2751 (PR #3635)

Compatibility: align with other engines' implementation here.

See @littledan's comment https://github.com/Microsoft/ChakraCore/issues/2751#issuecomment-326902301

/cc @xiaoyinl @littledan @bterlson

**Comment by xiaoyinl** [comment]
I'd like to work on this issue.

**Comment by dilijev** [comment]
@xiaoyinl thanks!
