### ISSUE TITLE
Incorrect results for [[Get]] and [[HasProperty]] with Typed Array in prototype

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#374]
There was previously an inconsistency between [[Get]]/[[Set]] and [[HasProperty]] as noted in https://github.com/tc39/ecma262/issues/347. However, we did not comply with the old semantics either (our [[HasProperty]] seemed to be guarded on the receiver as well). The new semantics remove all the receiver checks.

``` js
var o = {__proto__: new Int32Array(100)};
Object.prototype[1.3] = 100;
print(o[1.3]);
print(Reflect.has(o, '1.3'));
```

Expected: undefined/false (same as v8)
Actual: 100/true (same as sm)

**Comment by abchatra** [comment]
@dilijev Any update on this issue?

**Comment by dilijev** [comment]
Investigating and trying to understand the issue and solution. I hope to have this completed today.

**Comment by dilijev** [comment]
Got distracted working on #660. Focusing on this bug today.

**Comment by dilijev** [comment]
cf. 9.4.5.2 https://tc39.github.io/ecma262/2016/#sec-integer-indexed-exotic-objects-hasproperty-p
cf. 9.4.5.4 https://tc39.github.io/ecma262/2016/#sec-integer-indexed-exotic-objects-get-p-receiver

**Comment by dilijev** [comment]
Relevant methods to refer to:

```cpp
Var JavascriptReflect::EntryHas(...);
BOOL JavascriptOperators::OP_HasItem(...);
BOOL TypedArrayBase::GetProperty(...);
BOOL TypedArrayBase::HasProperty(...);
```

**Comment by dilijev** [comment]
Complex prototype chain has no impact on this bug. Reduced repro:

```js
var o = new Int32Array(10);
Object.prototype[1.3] = 100;
console.log(o[1.3]);
console.log(Reflect.has(o, '1.3'));
```

**Comment by dilijev** [comment]
After discussing with @ianwjhalliday offline, it seems our implementation differs from the spec in such a way that this would require a somewhat large change to properly implement [[HasProperty]] for Typed Arrays that is inappropriate for the 1.2 milestone.

I'm looking into fixing [[Get]] which seems more straightforward.

**Comment by dilijev** [comment]
Starting work on this as a priority starting today.

**Comment by dilijev** [comment]
@bterlson Maybe we're reading the spec incorrectly but @curtisman and I were going through the spec and it seems to us that for the original test case you included in the issue description (where the TypedArray is in the prototype chain), should actually continue walking the prototype chain and SHOULD result in `100/true`, whereas the case I posted later (calling get/has on the TypedArray directly) should result in `undefined/false`.

I'm working on pulling the various references from the spec and our interpretation for these cases. I'll post a followup comment shortly.

/cc @ianwjhalliday

**Comment by dilijev** [comment]
@bterlson @ianwjhalliday - ignore previous comment. A closer look showed that we were mistaken (cc @curtisman @Yongqu).

Fix in progress.

**Comment by dilijev** [comment]
The needed fix is understood but would be a perf regression in Chakra. We will put the fix on hold until we can confirm whether this is really the desired behavior. @bterlson @curtisman

**Comment by bterlson** [comment]
The original bug's expected behavior is indeed what is expected.
