### ISSUE TITLE
Construct with new keyword

### ISSUE THREAD

**Issue by beetfarmer** [Microsoft/ChakraCore#3761]
How do I put a function on a constructed object and tie my internal object to the instance?  The code

```
var client = new client();
client.get("value");
```

I am able to get the first line to call a native function as a ctor call with the code..
```
JsPropertyIdRef clientId;
JsGetPropertyIdFromName(L"client", &clientId);
JsValueRef clientCtor;
JsCreateFunction(Client, nullptr, &clientctor);
JsSetProperty(globalObject, clientId, clientctor, true);
```
I want to have a function on the object (get) that can call to native, but I can't figure how.  I suppose I need to associate a pointer to the instance and define a call back that is assigned to client.  I've tried a number of ways but cannot figure out.

**Comment by liminzhu** [comment]
Thanks for opening the issue @beetfarmer ! 

Do you want to define a native function on a class of objects or a specific instance? If latter, you have the right idea to grab the JsValueRef of the instance and set the native function as a property. If former, you need to set the native function as a property of the prototype. As an [example](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L515), you can check out how I project a native ctor called JsPoint with its member functions to JS. 

[projectNativeClass](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L480)
[JSPointConstructor](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L270)
[JSPointPrototype](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L175)

**Comment by beetfarmer** [comment]
@liminzhu Thanks - It's for an instance.  The example using the JsSetPrototype did the trick.

**Comment by beetfarmer** [comment]
@liminzhu Thanks - It's for an instance.  The example using the JsSetPrototype did the trick.
