### ISSUE TITLE
API to get value of `new.target` in native function

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3762]
It's not currently possible, as far as I can tell, to make a constructor that creates an external object without returning the object directly (i.e. you can't use the default `this`), this leaves me to create the object and then manually set its prototype to `new.target.prototype` in order to support subclassing.  However, that doesn't seem to be possible to do in a JsNativeFunction.

Is there an API to get the value of `new.target`?  If not, I would like to propose such an API.

**Comment by akroshg** [comment]
@liminzhu, did we consider this before?

**Comment by fatcerberus** [comment]
In the absence of this proposed API, for my use case I wonder if it would be possible to fetch the correct prototype from `this.__proto__`.  I'm not familiar enough with ES6 class semantics to know if that would work.

**Comment by simply-jos** [comment]
You're trying to subclass a "native" class with an ES class?

The "this" object of a native constructor is the constructor of the derived type. If you check if "arguments[0]" has its "prototype" property set, then you know that its extending something.

When you return the object from the constructor, if that property is set, you need to set the prototype of your return value to that instead of the native class's prototype.

some psuedocode:

```
thisProto = nullptr;
if arguments[0].HasProperty("prototype"):
  thisProto = arguments[0].GetProperty("prototype")
else
  thisProto = NativeClassPrototype

JsSetPrototype(nativeConstructorReturnValue, thisProto);
```

Make sure you set the "prototype" property of your native constructor to your class's prototype.
Make sure you call "super" in the derived's constructor.

The prototype property should really always exist, since you set it explicitly on your native constructor, but I guess it makes sense to check if it doesn't anyway :)

**Comment by simply-jos** [comment]
for the record i believe this is semantically incorrect as far as JS goes, but it's just how ChakraCore calls native ctors

**Comment by fatcerberus** [comment]
Right, my issue is that I want to make my native constructors *subclassable*, but if I just return an instance of the native type (as I do now) then `new Derived() instance Base` is false and nothing is inherited.  In order for subclassing to work, the native constructor has to dynamically know what the derived class prototype is (or the value of `new.target`), hence why I thought of pulling it from `this.__proto__` in the absence of new.target.

**Comment by simply-jos** [comment]
Yes, my proposed solution solves that.

**Comment by fatcerberus** [comment]
Wait, `this` for a subclassed constructor is the derived class?  That doesn't seem right... I thought `this` was always the instance being constructed?

**Comment by simply-jos** [comment]
Yeah, that's how it behaves. Like I said, I agree it's semantically wonky.

It would be nice if all this stuff was explicitly passed in as arguments to the callback, and the "this" object was what the user would expect it to be.

**Comment by fatcerberus** [comment]
@simply-jos Thanks, you're right about the behavior.  I'm glad someone pointed this out to me; it's not documented anywhere that I can tell, and means that native functions can't actually safely use their `this` binding at all since if it's a `super` call they will end up modifying the derived class constructor instead of the object they're constructing.  That's a pretty big footgun! :footprints::gun:

**Comment by liminzhu** [comment]
@fatcerberus apology for being late to the party. Are you trying to make sure you can extend your native constructor from JS? You'd need to properly set the prototype on the returned external object. Here's an example for the Point class:

https://github.com/Microsoft/Chakra-Samples/blob/f35815c03d601a7bd7e2e306549124540d6d9038/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L515

https://github.com/Microsoft/Chakra-Samples/blob/f35815c03d601a7bd7e2e306549124540d6d9038/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L493

https://github.com/Microsoft/Chakra-Samples/blob/f35815c03d601a7bd7e2e306549124540d6d9038/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L280

**Comment by fatcerberus** [comment]
> Are you trying to make sure you can extend your native constructor from JS? You'd need to properly set the prototype on the returned external object. 

Yes, I figured it out.  The piece of the puzzle I was missing was that I didn’t know how to get the value of `new.target` so I could find the correct prototype to set.  I didn’t realize that for a constructor call argv[0] was the value of `new.target` rather than `this` (although I suspect that behavior may be the cause of #3708).

**Comment by akroshg** [comment]
@digitalinfinity for fyi
