### ISSUE TITLE
(1d,P3) Intl-ICU: Collect test262 conformance numbers in various configs

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3764]
Configurations for example and as-applies:

WinGlob / ICU
Windows / Linux / (optionally OSX if there's a reason to believe it's different)
ChakraCore / Node-ChakraCore

See https://github.com/bterlson/test262-harness

/cc @jackhorton @digitalinfinity 

Note: waiting on completion of the majority of the [milestone 1.7 Intl-ICU tasks](https://github.com/Microsoft/ChakraCore/issues?q=is%3Aopen+is%3Aissue+label%3AIntl-ICU+milestone%3A1.7)

**Comment by dilijev** [comment]
Work is merged, now's a good time to collect some numbers.

**Comment by dilijev** [comment]
Increased estimate to 1d because of need to build and test mutliple configs across potentially multiple products (chakracore, node-chakracore)

**Comment by jackhorton** [comment]
As of #4645:
* ChakraCore-ICU: 70% in 12 seconds (this time is much lower than I have gotten in past runs, so I need to investigate that more).
* ChakraCore-WinGlob (1.8.1): 64% in 16 seconds
* V8 (6.6): 94% in 16.3 seconds
* SpiderMonkey (59): 97% in 18.1 seconds

**Comment by dilijev** [comment]
> this time is much lower

as in faster than expected?

**Comment by jackhorton** [comment]
Yeah -- in my initial runs, CC-ICU was _substantially_ slower than CC-WinGlob, so I need to figure out whats going on there.
