### ISSUE TITLE
Error thrown access new.target

### ISSUE THREAD

**Issue by nzakas** [Microsoft/ChakraCore#378]
I'm not sure if this is the correct place to file this issue, so please feel free to redirect me.

I'm using Microsoft Edge 25.10586.0.0, EdgeHTML 13.10586.

This is the code I'm running in the console:

```js
function Person(name) {
    console.log(new.target);
}

var person = new Person();
```

The console then reports a thrown error and outputs:

```
'<_lexicalNewTargetSymbol>' is undefined
```

I expected that it would output the function. It seems like this has been somewhat implemented due to the content of that error message, but perhaps not completely?

**Comment by bterlson** [comment]
You've come to the right place! This code sample does work fine in ch.exe, so likely it was fixed and will be available in insider builds soon. Will try to nail this down further for you.

Thanks!!

**Comment by abchatra** [comment]
@suwc  can you verify this is fixed and close the issue?

**Comment by suwc** [comment]
Yes, this has been fixed in our current ChakraCore master branch and should be included in the next release.
