### ISSUE TITLE
NuGet packages for MSVC 2017, XP toolchain

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3786]
Current NuGet release is only for MSVC 2015 `v140` toolchain.  miniSphere builds against `v141_xp` for maximum portability, but this prevents me from using the CC NuGet package and forces me to commit the ChakraCore binaries, which are quite large.  This is unwieldy and makes upgrading to new ChakraCore releases painful.

Are there any plans to support MSVC toolchains other than `v140` in NuGet?

**Comment by digitalinfinity** [comment]
Hi @fatcerberus, sorry, this slipped through my radar. We don't have any plans to support different MSVC toolchains but I think in this case, we'd certainly accept a PR. @MSLaguana we just need to introduce a new nuspec + targets file in Build\NuGet, yes?

**Comment by fatcerberus** [comment]
I think there should at least be support for v141 (MSVC 2017), since that’s the current version and the VC2015 tools aren’t installed by default.  It’s a bit weird not to have a NuGet package for it.

I understand if there’s no planned support for the XP toolchains but not having official support for the normal VC2017 toolset strikes me as odd.

**Comment by MSLaguana** [comment]
@dilijev might know more, I've not actually looked into the mechanics of how the nuget packages are produced. I don't see much specific in the package about v140 though; All the dlls and libs are copied from the build output (`VcBuild\bin\<platform>_release\`) to a folder that mentions v140 (`lib\native\v140\<platform>\release\`). That suggests to me that if any changes are required to support v141, they will need to be made in our build process, not just the nuget definition.

**Comment by dilijev** [comment]
I think the binaries should work, but the package has some metadata saying which MSVC toolchain it targets. v140 was the toolchain at the time we set it up. We can augment the package to be able to target others as well.

I know that we have issues building chakracore if we don't have the right windows toolkit versions installed but I don't think that would affect running chakracore.

**Comment by dilijev** [comment]
Update: I was under the impression that the lib/native/v140 subfolder had some nuget magic associated with it to handle the vc140 framework specifically, but now that we're investigating it looks like we might not have the full picture.

**Comment by dilijev** [comment]
Re discussion in #4552 -- we're not saying no, we're just saying we need to understand how to do this correctly (i.e. update to support newer toolchains while not breaking compat with older toolchains we support).

When you say it doesn't work, could you show us the error message or log showing it doesn't work so we have more context on this issue?

**Comment by fatcerberus** [comment]
It turns out that ChakraCore's v140 package works fine against v141 as-is, the reason the binaries weren't found at link time in my case has to do with interference from another NuGet package (Allegro), see https://github.com/liballeg/allegro5/issues/881.  Closing this issue.
