### ISSUE TITLE
JSCopyString number of parameters changed Wiki is wrong

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#3787]
The wiki entry: https://github.com/Microsoft/ChakraCore/wiki/JsCopyString states that JSCopyString has 5 parameters.

However this commit which was merged 17 days ago: https://github.com/Microsoft/ChakraCore/commit/f2078fed54fdeca4c3842fbd8d007de2502b06d5
Changed it to 4 parameters.

I'm not sure if this change was intentional, noting that the parameter change breaks things that depend on JSCopyString, but either way one of the two is now wrong (either the wiki or the codebase) - which one should be updated?

**Comment by obastemur** [comment]
@MSLaguana could you please update wiki?

@rhuanjl Thanks for reporting this.

**Comment by MSLaguana** [comment]
I've updated the wiki to reflect current usage / behavior. Thanks for bringing this to my attention!
