### ISSUE TITLE
What’s needed to make dynamic import work?

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3793]
In miniSphere at present calling `import(...)` makes the engine segfault while static `import` works just fine, which makes me think I’m missing a callback.  What do I need to do for dynamic imports to work?

**Comment by fatcerberus** [comment]
After some digging I figured out that I need to define a FetchImportedModuleFromScript callback.  However, that doesn't solve the problem of `import('module')` from global code, which still causes a segfault.  How do I set a fetch from script callback for global code?  I need a module record to set the callback.

**Comment by akroshg** [comment]
could you share the stacktrace? or what arguments you got?
from the ch.exe I can see that 
```
JsErrorCode WScriptJsrt::FetchImportedModuleFromScript(_In_ JsSourceContext dwReferencingSourceContext,
```
is called when I do 
```
import('module1.js').then(mod => {
    print(mod.bar());
})
```
Eventually FetchImportedModuleHelper will make a call to the JsInitializeModuleRecord.

**Comment by akroshg** [comment]
module1.js
```
export var foo = 10;
export var bar = function() {
    return 'fn bar';
}
```

**Comment by fatcerberus** [comment]
Right, but how does that work for global code which has no module record?  What do I define the callback on?  i.e. What do I pass to JsSetModuleHostInfo?

**Comment by akroshg** [comment]
I think this has native example on how to do that.
[void ModuleSuccessTest(JsRuntimeAttributes attributes, JsRuntimeHandle runtime)
](https://github.com/Microsoft/ChakraCore/blob/master/bin/NativeTests/JsRTApiTest.cpp#L1929
)

**Comment by fatcerberus** [comment]
I don’t have the stack trace handy at the moment, but I can post it later.  I do know that it ends in a call to a null function pointer (0000000000000000 in stack listing), however.

**Comment by fatcerberus** [comment]
@akroshg That code example you showed runs the test code as an ES module.  In my case I need to know how to set the callback to be used when import() is encountered in traditional (non-ESM) code.  That works in ch.exe but I can’t figure out how.

**Comment by akroshg** [comment]
@fatcerberus let me write a sample code and get back to you.

**Comment by akroshg** [comment]
@fatcerberus below code seems to work. Although you still need to lay down channel for **promise** handling as the import(...) will return a promise.
```cpp
    static JsErrorCode CALLBACK FIMC1(_In_ JsModuleRecord referencingModule, _In_ JsValueRef specifier, _Outptr_result_maybenull_ JsModuleRecord* dependentModuleRecord)
    {
        JsModuleRecord moduleRecord = JS_INVALID_REFERENCE;
        LPCWSTR specifierStr;
        size_t length;
        JsErrorCode errorCode = JsStringToPointer(specifier, &specifierStr, &length);
        REQUIRE(errorCode == JsNoError);

        if (wcscmp(specifierStr, _u("foo.js")) == 0)
        {
            errorCode = JsInitializeModuleRecord(referencingModule, specifier, &moduleRecord);
            REQUIRE(errorCode == JsNoError);
            *dependentModuleRecord = moduleRecord;
        }
        return JsNoError;
    }

    static JsErrorCode CALLBACK NMRC1(_In_opt_ JsModuleRecord referencingModule, _In_opt_ JsValueRef exceptionVar)
    {
        // NotifyModuleReadyCallback handling.

        return JsNoError;
    }

    void SomebugTest(JsRuntimeAttributes attributes, JsRuntimeHandle runtime)
    {
        JsModuleRecord rec;
        JsInitializeModuleRecord(nullptr, nullptr, &rec);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_FetchImportedModuleCallback, FIMC1);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_FetchImportedModuleFromScriptCallback, FIMC1);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_NotifyModuleReadyCallback, NMRC1);

        JsValueRef F = JS_INVALID_REFERENCE;
        JsErrorCode err = JsRunScript(_u("import('foo.js').then(mod => { mod.bar(); })"), 0, _u(""), &F);

        CHECK(err == JsNoError);
    }
```

**Comment by fatcerberus** [comment]
Oh, so you pass a `nullptr` as the specifier to get a module record for global code.  I didn’t realize that was legal.

**Comment by fatcerberus** [comment]
Thanks @akroshg!

**Comment by akroshg** [comment]
I am assigning this issue to @liminzhu in order to modify the documentation in order to satisfy dynamic import.

**Comment by liminzhu** [comment]
Since the question is answered, I will close this issue and put the task of documentation on the wiki repo - https://github.com/Microsoft/ChakraCore-wiki/issues/5.
