### ISSUE TITLE
Calling JsInitializeModuleRecord a second time creates a new record

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3798]
According to documentation, JsInitializeModuleRecord() will return the already existing module record if the same normalized specifier is passed in twice.  Parsing source for an already-loaded module will then return an "already parsed" error, which should be enough to ensure only one instance of a module ever gets created.  There were a few cases, however, where I noticed I was loading the same module more than once, so I investigated.

As an experiment, I tried the following:
```c
JsInitializeModuleRecord(NULL, specifier_ref, &module1);
JsInitializeModuleRecord(NULL, specifier_ref, &module2);
```

Both calls succeed, but `module2 != module1`.  Is the documentation incorrect, or is this a bug?

**Comment by akroshg** [comment]
@fatcerberus thanks for reporting this.
I may be wrong but that seems like the host has to confirm what spec says.
According to spec 
https://tc39.github.io/ecma262/#sec-hostresolveimportedmodule

- This  operation must be idempotent if it completes normally. Each time it is called with a specific referencingModule, specifier pair as arguments it must return the same Module Record instance. 

This is what we have in WScriptJsrt::FetchImportedModuleHelper
Could you provide the documentation of JsInitializeModuleRecord() what you have? 

@boingoing has more idea on this.
@liminzhu  for fyi.
Thanks,

**Comment by fatcerberus** [comment]
I was referring to the IntelliSense documentation, specifically this line:
https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L114-L115

I see there’s a note there now which says not to call it twice for the same specifier, which I don’t remember seeing in my copy.  Even so it explicitly states the existing record will be returned in that case, which isn’t the behavior I’m seeing here.

**Comment by akroshg** [comment]
may be documentation error (@liminzhu ? )
But the host (the callback for JsModuleHostInfo_FetchImportedModuleCallback) should sanitize the specifier before calling the JsInitializeModuleRecord.

**Comment by fatcerberus** [comment]
Yes, I already normalize the specifier against my sandboxed file system.  I just didn't think I had to track module records because the documentation seemed to suggest Chakra would do so automatically.  If that's not the case in reality then I can adapt :)

**Comment by liminzhu** [comment]
I dug through the source code a bit. It doesn't not seem like we are returning an existing moduleRecord if `JsInitializeModuleRecord` is called twice on the same parent+specifier. On the second time, we do create a new module record, but we [skip setting the parent/child module dependency on our record](https://github.com/Microsoft/ChakraCore/blob/d2d1fe52d36e2a6134a6548c3d7826afa4eccd49/lib/Runtime/Language/SourceTextModuleRecord.cpp#L687) so the host still shouldn't do that.

I will get rid of `chakra will return an existing ModuleRecord if the specifier was passed in before` on [docs](https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L115).

Where I looked: 
[JsInitializeModuleRecord](https://github.com/Microsoft/ChakraCore/blob/b0e826d669ed300a13a70167bbbcf7b3bf0ba5bf/lib/Jsrt/Core/JsrtCore.cpp#L32)
[SourceTextModuleRecord::SetParent](https://github.com/Microsoft/ChakraCore/blob/d2d1fe52d36e2a6134a6548c3d7826afa4eccd49/lib/Runtime/Language/SourceTextModuleRecord.cpp#L687)

**Comment by fatcerberus** [comment]
For the record I ended up just initializing all my module records as root modules because child modules were glitchy in general.  For example initializing a dynamic import() as a child module never calls the ModuleReady callback so the promise never resolves.  And then there’s #3638...

**Comment by rhuanjl** [comment]
The points being discussed here were fixed some time ago:
1. Revising function to do what the documentation said was considered here - but was not feasible:
https://github.com/Microsoft/ChakraCore/issues/4740
2. Therefore documentation for function was wrong, re-written in https://github.com/Microsoft/ChakraCore/pull/4739/
3. the actual behaviour of the function was slightly problematic corrected in:
https://github.com/Microsoft/ChakraCore/pull/4585/
4. Bug mentioned around dynamic import - was fixed in:
https://github.com/Microsoft/ChakraCore/pull/3934

@fatcerberus

**Comment by fatcerberus** [comment]
As @rhuanjl says above, the current behavior is by-design based on both the existing documentation and the result of the discussion in #4740 so I’ll close this.
