### ISSUE TITLE
Class methods cannot be called static

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/ChakraCore#3816]
Currently it seems to not be possible to name a regular (non static) class method `static`. Edge errors out with `Expected identifier, string or number` so I assume that it gets interpreted as the static keyword instead of the method name.  
I've encountered this problem in Edge 15 and the Edge 16 preview.  

Here's a small reproduction: 

```js
class Foo {
  static() {
    console.log('this does not work in Edge');
  }
}

const foo = new Foo();
foo.static();
```

I am not 100% sure if the name is allowed, but it seems to work in other JavaScript engines

**Comment by akroshg** [comment]
If I read correctly from https://tc39.github.io/ecma262/#sec-class-definitions
```
 static MethodDefinition[?Yield, ?Await]
```
```
MethodDefinition[Yield, Await]:
PropertyName[?Yield, ?Await](UniqueFormalParameters[~Yield, ~Await]){FunctionBody[~Yield, ~Await]}
```

Here the PropertyName does not seem to be optional.

@tcare @bterlson can you take a look?

**Comment by t-sauer** [comment]
@akroshg It is not about an optional name of a static method. It is about a regular (not-static) method, that is called `static`.

**Comment by fatcerberus** [comment]
Looking at the ES spec it seems that `static` is not a reserved word but is treated as one only contextually similar to `yield` and `await`.  So a method named “static” should be legal as it satisfies *PropertyName* in the MethodDefiniton production.

**Comment by akroshg** [comment]
hmm, makes sense to me. I'll let @tcare chime in.
Also to verify that if we have a test262 test cases for this

**Comment by tcare** [comment]
You are correct, this is a spec update we missed. There are also some scattered unit tests that have the wrong definitions of keywords/reserved words after the change, I'll check those out as well.

**Comment by rwjblue** [comment]
Thank you @tcare!
