### ISSUE TITLE
Async-await difference between ChakraCore and v8

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#3827]
The following code behaves differently between Chakra and v8:
```
async function bar() {
    throw new Error("Whoops");
}

async function foo() {
    try {
        await bar();
    } catch (e){
        console.log("Caught ");
    }
}

var oldThen = Promise.prototype.then;
Promise.prototype.then = function(thenx, catchx) {
    console.log(`then: ${thenx}, catch: ${catchx}`)
    oldThen.apply(this, [ thenx, catchx ]);
}

foo()
```

In ChakraCore's case, we see the following output:
```
then: function() {
    [native code]
}, catch: undefined
then: undefined, catch: function() {
    [native code]
}
Caught
```

In v8's case, we see the following output:
```
then: function () { [native code] }, catch: function () { [native code] }
Caught
```

Basically, v8 calls then with resolve and reject in one step, whereas ChakraCore calls it in two (then followed by catch which calls then). It appears that this behavior also trips up zone.js (if you use zone.js with the above snippet, you'll see an unhandled promise rejection in ChakraCore but not in v8).

It's unclear from reading the [spec](https://tc39.github.io/ecma262/#sec-async-functions-abstract-operations-async-function-await) whether there is one mandated approach, but it's worth understanding to see if this is a bug in ChakraCore or Zone.js is just being pedantic in it's expectation of awaited promise resolution.

**Comment by bterlson** [comment]
These should be passed together as per step 10 of https://tc39.github.io/ecma262/#sec-async-functions-abstract-operations-async-function-await (IIUC).
