### ISSUE TITLE
Sometimes loading big diffs causes browser to crash or freeze

### ISSUE THREAD

**Issue by paladox** [Microsoft/ChakraCore#383]
Sometimes loading a big file through Microsoft edge or internet explorer causes the browser to crash or freeze and load the web page slowely.

For an example please see https://gerrit.wikimedia.org/r/#/c/272954/2/zuul/layout.yaml

Also this problem happened in webkit which I hope has been fixed with https://bugs.webkit.org/show_bug.cgi?id=154068

In google chrome the web page is loaded almost instantly without freeze.

It happends on GitHub here to, viewing large diffs causes slowness or crashes.

Works in chrome.

**Comment by MikeHolman** [comment]
This doesn't look like a Chakra issue. Almost 60% of main thread time is spent in DOM handling text replacement:
![image](https://cloud.githubusercontent.com/assets/4925255/13590366/212be9d2-e494-11e5-90be-0f894102f804.png)

Correct location to report Edge bugs is https://connect.microsoft.com/IE.

**Comment by digitalinfinity** [comment]
Bringing to the attention of @digitec so he can chime in if this is known.
