### ISSUE TITLE
Collected exception even after AddRef was done

### ISSUE THREAD

**Issue by angshuman** [Microsoft/ChakraCore#3831]
I have the following pattern of code in JS

```
return new Promise((resolve, reject) => {
            try {
                csharpFunction(text, function (bodyContent) {  
                    if (somthing) {
                     resolve(true);
                    }
                    else {
                        resolve(false);
                    }
                });
            } catch (err) {
                reject(err);
            }
```

In the managed code I am doing AddRef on the callback.

```
private JavaScriptValue CSharpFunction(JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData)
        {
                var queue = (JsQueue)((GCHandle)callbackData).Target;
                queue.Lock.Increment();

                var text = arguments[1].ToString();
                var refCount = arguments[2].AddRef();
                var callback = arguments[2];
                var context = JavaScriptContext.Current;

                var t = Task.Run(async () =>
                {
                    var response = await something();
                    queue.Schedule(new JsFunc(() =>
                    {
                            callback.CallFunction(JavaScriptValue.GlobalObject, luisResponse);
                        
                    }
                });
                return JavaScriptValue.Undefined;
            }
        }
```

While calling CallFunction I am getting the following exception. Please note that **AddRef** is done on 'callback'

Managed Debugging Assistant 'CallbackOnCollectedDelegate'  occurred
  Message=Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'Microsoft.Bots.Runtime!Microsoft.Bots.Hosting.JavaScriptNativeFunction::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'

**Comment by liminzhu** [comment]
Did you pin down `CSharpFunction` ? If not, you can try

```c#
private static JavaScriptValue CSharpFunction(...) {...}
private static readonly JavaScriptNativeFunction CSharpFunctionDelegate = CSharpFunction;
```

**Comment by angshuman** [comment]
Yes, the CSharp function is pinned down to a private JavaScriptNativeFunction. 

That's what is strange. Here I am calling into a function that was defined in JS in Chakra. So why does the exception point to a NativeFunction. I am already inside the native function when calling this callback.

**Comment by angshuman** [comment]
I found the issue. It was caused by calling to another NativeFunction from the callback code. False alarm.
