### ISSUE TITLE
Element.addEventListener('click', null) throws error only when dev tools opened

### ISSUE THREAD

**Issue by valdrinkoshi** [Microsoft/ChakraCore#3863]
On MS Edge 15, `Element.addEventListener('click', null)` or `Element.addEventListener('click', undefined)` will throw the error `Unable to get property 'handleEvent' of undefined or null reference` when the F12 developer tools is opened. 

If the script is run before opening the dev tools, the errors are not logged in the console.

To reproduce, execute this code on Edge 15 ([jsbin here](http://output.jsbin.com/bidusoloku/1/)):
```html
<body>
  <script>
     document.body.addEventListener('click', undefined);
     document.body.addEventListener('click', null);
  </script>
</body>
```

Not sure if this is a ChakraCore bug or Dev Tools bug, ended up filing it both in this repo and [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14063806/), sorry in advance and feel free to close the one in the wrong place :)

**Comment by stevebauman** [comment]
Getting this as well developing locally.

**Comment by Herst** [comment]
A library I used required a workaround for this: https://github.com/Bernardo-Castilho/dragdroptouch/issues/10

**Comment by liminzhu** [comment]
EdgeHTML issue tracker is the right place for Web APIs. It looks like this issue is already triaged and fixed 😄.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14063806/
