### ISSUE TITLE
Map.get bug with hash code calc

### ISSUE THREAD

**Issue by mybios** [Microsoft/ChakraCore#390]
test case
```javascript
var map = new Map();
map.set(1 , "value");
console.assert(map.get(1) , "ok");

var key = 1.1;
key -= 0.1;
// will assert because "key" is double , and 1 is int
console.assert(map.get(key) , "not ok");
```

**Comment by dilijev** [comment]
Confirmed no throw from v8 in Canary (50) and Chrome (48).

**Comment by ianwjhalliday** [comment]
Good catch.  Yep, a quick look shows that `SameValueComparerCommon::GetHashCode` incorrectly returns different hash values for tagged ints and equivalent untagged ints.  Probably also has this error with Int64 and UInt64 integers.

**Comment by dilijev** [comment]
Tried another repro.

```js

(function() {

var _1 = 1;
var _1dot1 = 1.1;
var _1dot1minus1 = _1dot1 - 0.1;
if (_1 === _1dot1minus1) {
    print("1 === 1.1 - 0.1");
} else {
    print("0: not good");
}
    
var map = new Map();
map.set(1, "test value");

try {
    print(map.get(_1));
} catch (e) {
    print("1: not good");
}

var key = 1.1;
key -= 0.1;

if (map.get(key)) {
    print(map.get(key));
} else {
    print("2: not good");
}

})();
```

Replace print with console.log and it runs with no repro in Canary and Chrome.
Repros in latest Chakra by printing "2: not good"

**Comment by ianwjhalliday** [comment]
This is my bug from years old code. I've assigned it to myself but if someone wants to grab it off me before I get to it I'm cool with that.  Probably will be a couple weeks at minimum before I can get to this.
