### ISSUE TITLE
Edge: sessionStorage in Javascript doesn't work in local

### ISSUE THREAD

**Issue by Buhart** [Microsoft/ChakraCore#3906]
sessionStorage in Javascript doesn't work when I run a page in local without a server directly on a disk. Example:

file:///C:/UwAmp/ww....HTML/Example.html

but it works if you read the page via the network at the  adress:
file://pc_tower/ww....HTML/Example.html

Regards
André

**Comment by jackhorton** [comment]
The EdgeHTML issue tracker is the place to report issues for Web APIs: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues. Thanks!
