### ISSUE TITLE
toPrecision() in Edge gives incorrect output in rare cases

### ISSUE THREAD

**Issue by dajp1** [Microsoft/ChakraCore#3929]
My apologies if this is the wrong place to submit this.

I have found what I suspect is a bug in Edge.  In JavaScript, the lines:

```
a = 0.0003;
b = a.toPrecision(3);

```
result in b containing "0.000200".  (IE, Chrome and Firefox all give the "0.000300" that I was expecting.)

See [http://jsfiddle.net/dajp/2b47qLg0/](http://jsfiddle.net/dajp/2b47qLg0/)

I'm using Edge 40.15063.0.0.
This is causing me some difficulties.  Many thanks.

**Comment by MikeHolman** [comment]
Definitely seems like a real bug and something we should fix. That code is crazy complicated, so I can't immediately understand the problem.

Looks like something is going wrong inside `NumberUtilities::FDblToStr`'s call to `FDblToRgbPrecise` though.

**Comment by obastemur** [comment]
`0.0003` IEEE754 => `0.0003000000142492353916168212890625`

So, toPrecision(3) `indeed` should not return `0.0002`

**Comment by obastemur** [comment]
@dajp1 the expected output for your sample should be `0.00` not `0.003` (since the precision is 3 and there are three zeroes pre any number.) When precision is set to `3` ChakraCore calculates the correct result.

However ChakraCore (as reported) results in `0.0002` when precision is `3`.

**Comment by dajp1** [comment]
@obastemur  I don't agree.  As far as I can see, the specification says that toPrecision() should return a string to the specified number of significant digits, and examples always start with the first non-zero digit.

In my case I was expecting "0.000300" since that has three significant digits starting with the first non-zero digit, and this is what I get on every browser I have tried except Edge.  If precision was set to 4, I would expect "0.0003000", which is indeed what I get (on Edge, IE, Firefox and Chrome).  The bug only appears when the number of significant digits is set to three or fewer.

**Comment by dajp1** [comment]
Sorry - newbie mistake, I pressed the wrong button.  Didn't mean to close this issue.

**Comment by obastemur** [comment]
> As far as I can see, the specification says that toPrecision() should return a string to the specified number of significant digits, and examples always start with the first non-zero digit.

I agree on that. A counting issue on my end. Well, either way ChakraCore was returning the wrong result :)

**Comment by Niggler** [comment]
Stumbled upon a similar issue with `(-6.9e-11).toExponential(4)`.  Edge 13/14 give the correct string `'-6.9000e-11'` but 15/16 give `'-6.8000e-11'`. @obastemur does the patch also cover this case?

**Comment by obastemur** [comment]
Just tested. Yes, the fix covers that case too.
