### ISSUE TITLE
Proposal: Rename tag "Accepting PRs" to "help wanted" 

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3938]
New feature from GitHub: GitHub will now directly surface “help wanted” PRs.
 
![image](https://user-images.githubusercontent.com/494055/31473951-8a4384e6-aeac-11e7-83b7-a9b830fc83aa.png)

We are currently using “Accepting PRs” and have that label set up with up-for-grabs:  https://github.com/Microsoft/ChakraCore/wiki/Label-Glossary#accepting-prs

We can update our entry for up-for-grabs.net here: https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/ChakraCore.yml

Typescript has already made this change in their issue tracker:
https://github.com/Microsoft/TypeScript/pull/19105

This is a quick change:

* [x] https://github.com/Microsoft/ChakraCore/labels - rename “Accepting PRs” to “help wanted”
* [x] Update https://github.com/Microsoft/ChakraCore/wiki/Label-Glossary
* [x] Update references to this tag in ChakraCore-wiki
* [x] Update references to this tag in README etc in ChakraCore
* [x] Submit a PR for https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/ChakraCore.yml
* [x] Confirm up-for-grabs PR is merged and the resulting [query](http://up-for-grabs.net/#/tags/chakra) looks right.

Any objections?

**Comment by dilijev** [comment]
See: https://github.com/up-for-grabs/up-for-grabs.net/pull/765

**Comment by dilijev** [comment]
@liminzhu I'd appreciate a double-check on locations where we had referenced Accepting PRs. It seems to have only been Label Glossary (wiki) and CONTRIBUTING.md, but a second pair of eyes wouldn't hurt.

**Comment by liminzhu** [comment]
Re @dilijev - think you got all of them.

**Comment by dilijev** [comment]
All items completed!

**Comment by dilijev** [comment]
Also updating "Your First PR" to "good first issue" to best take advantage of the new GitHub feature.

**Comment by dilijev** [comment]
'Your first PR' -> 'good first issue': Microsoft/ChakraCore-wiki@e9a0bdc
