### ISSUE TITLE
CustomEvent ES2015 SubClass vs instanceof operator

### ISSUE THREAD

**Issue by beauceant** [Microsoft/ChakraCore#3952]
Might be related to this [other issue](https://github.com/Microsoft/ChakraCore/issues/2997).

**Problem**: when subclassing `CustomEvent`, the `instanceof` operator fails in returning the correct boolean on an instance of that subclass.
Example:
```js
class MySubCustomEvent extends CustomEvent{
    constructor(){
        super('subcustom');
    }
}

const instance = new MySubCustomEvent();
instance instanceof MySubCustomEvent; // returns false (expected true);
instance instanceof CustomEvent; // return true
```

Here's a [jsfiddle](https://jsfiddle.net/8m0fjfh1/1/) that works fine for Chrome, Opera, Firefox, ...but not for Edge.

**Comment by dilijev** [comment]
`CustomEvent` is defined in the web host, so this is likely an [Edge Bug](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues)

**Comment by beauceant** [comment]
I've included "*me too*" [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11923584/) and referenced this GitHub page.

**Comment by dilijev** [comment]
Those issues have been open for awhile and from that site it looks like they have someone assigned to address the issue, so I'm closing this issue.

Thanks for your report!
