### ISSUE TITLE
BUG: Inconsistent module path handling in ch

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#3964]
Slightly convoluted issue I discovered whilst fixing https://github.com/Microsoft/ChakraCore/issues/3902

Note I believe that this is an issue in ch not ChakraCore itself. BUT this issue was causing a CI test failure when I was fixing 3902; and could cause other test errors in the future.

Issue is slightly convoluted and is best illustrated by 5 test cases:
**Case 1**
```js
//testStart.js
WScript.LoadScriptFile("folder/script.js");
```
```js
//folder/script.js
import("../moduleOne.js");
```
```js
//moduleOne.js
console.log("Completed");
```

Output:
```
Couldn't load file.
thrown at moduleOne.js:
^
URIError: [snip]/ChakraCore-master/out/Test/moduleOne.js
```
**The path for the import() from the Script is expected to be relative to the CWD by ch and so this case fails.**

***Case 2***
```js
//testStart.js
WScript.LoadScriptFile("folder/script.js");
```
```js
//folder/script.js
import("moduleOne.js");
```
```js
//moduleOne.js
console.log("Completed");
```
Output:
```
Completed
```

**The path for the import() from the Script is expected to be relative to the CWD by ch and so this case succeeds.**

***Case 3***
```js
//testStart.js
WScript.LoadScriptFile("folder/module.js","module");
```
```js
//folder/module.js
import("../moduleOne.js");
```
```js
//moduleOne.js
console.log("Completed");
```

Output:
```
Completed
```
**The path for the import() from the Module is expected to be relative to the Module by ch and so this case succeeds.**

***Case 4***
```js
//testStart.js
WScript.LoadScriptFile("folder/module.js","module");
WScript.LoadScriptFile("folder/script.js");
```
```js
//folder/module.js
import("../moduleOne.js");
```
```js
//folder/script.js
import("../moduleOne.js");
```
```js
//moduleOne.js
console.log("Completed");
```

Output:
```
Completed
```

**Running both cases 1 and 3 (with 3 first) expect the failure from case 1 BUT ch substitutes the version of moduleOne.js loaded for module.js when moduleOne.js is requested by script.js and so this case succeeds - this behaviour is clearly inconsistent - either the path used in script.js is wrong or it isn't, its accuracy should not be determined by whether the module has already been imported**

***Case 5***
```js
//testStart.js
WScript.LoadScriptFile("folder/script.js");
WScript.LoadScriptFile("folder/module.js","module");
```
```js
//folder/module.js
import("../moduleOne.js");
```
```js
//folder/script.js
import("../moduleOne.js");
```
```js
//moduleOne.js
console.log("Completed");
```

Output:
```
Couldn't load file.
thrown at moduleOne.js:
^
URIError: [snip]/ChakraCore-master/out/Test/moduleOne.js
```

**Running both cases 1 and 3 again but this time with 1 first and the failure is restored**

In the slightly more involved case of the CI test for bug_issue_3257 this behaviour was leading to a hard crash - I had to change the paths in the equivalent script file to suppress it; see also https://github.com/Microsoft/ChakraCore/pull/3934

**Comment by rhuanjl** [comment]
I don't really know the source for ch but at a quick read it seems to me that the difference between cases 4 and 5 above is due to the order of checks in WScriptJSRT::LoadModuleFromString
https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp#L360-L387

I think the only check for whether the file exists is in lines 363-364 BUT if a specifier for the filename exists then lines 360-383 are skipped.

Potentially specifiers should be based on fullpaths not just filenames to avoid this?

**Comment by dilijev** [comment]
Assigning to @akroshg for triage.
/cc @boingoing

**Comment by boingoing** [comment]
I think fixing this in ch and other internal tools will resolve:
https://microsoft.visualstudio.com/web/wi.aspx?id=14303885

**Comment by obastemur** [comment]
I had fixed this issue. @rhuanjl could you please check if latest ch covers this? Closing for now, feel free to open back.
