### ISSUE TITLE
NaN and -NaN can give different bit patterns

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#398]
AFAIK our intention is to always canonicalize so this should be fixed. Note that this only repros in Edge, not in ch.exe.

``` js
function numberToRawBits(v) {
  var isLittleEndian = new Uint8Array(new Uint16Array([1]).buffer)[0] === 1;
  var reduce = Array.prototype[isLittleEndian ? 'reduceRight' : 'reduce'];
  var uint8 = new Uint8Array(new Float64Array([v]).buffer);
  return reduce.call(uint8, (a, v) => a + (v < 16 ? "0" : "") + v.toString(16), "");
}

console.log(numberToRawBits(NaN));
console.log(numberToRawBits(-NaN));
```

Output on Edge 25:
fff8000000000000
7ff8000000000000

**Comment by dilijev** [comment]
@Penguinwizzard I think you did some work in this area. Is this fixed / by design / still an issue we need to look at?

**Comment by wyrichte** [comment]
https://github.com/Microsoft/ChakraCore/pull/5905
