### ISSUE TITLE
perf: String Equal is slow

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#4002]
See https://github.com/Microsoft/ChakraCore/blob/9427f0feefc6b7fd4bb38f700768e395986d2802/lib/Runtime/Library/JavascriptString.cpp#L3896-L3899

Do we have to do this ? It will unnecessarily flatten the string.

Not sure the perf gain on Acme-Air but #3752 case (1) suffers here with 25% perf drop. I would like to investigate it.

**Comment by obastemur** [comment]
Besides; Also investigate whenever / wherever flatten the string on acme-air.

**Comment by rhuanjl** [comment]
Noticed this as a key remaining target for micro optimising with new Date (see comment in https://github.com/Microsoft/ChakraCore/issues/4008 )

I'd like to look at this one but struggling to get to grips with the details of the string implementation.

I'd figure the "easy" fix would be to implement a method for getting a character from a string without flattening it - then use it in a loop.

**Comment by obastemur** [comment]
I have some numbers to share... 

- 25K CopyVirtual call per 1K acme air request.
- 0 UnChain call

This is getting more interesting.

@rhuanjl We will indeed benefit such `getting a character from a string without flattening it` interface but I expect some other changes too. Right now, this is more than improving `Equals` call or some hot path. I'm on it.

**Comment by obastemur** [comment]
Some additional notes;

Added a new function `char16 GetItemNoCopy(charcount_t index)` to all the string types. String::Equals is going to execute in given order below; (the step in the middle is new)

- if str1->Length != str2->Length .. return false
- if !str1->IsFinalized || !str2->IsFinalized ---> GetItemNoCopy (the char in the middle) and compare. If it's different, return false
- Flatten the string(s) and compare as usual.

The middle step corresponds to 3% of the flattening ops in Acme-Air.

Figuring additional usage for `GetItemNoCopy`;

`SimpleTypeHandler` 's `Get/Has...Property` calls suitable for further optimization.

- Equal should take `JavascriptString, PropertyRecord` couple
- Check string type (if it's a LiteralStringWithPropertyStringPtr.. or PropertyString.. get the PropertyRecord and compare the property id.)
- Other string types should first compare the length, and then GetItemNoCopy (the char in the middle) (before flattening the string) and eventually the whole string.

**Comment by obastemur** [comment]
- Consumer (i.e. node-chakracore) uses `JsCopyString` to measure string length. This causes multi level string flattening for no reason. I'm not sure why `JsCopyString` is used there. (Chakrashim, `v8::String::Utf8Length`)

- Adding string memory sharing if two JavascriptString carry same content.

**Comment by MSLaguana** [comment]
We use `JsCopyString` to get the length because every step of the process is required (currently) except for storing the actual utf8 bytes anywhere; We need to iterate over every utf16 character and work out how many utf8 characters it encodes into.

**Comment by obastemur** [comment]
@MSLaguana could please elaborate what ‘’’We need to iterate over every utf16 character and work out how many utf8 characters it encodes into.’’’ means?

**Comment by MSLaguana** [comment]
Given a utf16 string, `v8::String::Utf8Length` wants to know how many bytes it would be when expressed in utf8. The only way to determine this is to look at every utf16 character and see whether it corresponds to 1, 2 or 3 utf8 bytes (or if a pair of 2 utf16 characters corresponds to a 4 utf8 byte codepoint). This is almost exactly the same amount of work as actually encoding the string into utf8, except we don't need to store the resulting utf8 bytes anywhere (and in the counting-only case we don't store them).

**Comment by obastemur** [comment]
There is no tangible gain here. I will open another JavascriptString related issue and track the remaining interesting stuff from there.
