### ISSUE TITLE
perf: new Date(STRING) is slow

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#4008]
`new Date(STRING)` is a hot call on acme-air.

Micro-bench

```
var arr_dates = [];

var days = ['Sun', 'Mon', 'Tue', 'Wed', 'Sat'];
var mons = ['Oct', 'Nov', 'Sep', 'Jun', 'Jan'];

for (var i = 1980; i < 2050; i++)
{
	for(var mday = 1; mday < 29; mday++)
	{
		for(var j = 0; j < days.length; j++)
		{
			for(var k = 0; k < mons.length; k++)
			{
				arr_dates.push(days[j] + " " + mons[k] + " " + mday + " 00:00:00 GMT " + i);
			}
		}
	}
}

// 50K+ dates.. we won't be measuring the cached results

var start = Date.now();
var len = arr_dates.length;
var tt = 0;
for(var i = 0; i < len; i++)
{
	tt += new Date(arr_dates[i]).getMonth();
	tt = tt & 63; // MOD 64
}
var end = Date.now() - start;

console.log("Total: ", end, tt) // tt should be 0!
```

CC is 6x slower than v8 on above micro bench.

**Comment by akroshg** [comment]
When I ran the test with the jshost on the master I get 
```Total:  45 18```
This seems quick enough, no?

**Comment by rhuanjl** [comment]
@obastemur thought I'd try and be helpful

Running with ch on master, release build and lto I get "Total: 380 0"

I then tried running it with instruments' time profiler and found that 348ms of that was spent in this call to _wcslwr:
https://github.com/Microsoft/ChakraCore/blob/2e15b3995061d9dfaf16e0951407c3fbf4139ace/lib/Runtime/Library/DateImplementation.cpp#L1076

It seems to make it faster the key thing to do would be try and make it handle uppercase as well as lowercase.

I'd be happy to have a go at this if you've not already started it (that is if it's ok for an external contributor to look at this.)

**Comment by obastemur** [comment]
@rhuanjl go ahead if you want!

@akroshg Thanks for looking at Windows numbers. Looks like the origin of this issue is PAL `towlower`

**Comment by rhuanjl** [comment]
I’ve had a quick go hacking around with Pal and got the time down from 380ms to 27 ms.
Hi 
I’ve noticed a few optimisation opportunities in pal, will aim to submit a PR over the weekend if it’s ok to edit pal?

**Comment by rhuanjl** [comment]
27ms was an erroneous result (I'd messed up the test).

With it running properly 48ms is my consistent result with https://github.com/Microsoft/ChakraCore/pull/4035

Remaining obvious slow actions are:
a) the use of localtime_r within GetMonth (30% of execution time)
b) the use of memcmp within the string parser - probably could be re-worked to cut down the number of times this is called but would be an extensive re-work. (10 % of execution time)
c) the call to String::Equal used to see if a cached value is available (10 % of execution time) - probably the easiest target - https://github.com/Microsoft/ChakraCore/issues/4002
