### ISSUE TITLE
Use enum classes NumberFormatStyle and NumberFormatCurrencyDisplay in WinGlob code

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#4010]
These enums were introduced to eliminate magic constants, but at the time they were only used in ICU-based Intl code. The WinGlob code uses these same constants for the same meaning.

Move these enums to a header that ICU and WinGlob have in common and update the WinGlob code.

**Comment by jackhorton** [comment]
This was already fixed in master, not sure when it got so

**Comment by dilijev** [comment]
Somewhere in all the refactorings :P
