### ISSUE TITLE
window.fetch() requests that return 401 code do not get their data returned

### ISSUE THREAD

**Issue by wojciechka** [Microsoft/ChakraCore#4019]
When trying to implement authentication in an application, I've come across the following - when using `window.fetch` to make an API call that results in 401 error, the response is not returned and an empty string is returned instead. For example:

```
window.fetch('/api/method', {
  method: 'POST', body: '{"data":"data"}'
}).then(function(r) {return r.json();})
.then(function(ok) {console.log('OK', ok);},
  function(e) {console.log('ERROR',err);});
```

If `/api/method` returns any other HTTP code (i.e. 200, 201, 404), then the result is returned and OK logs the json data. However, if the returned code is 401, `.json()` throws an error that it can't parse the body.

All other browsers I've tested (Chrome 61, Firefox 56) do return the response properly and the issue only happens with Edge.

Ideally the authentication model for the application I am working on will depend on HTTP code being 401 and the response providing enough information to authenticate the user by the frontend and perform auth again.

This does not seem to be possible with Edge.

As 403 code is already used for other things, it can't be switched to that code. Also 401, not 403 should be used to indicate the application has to provide Authorization HTTP header.

**Comment by liminzhu** [comment]
Hey thanks for opening the issue @wojciechka ! This is likely a Web API/EdgeHTML issue, so the EdgeHTML issue tracker is the best place to get the right set of eyes on the matter. Can you file a bug there? See [instructions](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

**Comment by wojciechka** [comment]
Thank you for the response.

FYI opened https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14320968/

**Comment by liminzhu** [comment]
Thank you. I'll close the issue for now since it's tracked somewhere else.
