### ISSUE TITLE
API to get ChakraCore DLL version?

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#4037]
When miniSphere is run with the `--version` switch, I print out the version number of the engine and all its major dependencies, like this:

```
C:\src\spectacles-i>spherun --version
miniSphere 5.0a5 JS game engine (x64)
a lightweight JavaScript-powered game engine
(c) 2015-2017 Fat Cerberus

    Allegro: v5.2.3.0    libmng: v1.0.10
     Dyad.c: v0.2.0        zlib: v1.2.11
```

I haven't found a way to detect the version number of the ChakraCore DLL in use.  Is this possible?

**Comment by xiaoyinl** [comment]
As far as I know, there is no API, but here is how ch.exe reads the version of the ChakraCore DLL from the binary:
https://github.com/Microsoft/ChakraCore/blob/556f5262dc323df05506f4caffb89dbc800434a9/bin/ch/ch.cpp#L106-L152

**Comment by liminzhu** [comment]
Yep there's no API for this now but you can do ch -v or -version
