### ISSUE TITLE
ES6 modules not working with try/catch in module

### ISSUE THREAD

**Issue by herrernst** [Microsoft/ChakraCore#4038]
Hi,
I've found a case where ES6 modules are not working for me in current MS Edge (Creators Update 41.16299.15.0), that is when there is a try/catch in an imported module. It's also reproducable in ChakraCore.

Here is a hosted reduced test case:
https://rawgit.com/herrernst/es6-module-try-catch/master/index.html
It works in current Chrome, Safari, and Firefox (with dom.moduleScripts.enabled), but not in MS Edge (nothing happens). If you [remove the try/catch](https://github.com/herrernst/es6-module-try-catch/blob/master/utils.js#L4) it works.
When running in Chakra (tested with 1.7.3 OSX binary release from GitHub) via `ch ./chakra-wrap.js`, this is printed:
```
thrown at main.js:
^
SyntaxError: Module import or export statement unexpected here
```

**Comment by akroshg** [comment]
@herrernst thanks for reporting this.
I can repro this. @boingoing  do you happen to know why this not working?
although if I move the try/catch to a function it works.

**Comment by boingoing** [comment]
I don't see any obvious issues; seems like that should work.

**Comment by akroshg** [comment]
ok - found the problem. I'll fix and send PR.

**Comment by rhuanjl** [comment]
Also noticed it works if you move the try/catch down to the bottom of the file - specifically have it after the exports rather than before - possible work around until the fix flows through to release.
