### ISSUE TITLE
Default value for function parameters

### ISSUE THREAD

**Issue by Torxed** [Microsoft/ChakraCore#4039]
Hi.

I've got a minimal class which looks as follows:

```javascript
class DB {
	constructor () {

	}

	save(key, val) {
		localStorage.setItem(key, JSON.stringify(val));
		window[key] = val;
	}

	load(key, def='{}') {
		var x = localStorage.getItem(key) || def;
		window[key] = JSON.parse(x);
		return window[key];
	}
}
```

Apparently, Edge is complaining about the use of `def='{}'` in the parameter list. The error is `Expected ')' on Line 11` which tells me that Edge doesn't like the [default parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)

The code works in almost every other browser, which got me thinking. Maybe this isn't actual native JavaScript syntax? Or maybe Edge is just being Edge. But as far as I can tell, it is standard syntax.

Edge is however having a `?` in the [Browser Compatibility list](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility). Either way, I would strongly recommend that this be implemented in Chakra - seeing as it won't break anything, just add functionality.

Sources:

 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by Torxed** [comment]
Just like back in the days where you had to develop specifically for IE, the workaround here would be:

    load(key, def) {
        if(def === undefined)
            def = '{}';
        ...
    }

Again, would be neat if a modern browser was following modern syntax.

**Comment by pleath** [comment]
Hi, @torxed. Can you tell me which version of Edge you're using? Newer releases, beginning with the 1607 release of Windows 10, do support this syntax.

**Comment by dilijev** [comment]
Confirming: ChakraCore at least as far back as 1.2.* (which was approximately 1607 or Anniversary Update) supports this syntax.

```
## Source
function foo(val, a='{}'){print(val, a)}; foo(42);

┌──────────────────┬─────────┐
│ ch-1.2.3         │ 42 {}   │
│ ch-1.3.2         │         │
│ ch-1.4.5         │         │
│ ch-1.5.3         │         │
│ ch-1.6.0         │         │
│ ch-1.6-latest    │         │
│ ch-1.7.1         │         │
│ ch-1.7-latest    │         │
│ ch-master-latest │         │
└──────────────────┴─────────┘
```

**Comment by Torxed** [comment]
Now running `Microsoft Edge 25.10586.672.0 / EdgeHTML 13.10586`, not sure if it auto-update during the testing but it's working now.

Weird to me that the later version wasn't on the ISO.
