### ISSUE TITLE
Error handling for ES Modules

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4068]
ChakraCore does not currently propagate relevant information in error messages from within ES Modules; it would be good to see this fixed
**EDIT1:** see 2nd comment for proposed solution to these issues.
**EDIT2:** see https://github.com/Microsoft/ChakraCore/pull/4080 for PR that addresses points 1 and 3.

**I think I could make a PR to address all of the below points - but a couple of them involve decisions - particularly the fact that currently there is no interface to set a URL for a module see related issue** #3618 

Please let me know what the view of the team is on the below points and if a Pull Request for one or all of them would be welcome.

**Examples - make any error in a module in ch, standard cases:**
1. Syntax error - an error message is given along with the name of the top level parent module but not the file the error is actually in - and no line number (line number is a ch issue - CC provides it)

2. import/export name not found as above, name of top level module and - SyntaxError: Module import insert_name_here cannot be resolved

3. Run time error - stack trace with no filename or URL or specifier

**Looking into this in ChakraCore - key information is not provided when errors are set within modules:**

**1. As far as I cans see syntax errors can be thrown from these two places:**
https://github.com/Microsoft/ChakraCore/blob/9b255666b90e8594054ad851cb88d27675353582/lib/Runtime/Language/SourceTextModuleRecord.cpp#L174
https://github.com/Microsoft/ChakraCore/blob/9b255666b90e8594054ad851cb88d27675353582/lib/Runtime/Language/SourceTextModuleRecord.cpp#L834
In both cases the "optional" 3rd parameter of a URL for ```JavascriptError::CreateFromCompileScriptException``` is not provided. Meaning that the host receives no specifier/url/filename for the error.

I note that as discussed in issue https://github.com/Microsoft/ChakraCore/issues/3618 modules don't have URLs set at the moment (as there is actually no API to provide the URL) BUT the specifier is available ```this->GetSpecifierSz()``` and for most cases could be usable for error handling.

**2. import/export names not found**
https://github.com/Microsoft/ChakraCore/blob/9b255666b90e8594054ad851cb88d27675353582/lib/Runtime/Language/SourceTextModuleRecord.cpp#L630
https://github.com/Microsoft/ChakraCore/blob/9b255666b90e8594054ad851cb88d27675353582/lib/Runtime/Language/SourceTextModuleRecord.cpp#L979
https://github.com/Microsoft/ChakraCore/blob/9b255666b90e8594054ad851cb88d27675353582/lib/Runtime/Language/SourceTextModuleRecord.cpp#L1111
The property name that can't be found is given but the specifier is not provided - for debugging any large module based codebase this will be painful to work with, particularly as default exports will always come up with "default" as their name. In these cases the "fix" looks to be to change the sahpe of the error message slightly, possibly concatenating module specifier with the name of the import/export that can't be resolved.

**3. Run time error - no filename/URL in stack trace**
This comes back to the no URL issue (#3618) I pointed at above and the choice in https://github.com/Microsoft/ChakraCore/blob/09ab25c9a4e28dba22d2130ed323ab791676b11d/lib/Jsrt/Core/JsrtCore.cpp#L80 to give a nullptr as the URL for CreateSourceContextInfo as opposed to setting the specifier in the absence of a URL.

**Comment by rhuanjl** [comment]
Further to the above, thought more on this:

**Proposal**
1. Add URL as a property of a moduleRecord that can be set with JsSetModuleHostInfo

2. If this is set prior to the call to JsParseModuleSource set it as the URL for debugging purposes when parsing the script (otherwise leave as nullptr as it currently is)

3. in all places where an error message is given for a module check if the URL property is nullptr, if it is not include it in the message.

**Possitives**
1. Significantly better error handling will be available for module code

2. No new API required

3. No breaking changes to any existing API

**Negatives**
1. will take a bit of time to write + time to review etc...

**I will aim to make a Pull request  that does the above at some point in the next 5 days; please let me know if this is not wanted.**

**Comment by rhuanjl** [comment]
Points 1 and 3 fixed by PR #4080 which has been merged.

Still need to revisit point 2.

**Comment by kfarnung** [comment]
@curtisman This needs to be reassigned.

**Comment by rhuanjl** [comment]
@kfarnung https://github.com/Microsoft/ChakraCore/pull/4080 fixed most of this issue (for JSRT users at least not sure if it's also an issue in Edge)

I was intending to revisit and fix the rest of the issue later (point 2 from the original post) i.e. that if you import an import that doesn't exist the error message tells you the name of the top level parent module and not the name of the module that actually has the wrong import in it.

When I last looked at it I didn't understand enough of your codebase. I'll take another look shortly and see if I can provide a fix.

**Comment by obastemur** [comment]
I had looked into this a bit. IIRC;The remaining part of the issue is the concern of the consumer (mostly)

**Comment by rhuanjl** [comment]
I'm going to close this issue - as really the key point was resolved in 4080 as I noted above.

The remaining point was just that some error messages aren't great but they're not terrible either and I couldn't see a way to present a more helpful message without some invasive changes which seemed more effort than they were worth.
