### ISSUE TITLE
Emscripten WebGL JS WASM crash

### ISSUE THREAD

**Issue by GregSlazinski** [Microsoft/ChakraCore#4099]
Open with MS Edge:
http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.html
And get crash:
```
xception thrown: RuntimeError: Memory index is out of range,RuntimeError: Memory index is out of range
   at Module[dynCall_v] (http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:374378)
   at browserIterationFunc (http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:174851)
   at Browser.mainLoop.runIter (http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:177943)
   at Browser_mainLoop_runner (http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:176388)

 SCRIPT7017: SCRIPT7017: Memory index is out of range
```

Works fine on Chrome, FireFox and Opera.

**Comment by MikeHolman** [comment]
Weirdly, it looks like we don't crash when the F12 console is open.

**Comment by rhuanjl** [comment]
@GregSlazinski Thought it may be relevant to comment that this crashes in Apple's Safari on macOS too, it triggers a segfault 11 (in both the latest release and the latest technology preview build of Safari).

**Comment by GregSlazinski** [comment]
Hi, yes, Safari bug was reported to Apple as well.

**Comment by GregSlazinski** [comment]
This was supposedly fixed months ago, but I'm still having same crashes.
Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299

**Comment by MikeHolman** [comment]
This was fixed, but we ship on Windows release schedule, which is about a 6 month development cycle. The fix will ship in RS4, which is now not too much farther out. (I don't know/can't say exactly, but I'm sure the internet has decent speculation.)

**Comment by GregSlazinski** [comment]
Cool, the page loads now, but the screen is black. Do I need to wait another 6 months until this is fixed?
Works fine on Chrome and Opera.

**Comment by Cellule** [comment]
@MikeHolman I have checked and the page does show a black screen in insider builds.
I do remember that it was working when we fixed this initially. I fear that a bug in Edge was introduced afterward. The Wasm seems to be fine at least as I can hear sound and the GUI does show up.
Can you verify to see if we need to escalate this to another team?

**Comment by MikeHolman** [comment]
@GregSlazinski Chrome and Opera use the same engine so it's expected that they would have the same result. I'm also seeing a black screen on Firefox. Has the demo page changed since February?

**Comment by GregSlazinski** [comment]
Hi,

http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.html
Latest version of demo from June 2018, compiled with latest Emscripten
uses WebGL 2.0, if not available then falls back to 1.0
Chrome - all OK
FireFox - I'm guessing that older FireFox would work OK since the old demo worked fine, new FireFox has completely black screen (no 2D UI)
Edge - latest Edge has only 2D UI, but no 3D graphics

http://esenthel.com/site/Esenthel%20Fantasy%20Demo%20WebGL1/Esenthel%20Fantasy%20Demo%20WebGL1.html
Latest version of demo from June 2018, compiled with latest Emscripten
uses WebGL 1.0 only
Chrome - all OK
FireFox - I'm guessing that older FireFox would work OK since the old demo worked fine, new FireFox has completely black screen (no 2D UI)
Edge - latest Edge has only 2D UI, but no 3D graphics

http://esenthel.com/site/Esenthel%20Fantasy%20Demo%20Old/Esenthel%20Fantasy%20Demo.html
The old demo from December 2017
uses WebGL 2.0, if not available then falls back to 1.0
Chrome - all OK
FireFox - older FireFox worked OK, new FireFox has completely black screen (no 2D UI)
Edge - latest Edge has only 2D UI, but no 3D graphics

Summary:
Chrome - all OK
FireFox - older version worked OK with GL2/1, new version works with WebGL 1 demo but on WebGL 2 has black screen
Edge - doesn't support WebGL 2 at all, and WebGL 1 has only 2D UI but no 3D

**Comment by MikeHolman** [comment]
Thanks for the details! I think this is a WebGL issue, so I've opened a bug internally and assigned it to our WebGL people.

**Comment by liminzhu** [comment]
I'm going to close this one since it's unrelated to ChakraCore. Feel free to re-open if you have anything we can help with.
