### ISSUE TITLE
Functions returned by Function.prototype.bind() have non-configurable lengths

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4122]
Example:
```js
Object.getOwnPropertyDescriptor(function (a, b) { return 0; }, "length").configurable // true
Object.getOwnPropertyDescriptor(function (a, b) { return 0; }.bind({}), "length").configurable // false
```

This is blocking tests 10.3.2_1_a_L15.js, 12.3.2_1_a_L15, 11.3.2_1_a_L15, 10.2.2_L15.js, 12.2.2_L15.js, and 11.2.2_L15.js in test262/test/intl402

/cc @bterlson

**Comment by jackhorton** [comment]
There's a whole lot of special casing in BoundFunction.cpp for not allowing things to happen to the length property (its hard-coded to be non-configurable, non-enumerable, non-writable, and non-delete-able).

**Comment by dilijev** [comment]
Removing Intl-ICU tag since this applies to non-ICU Intl as well.

**Comment by bterlson** [comment]
Possibly related: https://github.com/Microsoft/ChakraCore/pull/3606.

**Comment by akroshg** [comment]
well #3606 didn't address the boundfunction scenario. But it can easily be done by returning true in the IsConfigurable function.

**Comment by jackhorton** [comment]
Removing that if block definitely resolves the test262 failures, but I didn't test how that impacted actually trying to configure it. There's enough special casing about the length property in BoundFunction.cpp that I would imagine it would still fail in relatively interesting ways.

**Comment by akroshg** [comment]
even though the length is marked as configurable, we actually don't honor it's configurability.
```js
        function foo() { }
        delete foo.length;
        print(foo.hasOwnProperty("length"));

```
this should yield ```false```, but it prints ```true```

**Comment by rhuanjl** [comment]
Taking a look at this, seems to be several related problems:

| Issue   | normal Function  |  boundFunction |
|:----------|:-------------|:------|
| Length should be configurable| passes | fails |
| Deleting length should succeed |    fails   |   fails  |
| Deleting length should not throw| fails (in strict mode) | fails (in strict mode) |
| value after deletion = 0 | fails | fails |
|using defineProperty to redefine length | fails | fails |

These errors appear to relate to the mechanism for handling length:
- script functions do not have a length property
- instead traps for length are used within hasProperty, getProperty, delete property etc. to provide the correct answers
- the traps don't handle deletion or redefinition
- bizarrely the trap in the delete method has a throwIfStrict mode

I'll look at fixing this by making length into a normal property and getting rid of the trap(s).
