### ISSUE TITLE
IE11 does not render controls when there is a slow connection but Chrome and Firefox do

### ISSUE THREAD

**Issue by sreeramana** [Microsoft/ChakraCore#4142]
Hi,
One of our deployed website is slow because of several reasons. We are constantly trying to fix the latency issues. Our end users do not have much concerns about latency but missing controls like buttons etc while using IE11 and Edge. They have to refresh the page again to get the controls to be visible. This is not the case with Chrome or Firefox.

Looks like the way IE or Edge interprets javascript code and looking for dependent files is not efficient in slow connections. This is our observation so far.

Please give us any hints/suggestions to resolve this during slow connections if there are settings to tuneup at browser level.There are around 160 CSS & JS files downloaded while accessing our site and it takes 20 to 40 secs on average.

you can try accessing our website at https://connex.ngsmedicare.com

**Comment by dilijev** [comment]
Thanks for the issue report.

This is an Edge issue. Please open an issue on their issue tracker: https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues

**Comment by digitalinfinity** [comment]
Network transfer of content is not done by Chakra- it's handled by Edge itself. You can try filing an issue using Edge's issue tracker at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ and someone there might be able to help you better.
