### ISSUE TITLE
Problem with URLSearchParams 

### ISSUE THREAD

**Issue by kasper3** [Microsoft/ChakraCore#4164]
Is this API going to be supported in edge anytime soon? `getAll` seems to only return one occurrence.
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/getAll

**Comment by liminzhu** [comment]
hey @kasper3 , thanks for reporting the issue. This is a web API which is out of scope of the JS engine. Please open an issue on the Edge issue tracker https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues.
