### ISSUE TITLE
Unicode: String.prototype.{toUpperCase,toLowerCase} don't handle characters that would increase the string length

### ISSUE THREAD

**Issue by goyakin** [Microsoft/ChakraCore#421]
For example, `'ß'.toUpperCase() === 'SS'` should be true, but Chakra doesn't handle that character and it's `'ß'.toUpperCase() === 'ß'` instead.

The list of such characters are maintained in the [SpecialCasing.txt](http://unicode.org/Public/UNIDATA/SpecialCasing.txt) file.

**Comment by abchatra** [comment]
Does this has potential to break websites?

**Comment by goyakin** [comment]
@abchatra We never supported such mappings, so this isn't something new.

**Comment by mfikes** [comment]
With ChakraCore v1.7.0 (downloaded from [here](https://github.com/Microsoft/ChakraCore/releases)) on macOS, for this script

```javascript
print("[" + "Straße".toUpperCase() + "]");
```

I get this output when running with ChackraCore:

```
[STRASS]
```

For comparison, V8, Nashorn, and JavaScriptCore produce:

```
[STRASSE]
```

while SpiderMonkey produces

```
[STRAßE]
```

**Comment by envygeeks** [comment]
That should be "doesn't" not "don't"

**Comment by jackhorton** [comment]
This is only impacting macOS and Linux, it seems -- Windows returns `[STRAßE]`, similar to SpiderMonkey in your testing (though, interestingly, Firefox returns `[STRASSE]` for me on both Windows and Linux). I can probably look into this going forward.
