### ISSUE TITLE
cross-compile from BSD or Linux

### ISSUE THREAD

**Issue by rvx86** [Microsoft/ChakraCore#4210]
Are there any plans to allow BSD or Linux cross-compile for Windows, using mingw-w64 or an LLVM/Clang cross-compiler?

**Comment by obastemur** [comment]
Have you tried Windows bash?

**Comment by obastemur** [comment]
Just realized got the question wrong. AFAIK, there is no special plan for it. However, if you are able to cross compile a similarly complex project, you should be able to do the same with ChakraCore.
