### ISSUE TITLE
Should PAGE_EXECUTE_RO_TARGETS_INVALID include PAGE_TARGETS_NO_UPDATE?

### ISSUE THREAD

**Issue by tomrittervg** [Microsoft/ChakraCore#4211]
While reviewing PAGE_EXECUTE_RO_TARGETS_INVALID I saw that it includes PAGE_TARGETS_INVALID (assuming CFG is enabled of course) but not PAGE_TARGETS_NO_UPDATE.

From my understanding, PAGE_TARGETS_NO_UPDATE says that if a memory region (that was allocated with PAGE_TARGETS_INVALID) is remapped using VirtualProtect, then all locations become valid call targets for CFG - effectively disabling CFG protection.

I am thinking of Chakra primarily in the Edge use case. In Edge, Arbitrary Code Guard should prevent a memory section from ever being remapped. PAGE_TARGETS_NO_UPDATE only applied that situation so one could say that it either is not needed or that adding it is effectively a no-op.  However, imagine if there were a vulnerability in ACG that _did_ allow a page to be remapped. In that instance, PAGE_TARGETS_NO_UPDATE _would_ prevent CFG from being disabled.

If I understand things correctly, it seems like (at least as far as Edge is concerned) there is no harm in adding it, and a small but non-zero chance it might help in an unlikely scenario.

**Comment by MikeHolman** [comment]
Interesting question. Both `PAGE_TARGETS_NO_UPDATE` and `PAGE_TARGETS_INVALID` actually have the same value (`0x40000000`), so adding both wouldn't do anything. The flag just has different meaning depending on if it is used in `VirtualProtect` or `VirtualAlloc` call.
