### ISSUE TITLE
stack-use-after-scope in ArenaAllocator.cpp (only Debug version)

### ISSUE THREAD

**Issue by hikame** [Microsoft/ChakraCore#4237]
The following code segment in the ArenaAllocator.cpp file has a stack-use-after-scope bug.
`        void **policy = &this->freeList;`
`#if DBG`
`        if (needsDelayFreeList)`
`        {`
`            void *delayFreeList = reinterpret_cast<FreeObject **>(this->freeList) + (MaxSmallObjectSize >> ObjectAlignmentBitShift);`
`            policy = &delayFreeList;`
`        }`
`#endif`
`        *policy = TFreeListPolicy::Free(*policy, buffer, size);`

**Comment by jianchun** [comment]
@hikame Thanks for finding and filing this issue. It was fixed by https://github.com/Microsoft/ChakraCore/pull/4216.
