### ISSUE TITLE
Fix error message for changing [[Writable]] to true from false for non-configurable properties

### ISSUE THREAD

**Issue by rajatd** [Microsoft/ChakraCore#424]
Currently the error message we print is "Cannot modify non-writable property" while it should be "Cannot redefine non-configurable property"

**Comment by ljharb** [comment]
By spec, nonconfigurable properties certainly can be changed from `writable: true` to `writable: false` - it's only that nonconfigurable nonwritable properties can't be made writable.

You can see this with:
```js
'use strict';
var obj = Object.defineProperty({}, 'foo', { configurable: false, writable: true });
console.log(Object.getOwnPropertyDescriptor(obj, 'foo'));
Object.defineProperty(obj, 'foo', { writable: false });
console.log(Object.getOwnPropertyDescriptor(obj, 'foo'));
```

**Comment by ljharb** [comment]
oops, never mind, I misread your issue title :-) will delete my comment

**Comment by ljharb** [comment]
It might be useful to say something more specific like "Cannot make nonconfigurable property writable" when attempting to set `writable` to `true` - to highlight the difference where you can change it to `false`.

**Comment by rajatd** [comment]
Thanks @ljharb . Sure, we could have that. However, we have a macro for the error message to be thrown when trying to redefine non-configurable properties (except for the cases where it is allowed). Having a different one just for this case doesn't really seem worth it. Other browsers also just say "cannot redefine....".

**Comment by ljharb** [comment]
Fair. I'd say every error message should be as helpful as possible, even if other browsers don't live up to that standard, but I don't truly understand the tradeoffs there.

**Comment by EdMaurer** [comment]
Not enough impact to add to 1.4.1
