### ISSUE TITLE
Jenkins CI should signal error if there are invalid characters (non-ASCII etc) in a source file

### ISSUE THREAD

**Issue by ricobbe** [Microsoft/ChakraCore#4268]
I just discovered and removed a control-C character that somehow managed to get into one of our source files.  Can we add a Jenkins check for invalid chars, similar to (and possibly part of) the existing tab and EOL checks?

Candidate definition of the set of valid characters: U+000A and U+0020 through U+007E, inclusive.  (That is, newline, space, and all of the printable ASCII characters.)

**Comment by MSLaguana** [comment]
I think it'll be easier to have a ban-list of control characters, since some of our files are expected to have unicode characters. @dilijev do you have any thoughts on this?

**Comment by obastemur** [comment]
> since some of our files are expected to have unicode characters.

Curious which ChakraCore source files have. Any link to those?

**Comment by MSLaguana** [comment]
I was thinking of test js files, not sure if any of our C files are expected to have unicode

**Comment by obastemur** [comment]
We don't have any C/C++ source code with non ascii char.

`find -E . -regex ".*\.(c|cc|h|cpp|hpp|C|CC|CPP|HPP)" -exec perl -lne 'print if /[^[:ascii:]]/' {} \;`

Didn't spend much time but the line above should be enough to test.

**Comment by MSLaguana** [comment]
I was just experimenting with this command line: ` grep -RIl -P -n "[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]" `

That finds 2 more non-printable characters: there's a couple of `^L` characters in `test/Optimizer/test115.js` and a few more in `test/Strings.trim.baseline`.

I'm pretty sure we want to leave baselines alone, but I'm somewhat confused about how the optimizer test isn't a parse error (unless it's supposed to be?!).

**Comment by ricobbe** [comment]
I should have been clearer in the original description.  I'd intended this to apply to .cpp, .h, etc. files, and not to test files or baselines.

**Comment by dilijev** [comment]
At some point in the past I sanitized all of our C++ source files to remove non-ASCII characters. Didn't include control characters in that pass; it's possible that could have slipped through. It's easier for us to ensure we compile on systems of all locales (no code page confusion) if we stick to strict ASCII in our C++ files. JS files can, and sometimes must, include unicode characters.

We can absolutely add a CI check in the same vein as the existing style checks to check for banned characters in .cpp and .h files.

**Comment by dilijev** [comment]
See https://github.com/Microsoft/ChakraCore/pull/4766#discussion_r172352553

> at least for MSVC, not sure if other platforms just assume UTF-8 by default.
`/source-charset:utf-8`

**Comment by dilijev** [comment]
See PR #5452 (Fix #5428) -- we should also enforce ASCII-only in Intl.js and JsBuiltins.js

**Comment by dilijev** [comment]
FWIW I don't think this check needs to be any more strict than one which prevents errors related to encodings (so, check for and block all non-ASCII only in C++ source files and any text which would end up in generated C++ source files)

**Comment by rhuanjl** [comment]
If I wanted to address this issue would it be as per instructions here: 
https://github.com/Microsoft/ChakraCore/wiki/Jenkins-CI-Checks#making-changes-to-the-jenkins-ci-configuration

Including opening a PR to master-ci initially?

**Comment by dilijev** [comment]
Hey, I didn't see this notification. Yes, that's correct. Let me update master-ci to match latest master for you.

**Comment by dilijev** [comment]
Done, have at it!
