### ISSUE TITLE
Build minimum size ChakraCore for embedding?

### ISSUE THREAD

**Issue by tommyZZM** [Microsoft/ChakraCore#4278]
default ChakraCore size uses over 41.7mb size, can i make it smaller?

**Comment by obastemur** [comment]
41.7? Is that the .a file ? It gets smaller after linker. You may also do ‘strip -x’ to ditch debug symbols.

++
@curtisman had added a smaller binary option that should help further. IIRC that option needs to be enabled with build.sh/CMake for *nix. I will look at that.

**Comment by tommyZZM** [comment]
reply @obastemur

 `41.7` is the size of chakracore for macOS (a binary name `ch`) that i download from the release page (https://github.com/Microsoft/ChakraCore/releases), 

in embedding project, ` .a` file got even larger, nearly 250mb

**Comment by obastemur** [comment]
@tommyZZM makes sense. That’s not stripped nor optimized for size.

**Comment by obastemur** [comment]
BTW; we include ICU + stdlibc++ embedded into `ch` and `.so` in order to make things easy for end users.

++ `strip -x` reduces extra ~6Mb.. IIRC ChakraCore related part should be around ~20 .

**Comment by rhuanjl** [comment]
If Unicode support is not required running the build script with the --no-icu option shrinks it a lot (around 16mb).

**Comment by liminzhu** [comment]
You can also build with interpreter-only if you want the bare minimum. Trade-off here is obviously performance. 

@obastemur @curtisman what's the flag for that again?

**Comment by digitalinfinity** [comment]
I don't think the build flags are exposed nicely through build.sh but the flag needed is CHAKRACORE_LITE - you can define it in CommonDefines.h or also perhaps also in CFLAGS/CXXFLAGS. I haven't tested the latter though.

See https://github.com/Microsoft/ChakraCore/pull/3553 for details

**Comment by obastemur** [comment]
`build.sh` supports turning of JIT and disabling ICU. `--no-jit` `--no-icu` yet ` CHAKRACORE_LITE` comes with additional perks those I've been planning to enable via `build.sh`.

We need to https://github.com/Microsoft/ChakraCore/pull/4285 first

**Comment by liminzhu** [comment]
// cc @curtisman 

Lite mode seems very useful that we should document it perhaps in [Building ChakraCore](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore). 

I did `#define CHAKRACORE_LITE` in CommonDefines.h and made a x64 release build from today's master but I only see the binary size go down from 6663kb to 6014kb. Am I missing anything?

**Comment by curtisman** [comment]
#define is not enough, because it also disable JIT and ScriptDebug in the project files.

On windows build, pass /p:BuildLite=true to msbuild to build Lite mode.

Latest master x64 binary size:
Default: 6.71MB
Lite: 3.16MB

We need to do a little work for Linux build to enable Lite mode.
I believe it need to add the NoScriptDebug build and have lite build to turn off both JIT and ScriptDebug in additional to defining CHAKRACORE_LITE.
