### ISSUE TITLE
Remove EnableJitInDiagMode from the code

### ISSUE THREAD

**Issue by obastemur** [microsoft/ChakraCore#4311]
It's an unused broken flag. We better remove it from the code and test cases. Long story short, if JIT is enabled, it's also enabled for Debugger and there is no another supported option.

**Comment by akroshg** [comment]
Yup.

**Comment by fatcerberus** [comment]
> if JIT is enabled, it's also enabled for Debugger 

Is this actually the case in practice?  It’s been my experience based on performance assessments that attaching the debugger switches execution to a fully interpreted mode with no JIT.

**Comment by tanya-vedi** [comment]
I want to take up this issue.

**Comment by obastemur** [comment]
@tanya-vedi , it’s yours. Go ahead and send the PR

**Comment by tanya-vedi** [comment]
Thanks! I'm a beginner, can someone help me with this?

**Comment by obastemur** [comment]
> Is this actually the case in practice?

@fatcerberus JIT debugging was disabled on xplat. Now it’s enabled again on both master and release 1.9

> I'm a beginner, can someone help me with this?

@tanya-vedi feel free to ask your questions here. I have no doubt that ChakraCore contributors will gladly answer them.

**Comment by tanya-vedi** [comment]
If anyone can help me proceed with this issue, then it would be great.

**Comment by ajomadlabs** [comment]
Is there anyone working on this ?

**Comment by fatcerberus** [comment]
@ajomadlabs Yes, see #4657 (which in fact is linked above).

**Comment by championshuttler** [comment]
Can i take this up if some is not working on it. It seems like there is a PR against this issue but its quite old and not updated from a while

**Comment by digitalinfinity** [comment]
@mhaviv are you still planning on working on #4657?

**Comment by mhaviv** [comment]
Hi Hitesh,

Unfortunately I have not had the time and I cannot work on it. You can give the task to someone else. I apologize for any inconvenience

- Michael
