### ISSUE TITLE
undefined identifier uint16_t - ChakraCore.h

### ISSUE THREAD

**Issue by notvita** [Microsoft/ChakraCore#4320]
Following the embedding [guide in the wiki](https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore) I was getting errors caused by an undefined identifier `uint16_t` in `CharkraCore.h` caused by a missing header.

Including `inttypes.h` or `stdint.h` fixed the issue. Not sure if this was a problem on my end but thought I'd make a issue anyway.

Thanks.

**Comment by obastemur** [comment]
Do you have ChakraCommon.h there? That’s the one adding those. Which OS?

**Comment by notvita** [comment]
Yeah I do. Windows 10, x64.

I have a higher `_MSC_VER` than in the if statement where the typedef is defined.

My macro is:

`#define _MSC_VER 1911`

**Comment by obastemur** [comment]
I see. IMHO we can put an `#else` to https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCommon.h#L96 and `#include<stdint.h>`

@notvita could you please try and if it works for you, could you please send a PR with the fix?

**Comment by notvita** [comment]
That did the trick. PR sent. Thanks

**Comment by obastemur** [comment]
#4322 fixes.
