### ISSUE TITLE
Can I run webasm with ChakraCore?

### ISSUE THREAD

**Issue by justinmchase** [Microsoft/ChakraCore#4323]
Suppose I'm making a C++ app and embedding ChakraCore and I want to execute some pre-compiled webassembly, is this supported? And what would be the api I would need to call for that if so?

To start with lets  just assume I'm doing a straight copy [this example app.](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/Hello%20World/Windows/C%2B%2B/HelloWorld/HelloWorld.cpp#L16)

And on that highlighted line instead of using javascript I am reading webasm from a file. And suppose I am using this to compile to webassembly:
https://www.npmjs.com/package/binaryen

What I'm wondering is if there is a `JsRunWebAsm` [instead of `JsRunScript`](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/Hello%20World/Windows/C%2B%2B/HelloWorld/HelloWorld.cpp#L28)

**Comment by liminzhu** [comment]
I don't think we have a ```JsRunWebAsm``` per se, but you can execute wasm by running a script using the [JS APIs](http://webassembly.org/getting-started/js-api/).

**Comment by MikeHolman** [comment]
That's right, you can still use JsRunScript. Binaryen creates JS glue code needed for hosting wasm, including the code to initialize the wasm module, but also code to perform I/O which isn't natively supported by wasm. As such. we don't have a "pure" wasm environment. It's possible that this glue code will need some tweaking for ChakraCore embedding, though.

**Comment by justinmchase** [comment]
Awesome, you even answered my followup question with that link :)

One last followup as I think I have what I need to keep digging otherwise, on [this page in the webassembly docs](http://webassembly.org/getting-started/js-api/#function-imports-and-exports) it says:

> (Here, instead of writing the module in C/C++ and compiling to WebAssembly, we write the module directly in the text format which can be assembled directly into the binary file simple.wasm.)

Then they link to this [WABT](https://github.com/WebAssembly/wabt) tool. This tool appears to be a C++ command line tool but suppose I wanted to dynamically compile something in the browser. Do you know of any pure JS implementations of an assembler? Is there any reason why it couldn't be done in JS?

**Comment by liminzhu** [comment]
I'm not aware of a pure JS WABT but you can ask WABT maintainers if they know anything and why WABT isn't done in JS instead of me giving you my guess :). 

Actually you might be able to convert wabt to wasm or asm.js to run in a browser, but I haven't tried that.

**Comment by justinmchase** [comment]
I was having similar thoughts and did ask them, thanks.
