### ISSUE TITLE
Chakracore not building with clang 5.0 on Linux

### ISSUE THREAD

**Issue by gh-markt** [Microsoft/ChakraCore#4327]
Building 1.7 or 1.8 from the source results in a large number of duplicate symbol errors, appearing to arise because instances of a const int are created in a header file that is included in multiple source files.   This is apparently tried to be mitigated by using a __declspec(selectany) construct to only link one of them, but this construct does not seem to work in Clang 5 on Linux.   While this may be a bug in the compiler, at the end of the day, it seems that there could still be workarounds to this which are less problematic.

Attached to this is a diff, which I would propose as a solution to the issue.   There are two components to the fix.  The first is to fix the ShiftValue in BVUnitT so that it did not complain about multiple definitions, and the second part is to change how MachPtr is defined in the architecture-dependent md.h file.  In particular, the const int construct is removed, and both replaced with enums, which can be evaluated at compile time.  Then, a template specialized constexpr function is used to specialize the value of ShiftValue, a regular global integer value is created in one source file to hold a duplicate of MachPtr that can be accessed externally, and the preprocessor is used to redirect access to what would otherwise be an extern const int to the global variable, so the change is transparent to everything else.

[chakracore.txt](https://github.com/Microsoft/ChakraCore/files/1506479/chakracore.txt)

**Comment by obastemur** [comment]
@gh-markt could be nice if you can send the PR.

**Comment by obastemur** [comment]
Additionally updating package creator for release/1.8 ++ master to Clang 5.0.0

**Comment by gh-markt** [comment]
I didn’t know I had any authorization to do so.  I’ll submit a pull request when I get home tonight.

**Comment by obastemur** [comment]
Great, could be nice if you target Release/1.8

**Comment by obastemur** [comment]
Please also include https://github.com/Microsoft/ChakraCore/commit/c5d88847f2f6f287991db878e8852ad49b290712

**Comment by gh-markt** [comment]
As I suspect, I don't have the ability to push my own branch to this project to make a pull request with.

**Comment by rhuanjl** [comment]
@gh-markt you have to fork the whole project, create a branch on your fork by cloning 1.8 make your changes in that branch then make a pull request here; anyone can do it.

**Comment by obastemur** [comment]
Fixed. @gh-markt Thanks for the issue and the fix.
