### ISSUE TITLE
Lambda functions have issues inside ternary statements

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/ChakraCore#4338]
After a recent change in master, node-chakracore started failing a test with this snippet of code:

```js
const onentryFunction = opt => {
  const onentry = opt.onentry
  opt.onentry = onentry ? e => {
    onentry(e)
    e.resume()
  } : e => e.resume()
}
```

In particular, it complained about the `:` in the ternary:

```
  } : e => e.resume()
    ^^

SyntaxError: Expected ';'
```

**Comment by dilijev** [comment]
Fixed in https://github.com/Microsoft/ChakraCore/pull/4339
