### ISSUE TITLE
Throwing an error causes ToString call on a property, and that property is a Symbol.

### ISSUE THREAD

**Issue by akroshg** [Microsoft/ChakraCore#435]
eg. 
```javascript
var a = undefined
a[Object(Symbol())] = 10;
```
as `a `is undefined we throw a type error. While throwing, we are trying to get string from that property to populate error information, which makes `ToString `call to that property (in this scenario that property is `Symbol`).
Is this implicit `ToString `call on `Symbol `correct and as per spec?
Look for 
`JavascriptError::ThrowTypeError(scriptContext, JSERR_Property_CannotSet_NullOrUndefined, GetPropertyDisplayNameForError(index, scriptContext));
`in the code base.

**Comment by akroshg** [comment]
This issue raised from #422.

**Comment by ljharb** [comment]
The spec doesn't talk about how error message text is generated - so an observable `toString` on that property is probably not something that's expected.

**Comment by boingoing** [comment]
Fixed by #540
