### ISSUE TITLE
TreeWalker API issue

### ISSUE THREAD

**Issue by sergei-startsev** [Microsoft/ChakraCore#4358]
Open the following codepen with MS Edge (38.14393.1066.0):
https://codepen.io/asapach/pen/MOZyRp?editors=1012

And get the FAILED result:
```html
<strong>FAILED</strong>
```
And then compare results in Chrome, FireFox:
```html
<span>PASSED</span>
```

**Comment by dilijev** [comment]
TreeWalker APIs (and anything on the document object) are owned by Edge. Can you open this issue on their issue tracker? https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues

**Comment by sergei-startsev** [comment]
Opened the corresponding issue to Edge tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14904585/

**Comment by digitalinfinity** [comment]
Thanks @sergei-startsev - closing this one since it's being tracked by Edge now.
