### ISSUE TITLE
first item in jQuery XMLfind shows twice

### ISSUE THREAD

**Issue by mlasell2** [Microsoft/ChakraCore#4369]
This rss feed jQuery parsing code works in Chrome and Safari on an IPhone but inexplicably doubles the first item in  Edge.
 $.get("htps://themidpod.libsyn.com/rss", function (data) {
    var $XML = $(data);
    $XML.find("item").each(function (i) {
        var $this = $(this),
            item = {
                title: $this.find("title").text(),
                link: $this.find("enclosure").attr("url"),
                description: $this.find("description").text(),
                pubDate: $this.find("pubDate").text(),
               ...
            };
        var theTitle='`<h3>`' + item.title + '`</h3>`';
In the Edge debugger at this point item.title is already "The title goes hereThe title goes here".
Everything that follows is correct. 
This can be seen at https://www.themidpod.com/listen. In Edge the title is doubled, in other browsers it is not.
 Is this a known issue or something else I need to keep hunting for?
Thanks,
Michael Lasell

**Comment by liminzhu** [comment]
Thanks for reporting the issue @mlasell2. This looks like a Web API issue rather than a JavaScript one. Please open an issue on the Edge issue tracker https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues to get the right set of people looking into it.

**Comment by mlasell2** [comment]
I further debugged this and noticed that Edge jQuery implementation is finding and concatenating both
```
<item>
			<title>xyz</title> and
			<itunes:title>xyz</itunes:title>
```

Other browsers do not do this. Not sure if this is a bug or a feature, but it isn’t the standard other browsers are using. I can figure out a solution for my issue.

**Comment by dilijev** [comment]
@mlasell2 The best way to get eyes on this issue (and whether or not it is an issue) is to report the issue to the Edge issue tracker as @liminzhu mentioned.
