### ISSUE TITLE
After calling appendChild, checked nodes are no longer shown as checked using innerHTML property

### ISSUE THREAD

**Issue by svejdo1** [Microsoft/ChakraCore#4380]
Sample:
```
<div id="editor" contenteditable="true" data-ckeditor="true"></div>
<div>
  <input name="fieldControlId2" id="kid1" type="radio" checked="checked" value="1">
  <input name="fieldControlId2" id="kid2" type="radio" value="2">
</div>
```

```
var root = document.getElementById('editor');
var kid1 = document.getElementById('kid1');
var kid2 = document.getElementById('kid2');
root.appendChild(kid1);
root.appendChild(kid2);
alert(root.innerHTML);

```

Notice the checked="checked" is no longer present.
JsFiddle: https://jsfiddle.net/svejdo1/tpghugv2/1/

Reproes both in EDGE/IE11.

**Comment by liminzhu** [comment]
Thanks for opening the issue @svejdo1 . This looks like a DOM issue rather than a JS problem. Please file an issue on the [Edge issue tracker](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) to get the right set of people looking into it.
