### ISSUE TITLE
Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by hemanth** [Microsoft/ChakraCore#4393]
Building Chakra on macOS ≤ 10.12 resulted in `Symbol not found: _clock_gettime`

<img width="709" alt="screen shot 2017-12-07 at 10 31 32 pm" src="https://user-images.githubusercontent.com/18315/33727658-b499ce52-db9e-11e7-95b0-a9ed7f5f5fa1.png">

//cc @bterlson

**Comment by obastemur** [comment]
@hemanth Thanks for reporting this. Looks like we have got an issue with build script. Looking into it closely.
