### ISSUE TITLE
Microsoft Edge doesn't display nested elements properly when I dynamically remove the hidden attribute on the parent of the nested element.

### ISSUE THREAD

**Issue by JoshuaKeyz** [Microsoft/ChakraCore#4397]
Please can this issue be fixed? Other browsers including Internet Explorer works pretty fine with respect to this Microsoft Edge error.

This bug is quite unpredictable. When you first load run the plunker on Microsoft Edge, it might work properly, while sometimes it doesn't. But just reload the page, first with a Major reload, and try if the problem appears, if it doesn't, then try the minor reload, (the one with the reload icon) and then the problem will appear. It's in inconsistent but persistent. 

It works on Internet Explorer and other browsers but it seems to have some problems in Microsoft Edge

**Comment by JoshuaKeyz** [comment]
[https://plnkr.co/edit/4XalOoE2Y3TiMyYKR3Py?p=preview](url)
This is the link to the code launched in plunker.

**Comment by liminzhu** [comment]
Thanks for reporting the issue @mlasell2. This sounds like a web browser issue rather than a JavaScript VM one. Please open an issue on the Edge issue tracker https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues to get the right set of people looking into it.
