### ISSUE TITLE
Test: wasm/params.js flaky failure

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#4414]
Seen in: https://github.com/Microsoft/ChakraCore/pull/4409

https://ci2.dot.net/job/Microsoft_ChakraCore/job/release_1.8/job/shared_ubuntu_linux_debug_prtest/248/consoleFull#-3969678191145e095-857e-4c41-a4bc-0e4be44ef5c5

```
[2140/2141 2.70] Failed -> wasm/params.js
00:14:08.685 /mnt/j/w/Microsoft_ChakraCore/release_1.8/shared_ubuntu_linux_debug_prtest/out/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- -dynamicprofilecache:profile.dpl.2712 -wasm -EnableFatalErrorOnOOM- -args 14000 -endargs /mnt/j/w/Microsoft_ChakraCore/release_1.8/shared_ubuntu_linux_debug_prtest/test/wasm/params.js
```

**Comment by Cellule** [comment]
Have we seen this issue occur again since then ?
I remember looking into it when you first created the issue, but I don't recall if I took action and just forgot to close the issue.

**Comment by dilijev** [comment]
I haven't been watching CI failures very closely unless they're on my PRs. @MSLaguana have you noticed any?

**Comment by MSLaguana** [comment]
I don't recall seeing this come up recently, but I wasn't paying much attention for the past two weeks.

**Comment by Cellule** [comment]
Since we dont know if there is any work needed and I haven't seen any failures recently either.
I will close this issue for the time being.
