### ISSUE TITLE
Bug in the javascript toExponential function

### ISSUE THREAD

**Issue by eakondratiev** [Microsoft/ChakraCore#4421]
Edge console:
5e-7.toExponential (5)

result
"4.00000e-7"

should be
"5.00000e-7"

Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

**Comment by sethbrenith** [comment]
I can repro this in Edge 41.16299.15.0 but not the latest and greatest ch.exe built on master, so I'm guessing this was already fixed.

**Comment by sethbrenith** [comment]
Maybe [this commit](https://github.com/Microsoft/ChakraCore/commit/b8fcc4b8779c994085874096b5cfb322ac858615). I'll leave this issue open for @obastemur or anyone else with more context to confirm.

**Comment by obastemur** [comment]
Yep, I had fixed this problem on release/1.8 .. master. @eakondratiev Thanks for reporting it.
