### ISSUE TITLE
ChakraCore 1.7.5 Release Package for linux missing .so file.

### ISSUE THREAD

**Issue by Oceanswave** [Microsoft/ChakraCore#4434]
The linux 1.7.5 linux release located on this page:

https://github.com/Microsoft/ChakraCore/releases/tag/v1.7.5

Seems to be missing the /lib/libChakraCore.so file which has been present on previous releases.

**Comment by obastemur** [comment]
@Oceanswave Thanks for reporting this. Fixed the package and updated SHASUM
