### ISSUE TITLE
TTD does not account for ObjectArrays in standard library functions

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4435]
This is currently only impacting the #4390

**Comment by kfarnung** [comment]
@jackhorton Is there any more detail about what issues this is causing?  It wasn't clear by looking at #4390.

**Comment by jackhorton** [comment]
It is fixed by https://github.com/Microsoft/ChakraCore/pull/4390/commits/0c738bd824dc4d1702dd36cdad67ae854db710fd, which simply hasn't made it to master yet.

**Comment by kfarnung** [comment]
Got it, thanks for clarification!
