### ISSUE TITLE
tools/compile_clang.sh  :  'makeinfo' is missing on your system.

### ISSUE THREAD

**Issue by kkrynitski** [Microsoft/ChakraCore#4437]
I've used 'compile_clang.sh' as a stand alone installer of clang 5, and have 'Warning':  
`WARNING: 'makeinfo' is missing on your system.`
and bunch of Errors similar to that: 
```
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/home/linuxdev/clang_5/cc-toolchain/src/lto_utils/binutils_compile/bfd'
make[2]: *** [install] Error 2
make[2]: Leaving directory `/home/linuxdev/clang_5/cc-toolchain/src/lto_utils/binutils_compile/bfd'
make[1]: *** [install-bfd] Error 2
make[1]: Leaving directory `/home/linuxdev/clang_5/cc-toolchain/src/lto_utils/binutils_compile'
make: *** [install] Error 2
+ '[' 2 '!=' 0 ']'
```

`sudo apt-get install texinfo` -- solved that.
 Can you please add it to script?

**Comment by obastemur** [comment]
It is already part of the script. You should  run compile_clang.sh under su/sudo

**Comment by obastemur** [comment]
Closing this for now, feel free to open it back if you think the solution is not okay.
