### ISSUE TITLE
Intl: Invalid unicode option values cause RangeErrors

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4450]
The following code throws a RangeError in Edge and simply ignores the bad value in Firefox and Chrome.

```js
new Intl.Collator("en-US-u-kf-invalid")
```

We actually have a test _expecting_ this to throw, so it might have been part of an older version of the spec. Regardless, standardizing on the 2018-compliant version of ResolveLocale introduced in #4390 fixes this.

**Comment by dilijev** [comment]
@bterlson @caridy @zbraniecki do you know if the spec changed re: expected handling for this situation?

**Comment by zbraniecki** [comment]
Why would it throw?

According to https://www.ietf.org/rfc/rfc6067.txt

```
      B.  A 'type' is a subtag with a length of three to eight
          characters following a 'key'.  (...)
```

`invalid` is a 7 char long type for key `kf`. I'm not sure why would it throw?

**Comment by jackhorton** [comment]
The WinGlob version of our implementation has... _interesting_ handling of locales before this. Basically, we used to call GetOption in a roundabout way on what we retrieved as unicode extensions.
