### ISSUE TITLE
[Clarify request] Question about support module loading in host

### ISSUE THREAD

**Issue by JohnMasen** [Microsoft/ChakraCore#4472]
hi,
I'm working on a library which porting the chakracore to dotnetcore (Chakracore.NET on Github). 
After reading the PR (https://github.com/Microsoft/ChakraCore/pull/1254), I have a question about the host implementation:

What does "1. Load top level script " mean? I'm using JsRunScript to execute the script. does the "Load" means "serialize the script"? I tried to read the C++ source., but due to lack of C++ experience, still can't confirm my assumption. 
It would be good to provide a JSRTApi call steps of how to implement the module supported hosting.
Thanks

**Comment by obastemur** [comment]
>  I'm using JsRunScript to execute the script. 

Don't. At least, not for module script source.

See https://github.com/Microsoft/ChakraCore/blob/c6026b45bb187cddf373d14abf7c2f63c9aae525/bin/ch/WScriptJsrt.cpp#L355

Important JSRT calls;
- JsInitializeModuleRecord
- JsSetModuleHostInfo
- JsParseModuleSource

**Comment by JohnMasen** [comment]
OK, I got it. seems support module requires different API to execute the script. 
Thanks obastemur.
