### ISSUE TITLE
Shadow DOM - Where are web components?

### ISSUE THREAD

**Issue by ndugger** [Microsoft/ChakraCore#4481]
I am so very sorry for this more than likely being in the wrong place, but I've reached out to various twitter accounts, commented on the shadow DOM status page, and haven't heard back from anyone.

---

As of writing, [Shadow DOM](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263785-shadow-dom-unprefixed) has 11,796 votes on [Edge's platform status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/) page. This makes it the highest voted listing on there.

MS seems to have made promises about implementing web components, but there have been **0** updates on it in over 2 years. All we know is that it's been on the backlog for two years, with no end in sight.

Can we get an official update on an ETA?

Chrome has it
Firefox is working on it, and it should land in v 59 or 60

Will MS at least commit to working on it in the near future? It feels like self sabotage so they can continue to market Angular, though this is obviously conjecture.

Since this is probably the wrong place to open this discussion, is there someone I can reach out to that is actually interested in responding who can help work out an ETA for the arrival of web components?

Again, sorry for posting this here, but I'm not having any luck anywhere else.

**Comment by bterlson** [comment]
This is not the right place. As you suspected, the [UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263785-shadow-dom-unprefixed) is the correct place for Edge Platform feedback.
