### ISSUE TITLE
Regex works incorrect in Edge

### ISSUE THREAD

**Issue by VadymMakhonin** [Microsoft/ChakraCore#4483]
`/^[\w!\$&\*\-\.\?\^\{\}~]+@[\w!\$&\*\-\.\?\^\{\}~]+\.[\w!\$&\*\-\.\?\^\{\}~]+$/.test('q@.com')`
This code returns true in Microsoft Edge 40.15063.674.0, Microsoft EdgeHTML 15.15063

Also this issue doesn’t reproduce in following versions:
Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393
Microsoft Edge 41.16299.15.0, Microsoft EdgeHTML 16.16299
Also this issues doesn't reproduce in other browsers (IE, Chrome, Firefox)

**Comment by bterlson** [comment]
Thanks for the report!

As this seems already fixed in the current version of Edge and ChakraCore, and we do not typically back-port functionality bug fixes, I am going to close this for now.
