### ISSUE TITLE
Promise subscriptions fire in reversed order inside a Worker

### ISSUE THREAD

**Issue by sorgloomer** [Microsoft/ChakraCore#451]
Hi,

Running the following code in Edge:

```
new Worker(URL.createObjectURL(new Blob([`
  var p = Promise.resolve();
  p.then(x => console.log("#1"));
  p.then(x => console.log("#2"));
`], {type: 'text/javascript'})));
```

prints:
```
#2
#1
```

I think the expected output should be `#1 #2`, according to https://promisesaplus.com/  §2.2.6.1, §2.2.6.2. Interestingly, the same experiment logs `#1 #2` when run in the main worker.

Version:
```
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586
```

Best regards

**Comment by DigiTec** [comment]
Wow great find! We knew that our timer implementation of Promises was bad, but I never found a use case where it actually reordered promises. Thank you so much for this report!

That said, we've recently upgraded our Promises to a micro-task checkpoint model similar to other browsers. Running your test case on unreleased bits I'm able to see that we've definitely fixed this issue and we get the expected output.

I've gone ahead and shared your findings and information on our upcoming fixes here https://twitter.com/JustRogDigiTec/status/706893585711411200

**Comment by DigiTec** [comment]
Closing. The fix for this issue will be in a future build of Edge.

**Comment by sorgloomer** [comment]
Awesome, thanks!
