### ISSUE TITLE
Getting unable to load chakra core.dll error while running hello world sample

### ISSUE THREAD

**Issue by AkibSiddiqui** [Microsoft/ChakraCore#4510]
I am trying to run chakra core c# sample provided here(https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore#before-you-start) but getting error :

![chakracore](https://user-images.githubusercontent.com/19324983/34661126-7d7330a2-f46d-11e7-920d-b74530185a0f.png)

I tried to install this also but getting error with it :
`Install-Package JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64 -Version 2.4.6` 

![chakracore1](https://user-images.githubusercontent.com/19324983/34661160-c7ab5ed8-f46d-11e7-90d6-03c172eb5186.png)

As per my understanding if i want to use chakracore in my project(console app or web application) then i only need chakra core.dll but still i am getting error that chakra core dll not found.

I have tried in visual studio 2015 and 2017 on window 7 but same problem.

How run run sample application which should display hello world in console application execcuting javascript code?

**Comment by jackhorton** [comment]
This seems like a general build system issue in your project. Just to confirm, you have a ChakraCore.dll file in the same folder as your output executable, correct?

**Comment by AkibSiddiqui** [comment]
I have added chakra core dll with nuget package also but the project didnt run with it.

I also added chakra core dll like this:https://i.stack.imgur.com/19JhE.png

Now when i try to reference chakracore dll from visual studio with "Add new reference" it is not allowing me to add chakracore dll.

I am really not getting whats the problem with the sample project which is there on the official website and why it is not running.

**Comment by liminzhu** [comment]
Hey @AkibSiddiqui , as @jackhorton suggested, did you make sure the .dll sits in the same folder as the built executable? The dir you had doesn't seem to have the built HelloWorld.exe.  Let's say you make a x64 Debug build, it should be in '/HelloWorld/bin/x64/Debug/'.

**Comment by AkibSiddiqui** [comment]
@liminzhu @jackhorton  Can you please send me the link to download sample hello world project of chakra core for c# which is runnable ?

As because the project which i downloaded from here doesnt seems to working:https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore#before-you-start


What are the pre-requisites that are needed in order to run sample hello world c# project?

As far as i know only chakracore.dll is need but is `JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64` needed?

What other things are needed for chakracore.dll?
