### ISSUE TITLE
clang-6.0 build error

### ISSUE THREAD

**Issue by sucof** [Microsoft/ChakraCore#4524]
Hi, all guys, When I use clang6.0 to build chakracore, there are some mistakes as below:

> chakra/pal/src/shmemory/shmemory.cpp:946:16: error: result of comparison of unsigned enum expression < 0 is always false [-Werror,-Wtautological-unsigned-enum-zero-compare]
>     if(element < 0 || element >= SIID_LAST)

my build command is like this:
`./build.sh --test-build --static --embed-icu --cc="$(which clang)" --cxx="$(which clang++)" -j -v -y`

Who knows which version of clang is the official used?

**Comment by obastemur** [comment]
@sucof master / release1.8 branches are tested with up to clang5.0. I’m looking at this one now

**Comment by sucof** [comment]
@obastemur Thanks your replay, clang3.9 is fine, and I will try clang5.0.

**Comment by obastemur** [comment]
@sucof Thanks for opening this issue. I would wait for llvm 6.0 to be final. (somewhere around mid February). ChakraCore is compatible with all the `current` clang release versions.
