### ISSUE TITLE
Crash: nullptr access in VALIDATE_INCOMING_REFERENCE

### ISSUE THREAD

**Issue by mihe** [Microsoft/ChakraCore#4532]
I'm currently embedding ChakraCore (tried both `release/1.7` and `release/1.8`) into my Windows-based application.

Sometimes (completely randomly it seems) when I call `JsCallFunction` I get a crash on one of the calls to [`VALIDATE_INCOMING_REFERENCE`](https://github.com/Microsoft/ChakraCore/blob/ebd118a65df11bb6f5ea52b9012012d02d4245cd/lib/Jsrt/Jsrt.cpp#L2732). More specifically it seems to be `JsrtContext::javascriptLibrary` being `nullptr` when calling `JsrtContext::GetScriptContext()` in the [`MARSHAL_OBJECT`](https://github.com/Microsoft/ChakraCore/blob/76373f24141ee66bc5e9e4ff131f097f96542a95/lib/Jsrt/JsrtInternal.h#L42) macro.

As far as I can tell there's no specific event that leads up to this. Sometimes I can call `JsCallFunction` with the same arguments hundreds of thousands of times with no issue, and sometimes it crashes almost instantly. I'm not really seeing any patterns in the amount of calls made or general workload.

I've compiled both the Release and Debug versions of ChakraCore (using the bundled `Build/Chakra.Core.sln`, without changing any build flags or anything), but was never able to reproduce this issue with the Debug build sadly.

I should maybe note that I use the `JsRuntimeAttributeEnableIdleProcessing` and `JsRuntimeAttributeDisableBackgroundWork` flags on my context. I've tried playing with various combinations of these, including removing them altogether, but I seem to get the error in any sort of configuration.

Any wild guess or hint as to what could cause that `javascriptLibrary` variable to ever become `nullptr` would be appreciated.

**Comment by MSLaguana** [comment]
If it's possible for you to get a crash dump, that can help narrow down exactly what is happening.

My first thought is that you might be providing bogus arguments (if you provide an argument which is not a tagged number we assume it must be one of our own internal types, but if it isn't then we'll be accessing the wrong memory which is likely to crash), but you say that you can provide the same arguments and have it work (presumably with correct results, and not simply not crashing?) for a while, and then crash?

Another thought I had was if you were trying to access script in a multithreaded way, but I don't think that would crash in this particular way.

**Comment by mihe** [comment]
To the best of my knowledge we are not accessing ChakraCore in a multi-threaded way, no.

[Here](https://github.com/Microsoft/ChakraCore/files/1625261/Crash_JsCallFunction.zip) is one of the crash dumps plus the appropriate ChakraCore DLL and PDB. Unfortunately it's a pretty barebones minidump from an optimized build, so I'm not sure how much use it will be to you.

Regarding the bogus argument, that was my initial reaction when I saw the crash site, so I tried looking at the argument creation, and I couldn't see any really apparent errors in the way I was creating these arguments.

Would this crash be expected if say the JS function that I'm invoking expects a number and I instead pass in an object, or are we purely talking about the arguments to `JsCallFunction` receiving a `JsValueRef` pointing to bogus memory?

**Comment by MSLaguana** [comment]
I had a look at the crash dump, but unfortunately it's missing the memory that contains the bad variable.

I can tell that it is failing to validate the argument at index 2 (so the second function argument, considering that `this` is at index 0), and as you state above it is trying to get the scriptContext off the `javascriptLibrary` when the `javascriptLibrary` is null. Specifically, the `javascriptLibrary` on the object's `Type` is null, which should only happen if the type was created when the scriptContext had no library.

What kind of parameter are you passing as this argument?

Are you ever calling `JsDisposeRuntime`?

The other thing I noticed is that there are a lot of threads that exist in the dump, it might be worth adding some logging to your code to see whether you do ever access chakracore from multiple different threads.

**Comment by agarwal-sandeep** [comment]
Is the function get collected? Trying calling JsAddRef on the function after you create it to make sure it is not collected.

**Comment by MSLaguana** [comment]
@agarwal-sandeep it's not the function that is causing the crash here, it's during validation of the passed-in arguments at the JSRT level.

**Comment by digitalinfinity** [comment]
@mihe to echo @MSLaguana the dump collected doesn't have all of the memory needed to debug your issue. Can you share a full process dump please? If you're using windbg to collect the dump, try using the `/ma` flag ([procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) has the same flag)

**Comment by mihe** [comment]
First of all thanks for the replies.

@digitalinfinity Unfortunately I'm not getting the dump from a debugging session, but rather from the Win32 `MiniDumpWriteDump` API. The error has been near impossible to reliably reproduce, so I had to rely on a minidump produced on a non-dev environment. I'll see about changing the flags there to give me a more comprehensive dump.

@MSLaguana I unfortunately don't know what the argument at index 2 was in that particular minidump. At best I can narrow it down to being a value created by `JsPointerToString`, `JsBoolToBoolean`, `JsDoubleToNumber` or `JsCreateExternalObject`. Again, I'll see if I can get some better data surrounding the crash.

Regarding `JsDisposeRuntime`, I don't ever call it no. I do however have multiple (3-4) contexts alive at the same time, with some being released and new ones created throughout the programs lifetime.

**Comment by mihe** [comment]
Closing this as we've now moved over to V8 instead.
