### ISSUE TITLE
osx: enable MathBuiltinsCall.js

### ISSUE THREAD

**Issue by MikeHolman** [Microsoft/ChakraCore#4537]
Not sure how much we care, but for example, `Math.atan(10)` is `1.4711276743037344` on OSX. On other platforms it equals `1.4711276743037347`.

Opened as result of test failure in #4531

**Comment by obastemur** [comment]
some tips;

Test: https://github.com/Microsoft/ChakraCore/blob/master/test/AsmJs/MathBuiltinsCall.js

The test file looks useful for testing math builtins and we may compare `atan` result per platform if it's necessary: 

`var isMac = (WScript.Platform && WScript.Platform.OS == 'darwin');`

The line above is to check if the host OS is a mac.
