### ISSUE TITLE
Factor ENABLE_CUSTOM_ENTROPY/Entropy.cpp out into PlatformAgnostic

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4563]
Ran into this while doing ICU build system work. This seems like a great use case for being a PlatformAgnostic API defined per-platform.

**Comment by jackhorton** [comment]
Looking into this slightly more, I am not entirely convinced we need this at all anymore?

**Comment by obastemur** [comment]
Previously discussed. See https://github.com/Microsoft/ChakraCore/pull/1174#issuecomment-244280521
