### ISSUE TITLE
Update build configs (legacy -> dev14)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#4566]
/cc @Penguinwizzard @MSLaguana @boingoing

Context: we removed legacy builds on **Server 2008 R2 + Dev12** instead of updating the legacy build config to something more modern. Currently branches **release/1.8, release/1.9, master** do not have legacy builds.

See #2552 (superceded by #3855)

TODO CI Build Configuration Updates:

* [ ] Modern = Dev15 on Server 2016 (~= Windows 10)
* [ ] Legacy = Dev14 on Server 2008 R2 (~= Windows 7)

With those changes, the following OS would not be covered by Jenkins:

* Server 2012 R2 (~= Windows 8.1)

To cover the above, it might make sense to add one of these in-between sanity-check build:

* Dev14 on Server 2012 R2
  * Note: without the above changes this is the "modern" configuration covered by the current VSO CI build configuration (/cc @MSLaguana @boingoing)
* Dev15 on Server 2012 R2

Follow-up tasks:

* [ ] Update Build Status wiki pages
* [ ] Update other documentation referencing CI build configurations

Will follow up with notes on the migration.

FYI @mmitche - We're planning to migrate to Server 2016 soon. Let us know if there are any capacity concerns on the various servers we use for CI (master on ci.dot.net and most other branches on ci2.dot.net)

**Comment by jackhorton** [comment]
This is done, no?

**Comment by dilijev** [comment]
Yep, thanks.
