### ISSUE TITLE
Re-implement numbers in JS to be like numbers in Python

### ISSUE THREAD

**Issue by kapv89** [Microsoft/ChakraCore#4573]
JS is fast, and the business value of writing one language across the stack is hard to ignore. Its async nature and concurrency primitives(like `async`/`await`, and `Promise`) also make it attractive for writing IO intensive applications. And its functional primitives(`map`, `filter`, `reduce`, `slice`), and features like object, array destructuring, make it a very good fit for data-intensive applications.

One thing that JS lacks which can be a big hindrance for medium-to-large-businesses thinking of investing heavily in JS for their server-side-software is the lack of proper numbers.

Because of the way numbers are implemented in JS, if a number grows beyond certain digits, JS loses information about it. Shown in the image below:
![screenshot from 2018-01-18 22-22-22](https://user-images.githubusercontent.com/1023032/35111091-69e0e7d8-fca0-11e7-86b6-594e46de6671.png)

This sort of information loss will be very unattractive for companies that need to deal with critical numbers which are more than 21 digits big.

On the other hand, take a look at the example shown below from the language python:
![screenshot from 2018-01-18 22-49-54](https://user-images.githubusercontent.com/1023032/35111731-efdf1746-fca1-11e7-87f3-3a745b41ed59.png)

All the information about both numbers shown in the above example remains preserved.

I suspect that the problem I am attempting to identify in this post is the reason for lack of an industry-standard open-source infrastructure for data science in JS. And that this is a big reason for why JS has not revolutionised server programming the same way it has revolutionised UI programming.

By creating this issue, I am trying to put this hypothesis in front of people who have the skills to do something about the problem detailed in this issue.

Thanks.

**Comment by mathiasbynens** [comment]
You might be interested in [the `BigInt` proposal](https://github.com/tc39/proposal-bigint).

**Comment by kapv89** [comment]
@mathiasbynens that looks interesting, thanks. Closing this issue.
