### ISSUE TITLE
Way to create JsEnhancedNativeFunction with name

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#4587]
My current code uses JsCreateNamedFunction to create native functions with names.  I would like to use JsCreateEnhancedFunction in order to take advantage of the `new.target` binding, however there doesn't seem to be a way to give these names.  Is there a way to do this?

**Comment by liminzhu** [comment]
Use `metadata` for names. https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L139

**Comment by fatcerberus** [comment]
Thanks, didn’t see that.

Seems to be an odd naming choice, if the metadata is only used for the name of the function (and must be a string), why isn’t it just called “name”?  Mostly I use intellisense for documentation when developing so the parameter names are the only thing I see 99% of the time.

**Comment by liminzhu** [comment]
@boingoing any idea?

**Comment by jackhorton** [comment]
The comment on the PR was that that param may change in the future to be an object containing a name key in addition to other keys. I wasn't a huge fan of that decision either, for what its worth -- I would have preferred making it an object from day one that only contains a single important key for now.

**Comment by fatcerberus** [comment]
I'll close this as the question was answered satisfactorily, passing the name string as `metadata` works as expected.  Thanks guys! 😺
