### ISSUE TITLE
Process abort when handling OOM exception

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#4597]
We run following code in ch-release 1.9.0.0. The ch process will abort.
```
var x=("\u2604").repeat(32 * 1024 * 1024);
var z="haha";
for(;;) {
	z += x;
}
```
Output:
Aborted (core dumped)

ICT BT group
2018.1.24

**Comment by sethbrenith** [comment]
Seems like a reasonable behavior to me. What were you expecting to see?

**Comment by MSLaguana** [comment]
To clarify a little: If we OOM we now intentionally abort the process for security reasons. This is a change compared to some previous versions of chakracore, but it is a deliberate one.

**Comment by akroshg** [comment]
This is by-design, although if you are building your own JSRT application you can provide flag ```JsRuntimeAttributeDisableFatalOnOOM``` to disable fatal error.

**Comment by akroshg** [comment]
Closing this as by-design.
