### ISSUE TITLE
Is there any document about the meaning of bytecode?

### ISSUE THREAD

**Issue by zhangxffff** [Microsoft/ChakraCore#4605]
I'm doing a project on the ChakraCore. However, I can't figure out the bytecode format and its meaning. Is there some detailed specification about bytecode?

**Comment by pleath** [comment]
@zhangxffff , I'm afraid the code itself is the only bytecode spec at the moment. There are a number of different formats, all of them described in core\lib\Runtime\ByteCode\OpLayouts.h. OpCodes.h lists the opcodes and indicates which layout is employed by each opcode. Let me know if you'd like more detail or a simple example of how a particular byte code works. And thanks for your interest in the project.
