### ISSUE TITLE
Feature request: Make it easier for embedders to debug their scripts

### ISSUE THREAD

**Issue by digitalinfinity** [Microsoft/ChakraCore#4616]
Today, unlike the experience in Chakra.dll, embedders of ChakraCore cannot debug the scripts they run easily. While ChakraCore has a rich JSRT API for debugging, not all embedders want to write their own debugger. This issue is to track a feature request to provide a companion library to ChakraCore that embedders can link to for a default debugger implementation.

**Comment by kfarnung** [comment]
I've uploaded an initial draft for review: https://github.com/kfarnung/ChakraCore/blob/debug-doc/doc/debug-companion.md

Feel free to leave any comments here and I'll incorporate them into the document.

**Comment by dilijev** [comment]
I'd recommend opening a pull request (on your fork) from that branch to some other branch, so that comments can be added as code review comments.

> This feature aims to provide an end-to-end flor for debugging a ChakraCore-embedded application VS Code.

* `flor` looks like a typo?

* Maybe add figure numbers so you can reference things in the diagrams unambiguously from the text.

**Comment by kfarnung** [comment]
Thanks @dilijev!  As requested:  https://github.com/kfarnung/ChakraCore/pull/2

**Comment by pallammadhukar** [comment]
Is this feature available today?

**Comment by MSLaguana** [comment]
It is in development at https://github.com/Microsoft/ChakraCore-Debugger, but you are welcome to try it out.

**Comment by MSLaguana** [comment]
I just noticed that I was somewhat premature; it is still private for now, but we are working on taking it public. Apologies for any confusion!

**Comment by pallammadhukar** [comment]
Thank you. When is the tentative Plan for Public.

**Comment by kfarnung** [comment]
It's now public, but currently Windows-only at this point.  Getting it cross-platform is on the backlog.

https://github.com/Microsoft/ChakraCore-Debugger
