### ISSUE TITLE
when calling a native function associated to an object, an object is always passed as first parameter

### ISSUE THREAD

**Issue by lemmel** [Microsoft/ChakraCore#4669]
Hi.

#### First a bit of context, totally useless but maybe interesting for the reader.
I'm progressing slowly but surely (don't have a lot of time) migrating an application from QWebEgine to ChakraCore.
I'm currently making a bridge between Qt's QObject and CharkaCore, and I need to be able to give access from the JS side to Qt's objects.
For doing so I register an object through [JsCreateObject](https://github.com/Microsoft/ChakraCore/wiki/JsCreateObject), and add a function to this object with [JsCreateFunction](https://github.com/Microsoft/ChakraCore/wiki/JsCreateFunction) and [JsSetProperty](https://github.com/Microsoft/ChakraCore/wiki/JsSetProperty).

#### Now my problem/question

When my function is called (keep in mind that this function is associated to a JS Object), it received always an object as first parameter, even though this function is called without any parameter given.

As explanation/example:
- when I called:
  ``` js
  myObject.myFunction();
  ```
- my function received a parameter:
   ``` cpp
   JsValueRef myFunction(JsValueRef, bool, JsValueRef *, unsigned short argumentCount, void *)
  ```
  argumentCount is equal to 1

So : what is this object ? Is there something that I'm doing wrongly ?
P.S.: I'm under linux, using ChakraCore (git log) : 
    commit e20d5c67e47bf26f3f677b50e2823fc0e2eeb190 (HEAD -> release/1.7, origin/release/1.7)
and tested (with the same result) :
    commit 3f7691187ba02ab2a1079619fed867714786b693 (HEAD -> master, origin/master, origin/HEAD)
P.P.S. : Here is a full source code that can be used to check my explanation, or for the curious ones.

``` cpp
#include "ChakraCore.h"
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <cstring>
#define MAX 255
class ErrorCode // Just a helper for error management; you can ignore this
{
  JsErrorCode errCode;
public:
  ErrorCode():errCode(JsNoError){}
  ErrorCode(JsErrorCode errCode):errCode(errCode){}
#define EXCEPTION_MAX_LENGTH 255
  ErrorCode& operator=(JsErrorCode errorCode)
  {
    this->errCode = errorCode;
    if (errorCode == JsNoError)
      return *this;

    char buffer [EXCEPTION_MAX_LENGTH + 1];
    size_t actualLength;
    JsErrorCode error;

    JsValueRef exception;
    if ((error = JsGetAndClearException(&exception)) != JsNoError)
    {
      printf("Error on Error! Original error code=%d, new error code=%d\n", errorCode, error);
      return *this;
    }
    JsPropertyIdRef messageName;
    if ((error = JsCreatePropertyId("message", strlen("message"), &messageName)) != JsNoError)
    {
      printf("Error on Error! Original error code=%d, new error code=%d\n", errorCode, error);
      return *this;
    }
    JsValueRef messageValue;
    if ((error = JsGetProperty(exception, messageName, &messageValue)) != JsNoError)
    {
      printf("Error on Error! Original error code=%d, new error code=%d\n", errorCode, error);
      return *this;
    }
    if ((error = JsCopyString(messageValue, buffer, EXCEPTION_MAX_LENGTH, &actualLength)) != JsNoError)
    {
      printf("Error on Error! Original error code=%d, new error code=%d\n", errorCode, error);
      return *this;
    }
    buffer[actualLength] = 0;

    printf("Error: %s\n", buffer);
    exit(EXIT_FAILURE);
    return *this;
  }
};
JsErrorCode JsGetPropertyIdFromName(const char* string, size_t stringLen, JsPropertyIdRef *propertyId)
{
  return JsCreatePropertyId(
        string,
        stringLen,
        propertyId);
}
JsErrorCode registerFunction(JsValueRef hostObject, const char *callbackName, const size_t &length, JsNativeFunction callback, void *callbackState)
{
    JsErrorCode error;
    JsPropertyIdRef propertyId;
    JsValueRef function;
    if ((error = JsCreatePropertyId(callbackName, length,&propertyId)) != JsNoError) return error;
    if ((error = JsCreateFunction(callback, callbackState, &function)) != JsNoError) return error;
    if ((error = JsSetProperty(hostObject, propertyId, function, true)) != JsNoError) return error;
    return JsNoError;
}
JsValueRef theCaller(JsValueRef callee, bool isConstructCall, JsValueRef *arguments, unsigned short argumentCount, void *callbackState)
{
  bool ok;
  printf("====> argumentCount=%d\n", argumentCount);
  return JS_INVALID_REFERENCE;
}
int main()
{
  JsRuntimeHandle runtime;
  JsValueRef globalObject;
  JsContextRef context;
  ErrorCode errCode     = JsNoError;
  errCode = JsCreateRuntime(JsRuntimeAttributeNone, nullptr, &runtime);
  errCode = JsCreateContext(runtime, &context);
  errCode = JsSetCurrentContext(context);
  errCode = JsGetGlobalObject(&globalObject);

  /*
   Now I want to create my "very own object": Toto !
   class Toto
   {
     public:
     void toto();
   };
  */
  JsValueRef object;//The instance of an object Toto
  JsPropertyIdRef objectPropertyId;
  errCode = JsCreateObject(&object);
  errCode = JsGetPropertyIdFromName("Toto", 4, &objectPropertyId);
  errCode = JsSetProperty(globalObject, objectPropertyId, object, true);
  errCode = registerFunction(object, "toto", 4, theCaller, nullptr);

  //Now to the JS code

  static unsigned currentSourceContext = 0;
  JsValueRef result;
  JsValueRef fname;
  errCode = JsCreateString("", 0, &fname);

  JsValueRef scriptSource;
  char jscode[] = "Toto.toto(5);";
  errCode = JsCreateString(jscode, strlen(jscode), &scriptSource);
  errCode = JsRun(scriptSource, currentSourceContext++, fname, JsParseScriptAttributeNone, &result);

  return 0;
}
```

**Comment by MSLaguana** [comment]
JavaScript functions always have a `this` parameter, so when you invoke `myObject.myFunction()`, the native function is passed a reference to `myObject` to be used as `this`.

If you build ChakraCore from the release/1.9 branch or master, then you can also use the new "enhanced" native functions which have additional metadata: https://github.com/Microsoft/ChakraCore/blob/607e4e15f1469ba18958d73d7447e1eea447307f/lib/Jsrt/ChakraCore.h#L131 and in particular https://github.com/Microsoft/ChakraCore/blob/607e4e15f1469ba18958d73d7447e1eea447307f/lib/Jsrt/ChakraCore.h#L111-L116
This way you can explicitly access the `this` parameter, but it will also still be the first argument in the list as well.

**Comment by lemmel** [comment]
I thought so and added some printf (e.g. ```printf("===>%ld", (long)objectPropertyId); ```), but I didn't get the same adresses, so I figured it out that there was something else/more.

Ok thanks for the answer.

I corrected my code (remove some Qt's specifics) so the question and the provided code will be usefull for other people :D
