### ISSUE TITLE
Add a check for non-ASCII characters/bytes in C++ source code

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#4672]
This has caused issues when compiling ChakraCore on certain non-English locales in the past.

See https://github.com/Microsoft/ChakraCore/pull/4668#discussion_r167734493

**Comment by obastemur** [comment]
duplicate ? https://github.com/Microsoft/ChakraCore/issues/4268

**Comment by dilijev** [comment]
Yes, thanks.
