### ISSUE TITLE
How Can I Store Some C# Object Data on a Function Instance

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/ChakraCore#4679]
I am trying to store some binary data for other callers of the function but i cant see how this can be done. I have tried CreateExternalObject and Get/SetExternalData but i just get exceptions. I am using the Hosting code, but it just calls into native calls.

What I am trying to emulate is a set of image manipulation functions on an object/class/function like, so when i construct my Image object i stream an image and then i can perform other operations on that image data before i save and close it:

```
var img = new Image( filepath );
img.quality = 100;
img.resize(1000,500);
img.save(newfilepath);
img.close();
```

This is what i have tried so far:
```
DefineFunctionCallback( globalObject, "Image", ImageDelegate, IntPtr.Zero );

var delegateFuncId = globalObject.GetProperty( JavaScriptPropertyId.FromString( "ImageDelegate" ) );
DefineFunctionCallback( delegateFuncId, "save", SaveDelegate, IntPtr.Zero );


public static JavaScriptValue ImageDelegate( JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData )
{
    // First argument is the function name, so start looking at arguments from index 1...
    if( argumentCount < 1 )
    {
        ChakraScriptRunner.ThrowJavascriptException( "Invalid number of arguments to ImageDelegate( info )" );
        return JavaScriptValue.Invalid;
    }

    try
    {
        var info = arguments[ 1 ].ConvertToString().ToString();

        var obj = new MyImageObject( info );
        var objHandle = GCHandle.Alloc( obj );

		// This throws and InvalidArgument Exception
        callee.ExternalData = (IntPtr)objHandle;


		// This works but i cant get the data back out from 'save' function
        JavaScriptValue val = ChakraScriptHelpers.CreateExternalObject( (IntPtr)objHandle, PawaImageFinalizeCallback );
        callee.SetProperty( JavaScriptPropertyId.FromString( "imageData" ), val, true );


        return callee;
    }
    catch( Exception ex )
    {
        // we must catch normal exceptions and throw them as JS ones when in delegates otherwise we get issues further downstream
        ChakraScriptRunner.ThrowJavascriptException( ex.Message );
        return JavaScriptValue.Invalid;
    }
}



public static JavaScriptValue SaveDelegate( JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData )
{
    try
    {
		// infoPtr is always Zero
        IntPtr infoPtr = callee.HasExternalData ? callee.ExternalData : IntPtr.Zero;
        if( infoPtr != IntPtr.Zero )
        {
            var imageHandle = (GCHandle)infoPtr;
            var image = ( imageHandle.Target as MyImageObject );
        }

        JavaScriptValue imageVal = callee.GetProperty( JavaScriptPropertyId.FromString( "imageData" ) );
        IntPtr imagePtr2 = ChakraScriptHelpers.GetExternalData( imageVal );
		// imagePtr2 is also Zero
        if( imagePtr2 != IntPtr.Zero )
        {
            var imageHandle = (GCHandle)imagePtr2;
            var image = ( imageHandle.Target as MyImageObject );
        }



        return callee;
    }
    catch( Exception ex )
    {
        // we must catch normal exceptions and throw them as JS ones when in delegates otherwise we get issues further downstream
        ChakraScriptRunner.ThrowJavascriptException( ex.Message );
        return JavaScriptValue.Invalid;
    }
}
```

**Comment by MSLaguana** [comment]
Could you please point out how you are using ChakraCore? Have you done your own C# to native bindings, or are you using a library? I'm not familiar with one that has `ChakraScriptHelpers`.

**Comment by coderangerdan** [comment]
Sorry, I am using the hosting code which i have modified/extended from the [ChakraSamples](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/JSRT%20Hosting%20Samples/C%23)

**Comment by MSLaguana** [comment]
I'm not so familiar with the c# binding side of things, but I believe I see part of the problem.

First, the `callee` property that you are using is actually a reference to the function object, e.g. `Image` or `Image.prototype.save`. You probably want to be modifying the `this` parameter (which is the first argument passed in) so you can have per-instance data.

Secondly, you are assigning your external data as a property of an object, roughly equivalent to `foo.imageData = externalObject`, but in `SaveDelegate` you are checking the object itself, not the thing you set as the property (e.g. you are checking if `foo` is an external, not `foo.imageData`).

Since the external objects that we create are actually javascript objects (with some additional hidden state), you probably want your `ImageDelegate` function to create a new external object with your `MyImageObject` as its data, and then set the prototype on that external object to be the prototype of the callee. Essentially manually creating an instance of the `Image` class by doing `var o = {/*external data */}; Object.setPrototypeOf(o, Image.prototype); return o;`. Then in `SaveDelgate` the `this` object will be/have ExternalData (if it was constructed by your function and nobody did `Image.prototype.save.call(somethingElse)`) and you can get access to your `MyObjectData` and go from there.

**Comment by liminzhu** [comment]
[Here](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#expose-native-functionsobjects-to-javascript) is C++ example which you can easily translate to C#. As @MSLaguana pointed out, the main problem is in

 > ```IntPtr infoPtr = callee.HasExternalData ? callee.ExternalData : IntPtr.Zero;```

`callee` is the function (your delegates) being called, you want get/set external data on `arguments[0]` which is `this` and your image instance.

**Comment by coderangerdan** [comment]
Thanks a lot guys, using your info and quite a bit of tinkering, I have some progress now;
a) I had to set my Save delegate onto my 'this' instance and not globally
b) I have to create my external object and set it onto a new property on 'this'

However, calling `thisValue.ExternalData` always throws an 'InvalidArgument' exception so i cannot use that, instead i have to (b) set it onto a property which is a bit nasty as its not an object which should be manipulable from within Javascript so i didn't really want it accessible.

Any ideas, why `thisValue.ExternalData` always fails; my calling JS code is now (where echo, writes out to debugger window):
```javascript
var img = new Image( 'd:\\myfilepathvalue.jpg' );
echo( 'filepath = ' + img.filePath );
img.save(newfilepath);
```

My delegates are now:
```c#
public static readonly JavaScriptNativeFunction ImageDelegate = MyImageFunc;
public static readonly JavaScriptNativeFunction SaveDelegate = MySaveFunc;

public static JavaScriptValue MyImageFunc( JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData )
{
    // First argument is the function name, so start looking at arguments from index 1...
    if( argumentCount < 1 )
    {
        ChakraScriptRunner.ThrowJavascriptException( "Invalid number of arguments to ImageDelegate( info )" );
        return JavaScriptValue.Invalid;
    }

    try
    {
        var info = arguments[ 1 ].ConvertToString().ToString();

        var obj = new MyImageObject( info );
        var objHandle = GCHandle.Alloc( obj );

        JavaScriptValue thisValue = arguments[ 0 ];

        // ERROR: This throws an InvalidArgument Exception
        thisValue.ExternalData = (IntPtr)objHandle;

        // This works but it means 'imageData' is now accessible from within JS which is okay, but not ideal
        JavaScriptValue val = ChakraScriptHelpers.CreateExternalObject( (IntPtr)objHandle, ImageFinalizeCallback );
        thisValue.SetProperty( JavaScriptPropertyId.FromString( "imageData" ), val, true );

        // Following now allows me access to 'save' from this instance
        DefineFunctionCallback( thisValue, "save", SaveDelegate, IntPtr.Zero );

        return thisValue;
    }
    catch( Exception ex )
    {
        // we must catch normal exceptions and throw them as JS ones when in delegates otherwise we get issues further downstream
        ChakraScriptRunner.ThrowJavascriptException( ex.Message );
        return JavaScriptValue.Invalid;
    }
}

public static JavaScriptValue MySaveFunc( JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData )
{
    try
    {
        JavaScriptValue thisValue = arguments[ 0 ];
        var relativeSavePath = arguments[ 1 ].ConvertToString().ToString();

        JavaScriptValue filePathVal = thisValue.GetProperty( JavaScriptPropertyId.FromString( "filePath" ) );

        // This now writes out the correct value set in ImageDelegate
        Debug.WriteLine( $"Saving image: from: {filePathVal.ConvertToString().ToString() }" ); 

        // ERROR: infoPtr is always Zero
        IntPtr infoPtr = thisValue .HasExternalData ? thisValue .ExternalData : IntPtr.Zero;
        if( infoPtr != IntPtr.Zero )
        {
            // never gets here
            var imageHandle = (GCHandle)infoPtr;
            var image = ( imageHandle.Target as MyImageObject );
        }

        // this works
        JavaScriptValue imageVal = thisValue.GetProperty( JavaScriptPropertyId.FromString( "imageData" ) );
        IntPtr imagePtr2 = ChakraScriptHelpers.GetExternalData( imageVal );
        if( imagePtr2 != IntPtr.Zero )
        {
            var imageHandle = (GCHandle)imagePtr2;
            var image = ( imageHandle.Target as MyImageObject );

            Debug.WriteLine( $"Saving image {image.FileName} to {relativeSavePath}" );
        }

        return JavaScriptValue.Invalid;
    }
    catch( Exception ex )
    {
        // we must catch normal exceptions and throw them as JS ones when in delegates otherwise we get issues further downstream
        ChakraScriptRunner.ThrowJavascriptException( ex.Message );
        return JavaScriptValue.Invalid;
    }
}
```

**Comment by liminzhu** [comment]
Is `MyImageFunc` the `image` constructor? In that case, `this` would be whatever enclosing scope where the constructor is called, and you wouldn't be able to get external data off it since it's not a external object. 

What you probably want to do within the constructor is to create an external object, attach your native handle to the extObj, and return the extObj. Then in `MySaveFunc`, since this is called as `img.save(...)`, `img` would be `this` and your `args[0].externalData` should be the handle you attached before.

**Comment by coderangerdan** [comment]
I need to return `this` from the `MyImageFunc` otherwise I cant access any functions off the instance like `save` or `close`. So I cant return the extObj; or have I misunderstood?

**Comment by liminzhu** [comment]
If you're returning `this` from the constructor, then `new image(...)` basically also returns `this` in JS instead of an actual instance.

Consider putting methods on the prototype, like this (pseudocode)

```cpp
JsCreateObject(&imgProto);

// your constructor
MyImageFunc(...) 
{
  ...
  JsCreateExternalObjectWithPrototype(nativeHandle, nullptr, imgProto, &extObj);
  return extObj;
}

// your save function
MySaveFunc(...) {}

// attach Image to global object
setCallback(globalObj, "Image", MyImageFunc);
// same as Image.prototype.save = MySaveFunc in JS
setCallback(imgProto, "save", MySaveFunc); 
```

**Comment by coderangerdan** [comment]
Doesn't look like JsCreateExternalObjectWithPrototype is available to me:
`Unable to find an entry point named 'JsCreateExternalObjectWithPrototype' in DLL 'ChakraCore.dll'.`

**Comment by liminzhu** [comment]
It should be available in the latest release, alternatively, you can call `JsSetPrototype` after the creating the object as well.

**Comment by coderangerdan** [comment]
Cool, that works perfectly and is a much tidier implementation. Thanks guys!
