### ISSUE TITLE
RegEx Look Ahead/Behind Not Supported

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/ChakraCore#4687]
I couldn't find anywhere that this was a known issue, but regex look ahead/behind is not supported. But it is in Chrome which caused me some headaches :-)

This gives an 'Unexpected quantifier' error (taken from a [SO answer](https://stackoverflow.com/a/15099212/1478) to find single digits):
`var reSingleDigits = /(?<!\S)\d(?![^\s.,?!])/;`

**Comment by MSLaguana** [comment]
Regex lookahead should work; if I do `/a(?=b)/.exec("acab")` then I get a match pointing to index 2, meaning it matched the `ab` and not the `ac`. We don't currently support lookbehind, which has only recently been accepted into the ES2018 spec.

**Comment by rhuanjl** [comment]
There's a separate issue for implementing look behind: https://github.com/Microsoft/ChakraCore/issues/3448

**Comment by coderangerdan** [comment]
Thank you, my error not finding the other issue
