### ISSUE TITLE
Add JSRT API to get default built-ins regardless of changes a script makes.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#4690]
From https://github.com/Microsoft/ChakraCore/issues/3575

> I think a lot of integrators would like to get the default "built-ins" before the script mess with it on the global.

**Comment by MSLaguana** [comment]
Currently the way we handle this in node-chakracore is that we run a script early on to grab references to all the built-ins that we care about. That way it's fairly simple to change exactly what builtins we care about (do you care about `Symbol`? `Object.keys`? `Array.prototype.map`? doesn't matter how deep the property is, if it's accessible via script it can be cached) without needing to hard-code a list of builtins as part of the API.

I worry that if we provide some kind of `JsGetOriginalBuiltIn(JsBuiltInEnum which, JsValueRef *result)` then it will either become out of date with new ES features, or require a fair bit of churn.

**Comment by liminzhu** [comment]
Do we have (or can we implement) the ability to instantiate a single builtin? If not, this could be a very expensive API to call and you're trading perf for convenience v.s. what @MSLaguana said we do for node-ch. I'm not super worried about being out of date with new ES features though since we can ask for a JsValueRef or native string representing the path to the builtin (e.g. `JsGetOriginalBuiltIn('Object.create', &res)`, kinda like `JsRunScript`).

Somewhat related - v8 does this pretty neat thing that they [delay-instantiate built-ins till called](https://v8project.blogspot.com/2018/02/lazy-deserialization.html). If we don't already do this and it's easy to implement with our architecture, maybe we should do something similar provided its protected benefit is backed our data.

**Comment by dilijev** [comment]
Now that you mention it, `JsGetOriginalBuiltIn('Object.create', &res)` would probably not provide much value over `JsRunScript` with a snippet to return that function object, except the possibility of optimizing the operation (not running a script) and reducing host start-up time.

A naïve backing implementation would run a script snippet as JsRunScript would and return the function object (no perf improvement). To improve perf, we could identify each built-in by registering each built-in with a string that looks like the script string that would be used to access them (probably via some macro-generated table and code) and look them up directly that way.

I imagine use-case would be to query built-ins as needed (some smaller set that the host cares about preserving) like Node does.

We do delay-initialize [at least certain] built-ins (Intl definitely). In any case, looking them up would probably have to cause them to be initialized, unless we also implemented an initialize-on-call of the function rather than on-lookup.

**Comment by fatcerberus** [comment]
> Currently the way we handle this in node-chakracore is that we run a script early on to grab references to all the built-ins that we care about.

I guess that's one approach that works today, however that's not very good for encapsulation/compartmentalization as you need to know upfront when you initialize the context which builtins you care about.  Hypothetically, depending on how much encapsulation the host code has, that information may not even be available at startup--and maybe you end up having to grab *everything* as a result.

**Comment by rhuanjl** [comment]
If a script is used for this there's the risk that the default implementation has been overwritten by some other script and therefore what is retrieved is not the default implementation but the now modified one.

Conversely if a different method is used, it feels like you end up with an almost endless enum to provide all of the options - presumably with each option being a wrapper around a variety of calls to methods within JavascriptLibrary.cpp unless library->GetBuiltinFunctions() can do all of the required options? in which case the enum would be specifying which one is selected.

**Comment by liminzhu** [comment]
I think there're technically two scenarios here,
1) grab builtins in a performant and/or convenient way
2) grab _mint_ builtins in a performant and/or convenient way

You can do 1) by `JsRunScript` already. We can probably make 1) slightly faster but I don't know if it's worth it b/c you only need to do it once per builtin and it's probably very expensive anyway?

I was thinking about 2) and how expensive it would be in the earlier comment. It comes back to whether calling `JsGetOriginalBuiltIn` would be as expensive as instantiating a new context/globalObj. The input string is just one way to specify the path to unmodified builtin and avoid enums, so it's different to JsRunScript.

**Comment by MSLaguana** [comment]
Would creating a new context or global object even work? I guess if you wanted the functionality of the built ins then it would be sufficient, but if you wanted to do something else like check if a builtin had been overridden or something, then you can't check for equality since it is from a different context.

**Comment by liminzhu** [comment]
I mean if we can instantiate a single builtin then it'd be clean and great. I'd love to expose API based on that. 

But if we can't for some reason, a very naive implementation could be to create new global object in the same context, have it as one of those native JsValueRefs floating around not exposed in JS-land, and hand out a native handle to the specific builtin? This is what I'm trying to avoid.

**Comment by dilijev** [comment]
I could be wrong, but I believe we never throw away the original implementations of spec built-in functions (and certainly not their entry points), as they may be used by internal operations (and are sometimes required to by spec).

**Comment by fatcerberus** [comment]
Yeah, what @dilijev said, the way the spec is written I wouldn’t expect the default built-ins to ever be GC’d.  You’d only need to construct new ones if the user wanted absolute “mint condition” versions, but that’s not what I suspect most users want or even need (could be wrong though...).

At this point the question simply becomes, how granular do we want this API to be?

**Comment by liminzhu** [comment]
@dilijev If we keep the original ones then it's just a matter of us finding a way to expose them :). 

@fatcerberus We certainly can't GC anything global. I still think we should expose API for original builtins rather than just what's on the current global object. though. Like I said [before](https://github.com/Microsoft/ChakraCore/issues/4690#issuecomment-367133609) I don't see many merits for a new API over JsRunScript.

**Comment by fatcerberus** [comment]
When I said users wouldnt need mint-condition builtins, I just meant that in case the user does say:
```js
Object.foo = 812;
```
and then asks for the original `Object` I’d expect that to be by-reference and not by-value, i.e. return the monkeyed-with object and not some newly constructed virgin copy of it.

On the other hand if someone does `Math = undefined` and then I ask for the original `Math`, then give me the original reference before the reassignment.

**Comment by dilijev** [comment]
@fatcerberus I think that's true about the by-reference and changes to an object namespace like `Object` being observable from the original reference.

Note: We have to deal with this problem when exposing built-ins to Intl.js so that user modifications do not affect Intl.js semantics. We call observable user changes "tainting" in the source. We prevent tainting by preserving the original built-ins and built-in functions and pass this "library" of preserved functions in via an argument to the initializer function so that it is not possible for a user to modify them before they enter the function.

The only way around that is to get a completely fresh version which would be expensive, and might not even be possible in our current design. If not possible, the only other way to get an original would be from a new ScriptContext, but that version can only be used in that ScriptContext, I think.

Assuming we'd rely on the existing approach, I can't think of a scenario where you would want to be able to access a completely fresh built-in that you didn't know about before running user script. If you didn't know that would mean that somehow the user script could indicate to you what they need. If that's the case, then yes you'd need to preserve everything. I guess the goal is lazy-loading somehow. I guess I could imagine user code saying something like `let _obj_p = getBuiltin('Object.prototype')` which your host could have implemented as returning the original built-in, which you would have to already have because lazy-initialization or dynamically getting the original reference would not be possible in this case.

In any case, if you're running a user script on a new ScriptContext, you get a clean context with clean built-ins. If you don't use a new context, your user is subject to environment modifications done by previously-run user script. Assuming a user or more generically a "scripting concern" is aware of all possible previous modifications done to the environment, I can't see this being a problem. In the case where some script may not have knowledge, a new ScriptContext might be more appropriate to prevent leaking changes from one "concern" to another.

**Comment by dilijev** [comment]
Agree with you -- but devil's advocate: elegance is a matter of perspective. If we have to jump through hoops to provide an API which on the implementation side is clumsy or difficult to maintain at very little benefit to the API consumer, that's not a great win.

I think for now we will say that the requested functionality can be accomplished with the existing API and not necessarily look into this any further until there is a request with a clearly blocked use case.

**Comment by fatcerberus** [comment]
Sounds good to me, thanks.
