### ISSUE TITLE
`--no-icu` broken on Ubuntu after #4688

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#4701]
After #4688 was merged `--no-icu` will no longer work on Ubuntu, I receive the following output:

```
fatcerberus@pigcult-vm:~/src/ChakraCore$ ./build.sh -j=8 --no-icu
```

```
Searching for Clang...
Clang++ found at /usr/bin/clang++
Build path: /home/fatcerberus/src/ChakraCore/out/Release
-- /home/fatcerberus/src/ChakraCore/bin/ch/DbgController.js.h is up to date. skipping.
Compile Target : System Default
Generating Release makefiles

-- Looking for include file unicode/uchar.h
-- Looking for include file unicode/uchar.h - not found
CMake Error at pal/src/configure.cmake:919 (message):
  Cannot find ICU.  Try installing libicu-dev or the appropriate packages for
  your platform.  You may also disable icu/unicode with '--no-icu' argument
Call Stack (most recent call first):
  CMakeLists.txt:489 (include)


-- Configuring incomplete, errors occurred!
See also "/home/fatcerberus/src/ChakraCore/out/Release/CMakeFiles/CMakeOutput.log".
See also "/home/fatcerberus/src/ChakraCore/out/Release/CMakeFiles/CMakeError.log".
CMake Error at CMakeLists.txt:47 (message):
  Couldn't detect target processor, try `--arch` argument with build.sh


-- Configuring incomplete, errors occurred!
See also "/home/fatcerberus/src/ChakraCore/out/Release/CMakeFiles/CMakeOutput.log".
See also "/home/fatcerberus/src/ChakraCore/out/Release/CMakeFiles/CMakeError.log".
Makefile:524: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
See error details above. Exit code was 2
```

Ubuntu 16.04.3, if it makes a difference.

**Comment by jackhorton** [comment]
uh.... oops. I will try to fix this tonight or tomorrow. Sorry!

/cc @obastemur

**Comment by obastemur** [comment]
Dont we have a jenkins run for noicu?

**Comment by dilijev** [comment]
I don't think so. We do have the Lite build which has no Intl, but that's different. We should add an ICU Jenkins build if we don't have one. @jackhorton let me know if you need help with that. /cc @MSLaguana

**Comment by jackhorton** [comment]
Should we be concerned about adding more ubuntu builds to Jenkins? I am of the opinion that doing release, test, and debug of static and shared doesn't help a ton, if we needed to trade (I always thought it'd be better to do static debug, static test, static release, shared test, but maybe theres value in shared debug and shared release too)

**Comment by dilijev** [comment]
@jackhorton on Windows builds on Jenkins, the release builds basically only tell us that it builds (because we compile in different code paths for debug and release) and runs static analysis (only on release). If, in theory, there's nothing unique to a particular build configuration for Linux we could drop it. I think your suggestion sounds like a reasonable reduction.
