### ISSUE TITLE
How to get current script context

### ISSUE THREAD

**Issue by nullbus** [Microsoft/ChakraCore#4702]
Hi, I am doing some migration from V8 to ChakraCore. Some of JS code requires to be able to read file synchronously from its relative location (like `require` in CommonJS), so I have to figure out which script called the native function.

After some hacking, I noticed it is related to `JsSourceContext` but it is introduced as just debugging purpose in documentation. And there is no exposed JSRT api for that (excluding debug API).

If it is intended feature, then, could you suggest a way (either pure JS or native) to solve the problem?

**Comment by MSLaguana** [comment]
What exactly do you mean by `context`? There is the JSRT function `JsGetContextOfObject` which can get you a `JsContextRef` corresponding to where that object comes from. But that is not to do with the source of the script, that's more like which "iframe" type of thing the object is from.

Node implements `require` largely in script (at least the constructing the correct path part of it) and I believe it's done by caching the information about where scripts come from at the time they are read. That is, the host (node) is in control of how scripts enter the engine, so it can store that information however it likes. In particular I believe that node's `require` function has access to a "module" object which associated with a specific file, and that is used to determine search paths.

**Comment by nullbus** [comment]
Thanks for information. I wanted to know if there is built-in way to figure out the source/script which called the function. And now I understand the host is responsible for making relationship between scripts.

I should implement it manually. Some idea came up. Thanks again.
