### ISSUE TITLE
How do objects created using JsCreateExternalObject get cleared up

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/ChakraCore#4706]
I was wondering how you are able to clean up objects created on the heap and used via `JsCreateExternalObject`. 

I tried using the FinalizerCallback (in my previous issue #4679) but whenever i have that referenced in my `JsCreateExternalObject` call (and not even do anything) I get all sorts of crashes and corruptions happening. So I must be doing something wrong.

I tried looking at [one of the hosting samples](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp) and that doesn't `delete` the `GLPoint` objects created so it must be leaking unless `JsCreateExternalObject` auto-cleans up?

**Comment by MSLaguana** [comment]
You can take a look at how we do things in node-chakracore, e.g. in https://github.com/nodejs/node-chakracore/blob/master/deps/chakrashim/src/v8functiontemplate.cc. The general shape of things is we `new` up some native thing, and then wrap it in an `ExternalObject` with an appropriate finalizer function. In that finalizer, we cast the `void *` argument back to the correct type that we expect it to be, and then `delete` it to clean up.

As long as you are passing plain c-style functions (not member functions etc, but static class functions are fine) as the finalizer callback then nothing strange should happen when calling `JsCreateExternalObject`.

**Comment by coderangerdan** [comment]
Hmm, that's effectively what i am doing but its crashing when disposing of the runtime with "Object reference not set to instance" or other strange messages, sometimes even with memory corruption errors. These all go away as soon as I remove the finalizer.

**Comment by fatcerberus** [comment]
I ran into similar issues when trying to read properties off of JS objects in my finalizers.  As the finalizer may be called during runtime destruction (i.e. after the JsContextRef is out of scope) you can only safely access native resources in your finalizer.

**Comment by coderangerdan** [comment]
I get exceptions and all sorts of odd errors if i just setup a FinalizerCallback which is empty and does nothing. As soon as i pass `null` as my callback in the `JsCreateExternalObject` function, those exceptions go away.

**Comment by MSLaguana** [comment]
You are still using your c# wrapper, is that correct? Are you making sure to pass a plan c-style function to `JsCreateExternalObject`? Could your wrapper be taking or converting references somehow?

**Comment by coderangerdan** [comment]
Yes still using the C# Wrapper, yes its a plain static function:
```
private static void ImageFinalizeCallback( IntPtr dataPtr )
{
    // empty
}


var image = new MagickImage( "d:\\file.png" );
var imageHandle = GCHandle.Alloc( image );
var externalInstanceObject = JavaScriptValue.CreateExternalObject( GCHandle.ToIntPtr( imageHandle ), ImageFinalizeCallback );
externalInstanceObject.Prototype = PawaImagePrototype;
```

But even an empty one causes exceptions on disposing of the runtime. The only thing that works is passing `null` as the callback to `JavaScriptValue.CreateExternalObject` (which is a simple wrapper around `JsCreateExternalObject`.

I am really confused!!

**Comment by liminzhu** [comment]
Maybe your finalizer function gets GC'ed? Try making a delegate holding on to the finalizer and then pass the delegate to JsCreateExternalObject to keep it alive.

**Comment by coderangerdan** [comment]
Yeah, very good point. This would explain the oddities and also that sometimes it gets called, sometimes it doesn’t. Don’t know why I didn’t think of that as you have to do that for the FunctionCallbacks to ensure they don’t get GC’ed.

I will try in the morning and feedback

**Comment by fatcerberus** [comment]
Admittedly I'm not that familiar with the inner workings of the CLR, but I'm confused on 1) why a function defined as part of a class and presumably baked right into the IL would (or even could) ever be GC'd, and 2) how wrapping it in a delegate prevents that same function from being GC'd once the delegate goes out of scope.

**Comment by liminzhu** [comment]
Basically in .NET when you pass a function to unmanaged code, .NET doesn't know unmanaged side has an implicit reference after that line of code and will proceed and GC. Having a static delegate is an explicit way of keeping that reference in .NET world.

**Comment by coderangerdan** [comment]
That was it, thanks everyone. Seems obvious now, argh!!
