### ISSUE TITLE
Question: How do you use config flags?

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4718]
I looked but couldn't find this documented anywhere.

In https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/ConfigFlagsList.h there are lots of config flags with default values set.

Is there any API or convenient method an embedder can use to adjust these when creating a runtime? 

There doesn't seem to be anything for it in Jsrt other than the one Enable Experimental flag to turn on all experimental features.

**Comment by Penguinwizzard** [comment]
The vast majority of the config flags are set at compile-time for release builds. If you'd like to make a release build that enables toggling of some of them, then you'll have to do changes to chakracore. Are there any flags in particular that you find particularly interesting in some scenario?

**Comment by rhuanjl** [comment]
This was primarily curiosity - though:
a) I was interested in seeing if there was any measurable performance difference from turning the SpectreMitigation off. And

b) I'd seen reference to reading a config file which I assumed should be able to alter some of the flags but I couldn't see how that would be done.

**Comment by Penguinwizzard** [comment]
There's code in ConfigParser (at https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/Core/ConfigParser.cpp#L313) to control the spectre mitigations via registry. I'm not sure about the config file support; as far as I know, nothing on our end uses/tests that, and untested functionality tends to have a very short working lifetime in our codebase.

**Comment by MSLaguana** [comment]
Debug and test builds of ch (and node-chakracore) support reading from a `jscript.config` file that can specify flags like `-dump:bytecode` and `-trace:bailouts` etc. That file should be placed adjacent to the chakracore dll, or on linux and mac it should be placed in your home folder.

Note that these are intended for specific purposes and playing around with them gives no guarantee that things will necessarily work properly :)

**Comment by rhuanjl** [comment]
Thanks for the answers.
