### ISSUE TITLE
Expression shouldn't be allowed as computed property name

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/ChakraCore#472]
Chakra doesn't throw a SyntaxError for this code:
```js
({ [ 1, 2 ]: 3 });
```
but the specification defines [`ComputedPropertyName`](https://tc39.github.io/ecma262/#prod-ComputedPropertyName) as `[ AssignmentExpression ]`

**Comment by ianwjhalliday** [comment]
Similar to #147. @nicolo-ribaudo feel free to tackle this one as well at the same time.  Thanks for finding and reporting this.

**Comment by nicolo-ribaudo** [comment]
@ianwjhalliday Should I open a different pr or can I just add a commit to #471?

**Comment by ljharb** [comment]
wait, why would that throw a syntax error? I thought computed properties could be any JS expression - `{ ['foo']: 3 }` is certainly valid, why wouldn't `{ [2]: 3 }` be?

**Comment by nicolo-ribaudo** [comment]
`{ [2]: 3 }` is valid, but `{ [ 1, 2 ]: 3 }` isn't, because `1, 2` isn't an AssignmentExpression

**Comment by ianwjhalliday** [comment]
@nicolo-ribaudo one PR for both is fine

**Comment by ljharb** [comment]
@nicolo-ribaudo Is the [comma operator](https://tc39.github.io/ecma262/#sec-comma-operator) not an AssignmentExpression?

**Comment by ianwjhalliday** [comment]
@ljharb no it isn't. It is the only thing that is not an AssignmentExpression.  Expression is defined in the grammar as 

[_Expression_](https://tc39.github.io/ecma262/#prod-Expression)[In, Yield]:
 - _AssignmentExpression_[?In, ?Yield]
 - _Expression_[?In, ?Yield] __,__ _AssignmentExpression_[?In, ?Yield]

**Comment by ljharb** [comment]
gotcha, thanks for clarifying

**Comment by nicolo-ribaudo** [comment]
I just pushed the fix at #471
