### ISSUE TITLE
Inheriting from proxied class causes `this` mixup

### ISSUE THREAD

**Issue by jdalton** [Microsoft/ChakraCore#4729]
Using NodeChakra
```js
const EventEmitter = new Proxy(require("events"), {})

class B extends EventEmitter {
  constructor() { 
    super();
    console.log(this.a, this)
  }
  
  a() {
    return "a"
  } 
}

new B // logs `undefined` for `this.a` and the `this` of `EventEmitter` instead of `B`.
```

**Comment by jdalton** [comment]
Simplified repro
```js
function A() {}

class B extends new Proxy(A, {}) {
  a() {
    return "a"
  } 
}

console.log(new B().a)
// logs `undefined` instead of the function `a`
```

**Comment by rhuanjl** [comment]
Had a quick look - I don't think it's a simple mixup.

It seems that if a class extends a Proxy attempting to instantiate the class simply gives you the Proxy.

**Comment by jdalton** [comment]
Ya. 

Further testing shows Chrome (v8), Firefox, Safari return the expected result.

**Comment by rhuanjl** [comment]
I made a naive attempt at fixing this:
https://github.com/rhuanjl/ChakraCore/commit/e65706869fe67f048912411bab1a42054ac012bb

But whilst it fixes this issue it creates some new issues.

Previously the value "isCtorSuperCall" was being set at the top of the trap function but then not used. I've put in usage of it based on how native constructors treat it BUT it introduces strange behaviour as it appears to be true at odd times when it should not be; proxytest9.js from es6 tests in CI hits multiple such cases.

For a simple though unobservable example, in the below case the second time the constructor trap is hit it is treated as a super call:

```js
var handler =
{
    construct: function(target, args) {
        print('constructor trap');
        return Reflect.construct(target, args);
    }
};

function foo() { this.x = 1};
var pFoo = new Proxy(foo, handler);
var y = new Proxy(pFoo, handler);

print((new y()).x == 1);
```
