### ISSUE TITLE
Proxied functions aren't considered functions by Function.prototype.toString.call

### ISSUE THREAD

**Issue by jdalton** [Microsoft/ChakraCore#4730]
```js
var a = function() {}
var p = new Proxy(a, {})

Function.prototype.toString.call(p)
// TypeError: Function.prototype.toString: 'this' is not a Function object

typeof p // "function"
Object.prototype.toString.call(p) // [object Function]
```

With at least Safari passing a proxied function to `Function.prototype.toString.call` will work.

<img width="455" src="https://user-images.githubusercontent.com/4303/36560441-90f3d82c-17c5-11e8-891a-9c921cb6c9a6.png">

Related: https://bugs.chromium.org/p/v8/issues/detail?id=7484

**Comment by jdalton** [comment]
Related: https://bugs.chromium.org/p/v8/issues/detail?id=7484

**Comment by jdalton** [comment]
**Update:**

Patched in v8 https://chromium.googlesource.com/v8/v8.git/+/f7d7b5c6a4a55baa8984525fba6d0d5e1355b3b0.

**Comment by dilijev** [comment]
The version available to jsvu right now does not have the fix?

```
>eshost --tags jsvu -h ch-master-latest -isx "var a = function() {}; var p = new Proxy(a, {}); print(Function.prototype.toString.call(p))"
## Source
var a = function() {}; var p = new Proxy(a, {}); print(Function.prototype.toString.call(p))

#### ch-master-latest, jsvu-ch
TypeError: Function.prototype.toString: 'this' is not a Function object

#### jsvu-d8
TypeError: Function.prototype.toString requires that 'this' be a Function

#### jsvu-sm
TypeError: Function.prototype.toString called on incompatible object

#### jsvu-jsc
function ProxyObject() {
    [native code]
}


>eshost --tags jsvu -h ch-master-latest -isx "var a = function() {}; var p = new Proxy(a, {}); print(typeof p); Object.prototype.toString.call(p)"
## Source
var a = function() {}; var p = new Proxy(a, {}); print(typeof p); Object.prototype.toString.call(p)

#### ch-master-latest, jsvu-ch, jsvu-d8, jsvu-jsc, jsvu-sm
function
```

**Comment by jdalton** [comment]
> The version available to jsvu right now does not have the fix?

Prolly not, it was patched like 2 hours ago.

**Comment by dilijev** [comment]
Yep, now fixed:

```
>eshost --tags jsvu -h ch-master-latest -isx "var a = function() {}; var p = new Proxy(a, {}); print(Function.prototype.toString.call(p))"
## Source
var a = function() {}; var p = new Proxy(a, {}); print(Function.prototype.toString.call(p))

#### jsvu-sm
TypeError: Function.prototype.toString called on incompatible object

#### ch-master-latest, jsvu-ch
TypeError: Function.prototype.toString: 'this' is not a Function object

#### jsvu-d8
function () { [native code] }

#### jsvu-jsc
function ProxyObject() {
    [native code]
}
```

**Comment by jdalton** [comment]
Might hold off until after next tc39 meeting. It seems be opening the issue, it getting patched, has alerted folks that the revised spec allows this. They may want to back it out or decorate the bound/proxied native code representation in a way that distinguishes it from the generic native code representation while still being valid so `"function proxied () { [native code] }"` or smth.

**Comment by dilijev** [comment]
Thanks for the update, @jdalton

**Comment by jdalton** [comment]
Ok so it looks like the points of contention have passed as tests land in test262 https://github.com/tc39/test262/commit/c55d2ab7c344e35a3ceb93cf1d4d30019584db82.

**Comment by dilijev** [comment]
@bterlson can you confirm whether tc39 has reached consensus here?
