### ISSUE TITLE
Releases CDN exhibiting authn errors

### ISSUE THREAD

**Issue by mfikes** [Microsoft/ChakraCore#4738]
If you go to the releases page https://github.com/Microsoft/ChakraCore/releases and attempt to download you will get an error

```xml
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:2ecb0da1-a01a-008e-4cf5-ac5923000000 Time:2018-02-23T22:30:55.2871499Z
</Message>
<AuthenticationErrorDetail>
Signature did not match. String to sign used was r 2018-02-12T06:03:00Z 2025-02-13T06:03:00Z /file/chakratestx/chakrashare 2017-04-17
</AuthenticationErrorDetail>
</Error>
```

**Comment by sethbrenith** [comment]
Sorry about that; thanks for the report. 1.8.1 is repaired now, but I'll need some help from @obastemur or @jianchun for the older releases.

**Comment by dilijev** [comment]
Oh I misunderstood. I didn't realize older releases had issues also.

**Comment by obastemur** [comment]
@sethbrenith thanks for taking care of it. I just updated the rest.
@mfikes thanks for reporting it. Fixed.
