### ISSUE TITLE
Error when using name "async" in destructuring assignment

### ISSUE THREAD

**Issue by webmaster128** [Microsoft/ChakraCore#4741]
This code fails with

> SCRIPT1028: Expected identifier, string or number

in line 21:15 of

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<script>
function test1() {
    var async = 1;
    console.log(async);
}

function test2() {    
    var object = {p: 42, async: true};
    var {p, async} = object;
    console.log(p);
    console.log(async);
}

function test3() {
    var object = {p: 42, async: true};
    var {async, p} = object;
    console.log(p);
    console.log(async);
}

test1();
test2();
test3();
</script>
</body>
</html>
```

using

Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299

See also #4158

**Comment by akroshg** [comment]
It is seems like it is correctly in the current build of ch.exe out of release/1.8

**Comment by akroshg** [comment]
This is fixed by @aneeshdk by #4377

**Comment by webmaster128** [comment]
Okay cool. Feel free to close if you are confident that the use in destructuring assignment is the same thing as the test added in #4377.

Is there a versions table of Edge version / Chakra version? Is there a version of Edge that can be used to test Chakra 1.8?

**Comment by akroshg** [comment]
This should be part of Redstone 4 (not sure the exact date of release). Although you can get the insider preview here  https://blogs.windows.com/windowsexperience/2018/02/23/announcing-windows-10-insider-preview-build-17107-fast-ring/#1YzsjCSGuE3fo5uQ.97

Thanks for reporting the issue @webmaster128
