### ISSUE TITLE
Use of 1 numeric literal is slow

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4744]
Slightly odd issue I stumbled to when profiling some code recently - seemingly:
```js
someVar = 1;
//or
let someVar = 1;
```
Is a source of significant slowdown in CC.

Assuming the above is in a hot path replacing the 1 with a different number or with a variable already set to 1 causes significant speed up - even setting the variable to 2 and then multiplying by a half seems faster than initialising it as 1.

I've written a slightly extended test case which uses 3 functions to calculate a factorial each one initialises a variable then multiplies it in a loop to produce the answer.
factorialA() - initialises to 1
factorialB() - initialises to one - a constant pre-defined to 1.
factorialC() - initialises to 2 and returns the result multiplied by 0.5

I've included warmup calls to endeavour to ensure that the code is jitted properly - factorialA() takes twice as long to run as the other 2 cases in CC - in other engines results are comparable for all 3 cases - results table using eshost posted below test case.

```js
function factorialA(n)
{
    let result = 1;
    for(let i = 0; i < n; ++i)
    {
        result *= (n - i)
    }
    return result;
}

const one = 1;
function factorialB(n)
{
    let result = one;
    for(let i = 0; i < n; ++i)
    {
        result *= (n - i)
    }
    return result;
}

function factorial2(n)
{
    let result = 2;
    for(let i = 0; i < n; ++i)
    {
        result *= (n - i)
    }
    return (result * 0.5);
}

function testFactA()
{
    let result = 0;
    for (let i = 0; i < 1000; ++i)
    {
        result += factorialA(i);
    }
    return result;
}

function testFactB()
{
    let result = 0;
    for (let i = 0; i < 1000; ++i)
    {
        result += factorialB(i);
    }
    return result;
}

function testFactC()
{
    let result = 0;
    for (let i = 0; i < 1000; ++i)
    {
        result += factorial2(i);
    }
    return result;
}

//warmup
let start = 0;
for(let j = 0; j < 10000; ++j)
{
    testFactA();
    testFactB();
    testFactB();
}

//test
start = Date.now();
for(let j = 0; j < 1000; ++j)
{
    testFactA();
}
print("factorialA time = " + (Date.now() - start));

start = Date.now();
for(let j = 0; j < 1000; ++j)
{
    testFactB();
}
print("factorialB time = " + (Date.now() - start));

start = Date.now();
for(let j = 0; j < 1000; ++j)
{
    testFactC();
}
print("factorialC time = " + (Date.now() - start));
```
Results using eshost:

```
#### SpiderMonkey
factorialA time = 700
factorialB time = 699
factorialC time = 701

#### V8 --harmony
factorialA time = 705
factorialB time = 703
factorialC time = 708

#### JavaScriptCore
factorialA time = 714
factorialB time = 712
factorialC time = 709

#### Chakra
factorialA time = 1412
factorialB time = 678
factorialC time = 669
```

**Comment by VSadov** [comment]
In a case of literal `1` , the JIT gets into situation when `result` is TypeSpec`d  to `int32`. 

However, later `result` becomes a `float` and that causes a JIT time bailout and a subsequent rejit with `int` typespec disabled.

It is a bit puzzling though, why literal `2` or `const one = 1` do not trigger this behavior. 
Not sure yet why the `1` is special

**Comment by rhuanjl** [comment]
@VSadov Interesting - so this is CC attempting to optimise using int32s then hitting a trap when the answers get too big and having to coerce to float?

Curious that this doesn't happen with the const one = 1 case then. Though IMO would make sense that it doesn't happen for the 2 case as I multiply by a half in the function there (to get the answer as if I'd used 1 in the first place)

**Comment by VSadov** [comment]
There are two kinds of analysis - one tries to estimate if `int32` math is applicable. And it optimistically says "yes" in the case of `1`. That does not get to be the running code though.
Later the dataflow/liveness analysis sees that the value is re-used in the loop and concludes that `result` better be a float. That is in conflict with the previous analysis so the JIT must rerun with less aggressive optimizations.

**Comment by VSadov** [comment]
Why  this is specific to `1` :

TypeSpecializeBinary for `Js::OpCode::Mul_A`  tries to predict overflows based on likely min/max values of the operands.

If one of the operands is seen to have value `1` (and that is the case when literal `1` is used), then `Mul_A` cannot overflow or result in `-0.0` regardless of the value of the other operand (assuming it is also `int32`), so the analysis concludes that `int32` math can be used. 
That feels somewaht aggressive. `1` is indeed special. It is a fixed point for `Mul_A`. Also it is likely to be just some initial trivial value that will change. If the other operand is large enough that will cause an overflow bailout. 

Simple bumping `max` values `1` -> `2` for the purpose of overflow prediction when doing typespec for Mul_A seems to fix the issue while keeping the desired behavior in other cases - i.e. if the other operand is a small number we will still typespec to 'int32`.

Not sure if this would be the right fix though.
