### ISSUE TITLE
How can I debug JS code running in an WPF app which embeds ChakraCore?

### ISSUE THREAD

**Issue by pallammadhukar** [Microsoft/ChakraCore#4778]
Hi All,

We have created an WPF C# Application Which embeds ChakraCore. We wanted to debug javascript files that are loaded in chakra core engine.

Please help me. Feel free to ask any required information.

Thanks,
Pallam Madhukar

**Comment by liminzhu** [comment]
We're tracking this in https://github.com/Microsoft/ChakraCore/issues/4616
