### ISSUE TITLE
build.sh breaks when python 3 is the default interpreter

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/ChakraCore#4791]
The problem is on lines 523-524:

```
BUILD_RELATIVE_DIRECTORY=$(python -c "import os.path;print \
    os.path.relpath('${CHAKRACORE_DIR}', '$BUILD_DIRECTORY')")
```

This fails for me because `python` invokes python3, where `print foo` is no longer legal syntax.  If I manually change the invocation to `python2.7` (valid on my system), things work as expected.  I hit this failure after some system update or other updated the interpreter pointed to by `python` to version 3.4.

I notice that we only use python here, to get a relative path, and we only use the resulting relative path as an argument to `cmake`.  Is it strictly necessary to give `cmake` a relative path?  Could we get away with just passing `CHAKRACORE_DIR` instead?  It seems to work on my machine, but I don't know enough about CMake to be confident here.

If we can't get away with using the absolute path, would we consider using perl here instead?  We can do the same thing with a one-liner, and perl has (IMO) better distribution on platforms that run bash.  Increasingly, we won't be able to rely on python2 being available.  For so minor a use-case, we may not want to bet on it.

Thanks!

**Comment by jackhorton** [comment]
Looks like this is related to creating the binary release package, which I _think_ @sethbrenith owns now? I am going to assume that for that purpose, it should be relative for... some reason related to finding things on the installer's system. With that being said, we could almost certainly do something like

```bash
PYTHON_BINARY=$(which python2.7 || which python2 || which python 2> /dev/null)
```

To find the correct version of python to use.

**Comment by benjamin-bader** [comment]
That works for me personally.  Too bad relativizing is such a pain in posix shells!

**Comment by jackhorton** [comment]
I will make a PR for this in a bit.

**Comment by benjamin-bader** [comment]
Awesome, thank you!
