### ISSUE TITLE
Suggestion: implement array.prototype.sort in javascript

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4793]
**Suggestion**
Implement Array.prototype.sort  as an additional JsBuiltin within JsBuiltins.js - OR at the minimum the sort it uses when it is called with a comparison function.

Motivation is performance and compatibility (the current implementation sometimes errors out with "Out of stack space" when sorting large arrays with a custom comparison)

Further details including cross engine comparisons below.

**Current status of Array.prototype.sort**
Currently Array.prototype.sort in ChakraCore is very fast when called without a custom comparison method.

BUT with a custom comparison method it is not quick. For arrays of length < 10,000 it's reasonable but for larger arrays it becomes either too slow or it crashes with "out of stack space"

**Comparison to other engines - observed behaviour**
Chakra's performance is similar to v8 - quick with the built in comparison - slow with custom methods - BUT v8 does not crash with "out of stack space" for large arrays.

SM and JSC on the other hand perform sorts with custom comparisons in very short amounts of time. - see illustrative test case below.

**Comparison to other engines - internals**
JSC and Spidermonkey both implement array.prototype.sort as a self-hosted javascript built in - this means that when using a custom comparison method it can assumedly be inlined within the sort - resulting in the much higher observed performance.

v8 and ChakraCore both implement array.prototype.sort in C++ hence the observed issue of very slow handling for sorting large arrays using a custom comparison - as the C++ sort method has to repeatedly call into the Javascript comparison method.

**Illustrative test cases**
Firstly - array of length 100,000
```js
let foo = [];
let names = ["bar", "foo", "test", "adam", "jeff"];

for (let i = 0, id = 0.1; i < 10000; ++i)
{
    id = Math.random();
   foo[i] = {
        id : id,
        name : names[Math.floor(id * 5)]
    };
}
let bar = Date.now();

function compare ( a, b)
{
    return a.name < b.name ? -1 : 1;
}
foo.sort(compare);

print("Time taken is " + (Date.now() - bar));
```

**eshost results**
```
#### JavaScriptCore
Time taken is 53

#### SpiderMonkey
Time taken is 104

#### Chakra
Time taken is 24559

#### V8 --harmony
Time taken is 29243
```

Secondly - repeat the same changing the length to 500,000
```
#### JavaScriptCore
Time taken is 252

#### SpiderMonkey
Time taken is 482

#### Chakra
Error: out of stack space

#### V8 --harmony
Time taken is 649802
```

**Comment by jackhorton** [comment]
cc @LouisLaf who was discussing something very similar for Array.prototype.filter yesterday

**Comment by rhuanjl** [comment]
Thinking about it more, in general this seems like a good idea for any spec defined methods which:
a) can be implemented in this way (i.e. don't need OS calls etc.) and
b) take callable parameters which they call repeatedly

Lots of array methods seem like obvious candidates e.g.
Array.prototype.sort
Array.prototype.filter
Array.prototype.indexOf
Array.prototype.every
Array.prototype.map
Array.prototype.find
...

Considering the (fairly) recent addition of JsBuiltins.js is there already a plan to do some of this?

Having looked over the logic of how JsBuiltins.js is implemented I figure I could write a PR for array.prototype.sort and maybe one or two more if this was wanted - wouldn't be immediate, would be a few weeks until I'd have the time.

**Comment by jackhorton** [comment]
As the main person working on Intl right now, I can say that our story for writing builtins in JavaScript is really rough right now. Intl was the first in ChakraCore (there is another component of ChakraFull that uses the same system), but its unfortunately far more difficult than writing normal JS (or even Node-style libraries) and, more importantly, far more difficult to debug. If you are willing to take a crack at it, I can try to explain some of the extra processes that you need to work with these either in Gitter or on the Wiki.

cc @meg-gupta who wrote most of the current JsBuiltIns

**Comment by jackhorton** [comment]
Also I believe there was an effort to implement some or all of those methods in JS in the past, but it didn't provide the perf wins we had expected. I wasn't on the team for that but meg might have more insight.

**Comment by meg-gupta** [comment]
Implementing array iterator in Js was much more straight forward. From what I have understood from several discussions on this, implementing these functions in Js will not completely unleash our global optimizer due to challenges seen in inlining when we see these functions called multiple profiled types. We saw similar challenges with the indexOf project. @LouisLaf was saying Function specialization is needed to tackle this issue.

**Comment by rhuanjl** [comment]
I suppose the issue is that with these functions in JS they get called with different types and hence trigger bailouts?

In most cases where the performance matters i.e. arrays with length >1000 or so, assumedly it would be a bailout and re-jit? But then do you run into problems if it happens too many times? And also potentially seriously hurt performance of code that uses these functions with numerous short arrays... I wonder how Mozilla and Apple get around that in their versions.

Could there be a mechanism whereby each individual piece of code that needs one of these functions somehow triggers creation of a new copy of the relevant builtin code? I imagine that that could be somewhat complex to implement and likely would have other tradeoffs.

**Comment by rhuanjl** [comment]
I'm going to close this issue - for now:
a) it's clearly a larger/more complex idea than I thought
b) my performance stats above are actually to do with merge sort vs qsort with a comparison function that can reverse direction (i.e. the strict less than condition I used)
c) the gain/benefit is far less clear than I thought
