### ISSUE TITLE
Intl: Convert AssertOrFailFast to AssertOrThrow where applicable

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4798]
Most of our failfasts are there to predict against unknown states, however Intl is not particularly vulnerable code -- if we are in a state we don't expect, its likely due to bad assumptions about the system configuration of the locales and formats that we weren't expecting. As a result, it may not be worth it to crash the Chakra process and render sites that use Intl on that computer unusable if we can at least let userland JS code work around any such issues itself.

I know that @dilijev is in favor of this but am open to alternate opinions.

**Comment by agarwal-sandeep** [comment]
Which failfast are we considering here? the 2 in IntlEngineInterfaceExtensionObject.cpp?

**Comment by jackhorton** [comment]
All of the ICU_ASSERTs are failfasts on both the status code returned from ICU (basically equivalent to an HRESULT) as well as additional conditions, usually checking the lengths of returned buffers. The buffer length checks usually are redundant, assuming ICU is correctly setting their status code every time.

**Comment by jackhorton** [comment]
After some internal discussion, it seems like the only way forward here is to add -IntlThrowOnFailure as a flag that we can run in debug/test builds, but failfasting should remain the default and only option for release builds.

**Comment by jackhorton** [comment]
Not worth keeping open without a known use case, and the failfasts haven't been noisy in flights.
