### ISSUE TITLE
Move jenkins.*.* scripts into a jenkins directory off the project root.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#48]
This will make the contents of the root of our project more legible, and effectively bring the `README` into view sooner on the main page of the project.

It will require modifications to most of those scripts and to the `netci.groovy` script itself.

The build checks will break on the PR for this change because the Jenkins task definitions will be out of sync with the actual locations of the files, so we will need to accept the change despite the breaks and quickly react to breaks following that change.

**Comment by Croydon** [comment]
:+1:

**Comment by ianwjhalliday** [comment]
@dilijev how does this look? https://github.com/Microsoft/ChakraCore/compare/master...ianwjhalliday:mvjenkins

I did not test this at all. Just throwing it up there as a rough start.

**Comment by dilijev** [comment]
@ianwjhalliday Great! Exactly what I was planning. I would also like to remove the `jenkins.` prefix from them since it's redundant. Might as well make the folder name capitalized `Jenkins` to go with the new scheme.

That should work. Keep in mind your pull request will break the checks because they won't be able to find the scripts where expected (it uses the jobs generated by the current master when `netci.groovy` was last updated). The subsequent build on master should succeed though, unless something went wrong.

**Comment by dilijev** [comment]
@mmitche FYI does @ianwjhalliday's change in https://github.com/Microsoft/ChakraCore/compare/master...ianwjhalliday:mvjenkins look good to you?

**Comment by mmitche** [comment]
jenkins/jenkins.buildone.cmd looks like it need ~%dp0 in front of the script call?

**Comment by ianwjhalliday** [comment]
@mmitche yep, thanks for catching that

**Comment by dilijev** [comment]
For the linux scripts as defined, you'll want to make sure that the scripts are invoked relative to the working directory and not the script directory. I don't know if linux has an equivalent of `%~dp0` for that purpose.

**Comment by dilijev** [comment]
In https://github.com/Microsoft/ChakraCore/commit/28c00648ddd98ec48d0fa176351aea32cf103d10 it looks like the execute bit was lost on the shell scripts when you renamed the files.

Please run `git update-index --chmod=+x [file]` on the shell scripts.

This is required for Ubuntu to be able to execute the scripts.

**Comment by dilijev** [comment]
@ianwjhalliday FYI there are currently several open pull requests regarding changes to the scripts so you'll probably want to reapply the changes you made to move the scripts from scratch after those PRs are resolved.

**Comment by ianwjhalliday** [comment]
Yeah, good idea. Thanks for the heads up.

**Comment by ianwjhalliday** [comment]
The redirection stub scripts are still in the root directory.  This will be fixed by #531.
