### ISSUE TITLE
Implementing a synchronous Javascript operation asynchronously

### ISSUE THREAD

**Issue by crdumoul** [Microsoft/ChakraCore#4801]
I have a Javascript function that I want to complete synchronously, from a Javascript perspective. However, I would like to bind that Javascript function to a native function where I want to do some I/O asynchronously. While waiting on the I/O, I want to unload/disassociate the Context and Runtime from the current thread, work with a different Context and Runtime, and then resume the original Context once the I/O is complete.

How would I do that? I was thinking it might just be about calling JsSetCurrentContext (to switch to a different context) within the bound native function, but I'm not sure.

**Comment by crdumoul** [comment]
In the [JSRT Overview document Concepts section](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#concepts) there's a paragraph that says,

> Unlike runtimes, multiple execution contexts can be active on a thread at the same time. So a host can make a call into an execution context, that execution context can call back to the host, and the host can make a call into a different execution context.

That's followed by a diagram that looks like:
Host -> Execution Context 1 -> Host -> Execution Context 2

I think what I'm trying to do is a variant of that pattern.

**Comment by liminzhu** [comment]
You can achieve this by switching context in native functions or somewhere else, but what you describe is a fairly complex architecture. Any reason why you can't let the JS side to be async as well?
