### ISSUE TITLE
Undeferring a deferred function type handler can change its prototype

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/ChakraCore#4829]
Running the following in ch will print `false` rather than `true` as expected:

```js
function testreturner(){
  return function test(){};
}

var t = testreturner();
Object.defineProperty(t, "a", {value: 1});


var t2 = testreturner();
var o = {};
Object.setPrototypeOf(t2, o);
Object.defineProperty(t2, "b", {value: 1});
WScript.Echo(o === t2.__proto__);
```

Looks like this might have been introduced by f3c5f9f215

**Comment by pleath** [comment]
Ah. Looks like this will be resolved by moving to PathTypeHandler for function objects that have properties added to them. I'll keep this open for now and then close it once the PathTypeHandler change goes in.

**Comment by MSLaguana** [comment]
This has been fixed.
