### ISSUE TITLE
Compare objects created using JsCreateExternalObject at JS runtime.

### ISSUE THREAD

**Issue by vputsenko** [Microsoft/ChakraCore#4839]
Hello,

This is more question rather than issue. If I call JsCreateExternalObject twice, pass same pointer to data argument and set same prototype, JsEqual and operator == at JS runtime for created objects will always return false. I know, you may say "what do you expect,  these are physically different objects!" Yes, I partially agree. But from other side, these are different projection wrappers to same core object, they have same prototype and even you can call JsPreventExtension to prevent any data binding at JS runtime. So everything is same except memory block that holds this data and GC state.

Suppose you want to create JS projection to large C++ object model. Sometimes you may have different interfaces which may return pointer to same object in their methods. You wrap these objects with projection wrappers and return to JS script. In this case JS script will not have way to check whether these objects are the same. The only way to archive this - keep map of alive JS objects and return existing projection wrapper instead of creating new. From my look this is expensive lookup considering fact that JS script may not even attempt to compare these object, because it doesn't require this. it will also require expensive locks in multithreaded environment.

So is that mapping is the only way to solve the problem? Are you going to add some API? 

Thanks.

**Comment by jackhorton** [comment]
Could you add a method to the external objects called, say, `equals(other)`, and implement that as a native function which first checks JsEquals and then checks if the external data of each object is equal?

**Comment by MSLaguana** [comment]
The `JsCreateExternalObject` method is similar to `JsCreateObject` method, in that they are both conceptually equivalent to `var ret = {}`, with some additional JS-invisible data stashed away in the case of `JsCreateExternalObject`. Based on that, and the javascript behavior that `{} != {}` (that is, objects are only equal if they are the same reference) we won't be changing that behavior in the JSRT.

Can you describe your scenario in more detail? You say that keeping a native<->script object map would be expensive, do you expect to create thousands of these objects? You also mention needings locks for multithreaded environments, but you must always be invoking JSRT functions on the same script thread, so you'll need coordination there regardless if you have a multithreaded environment.

How do you expect/want to use these objects from script? Rather than using pointer equality of your native data, could there be some other identifier which you expose to script and then do your comparisons on that?

**Comment by vputsenko** [comment]
Thanks for the responses.

1. Currently our platform uses Active Scripting to execute JScript code. We already have equal method in our object model. However, besides IDispatch interface our projection wrappers implement [IObjectIdentity](https://docs.microsoft.com/en-us/scripting/winscript/reference/iobjectidentity-isequalobject), Active Scripting calls this interface when executes == operator on custom objects. Our implementation compares internal data (pointers to wrapped C++ object). So without mapping described above, moving to Chakra, will cause existing JS scripts  run incorrectly in these cases. In projects where there are no unit tests - it will be pain.

2. I didn't test it, basing on fact that i can set current context before executing any script code, i assumed that thread just needs to know value of context variable so it can set it as current and execute peace of script code. If this is wrong, then thread locks for that map is not  required. Just forget it... In this case i can keep this mapping in object bound to prototype using some custom symbol.

3. Actually we are platform which exposes large object model. All projection wrappers are written using single template which just accepts array of names and array of C++ methods. Then special templates automatically generate necessary convertors between basic C++ (STL) types and JSRT. Objects are different: from UI control to item with fields that represent record in SQL DB. Event exposed to script may call heavy handlers which may iterate over thousand of items found by search criteria and so on. So avoiding that mappings would be nice. Note that the mapping will be accessed two times per object: during construction to check whether we already have wrapper and from finalize callback to remove mapping slot.

4. Real world scenario: you have "form" object which has read/write "item" property which sets/gets item the form should display fields of. Look at script:
`var form = application.create_form("Contact Form");
var contact= application.create_item("Contact");
item.set_field("Name", "John");
form.item = contact; // at this point we extract C++ object from passed JSRT value using JsGetExternalData and save extracted C++ object in form object.
var contact2 = form.item; // we create new wrapper and return it
var eq = contact == contact2;  // no way ...
`
There are more complex scenarios when object can be wrapped and unwrapped multiple times. We implement commonJS  interface so we are talking  about not a single script file which knows what he does, multiple scripts and libs can participate. 

Thanks,

**Comment by VSadov** [comment]
It seems it depends on what is more frequent - creating/destroying the projections or comparing their identities. If comparing is common/important enough, then having "uniqueness" map could be worth it.

It is also likely that a duplicate projection has larger memory footprint than an entry in a map would have. It all depends on the actual use patterns, but if "duplicate" projections are common occurence, then "uniqueness" map could actually have overall positive impact on performance via the working set reduction.

Note that the "uniqueness" behavior _can_ be implemented on top of existing API via a host-side map, but the opposite (if API itself reuses existing projections, but user wants a new one every time) would not be possible. Besides changing the behavior would be breaking to the users who rely on distinct projection objects created.
