### ISSUE TITLE
Implement JavascriptArray::GetLocaleSeparator for Linux/macOS

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4840]
Currently, Array.prototype.toLocaleString() uses ", " as the separator in every locale on xplat. This should probably be factored into a new PlatformAgnostic::Arrays module similar to PlatformAgnostic::Numbers.

**Comment by sumitsahrawat** [comment]
This should be closed according to #5264

**Comment by jackhorton** [comment]
You're right, thanks!
