### ISSUE TITLE
Move PlatformAgnostic::UnicodeText::LogicalStringCompare tests to native tests

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4844]
These tests are never run because they require an explicit, opt-in build configuration.

**Comment by aileronajay** [comment]
Hi @jackhorton the cpp file, UnicodeText.Common.cpp is current nested at \lib\runtime whereas the native tests is at \bin\NativeTest, should a new file be created at \bin\NativeTest\ to hold these test cases?

**Comment by jackhorton** [comment]
Yup! If you want to take a stab at this, it would be great to convert the asserts to use "Catch.hpp" in bin\External -- mostly the CHECK(), REQUIRE(), and TEST_CASE() macros. See how the other files are set up there to get a sense. I think anything in the compilation unit that is marked as TEST_CASE automagically get picked up by the Catch test runner and run by NativeTests.cpp. I should note that I haven't actually ran the test that's currently in UnicodeText.Common.cpp, so theres a chance it may fail the way it is now?

**Comment by aileronajay** [comment]
created PR https://github.com/Microsoft/ChakraCore/pull/4905 to confirm that the file location is correct

**Comment by aileronajay** [comment]
@jackhorton, i added tests to the blank file i created. In the tests there is a reference to 

PlatformAgnostic::UnicodeText::Internal::LogicalStringCompareImpl(str1, str2);

Visual studio is unable to resolve this reference in the current file, ie in UnicodeTextTest.cpp, any pointers on how to fix this?

**Comment by MikeHolman** [comment]
@jackhorton does #5029 resolve this?

**Comment by jackhorton** [comment]
Yes, sorry.
