### ISSUE TITLE
Chakra failed when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [microsoft/ChakraCore#4848]
Chakra failed with error error C2760: syntax error: unexpected token 'char', expected 'expression' and error C7510: 'Tick': use of dependent type name must be prefixed with 'typename' when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**
1.	git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2.	Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\Chakra\src
3.	set  _CL_=-wd4471  /permissive-
4.	msbuild /m /p:Platform=x86 /p:Configuration=Test /p:WindowsTargetPlatformVersion=10.0.16299.0 Build\Chakra.Core.sln /t:Rebuild

**Error info:**
d:\chakra\src\lib\common\Memory/SmallHeapBlockAllocator.h(146): error C2760: syntax error: unexpected token 'char', expected 'expression'
d:\chakra\src\lib\common\Memory/SmallHeapBlockAllocator.h(146): note: This diagnostic occurred in the compiler generated function 'char *Memory::SmallHeapBlockAllocator<TBlockType>::InlinedAllocImpl(Memory::Recycler *,size_t,Memory::ObjectInfoBits)'
Jobs.i
D:\Chakra\src\lib\Common\Common/Jobs.inl(121): error C2760: syntax error: unexpected token 'identifier', expected ';'
D:\Chakra\src\lib\Common\Common/Jobs.inl(121): note: This diagnostic occurred in the compiler generated function 'void JsUtil::ForegroundJobProcessor::PrioritizeManagerAndWait(TJobManager *const ,const unsigned int)'
D:\Chakra\src\lib\Common\Common/Jobs.inl(121): error C7510: 'Tick': use of dependent type name must be prefixed with 'typename'
D:\Chakra\src\lib\Common\Common/Jobs.inl(121): note: This diagnostic occurred in the compiler generated function 'void JsUtil::ForegroundJobProcessor::PrioritizeManagerAndWait(TJobManager *const ,const unsigned int)'
D:\Chakra\src\lib\Common\Common/Jobs.inl(260): error C2760: syntax error: unexpected token 'identifier', expected ';'
D:\Chakra\src\lib\Common\Common/Jobs.inl(260): note: This diagnostic occurred in the compiler generated function 'void JsUtil::BackgroundJobProcessor::PrioritizeManagerAndWait(TJobManager *const ,const unsigned int)'
D:\Chakra\src\lib\Common\Common/Jobs.inl(260): error C7510: 'Tick': use of dependent type name must be prefixed with 'typename'
D:\Chakra\src\lib\Common\Common/Jobs.inl(260): note: This diagnostic occurred in the compiler generated function 'void JsUtil::BackgroundJobProcessor::PrioritizeManagerAndWait(TJobManager *const ,const unsigned int)'

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by QuellaZhang** [comment]
Closed.
