### ISSUE TITLE
Chakra failed with error C4596 when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/ChakraCore#4849]
Chakra failed with error error C4596: '{ctor}': illegal qualified name in member declaration when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**
1.	git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2.	Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\Chakra\src
3.	set  _CL_=-wd4471 /permissive-
4.	msbuild /m /p:Platform=x86 /p:Configuration=Test /p:WindowsTargetPlatformVersion=10.0.16299.0 Build\Chakra.Core.sln /t:Rebuild

**Error info:**
D:\Chakra\src\lib\Runtime\PlatformAgnostic\Platform\Windows\HiResTimer.cpp(25): error C4596: '{ctor}': illegal qualified name in member declaration 
D:\Chakra\src\lib\Runtime\PlatformAgnostic\Platform\Windows\HiResTimer.cpp(71): error C4596: 'QuantizedQPC': illegal qualified name in member declaration

**Comment by Penguinwizzard** [comment]
Woops, my bad.

**Comment by PhoebeHui** [comment]
The toolset is released, you can could fix this issue.

**Comment by Penguinwizzard** [comment]
Fixed in 1fc4e1f.
