### ISSUE TITLE
What mitigations have been added for Spectre/Meltdown

### ISSUE THREAD

**Issue by crdumoul** [Microsoft/ChakraCore#4859]
I found this commit, where some JIT mitigations were added for Spectre:
https://github.com/Microsoft/ChakraCore/commit/08b82b8d33e9b36c0d6628b856f280234c87ba13

I'm interested in understanding, practically, what these changes protect against and don't protect against. Is there any writeup or description anywhere explaining the mitigations that have been added? Are there any other mitigations related to Meltdown/Spectre that have been added but are not included in this commit?

Thanks,
Chris

**Comment by crdumoul** [comment]
Related to this, I see in this blog post on Microsoft Edge mitigations they describe "reducing the resolution of performance.now() in Microsoft Edge and Internet Explorer from 5 microseconds to 20 microseconds, with variable jitter of up to an additional 20 microseconds."

Is the resolution and jitter of performance.now() a simple runtime or build-time setting that is configurable within ChakraCore?

**Comment by jackhorton** [comment]
@MikeHolman ?

**Comment by MikeHolman** [comment]
ChakraCore doesn't implement performance.now (it's a web API implemented by the host).

However, we added 1ms jitter for Date.now here https://github.com/Microsoft/ChakraCore/commit/72548574a0a25368399fa7cc53fe02b54c268b8a. We also disabled SharedArrayBuffers.

These mitigations are intended to make Spectre impractical by removing high performance timers.

The JIT mitigations are a further defense in depth measure against variant 1. They protect against speculative out of bounds reads in JIT code, so that speculative paths will load 0 instead of OOB.

**Comment by xtuc** [comment]
As far as I can see in the https://github.com/Microsoft/ChakraCore/commit/08b82b8d33e9b36c0d6628b856f280234c87ba13 commit, you are adding cache poisoning after some execution. Is that documented somewhere? Or where could we find more information about that?

**Comment by crdumoul** [comment]
@MikeHolman the 1ms jitter implemented in https://github.com/Microsoft/ChakraCore/commit/72548574a0a25368399fa7cc53fe02b54c268b8a is in Platform/Windows/HiResTimer.cpp, does that mean it only applies to running ChakraCore on Windows?

**Comment by MikeHolman** [comment]
@xtuc You basically have it right. We added the poisoning around risky speculation, in particular type checks and indexed property loads. Right now there isn't any further documentation. I don't know if we have any plans to put up a blog post or anything.

**Comment by MikeHolman** [comment]
@crdumoul It does look like 1ms jitter is there only on Windows. @Penguinwizzard Would it be feasible to move this into common code?

**Comment by xtuc** [comment]
@MikeHolman Ok. It's not surprising because it's a security fix which should remains pretty private. But if it's not I would love hearing more from you.

**Comment by Penguinwizzard** [comment]
@MikeHolman possibly, but there's a couple windows library calls for which I'd have to look at the PAL implementations to see if they're sufficient, or look for other alternative calls if they aren't present there/don't suffice.
