### ISSUE TITLE
Clearing a context via JSRT API

### ISSUE THREAD

**Issue by basdl** [Microsoft/ChakraCore#4875]
Hi,

I hope this is the right place to ask this question, but anyways: I created a lot of contexts via the JSRT API and I am wondering how the memory and resources allocated for that context gets cleaned up. The JSRT API doesn't have anything like clear context. Is the context garbage collected?

Thanks for the answer...

**Comment by liminzhu** [comment]
It is indeed garbage collected. As long as a context is not set as current context of the runtime or intentionally pinned through JsAddRef, GC will be able to collect it.
