### ISSUE TITLE
ChakraCore binary install script is inaccessible

### ISSUE THREAD

**Issue by vikrem** [Microsoft/ChakraCore#4883]
Trying to access `https://aka.ms/chakracore/install` gives an error:
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:...
Time:...</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was r
2017-02-22T15:31:00Z
2050-01-01T00:01:00Z
/file/chakratestx/chakrashare/share/install_ch.sh



2015-12-11




</AuthenticationErrorDetail></Error>
```

**Comment by liminzhu** [comment]
@dilijev @MSLaguana who owns this now?

**Comment by MSLaguana** [comment]
I was hoping that you might. @sethbrenith and myself checked and we don't have permissions for the `chakracore/install` link.

**Comment by dilijev** [comment]
@obastemur can you give us some context on this?

**Comment by dilijev** [comment]
(FWIW aka.ms doesn't give me any entry for that URL, let alone one I can edit, which either means the link registration is private or the link disappeared?)

**Comment by dilijev** [comment]
Not really a build bug but that seems pretty close. This URL is referenced from here:
https://github.com/Microsoft/ChakraCore-wiki/blob/82203f28fd67e1947b2d9de1cea37b7d70f46896/Getting-ChakraCore-binaries.md

**Comment by obastemur** [comment]
Looks like the certificate for early urls are expired. I’m taking a look at

**Comment by obastemur** [comment]
Updated both `install` and `version` aka.ms certs. Also added @dilijev , @sethbrenith  and @MSLaguana  as other owners. @vikrem Thanks! for reporting this, it should be fixed now.
