### ISSUE TITLE
Edge getting stuck now and then.

### ISSUE THREAD

**Issue by Iridesscent** [Microsoft/ChakraCore#4903]
My Edge easily getting stuck when open several pages with a high CPU consuming. i can still select different page but no page can respond my operation anymore.
Edge might back online with a loooooong time wait.

<img width="1015" alt="pic" src="https://user-images.githubusercontent.com/12831220/38092922-1f5f4186-339c-11e8-9792-2b5f7c734de9.png">

OS: Surface Laptop & Win10 Pro

**Comment by jackhorton** [comment]
You can also file feedback using the feedback hub, and it'll give the team a bit more context to help them resolve the issue. Going to close this for now.
