### ISSUE TITLE
Indexed/Named property API 

### ISSUE THREAD

**Issue by NDobrev** [Microsoft/ChakraCore#4904]
Hi,

I hope this is the right place to ask this question, I am trying to implement Array/Map like object, but I can't find how to set Indexed/Named Property  getter /setter callback or something similar to that. JsDefineProperty doesn't look very useful in my case.
For example if I have:
var obj = new MyCppObject();
obj[3] = 4;  <- I want to intercept this and run my c++ code.
obj["newProp"] = 4 <- and this too (where newProp is not part of my object prototype)

Can anyone share what is the best way to achieve this with public API. I can use js Proxy object, but looks like very poor decision.

**Comment by MSLaguana** [comment]
What you probably want to do here is use a Proxy, which has native methods implementing the different proxy hooks. If you're willing to take a look at some code, you could see how we do that sort of thing in node-chakracore around https://github.com/nodejs/node-chakracore/blob/master/deps/chakrashim/src/v8objecttemplate.cc#L857, in particular https://github.com/nodejs/node-chakracore/blob/master/deps/chakrashim/src/v8objecttemplate.cc#L901-L952
