### ISSUE TITLE
Error SCRIPT1003: Expected ':'  This is when object deconstruction is used with default values as a function parameter

### ISSUE THREAD

**Issue by psavur** [Microsoft/ChakraCore#4919]
Example:
 Open this in Edge, you will see an error in console
 Fiddle: https://jsfiddle.net/c8rfL49t/4/

`
function getHelloFn() {
  const helloFn = ((cacheAccessor2, { name = "foo" }) => {
    
  });
  return helloFn;
}
`

Version: Microsoft Edge 41.16299.248.0
Same works fine in other browsers (Chrome, Firefox, IE11)

**Comment by liminzhu** [comment]
Can confirm the same behavior in EdgeHTML 17 in the latest insider build. We should look into this @curtisman .

**Comment by akroshg** [comment]
I think it is issue with arrow function. As we do reparsing due to arrow function - some of the bookkeeping went wrong.
this seems fine
```js 
let b = function(o, {name = 'foo'}) {};
```
Assigning it to myself.

**Comment by akroshg** [comment]
@psavur thanks for reporting this issue.
It is fixed now.
