### ISSUE TITLE
Intl-ICU: String.prototype.localeCompare(other) is 4x slower than with WinGlob

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#4921]
The simplest of microbenchmarks for proof:

```js
const start = Date.now();
let result = 0;
for (var i = 0; i < 1e5; ++i) {
    result -= "a".localeCompare("A");
}
const end = Date.now();

print(`Elapsed: ${end - start}, result: ${result}`);
```

This takes ~22ms in WinGlob and ~100ms in ICU on my machine using jshost.exe x64_test_pogo. 

For a real world case, this 4x regression is visible in a 70% regression in JetStream's CDjs benchmark, which uses localeCompare for comparing nodes in a particularly hot red-black tree.

**Comment by jefgen** [comment]
From offline discussion, it seems that the collator isn't being cached and is recreated every time. Lazy-initiation of the collator and caching would likely greatly help with the performance. :)
