### ISSUE TITLE
Rename MarkStack_OOM_fatal_error and OutOfMemory_fatal_error

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#4927]
The string "fatal" in these symbols triggers !analyze to skip these frames when looking for blame frames. We should choose new names that do not include "fatal" to play nice with !analyze.

**Comment by curtisman** [comment]
We need to choose a name that !analyze won't ignore.

**Comment by irinayat-MS** [comment]
Because the OOM frame is ignored, heap corruptions and OOM failures might end up being bucketed together (as they are attributed to down level symbols such as HeapAllocator::AllocZero). We'd like to have a separate signal for heap corruptions.

**Comment by irinayat-MS** [comment]
Other methods with _fatal_ substr in their names. Should fix all of them?

core\lib\Common\CommonDefines.h:#define TTDAssert(C, M) { if(!(C)) TTDAbort_fatal_error(M); }
core\lib\Common\Exceptions\ReportError.h:void JavascriptDispatch_OOM_fatal_error(
core\lib\Common\Exceptions\ReportError.h:void CustomHeap_BadPageState_fatal_error(
core\lib\Common\Exceptions\ReportError.h:void Amd64StackWalkerOutOfContexts_fatal_error(
core\lib\Common\Exceptions\ReportError.h:void FailedToBox_OOM_fatal_error(
core\lib\Common\Exceptions\ReportError.h:void X64WriteBarrier_OOM_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void DebugHeap_OOM_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void MarkStack_OOM_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void Binary_Inconsistency_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void Version_Inconsistency_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void EntryExitRecord_Corrupted_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void UnexpectedExceptionHandling_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void FromDOM_NoScriptScope_fatal_error();
core\lib\Common\Exceptions\ReportError.h:void Debugger_AttachDetach_fatal_error(HRESULT hr);
core\lib\Common\Exceptions\ReportError.h:void RpcFailure_fatal_error(HRESULT hr);
core\lib\Common\Exceptions\ReportError.h:void OutOfMemory_fatal_error();
core\lib\Common\Exceptions\Throw.h:#define DEBUGGER_ATTACHDETACH_FATAL_ERROR_IF_FAILED(hr) if (hr != S_OK) Debugger_AttachDetach_fatal_error(hr);
core\lib\Common\Memory\HeapAllocator.h:            DebugHeap_OOM_fatal_error();
core\lib\Common\Memory\HeapAllocator.h:            DebugHeap_OOM_fatal_error();
core\lib\Runtime\Debug\TTSupport.h:void _NOINLINE __declspec(noreturn) TTDAbort_fatal_error(const char* msg);
private\bin\ChakraDiag\DAC.h:void DebugHeap_OOM_fatal_error();
