### ISSUE TITLE
Do you have plan to support native (or without transpiling) TypeScript in ChakraCore?

### ISSUE THREAD

**Issue by zbitname** [Microsoft/ChakraCore#494]

**Comment by anthrax63** [comment]
+1It would be great

**Comment by huodon** [comment]
+1 
We need full native TypeScript supported dev platform alter node.

**Comment by bterlson** [comment]
There are no plans. You can read about our plans on the [roadmap](https://github.com/Microsoft/ChakraCore/wiki/Roadmap). Thanks!
