### ISSUE TITLE
Issue in loading data

### ISSUE THREAD

**Issue by Shivani-Sengar** [Microsoft/ChakraCore#4950]
Error Details:
Activity ID69a92aeb-0f68-4906-c5db-c965e1fd6f16
Request IDa4b98965-1797-5319-d3ed-1701c8ac76cc
Correlation IDcb7af31b-5bb7-f696-d17b-c45ba618eeac
Status code500
TimeSun Apr 08 2018 20:04:35 GMT+0530 (India Standard Time)
Version13.0.4898.201
Cluster URIhttps://wabi-us-north-central-redirect.analysis.windows.net

**Comment by jackhorton** [comment]
Not sure what the issue is here... could you clarify?

**Comment by dilijev** [comment]
Status code 500 is internal server error. I got 403 Forbidden for that URL (https:// wabi-us-north-central-redirect.analysis.windows.net). This doesn't seem to be a Chakra or ChakraCore issue.
