### ISSUE TITLE
Hosting: How to prevent Sporadic Read Access Violation

### ISSUE THREAD

**Issue by basdl** [Microsoft/ChakraCore#4960]
Hi,

I am hosting a multi-context, single runtime ChakraCore in my C++ application. I provide a "setInterval" method just as in a browser. In my C++ code I hold the reference to the javascript callback combined with the calling context,. I have a single thread which checks whether an interval elapses. When it does, I set the according context as the current one and trigger the JS callback. Unfortunately, when I have multiple short intervals at some point the code raises an "Read Access Violation" exception (most of the time when setting the current context, but also sometimes when doing the callback). There is just this single "timer" thread communicating with the engine.

As what I have seen from the examples, I guess this is the right way to implement a setInterval right? Is there some other obvious things which I haven't done yet do make it work correctly?

**Comment by liminzhu** [comment]
When you hold on to the reference of the callback, do you have a JsAddRef call on it to make sure it isn't GC'ed? We have an implementation of setInternal in the samples. See [1](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/ChakraCoreHost.cpp#L254) [2](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/Task.cpp#L16).

**Comment by basdl** [comment]
Awesome thanks! That solved my issue :) :+1:
