### ISSUE TITLE
Compile failed with build.sh and clang 6.0

### ISSUE THREAD

**Issue by summershrimp** [Microsoft/ChakraCore#4961]
It seems that clang treat all enum variable as unsigned, so compare unsigned to 0 should always be >= 

```
[  0%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.Singular.dir/shmemory/shmemory.cpp.o
/home/xm1994/ChakraCore/pal/src/shmemory/shmemory.cpp:904:16: error: comparison of unsigned enum expression < 0 is always false [-Werror,-Wtautological-unsigned-enum-zero-compare]
    if(element < 0 || element >= SIID_LAST)
       ~~~~~~~ ^ ~
/home/xm1994/ChakraCore/pal/src/shmemory/shmemory.cpp:946:16: error: comparison of unsigned enum expression < 0 is always false [-Werror,-Wtautological-unsigned-enum-zero-compare]
    if(element < 0 || element >= SIID_LAST)
       ~~~~~~~ ^ ~
2 errors generated.
```

**Comment by obastemur** [comment]
@summershrimp thanks for reporting this. Would you like to contribute the fix? just remove the `element < 0 || ` part from both of them and shoot the PR ?

**Comment by summershrimp** [comment]
@obastemur Would this affect other compiler？ Just wondering why somebody write a enum var < 0 here.

**Comment by obastemur** [comment]
@summershrimp I don't see a reason to break and I'm not sure the original intention though

**Comment by summershrimp** [comment]
@obastemur Okay, I will make a PR off duty.

**Comment by fatcerberus** [comment]
I think MSVC treats enum variables as signed (even if the enum is zero-based) while GCC/clang treats them as unsigned.  I have similar checks to this in my own code and clang annoyingly warns me about them too.
