### ISSUE TITLE
super() call breaks when extending legacy classes

### ISSUE THREAD

**Issue by WebReflection** [Microsoft/ChakraCore#4970]
When a legacy, empty, constructor does not explicitly return `this`, usually considered a redundant operation pretty much nobody wrote in ES3 to ES5.1 times, the `super()` call in MS Edge breaks like a charm, considering `undefined` a valid return value for a `super()` call, instead of the current context.

You can [test this in Code Pen](https://codepen.io/WebReflection/pen/pLYBea?editors=0010) or through Edge HTML console.

```js
function OldSchool() {}
function OldSchoolReturn() { return this; }
OldSchool.prototype.method =
OldSchoolReturn.prototype.method = function () {
  document.body.appendChild(
    document.createElement('p')
  ).textContent = this.constructor.name;
};
class Shenanigans extends OldSchool {
  constructor() {
    try { super().method(); }
    catch (o_O) { console.error(o_O); }
  }
}
class ShenanigansReturn extends OldSchoolReturn {
  constructor() {
    try { super().method(); }
    catch (o_O) { console.error(o_O); }
  }
}
new Shenanigans;
new ShenanigansReturn;
```

Thanks for fixing this.

**Comment by bterlson** [comment]
I think this is https://github.com/Microsoft/ChakraCore/issues/4663?

I'm not sure when that fix will make it into insider builds. Perhaps @liminzhu can comment.

**Comment by WebReflection** [comment]
@bterlson yes, absolutely that one. I swear I've searched for `super()` and nothing came out ... but of course 'cause I've checked opened bugs only.

Glad to know it's fixed already. Thank you.
