### ISSUE TITLE
 bound proxy - Regression since 1.7

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4989]
......

**Comment by dilijev** [comment]
Looks like it did not crash in 1.7 but does crash in latest 1.8.

(No output implies crash before reaching the `print("DONE")`.)

```
## Source
function a(arg1, arg2) {
    this[arg1] = arg2;
}
const b = new Proxy(a, {
    construct: function (x, y, z) {
     return {};
  }
});
const boundObject = {};
const c = b.bind(boundObject, "prop-name");
function newTarget() {}
const obj = Reflect.construct(c, ["prop-value-2"], newTarget);
print("DONE")

#### ch-1.8-latest, ch-master-latest, jsvu-ch


#### ch-1.7-latest, jsvu-d8, jsvu-jsc, jsvu-sm
DONE
```

**Comment by dilijev** [comment]
Confirmed with a larger set of builds.

```
#### ch-1.8-latest, ch-1.8.0, ch-1.8.1, ch-1.8.2, ch-1.8.3, ch-master-latest, jsvu-ch


#### ch-1.7-latest, ch-1.7.4, ch-1.7.5, ch-1.7.6, jsvu-jsc, jsvu-sm, jsvu-v8
DONE
```

**Comment by rhuanjl** [comment]
I'll see if I can ind the commit that introduced this regression, I think it may be to do with one of the parameters somehow becoming a nullptr.

**Comment by rhuanjl** [comment]
Issue is with when a bound function has:
a) "extra arguments" FrameDisplay or New.Target object. AND
b) 1 or more bound arguments

In these cases the extra argument was not being copied into the new arguments object used for calling the actual function BUT the call flag to say it existed was being set - so CC could then attempt to access that non-existent extra argument (normally new.target) and segfault.
