### ISSUE TITLE
Cannot build ChakraCore in debug mode in MSVC

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#4991]
ChakraCore MSVC debug build (x64) currently fails with the following errors/warnings:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'ENABLE_VIRTUAL_TERMINAL_PROCESSING': undeclared identifier	wabt	d:\src\chakracore\lib\wabt\src\color.cc	57	
Warning	MIDL1007	switch specified more than once on command line : target	Chakra.JITIDL	D:\src\ChakraCore\lib\JITIDL\midl	1	
Error	C2660	'SetConsoleMode': function does not take 1 arguments	wabt	d:\src\chakracore\lib\wabt\src\color.cc	57	
Error	LNK1181	cannot open input file 'D:\src\ChakraCore\Build\VcBuild\obj\x64_debug\wabt\wabt.lib'	ChakraCore	D:\src\ChakraCore\bin\ChakraCore\LINK	1	
Error	LNK1181	cannot open input file 'D:\src\ChakraCore\Build\VcBuild\bin\x64_debug\ChakraCore.lib'	NativeTests	D:\src\ChakraCore\bin\NativeTests\LINK	1	
Error	LNK1181	cannot open input file 'D:\src\ChakraCore\Build\VcBuild\bin\x64_debug\ChakraCore.lib'	ch	D:\src\ChakraCore\bin\ch\LINK	1	
```

Release build is fine.

**Comment by digitalinfinity** [comment]
Hi @fatcerberus - which version of VC++ and the Windows SDK are you using, and which branch? I see that https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/x64_debug/ indicates that the master branch is currently building fine, and our internal build pages are showing green as well.

As far as I can tell, the file in question hasn't been changed in a while. @Cellule can you take a look here and see if I missed something obvious?

**Comment by fatcerberus** [comment]
master branch, nothing unusual there.  MSVC version is 2017 v15.6.6.  Not sure on Windows SDK version as I used the default config when installing but I assume it’s the correct one since the release build works...

**Comment by Cellule** [comment]
Release build is fine because we don't build `wabt` in Release builds.
It seems that your version of the SDK doesn't support Virtual Terminal for console coloring.
However, I don't think we really need it in our project.

You can try to change 
`#define HAVE_WIN32_VT100 1` to `#define HAVE_WIN32_VT100 0` in [config.h](https://github.com/Microsoft/ChakraCore/blob/a1d1dd8a92ffb60b1d15226c8d22ba2b496402b8/lib/wabt/chakra/windows/config.h#L41)
I'll see if we can disable this to support more sdk versions

**Comment by fatcerberus** [comment]
Is this a recent change?  This is a clean checkout of CC and I used to be able to build debug builds okay...
