### ISSUE TITLE
Infinite loop in get property for shared deferred types

### ISSUE THREAD

**Issue by kfarnung** [Microsoft/ChakraCore#4997]
While investigating another issue I came across the following situation:

```javascript
function foo() {
    function bar() {
        // Deferred function   
    }

    return bar;
}

// Create two deferred functions
var func1 = foo();
var func2 = foo();

// Set the prototype of `func2` to `func1`
Object.setPrototypeOf(func2, func1);

// Set a property of `func2` first causing it to be undeferred
func2.x = 1;

// Set a property of `func1` second causing it to share the type of `func2`
func1.x = 2;

// Try to access an undefined property, this will loop infinitely
console.log(undefined === func1.y);
```

What appears to be happening is that since the types of `func1` and `func2` are deferred, the order that they are undeferred can create a self-referential prototype loop.  From what I was seeing when `func2` gets undeferred it will create a type with a prototype pointing to `func1` (which is still deferred). When `func1` finally gets undeferred the type sharing logic ends up assigning the type of `func2` to `func1`.  Since `func2.__proto__ === func1` it creates a reference loop where `func1.__proto__ == func1`.

The infinite loop occurs when accessing a non-existent property of `func1`, the function `chakracore!Js::JavascriptOperators::GetProperty_Internal<0>` tries to search the prototype chain, but never finds an terminating condition.

Thanks @digitalinfinity and @boingoing for the investigation help!

**Comment by kfarnung** [comment]
@pleath Can you take a look?

**Comment by kfarnung** [comment]
This may have been caught more easily with a new assert in `DynamicObject::ReplaceType` which ensures that the `prototype` doesn't match the `this` pointer.

**Comment by pleath** [comment]
...or that "this" doesn't appear anywhere in the prototype chain starting with the new type. (I think the language allows us to reject Object.setPrototypeOf calls that create cycles.)

**Comment by MSLaguana** [comment]
Yeah, currently if you try to create a cycle via `Object.setPrototypeOf` you get an error thrown.
