### ISSUE TITLE
Native background processing + ChakraCore Promise API

### ISSUE THREAD

**Issue by vikrem** [Microsoft/ChakraCore#5013]
Hi all,

I'm looking for a bit more clarity on using the JSRT Promise API.

I've read the Promise overview in the embedded JSRT overview (https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#promises)
and the PR involving JsCreatePromise (https://github.com/Microsoft/ChakraCore/pull/2581#issuecomment-281875736)

From what I've gathered so far, the following process is sane:

- ChakraCore makes a function call to native code
- The native code creates promise, resolve, and reject value refs, with JsCreatePromise.
- The native code can block here as it calculates something expensive, and then can JsCallFunction the resolve ref, with the expensive calculation as a parameter.
- The native code can then return the promise object back to ChakraCore, and JS execution will resume.
- After JS script execution has finished, the native host will process all items produced by the EnqueuePromiseCallback, in FIFO order.
- JS evaluation is now complete.

This does work, though the native code blocks script execution during its expensive computation. Wanting a better approach, I try this method:

- ChakraCore makes a function call to native code
- The native code creates promise, resolve, and reject value refs, and adds a reference to each to prevent Chakra from garbage collecting them.
- The native code forks a background thread. This thread will compute an expensive operation, and then execute the resolve function with JsCallFunction
- The native code does not wait for the background thread to complete. It returns the promise object back to Chakra immediately.
- ...

This doesn't work. JS execution, including the EnqueuePromiseCallback processing, can complete and terminate before the background thread is ready to resolve the promise, at which point the runtime can already have been cleaned up, and the refs invalidated (despite JsAddRef-ing the refs)

Afaict ChakraCore doesn't have specific provisions for evaluating promises in this manner.
Instead, the host must implement its own eventloop, that waits for pending native background tasks to finish completing and calls into their respective resolve functions, after initial script execution and EnqueuePromiseCallback processing.

Is this thinking correct? Are there any code examples of this?

**Comment by jackhorton** [comment]
I believe the way this should, if not must, work is to use an event loop, similar to how Node.js uses libuv. Basically the event loop keeps looping until it gets word back from the background thread about a piece of queued work finishing. When that piece of work finishes, the native code will call back into javascript (in your case, it will call resolve or reject, basically), at which point javascript will continue executing synchronously until it runs out; then the event loop regains control, starts a new tick, checks for work, etc. The devil is in the details and there may be a simpler way to do it for smaller applications, but I believe this is the general gist of how Node and major browsers work. https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop may be a more generic overview, and searching for "node event loop" yields numerous high quality resources on how these things work, even if not how to implement them.
