### ISSUE TITLE
crash running System.Core under mono+wasm

### ISSUE THREAD

**Issue by kumpera** [Microsoft/ChakraCore#5015]
Found during CI of mono WebAssembly.
This is on 64bits linux and ChakraCore 1.8.3.

Build log: https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/7/parsed_console/log.html

Error:
```
WASM: TestToList 66/1183
WASM: TestToListOrdered 66/1184
WASM: UnorderedTakeTestCase 66/1185
WASM: WhereTestCase 66/1186
WASM: ZipTestCase 66/1187
WASM: CtorNull 66/1188
WASM: DefaultCtor 66/1189
WASM: TransformCtor 66/1190
make[1]: *** [run-ch-system-core] Segmentation fault (core dumped)
make: *** [run-all-system-core] Error 2
```

To reproduce it you need to build & run mono in the wasm configuration.
Instructions here:  https://github.com/mono/mono/blob/master/sdks/wasm/README.md

**Comment by VSadov** [comment]
the log seems missing.

**Comment by jackhorton** [comment]
@Cellule may know more about this

**Comment by MikeHolman** [comment]
This is a bug with SWB, which assumes any pointer size write to a field is updating a recycler Object (which is not the case in wasm). Consequence is writing to the card table at an invalid index.
