### ISSUE TITLE
Add FailFast that triggers when commit reaches "unreasonably large" value like 3GB

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#5031]
Should be something embedders can disable without rebuilding.

**Comment by curtisman** [comment]
@VSadov can you take a look at this.  Thanks.

**Comment by VSadov** [comment]
Will take a look. Can't assign to myself yet though...

**Comment by VSadov** [comment]
Is that in addition to `JsSetRuntimeMemoryLimit` or to change the behavior to track committed memory?

I think it might be more common to care about committed size than about reserved VM.

**Comment by MSLaguana** [comment]
Currently we have configurable behavior on OOM; by default we failfast on OOM, so this might be exactly the right mechanism here.

**Comment by VSadov** [comment]
Yes, we do currently failfast on OOM. I can't find where the behavior is configurable though. Is that through some JsRt ?

**Comment by MSLaguana** [comment]
It's controlled through `EnableFatalErrorOnOOM` in https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/ConfigFlagsList.h#L1172

In debug and test builds you can pass flags to chakracore to toggle that value, but in release builds it looks like we don't allow configuring it without recompiling.

**Comment by VSadov** [comment]
Yes, just found it - `JsRuntimeAttributeDisableFatalOnOOM`

**Comment by VSadov** [comment]
`JsCreateRuntime` can pass the attributes. I do not think it requires rebuilding, but the behavior is set once the runtime is created. Host still can change the limit.

**Comment by VSadov** [comment]
I think we actually have all what is requested in the bug. 

The only caveat is that the default limit is `-1` , which is `unlimited` and that is what documentation specifies, so I am not sure we want to change that.

Perhaps we just want to set the limit to be 3GB in `ch.exe` and tell hosters to do the same?
