### ISSUE TITLE
Unary plus with invalid hexadecimal value

### ISSUE THREAD

**Issue by igor-simoes** [Microsoft/ChakraCore#5038]
Hi everyone,
I found this inconsistency when I try to use unary plus with invalid hexadecimal value.

OS: ubuntu 16.04 x86
chakra: 1.9

Steps to reproduce:
```
var a = +"\x00";
if (a===0) {
    throw new Error("expected NaN but found 0");
}
```
Actual results:
Error: expected NaN but found 0

Expected results:
Pass without failures

According to documentation [Unary plus](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_()) `If it cannot parse a particular value, it will evaluate to NaN`. The others engines (V8, SpiderMonkey and JavascriptCore) pass without failures, but chakra recognize '\x00' as a null object.

**Comment by fatcerberus** [comment]
Note that the repro above is incorrect: it will always throw because nothing is === NaN, including NaN itself.

**Comment by igor-simoes** [comment]
Yep, my fault. Sorry about that.
