### ISSUE TITLE
Global object with a custom prototype

### ISSUE THREAD

**Issue by adudov** [Microsoft/ChakraCore#5068]
Is it possible to make a global object with a custom prototype?
If so, how?

**Comment by liminzhu** [comment]
You can set prototype to any custom object you want through either JS or native in ChakraCore, given the host doesn't prevent you from doing this by e.g. freezing the global object.

```js
Object.setPrototypeOf(this, customProto);
```

or equivalently

```c++
JsValueRef global, customProto;
JsGetGlobalObject(&global);
JsSetPrototype(global, customProto);
```

**Comment by adudov** [comment]
Thank you for the response, we do it exactly that way(via C++), but we have a problem:

We set the prototype of the global object to be the one of our window object.
We added a property called "window" to the global object with a value the global object itself.

We added some of the window methods like this:
```
JsPropertyIdRef propertyId;
JsValueRef function;
JsCreateFunction(&setTimeoutCallback, nullptr, &function);
JsCreatePropertyId("setTimeout", 10, &propertyId);
JsSetProperty(windowObject, propertyId, function, true);
```

and we have a page with the following:
```
<script>
  setTimeout(function() { }, 1);
</script>
```

The `setTimeoutCallback` method is called, but the first argument(which should be the 'this' object) is not a pointer to the global object but a pointer with an offset(0x4030 if that matters) from the global object.

If we change it to:
`window.setTimeout(function() { }, 1);`
or
`this.setTimeout(function() { }, 1);`
The first argument is the right one, i.e. a pointer to the global object.


We tried also to change the adding of the 'setTimeout' method to be via a property descriptor with a 'get' function - e.g. `SetTimeoutGetter`.
Inside the `SetTimeoutGetter` we create the js function(like above) and return it.
The `SetTimeoutGetter` is called with the correct argument(a pointer to the global object) but `setTimeoutCallback` is not (again, the pointer is with an offset).

**Comment by liminzhu** [comment]
Yeah this is the same as https://github.com/Microsoft/ChakraCore/issues/3276. Basically a better description of what `args[0]` would be what's literally on the LHS. In your case if you call `setTimeout`, you'd get `undefined` as `args[0]`. Try `window.setTimeout` you will get `window` back.

I will update the documentation to make it more explicit.

**Comment by adudov** [comment]
Thank you for the response. 
But, it is not the same behaviour as in some other virtual machines, like V8 or JavaScriptCore. There if you just call a global object's method, i.e. if you call it plainly - you are getting the correct 'this' object(the global object).
It will be really very convinient for embedders.

**Comment by liminzhu** [comment]
Sorry for the late response @adudov . I do appreciate the feedback, but it's a bit hard for us to do since this behavior existed for many years in both ChakraCore and Chakra and changing it may break some other folks (this is especially bad for Chakra b/c of windows backwards compatibility). We'd always want to interop with other VMs in terms of JavaScript support, for hosting APIs it's more of a nice-to-have thing, plus dealing with multiple VMs isn't that common for most embedders afaik. 

I think when there's enough demand and scenarios driving us, we may consider a new API, but for now I'd love to just table it.
