### ISSUE TITLE
WASM: Global SIMD incorrectly handled

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#5078]
It looks like we don't handle global simd correctly.
It is unclear if global simd are allowed, but regardless we are missing explicit checks of the globals we support and this can lead to all sort of badness.
Either properly support global simd or make sure we have a compile error if the user tries to use global with the simd type

**Comment by arunetm** [comment]
ref: https://github.com/WebAssembly/simd/issues/9

**Comment by lizhengxing** [comment]
Hi, Cellule:
I will work on this issue. Could you assign it to me?
Thanks!

@arunetm FYI!

**Comment by lizhengxing** [comment]
Hi, Michael:

   The initial PR for this issue was done. the implementation is based on Arun's proposal on github.
   1. In WebAssemblyInstance::LoadImports()
       a) Check the signature of the imported functions, if encounter a simd value, throw error.
       b) Check the imported variable type, if a simd value, throw error.

   2. In WebAssemblyInstance::CreateExportObject()
       a) Check the signature of the exported functions, if encounter a simd value, throw error.
       b) Check the exported variable type, if a simd value, throw error.

The PR is at: https://github.com/Microsoft/ChakraCore/pull/5100

**Comment by lizhengxing** [comment]
It seems that global exported simd variable will be checked earlier in WebAssemblyInstance::InitialGlobals().
In current WebAssemblyInstance::InitialGlobals(), it will throw the error when encountering simd or I64 variable.

Anyway, I still add the global simd variable checks in  WebAssemblyInstance::CreateExportObject().
