### ISSUE TITLE
No TypeError thrown in strict mode when Proxy set trap returns falsy

### ISSUE THREAD

**Issue by fasttime** [Microsoft/ChakraCore#5084]
As the title says. The following snippet should throw a `TypeError`, and it does so in most JS engines but not in Chakra/Edge.

```js
(() => { 'use strict'; (new Proxy({ }, { set() { } })).foo = 1; })();
```

I noticed this behavior in previous versions already, but could reproduce it in current `Microsoft Edge 42.17134.1.0` `Microsoft EdgeHTML 17.17134`.

**Comment by dilijev** [comment]
Confirmed repro:

```
## Source
(() => { 'use strict'; (new Proxy({ }, { set() { } })).foo = 1; })();
print('DONE')


#### jsvu-d8
TypeError: 'set' on proxy: trap returned falsish for property 'foo'

#### jsvu-sm
TypeError: proxy set handler returned false for property '"foo"'

#### jsvu-ch, jsvu-jsc
DONE
```

**Comment by fasttime** [comment]
I think the relevant spec is in **PutValue** (6.2.4.9 step 6. c.): https://tc39.github.io/ecma262/#sec-putvalue

> If succeeded is **false** and IsStrictReference(V) is **true**, throw a **TypeError** exception.

The **PutValue** operation itself is called when performing the assignment (12.15.4 step 1. f. in my example): https://tc39.github.io/ecma262/#sec-assignment-operators-runtime-semantics-evaluation

> Perform ? PutValue(lref, rval).

So it's not evaluating the trap that should throw an error according to the spec, but rather performing the assignment in strict mode.

But I'm not familiar with the Chakra code, so I can't really say what makes more sense from the implementation point of view.

**Comment by akroshg** [comment]
This is fixed.
