### ISSUE TITLE
Chakra should throw TypeError if [[OwnPropertyKeys]] returns duplicate entries

### ISSUE THREAD

**Issue by acaroliny** [microsoft/ChakraCore#5087]
Hello,
according ES6 specification (https://github.com/tc39/ecma262/pull/833), the engine should throw a TypeError if ownKeys have duplicate entries.

OS = Ubuntu 17.10 x64
ChakraCore: 1.10.0.0-beta

Steps to reproduce:

var proxy = new Proxy({}, {
    ownKeys: function (t) {
        return ["A", "A"];
    }
});
var keys = Object.keys(proxy);

Actual results:
Pass without failures

Expected results:
TypeError: proxy [[OwnPropertyKeys]] can't report property '"A"' more than once

Actually, only SpiderMonkey supports this specification. V8 have an open issue (https://bugs.chromium.org/p/v8/issues/detail?id=6776).

**Comment by dilijev** [comment]
Confirmed with spec:

https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods

> ECMAScript Proxy objects maintain these invariants by means of runtime checks on the result of traps invoked on the [[ProxyHandler]] object.

> [[OwnPropertyKeys]] ( )

> * The returned list must not contain any duplicate entries. 

From what I can tell it doesn't require that it throw a `TypeError`, but that seems reasonable.

**Comment by fatcerberus** [comment]
I personally would read that spec text as implying an exception of some sort should be thrown - otherwise why specify the invariant at all?

**Comment by dilijev** [comment]
@fatcerberus yes I agree it implies we should throw something, I was just saying the spec doesn't specify that `TypeError` in particular should be that thing.

**Comment by fatcerberus** [comment]
Reading more into the specification text, it looks like the spec wants to treat violations as undefined behavior:
> Violation of these invariants may cause ECMAScript code to have unpredictable behaviour and create security issues. However, violation of these invariants must never compromise the memory safety of an implementation.

Based on this text, if the invariants are violated then the engine is basically free to do anything it wants as long as memory safety is assured.

On the other hand, the paragraph immediately afterward suggests leniency is not a valid interpretation of the aforementioned UB:
> An implementation must not allow these invariants to be circumvented in any manner such as by providing alternative interfaces that implement the functionality of the essential internal methods without enforcing their invariants.

This is honestly a bit confusing.

**Comment by igor-simoes** [comment]
cinfuzz

**Comment by rhuanjl** [comment]
This has been fixed in master.
