### ISSUE TITLE
Static sized arrays may lead to overflows

### ISSUE THREAD

**Issue by RootUp** [Microsoft/ChakraCore#5090]
Hi Team, 

This issue was observed while analysis of source code : 
`https://github.com/Microsoft/ChakraCore/blob/master/pal/src/thread/process.cpp#L743`

Statically-sized arrays can be improperly restricted, leading to potential overflows or other issues (CWE-119!/CWE-120). Perform bounds checking, use functions that limit length, or ensure that the size is larger than the maximum possible length.

Request to please have a look.

Cheers!

**Comment by MSLaguana** [comment]
Which statically-sized array are you referring to there? I see accesses to the environment (a null-terminated sequence of null-terminated strings) and a dynamically allocated buffer of pointers to those environment strings.

**Comment by sethbrenith** [comment]
Looks fine to me, since we use `snprintf` to ensure that any access to that array is restricted to valid locations.

**Comment by RootUp** [comment]
Then this looks fine to me, closing this issue!
