### ISSUE TITLE
yield* does not forward .next() argument to iterable's .next() call

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#510]
```javascript
// repro, expected to print "X" but prints "undefined"

function* foo() {
    var x = yield 1;
    print(x);
}
function* bar() {
    yield* foo();
}
var it = bar();
it.next();
it.next("X");
```

From VSO bug [6790309](https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=6790309)

This bug repros for any iterable passed to yield*.

**Comment by nicolo-ribaudo** [comment]
Can I work on this issue?

**Comment by ianwjhalliday** [comment]
Sure!  This looks like a bytecode issue so I suggest running the repro with `ch.exe -dump:bytecode` and taking a moment to take all the bytecode in.  `EmitYieldStar(...)` in `ByteCodeEmitter.cpp` is where you'll find the code that emits the bytecode for `yield*`.

I didn't look too closely at it but it seemed it is overwriting the next argument at the top of the loop with undefined always and/or it is missing the logic to get the argument value and load it into the register used for the inner next() call.

I would suggest fixing this issue standalone, and then considering #137 and #139 separately afterwards, if you're interested.

**Comment by ianwjhalliday** [comment]
You might while looking at this also see a solution to #265.  If you do please feel free to tackle that one as well.

**Comment by nicolo-ribaudo** [comment]
I just opened the pr - #525

> it seemed it is overwriting the next argument at the top of the loop with undefined always

The problem was exactly this :+1: 

> You might while looking at this also see a solution to #265. If you do please feel free to tackle that one as well.

I'll comment on the issue in few minutes if I can fix it.

**Comment by ianwjhalliday** [comment]
Thanks for knocking this one off so quickly, @nicolo-ribaudo
