### ISSUE TITLE
Low delay playback of fragmented MP4

### ISSUE THREAD

**Issue by forderud** [Microsoft/ChakraCore#5107]
Other browsers, like. Chrome, contains heuristics to reduce playback delay/latency when encountering fragmented MP4 files with unknown duration. This is typically encountered in live video streaming. Opening a such video will cause `"Video rendering in low delay mode."` to be displayed in the `chrome://media-internals/` page. Edge does not seem to support anything similar, and instead buffers extensively before starting playback.

Chrome implementation:
* Detection logic: https://cs.chromium.org/chromium/src/media/formats/mp4/mp4_stream_parser.cc?type=cs&l=616
* Usage: https://cs.chromium.org/chromium/src/media/renderers/video_renderer_impl.cc?type=cs&l=239

Steps to reproduce:
* Build & run https://github.com/forderud/AppWebStream with "8080" as argument. The FFMPEG-based back-end currently works best.
* Open `localhost:8080` in web browser.
* Observe video latency.

**Comment by sethbrenith** [comment]
Hi @forderud, thanks for the feedback! However, this is not a Chakra issue but an Edge issue- please open an issue at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ and the Edge team members should be able to help you.

**Comment by forderud** [comment]
Thanks.

The issue have now been moved to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17410767/
