### ISSUE TITLE
typeof swallows too much exceptions

### ISSUE THREAD

**Issue by Cellule** [microsoft/ChakraCore#5117]
According to [ecma typeof operator](https://tc39.github.io/ecma262/#sec-typeof-operator) we are never supposed to swallow exceptions.
Instead we should check if the reference exists, if not return `"undefined"` otherwise let all other exceptions flow.

```js
var a = {
  get x() {
    throw new Error("Some error")
  }
};

var p = new Proxy(a, {
  get(obj, prop) {
    if (prop === "x") return obj.x;
    if (prop === "y") return obj.y;
    throw new Error("Another Error");
  }
})

try {console.log(typeof a.x);} catch (e) {console.log(e.message)}
try {console.log(typeof p.x);} catch (e) {console.log(e.message)}
try {console.log(typeof p.y);} catch (e) {console.log(e.message)}
try {console.log(typeof p.z);} catch (e) {console.log(e.message)}

// Excepted Output:
// Some error
// Some error
// undefined
// Another Error

// Actual Output:
// undefined
// undefined
// undefined
// undefined
```

**Comment by Cellule** [comment]
There might be a perf factor where we didn't want to do a 
```if (hasProperty(prop)) return getProperty(prop).type else return "undefined"````
and do instead
```try { return getProperty(prop).type } catch(e) { return "undefined" }```

**Comment by dilijev** [comment]
Dupes:
https://microsoft.visualstudio.com/OS/_workitems/edit/17352551
https://microsoft.visualstudio.com/OS/_workitems/edit/17199641

**Comment by MikeHolman** [comment]
Looks fixed
