### ISSUE TITLE
Can ChakraCore on MacOS be built for arm-Windows platform with VS 2017?

### ISSUE THREAD

**Issue by Funkwai** [Microsoft/ChakraCore#5159]
Can ChakraCore on MacOS be built for arm-Windows platform using Visual Studio Community 2017? e.g. arm Chromebook

I import the Build\Chakra.Core.sln into VS 2017 on MacOS, and seems cannot build, occur "This project type is not supported by Visual Studio Community 2017 for Mac".

Thanks.

**Comment by jackhorton** [comment]
I haven't tested this yet but my initial guess is that Build\Chakra.Core.sln is not intended to work in VS for Mac (I was surprised to hear that VS for Mac uses .sln files at all). It has historically been used only on windows. Normally, we recommend using `build.sh` in the root of the repo for building ChakraCore on Linux and macOS (see https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore). Does that work for you?

**Comment by rhuanjl** [comment]
I had a go at this quickly, running build.sh on a mac doesn't seem to allow targeting windows - well it tries but the build fails, not sure if it's designed for that.

Easy enough to build for mac on a mac and easy enough to build for windows on windows - but can't see a working way to build for windows from mac.
