### ISSUE TITLE
Problem while switching contexts

### ISSUE THREAD

**Issue by dimitrovp** [Microsoft/ChakraCore#5160]
Hi all, I have a problem when I am trying to switch a context.
I have two contexts in a single runtime and everything is happening on the same thread, but when I am trying to change the current context the operation failed. I am using "JsSetCurrentContext" It seems that there is a running script in the active context and "ThreadContextTLSEntry::ClearThreadContext" returns false. What can I do to change the context? Is it possible an active context to trigger something to happen in a different context?

**Comment by digitalinfinity** [comment]
Can you share the callstack at the point at which you call `JsSetCurrentContext` please?

**Comment by kfarnung** [comment]
Hi @dimitrovp, do you have some sample code that reproduces the issue?

It sounds like you're trying to change the context from another thread.  Changing the context can only be done from the engine thread, so by definition no JavaScript code can be running when the call to `JsSetCurrentContext` occurs.

If you'd like to have a call from one context call into a function in another context you can initialize the function in the other context and provide that value to the second context:

```cpp
JsSetCurrentContext(firstContext);

JsValueRef myFunc = JS_INVALID_REFERENCE;
JsCreateFunction(myNativeFunction, myCallbackState, &myFunc);

JsSetCurrentContext(secondContext);

JsValueRef globalObject = JS_INVALID_REFERENCE;
JsGetGlobalObject(&globalObject);

JsPropertyIdRef propId = JS_INVALID_REFERENCE;
JsCreatePropertyId("myFunc", 6, &propId);

JsSetProperty(globalObject, propId, myFunc);
```

**Comment by fatcerberus** [comment]
> by definition no JavaScript code can be running when the call to JsSetCurrentContext occurs.

Hypothetically, what happens if one calls `JsSetCurrentContext` during execution of a native host function which was called from JS code?

**Comment by dimitrovp** [comment]
Thank you @fatcerberus. @kfarnung my case is exactly what @fatcerberus has said.

**Comment by MSLaguana** [comment]
Calling `JsSetCurrentContext` when you are already in a context, even executing other JS, is fine. We do this in node-chakracore to implement `vm.runInContext`. There are some constraints, like if the GC is enumerating the heap then it fails, but that would give a relevant error code.

You mention that you are calling into `ThreadContextTLSEntry::ClearThreadContext`; what stack do you have there? Unless you are calling `JsSetCurrentContext(nullptr)` it shouldn't be clearing the thread context, and we don't allow completely un-setting a context while script is still on the stack, which sounds like it might be the case you are running into.

Are you trying to `JsSetCurrentContext(nullptr)` while script is still on the stack?

**Comment by dimitrovp** [comment]
Sorry guys but I have one more question about JsSetCurrentContext.
When can I use JsSetCurrentContext(nullptr or JS_INVALID_REFERENCE)?

**Comment by fatcerberus** [comment]
It's safe to do that as long as there are no JavaScript functions on the callstack of the thread making the call.

Note `JS_INVALID_REFERENCE` is ultimately just an alias for `nullptr`.

**Comment by MSLaguana** [comment]
The main restriction on `JsSetCurrentContext(JS_INVALID_REFERENCE)` is that no script can be on the stack at the time. Note that if you do change the running context and you don't make sure to add a reference to the previous context, it may be GCd and go away.

I think that typically we expect that you'll do it when the javascript session is over (e.g. in node-chakracore it happens once the program is finished and is just about to exit), but in our ch host we use different contexts to isolate tests, and we completely tear them down / return to nullptr between tests to make sure there's nothing shared.

**Comment by dimitrovp** [comment]
Thank you very much, guys :)
