### ISSUE TITLE
Uninformative error message for extra semicolon in method chain

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#5178]
It's common in JavaScript to find method call chains like the one below, particularly when using query libraries like Lazy.js or jQuery:
```js
doSomething()
    .doA()
    .doB()
    .doC();
```

If one accidentally adds an extra semicolon in the middle of such a chain--a mistake I myself make way too often--like so:
```js
doSomething()
    .doA()
    .doB();
    .doC();
```

The resulting error message is pretty much as vague as they come:
```
SyntaxError: Syntax error
```

**Comment by fatcerberus** [comment]
For comparison, Node.js prints in this case:
```
C:\temp\err.js:3
        .c();
        ^

SyntaxError: Unexpected token .
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
```

While I think I would ultimately prefer flagging the previous line with "unexpected semicolon", this is still infinitely better than ChakraCore's error message.

**Comment by MSLaguana** [comment]
If you use `JsGetAndClearExceptionWithMetadata` then you can get some additional information, including the line that caused the issue and the location on that line. With that, a host can produce an error looking like this (from node-chakracore):

```js
> o.a();.b()
o.a();.b()
      ^^
SyntaxError: Syntax error
```

However I do agree that it'd be nice if the error was more descriptive.

**Comment by fatcerberus** [comment]
Right, the issue is when the method chain is on multiple lines, then that error looks more like
```
    .b();
    ^^
SyntaxError: Syntax error
```
Which is misleading.

**Comment by rhuanjl** [comment]
@MSLaguana I was thinking it may be good to add nicer error messages for most of the instances of ERRsyntax within parse.cpp would a PR to add ~20 more specific error messages be welcome? If yes I will prepare one. If no I could do just this one (assuming it would be wanted).

**Comment by boingoing** [comment]
There are typically no compat issues related to the contents of error messages. We have a lot of syntax error messages in our test baselines which will probably need to be updated, though.

**Comment by rhuanjl** [comment]
OK I'll put something together to improve this and a few other error messages.

**Comment by rhuanjl** [comment]
I'm looking at this again now, sorry for the delay.
