### ISSUE TITLE
Switching a context from different runtime while running a script

### ISSUE THREAD

**Issue by dimitrovp** [Microsoft/ChakraCore#5179]
Hi all :) 
Is it possible to make a native function call from one context where the native function makes a call which switches the context and the runtime? In this example, every context has a different runtime and everything happens on the same thread.

**Comment by fatcerberus** [comment]
I'm not positive but I think you can only have one runtime per thread.

**Comment by MSLaguana** [comment]
Why do you want to have multiple different runtimes running in the same thread? The runtime includes things like the recycler (aka garbage collector), and I'm not sure I can see a reason to have several of those shared resources around.

To answer the other parts of your question: Yes it is possible to have a native call made from one context switch to another context and call back into javascript. If you do want to switch between runtimes (e.g. passing between threads) then I believe you will need to serialize data and marshal it around yourself, similar to how webworkers work. You can't just pass a function or an object from one runtime to another, unlike with contexts.

**Comment by dimitrovp** [comment]
Thank you, guys :)
