### ISSUE TITLE
Chakra cannot override RegExp.prototype.exec property

### ISSUE THREAD

**Issue by igor-simoes** [microsoft/ChakraCore#5187]
OS: Ubuntu 16.04 x86
Chakra: 1.10.0.0-beta

Step to reproduce:
```
// RegExp.prototype with overridden exec: Testing ES6 21.2.5.11: 19.b. Let z be ? RegExpExec(splitter, S).
let accesses = [];
let origDescriptor = Object.getOwnPropertyDescriptor(RegExp.prototype, "exec");
let origExec = origDescriptor.value;

Object.defineProperty(RegExp.prototype, "exec", {
    value: function(str) {
        accesses.push("exec");
        return origExec.call(this, str);
    }
});

if (!(accesses == "")) throw new Error("unexpected call to overridden props");
let result = "splitme".split(/it/);
if (!(result == "spl,me")) throw new Error("Unexpec󠁄ted result");
if (!(accesses == "exec,exec,exec,exec,exec,exec")) throw new Error("Property access󠀡es do not match expectation");
```
Actual results:
```
Error: Property access󠀡es do not match expectation
```
Expected results:
```
Pass without failures
```

V8, SpiderMonkey and JavascriptCore works as expected. 

cinfuzz

**Comment by dilijev** [comment]
Most likely has to do with this property being `configurable: false`

**Comment by fatcerberus** [comment]
`RegExp.prototype.exec` seems to actually be both configurable and writable so I don't think that's the problem:
```
#/runtime/assert.mjs:33 module()
(ssj) x Object.getOwnPropertyDescriptor(RegExp.prototype, "exec")
prop  __proto__     {...} *3
prop  value         {...} *4
prop  writable      true
prop  enumerable    false
prop  configurable  true
```

**Comment by fatcerberus** [comment]
One thing I don’t understand about the repro above is why there should be six calls to `.exec`?  I’d expect two at most.

**Comment by curtisman** [comment]
This test case only make sense when RegEx symbols is enabled, because String.prototype.split is not defined based on Regexp.prototype[@@split].

Currently RegEx symbols is not fully implemented.   When I tried with the flag -ES6RegExSymbols, I ran into another exception:
SyntaxError: Syntax error in regular expression
        at Global code (blah.js:14:1)

The error comes form the implementation of @@split, where it ask for the flags from the passed in regex and got "undefinedy"  which seems wrong to me.

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
