### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by ppenzin** [Microsoft/ChakraCore#5199]
Encouraged by [a comment in ByteSwap.h][b], I am trying to understand what it would take to build ChakraCore on FreeBSD.

I understand that this might not be a priority, but I will appreciate any pointers or suggestions.

[b]: https://github.com/Microsoft/ChakraCore/blame/master/lib/Common/Common/ByteSwap.h#L72

**Comment by digitalinfinity** [comment]
Hi @ppenzin - my advice would be to just try it out and see what you run into- we currently depend on clang 4, libc and ICU60. Additionally, a lot of platform specific code is abstracted away under /pal, which was forked from the CoreCLR which does support FreeBSD. 

I don't know the details of differences between FreeBSD and Linux but if those components are available on FreeBSD, the port shouldn't be too bad.

This does seem like something @obastemur would have looked at in the past- maybe he has pointers?

**Comment by ppenzin** [comment]
@digitalinfinity thanks for the reply! Clang is used to build FreeBSD (11.1 comes with clang 4), and something ICU related is available, I would need to check. Unless there is a dependency on a specific LIinux feature or on a library that is hard to build, it should work.

So far I am sorting through undefined errors due to differences in build process. I did enable byteswap the way @obastemur suggested in the comment,

**Comment by jackhorton** [comment]
For what its worth, ICU _should_ work on FreeBSD without too much fanfare. I would be happy to know what issues you run into with it :)

**Comment by ethindp** [comment]
So, I'm trying to build ChakraCore on FreeBSD. Here is the command I used:
```./build.sh --arch=amd64 --system-icu --ninja --lto --target=freebsd```
I built ICU 63.1, Unicode 11.0, before this. here's the output I get whenever I run this command:
```
Warning: Installation script couldn't detect host OS..

Build path: /usr/home/ethin/chakracore/out/Release
-- /usr/home/ethin/chakracore/bin/ch/DbgController.js.h is created

Compile Target : amd64
Generating Release makefiles

-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:256 (message):
  This OS is not supported


-- Configuring incomplete, errors occurred!
See also "/usr/home/ethin/chakracore/out/Release/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
See error details above. Exit code was 1
```
What's odd about this error is that it seems like the makefile is assuming that my OS is OSX, as evidenced by the code that causes this error (lines 241-257 of CMakeLists.txt):
```
    if(NOT CC_XCODE_PROJECT)
      set(OSX_DEPLOYMENT_TARGET "$ENV{MACOSX_DEPLOYMENT_TARGET} CC")
      if (${OSX_DEPLOYMENT_TARGET} STREQUAL " CC")
        set(OSX_DEPLOYMENT_TARGET "10.9")
        add_compile_options(-mmacosx-version-min=10.9)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
          -mmacosx-version-min=10.9 -std=gnu99")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} \
          -mmacosx-version-min=10.9 -std=gnu++11")
      else()
        set(OSX_DEPLOYMENT_TARGET "$ENV{MACOSX_DEPLOYMENT_TARGET}")
        message(WARNING "-- !! macOS Deployment Target was set to $ENV{MACOSX_DEPLOYMENT_TARGET}. Using it as is.")
      endif()
    endif()
else()
    message(FATAL_ERROR "This OS is not supported")
endif()
```
I'm using clang/clang++, as the build.sh script requires. So I'm not sure how else to build this. But I'd like to try and integrate it into one of my projects.

**Comment by ethindp** [comment]
Ah. I was hoping something could be done. I can wait, I guess. :)

On 11/28/18, Oguz Bastemur <notifications@github.com> wrote:
> IIRC few changes are required to make that. Answer your question; not doable
> as is.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Microsoft/ChakraCore/issues/5199#issuecomment-442610392


-- 
Signed,
Ethin D. Probst

**Comment by ppenzin** [comment]
I've tried to get it to build and this is how for it got: https://github.com/ppenzin/ChakraCore/tree/freebsd
I am hoping to return to this one day, but haven't found time :)

It should be theoretically doable, as Chakra does not seem to depend on anything unavailable on FreeBSD, but you would have to make minor edits. There are usual issues with porting something that runs on OSX and LInux to FreeBSD -- include directories, link libraries paths and so on.
