### ISSUE TITLE
Cache template literals per site, not by contents

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/ChakraCore#5201]
Template literal caching was changed in https://github.com/tc39/ecma262/pull/890 to cache per source location, rather than by literal string contents.

V8, SpiderMonkey and JSC all seem to implement the new semantics.

This behavior is very important to template tag functions that caching work based on templates.
  1) Because with the old global behavior keying by template literal would cause a memory leak.
  2) If the cache is supposed to be keyed by site there's no fast way for userland code to do it.

**Comment by akroshg** [comment]
@boingoing is the expert on the template literal. looking for his opinion on this one.

**Comment by justinfagnani** [comment]
@boingoing The Test262 test for this is here: https://github.com/tc39/test262/blob/master/test/language/expressions/tagged-template/cache-differing-expressions.js

...but I haven't actually run that test specifically on Edge yet.
