### ISSUE TITLE
Module function exports not hoisted

### ISSUE THREAD

**Issue by rhuanjl** [microsoft/ChakraCore#5236]
Raising this as a separate issue from #5171 though it's related. #5171 was specifically talking about a regression - the only change having been module load order.

But this is the reason why the load order mattered in that case - in CC module function exports are not treated as hoistable exports. (In fact I don't think CC has a concept of a hoistable export)

Illustration:
```js
//a.js
import "./b.js";
console.log("a.js");
export function func(){}

//b.js
import {func} from "./a.js";
console.log("b.js");
console.log(func);
```
Results
1. Load a.js:
```
b.js
undefined
a.js
```
2. Load b.js
```
a.js
b.js
function func(){}
```
Conversely if you change them to .mjs and run with node:
Results
1. Load a.mjs:
```
b.mjs
[Function: func]
a.mjs
```
2. Load b.mjs
```
a.mjs
b.mjs
[Function: func]
```
The function export from a.js gets hoisted under v8 so the function is available at run time whichever way around you load the modules whereas under CC it is not hoisted and so you have to get your load order right in circular cases to avoid it being undefined.

**Comment by rhuanjl** [comment]
Extra note to add to this - it can cause code to throw an exception that shouldn't.

E.g. if in the above example instead of logging func you were to call it:
- in v8 this will complete normally (and if func did something it would do it)
- whereas in CC this will throw an error that func is not an object.

**Comment by rhuanjl** [comment]
One more note add. I believe this is related to https://github.com/Microsoft/ChakraCore/issues/3251

In that TDZ’d imported  bindings should throw TDZ errors, whereas hoistsbke ones should be available instead both TDZ’d imports and hoistable imports are undefined.

**Comment by guybedford** [comment]
Note v8 handles this by treating the top-level execution as a two-phase generator execution to define the hoisted functions.

**Comment by rhuanjl** [comment]
I figure this should actually be a relatively simple fix:
1. Optionally add some code to detect circularities so the fix is only applied when it's relevant
2. Create an edited GenerateRootFunction method that tells the bytecodeemitter that the function is a generator - it will automatically insert a yield at the top of the function body https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/ByteCode/ByteCodeEmitter.cpp#L3035-L3045
3. Split the module execution loop into two loops so that each function gets called once (to hit that first yield and define variables) and again to actually execute

With the points I've picked up on how generators work from the piece I've been doing on async generators I could likely do this.

**Comment by rhuanjl** [comment]
Just to update and apologise; I tried to fix this in November but underestimated the complexity of some of the related code - I've been having another look at it and think I'm about half way there but no guarantees there's some oddities to the logic I don't fully understand yet.
