### ISSUE TITLE
Module imports in ch should be relative to the current module

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#5237]
For comparison of esmodule behavior to any other environment imports should really be relative to the current module. (e.g. to investigate #5171 I had to use @fatcerberus miniSphere as my test harness to be able to try and load the ESM version of moment.js as it assumed relative imports so could not test in ch)

Currently in ch all imports are relative to the CWD instead.

I note that there was a previous issue about this #3257 which was fixed BUT since then the behaviour has been reverted.

There was a test case to confirm that imports were relative to current module not CWD https://github.com/Microsoft/ChakraCore/blob/master/test/es6module/bug_issue_3257.js But after it was broken a few times it was re-enabled without paths and hence no longer tested the original issue. (Though it remains a very useful test of circular imports combined with dynamic import)

**Comment by rhuanjl** [comment]
I could have a go at implementing this if wanted; I haven't done anything on it yet as I was unsure why this was implemented and then reverted again. Let me know if a PR to implement this in ch would be wanted.

**Comment by dilijev** [comment]
See Microsoft/ChakraCore#3284 addressing CWD issue

**Comment by rhuanjl** [comment]
Putting together an update to ch's module loader to address #5796 planning to fix this at the same time.
