### ISSUE TITLE
Cannot instrument libChakraCore.so with AddressSanitizer

### ISSUE THREAD

**Issue by symeonp** [Microsoft/ChakraCore#5239]
Hi team,

Quick question, I've spent many hours trying to compile the shared library with AddressSanitizer, however I'm not having luck. Am running on Ubuntu 16.04.4 x64 with clang 7 using the following command:

```./build.sh --cxx=/usr/bin/clang++ --cc=/usr/bin/clang --sanitize=address```

Once the compilation is finished am getting the following error:
```
symeon@ubuntu:~/Desktop/ChakraCore/out/Release$ ./ch sample.js 
dlopen() failed; dlerror says '/home/symeon/Desktop/ChakraCore/out/Release/libChakraCore.so: undefined symbol: __asan_option_detect_stack_use_after_return'
FATAL ERROR: Unable to load /home/symeon/Desktop/ChakraCore/out/Release/libChakraCore.so GetLastError=0x7e
```

Running the nm command reveals that the symbols for the library are not properly exported (they're undefined):
```
symeon@ubuntu:~/Desktop/ChakraCore/out/Release$ nm libChakraCore.so | grep asan_
                 U __asan_addr_is_in_fake_stack
                 U __asan_after_dynamic_init
                 U __asan_alloca_poison
                 U __asan_allocas_unpoison
                 U __asan_before_dynamic_init
                 U __asan_get_current_fake_stack
                 U __asan_handle_no_return
                 U __asan_init
                 U __asan_load1
                 U __asan_loadN
                 U __asan_memcpy
                 U __asan_memmove
                 U __asan_memset
                 U __asan_option_detect_stack_use_after_return
                --- snip ---
```
I've tried modifying directly the CMakeLists.txt and adding there the ```-fsanitize=address```, as well as ```-shared-libasan``` which then wouldn't compile successfully. Has anyone manage to get it working? Thanks!

**Comment by jackhorton** [comment]
@Penguinwizzard IIRC you had acknowledged issues with *SAN on the shared version of ChakraCore, right? Was that ever resolved?

(I believe our workaround is to compile ChakraCore as a static library to use the clang sanitizers, if it is blocking you).

**Comment by symeonp** [comment]
Hi Jack, thanks so much for your reply!
Well, I think the ```build.sh``` script does also compile the library as static, however I'm not quite sure if I can then use the ```ch``` binary as well. Let's see if @Penguinwizzard has a workaround for this!

**Comment by Penguinwizzard** [comment]
@jackhorton Yeah, we have issues with *SAN in shared builds, and the workaround is just to pass `--static` to `build.sh`. There hasn't been a resolution since it doesn't come across as too significant of an issue (we don't really have any significantly different behavior in static builds, afaik).
