### ISSUE TITLE
Code cache

### ISSUE THREAD

**Issue by arjunasuresh3** [Microsoft/ChakraCore#5241]
Is there any plans to implement code cache which is used by V8 (https://v8project.blogspot.in/2015/07/code-caching.html)?

**Comment by fatcerberus** [comment]
I think that’s what the `JsSerializeScript` API is for, see this page:
https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview

**Comment by MikeHolman** [comment]
In some scenarios we already cache bytecode, and @boingoing has been working on improving this and getting this hooked up for normal websites in Edge.

**Comment by boingoing** [comment]
Yes, we have such plans. Please check out the `JsSerializeParserState` and `JsRunScriptWithParserState` APIs for details on the implementation and how to use this in ChakraCore. We are working on enabling this feature for Edge as well.
