### ISSUE TITLE
navigator.plugins object's named property become non-enumerable on certain circumstances

### ISSUE THREAD

**Issue by theseanl** [Microsoft/ChakraCore#5263]
`navigator.plugins` object behaves in an odd way in certain edge cases.

I suppose the specification relevant for the `navigator.plugins` object is https://heycam.github.io/webidl/#es-legacy-platform-objects, and  https://html.spec.whatwg.org/multipage/#pluginarray . Since these do not specify whether the object should "support named property setters"  and what "named property visibility algorithm" should the object use, I suppose the behavior of the object can be largely platform-dependent.

However, even assuming this, there seem to be some weirdness coming into play in situations described below:

When the following script is executed:
```js
var plugins = navigator.plugins;

plugins.propertyIsEnumerable('Edge PDF Viewer') // true!

Object.defineProperty(plugins, 1e9, {
    value: null,
    configurable: true
});
delete plugins[1e9];

plugins['Edge PDF Viewer'] = {};

delete plugins['Edge PDF Viewer'];

plugins.propertyIsEnumerable('Edge PDF Viewer') // false!
```

the _named property_ `"Edge PDF Viewer"`, which is enumerable at beginning, suddenly becomes a non-enumerable property of the plugins object. This is weird, because in usual situation where one defines some properties on the plugin object and deletes it afterwards, it recovers the exact same property descriptor which it had at the beginning. However, in this case, it recovers a descriptor that is the same to the original one _except_ the `enumerable` key changed from `true` to `false`.

`1e9` can be changed to any number that exceeds `navigator.plugins.length`. The issue disappears when changing it to a number less than `navigator.plugins.length`.

Also, if the temporary property descriptor is changed to have _both_ `writable` and `enumerable` attribute, the issue disappears as well:

```js
var plugins = navigator.plugins;

plugins.propertyIsEnumerable('Edge PDF Viewer') // true!

Object.defineProperty(plugins, 1e9, {
    value: null,
    writable: true,
    enumerable: true,
    configurable: true
});
delete plugins[1e9];

plugins['Edge PDF Viewer'] = {};

delete plugins['Edge PDF Viewer'];

plugins.propertyIsEnumerable('Edge PDF Viewer'); // true now!
```

[Edit - changed misspelled "Edge PDF Plugin"s to "Edge PDF Viewer"]

**Comment by fatcerberus** [comment]
`navigator.plugins` is a web API and therefore not directly relevant to ChakraCore, which only provides the basic ECMAScript-specified APIs.  Unless I'm misunderstanding what this issue is about, you should probably post this on the Edge bug tracker instead.

**Comment by seanl-adg** [comment]
Ok, by Edge bug tracker you meant https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/, right?
I created an issue several times before but none of them got approved. I created about this one though, but it is still not approved by moderators.

**Comment by fatcerberus** [comment]
Yeah, it's just there's not much we can do about this if it's specific to `navigator.plugins` since that API, like the rest of HTML5 is not actually part of ChakraCore.  Those APIs from what I understand are implemented by ChakraFull, which is part of Edge.  ChakraCore is only a subset of that.

**Comment by seanl-adg** [comment]
Got it, then this issue may be closed.
Would there anything I can do for to have issues created by myself getting approved by the issue tracker moderators? It seems that something is wrong there, since none of my issues were approved.

**Comment by jackhorton** [comment]
Could you post a link to the Edge issue you created?

**Comment by seanl-adg** [comment]
> Could you post a link to the Edge issue you created?

The issue submitter in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ did not provide a link of the new issue, it merely provided a text `The content of this issue will be manually approved. Thanks for your patience.`

> Edit: And also, are you seeing this as a new issue in Edge?

On my end this issue is manifested on IE11 as well.

**Comment by liminzhu** [comment]
I'm going to close this one since it's unrelated to ChakraCore. Feel free to re-open if you have anything we can help with.
