### ISSUE TITLE
Dynamic Imports: import() must produce a SyntaxError  

### ISSUE THREAD

**Issue by rwaldron** [Microsoft/ChakraCore#5270]
While writing Test262 tests for dynamic import, I discovered the following incompatibility: 

```js
import()
```

Should produce a SyntaxError, given the grammar:

`import (` _AssignmentExpression_ `)`

Does not expand to `import()`

**Comment by fatcerberus** [comment]
This already appears to produce a SyntaxError.

```js
// test.js
import();
print("This can't happen.");
```

Output
```
D:\temp>spherun test.js
miniSphere X.X.X JS game engine (x64)
a lightweight JavaScript-powered game engine
(c) 2015-2018 Fat Cerberus

GAME CRASH: error at '@/test.js':2:8
SyntaxError: Syntax error
   2 import();
```

**Comment by rwaldron** [comment]
Ok, I've narrowed it down further... this only happens when the `-ESModule` flag is present. Incidentally, that flag appears to cause other strangeness:

```
rwaldron in ~/js
$ echo "import();print('must not be reached');" >> dynamic-import.js
rwaldron in ~/js
$ cat dynamic-import.js
import();print('must not be reached');
rwaldron in ~/js
$ ch dynamic-import.js
SyntaxError: Syntax error
  at code (dynamic-import.js:1:7)
rwaldron in ~/js
$ ch -ESModule dynamic-import.js
rwaldron in ~/js
```

There's no output at all for `ch -ESModule dynamic-import.js`, which makes me think I might be doing something wrong here. I will close this for now and re-open if necessary.

**Comment by fatcerberus** [comment]
I see no change if I rename my test file to `test.mjs` (miniSphere will run it as a module), I still get a SyntaxError without reaching the `print()`.

I think I see the problem though: `ch -ESModule filename.js` doesn't run the file as a module, it just enables module support while still loading the script as traditional code (I hit this pitfall myself in the past).  You instead need to write a shim that does:
```js
WScript.LoadScriptFile('module.mjs', 'module');  // execute root module
```

And then run the shim.

**Comment by rwaldron** [comment]
Lol, I just came back to post this same update. Thanks for preemptively confirming :D

**Comment by rhuanjl** [comment]
-ESModule isn't a flag that does anything in master.

-ESDynamicImport is the flag to enable import() - without it any dynamic import is a syntax error

**Comment by fatcerberus** [comment]
@rhuanjl Right, this issue was specifically about `import()` (with no specifier) incorrectly *NOT* being a syntax error; I’ve already verified that it is.
