### ISSUE TITLE
Is it possible to embed ChakraCore in a game framework?

### ISSUE THREAD

**Issue by VictorQueiroz** [Microsoft/ChakraCore#5289]
Let's imagine that I'm building a game and I want to handle a specific part of the game using code processed by ChakraCore. How would I invoke JS and take all of it's advantages and also build bindings so this JS code could access other bindings to other functionality of the game framework? Is it possible or I'm talking nonsense? If not, can somebody guide me to the right direction? Just so you know, the game framework would be written in C/C++.

Best regards

**Comment by jackhorton** [comment]
It is possible to embed JS in _any_ C/C++/Language-that-has-access-to-C-APIs application :) You may want to look at the [miniSphere](https://github.com/fatcerberus/minisphere) game engine by our friends @fatcerberus and @rhuanjl, which embeds ChakaCore.

**Comment by liminzhu** [comment]
Allow scripting in native apps is definitely an intended and supported use case. Something to help get you started:

1. [Embedding ChakraCore](https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore) and [JSRT Overview](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview) docs should help you get a bit familiar with the engine. You should know how to do a HelloWorld and a few other most common things in ChakraCore after you finish.
2. There are a whole bunch of samples we wrote in [Chakra-samples](https://github.com/Microsoft/Chakra-samples). [This](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/OpenGL%20Engine) is my favorite and imo most informative. 
3. Like Jack said, you can also look into [miniSphere](https://github.com/fatcerberus/minisphere) engine. Their developers hang out with us on our repo a lot :). 

Feel free to ask anything here.
