### ISSUE TITLE
Problem with r(v) function

### ISSUE THREAD

**Issue by DrEight** [Microsoft/ChakraCore#5333]
I have the chakracore hosted in a windows application. I 'm running a JS script with defined a function r(v). The script throws the error: 'object expected' when the r() function is called. So it seems that r() is a predefined chakra function. Am I correct ?
How can I fix the problem ?

**Comment by MSLaguana** [comment]
We don't have a built-in function `r`, but I can reproduce the error you report if I try to invoke undefined:

```js
> undefined()
TypeError: Object expected
```

Are you sure that you have defined your `r` function correctly?

**Comment by DrEight** [comment]
Thank you for your help, after days of debugging, I figured out the problem in my code.

**Comment by MSLaguana** [comment]
Glad you've solved your problem!
