### ISSUE TITLE
Proxy traps not triggered for __lookupGetter and  __lookupSetter_

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#535]
Expected true from both the following test cases. Actual: false
This is a kangax test case

```js
print((function()
{
// Object.prototype.__lookupGetter__ -> [[GetOwnProperty]]
// Object.prototype.__lookupGetter__ -> [[GetPrototypeOf]]
var gopd = [];
var gpo = false;
var p = new Proxy({},
  { getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); }},
  { getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }});
Object.prototype.__lookupGetter__.call(p, "foo");
return gopd + '' === "foo" && gpo;
})());
```
```js
print((function()
{
// Object.prototype.__lookupSetter__ -> [[GetOwnProperty]]
// Object.prototype.__lookupSetter__ -> [[GetPrototypeOf]]
var gopd = [];
var gpo = false;
var p = new Proxy({},
  { getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); }},
  { getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }});
Object.prototype.__lookupSetter__.call(p, "foo");
return gopd + '' === "foo" && gpo;
})());
```

**Comment by leirocks** [comment]
looks there's problem in the repro code?
it's new-ing  Proxy with 3 parameters, not two:
1. {},
2.  { getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); }},
3.  { getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }}

the code should be like this:?

`
print((function()
{
// Object.prototype.__lookupGetter__ -> [[GetOwnProperty]]
// Object.prototype.__lookupGetter__ -> [[GetPrototypeOf]]
var gopd = [];
var gpo = false;
var p = new Proxy({},
  { 
      getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); },
      getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); 
});
Object.prototype.__lookupGetter__.call(p, "foo");
return gopd + '' === "foo" && gpo;
})());
`

**Comment by leirocks** [comment]
and looks getOwnPropertyDescriptor is called, but getPrototypeOf is not.

**Comment by abchatra** [comment]
@leirocks. This is a test from [kangax esnext](http://kangax.github.io/compat-table/esnext/)

You are right, seems like test was incorrect before and the right test is below, which still fails.
```js
print((function()
{
// Object.prototype.__lookupGetter__ -> [[GetOwnProperty]]
// Object.prototype.__lookupGetter__ -> [[GetPrototypeOf]]
var gopd = [];
var gpo = false;
var p = new Proxy({}, {
  getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); },
  getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }
});
Object.prototype.__lookupGetter__.call(p, "foo");
return gopd + '' === "foo" && gpo;
})());
```

**Comment by leirocks** [comment]
Yes, it still fails, after fixing the test, the getownpropertydescripotr trap will be called, butgetprototypeof trap is still not called, I'm investigating that

Get Outlook<https://aka.ms/uzin6x>




On Tue, Apr 26, 2016 at 10:48 AM -0700, "Abhijith Chatra" <notifications@github.com<mailto:notifications@github.com>> wrote:


@leirocks<https://github.com/leirocks>. This is a test from kangax esnext<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fkangax.github.io%2fcompat-table%2fesnext%2f&data=01%7c01%7cleish%40microsoft.com%7c2eb2db9393b540ee794e08d36dfb0884%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=eKyiWe%2bk8qem3nBdNrvqQq97GAkn9XTqx15mw3axFGc%3d>

You are right, seems like test was incorrect before and the right test is below, which still fails.

print((function()
{
// Object.prototype.__lookupGetter__ -> [[GetOwnProperty]]
// Object.prototype.__lookupGetter__ -> [[GetPrototypeOf]]
var gopd = [];
var gpo = false;
var p = new Proxy({}, {
  getPrototypeOf: function(o) { gpo = true; return Object.getPrototypeOf(o); },
  getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }
});
Object.prototype.__lookupGetter__.call(p, "foo");
return gopd + '' === "foo" && gpo;
})());

-

**Comment by abchatra** [comment]
@leirocks Any update on this issue?
