### ISSUE TITLE
JsCreateExternalObject returns ArgumentNotObject

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Microsoft/ChakraCore#5353]
We have some code that calls JsCreateExternalObject (through the .NET wrapper) to get a reference to external C# objects. It works fine most of the time, but it looks like one time it returned ArgumentNotObject. Is there any valid scenario where this error would be returned from this method?

I looked at the [implementation](https://github.com/Microsoft/ChakraCore/blob/6c2c8a78420e9bcc0b126ea05a6f17237aff3415/lib/Jsrt/Jsrt.cpp#L1331), and it seems this error can be returned from [VALIDATE_INCOMING_OBJECT](https://github.com/Microsoft/ChakraCore/blob/6c2c8a78420e9bcc0b126ea05a6f17237aff3415/lib/Jsrt/Jsrt.cpp#L1331) in `JsCreateExternalObjectWithPrototype`, but the `prototype` value should be JS_INVALID_REFERENCE, and this check shouldn't be executed. Could the error be related to the `data` parameter that we are passing in?

The version of ChakraCore is 1.8.4.

**Comment by MSLaguana** [comment]
If you are using ChakraCore 1.8.4 then you're actually using an implementation closer to this: https://github.com/Microsoft/ChakraCore/blob/release/1.8/lib/Jsrt/Jsrt.cpp#L1291

I can't see any obvious reason that you'd get `JsErrorArgumentNotObject` from that function. Are you sure it was that and not an adjacent call which returned the error?

**Comment by dennis-yemelyanov** [comment]
Thanks, @MSLaguana . I think it could also be coming from the following line that sets the prototype (I guess the line numbers in the call stack might be a little off due to optimizations etc.):

```
        public JavaScriptValue CreateJsObject(object obj)
        {
            var jsObject = JavaScriptValue.CreateExternalObject(obj.CreateIntPtr(), null);

            jsObject.Prototype = Prototype;

            return jsObject;
        }
```

And the prototype object is created as `Prototype = JavaScriptValue.CreateObject();` (and then setting some properties on this Prototype) before the above code executes.

**Comment by MSLaguana** [comment]
That also looks like it should work, unless the .net wrapper is doing strange things. `JsCreateExternalObject` should always result in a `JsrtExternalObject`, which is a valid object, and similarly `JsCreateObject` should always result in a valid object, so calling `JsSetPrototype(jsObject, Prototype)` should also always work. Is it possible that you have a race condition such that your `Prototype` isn't initialized properly?

**Comment by dennis-yemelyanov** [comment]
I don't think there is a race condition since the `Prototype` is basically initialized at application startup and `CreateJsObject` calls are made later. I'm also checking if there could be some garbage collection happening leading to this state (unlikely)... I'll also add some logging to get `Prototype.ValueType` right before using it.

**Comment by dennis-yemelyanov** [comment]
Actually garbage collection might be a likely candidate... After debugging this further I noticed that sometimes JsSetPrototype throws AccessViolationException, and from [this](https://github.com/Microsoft/ChakraCore/issues/1033) thread any object created with `JsCreateObject` should be "pinned" by calling `.AddRef()`, unless it's used explicitly by the JS runtime (placed on some JS call stack etc.). So right after creating the `Prototype` I need to call `Prototype.AddRef()`. Is that correct?

And the final question is, could the `JsErrorArgumentNotObject` error have also been caused by the JS value being garbage collected?

**Comment by MSLaguana** [comment]
Right; whenever you hold onto a reference to a javascript object in a way that chakracore can't detect (basically, if it isn't on the stack or referenced by another object known to chakracore) then you need to explicitly add a reference to it (and then later dereference once you're done with it, to avoid leaking memory). If you fail to do that, it may be considered unreferenced and then garbage collected out from underneath you, leading to unpredictable and bad behavior later on.

However, I'm not sure whether that would cause the `JsErrorArgumentNotObject`, since that check is based on looking at the pointer only. Some pointers are tagged and treated as integers or floats, and the check that can return that error is only checking for that tag. If the tag is not present, then we go ahead and treat it as though it is a pointer to one of our internal objects and potentially dereference it, and that could cause crashes or other bad things, but I don't expect that it would return that particular error...

**Comment by MSLaguana** [comment]
Ah, there's one path that I hadn't considered and could result in that: the check doesn't just check for tagged values, it does go and try to fetch the internal type of the object, and so if that type happens to be a small number (< ~20) then it could cause that error. So it may be that the object was collected, something else allocated in its place, and after following a chain of bogus pointers the value it read was small or negative.

**Comment by dennis-yemelyanov** [comment]
Great, thank you for confirming that it could happen. I'll try the .AddRef() fix, hope it solves the problem.

**Comment by dilijev** [comment]
Feel free to comment back if you have any further questions and we will reopen the thread.
