### ISSUE TITLE
webcrypto generateKey promise does not resolve.

### ISSUE THREAD

**Issue by farzonl** [Microsoft/ChakraCore#5359]
Not sure if this is an Edge or F12 issue, but in any case I'm having a hard time porting a web app that uses web crypto to Edge. Below please find a similar simpler use case that also does not resolve.
Sample code:
borrowed: from here: https://github.com/diafygi/webcrypto-examples#aes-ctr---generatekey
```javascript
crypto.subtle.generateKey(
    {
        name: "AES-CTR",
        length: 256, //can be  128, 192, or 256
    },
    false, //whether the key is extractable (i.e. can be used in exportKey)
    ["encrypt", "decrypt"] //can "encrypt", "decrypt", "wrapKey", or "unwrapKey"
)
.then(function(key){
    //returns a key object
    console.log(key);
})
```
Chrome behavior:
prints out the CryptoKey
![image](https://user-images.githubusercontent.com/1802579/41805661-a19f5e60-767c-11e8-892d-f18cef66e888.png)

Edge Behavior
![image](https://user-images.githubusercontent.com/1802579/41805676-e22eba34-767c-11e8-9e78-e531f221acab.png)

Testing is on Edge version 17 off of browserstack.

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey
support for this API seems to be available as of Edge 12.

At this point not sure  if the debugger is lying to me or if the API is deficient.

**Comment by MSLaguana** [comment]
I just tried this out in edge, and the reason that it isn't resolving the promise is that it is instead rejecting the promise; if you add a `.catch` to the promise chain, you'll see that the catch handler is being called with the first argument passed to `generateKey`. If I change your example to use `{ name: "AES-CBC", length: 256}` instead, then it seems to work correctly. It seems like there may be support for some algorithms missing in edge. Could you please report this issue at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?
