### ISSUE TITLE
Inconsistent output compared with V8 and SpiderMonkey

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5360]
Hello,
The following code behaves incorrectly (inconsistent with the standard and other engines).
ch version 1.8.5.0
```
arr0 = [ 1, 2, 3 ];                                                                                                                 
arr1 = [ 4, 5, 6 ];  
handler1 = { 
    get: function (oTarget, sKey) { 
        print('arg ' + '1' + ':get ' + sKey.toString()); 
        if (sKey.toString() == 'Symbol(Symbol.isConcatSpreadable)') { 
            arr1['length'] = 4294967294;
        }   
        if (sKey.toString() == 'length') { 
            arr1['length'] = 10; 
        }   
        if (Number(sKey.toString()) != NaN) { ; } 
        return Reflect.get(oTarget, sKey); 
    },  
    has: function (oTarget, sKey) { 
        print('arg ' + '1' + ':has ' + sKey.toString()); 
        if (Number(sKey.toString()) != NaN) { 
            return Symbol.search;
        }   
        return Reflect.has(oTarget, sKey);
     }   
}; 
var proxy1 = new Proxy(arr1, handler1); 
func = Array.prototype.concat.bind(arr0, proxy1); 
arr2 = func(); 
print(arr2);
```
The output is:
arg 1:get Symbol(Symbol.isConcatSpreadable)
arg 1:get length
arg 1:has 0
arg 1:has 1
arg 1:has 2
arg 1:has 3
arg 1:has 4
arg 1:has 5
arg 1:has 6
arg 1:has 7
arg 1:has 8
arg 1:has 9
1,2,3,,,,,,,,,,

However, it should be:
arg 1:get Symbol(Symbol.isConcatSpreadable)
arg 1:get length
arg 1:has 0
arg 1:get 0
arg 1:has 1
arg 1:get 1
arg 1:has 2
arg 1:get 2
arg 1:has 3
arg 1:get 3
arg 1:has 4
arg 1:get 4
arg 1:has 5
arg 1:get 5
arg 1:has 6
arg 1:get 6
arg 1:has 7
arg 1:get 7
arg 1:has 8
arg 1:get 8
arg 1:has 9
arg 1:get 9
1,2,3,4,5,6,,,,,,,

BT group
2018.6.25

**Comment by zenparsing** [comment]
This is due to the fact that ES6 Regexp symbols are currently behind a flag (`Symbol.search` is undefined in that case). With `-ES6RegExSymbols` the test case works as expected.
