### ISSUE TITLE
OS X builds failing in release/1.8 

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#5365]
See https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28release-1.8%29

```
13:55:03 [1m/Users/dotnet-bot/j/w/Microsoft_ChakraCore/release_1.8/static_osx_osx_debug/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:38:22: [0m[0;1;31merror: [0m[1munknown type name 'Normalizer2'; did you mean 'UNormalizer2'?[0m
13:55:03         static const Normalizer2* TranslateToICUNormalizer(NormalizationForm normalizationForm)
13:55:03 [0;1;32m                     ^~~~~~~~~~~
13:55:03 [0m[0;32m                     UNormalizer2
13:55:03 [0m[1m/usr/local/opt/icu4c/include/unicode/unorm2.h:120:29: [0m[0;1;30mnote: [0m'UNormalizer2' declared here[0m
13:55:03 typedef struct UNormalizer2 UNormalizer2;  /**< C typedef for struct UNormalizer2. @stable ICU 4.4 */
```

**Comment by dilijev** [comment]
@MSLaguana it looks like we got a build on OSX and released 1.8.5 in any case. Maybe there's a difference in the installed version of ICU dev dependencies on the lab machines?>

**Comment by MSLaguana** [comment]
Yeah, the bug here is fixed in newer branches since it is to do with the c++ ICU api, and we changed to use only the C API. It looks like the OSX machines no longer(?) have that c++ API present, and so the build fails, but the machine that we use to make the releases does have the correct dependencies and so we were able to do the release.

**Comment by dilijev** [comment]
Sounds like it should be fine if users build with the correct documented dependencies, and it's not worth the effort of fixing up the CI machines for this older branch at this point.
