### ISSUE TITLE
Inconsistent output compared with other JS engines when using sort()

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5381]
Hello,
The following code behaves strangely (inconsistent with other engines).
```
a=[3.3,2.2,1];
a.sort(function () { return -1;});
```
In Edge, output is
```[1, 2.2, 3.3]```
However, output should be:
```[3.3, 2.2, 1]```

BT group
2018.6.28

**Comment by fatcerberus** [comment]
In the example you give, the comparison function itself is not internally consistent as it always returns -1.  I'm not 100% positive but I think that might be undefined behavior?

**Comment by fatcerberus** [comment]
Yep, from MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

> compareFunction(a, b) must always return the same value when given a specific pair of elements a and b as its two arguments. **If inconsistent results are returned then the sort order is undefined.**

**Comment by sunlili** [comment]
You are right, it is undefined.

**Comment by jackhorton** [comment]
@zenparsing , FYI

Sounds like this is not an issue, then?

**Comment by rhuanjl** [comment]
FYI with eshost:
```
## Source
a=[3.3,2.2,1];
a.sort(function () { return -1;});
print(JSON.stringify(a));

#### Chakra, JavaScriptCore
[1,2.2,3.3]

#### SpiderMonkey, V8 --harmony
[3.3,2.2,1]
```

**Comment by zenparsing** [comment]
The output of the `sort` function in this case is specified to the implementation-dependent. Specifically:

> If comparefn is not undefined and is not a consistent comparison function for the elements of this array (see below), the sort order is implementation-defined. 

The comparison function here is not "consistent".

https://tc39.github.io/ecma262/#sec-array.prototype.sort
