### ISSUE TITLE
RegExp should call property "lastIndex" using Symbol.search

### ISSUE THREAD

**Issue by igor-simoes** [microsoft/ChakraCore#5388]
Hi everyone,
there is an inconsistence on Chakra when I call this Proxy using Symbol.search.
The `-ES6Experimental` flag is activated.

Chakra: ch version 1.11.0.0-beta
OS: Ubuntu 16.04 x64

Steps to reproduce:
```
function test() {
   var get = [];
   var p = new Proxy(
       { exec: function () { return null; } },
       { get: function (o,k) { get.push(k); return o[k]; }}
   );
   RegExp.prototype[Symbol.search].call(p);
   return get + "" ===
       "lastIndex,exec,lastIndex";
}
if (!test())
   throw new Error("Test failed");
```

Actual results:
Error: Test failed

Expected results:
Pass without failures

It was observed that the array `get` contains only `"lastIndex,exec"`. The others engines (V8, SpiderMonkey and JavascriptCore) works as expected (lastIndex,exec,lastIndex).

cinfuzz

**Comment by dilijev** [comment]
@tcare does/should `-ES6Experimental` include `-ES6RegExSymbols` ?

In any case `ch -ES6Experimental -ES6RegExSymbols test.js` still fails.

**Comment by tcare** [comment]
@dilijev at some point this corresponded with Edge feature staging in the settings dialog, but I don't think this is the case now. I'm not 100% sure though. I don't think any unit tests should be using -ES6Experimental...

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
