### ISSUE TITLE
Fetch errors not displayed correctly

### ISSUE THREAD

**Issue by vainamov** [Microsoft/ChakraCore#5434]
I am currently developing an Angular application fetching data from an GraphQL server. When the GraphQL server throws an error and does not return data, the console in Edge would show a simple "Error on "fetch"" message whereas a browser like Firefox would show the correct error returned from the GraphQL server. As both browsers access the same Angular project connecting to the same GraphQL server through the same graphql-request module the problem seems to lie in Edge and presumably in Chakra.

The attached images show the returned error (1) from the GraphQL playground, (2) Firefox and (3) Edge.  

![Playground Error](https://user-images.githubusercontent.com/11841072/42423894-a6572004-8302-11e8-82a9-b96ceaf53db4.png)
![Firefox Error](https://i.xn--v-0fa.eu/aXM0cb)
![Edge Error](https://i.xn--v-0fa.eu/vDXzM9)

**Comment by vainamov** [comment]
Quick update: When the GraphQL server is responding with valid data, Edge also throws a fetch error while all other major browsers correctly receive and parse the data.

**Comment by vainamov** [comment]
Second update: Upon further investigation, similar issues also occur when using plain Xhr requests instead of fetch. Right now, I am not able to make any http request from my Angular application whatsoever in Edge.

**Comment by liminzhu** [comment]
I'm going to close this one since it's unrelated to ChakraCore. Feel free to re-open if you have anything we can help with.
