### ISSUE TITLE
Chakra should eval function with comma after params

### ISSUE THREAD

**Issue by igor-simoes** [Microsoft/ChakraCore#5478]
Hi everyone,
I found a case of inconsistency using `eval` to evaluate a function that have a comma after function params.

OS: Ubuntu 16.04 x64
Version: 1.10.1

Step to reproduce:
```
let fun = (a,b) => { print( a + b ); }
fun(1,2)
fun(1,2, )

fun = (a,b, ) => { print( a + b ); } // with comma after params
fun(1,2)

```
Actual results:
```
3
3
SyntaxError: Syntax error
```
Expected results:
```
3
3
3
```

V8, SpiderMonkey, JSC and XS works as expected.

**Comment by akroshg** [comment]
I think this is inconsistency on the arrow function.
As this works 
```js
let fun = function (a,b, ) { print( a + b ); } // with comma after params

```
Thanks @igor-simoes for reporting this.
