### ISSUE TITLE
Calling `Array.from` fails when passed a `Proxy` of a `function`

### ISSUE THREAD

**Issue by antross** [microsoft/ChakraCore#5480]
Found from searching the spec for uses of `isCallable` after hitting #5479. This repros on the latest ChakraCore from master today.

Repro:
```javascript
// returns `[2]`
Array.from([1], () => 2);

// returns `[2]` in Chrome (V8) and Firefox
// throws "TypeError: Array.from: argument is not a Function object" in ChakraCore
Array.from([1], new Proxy(() => 2, {}));
```

See step 3.a in http://www.ecma-international.org/ecma-262/#sec-array.from

**Comment by akroshg** [comment]
We should have 
```!JavascriptConversion::IsCallable(args[2])```
instead of 
```!JavascriptFunction::Is(args[2]))```
at https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/JavascriptArray.cpp#L10244
