### ISSUE TITLE
Inconsistent output compared with other JS engines when handling global property of RegExp

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#5508]
Hello,
The following code behaves incorrectly (inconsistent with other engines).
```
RegExp.prototype.__defineGetter__("global", () => true);
print("BT_FLAG");
```

In ChakraCore, the output is
`TypeError: Cannot redefine non-configurable property 'global'`

However, in V8 , SpiderMonkey and JSC, output is
`BT_FLAG`

BT group
2018.7.24

**Comment by MSLaguana** [comment]
This is because we have not yet enabled the ES6 regex prototype properties by default. If you run with `-ES6RegexPrototypeProperties` then it behaves as expected.

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
