### ISSUE TITLE
Support for regexp symbols like Symbol.split not enabled by default

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#5510]
Hello,
The following code behaves strangely (inconsistent with other engines).
```
function testToUint32InSplit() {
  var re;
  function toDictMode() {
    re.x = 42;
    delete re.x;
    return "def";
  }

  re *= /./g  // Needs to be global to trigger lastIndex accesses.
  return testToStringInReplace(toDictMode(new String('a'), 'length'), 1);
}

function testToStringInReplace() {
  var re;
  function toDictMode() {
    re.x = 42;
    delete re.x;
    return 42;
  }

  re = /./g;  // Needs to be global to trigger lastIndex accesses.
  return re[Symbol.split]("abc", { valueOf: toDictMode });
}

testToUint32InSplit();
testToStringInReplace();

print("BT_FLAG");
```

In ChakraCore, the output is
`TypeError: Object doesn't support property or method 'undefined'`

However, in V8 and SpiderMonkey, output is
`BT_FLAG`

BT group
2018.7.24

**Comment by MSLaguana** [comment]
This is because by default chakracore does not enable support for some of the regex symbols, like `Symbol.split`. If you specify the `-ES6RegexSymbols` flag then it turns on that support, and this test case behaves as expected.

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
