### ISSUE TITLE
Add an `IsRevoked` helper to JavascriptProxy for more code clarity

### ISSUE THREAD

**Issue by VSadov** [microsoft/ChakraCore#5542]
The code uses `handler == null ` all over the place as the way to check for revocations. 
That is a very confusing practice as it came up in https://github.com/Microsoft/ChakraCore/pull/5529

**Comment by rhuanjl** [comment]
This is a simple re-factoring that would be a good first contribution for anyone interested.

Look in JavascriptProxy.cpp and JavascriptProxy.h
