### ISSUE TITLE
Invalid procedure call or argument on Intl.DateTimeFormat

### ISSUE THREAD

**Issue by CheloXL** [Microsoft/ChakraCore#5544]
If I try to instantiate a Intl.DateTimeFormat with very specific values (see below) I get the above exception.
So far this only happens with these values. Tried others combinations (for dates, times) and they all seems to be working.

This is not locale specific. It happens with any available locale.

```
new Intl.DateTimeFormat("en-US", {"minute" : "numeric"});
new Intl.DateTimeFormat("en-US", {"minute" : "2-digit"});
new Intl.DateTimeFormat("en-US", {"second" : "numeric"});
new Intl.DateTimeFormat("en-US", {"second" : "2-digit"});
```

**Comment by CheloXL** [comment]
@MSLaguana Microsoft Edge 41.16299.547.0, Microsoft EdgeHTML 16.16299

**Comment by MSLaguana** [comment]
I don't see that behavior in a more recent version of edge, Microsoft Edge 42.17134.1.0, so this might have been fixed already.

**Comment by CheloXL** [comment]
The only thing that I can add is the errorcode (`-2146828283`). The stacktrace doesn't seems to have anything useful `'TypeError: Invalid procedure call or argument at Global code (file:///D:/Code/ExtremeFX/edge.html:8:3)'`

**Comment by jackhorton** [comment]
Perhaps an RS3 bug in WinGlob? I don't think we ever report invalid procedure call except for on COM errors. @Microsoft/target-dev FYI, we can also discuss this offline to figure out if we can get a good repro.

**Comment by CheloXL** [comment]
Just tested in Microsoft Edge 42.17134.1.0/Microsoft EdgeHTML 17.17134. Same behavior. Please note that I have enabled "Break on all exceptions" on the debugger.

**Comment by MSLaguana** [comment]
Hmm, even with 'break on all exceptions' I still don't see this. How are you running the code? I was just using the f12 console to type it in, but it looks like you are using some html page; can you provide a complete repro?

**Comment by CheloXL** [comment]
Well, yes, but that's not something quite complicated :)
Here you have:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Title</title>
</head>
<body>
	<script>
		new Intl.DateTimeFormat("en-US", {"minute" : "numeric"});
		new Intl.DateTimeFormat("en-US", {"minute" : "2-digit"});
		new Intl.DateTimeFormat("en-US", {"second" : "numeric"});
		new Intl.DateTimeFormat("en-US", {"second" : "2-digit"});
	</script>
</body>
</html>
```

**Comment by jackhorton** [comment]
For what its worth, I am seeing this as working on windows build 17728, though I suspect it will work with any ICU-enabled build of Chakra/Core.

**Comment by kfarnung** [comment]
@jackhorton Please confirm this is fixed and close if so.

**Comment by jefgen** [comment]
FWIW, I could repro this on RS4. Not sure if the ask is if this is fixed in RS5 though?

**Comment by jackhorton** [comment]
This is fixed in RS5 with the move to ICU
