### ISSUE TITLE
Destructuring unrecognized when nested in Array Rest

### ISSUE THREAD

**Issue by huaiyudavid** [microsoft/ChakraCore#5551]
Currently, the parser does not recognize the destructuring object/array as an array rest parameter and as such, everything in the object/array remains uninitialized. However, the specific case of having object destructuring works syntactically (see issue #5550). For example:
```
function foo(a, ...{...rest}) {
    console.log(JSON.stringify(rest));
}            
foo(1, 2, 3);
```
results in rest being empty, when it should be {0:2, 1:3}.

The parser currently treats the `{...rest}` as a var declaration instead of a destructuring assignment in `ParseFncFormals()`. 

Note: When fixing this, also check for the effect of eval("").

@tcare

**Comment by akroshg** [comment]
The other case which is not supported is 
```js
function foo(...[rest]) {
    print(rest);
}
foo(1,2,3);
```

**Comment by dilijev** [comment]
@tcare Can I poach this issue?

**Comment by tcare** [comment]
Go for it
