### ISSUE TITLE
The ChakraCore Team Is Hiring

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#556]
If you're looking at issues in this repo then you might be a candidate to work for Microsoft on ChakraCore. We're looking for code-generation and VM enthusiasts. Holler at me EdMaurer AT microsoft.com

**Comment by bterlson** [comment]
With so many issues this will get lost in the noise and be annoying to have open all the time. Perhaps we should have a link to our open positions in the readme?

**Comment by liminzhu** [comment]
+1 on adding it to readme.

**Comment by dilijev** [comment]
+1 for adding to readme

**Comment by liminzhu** [comment]
Is there a link to our open positions? I can add it in the [Contribute](https://github.com/Microsoft/ChakraCore#contribute) block.

**Comment by EdMaurer** [comment]
I approve of adding this solicitation to the readme! Accepting PRs :)

**Comment by EdMaurer** [comment]
The ChakraCore Team is no longer hiring.

**Comment by EdMaurer** [comment]
Breaking news - Chakra Hiring Again!

holler.
