### ISSUE TITLE
Assertion when deleting indexed property from frozen array

### ISSUE THREAD

**Issue by irinayat-MS** [Microsoft/ChakraCore#5564]
'use strict';
var o = [1,2,3]
Object.freeze(o);
console.log(delete o[1]);

Result: Assert: (result || !(propertyOperationFlags & (PropertyOperation_StrictMode | PropertyOperation_ThrowOnDeleteIfNotConfig)))

**Comment by zenparsing** [comment]
See https://tc39.github.io/ecma262/#sec-delete-operator-runtime-semantics-evaluation Step 1.5.d.
