### ISSUE TITLE
Proper use of name parameter for JsCreatePropertyId

### ISSUE THREAD

**Issue by crdumoul** [microsoft/ChakraCore#5570]
The documentation for JsCreatePropertyId at https://github.com/Microsoft/ChakraCore/wiki/JsCreatePropertyId indicates that the 'name' parameter may consist of only digits.

I'm confused as I expect the name to be the name of whatever property you're going to get/set, and not just a string representation of an integer.

**Comment by MSLaguana** [comment]
I believe that the intention of that is to say that it is permissible for the name to consist only of digits, not that it is required that it consist only of digits. You are certainly correct that it is not clear though!

**Comment by MSLaguana** [comment]
@liminzhu What do you think about rephrasing the documentation there to 

```
The name of the property ID to get or create. The string is expected to be ASCII / utf8 encoded. The name can be any javascript property identifier, including all digits.
```

**Comment by liminzhu** [comment]
Yeah I think that'd be more accurate.

**Comment by liminzhu** [comment]
Just updated the wiki. I will make a PR to adjust the comment in the header as well.

**Comment by crdumoul** [comment]
Thanks for the clarification!
