### ISSUE TITLE
ChakraCore crashes with assertion failure in ScriptContext.cpp:2809

### ISSUE THREAD

**Issue by leeswimming** [Microsoft/ChakraCore#5572]
Debug build of ChakraCore received SIGILL with an ASSERTION FAILURE.

ASSERTION 15614: (/data/ChakraCore/lib/Runtime/Base/ScriptContext.cpp, line 2809) this->threadContext->GetRecordedException() == nullptr || GetThreadContext()->HasUnhandledException()
 Failure: (this->threadContext->GetRecordedException() == nullptr || GetThreadContext()->HasUnhandledException())

```
$ ./build.sh --debug
$ ./out/Debug/ch test.js
$ cat test.js
WScript.LoadScript('', '', {
    toString: function () {
      func_0();
    }
});
```

OS: Ubuntu 18.04 LTS
Arch: x86_64

**Comment by liminzhu** [comment]
@digitalinfinity who is our xplat expert now?

**Comment by digitalinfinity** [comment]
Not an xplat issue (I can repro on windows), likely a ch issue. @duongnhn can you take a look please?
