### ISSUE TITLE
Chakra should not redeclare "undefined" keyword

### ISSUE THREAD

**Issue by igor-simoes** [Microsoft/ChakraCore#5576]
Hi everyone,
this is a inconsistency on Chakra that can declare global binding `undefined`.

OS: Ubuntu 16.04 x64
chakra: 1.10.1.0

steps to reproduce:
```js
function undefined () {print('Test failed')}
undefined()

'use strict'
function undefined () {print('Test failed')}
undefined()
```
Actual results:
Test failed
Test failed

Expected results:
SpiderMonkey: TypeError: Property must be configurable or both writable and enumerable (Early error)
V8: SyntaxError: Identifier 'undefined' has already been declared (Early Error)
JSC: TypeError: undefined is not a function. (In 'undefined()', 'undefined' is undefined)

The others engines throws an Error as expected. I'm not sure if this case should be a TypeError (jsc/sm) or a SyntaxError (V8) but the test cannot pass without failures.

cinfuzz

**Comment by igor-simoes** [comment]
Similar case with NaN function pass without failures.
```js
function NaN() {
    return 123;
}
```

**Comment by zenparsing** [comment]
See https://tc39.github.io/ecma262/#sec-candeclareglobalfunction

Among other things, if there is a property on the global object whose configurability is `false`, then a TypeError should be thrown.
