### ISSUE TITLE
RegExp.prototype.compile with incompatible Object

### ISSUE THREAD

**Issue by igor-simoes** [microsoft/ChakraCore#5579]
Hi everyone, 
according to [es6 specs](https://tc39.github.io/ecma262/#sec-regexp.prototype.compile) chakra should throw a TypeError if  the object does not have a RegExpMatcher.

OS: Ubuntu 16.04 x64
chakra version: 1.10.1.0

steps to reproduce:
```js
RegExp().constructor().constructor.prototype.compile(RegExp.prototype)
```
Actual results:
pass without failures

Expected results:
TypeError: Method RegExp.prototype.compile called on incompatible receiver [object Object]

V8, Spiderminkey and JSC works as expected. Running with the flag `-ES6Experimental` the test works as expected (maybe some flags are supported only in experimental mode).

cinfuzz

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
