### ISSUE TITLE
The source property of exception-metadata may be wrong.

### ISSUE THREAD

**Issue by yuzurihara** [Microsoft/ChakraCore#5585]
Hello.
The following script will raise a compile error.
`trace("摩天楼"2222, true, 3.14);`

And the source property of exception-metadata is wrong.
like this:
`trace("摩天楼"2222, true, m File`

In Scanner::SysAllocErrorLine(), `pEnd` calculation is failed with two or more bytes character.
It makes insufficient string and we can see uninitialized memory.

environment: ChakraCore v1.10.1/Win10/64bit

**Comment by boingoing** [comment]
Fixed by 7fd1686cb6bb872ad29120505f037f05f463233e
