### ISSUE TITLE
Implement Object.fromEntries

### ISSUE THREAD

**Issue by ljharb** [Microsoft/ChakraCore#5590]
Object.fromEntries is a stage 3 proposal: https://github.com/tc39/proposal-object-from-entries

It'd be great to get it implemented in Chakra soon!

Test262 tests are here: https://github.com/tc39/test262/pull/1676

Ref: https://github.com/tc39/proposal-object-from-entries/issues/21

**Comment by rhuanjl** [comment]
I could do this one if an external contribution would be welcome?

Looks like it would be particularly easy as a JsBuiltin though I could do it native as well.

Let me know if you want me to do it andvwhich approach (JsBuiltIn or native) would be preferred.

**Comment by akroshg** [comment]
@rhuanjl go ahead and have a stab at it. I'd prefer JsBuiltIn approach. 
/cc @sigatrev incase you need any help on that.

**Comment by rhuanjl** [comment]
Sorry for the delayed response - I should have a PR to submit for this at some point this week or next.
