### ISSUE TITLE
Clarification on JsRef tracking

### ISSUE THREAD

**Issue by crdumoul** [Microsoft/ChakraCore#5620]
The remarks in [the JsRef reference documention](https://github.com/Microsoft/ChakraCore/wiki/JsRef) say,
"A Chakra runtime will automatically track JsRef references as long as they are stored in local variables or in parameters (i.e. on the stack). Storing a JsRef somewhere other than on the stack requires calling JsAddRef and JsRelease to manage the lifetime of the object, otherwise the garbage collector may free the object while it is still in use."

Is this talking about tracking JsRef references on the JavaScript stack, or on the C++ stack of the host program?

**Comment by liminzhu** [comment]
This is referring to the C++ stack, I guess [this](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#memory-management) is a better explanation.

**Comment by crdumoul** [comment]
Thanks for the response.

I'm working with a host program in Rust that is calling into the ChakraCore library. Do you know if this will affect the JsRef reference tracking of stack variables?

**Comment by tecywiz121** [comment]
Is it possible to disable stack walking, and manually track all references?

**Comment by MSLaguana** [comment]
It isn't possible to disable stack walking, but if you make sure to `JsAddRef` and `JsRelease` all references manually at the correct times, then it will be safe regardless of whether the stack walk finds any references or not.

**Comment by fatcerberus** [comment]
For the record, there’s no real degree of separation between the JavaScript and native stacks: one is embedded within the other.
