### ISSUE TITLE
Array.toLocaleString should return typeof string instead string value

### ISSUE THREAD

**Issue by soterojunior** [Microsoft/ChakraCore#5621]
Hi everyone,

I find out an inconsistency in Array.toLocaleString when `typeof this` is called  the return is `test`. V8, SpiderMonkey and JavaScriptCore return `string` as expected. 

Chakra version: 1.10.2.0
O.S: MacOS High Sierra version 10.13.6

step to reproduce: 
```js
"use strict";

Object.defineProperty(String.prototype, "toLocaleString", {
    get() {
        return function() { return typeof this; };
    }
})

print(["test"].toLocaleString())
```
actual result: 
test

expected result:
string

cinfuzz

**Comment by kfarnung** [comment]
ESHost repro:

```console
>eshost -is test5.js
## Source
"use strict";

Object.defineProperty(String.prototype, "toLocaleString", {
    get() {
        return function() { return typeof this; };
    }
})

print(["test"].toLocaleString())

#### cc-1.7.6, cc-1.8.5, Chakra
test

#### JavaScriptCore, SpiderMonkey, V8, V8 --harmony
string

```

**Comment by jackhorton** [comment]
Array.prototype.toLocaleString already needs to be updated to Intl spec, [which explicitly calls out that toLocaleString should be invoked on each element](https://tc39.github.io/ecma402/#sup-array.prototype.tolocalestring). The current fix is only one line, though, so ill probably throw it in with my current Intl PR

**Comment by jackhorton** [comment]
Since its a simple fix, I am going to label this as a good first issue instead.

**Comment by Fly-Style** [comment]
Can I pick it?

**Comment by rhuanjl** [comment]
@Fly-Style from one external contributor to another - if an issue is marked help wanted, has no referenced PR and no one else has commented saying they're doing it just give it a try (and comment saying that you are) no reason to wait for someone to say you can - the help wanted label already tells you that.

**Comment by jackhorton** [comment]
Go for it! To start, I would look at the method Js::JavascriptArray::EntryToLocaleString, and follow along from there to the point where the conversion actually takes place.

**Comment by mintunitish** [comment]
I will be taking this.
