### ISSUE TITLE
The URL class in JavaScript doesn't implement the full spec (search params)

### ISSUE THREAD

**Issue by macdonaldr93** [Microsoft/ChakraCore#5626]
I recently hit a bug where Edge doesn't expose `searchParams` as a property on the URL class. According to the URL spec, `searchParams` is supposed return an instance of URLSearchParams.

Reference: https://url.spec.whatwg.org/#url-class

Codepen: https://codepen.io/macdonaldr93/pen/wEKwLa

**Comment by kfarnung** [comment]
Thanks for the report @macdonaldr93! Unfortunately this is an issue in Edge (as opposed to Chakra). Can you please open an issue in their tracker (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) so they can investigate?  Feel free to paste the link to the new issue here once it's open.

**Comment by macdonaldr93** [comment]
Sounds good! Thanks for the response. In there issue tracker, when I selected JavaScript, it told me to open the issue here. Not sure what the category should be otherwise...

**Comment by kfarnung** [comment]
For lack of a better option I'd use "Network: XHR, Web Sockets, Fetch" since that's the closest category.  Since `URL` isn't part of the JavaScript language it's not implemented as part of Chakra.

**Comment by kfarnung** [comment]
Just to make sure I understand the issue, what is the expected output from your test page supposed to be?

In a recent Insider Preview build of Edge it looks correct to me:
>URL Search Params
> q=true
> q=true
> https://edge.com/?q=true

I don't have access to an older build at the moment, so it's possible this was fixed at some point or there's something else going on.  I'd still open an issue on the Edge issue tracker.

**Comment by macdonaldr93** [comment]
Okay thanks! And yeah I was getting `undefined` in the place of the search params. We were tophatting on older laptop so that might be why.
