### ISSUE TITLE
Wrong output of %TypedArray% 's constructor

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5638]
Executing following code : 
```
print(Int32Array.prototype.__proto__.constructor)
```
Output of ch is : 
```
function() {
    [native code]
}
```

However, output(v8, spm, jsc) should be : 
```
function TypedArray() {
    [native code]
}
```

BT group
2018.08.26

**Comment by jackhorton** [comment]
Looks like #3332 -- we are technically spec compliant, but I think we all agree that including the name would be better.
