### ISSUE TITLE
Fail to throw TypeError when using typeof to access  %TypedArray% Intrinsic Object's byteOffset

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5639]
Executing following code in ch 1.10: 
```
print(typeof Int32Array.prototype.__proto__.byteOffset);
```
Output of ChakraCore:
```
undefined
```
However, output should be : 
```
Exception: TypeError: Receiver should be a typed array view
```

BT group
2018.08.26

**Comment by kfarnung** [comment]
@zenparsing Can you look into this behavior?

**Comment by zenparsing** [comment]
The relevant section is https://tc39.github.io/ecma262/#sec-get-%typedarray%.prototype.byteoffset step 3.

It looks to me like this is fixed in master. Confirm?

**Comment by kfarnung** [comment]
Confirmed to be fixed in master:

```console
>ch.exe test.js
TypeError: 'this' is not a typed array object
   at Global code (D:\!Investigations\GH5639\test.js:1:1)
```
