### ISSUE TITLE
confusing block

### ISSUE THREAD

**Issue by enclairfarron** [Microsoft/ChakraCore#5641]
### html
`<button id="upload">upload</button>`
### js
`let button = document.getElementById('upload');`
`let input = document.createElement('input');`
` input.type = 'file';`
`button.onclick = function () {`
`        input.click();`
`        console.log('unblock')`
`    };`

### problem
   When i run this demo in Chrome or Firefox,unblock will be shown after clicking.But in Edge,opening upload input is something like blocking the thread unless i finish the upload input. Is it a bug or something else for reasons?

**Comment by liminzhu** [comment]
Thanks for opening the issue @enclairfarron! This looks like a DOM issue rather a JavaScript engine bug tbh, and the best way to get it sorted out would be filing an issue on [Edge Issue Tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).

**Comment by enclairfarron** [comment]
@liminzhu thanks for reply,this repo is the only one i found in MS open source on Github  about Edge.I will switch to Edge Issue later.

**Comment by liminzhu** [comment]
No problem @enclairfarron . I'm closing the issue now since this will move to Edge issue tracker, but feel free to re-open if you have more questions.
