### ISSUE TITLE
JsBuiltIns show as `funcName` rather than `Constructor.prototype.funcName` in stack traces

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ChakraCore#5643]
```js
try {
  [1, 2, 3].forEach(() => { throw new Error(); });
} catch (e) {
  print(e.stack);
}
```

This shows a line for `forEach (native code)` with jsbuiltins enabled, while it shows `Array.prototype.forEach (native code)` with jsbuiltins disabled. Same for .filter.

**Comment by rhuanjl** [comment]
This should be simple to fix - just need to update:
https://github.com/Microsoft/ChakraCore/blob/0b13df812da459410db7adde83e1b17ac12c4152/lib/Runtime/Library/JsBuiltInEngineInterfaceExtensionObject.cpp#L357

I note that the update would have to be slightly different to accommodate Object.fromEntries (which is static) compared with the other builtins which are properties of the prototype.

**Comment by jackhorton** [comment]
Yup -- I was going to wait for fromEntries before doing anything to it, since we can use the new prototype property to say whether to add ".prototype" to the middle of the string. Also, it looks like theres no standard for native functions (V8 shows Array.forEach, SM/Firefox show... nothing? Stack traces in FF don't make a ton of sense to me), it would just be to not change our existing behavior.
