### ISSUE TITLE
Functions 'length' is configurable but can't be deleted.

### ISSUE THREAD

**Issue by leobalter** [Microsoft/ChakraCore#5646]
Works on built-in functions and other non ECMAScript forms:

```js
var x = function() {};
Object.getOwnPropertyDescriptor(x, "length").configurable; // true
delete x.length; // expected true, received false
Object.getOwnPropertyDescriptor(x, "length"); // expected undefined, received the previous descriptor for 'length'
```

Same works for __some__ built-in functions, not all of them.

```
eshost -s -x 'var x = Array.prototype.forEach; print(Object.getOwnPropertyDescriptor(x, "length").configurable); print(delete x.length); print(Object.getOwnPropertyDescriptor(x, "length"));'
#### ch, d8, jsc, jsshell, node
true
true
undefined

eshost -s -x 'var x = Array.prototype.filter; print(Object.getOwnPropertyDescriptor(x, "length").configurable); print(delete x.length); print(Object.getOwnPropertyDescriptor(x, "length"));'
#### d8, jsc, jsshell, node
true
true
undefined

#### ch
true
false
[object Object]
```

**Comment by leobalter** [comment]
This is described in tests like `test/built-ins/Array/prototype/filter/length.js` but I couldn't find any matching bug here.

**Comment by rhuanjl** [comment]
Was this testing vs master or vs a release? I believe I fixed this in master with #5405

**Comment by leobalter** [comment]
I'm using jsvu to fetch chakracore so I imagine this should be a release version and I'm out of date and hopefully this problem is fixed. 

I'm also planning to add a few tests on Test262 for checking the length property in function forms, it should prevent any regression and confirm everything is fixed.

```
ch --version
ch version 1.10.2.0
```

**Comment by MSLaguana** [comment]
Yep, jsvu is using the releases that we publish, while the fix has landed in master which doesn't have a release yet. It should be fixed with @rhuanjl's change, but it won't show up in a release for a while.

**Comment by leobalter** [comment]
@rhuanjl @MSLaguana  feel free to close if you believe this is a duplicate or fixed, but if it's possible I'd appreciate if someone could confirm these cases are also fixed from #5405.

**Comment by jackhorton** [comment]
I can confirm that this is fixed in my local copy of master(ish):

```
## Source
var x = function() {};
print(Object.getOwnPropertyDescriptor(x, "length").configurable); // true
print(delete x.length); // expected true, received false
print(JSON.stringify(Object.getOwnPropertyDescriptor(x, "length"))); // expected undefined, received the previous descriptor for 'length'


┌────────────────────────────────┬─────────────────────────────────────────────────────────────────────┐
│ ch (Chakra1 x64_debug)         │ true                                                                │
│ ch (Chakra2 x64_debug)         │ true                                                                │
│ SpiderMonkey                   │ undefined                                                           │
│ V8                             │                                                                     │
├────────────────────────────────┼─────────────────────────────────────────────────────────────────────┤
│ Chakra (JSVU)                  │ true                                                                │
│                                │ false                                                               │
│                                │ {"value":0,"writable":false,"enumerable":false,"configurable":true} │
└────────────────────────────────┴─────────────────────────────────────────────────────────────────────┘
```

**Comment by rhuanjl** [comment]
Just for reference #5405 made "length" of functions (and bound functions) a normal configurable property - prior to this it had lots of special casing all of which has now been removed so it should behave like any other configurable property.

Note this has not yet been done for async functions and generator functions there is a follow up PR #5610 open to fix for those.

Also the following test cases were added to ChakraCore's CI with #5405 which I hope somewhat extensively cover this: https://github.com/Microsoft/ChakraCore/blob/master/test/Function/funcAndboundFuncLength.js
