### ISSUE TITLE
Unable to print exception message

### ISSUE THREAD

**Issue by luboslenco** [Microsoft/ChakraCore#5660]
First I just want to congratulate on your work on Chakra, thank you for making it available to us. We recently switched from v8 to chakra as our main driver in [Krom](https://github.com/Kode/Krom) / [Armory](https://armory3d.org/) game engine and we are quite excited!

With our [current setup](https://github.com/Kode/Krom/blob/master/Sources/main.cpp#L2476) I am able to print out this error message after an exception, which is almost perfect:

```
Uncaught exception:
                scene.raw.name = "test";
                ^
TypeError
   at Anonymous function (krom.js:333:3)
   at iron_App.render (krom.js:1293:5)
   at kha_System.render (krom.js:23463:3)
   at kha_SystemImpl.renderCallback (krom.js:23588:2)
```

The last bit I want to add is an exception message, something like:
> `Cannot read property 'raw' of null`

I am using [JsGetAndClearExceptionWithMetadata](https://github.com/Microsoft/ChakraCore/wiki/JsGetAndClearExceptionWithMetadata) to retrieve the metadata object. Accessing the `metadata.exception.name` property reads `TypeError` like I expect, however accessing `metadata.exception.message` gives me an empty string.

I am sure I am missing something obvious here, will appreciate any pointers.

**Comment by sethbrenith** [comment]
How are you getting the `message` property? I tried adding the following code to our test function `ExceptionHandlingTest`, and it passed:

```c++
REQUIRE(JsRunScript(_u("var a = {}; a.b.c = 3;"), JS_SOURCE_CONTEXT_NONE, _u(""), nullptr) == JsErrorScriptException);
REQUIRE(JsHasException(&value) == JsNoError);
CHECK(value == true);

REQUIRE(JsGetAndClearExceptionWithMetadata(&exceptionMetadata) == JsNoError);
REQUIRE(JsHasException(&value) == JsNoError);
CHECK(value == false);

REQUIRE(JsGetPropertyIdFromName(_u("exception"), &property) == JsNoError);
REQUIRE(JsGetProperty(exceptionMetadata, property, &exception) == JsNoError);

REQUIRE(JsGetPropertyIdFromName(_u("message"), &property) == JsNoError);
REQUIRE(JsGetProperty(exception, property, &metadataValue) == JsNoError);
REQUIRE(JsGetValueType(metadataValue, &type) == JsNoError);
CHECK(type == JsString);
{
    const WCHAR *stringValue;
    size_t stringLength;
    REQUIRE(JsStringToPointer(metadataValue, &stringValue, &stringLength) == JsNoError);
    CHECK(stringLength > 0);
    CHECK(wcscmp(_u("Unable to set property 'c' of undefined or null reference"), stringValue) == 0);
}
```

**Comment by sethbrenith** [comment]
Also, thanks for the feedback and I'm glad to hear you're excited!

**Comment by sethbrenith** [comment]
Never mind, you already answered my question in your link. Your code looks fine to me, and `message` should be present, so this seems likely to be a bug on our side.

**Comment by MSLaguana** [comment]
I see that you aren't checking the return code of the JSRT calls, such as `JsCopyString`. Are they perhaps returning an error for some reason?

**Comment by sethbrenith** [comment]
Okay, we investigated some more (thanks @MSLaguana and @irinayat-MS) and the issue is that your output binaries don't include the ChakraCore string resources, so when constructing an exception the program fails to find the string. When we build ChakraCore.dll, we include jserr.gen: the [vcxproj](https://github.com/Microsoft/ChakraCore/blob/3daa56768f45594ec3461731e68865323900acf1/lib/Parser/CMakeLists.txt#L26) creates a .rc2 file, and then [another file](https://github.com/Microsoft/ChakraCore/blob/master/bin/ChakraCore/ChakraCore.rc#L14) includes it. In order to access any strings from [rterrors.h](https://github.com/Microsoft/ChakraCore/blob/1ef7ea802a796aaa91690159b1dba891c9b0ed62/lib/Parser/rterrors.h) you'll need to do something similar.

**Comment by MSLaguana** [comment]
One other thing I'll note here: We don't currently support statically linking chakracore on windows. There are a number of things which trigger on DLL load, and with the way you've linked things in that is probably not happening, so you may end up with strange GC behaviors or other issues.

**Comment by RobDangerous** [comment]
We already hook into the code in bin/ChakraCore/ChakraCoreDllFunc.cpp but I'll have a closer look to make sure we call all the things. Thanks for the hint and super thanks for figuring the exception message thing out for us.
Would you be interested in pull requests to support static linking and similar portability/build-versatility fixes? We also got this running on an Xbox.

**Comment by MSLaguana** [comment]
We have been considering adding support for statically linking chakracore on windows, so if you have done the work and are willing to PR it back we'll certainly take a look at it!

**Comment by RobDangerous** [comment]
Sure thing, will do.
