### ISSUE TITLE
BUG: xplat Array.prototype.sort produces incorrect results when length > 512

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#5667]
Run the below script with eshost on macOS and it will throw in Ch but pass in all other engines - from reading CC's source there is a different sort algorithm used on xplat for arrays > 512 elements in length than on windows and I think there's an error in it's logic.

```js
const arr = [];
for (let i = 0; i < 600; ++i)
{
    arr[i] = Math.random() * 100 | 0;
}
arr.sort(function (a, b){ return a - b;});


for (let i = 1; i < 600; ++i)
{
    if (arr[i] < arr[i - 1]) // i.e. sort has not completed correctly
    {
        throw new Error (arr.slice(0, i + 5));
    }
}
```

**Comment by kfarnung** [comment]
Confirmed on Ubuntu 16.04:

```console
## Source
const arr = [];
for (let i = 0; i < 600; ++i)
{
    arr[i] = Math.random() * 100 | 0;
}
arr.sort(function (a, b){ return a - b;});


for (let i = 1; i < 600; ++i)
{
    if (arr[i] < arr[i - 1]) // i.e. sort has not completed correctly
    {
        throw new Error (arr.slice(0, i + 5));
    }
}



#### JavaScriptCore, SpiderMonkey, V8, V8 --harmony, XS


#### Chakra
Error: 0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,3,3,3,4,4,4,5,5,5,6,6,6,6,7,6,7,7,7,6

```

**Comment by fatcerberus** [comment]
Ouch, this is a nasty bug.  This is the kind of thing I might have spent hours futilely trying to find the bug in my own code... only to finally realize it was an engine bug... 😰  Needless to say, I'm glad someone else discovered it before me!

What's worse, there's no workaround except to implement your own sort...

**Comment by kfarnung** [comment]
I think I have a fix for this, I'm still testing it out.

**Comment by kfarnung** [comment]
Thanks for the report @rhuanjl!
