### ISSUE TITLE
TypeError shouldn't be thrown when function's argument is an empty array using spread operator

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#5677]
Hi, executing following code, ChakraCore will throw a TypeError. It seems that ch treats the empty array as undefined or null.
```
function f(...[]) {return 23};
f();
print("BT_FLAG");
```
The output of ChakraCore:
`TypeError: Unable to get property 'Symbol.iterator' of undefined or null reference`

However, the output should be:
`BT_FLAG`

BT group
2018.09.10

**Comment by akroshg** [comment]
This works if we pass the empty array during call
```js
function f(...[]) {return 23};
f([]);
print("BT_FLAG");
```
or 

```js
function f([]) {return 23};
f();
print("BT_FLAG");
```

**Comment by zenparsing** [comment]
Related to #5551

**Comment by fatcerberus** [comment]
I actually didn't even realize `function f(...[]) {return 23}` was legal syntax.  Huh.

@akroshg Interestingly, your second case actually throws in Node 10.9:
```
> function f([]) {return 23};
undefined
> f()
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at f (repl:1:11)
> process.version
'v10.9.0'
```

**Comment by ProfNandaa** [comment]
Same error is thrown on V8.

**Comment by fatcerberus** [comment]
@ProfNandaa Node.js *is* V8, unless using node-chakracore.

**Comment by rhuanjl** [comment]
This is fixed in master.
