### ISSUE TITLE
Realization of String.prototype.split is inconsistent with ecma-262

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#5679]
Hello, executing following code:
```
let arg_0 = /(.)\1/i;
let handler_0 = {get:function (oTarget, sKey) { 
    print(sKey.toString());
    return Reflect.get(oTarget, sKey); 
}};
var p_0 = new Proxy(arg_0, handler_0);
(0 + "\u1234\0").split(p_0);
```
In [ecma-262](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-string.prototype.split),  seperator's Symbol.split should be got firstly. However, ch get Symbol.toPrimitive firstly.

Output of ch:
```
Symbol(Symbol.toPrimitive)
toString
TypeError: RegExp.prototype.toString: 'this' is not a RegExp object
```
Output of other engines:
```
Symbol(Symbol.split)
constructor
flags
Symbol(Symbol.match)
source
```

BT group
2018.09.10

**Comment by MSLaguana** [comment]
This is because by default we disable support for the ES6 regex symbols. If you enable that support (such as we do for node-chakracore, or via `-ES6RegExSymbols` in a test or debug build) then this case works as expected.

**Comment by jackhorton** [comment]
I feel like we should just take the jump and enable all of the ES6 bits at this point...

**Comment by fatcerberus** [comment]
This is pretty much why I have `JsRuntimeAttributeEnableExperimentalFeatures` in my runtime creation for miniSphere (well... that, and also for `import()`).  I'd be giving up too much spec compliance to leave it off.

**Comment by jackhorton** [comment]
Hosts _can_ get more fine-grained control the same way that ch.exe does with the HostConfigFlags/TestHooks infrastructure, I believe. If you wanted to be more precise about what you enabled.

**Comment by jackhorton** [comment]
Ah yes, I forgot that they required test builds.

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
