### ISSUE TITLE
Wrong realization of Object.defineProperty

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5680]
Hello, executing following code:
```
let arg_0 = {};
let arg_2 = {};
var i = 1;
let handler_0 = {
	defineProperty : function (oTarget, sKey, oDesc) { 
		return Reflect.defineProperty(oTarget, sKey, oDesc); 
	}
};
let handler_2 = {
	has : function (oTarget, sKey) { 
		print(i++);
                print(sKey.toString());
		return Reflect.has(oTarget, sKey);
	}
}
let p_0 = new Proxy(arg_0, handler_0);
let p_2 = new Proxy(arg_2, handler_2);
Object.defineProperty(p_0,"c",p_2);
```
Output of ch:
```
1
enumerable
2
configurable
3
value
4
writable
5
get
6
set
7
enumerable
8
configurable
9
value
10
writable
11
get
12
set
```
However, the output should be:
```
1
enumerable
2
configurable
3
value
4
writable
5
get
6
set
```
It seems that chakracore call  [ToPropertyDescriptor](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-object.defineproperty) twice.

BT group
2018.09.10

**Comment by rhuanjl** [comment]
I've taken a quick look at this - it repros in latest master.

It's specifically an issue with Proxies that have a defineProperty trap that uses Reflect.defineProperty - ToPropertyDescriptor is called before the Proxy check and then the trap calls it again; I should be able to submit a fix tomorrow.

**Comment by rhuanjl** [comment]
Sorry for not submitting a fix for this yet as per my comment above - taking a bit of time to think how to do it neatly - my original fix was ugly.
