### ISSUE TITLE
When does Chakra require executable pages?

### ISSUE THREAD

**Issue by tecywiz121** [Microsoft/ChakraCore#5700]
Hey!

I'm looking at running Chakra under seccomp on Linux. Generally speaking, when does the VM need to allocate executable memory (ex. `mmap` with `PROT_EXEC`)?

I'm assuming most of that is limited to the JIT, but are there other cases?

Thanks!

**Comment by MSLaguana** [comment]
In addition to the JIT, we also have executable thunks used to identify interpreter frames uniquely rather than having a single trampoline location. This is so debugging can be simpler.

I'm not sure if there are any other executable pages... none come to mind at the moment.

**Comment by jackhorton** [comment]
One thing to note is that at least on Windows, both of these features can be turned off (JIT and dynamic thunks) to have absolutely 0 executable allocations. I know we support nojit versions of linux/macOS builds, but I am not sure if we support turning off dynamic thunks there too.

**Comment by sigatrev** [comment]
@jackhorton The dynamic interpreter thunks are disabled along with the JIT on all platforms.
