### ISSUE TITLE
Build issues with Ubuntu 16.04

### ISSUE THREAD

**Issue by jessebartels** [Microsoft/ChakraCore#5705]
Hey folks,

Recently I've been trying to build ChakraCore for some dynamic analysis experiments and I have been running into build issues. I've installed all of the dependencies, but running ./build.sh gives me a linking error, specifically:

> Run Build Command:"/usr/bin/ninja" "cmTC_2d072"
> 
>   [1/2] Building CXX object CMakeFiles/cmTC_2d072.dir/testCXXCompiler.cxx.o
> 
>   [2/2] Linking CXX executable cmTC_2d072
> 
>   FAILED: : && /usr/bin/clang++
>   CMakeFiles/cmTC_2d072.dir/testCXXCompiler.cxx.o -o cmTC_2d072 -rdynamic &&
>   :
> 
>   /usr/bin/ld: cannot find -lstdc++
> 
>   clang: error: linker command failed with exit code 1 (use -v to see
>   invocation)
> 
>   ninja: build stopped: subcommand failed.

I have tried a few things to work around this:
- Adding -stdlib=stdc++ to command line option in CMake
- Using ninja
- Updating clang/lllvm/libc++
- Setting my library path to where libstdc++.so.6 lives
- Symlinking libstdc++ to where libstdc++.so.6 lives

Symlinking libstc++ fixes the linker problem, but then I get build issues for a lot of files:

> ../../pal/inc/safemath.h:41:10: fatal error: 'type_traits' file not found
> #include <type_traits>

Has anyone had build experiences like this before? I appreciate your time and patience and appreciate any assistance. Thanks

**Comment by sethbrenith** [comment]
This sounds a bit like #2403, which was solved by installing a missing package. Could you please try the following, just to make sure all of these are installed?

```bash
sudo apt-get install -y build-essential cmake clang libclang-dev uuid-dev libunwind-dev libicu-dev liblttng-ust-dev
```

**Comment by jessebartels** [comment]
Thanks for the quick response! I've run the command above but I am still getting build issues with:

> ../../pal/inc/safemath.h:41:10: fatal error: 'type_traits' file not found
> #include <type_traits>

On the bright side I no longer need the symlink.

**Comment by sethbrenith** [comment]
Hm, either you don't have type_traits or the include path doesn't contain the right directory. Could you please check the following and see if it turns anything up?

```bash
ls /usr/include/c++/*/type_traits
```

**Comment by sethbrenith** [comment]
If that search doesn't find anything, I believe you can get it with

```bash
sudo apt-get install libstdc++6
```

**Comment by jessebartels** [comment]
I ran both commands and it appears that I have trait types (output from ls below). According to apt-get I already have the latest version

> /usr/include/c++/4.8.5/type_traits  /usr/include/c++/4.9.4/type_traits	/usr/include/c++/5.4.0/type_traits
> /usr/include/c++/4.8/type_traits    /usr/include/c++/4.9/type_traits	/usr/include/c++/5/type_traits

**Comment by MSLaguana** [comment]
What version of clang do you have installed?  `clang --version` should give that information. Could you also try creating a dummy file `test.cc` with contents `#include <type_traits>` and then try compiling that with `clang -v`? It won't link of course, but it should spit out the include paths that it is checking, and we'll see if it's an issue with the clang version or with the arguments that we are giving it in our cmake scripts.

**Comment by jessebartels** [comment]
I have clang 6.0. Clang -v on the dummy files gives the following (my apologies for the wall of text):

> clang version 6.0.1-svn334776-1~exp1~20180912093054.102 (branches/release_60)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7
> Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
> Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8.0.1
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1
> Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7
> Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
> Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8.0.1
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.4.0
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
> Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0
> Candidate multilib: .;@m64
> Selected multilib: .;@m64
> Found CUDA installation: /usr/local/cuda, version 7.5
>  "/usr/lib/llvm-6.0/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cc -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/lib/llvm-6.0/lib/clang/6.0.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++ -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++/backward -internal-isystem /usr/include/clang/6.0.1/include/ -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-6.0/lib/clang/6.0.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /lhome/jessebartels/chakraAttempt/ChakraCore -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /tmp/test-08408f.o -x c++ test.cc
> clang -cc1 version 6.0.1 based upon LLVM 6.0.1 default target x86_64-pc-linux-gnu
> ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++/x86_64-linux-gnu"
> ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++/backward"
> ignoring nonexistent directory "/include"
> ignoring duplicate directory "/usr/include/clang/6.0.1/include"
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++
>  /usr/include/clang/6.0.1/include
>  /usr/local/include
>  /usr/include/x86_64-linux-gnu
>  /usr/include
> End of search list.
> test.cc:1:10: fatal error: 'type_traits' file not found
> #include <type_traits>
>          ^~~~~~~~~~~~~
> 1 error generated.

The directory /usr/include/c++/5.4.0/ has type_traits in it. I decided to copy 5.4.0 to the directory /usr/include/c++/x86_64-linux-gnu and now the type_traits issue has gone away. Unfortunately there is now this error:

> /usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../../include/c++/x86_64-linux-gnu/type_traits:38:10: fatal error: 'bits/c++config.h' file not found
> #include <bits/c++config.h>

It would appear that /usr/include/c++/x86_64-linux-gnu has a bits directory but there is no c++config.h file in it.

**Comment by jessebartels** [comment]
First off, I gotta thank you folks for helping out (seriously, these are not the fun kind of problems to be plugging away at). I decided to continue going down the rabbit hole by copying my bits directory (with the ++config.h) into a spot where clang was looking (from /usr/include/x86_64-linux-gnu/c++/5/bits to /usr/include/x86_64-linux-gnu/). Now I don't have any more dependency issues but the linker is complaining about 

> /usr/bin/ld: cannot find -lstdc++

again. This kinda goes right back to the original problem but at least I was able to compile successfully until the last 12 .cpp files. If anyone has some pointers on why the linker isn't having a good time I would love to know. Thank you very much

**Comment by jessebartels** [comment]
I finally got the build process to work! It entailed getting /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21 and following the steps from [here](https://stackoverflow.com/questions/39332406/install-libc-on-ubuntu). I then had to symlink libstdc++.so to point at 6.0.21 and including the flags "-std=c++11 -stdlib=libc++" in the CMakelists.txt 

I seriously appreciate the help folks! Absolutely awesome (thank you!)
