### ISSUE TITLE
BUG: Math.cos and Math.sin function cause crash

### ISSUE THREAD

**Issue by taylorgordon20** [Microsoft/ChakraCore#5725]
This seems a little ridiculous, but I am encountering a sudden crash in a very simple usage of the JSRT. 

This is my complete usage:

```
constexpr auto kScript = R"(
var module = {}
module.foo = function() {
  var junk = Math.cos(0.5) * 0;
}
module;
)";

int main() {
 JsRuntimeHandle runtime;
  JsCreateRuntime(JsRuntimeAttributeNone, nullptr, &runtime);

  JsContextRef context;
  JsCreateContext(runtime, &context);

  JsValueRef module;
  {
    JsSetCurrentContext(context);

    JsValueRef script, url;
    JsCreateExternalArrayBuffer((void*)kScript, strlen(kScript), nullptr, nullptr, &script);
    JsCreateString("foo.js", 6, &url);

    JsRun(script, 0, url, JsParseScriptAttributeNone, &module);
    JsAddRef(module, nullptr);

    JsSetCurrentContext(JS_INVALID_REFERENCE);
  }

  for (int i = 0; i < 100000; i += 1) {
    std::cout << "iteration=" << i << std::endl;
    JsSetCurrentContext(context);

    JsValueRef fn;
    JsPropertyIdRef prop_id;
    JsCreatePropertyId("foo", 3, &prop_id);
    JsGetProperty(module, prop_id, &fn);

    JsValueRef undefined;
    JsGetUndefinedValue(&undefined);
    JsValueRef args[] = {undefined};

    JsValueRef ret;
    JsCallFunction(fn, args, 1, &ret);

    JsSetCurrentContext(JS_INVALID_REFERENCE);
  }
}
```

When I run the program it gets to iteration 200 or so and then terminates with error code "1073807364". The unbelievable thing is that I can replace the actual JS script with some fairly arbitrarily complicated code and everything works fine. There is something in particular about operating on the result of Math.cos (even multiplying by 0) that causes the crash. 

I can reproduce the value by replacing Math.cos(0.5) with Math.sin(0.5) or Math.sin(0.1) but if I actually hard-code the result of these functions I don't get the premature termination. I'm on Windows 10 and linking to Chakra with a vcpkg installation.

**Comment by taylorgordon20** [comment]
BTW this repros if I use a global function approach as well:

```
constexpr auto kScript = R"(
function foo() {
  var junk = Math.cos(0.5) * 0;
}
)";

,,,

    JsValueRef global, fn;
    JsGetGlobalObject(&global);
    JsPropertyIdRef prop_id;
    JsCreatePropertyId("foo", 3, &prop_id);
    JsGetProperty(global, prop_id, &fn);

    JsValueRef undefined;
    JsGetUndefinedValue(&undefined);
    JsValueRef args[] = {undefined};

    JsValueRef ret;
    JsCallFunction(fn, args, 1, &ret);
```

**Comment by MSLaguana** [comment]
I can't seem to reproduce this issue on my machine. What version of ChakraCore are you using, and are you building for x86 or x64, release or debug, windows or Linux or mac?

The error code that you get is `0x40010004` which is used for `DBG_TERMINATE_PROCESS` which essentially means that we hit some kind of fatal error, but that can come from a number of different places and without being able to debug it I can't say where.

**Comment by MSLaguana** [comment]
Using the same dlls and libs that we published for 1.11, I still don't see this failure. Is it possible for you to make a self-contained repro, e.g. put your build files into a repo, or zip it up and put it somewhere I can see it?

**Comment by taylorgordon20** [comment]
Made a repo: https://github.com/taylorgordon20/charkra_test

It's setup to use bazel to build (the chakra_test target builds the test executable with issues), The compilation is effectively some command like:

`C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-fastbuild/genfiles /Ibazel-out/x64_windows-fastbuild/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-fastbuild/genfiles/external/bazel_tools /Ibazel-out/x64_windows-fastbuild/bin/external/bazel_tools /Ithird_party/include /Ibazel-out/x64_windows-fastbuild/genfiles/third_party/include /Ibazel-out/x64_windows-fastbuild/bin/third_party/include /showIncludes /MD /Od /Z7 /DDEBUG /Fobazel-out/x64_windows-fastbuild/bin/_objs/chakra_test/main.obj /c main.cpp`

And the linking is:

`C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/HostX64/x64/link.exe /nologo /OUT:bazel-out/x64_windows-fastbuild/bin/chakra_test.exe /SUBSYSTEM:CONSOLE /MACHINE:X64 @bazel-out/x64_windows-fastbuild/bin/chakra_test.exe-2.params /DEBUG:FASTLINK /INCREMENTAL:NO`

**Comment by MSLaguana** [comment]
Using your repo I can reproduce the error, but the chakracore.dll that you've included there isn't one that we have published ourselves, and if I replace the chakracore.dll with one that we published, then the issue goes away.

I am not familiar with vcpkg, but looking at https://github.com/Microsoft/vcpkg/blob/master/ports/chakracore/portfile.cmake it seems like it is actually trying to compile chakracore itself / have you compile it yourself. It does mention pdbs in there; do you have the pdb for your chakracore.dll? If so, could you share that, then I can try to work out the specific cause of the crash, which may point to what's gone wrong in making the chakracore.dll?

**Comment by taylorgordon20** [comment]
I've updated the git repo to include the ChakraCore.pdb file.

**Comment by kfarnung** [comment]
Thanks for the repro @taylorgordon20, it looks like this is an incompatibility between ChakraCore and the dynamically linked CRT.  When I tried this myself I ended up with a build which linked to `ucrtbase` rather than `msvcrt`.  That's not currently a supported configuration for building ChakraCore, which explains the fail fast you're hitting.

To work around the issue you can create a new [triplet](https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md) and build ChakraCore with dynamic library linkage and static CRT linkage.

Just create a new file:

**<vcpkgroot>\triplets\x64-windows-mt**
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

Then install ChakraCore again:
```console
> vcpkg install chakracore:x64-windows-mt
```

And update your documentation to include/link against the new output directory in your vcpkg root:
```console
> dir .\installed\x64-windows-mt\


    Directory: E:\GitHub\vcpkg\installed\x64-windows-mt


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/27/2018   4:56 PM                bin
d-----        9/27/2018   4:56 PM                debug
d-----        9/27/2018   4:56 PM                include
d-----        9/27/2018   4:56 PM                lib
d-----        9/27/2018   4:56 PM                share
d-----        9/27/2018   4:56 PM                tools
```

I tested this out locally and after fixing the build configuration the test app runs successfully.

**Comment by taylorgordon20** [comment]
Thanks for investigating! I'll try with the suggested triplet. :)

**Comment by kfarnung** [comment]
Let us know if you hit any other issues, but I've opened a [PR against vcpkg](https://github.com/Microsoft/vcpkg/pull/4371) to force static linking of the CRT.
