### ISSUE TITLE
error on building on release 1.5

### ISSUE THREAD

**Issue by JiazhengXiong** [Microsoft/ChakraCore#5729]
Here is the error I encountered when I was trying to build release 1.5 on Linux:

/scratch/.../.../.../ChakraCore-1.5.0/lib/Backend/IRBuilderAsmJs.cpp:1158:14: error: comparison of two values with different enumeration types in switch statement ('Js::AsmJsRetType::Which' and 'Js::AsmJsVarType::Which') [-Werror,-Wenum-compare-switch]
        case Js::AsmJsVarType::Which::Int64:
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Any solution for this? Thanks in advance.

**Comment by MSLaguana** [comment]
Why are you trying to compile such an old version of chakracore?

I believe what's happened here is that clang has changed some of their defaults, and so something which previously wasn't an error (perhaps it was a warning) is now treated as an error. You could probably disable that warning with something like `-Wno-enum-compare-switch`, but we don't support older versions of chakracore and there are likely to be security vulnerabilities and other bugs.
