### ISSUE TITLE
Implement export-ns-from syntax.

### ISSUE THREAD

**Issue by jdalton** [Microsoft/ChakraCore#5759]
Now that export-ns-from [has TC39 consensus](https://github.com/tc39/ecma262/pull/1174#issuecomment-425120082) the TC39 is looking for engines to implement.

*Related: [V8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=8101) and [SpiderMonkey issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1496852)*

**Comment by rhuanjl** [comment]
Would a PR to implement this be appreciated?

**Comment by jdalton** [comment]
@rhuanjl Yes, totally!

**Comment by jackhorton** [comment]
cc @boingoing 

I haven't heard anyone say they were picking this up yet internally so it should be good to go.

**Comment by boingoing** [comment]
@rhuanjl We would definitely appreciate a contribution from you on this one and I would be happy to review it and marshal it through the checkin process. 

Just to clarify what exactly this feature is, it's re-exporting a namespace object under an exported name?

**Comment by leobalter** [comment]
> @boingoing: Just to clarify what exactly this feature is, it's re-exporting a namespace object under an exported name?

yes! The syntax production was not possible before:

```js
export * as ns from './module.js';
```

which is _almost_ a sugar for:

```js
import * as ns from './module.js';
export { ns };
```

without necessarily importing a local `ns` binding.

I hope the tests from Test262 might help. @rhuanjl please let me know if you need any help from the tests.

**Comment by rhuanjl** [comment]
Thanks all, I'll aim to do this over this weekend.
