### ISSUE TITLE
Date.parse accepts illegal ISO8601 format

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/ChakraCore#5789]
```js
Date.parse("2018-10-21Z"); // lacks time, it should be 2018-10-21T00:00Z
```

Expected: `NaN`
Actual: `1540080000000`

```js
Date.parse("2018-1-7T00:00Z"); // no padded zero, should be 2018-01-07T00:00Z
```

Expected: `NaN`
Actual: `1515283200000`

**Comment by sethbrenith** [comment]
After a bit of research, I think this behavior is actually for the best. The [spec](https://tc39.github.io/ecma262/#sec-date.parse) says "If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats." Currently V8 accepts `2018-10-21Z` and SpiderMonkey accepts `2018-1-7T00:00Z`, so the best possible behavior for compat is to accept both.
