### ISSUE TITLE
BUG: Dynamic import should return different promise objects, even if the specifier is the same. 

### ISSUE THREAD

**Issue by rwaldron** [Microsoft/ChakraCore#5795]
Test: https://github.com/tc39/test262/blob/master/test/language/expressions/dynamic-import/always-create-new-promise.js

Result: 

> the returned promises are not the same, regardless the reference and specifier pair Expected SameValue(«[object Promise]», «[object Promise]») to be false

**Comment by rhuanjl** [comment]
Hmm currently internally the promise for a dynamic import is a property of the SourceTextModuleRecord object - if you import the same module a second time the SourceTextModuleRecord object from the first import() is retrieved and the promise from it is returned.

This means that when the import() completes it has an easy reference to the promise it needs to resolve, so to fix this would probably have to change this mechanism - perhaps introducing a list of promises.

**Comment by fatcerberus** [comment]
It might not be necessary to keep a list; CC could keep the single internal promise and wire up the ones returned from `import` to it.  This way you resolve the internal one and all the ones attached to it get resolved automatically.

**Comment by rhuanjl** [comment]
I've submitted a fix, this commit https://github.com/Microsoft/ChakraCore/pull/5803/commits/866386bbf9fb7d5f4a14720ba9da16ed5c9083a2 in PR 5803.

It adds the new promises as reactions to the existing promise with an internal equivalent of ```promiseObject.then(a => a, e => throw e);```
