### ISSUE TITLE
BUG: ImportCall is an invalid AssignmentTargetType, should produce an Early ReferenceError

### ISSUE THREAD

**Issue by rwaldron** [microsoft/ChakraCore#5798]
Test: https://github.com/tc39/test262/blob/master/test/language/expressions/dynamic-import/syntax/invalid/invalid-asssignmenttargettype-reference-error-9-lhs-assignment-operator-assignment-expression.js

```js
import('') += 1;
```

Is producing a SyntaxError; however, like: 

```js
(() => 1) += 1;
```

It _should_ produce an Early ReferenceError.

**Comment by rhuanjl** [comment]
I plan on submitting a fix for this shortly, just trying to work out how it can be done neatly, the "obvious" fix would be a bit messy.

**Comment by rhuanjl** [comment]
@infinnie I think the 1=2 case was fixed by this commit https://github.com/Microsoft/ChakraCore/commit/13847da1662c5b603e1ae1f5b1bf978f21ed7b54 I guess that's not made it into the version of Edge you're using yet.

**Comment by rhuanjl** [comment]
I believe that this is no longer an error per normative spec PR: https://github.com/tc39/ecma262/pull/1527

**Comment by rhuanjl** [comment]
Closing per prior comment as spec changed to match existing behaviour.
