### ISSUE TITLE
Implement @@toStringTag in Object.prototype.toString

### ISSUE THREAD

**Issue by boingoing** [Microsoft/ChakraCore#580]
ES Spec  [19.1.3.6 Object.prototype.toString] (https://tc39.github.io/ecma262/#sec-object.prototype.tostring)
```js
var p = new Promise(function () {});
Object.prototype.toString.call(p);
```
Expected: "[object Promise]"
Actual: "[object Object]"

Resolved OS Bug [4646435] (https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=4646435)

**Comment by nicolo-ribaudo** [comment]
I think this has already been fixed:
```js
// demo.js

var p = new Promise(function () {});
print(Object.prototype.toString.call(p));

print(Object.prototype.toString.call({
    [Symbol.toStringTag]: "Custom toStringTag"
}));
```

```
$ Build/VcBuild/bin/x64_debug/ch.exe -ES6ToStringTag demo.js
[object Promise]
[object Custom toStringTag]
```

**Comment by abchatra** [comment]
Yes this is enabled inside -ES6ToStringTag. Though we need to enable this flag by default, which requires additional jit work. We can keep this open till then.

**Comment by tcare** [comment]
Enabled by default in #1383
