### ISSUE TITLE
Crashes on Number.MIN_VALUE.toString(2)

### ISSUE THREAD

**Issue by qntm** [Microsoft/ChakraCore#5809]
In Microsoft Edge 42.17134.1.0 on Windows 10, opening developer tools and running `Number.MIN_VALUE.toString(2)` causes the browser tab to crash and reload. Looks like the same area as #509?

The precise value of `Number.MIN_VALUE` is 2<sup>-1074</sup>, so I believe the correct return value is the 1076-character string:

> 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001

**Comment by fatcerberus** [comment]
I can confirm the crash in Edge on Windows 10 1803.  Doesn't repro in miniSphere, though, so it looks like this is either an Edge bug or else it was already fixed.

On an amusing sidenote, Chrome doesn't handle this well at all:
```
> Number.MIN_VALUE.toString(2)
< "0"
```

**Comment by MikeHolman** [comment]
Looks like this was already fixed. I see the expected string printed on Edge 44.17763.1001.0.
