### ISSUE TITLE
Does ChakraCore contains shell only functions? 

### ISSUE THREAD

**Issue by ZackJohn** [Microsoft/ChakraCore#5811]
Hi,
My boss wants to know how many shell only functions in CharaCore. It's quite difficult to know all
built-in functions and distinguish them which are shell only function. What could I do to find the shell only functions?
Thanks~

**Comment by MSLaguana** [comment]
What do you mean by "shell only" vs "built-in" function? Are you referring to functions defined in the javascript language, or to the native code that implements javascript?

**Comment by ZackJohn** [comment]
> What do you mean by "shell only" vs "built-in" function? Are you referring to functions defined in the javascript language, or to the native code that implements javascript?

Here are “shell only” functions defined in the SpiderMonkey:
[Shell only functions](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Shell_global_objects#Shell_only_functions)

For example, when we write a piece of js code that contains some "shell only" functions, we can only run CharaCore in the command line.
"./ch code_contains_shell_only_function.js"

About built-in functions, I mean functions defined in the javascript language, like "Array.from()".

**Comment by MSLaguana** [comment]
I see. "ChakraCore" does not have any "shell only" functions, but the "ch" executable / shell which is also built from this repository defines several functions, e.g. `WScript.Echo`, which would fit that definition.

If you just consume chakracore.dll then I believe we expose an ECMAScript compliant environment, and you as the host are responsible for providing whatever additional functionality is necessary to interact with the environment.

**Comment by ZackJohn** [comment]
Thank you for your help, I found that all the functions of "WScript" are so-called "shell only". Is that correct?
Besides, is there any other object like "WScript" that contains "shell only" functions?
Thanks again.

**Comment by fatcerberus** [comment]
Okay but the so-called “shell-only” functions are not implemented in ChakraCore at all, they are implemented in the codebase for `ch` itself.  So I don’t see how they’re relevant any more than custom API functions provided by any other host.

**Comment by EdMaurer** [comment]
Hopefully clear now.
