### ISSUE TITLE
Chakra failed when build with permissive- by msvc on Windows

### ISSUE THREAD

**Issue by QuellaZhang** [microsoft/ChakraCore#5813]
Chakra failed with lots of errors when build with permissive- by msvc on Windows, I use latest source version ce09d0e on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**

1. git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\Chakra\src
3. set CL=/permissive- /d1ParseTrees:identErrors-
4. msbuild /m /p:Platform=x86 /p:Configuration=Test /p:WindowsTargetPlatformVersion=10.0.17134.0 Build\Chakra.Core.sln /t:Rebuild

**Failures:**
ByteCodeGenerator.cpp
D:\Chakra\src\lib\Common\DataStructures\DictionaryEntry.h(85,17): error C3861: 'ClearValue': identifier not found
                ClearValue<TValue>::Clear(&this->value);
                ^
D:\Chakra\src\lib\Common\DataStructures\DictionaryEntry.h(91): note: see reference to class template instantiation 'JsUtil::`anonymous-namespace'::ValueEntry<TValue,TData>' being compiled
        };
D:\Chakra\src\lib\Common\DataStructures\DictionaryEntry.h(98,39): error C3861: 'ValueToKey': identifier not found
            TKey Key() const { return ValueToKey<TKey, TValue>::ToKey(this->value); }
                                      ^
D:\Chakra\src\lib\Common\DataStructures\DictionaryEntry.h(104): note: see reference to class template instantiation 'JsUtil::`anonymous-namespace'::ImplicitKeyValueEntry<TKey,TValue>' being compiled
        };
D:\Chakra\src\lib\Common\Memory\SmallHeapBlockAllocator.h(72,51): error C2039: 'IsConcurrentSweepState': is not a member of 'Memory::Recycler'
        return IsFreeListAllocMode() && recycler->IsConcurrentSweepState();
                                                  ^
D:\Chakra\src\lib\Common\Memory\HeapBlock.h(41): note: see declaration of 'Memory::Recycler'
class Recycler;
D:\Chakra\src\lib\Common\Memory\SmallHeapBlockAllocator.h(109): note: see reference to class template instantiation 'Memory::SmallHeapBlockAllocator<TBlockType>' being compiled
};
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(90,33): error C2039: 'CreateWeakReferenceHandle': is not a member of 'Memory::Recycler'
            weakRef = recycler->CreateWeakReferenceHandle((T*)this);
                                ^
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(16): note: see declaration of 'Memory::Recycler'
class Recycler;
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(95): note: see reference to class template instantiation 'Memory::WeakReferenceCache<T>' being compiled
};
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(355,47): error C2039: 'FindHeapBlock': is not a member of 'Memory::Recycler'
        entry->strongRefHeapBlock = recycler->FindHeapBlock(strongReference);
                                              ^
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(16): note: see declaration of 'Memory::Recycler'
class Recycler;
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(377): note: see reference to class template instantiation 'Memory::WeakReferenceHashTable<SizePolicy>' being compiled
};
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(358,50): error C2039: 'FindHeapBlock': is not a member of 'Memory::Recycler'
        HeapBlock * weakRefHeapBlock = recycler->FindHeapBlock(entry);
                                                 ^
D:\Chakra\src\lib\Common\Memory\RecyclerWeakReference.h(16): note: see declaration of 'Memory::Recycler'
class Recycler;
D:\Chakra\src\lib\Common\DataStructures\WeakReferenceDictionary.h(232,20): error C3861: 'values': identifier not found
            return values[i];
                   ^
D:\Chakra\src\lib\Common\DataStructures\WeakReferenceDictionary.h(822): note: see reference to class template instantiation 'JsUtil::SplitWeakDictionary<TEntry,TWeak,keyIsWeak,SizePolicy,Comparer,Lock,AllocType>' being compiled
    };
D:\Chakra\src\lib\Common\DataStructures\WeakReferenceDictionary.h(239,20): error C3861: 'values': identifier not found
            return values[i];
                   ^
D:\Chakra\src\lib\Runtime\Base\PropertyRecord.h(139,18): error C2039: 'GetPropertyRecord': is not a member of 'Js::JavascriptString'
            str->GetPropertyRecord(&propRecord);
                 ^
D:\Chakra\src\lib\Runtime\Runtime.h(144): note: see declaration of 'Js::JavascriptString'
    class JavascriptString;
D:\Chakra\src\lib\Runtime\Base\PropertyRecord.h(161): note: see reference to class template instantiation 'Js::BuiltInPropertyRecord<LEN>' being compiled
    };
D:\Chakra\src\lib\Runtime\Base\PropertyRecord.h(143,36): error C2039: 'GetString': is not a member of 'Js::JavascriptString'
                return Equals(str->GetString(), str->GetLength());
                                   ^
D:\Chakra\src\lib\Runtime\Runtime.h(144): note: see declaration of 'Js::JavascriptString'
    class JavascriptString;
D:\Chakra\src\lib\Runtime\Base\PropertyRecord.h(143,54): error C2039: 'GetLength': is not a member of 'Js::JavascriptString'
                return Equals(str->GetString(), str->GetLength());
                                                     ^
D:\Chakra\src\lib\Runtime\Runtime.h(144): note: see declaration of 'Js::JavascriptString'
    class JavascriptString;
D:\Chakra\src\lib\Runtime\Base\CrossSite.h(29,41): error C3861: 'CrossSiteObject': identifier not found
            BOOL ret = VirtualTableInfo<CrossSiteObject<T>>::HasVirtualTable(obj);
                                        ^
D:\Chakra\src\lib\Runtime\Base\CrossSite.h(29,41): note: This diagnostic occurred in the compiler generated function 'BOOL Js::CrossSite::IsCrossSiteObjectTyped(T *)'
            BOOL ret = VirtualTableInfo<CrossSiteObject<T>>::HasVirtualTable(obj);
                                        ^
D:\Chakra\src\lib\Runtime\Language\InlineCache.h(412,62): error C2039: 'GetLibrary': is not a member of 'Js::ScriptContext'
                *propertyValue = IsMissing ? requestContext->GetLibrary()->GetFalse() : requestContext->GetLibrary()->GetTrue();
                                                             ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Language\InlineCache.h(412,105): error C2039: 'GetLibrary': is not a member of 'Js::ScriptContext'
                *propertyValue = IsMissing ? requestContext->GetLibrary()->GetFalse() : requestContext->GetLibrary()->GetTrue();
                                                                                                        ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Base\FunctionBody.h(3473,20): error C3861: 'GetSlot': identifier not found
                fn(GetSlot[i]);
                   ^
D:\Chakra\src\lib\Runtime\Base\FunctionBody.h(3473,20): note: This diagnostic occurred in the compiler generated function 'void Js::ScopeSlots::Map(Fn)'
                fn(GetSlot[i]);
                   ^
D:\Chakra\src\lib\Runtime\Language\PrototypeChainCache.h(197,28): error C2039: 'InvalidateStoreFieldCaches': is not a member of 'Js::ScriptContext'
            scriptContext->InvalidateStoreFieldCaches(propertyId);
                           ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Language\PrototypeChainCache.h(197,28): note: This diagnostic occurred in the compiler generated function 'bool Js::OnlyWritablePropertyCache::ProcessProperty(Js::DynamicTypeHandler *,Js::PropertyAttributes,KeyType,Js::ScriptContext *)'
            scriptContext->InvalidateStoreFieldCaches(propertyId);
                           ^
D:\Chakra\src\lib\Runtime\Library\StringCache.h(66,28): error C2039: 'FindPropertyRecord': is not a member of 'Js::ScriptContext'
            scriptContext->FindPropertyRecord(value, N - 1, &propertyRecord);
                           ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Library\StringCache.h(66,28): note: This diagnostic occurred in the compiler generated function 'Js::JavascriptString *Js::StringCache::InitializeString(const char16 (&)[N]) const'
            scriptContext->FindPropertyRecord(value, N - 1, &propertyRecord);
                           ^
D:\Chakra\src\lib\Runtime\Library\StringCache.h(69,35): error C2039: 'GetPropertyString': is not a member of 'Js::ScriptContext'
            return scriptContext->GetPropertyString(propertyRecord->GetPropertyId());
                                  ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Library\StringCache.h(69,35): note: This diagnostic occurred in the compiler generated function 'Js::JavascriptString *Js::StringCache::InitializeString(const char16 (&)[N]) const'
            return scriptContext->GetPropertyString(propertyRecord->GetPropertyId());
                                  ^
D:\Chakra\src\lib\Runtime\Library\StringCache.h(73,120): error C2039: 'GetRecycler': is not a member of 'Js::ScriptContext'
            return LiteralString::New(stringTypeStatic, value, N - 1 /*don't include terminating NUL*/, scriptContext->GetRecycler());
                                                                                                                       ^
D:\Chakra\src\lib\Runtime\Runtime.h(210): note: see declaration of 'Js::ScriptContext'
    class ScriptContext;
D:\Chakra\src\lib\Runtime\Library\StringCache.h(73,120): note: This diagnostic occurred in the compiler generated function 'Js::JavascriptString *Js::StringCache::InitializeString(const char16 (&)[N]) const'
            return LiteralString::New(stringTypeStatic, value, N - 1 /*don't include terminating NUL*/, scriptContext->GetRecycler());
                                                                                                                       ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3456,13): error C2065: 'PreVisitCatch': undeclared identifier
            PreVisitCatch(pnodeCatchScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3456,13): error C3861: 'PreVisitCatch': identifier not found
            PreVisitCatch(pnodeCatchScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3456,26): note: 'PreVisitCatch': function declaration must be available as none of the arguments depend on a template parameter
            PreVisitCatch(pnodeCatchScope, byteCodeGenerator);
                         ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3468,13): error C2065: 'PostVisitCatch': undeclared identifier
            PostVisitCatch(pnodeCatchScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3468,13): error C3861: 'PostVisitCatch': identifier not found
            PostVisitCatch(pnodeCatchScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3468,27): note: 'PostVisitCatch': function declaration must be available as none of the arguments depend on a template parameter
            PostVisitCatch(pnodeCatchScope, byteCodeGenerator);
                          ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3476,13): error C2065: 'PreVisitWith': undeclared identifier
            PreVisitWith(pnodeScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3476,13): error C3861: 'PreVisitWith': identifier not found
            PreVisitWith(pnodeScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3476,25): note: 'PreVisitWith': function declaration must be available as none of the arguments depend on a template parameter
            PreVisitWith(pnodeScope, byteCodeGenerator);
                        ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3481,13): error C2065: 'PostVisitWith': undeclared identifier
            PostVisitWith(pnodeScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3481,13): error C3861: 'PostVisitWith': identifier not found
            PostVisitWith(pnodeScope, byteCodeGenerator);
            ^
D:\Chakra\src\lib\Runtime\ByteCode\ByteCodeGenerator.cpp(3481,26): note: 'PostVisitWith': function declaration must be available as none of the arguments depend on a template parameter
            PostVisitWith(pnodeScope, byteCodeGenerator);
                         ^

**Comment by QuellaZhang** [comment]
Hello, any updates?

**Comment by EdMaurer** [comment]
Sorry, but this is unlikely to get attention from the MS Chakra team soon. Everyone is focused elsewhere.

**Comment by dilijev** [comment]
@QuellaZhang we don't support building with `/permissive-` or unreleased toolsets, but we are happy to merge fixes for issues like this if you would like to submit a patch.

**Comment by QuellaZhang** [comment]
Closed.
