### ISSUE TITLE
Service Worker Automatically Skips Waiting

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/ChakraCore#5815]
Hi

Edge version: 42.17134.1.0
Edge HTML: 17.17134

In Edge a newly installed Service Worker is being automatically activated on refresh (ie equivalent to always calling `skipWaiting`).

The following bit of code should alert whenever `serviceworker.js` is modified and the browser is refreshed:
```js
navigator.serviceWorker.ready.then(function (registration) {
      console.log('ready');

      if (registration.waiting) {
           alert('waiting');
       }
});
```

This never alerts in Edge, but does in Chrome and FireFox.

**Comment by liminzhu** [comment]
Hey thanks for the report @NoelAbrahams ! Unfortunately this is a web API issue rather than a JS engine issue. Can you open an issue on [EdgeHTML issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) so the right folks can look at them?

**Comment by NoelAbrahams** [comment]
Moved to [EdgeHTML Issue Tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19608658/) as requested.
