### ISSUE TITLE
Cross OS standard browser shell

### ISSUE THREAD

**Issue by ab35** [Microsoft/ChakraCore#5836]
Hi,

One thinks that OS manufacturers should work on a browser shell standard common to all operating systems, because after all, all browsers do the same thing according to W3C standards.

That way, particular brands of browsers like Edge, Safari, Chrome, etc. would all derive from a common standard browser shell present in all operating systems (by shipping on top of it their own JS runtime, extensions and UI for example, in a decoupled way).

Then, users would just have to choose what browser brand they want to upgrade to/ or there will be one brand by default installed along the shell in the particular OS (for example the Edge brand in Windows OS, or the Chrome brand in Chrome OS).

But the core of the browser would be the same and embedded by default in all OS.

This would allow to reduce the internet bandwidth consumption when acquiring and updating new browsers on an OS, and desktop apps built on top of the web platform like carlo/nw.js/electron/uwp apps wouldn't need to ship with chromium (or other potential browsers) while still being compatible with all browser brands, by the simple fact that they would rely on the underlying common standard browser shell.

**Comment by EdMaurer** [comment]
Not a ChakraCore-specific topic.
