### ISSUE TITLE
`JavascriptOperators::IsIterable` can lead to script code getting executed twice instead of once

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#584]
`JavascriptOperators::IsIterable` calls `JavascriptOperators::GetProperty` when the object in question is a `JavascriptProxy`.  This will lead to code execution in the case that the property is a getter or the proxy has a `get` trap handler installed.

The use of `IsIterable` appears to be to check whether or not to go down the slow iterable iteration code paths rather than fast paths.  These code paths however will then again do a `GetProperty` on the property, which in the proxy case would call that getter or trap handler again.

IsIterable should be removed and uses of it fixed to follow the correct spec semantics.

**Comment by suwc** [comment]
Is this a 1.2 issue? Would be great to have some 2nd opinions.
@abchatra @bterlson ?

**Comment by abchatra** [comment]
What is the test case for this?

**Comment by suwc** [comment]
We don't have a real-world test case right now.
The idea is to make a getter function that has side effect and use it to override [Symbol.iterator] of an object, then use the object (possibly through a proxy) to construct a TypedArray.

**Comment by ianwjhalliday** [comment]
This has an easy repro.  This bug affects any clients of `JavascriptOperators::IsIterable` which fortunately is few for now, including `JavascriptArray::EntryFrom`, `TypedArrayBase::EntryFrom`, and `TypedArrayBase::CreateNewInstance`.

Here is an example repro using `Array.from()`

```javascript
let iterable = {
    count: 0,
    [Symbol.iterator]() {
        print("iterable[Symbol.iterator]() called: " + this.count);
        return {
            i: 0,
            a: [ 'a', 'b', 'c', 'd', 'e' ],
            next() {
                return {
                    value: this.a[this.i],
                    done: this.i++ >= this.a.length
                };
            }
        };
    }
};

let handler = {
    count: 0,
    get(target, propKey, receiver) {
        if (propKey === Symbol.iterator) {
            print("get trap propKey=Symbol.iterator called: " + ++this.count);
        }
        return target[propKey];
    }
}

let p = new Proxy(iterable, handler);
let a = Array.from(p);
print(a.join(''));
```

Running this with `ch.exe` prints the following output

```
get trap propKey=Symbol.iterator called: 1
get trap propKey=Symbol.iterator called: 2
iterable[Symbol.iterator]() called: 0
abcde
```

Notice that the trap handler is called twice but `iterable[Symbol.iterator]()` is only invoked once.

The spec is written such that the trap handler should only be called once, as well as `iterable[Symbol.iterator]()` being called only once.

**Comment by ianwjhalliday** [comment]
Leaving `JavascriptOperators::IsIterable` in our code base would let to this bug multiplying as the API gets used elsewhere when we implement more features in the future that might make use of it.

I recommend we change the API to `JavascriptOperators::GetIteratorFromIterable` so that it can make the query and return the iterator so that the property `get` on `Symbol.iterator` is only performed once as the spec dictates.

**Comment by suwc** [comment]
Another repro:
`function getIterator (array)
{
    return  ()=> {
            return {
                next: () => {
                    return {
                        value: array.shift(),
                        done: array.length == 0
                    };
                }
            };
        }
}

function getcobj () {
    var count = 99;
    return {
       get [Symbol.iterator] () { return getIterator([count--,0]); }
    }
}

var d = getcobj();

var b = new Int8Array(d);
print(b);
b = new Int8Array(d);
print(b);
`
Output:
`98
96`

**Comment by suwc** [comment]
Talked to Brian, and he is most interested in the following test case:

```javascript
var obj = {
  get [Symbol.iterator]() { print("Got!"); return getIterator([1,2]); }
}
for(p of obj) {}
```
Output
`Got!`

The test case behaves correctly.
So I would recommend not making this 1.2 but otherwise fix it ASAP before this issue becomes more widespread.

**Comment by ianwjhalliday** [comment]
Sounds good to me

**Comment by tcare** [comment]
Same issue in: OS: Bug 5204357: ES6 Spread over zealous optimization for Arrays ignores user changes to %ArrayIteratorPrototype%.next property
