### ISSUE TITLE
Intl.NumberFormat breaks with currency and more than 2 fraction digits

### ISSUE THREAD

**Issue by bashmish** [Microsoft/ChakraCore#5842]
## Expected Behavior

```
new Intl.NumberFormat('en-GB', {
  style: 'currency',
  currency: 'EUR',
  currencyDisplay: 'code',
  minimumFractionDigits: 3,
  maximumFractionDigits: 3,
}).format(0.001)
```

Result in Edge 17 (and other browsers): "EUR 0.001"

## Current Behavior

Result  in Edge 18 / Insiders Preview: "EUR0.00"

## Context (Environment)

According to one of many user reports:
Microsoft Edge 44.17763.1.0 and Microsoft Edge HTML 18.17763
Windows 10 Home Version 1809 4-10-2018

My own investigation:
Edge Insiders Preview on BrowserStack (should be close to Edge 18)

## Additional Notes

I could not get Edge 18 here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Some of my colleague could not get it installed/updated on Windows 10, it remains Edge 17 even now.
This brings me to some other questions:
Is Edge 18 stable?
Has it been released?
Did you stop rolling it out to users via Windows Update?

**Comment by liminzhu** [comment]
Can confirm the behavior in Microsoft EdgeHTML 18.17763. @LouisLaf can we get someone to look at the bug? 

@bashmish none of us here are in charging of rolling out Windows/Edge updates, but let me ask around to see if I can get some answers for you.

**Comment by LouisLaf** [comment]
Yes I do repro this.  minimumFractionDigits and maximumFractionDigits seem to be ignored completely...

**Comment by kypflug** [comment]
@bashmish @liminzhu To the question about the Edge 18 update - We temporarily suspended the rollout last month and resumed it on 11/13. However, the rollout is initially throttled based on the device profile to make sure everyone has a good update experience. You can learn more here: https://blogs.windows.com/windowsexperience/2018/11/13/resuming-the-rollout-of-the-windows-10-october-2018-update/.

We don't yet have VMs available but those should be coming soon.

**Comment by wyrichte** [comment]
This is not a Chakra bug but rather an ICU bug. It will be fixed in an upcoming version of Windows. Thanks for the report!

**Comment by torsten-knauf** [comment]
Got Microsoft EdgeHTML 18.17763 today and it is still broken. Could you maybe write here, when it is supposed to be fixxed?

One of our tests fails (correctly) in saucelabs on latest Edge due to this bug. So I will sadly set lattest Edge version to 17 in saucelabs and would be happy about a notification, when it is fixxed... :)
