### ISSUE TITLE
Edge show fraction digits even if i don't want it

### ISSUE THREAD

**Issue by Davilink** [Microsoft/ChakraCore#5845]
```js
new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD', useGrouping: true, minimumIntegerDigits: 1, minimumFractionDigits: 0, maximumFractionDigits: 0})
```

Result in IE (11):
![image](https://user-images.githubusercontent.com/1498932/48961030-88173300-ef3f-11e8-8d40-d35b62a682fe.png)

Result in Edge (18):
![image](https://user-images.githubusercontent.com/1498932/48961024-7cc40780-ef3f-11e8-99fe-b3c24d14e39a.png)

Result in Chrome (70):
![image](https://user-images.githubusercontent.com/1498932/48961117-299e8480-ef40-11e8-887c-cb3804e8c8a1.png)

Result in Firefox (nightly 65):
![image](https://user-images.githubusercontent.com/1498932/48961005-65851a00-ef3f-11e8-975a-eb45d0060b6c.png)

**Comment by liminzhu** [comment]
@Davilink thanks for reporting the bug! This is potentially related to https://github.com/Microsoft/ChakraCore/issues/5842 as min/maximumFractionDigits are ignored. So + @wyrichte .

**Comment by jefgen** [comment]
Note: It looks like the variable `culture` is not defined in the snippet you posted. Perhaps there was a line omitted?

**Comment by Davilink** [comment]
@jefgen
culture = 'fr-CA'

**Comment by jefgen** [comment]
Thanks!
So the snippet should probably look something like this:
`new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD', useGrouping: true, minimumIntegerDigits: 1, minimumFractionDigits: 0, maximumFractionDigits: 0}).format(25000);`

**Comment by wyrichte** [comment]
This bug is similar to #5842. This is not a Chakra bug but rather an ICU bug. It will be fixed in an upcoming version of Windows. Thanks for the report!

**Comment by mitkoevoets** [comment]
:'( microsoft
