### ISSUE TITLE
Add PR welcoming badge

### ISSUE THREAD

**Issue by open-source-explorer** [Microsoft/ChakraCore#5846]
It would be a good idea to add pr welcoming badge within the `README` file which is a common practice nowadays.
Thoughts 🤔

**Comment by liminzhu** [comment]
I'm personally indifferent. I don't see it in VSCode or TypeScript repo. Not that it matters, just a data point.

**Comment by open-source-explorer** [comment]
@liminzhu @dilijev Are we going forward with this?

**Comment by Ankk98** [comment]
![screenshot from 2018-12-03 18-42-27](https://user-images.githubusercontent.com/24476799/49375766-641bd480-f72b-11e8-8a06-e2cf444c9538.png)
@dilijev 
A good example is React, it has 117k stars.
