### ISSUE TITLE
Edge download .csv file as .xls (adds xls extension) 

### ISSUE THREAD

**Issue by gkhub** [Microsoft/ChakraCore#5850]
Customer using Azure blob store storage complained about csv file upload/download in edge. 
Repro:
Upload a csv file to blob store.
Download the file.
Other browsers correctly downloads csv file.
Edge adds .xls extension and unable to open the file. 

Found the issue mentioned public forum as well - https://answers.microsoft.com/en-us/edge/forum/edge_extension-edge_win10/edge-browser-changes-file-extension-while-saving/8f32e8a8-1f3a-4fad-a640-788e77f7425e

**Comment by liminzhu** [comment]
hey @gkhub . This isn't part of the ChakraCore implementation but rather something provided in the hosting browser Edge. Would you open a bug on the [Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)?

**Comment by liminzhu** [comment]
I'm going to close this one since it's unrelated to ChakraCore. Feel free to re-open if you have anything we can help with.
