### ISSUE TITLE
[Question] Future of ChakraCore?

### ISSUE THREAD

**Issue by wohali** [Microsoft/ChakraCore#5857]
Apologies for the bare-faced question here.

Over at [Apache CouchDB](https://github.com/apache/couchdb), we're prototyping replacements for our aging and rickety SpiderMonkey 1.8.5 JS engine. Based on the good work done by the Microsoft team on ChakraCore, and knowing it's embedded in products like CosmosDB, we felt this would be a good way forward for our team.

By now I'm sure you've [read the rumors](https://www.windowscentral.com/microsoft-building-chromium-powered-web-browser-windows-10), or the layoffs of some of our (mutual!) friends just a few months ago who worked on Edge. They tell us they are bound by NDAs over their dismissals, but now with the WindowsCentral article, we feel the writing is on the wall. [**ETA**: the announcement [is now official](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/).]

In the interest of ensuring we don't unnecessarily bind ourselves to a dying project, should we [continue our work to bind Erlang to ChakraCore](https://github.com/cloudant-labs/erlang-chakracore) without fear? Or would it be best for us to start over with V8 at this point?

We know that you're probably not able to say anything, either, but the question bears asking. Ideally, a statement from someone in leadership that ChakraCore isn't also on the chopping block would go some way to assuring us we've made a good decision. ~~We recognize that you'd have to acknowledge the other rumour first, though.~~

Once again, thanks to the entire ChakraCore team for building an engine that embeds easily and has the features we need. :crossed_fingers: We very much appreciate your work!

**Comment by rhuanjl** [comment]
(NOTE whilst I'm a contributor to chakracore I'm not from Microsoft and I have no inside info - I'm a hobbyist open source contributor)

So it's now not just a rumour - Edge is due to ditch EdgeHTML for chromium next year:
https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/#86hdHmPeOj1Xq32Q.97

I'd love to see chakracore continue to be maintained; IMO it is the all around best JS engine for embedding - primarily because of its simple, stable, well documented C API which IMO for an embedder is more important than getting the latest features quickly - but my opinion is unfortunately of little value.

**Comment by wohali** [comment]
Just wanted to say that: if you are unable to make a public statment, you can contact us directly at private@couchdb.apache.org .

**Comment by Fly-Style** [comment]
https://twitter.com/bterlson/status/1070754781822574592

**ChakraCore development continues for various non-Edge uses.**

Don't worry, be happy :)

**Comment by saschanaz** [comment]
Is there a project that heavily uses ChakraCore than Edge does? If not, I think ChakraCore will also be eventually doomed...

**Comment by wonkyweasel** [comment]
@saschanaz  There is node-chakra which is alive for now: https://twitter.com/AruneshC/status/1070813703656751104
don't know of any others. Many companies where one team uses another teams code will setup internal billing for services provided. Chakra likely lost its main customer. For it to continue something else has to fill in the funding gap. Further there are not that many experienced compiler developers out there. I would expect Microsoft to start reallocating resources to v8 at the detriment of chakra b\c thats the future for them.
Windows 10 has a different support cadence than previous versions of Windows, so funding might run out when security patches  are no longer needed. That time period being whenever the chromium switch happens. There are still patches for ie 11 though that come out so their will probably be a small support team at a minimum to support IE on older versions of windows. That probably means patches for chakra (jscript9.dll) will continue at least until  January 14, 2020 when windows 7 is EOF.

**Comment by liminzhu** [comment]
Thank you for your well-written message and understanding of our situation @wohali ! We don't like leaving our friends in the dark, but the announcement yesterday has such a broad impact that we've got some guidance to stage and just wait a day to let the dust settle first. 

To answer your and many others' questions, we have a short statement that will hopefully drive some clarity. If anyone has more questions for us, feel free to post on that issue as well.

**Comment by wohali** [comment]
Thanks for the update, @liminzhu . The only thing that we ask is that, should V8 start displacing ChakraCore in those other applications within MS, the community be given some sort of heads up so we have time to transition too.

It would be absolutely horrible if MS internally moved every application off of ChakraCore onto V8 secretly, *then* announced that ChakraCore was EOL. With no required long-term maintenance strategy on your service-based offerings, since they'd all already be upgraded behind-the-scenes, you could conceivably stop all work on ChakraCore the day you announce it to the public.

Please keep this in mind as you move forwards. Thanks.
