### ISSUE TITLE
JsCreateNamedFunction toString result is wrong

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#586]
JsCreateNamedFunction sets "functionNameId" as name. That is wrong in current code. Elsewhere we typically call 

```
if (scriptContext->GetConfig()->IsES6FunctionNameEnabled())
{
    object->SetPropertyWithAttributes(PropertyIds::name, functionName,
                                      PropertyConfigurable, nullptr);
}
```

"functionNameId" is used as toString result cache. Setting "functionNameId" to a string incorrectly makes the runtime use that string as toString result. We get `custom_name` instead of `function custom_name() { [native code] }`.

**Comment by farzonl** [comment]
JC do you have a test case for this bug? I just tried out:
var a =[];
a.indexOf.name;
print(a.indexOf.toString());
but this prints: function indexOf() { [native code] }

**Comment by jianchun** [comment]
@farzonl This issue only applies to native named functions created through JSRT ```JsCreateNamedFunction```. Repro needs native code.
