### ISSUE TITLE
TypeError.prototype.toString === Error.prototype.toString

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#588]
Firefox/Chrome:

```
TypeError.prototype.toString === Error.prototype.toString
true
```

Edge: `false`

A small compatibility issue. Don't know if affects anything.

**Comment by tcare** [comment]
It looks like there is inconsistency everywhere:
`
$ eshost -ts -e "TypeError.prototype.toString === Error.prototype.toString"
┌─────────┬───────┐                                                        
│ sm      │ true  │                                                        
│ node    │       │                                                        
├─────────┼───────┤                                                        
│ node-ch │ false │                                                        
│ jsc     │       │                                                        
└─────────┴───────┘                                                        
                                                                           
$ eshost -ts -e "TypeError.prototype.hasOwnProperty('toString')"           
┌─────────┬───────┐                                                        
│ jsc     │ true  │                                                        
│ node-ch │       │                                                        
│ node    │       │                                                        
├─────────┼───────┤                                                        
│ sm      │ false │                                                        
└─────────┴───────┘                                                        
 `

Brian is going to investigate. This is low pri, moving to vNext.

**Comment by EdMaurer** [comment]
Low impact, so closing.
