### ISSUE TITLE
instanceof with bound function should call [Symbol.hasInstance]

### ISSUE THREAD

**Issue by fasttime** [microsoft/ChakraCore#5883]
When the right hand side of an `instanceof` expression is a bound function, then a `[Symbol.hasInstance]` property set on the original function doesn't seem to be looked up as expected.

This is the test code I'm running:

```js
class A {
    static [Symbol.hasInstance]() {
        console.log(this.name);
    }
}

const B = A.bind();

({} instanceof B);
```

Here the last line should call `[Symbol.hasInstance]` on type A and print "A", but it doesn't.

Apparently, the issue is specific to ChakraCore since other engines behave as expected.

**Comment by fatcerberus** [comment]
Relevant specification text:
https://www.ecma-international.org/ecma-262/9.0/index.html#sec-ordinaryhasinstance

The correct behavior is indeed as described in the OP (contrary to my expectations).  ChakraCore is in the wrong here; the other engines are correct.

**Comment by liminzhu** [comment]
Yeah I can confirm we have a different behavior. We should look into it. @LouisLaf
