### ISSUE TITLE
Error.stack undefined when Error.stackTraceLimit == 0

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#589]
Small compatibility issue.

```
Error.stackTraceLimit = 0
new Error('abc').stack
```

Chrome: ```"Error: abc"```
Edge: ```undefined```

**Comment by Yongqu** [comment]
what's FF's behavior?

**Comment by jianchun** [comment]
> what's FF's behavior?

FF doesn't seem to support this. This is a Chrome/V8 API.
