### ISSUE TITLE
ChakraCore crashes in lib/Parser/Parse.cpp

### ISSUE THREAD

**Issue by leeswimming** [Microsoft/ChakraCore#5891]
Release build of ChakraCore crashes due to the null dereferencing after the commit 34b8876ec.
The input JavaScript is as follows.
```
({a: b => []} = [2]);
```

$ file ch
ch: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

Build Option: None
OS: Ubuntu 18.04.1 LTS
Arch: x86_64

**Comment by akroshg** [comment]
changes merged in.
