### ISSUE TITLE
Handling out of memory error

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Microsoft/ChakraCore#5892]
Is it possible to handle the "Out of memory" error gracefully without having the process killed immediately? For example, when running out of stack space the "Out of stack space" exception is thrown, but it looks like when running out of memory the process crashes immediately.

Is this expected? Can anything be done to have ChakraCore throw an exception that the host can handle?

I'm testing this by setting JsSetRuntimeMemoryLimit to a low value and running a script like this:
```
function main() {
    var a = [];

    a['1000000000'] = 1;

    var s = a.toString();
}

```

**Comment by rhuanjl** [comment]
Assuming you're embedding chakracore yourself there is a way it\s not documented in the wiki (not sure why) but you can use `JsRuntimeAttributeDisableFatalOnOOM` as one of the attributes when creating your runtime CC will then attempt to raise a JS exception for out of memory instead of crashing.

**Comment by dennis-yemelyanov** [comment]
Great, thank you, exactly what I need :)
