### ISSUE TITLE
[Discussion] Branch-specific Jenkins test configurations

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#590]
@mmitche and I have recently made some changes to the Jenkins CI configuration to enable alternate test configurations for different branches. This should help ease the transition when CI-breaking changes are made to one branch that don't yet affect other branches. Also, it will allow e.g. the `linux` branch to define CI builds on Linux which wouldn't otherwise apply to a branch like `master` which doesn't have the necessary changes.

Branch owners: @digitalinfinity @jianchun @MikeHolman @Cellule - could you weigh in on any specific test needs you might have for your branches? We can work together to get those set up soon.

P.S. @mmitche and I are aware that the recent changes stopped CI from working on non-master branches. I'm going to make some changes to unblock the branches' CI (edit: see #596). Then, we'll figure out the correct way to configure branches so that the same default checks will work on every branch in the absence of specific needs being specified.

**Comment by Cellule** [comment]
At this time the WebAssembly branch has the same needs as the master branch

**Comment by dilijev** [comment]
@Cellule Thanks! Noted.
