### ISSUE TITLE
ChakraCore 1.11.5 download broken on jsvu due to uppercase checksum

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/ChakraCore#5902]
[jsvu](https://github.com/GoogleChromeLabs/jsvu) downloads ChakraCore from GitHub releases and uses the checksum embedded in the tag to verify the download. It appears they're expecting the checksum string to be lowercase `a-f` in their regex: https://github.com/GoogleChromeLabs/jsvu/blob/5da9253b29b813f1799368432cd4dfee2f3c46f7/engines/chakra/get-checksums.js#L21

The latest 1.11.5 release however used uppercase chars in the checksum: https://github.com/Microsoft/ChakraCore/releases/tag/v1.11.5

~~@rajatd would it be possible to modify the strings to be lowercase?~~ Not needed anymore now that jsvu put in a workaround.

**Comment by mathiasbynens** [comment]
jsvu@1.3.2 works around this by also accepting uppercase hex digits.

**Comment by liminzhu** [comment]
Seems like this is resolved. Will close for now but feel free to re-open if you have any follow-up @akoeplinger.
