### ISSUE TITLE
Can't build on Visual Studio 2017 Community with Visual C++ 2017

### ISSUE THREAD

**Issue by davewthompson** [Microsoft/ChakraCore#5904]
Fresh clone of https://github.com/Microsoft/ChakraCore.git.
Using Visual Studio 2017 Community with Visual C++ on Windows 10 Pro x64 (1809)
Open project
Set target to x64
138 build errors ("unknown attribute 'guard'", etc). Entire output attached.

[build log errors.txt](https://github.com/Microsoft/ChakraCore/files/2743070/build.log.errors.txt)

**Comment by liminzhu** [comment]
Can't reporoduce with VS 2017 Community but on Win10 17763. Anyone know more about this?

**Comment by fatcerberus** [comment]
I’ve built successfully with VS2017 Community on 1809.  Only thing I can think of is there’s a misconfiguration somewhere on OP’s system.

**Comment by LouisLaf** [comment]
The compiler is complaining about __declspec(guard(overflow)).  It doesn't look like your build is using the right toolset.
