### ISSUE TITLE
Is there a way to stop a js script from crashing the application?

### ISSUE THREAD

**Issue by gh-markt** [microsoft/ChakraCore#5921]
Given the extremely simple (albeit contrived) script: 

`var arr=[];for(var i=0;i<1000000000;i++) arr.push(i);`

This will apparently crash the process that is executing it.  I did not see any obvious way in the API to prevent this, however.  Am I overlooking something, is this a shortcoming in the current API, or is this actually intended?

**Comment by fatcerberus** [comment]
This crashes because it runs out of memory.  You can disable abort-on-OoM but there’s no guarantee you will be able to recover cleanly once you’ve exhausted the available RAM, so the default behavior is just to induce a crash to avoid unforeseen security issues.

The flag in question is `JsRuntimeAttributeDisableFatalOnOOM`.

See also #4597.

**Comment by gh-markt** [comment]
Excellent.  Thank you, I did not see that option... would it be safe, then, if this situation were encountered, to simply dispose of the runtime, and for a user of the API to start over with a completely new runtime instance if any further js is needed later?

**Comment by fatcerberus** [comment]
It’s difficult to say... ChakraCore would try to recover by throwing an OOM error, but there’d still be that huge array in memory taking up space until the garbage collector could get around to freeing it.  *Any* attempts to allocate memory at this point are likely to fail, so you would have to be very careful to avoid creating an unrecovable situation yourself.  For example, disposing of a runtime will invoke finalizers so you’d have to take that into account.

**Comment by fatcerberus** [comment]
@gh-markt Just found out there’s a function you can use (in combination with the above mentioned flag), `JsSetRuntimeMemoryLimit`, to cause the OOM error to be thrown before you actually run out of physical RAM and therefore make it possible to recover.

https://docs.microsoft.com/en-us/microsoft-edge/hosting/chakra-hosting/jssetruntimememorylimit-function

**Comment by MikeHolman** [comment]
We have these flags, but beware if you are trying to continue execution of script after an OOM error. It's possible that you end up with objects that are only partially initialized, and trying to use them will cause strange behavior/crashes.

**Comment by fatcerberus** [comment]
What @MikeHolman said, though `JsSetRuntimeMemoryLimit` would presumably help with that, since then it would fail before a physical OOM and the runtime shouldn’t be left in a bad state then (?).

**Comment by MikeHolman** [comment]
It would help, and OOM along most codepaths doesn't cause problems, but there are some cases where we set fields on an object, and then we try to allocate memory to set more related fields on the object. OOMs there will lead to objects in inconsistent state.

These cases are rare (I don't know any offhand), but there are some corner cases where it can cause issues. These cases probably won't hit in practice, but it's risky if you are running untrusted scripts.
