### ISSUE TITLE
Release notes for ChakraCore 1.11.6 don't contain binaries, breaking jsvu

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/ChakraCore#5945]
[jsvu](https://github.com/GoogleChromeLabs/jsvu) relies on the binaries being mentioned in the release notes with the specific format, the latest 1.11.6 doesn't have them at all.

Compare 1.11.6: https://github.com/Microsoft/ChakraCore/releases/tag/v1.11.6
To 1.11.5: https://github.com/Microsoft/ChakraCore/releases/tag/v1.11.5

/cc @liminzhu @MikeHolman

**Comment by MikeHolman** [comment]
Binaries are coming, but there are infra issues with publishing right now. I should have them up by tomorrow at the latest (and will update release notes accordingly).

**Comment by akoeplinger** [comment]
@MikeHolman thanks! next time can you please make sure the binaries are ready before publishing the release tag? jsvu automatically picked this up and is broken right now on our CI.

Even better would be some permalink that allows getting the latest version so jsvu can stop grepping through the GitHub releases page.

**Comment by mathiasbynens** [comment]
https://github.com/GoogleChromeLabs/jsvu/issues/54#issuecomment-452746283

> Even better would be some permalink that allows getting the latest version so jsvu can stop grepping through the GitHub releases page.

Strong +1 on this. For V8, this is how we do it:

```
https://storage.googleapis.com/chromium-v8/official/canary/v8-linux64-rel-latest.json
```

(There’s a different JSON file for each architecture that we support, as binaries of different versions might be available for each of them at various points in time.)

Your JSON file could have `version` _and_ `sha256` fields. Generating it could be completely automated and made part of the release process. It could be part of the repo itself if that makes it easier.

**Comment by liminzhu** [comment]
We do have https://aka.ms/chakracore/version and we use this in a [script](https://aka.ms/chakracore/install) to install latest build. Not sure why this is at 1.11.1 though...Probably need some care.

**Comment by MikeHolman** [comment]
I don't think anyone doing servicing knew about the version link. I updated it to 1.11.5 (and will update again to 1.11.6 once all binaries come out).

**Comment by mathiasbynens** [comment]
If anyone can confirm <https://aka.ms/chakracore/version> will be kept up-to-date with future releases (ideally automated as part of release process), I'd be happy to update jsvu accordingly. Please let me know!

**Comment by liminzhu** [comment]
@mathiasbynens I just updated our internal document for release process to include this link so it should be kept up-to-date.

**Comment by akoeplinger** [comment]
@liminzhu it looks like the `_s` file with the checksum needs to be updated too, it's used by the script you mentioned.

Working: https://aka.ms/chakracore/cc_linux_x64_1_11_5_s
Missing: https://aka.ms/chakracore/cc_linux_x64_1_11_6_s

**Comment by liminzhu** [comment]
@MikeHolman can you talk a look?

**Comment by MikeHolman** [comment]
I removed the checksum file requirement from the script, since it doesn't seem to provide any real benefit.

**Comment by akoeplinger** [comment]
Ok thanks, jsvu did the same. Closing :)
