### ISSUE TITLE
Wasm should raises a CompileError due 31+ offset

### ISSUE THREAD

**Issue by igor-simoes** [microsoft/ChakraCore#5968]
Hi everyone,
running this test case, it was observed that Chakra didn't raised a WASM.CompileError due 31 offset.

Charka: 1.11.6.0
OS: Linux Mint 19

```js
function module(bytes) {
  let buffer = new ArrayBuffer(bytes.length);
  let view = new Uint8Array(buffer);
  for (let i = 0; i < bytes.length; ++i) {
    view[i] = bytes.charCodeAt(i);
  }
  return new WebAssembly.Module(buffer);
}

function assert_invalid(bytes) {
  try { module(bytes) } catch (e) {
    if (e instanceof WebAssembly.CompileError) return;
  }
  throw new Error("Wasm validation failure expected");
}

assert_invalid("\x00\x61\x73\x6d\x01\x00\x00\x00\x01\x05\x01\x60\x00\x01\x7f\x03\x02\x01\x00\x0a\x0f\x01\x0d\x00\x02\x7f\x02\x40\x00\x0d\x01\x0b\x41\x01\x0b\x0b");

```

Actual results:
pass without failures

Expected results:
Error: Wasm validation failure expected

V8 and SpiderMonkey works as expected.

cinfuzz

**Comment by MikeHolman** [comment]
This is not a bug. To improve startup performance, we defer validation until execution time, which is explicitly allowed by spec. If you pass `-off:wasmdeferred`, you can see that we throw a validation error.
