### ISSUE TITLE
Wrong Realization of Reflect.ownKeys

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5988]
Hello， 
I run following code in ch 1.11.6.0, the result is wrong. TypeError should be thrown when returns  duplicate entries.

```
var proxy = new Proxy({}, {
  ownKeys: function(target) {
    print("in ownKeys");
    return ['a','b','a']; 
  },
});
print(Reflect.ownKeys(proxy));
print("BT_FLAG");
```

SpiderMonkey and V8 throw a TypeError: 'ownKeys' on proxy: trap returned duplicate entries, However, ChakraCore and JavascriptCore execute without failures.

BT group
2019.3.5

**Comment by zenparsing** [comment]
Fixed by @akroshg in 0728265d1d
