### ISSUE TITLE
Remove oldest ES6 feature switches

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#6]
Here's my reasoning:
- switches were provided for allowing disabling unstable features for engineering infrastructure and RI
- **old features are now stable and any bugs in them are not going to cause us to disable the feature**
- I cannot think of any reason else why we would want to disable a given feature
- oldest switches do not necessarily even work anymore due to future changes requiring the older changes
  - e.g. let/const changed how we defer parse in a way that other features have taken a dependency on
- old unused switches are thus now useless visual cruft

Switches that I believe are reasonable to remove with no risk at this time:
- __proto__
- Map
- Set
- WeakMap
- ES6WeakSet
- DefineGetterSetter
- LetConst
- ES6Lambda
- ES6Math
- ES6Object
- ES6Number
- ES6String

Switches that I think are reasonable to remove but there might still be low risk in the feature having bugs or causing issues:
- ES6Iterators
- ES6NumericLiterals
- ES6Promise
- ES6StringTemplate
- ES6Symbol
- ES6Unscopables

**Comment by ianwjhalliday** [comment]
In PR #86 I have removed the commits that removed `-ES6Object -ES6String -ES6Promise -ES6Unscopables`.  @abchatra noted that these switches control built-in APIs that are often polyfilled, and being able to turn these built-ins off have proved useful in the past for website bug reduction (i.e. to quickly identify issues due to new built-ins being present).

Those commits did remove some reasonable checks however so i am keeping them around and will revisit later.  I am thinking it would be nice to consolidate the built-in APIs control under one switch and removes checks for other runtime changes.

**Comment by ianwjhalliday** [comment]
I also added new commits that remove `-ES6Classes -ES6ObjectLiterals -ES6Generators -ES6Rest -ES6Spread`

**Comment by ianwjhalliday** [comment]
In the near future we can expect to be able to remove or consolidate `-ES6Species -ES6DefaultArgs -ES6Destructuring -ES6ForLoopSemantics`.

`-ES6FunctionName -ES6FunctionNameFull -ES6Proxy` we should keep for now.

**Comment by ianwjhalliday** [comment]
Removed the commits that removed `-ES6Classes -ES6ObjectLiterals -ES6Generators -ES6Rest -ES6Spread`. @abchatra feels it is too early to remove control over these newer features.

Added commit removing `-TDZ`.

**Comment by dilijev** [comment]
This suggestion is something we will gradually make progress on regardless of whether there is an open issue and will never be, in spirit, "done" because there will always been more feature flags. Therefore, I'm closing this issue. /cc @kfarnung @agarwal-sandeep
