### ISSUE TITLE
How to disable CFG in win10

### ISSUE THREAD

**Issue by xuechiyaobai** [Microsoft/ChakraCore#6021]
Recently you add some new code here:https://github.com/Microsoft/ChakraCore/commit/c0c3de7acdc167ca93b689f7552a5a0fe4bc8be2#diff-368bbd31c6049b4faa033bbbc971ef0f

But there are some old win10 versions that does not support cfg(my test enviroment is 10.0.14393).
And when I build ch.exe, there is a fatal error that "no such file cfguard.h" ...etc

**Comment by liminzhu** [comment]
@LouisLaf

**Comment by rwaldron** [comment]
Hi! Just want to to add to the report that [eshost builds are failing on appveyor](https://ci.appveyor.com/project/bterlson/eshost/builds/23047497/job/4n6ans1iu09fc2es) with the same error message.

**Comment by LouisLaf** [comment]
Yes, it looks like the VS 2015 builds are broken.  CFGuard.h was added in VS 2017.  I'll look into it.

**Comment by LouisLaf** [comment]
VS2015 Update #3 should build fine now.
