### ISSUE TITLE
A branch in WebAssembly code is miscompiled

### ISSUE THREAD

**Issue by zeux** [microsoft/ChakraCore#6022]
I've hit a bug in Edge with WebAssembly; the following code snippet:

```
static void writeTriangle(void* destination, size_t offset, size_t index_size, unsigned int a, unsigned int b, unsigned int c)
{
	if (index_size == 2)
	{
		static_cast<unsigned short*>(destination)[offset + 0] = (unsigned short)(a);
		static_cast<unsigned short*>(destination)[offset + 1] = (unsigned short)(b);
		static_cast<unsigned short*>(destination)[offset + 2] = (unsigned short)(c);
	}
	else
	{
		static_cast<unsigned int*>(destination)[offset + 0] = a;
		static_cast<unsigned int*>(destination)[offset + 1] = b;
		static_cast<unsigned int*>(destination)[offset + 2] = c;
	}
}
```

When compiled with Emscripten to WebAssembly, works correctly in Chrome and Firefox, but doesn't work correctly in Edge - when `index_size` is 4, the code seems to still take the `if` branch instead of `else` branch (or something along these lines - I am not able to debug the resulting native code). Adding a check for `index_size == 4` to the `else` branch works around the issue.

Apologies for a somewhat high level bug report, I'm not quite sure how to reproduce this on a smaller example... The WebAssembly file in question is pretty small though.

This commit applies the workaround:
https://github.com/zeux/meshoptimizer/commit/a9d60cffcdd8bbbf0d2137861af61c620637221e

The easiest way to reproduce is to check out the parent of this commit, replace `demo/pirate.optmesh` with https://github.com/zeux/nyra/blob/master/nyra.optmesh, and open `demo/index.html` in Edge - due to CORS this needs a local web server, Python http.server will do. The mesh will be mangled due to incorrect index decoding:

![image](https://user-images.githubusercontent.com/1106629/54257992-74a7cc00-451e-11e9-9c5c-244215ea95f4.png)

Chrome and Firefox display the mesh properly:

![image](https://user-images.githubusercontent.com/1106629/54258015-838e7e80-451e-11e9-84da-e8c6e55a2910.png)

Attached is a ,zip file with raw .wasm files before (bad) and after (good) the workaround as well as their (wasm) disassembly.

[meshoptimizer.zip](https://github.com/Microsoft/ChakraCore/files/2960037/meshoptimizer.zip)

**Comment by zeux** [comment]
Sorry, forgot to mention - this is in Edge from Windows 10 1809 (build 17763.316). The app reports the following versions:

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by binji** [comment]
I took a look a the `_meshopt_decodeIndexBuffer` functions in both `decoder-bad.wasm` and `decoder-good.wasm`, and generated a CFG for each. The main thing that jumps out is that the one in `decoder-good.wasm` ends up using a lot of `br_table` instructions where the one in `decoder-bad.wasm` only uses `if`. Not sure if this gives any clues. In any case, here are the SVG files for the CFG, hope they can be of help!

[meshoptimizer-svg.zip](https://github.com/Microsoft/ChakraCore/files/2969060/meshoptimizer-svg.zip)

**Comment by zeux** [comment]
This is still reproducible using Edge from Windows 10 1903; Edge versions:

Microsoft Edge 44.18362.329.0
Microsoft EdgeHTML 18.18362

This problem doesn't seem to manifest when the C code is built using Emscripten's new upstream backend, presumably the CFG is different somehow.

To make this easier to reproduce, I've packaged all dependent files into a .zip file
[edge-repro.zip](https://github.com/microsoft/ChakraCore/files/3614689/edge-repro.zip)

This is using the wasm code that triggers the codegen bug in Edge:
![image](https://user-images.githubusercontent.com/1106629/64933657-0577a100-d7fb-11e9-99af-4e59eefd032a.png)

This is how it should look like (screenshot from Chrome):
![image](https://user-images.githubusercontent.com/1106629/64933678-16c0ad80-d7fb-11e9-919a-a749607f6df3.png)

Note that changing index.html to load `new_decoder.js` results in correct rendering in Edge; new_decoder.js uses Emscripten's upstream backend without the workaround.

**Comment by zeux** [comment]
Since it’s been almost a year, new Edge is going to use v8 which doesn’t have this bug, and this doesn’t reproduce with new Emscripten backend, I am going to close this as I don’t expect it to be fixed.
