### ISSUE TITLE
Edge throws an unexpected TypeError: Object expected

### ISSUE THREAD

**Issue by aidandownes** [microsoft/ChakraCore#6046]
Repro steps:
1. Go to https://console.cloud.google.com (requires a Google account)
1. Open the hamburger menu and click on the "Storage" navigation menu link 
    (bug occurs in minified Angular routing code)

Notes:
* Was unable to isolate the root cause so I don't have a minimum repro example 
* Bug occurs in minified Angular routing code. Specifically 
  https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L315
  which is inlined here:
  https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L257.
  This is minified to
   ```
   t = {};
   p = r == p.path && Jia(t, p.parameters);
   ```
   When the bug occurs, it looks like ```r == p.path``` executes then the assignment and then 
   ```Jia(t, p.parameters)```.  ```p.paramters``` will be undefined leading to the exception. 
* Bug occurs on 
  * Microsoft Edge 41.16299.1004.0
  * Microsoft EdgeHTML 16.16299
  * Windows 10 Enterprise, Version 1709, 16299.1029
  * Bug also occurs on IE11

**Comment by aidandownes** [comment]
Unable to repro the bug with EdgeHTML 17.

**Comment by boingoing** [comment]
Sounds like this was fixed. Closing old issues.
