### ISSUE TITLE
Null pointer dereference in ValueType::FromObject(Js::RecyclableObject*) ()

### ISSUE THREAD

**Issue by zhiyi01** [microsoft/ChakraCore#6058]
the following js fragment causes a null pointer dereference.

```javascript
function foo() {
    try {
        x = arguments;
        this = foo.call(this);
    } catch (e) {
        print(x.length);
    } 
    var x = {
        j: 1,
        k: 2.2
    };
}
foo();
```

Version: [ Release v1.11.7 ](https://github.com/Microsoft/ChakraCore/commit/86df3a4a1add9a5b104f553e65ac5c1d24b0bf2f)
OS: Ubuntu 16.04.1 LTS
Arch: x86_64

**Comment by MikeHolman** [comment]
Repros more consistently with `-bgjit- -mic:1`
