### ISSUE TITLE
TypedArray constructor optimizes construction from array when %ArrayIteratorPrototype%.next is no longer the built-in

### ISSUE THREAD

**Issue by ianwjhalliday** [Microsoft/ChakraCore#608]
Thanks to @evilpie for catching this looking at PR #561 

```javascript
var iter = [][Symbol.iterator]()
iter.__proto__.next = function() {
    return {done: true};
};

var i32a = new Int32Array([1, 2, 3]);

for (let i = 0; i < i32a.length; i += 1) {
    print(i32a[i]);
}
```

Currently prints 1, 2, 3, but should print nothing.  The Int32Array should be created empty because the array iterator's next() method is now supposed to always return {done: true} on first call.

The optimization legality check @suwc added in #561 needs to be fixed up to include verifying that the %ArrayIteratorPrototype%.next slot is still equal to the built-in method.

**Comment by suwc** [comment]
https://github.com/Microsoft/ChakraCore/pull/635

**Comment by suwc** [comment]
Merged
