### ISSUE TITLE
Microsoft Edge switch to chromium, now chakracore will discontinued?

### ISSUE THREAD

**Issue by netroby** [Microsoft/ChakraCore#6090]
Microsoft Edge switch to chromium, now chakracore will discontinued?

**Comment by sr229** [comment]
I don't think so, ChakraCore has still has more advantages compared to V8, so I'm sure Edge Chromium will use ChakraCore in place of V8

**Comment by DickvdBrink** [comment]
There is already a discussion here about this: https://github.com/Microsoft/ChakraCore/issues/5865
