### ISSUE TITLE
Provide JavaScript debugging support (API) in ChakraCore

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/ChakraCore#61]
ChakraCore should provide APIs to debug JavaScript

**Comment by dilijev** [comment]
See [JsRTDebugging branch](https://github.com/Microsoft/ChakraCore/tree/JsRTDebugging) for the work in progress.

**Comment by agarwal-sandeep** [comment]
Closing as debugging APIs are now in master
