### ISSUE TITLE
[Test] [Daily] [DisableJIT] test\Bugs\bug934443.js failing after commit 353e7d9 with AV (c0000005)

### ISSUE THREAD

**Issue by aneeshdk** [Microsoft/ChakraCore#610]
test\Bugs\bug934443.js failing after commit 353e7d9 with AV (c0000005)

To repro, build the binary with
`jenkins\buildone.cmd x64 debug "/p:BuildJIT=false"`

Failing test is:
`Build\VcBuild.NoJIT\bin\x64_debug\ch.exe  -DumpOnCrash  -WERExceptionSupport -ExtendedErrorStackForTestHost -nonative  -force:fieldcopyprop -off:dynamicprofile test\Bugs\bug934443.js`

**Comment by dilijev** [comment]
@abchatra Do you think this should be tagged as [Bug] and/or Milestone 1.2?
