### ISSUE TITLE
Edge "inspect elements" not working

### ISSUE THREAD

**Issue by cbdeveloper** [Microsoft/ChakraCore#6110]
I'm not really sure if this is the place to share this. If there is a more appropriate, please let me know. Sorry in advance.

I've been working as a web developer for over a year now. Yesterday was my first time inspecting elements on Edge. And it was just terrible. I will add a GIF below to illustrate the situation. The element is a div with contenteditable. This was on my localhost. PS: I'm having normal development experience on Firefox and Chrome at the same time.

What could be happening?

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Running Windows 10

![EdgeInspectElement](https://user-images.githubusercontent.com/43407798/56574638-aa2ee300-65bb-11e9-99d7-129125b18018.gif)

**Comment by zenparsing** [comment]
Hi @cbdeveloper, for EdgeHTML DevTools you can create an issue [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/), or leave feedback using the "smiley-face" feedback icon in the DevTools header.

Also, keep in mind that Edge is moving to a new chromium-based engine which you can preview [here](https://www.microsoftedgeinsider.com/en-us/).
