### ISSUE TITLE
assertion failure at linearscan.cpp, line 1559, Failure: (funcBailOutData[index].localOffsets[i] == 0)

### ISSUE THREAD

**Issue by akayn** [microsoft/ChakraCore#6113]
hi, the following test case asserts at:
linearscan.cpp, line 1559, Failure: (funcBailOutData[index].localOffsets[i] == 0)
(run the debug build):

function opt() {

  for (let i = 0; i < 9; i++) {

    for (let j = 0; j < 100; j++) {

        function opt2() {

            let a1 = [12.34];
            let a2 = [-3333333333,"symbol",parseFloat];
            let a3 = Object != Math;

            function opt3(a,b,c,d,e) {

                let arr = [d];
                let arg = arguments[9];

            }

            opt3(333333333,a3,0,a1,a2);

        }
        opt2();
    }
  }
}

for (let t = 0; t < 100; t++){
    opt();
}

platform:windows
version: the master branch compiled at: 13/4/2019

**Comment by akayn** [comment]
i have tested 6129, so i took a look on this one as well,
and you can close this too

**Comment by akayn** [comment]
ho.. sorry, just tested on windows and this is still relevant as well,
only on windows and only the debug build..

**Comment by LouisLaf** [comment]
This was fixed by #6109
