### ISSUE TITLE
Exception# Invalid character

### ISSUE THREAD

**Issue by rktuxyn** [microsoft/ChakraCore#6120]
I don't know what's the problem with this <code>`</code> character in #Chakra JavaScript engine. I'm unable to render my script into <b>Internet Explorer 11</b>.

If anyone explain me this problem, I would be graceful.

Here is the browser information below:
<b>Internet Explorer 11</b>
<b>Version:</b> 11.0.9600.17278
<b>Update Version:</b> 11.0.12 (KB2977629)
<b>navigator.userAgent:</b> Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.2; rv:11.0) like Gecko

Please look the following attachment:
1#
![Prob_1](https://user-images.githubusercontent.com/34983736/57407694-9b743d00-7205-11e9-894a-523ad4b6fd1e.jpg)

2#
![Prob_2](https://user-images.githubusercontent.com/34983736/57407925-2f460900-7206-11e9-8f2f-27fc84ed0ca8.jpg)

**Comment by MikeHolman** [comment]
Strings denoted by backticks are a newish language feature (template literals), which IE does not support. IE is no longer being updated (except for security fixes). If you want to support IE you will need to change to use a normal string literal (i.e. denoted with either single or double quotes) or use a library to polyfill them.
