### ISSUE TITLE
Have someway of waiting to attach debugger to ch.exe when starting up as an option

### ISSUE THREAD

**Issue by nojvek** [Microsoft/ChakraCore#614]
I'm currently adding a 10 second sleep in ch.cpp

```
int _cdecl wmain(int argc, __in_ecount(argc) LPWSTR argv[])
{
    if (argc < 2)
    {
        PrintUsage();
        return EXIT_FAILURE;
    }

    // Use Ctrl+Alt+P to attach debugger
    Sleep(10 * 1000);
```

Not the most efficient method but it does the trick.

**Comment by dilijev** [comment]
I think this doesn't directly answer your request, but you could build with VS and launch the process for debugging (you'll have to configure the debugging parameters in the project settings).

Is your scenario not covered by that kind of debugging from VS?

For non-VS processes, if you use windbg, you can also run the process under the debugger and it will launch immediately into the debugger. You'll need the symbols from a build though.

**Comment by ianwjhalliday** [comment]
Yes, you can you start ch.exe under the debugger in either VS or WinDBG.  If you're using a different debugger you'll have to look it up but it should also be able to do this.

In VS set ch project as start up project.  To change the command line arguments right click the project, go to the properties dialog, go to the `Debugging` section.  Make sure `Local Windows Debugger` is selected in the drop down near the top and then change the `Command Arguments` and `Working Directory` entries to suit your needs.

**Comment by ianwjhalliday** [comment]
Then F5 or F11 to start the process.

**Comment by ianwjhalliday** [comment]
@nojvek were you able to get this working?

**Comment by nojvek** [comment]
Yeah I was. Feel free to close this. Thanks.
