### ISSUE TITLE
Reading cssText off of a @keyframes cssRule errors with a "Member not found" message

### ISSUE THREAD

**Issue by zbs** [microsoft/ChakraCore#6165]
For example, in the following snippet:

```
<style>
  #foo {
    unsupportedPropertyName: 100%; /* works */
  }
  
  @keyframes foo {
    100% {
      height: 100%; /* works */
    }
  }
  @keyframes bar {
    100% {
      unsupportedPropertyName: 100%; /* doesn't work */
    }
  }
</style>
<script>
  var cssRules = document.styleSheets[0].cssRules;
  alert(cssRules[0].cssText);
  alert(cssRules[1].cssText);
  alert(cssRules[2].cssText);
</script>
```

The third logging command will error.

**Comment by MikeHolman** [comment]
This is not a ChakraCore bug.

You can file Edge issues here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by zbs** [comment]
It's a javascript issue, and the only category for that in the Edge issue tracker is "JavaScript Language / Chakra".

![Screenshot from 2019-06-17 14-22-09](https://user-images.githubusercontent.com/1444551/59627036-521fe300-910b-11e9-9928-a1bdac408392.png)

**Comment by zenparsing** [comment]
@zbs Try using the HTML/DOM category; this appears to be an issue with the DOM element properties.

**Comment by zbs** [comment]
Thanks. FYI, created a new issue here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/22216399/
