### ISSUE TITLE
Update https://aka.ms/chakracore/version per v1.11.10 release

### ISSUE THREAD

**Issue by mathiasbynens** [microsoft/ChakraCore#6175]
Per https://github.com/microsoft/ChakraCore/releases/tag/v1.11.10, v1.11.10 has been released. However, https://aka.ms/chakracore/version still returns `1_11_9`.

Please update this resource accordingly (ideally automated as part of the release process), since tools such as jsvu depend on this.

@zenparsing

jsvu issue: https://github.com/GoogleChromeLabs/jsvu/issues/71

**Comment by mathiasbynens** [comment]
cc @pleath

**Comment by pleath** [comment]
Thanks.
