### ISSUE TITLE
Discuss JsRTDebugging APIs

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/ChakraCore#619]
I have implemented significant part of new APIs to debug ChakraCore and flushed most of bugs using debugger implemented in ch.

Before opening the PR request for merging code from JsRTDebugging to master it will be good to discuss the APIs name, signature and arguments. 

Please take a look at https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h and provide any feedback you have.

**Comment by agarwal-sandeep** [comment]
@akroshg @liminzhu @yongqu please provide your feedback

**Comment by dilijev** [comment]
@agarwal-sandeep Did you mean the contents here? https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h

**Comment by agarwal-sandeep** [comment]
Yes, thanks. Fixed

**Comment by akroshg** [comment]
@agarwal-sandeep how do I resume as continue?

**Comment by agarwal-sandeep** [comment]
Execution resumes after call to JsDiagDebugEventCallback return. Host needs to call JsDiagSetStepType before returning from callback.

**Comment by akroshg** [comment]
line 47/51 change 'Indicates break ' to 'Indicates a break'

**Comment by akroshg** [comment]
>> JsDiagDebugEventCallback 
Please embed the description about that.

**Comment by akroshg** [comment]
line 86 : please reword the description : eg. Request the runtime to break on next javascript statement.

**Comment by akroshg** [comment]
line 98 : what do you mean by 'active' breakpoints ?

**Comment by akroshg** [comment]
line 100, change breakPoints to breakpoints.

**Comment by akroshg** [comment]
line 128 : the structure of the breakpoint is different from defined at line 104. that is not intentional, right?

**Comment by akroshg** [comment]
line 274 : do you get handle as well?

**Comment by akroshg** [comment]
line 282 : Shouldn't this be called JsDiagGetScript ?

**Comment by akroshg** [comment]
line 309 : change func to function

**Comment by akroshg** [comment]
line 296 : why do you need filename when we have scriptId ?

**Comment by akroshg** [comment]
line 299 : change the names -> firstStatementLine/Column.
Also this is relative to the current function or absolute ? as the line is 1 above but the stmtStartLine is 0.

**Comment by akroshg** [comment]
Overall it would be best if every function should have remark that mentions that it can be called in debug mode, break mode or neutral. for example setbreakpoint can be called both on debug mode and break mode.

**Comment by dilijev** [comment]
You'll want to make the Copyright adhere to our copyright header format.
https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L1

**Comment by dilijev** [comment]
I think the enum types should be grouped at the top of the file to make for easier browsing.

**Comment by akroshg** [comment]
line 320 : why we have to pass this many information at top level ? why not
{ index,
functionObject,
handle }
functionObject should have all the information about the scriptID and filename and other things.

**Comment by akroshg** [comment]
line 469 : Evaluate an expression. ?

**Comment by dilijev** [comment]
The doc comments at the top of https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h mirror those at the top of https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraCore.h -- was that intentional? I don't know how the docs are generated but which file will actually get that content, or will both files get associated documentation with that same content?

**Comment by Yongqu** [comment]
JsDiagStartDebugging: when and how will the developer free the callbackState?

**Comment by dilijev** [comment]
This line is very long. Break into multiple lines?
https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L66

**Comment by dilijev** [comment]
General nitpick: between declarations there are currently either one or two blank lines but it's not clear what the meaning of the extra spacing is. I'd prefer reducing it to just single line breaks between declarations.

**Comment by dilijev** [comment]
Nitpick: why is the entire body of the file indented even though there is no block declaration?

**Comment by dilijev** [comment]
Remove the blank line between description and declaration here to be consistent with the rest. https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L233

**Comment by dilijev** [comment]
Nit: this one is using 2 spaces per indent, inconsistent with the rest.
https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L307

**Comment by dilijev** [comment]
Nit: for the rest of the declarations you add an extra indent after the open paren on the previous line but this one does not.
https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L80

**Comment by Yongqu** [comment]
JsDiagSetBreakpoint return JsValueRef, but JsDiagRemoveBreakpoint takes an unsigned int.

**Comment by Yongqu** [comment]
JsDiagBreakOnExceptionType: should the value be enum (incremental) or bitmask?

**Comment by Yongqu** [comment]
JsDiagSetBreakOnException etc. : should we take a runtime parameter, or it requires activecontext that is currently in debug state?

**Comment by akroshg** [comment]
line 416 : propertyAttributes, can we define an enum for more descriptive usage?

**Comment by akroshg** [comment]
line 410 : totalPropertiesOfObject - what is the use case here?

**Comment by akroshg** [comment]
line 435 and 463 - the GetProperties and GetObjectFromHandle require rephrase. say GetProperties returns children of an handle?

**Comment by akroshg** [comment]
Are we considering JsDiagStopDebugging as well? Say I am creating my own debugger using these jsrt APIs how do I disconnect the debugger?

**Comment by jianchun** [comment]
Browsing the header and feel seeing too many "Diag". Existing APIs are all under the same "Js" family. Is it needed to start a new "JsDiag" family of APIs? What if remove "Diag" from the names?

**Comment by agarwal-sandeep** [comment]
Its a way of grouping all diagnostics API under one name (probably in future we will have more profiling and other diag APIs), if we decide its not good I can remove it.

**Comment by dilijev** [comment]
The `JsDiag` prefix makes sense to me.

**Comment by dilijev** [comment]
Unrelated to this specific request but I noticed this line is also super long: https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraCommon.h#L2334

**Comment by dilijev** [comment]
Even though https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraCore.h has 

```
#include "ChakraCommon.h"
#include "ChakraDebug.h"
```

So that the `ChakraCommon.h` dependencies are included before `ChakraDebug.h`, I think it is still a good idea to capture the dependency of `ChakraDebug.h` on `ChakraCommon.h` by adding

```
#include "ChakraCommon.h"
```

at the top of `ChakraDebug.h`.

**Comment by dilijev** [comment]
#625 mentioned this:

https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/lib/Jsrt/ChakraDebug.h#L121
change "but" -> "put"

**Comment by agarwal-sandeep** [comment]
Debugging APIs are now in master, closing this.

**Comment by zgsxtyzgd** [comment]
call JsDiagSetStepType.JsDiagStepTypeStepIn after,How to Run to the next statement?  @agarwal-sandeep

**Comment by zgsxtyzgd** [comment]
请问 在 JsDiagDebugEventCallback 中调用   JsDiagSetStepType.JsDiagStepTypeStepIn  后如何进入到下一条语句  打扰 @Yongqu

**Comment by agarwal-sandeep** [comment]
@zgsxtyzgd JsDiagStepTypeStepOver performs a single step over after a debug break if the next statement is a function call, else behaves as a step to next statement. Once a break event is notified (like JsDiagDebugEventBreakpoint or JsDiagDebugEventDebuggerStatement) call JsDiagSetStepType(JsDiagStepTypeStepOver) to set the internal state in ChakraCore to perform a step operation after JsDiagDebugEventCallback returns.
