### ISSUE TITLE
ChakraCore static library

### ISSUE THREAD

**Issue by pblackbird** [microsoft/ChakraCore#6209]
Hello friends! I want to embed ChakraCore into my project.
But it's undesirable to use chakra's dll. Can I build chakra as static library(or libraries) without dll?

P.S. Chakra is better than v8, thank you Microsoft!

**Comment by fatcerberus** [comment]
There is no (supported) way to build a static library on Windows, as far as I know.  Linux and macOS yes, but not Windows sadly. ☹️

**Comment by rhuanjl** [comment]
While it is not officially supported a windows static library of chakracore could likely be built with ~1 hour of fiddling see prior discussion here: https://github.com/microsoft/ChakraCore/issues/279
