### ISSUE TITLE
Nondeterministic JavaScript bug in latest version of Microsoft Edge

### ISSUE THREAD

**Issue by jaredkrinke** [microsoft/ChakraCore#6252]
The latest version of Edge appears to have a nondeterministic branching bug.

**Background**
I have a single-page JavaScript app that works in Chrome and used to work in Edge (was working for me in July), but it is now hitting an apparent timing bug in the latest version of Edge. I'm on this version of Edge:

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Bug**
I've isolated the problem down to some simple (and expected-to-be-deterministic) string-parsing code. Basically, the code (see gist linked below) parses a line of comma-separated values, allowing values to be enclosed in quotation marks (e.g. so the values can be strings that include commas).

Now, the code itself isn't super important. What's important is that the code should produce the same result every time it runs. However, if I run this code on the exact same input in a loop, sometimes a branch will be unexpectedly taken (!!!), resulting in incorrect parsing, thus breaking my app. Note that if I turn on F12 developer tools and put a breakpoint on the unexpected branch, the issue _does not_ occur (i.e. the debugger seems to change the timing/prevent the bug from manifesting).

I have only observed this bug on Edge and I suspect it only affects the latest version of Edge (since I never hit this bug until recently and I use Edge for development). I can reproduce the bug on multiple machines (all on the latest revision of Windows 10).

**Repro**
Here is a gist that reproduces the bug (on the latest Edge only, of course):
https://gist.github.com/jaredkrinke/a1a219ed1466423e927504297d27819e

The HTML page contains all of the code. Reload the page several times and you should hit the bug (it should say "Failed after X iterations" on Edge, but it always says "Successful after 1000 iterations" on other browsers--i.e. the bug only impacts Edge).

**Comment by jaredkrinke** [comment]
I can reproduce this issue with Chakra's ch.exe tool. The issue does not appear to affect Chakra 1.8.5, but it does affect 1.10.0 (and also the latest release, 1.11.12).

I used the x64 ch.exe release binary from this NuGet feed:
https://www.nuget.org/packages/Microsoft.ChakraCore.vc140

Here is a Chakra-only/command line version of my original code (run it on release 1.11.12 a few times and you should see the unexpectedly inconsistent results):
https://gist.github.com/jaredkrinke/7d80bd75cf6e8bd822f7d2be2484d56d

Copy-paste from my console session (showing success on 1.8.5 and inconsistent results on 1.10.0 and 1.11.12):

> C:\Users\jared\Desktop\chakra\1.8.5>ch.exe ..\repro.js
> Succeeded after 1000 iterations
> 
> C:\Users\jared\Desktop\chakra\1.8.5>ch.exe ..\repro.js
> Succeeded after 1000 iterations
> 
> C:\Users\jared\Desktop\chakra\1.8.5>ch.exe ..\repro.js
> Succeeded after 1000 iterations
> 
> C:\Users\jared\Desktop\chakra\1.8.5>cd ..\1.10.0
> 
> C:\Users\jared\Desktop\chakra\1.10.0>ch.exe ..\repro.js
> Failed after 488 iterations
> 
> C:\Users\jared\Desktop\chakra\1.10.0>ch.exe ..\repro.js
> Failed after 187 iterations
> 
> C:\Users\jared\Desktop\chakra\1.10.0>ch.exe ..\repro.js
> Failed after 183 iterations
> 
> C:\Users\jared\Desktop\chakra\1.10.0>cd ..\1.11.12
> 
> C:\Users\jared\Desktop\chakra\1.11.12>ch.exe ..\repro.js
> Failed after 164 iterations
> 
> C:\Users\jared\Desktop\chakra\1.11.12>ch.exe ..\repro.js
> Failed after 179 iterations
> 
> C:\Users\jared\Desktop\chakra\1.11.12>ch.exe ..\repro.js
> Failed after 158 iterations

**Comment by rhuanjl** [comment]
I tried using git bisect to investigate this. The error appears to have been introduced by this optimisation: https://github.com/microsoft/ChakraCore/pull/4995/commits/856dfbf35709a6d7f8d413547dbfcd615a66caca

Additionally it can be made consistent occurring always on the 2nd iteration in ch by running with -mic:1 and -off:simplejit i.e. this error reliably occurs whenever this code is run with the fulljit.

**Comment by zenparsing** [comment]
Thanks @rhuanjl for tracking down the commit. I can also confirm that the bug does not repro with the flag `-off:AVTInPrePass`.
