### ISSUE TITLE
using `await` throws incorrect error

### ISSUE THREAD

**Issue by soundlake** [microsoft/ChakraCore#6255]
### version info
- Microsoft Edge 44.18963.1000.0
- Microsoft EdgeHTML 18.18963

### problem

In the console, if I use `await` the console generate error `Expected ';'` and refuses to run the line.

### how to re-produce

In the console.

```js
var f = async () => { setTimeout(() => { console.log('foo'); }, 1000); };
await f();  // generates "Expected ';'" error message
```

**Comment by rhuanjl** [comment]
Await is only valid inside an async function so this should error is correct. Though it’s not the most helpful error message.

**Comment by soundlake** [comment]
@rhuanjl I've never cared about it! Thx!
