### ISSUE TITLE
JsParseSerialized Argument Documentation Disagreement

### ISSUE THREAD

**Issue by jcdickinson** [Microsoft/ChakraCore#6256]
The [documentation indicates](https://github.com/microsoft/ChakraCore/blob/c0ae3d327654e4390d9c250eb62cc81b6c47492e/lib/Jsrt/ChakraCore.h#L772) that `scriptLoadCallback` is optional (set to null if not required) for `JsParseSerialized`. This parameter is [actually checked against null](https://github.com/microsoft/ChakraCore/blob/833c7f5b862f6b56386ecff6278db64d0cdc451e/lib/Jsrt/Jsrt.cpp#L3978) and `ErrorNullArgument` is returned if it is.

Is the documentation or the code incorrect? I'm happy to fix either.

**Comment by fatcerberus** [comment]
The SAL annotation for this parameter is `_In_`, not `_In_opt_`; compilers that check these annotations will therefore warn on a null argument.  The documentation definitely appears to be incorrect.
