### ISSUE TITLE
Implement Top-Level Await (Stage 3 proposal)

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/ChakraCore#6262]
Consider implementing top-level await, stage 3: https://github.com/tc39/proposal-top-level-await

I had misgivings about this, but it seems to have picked up traction recently and is already stage 3 so I doubt it's going anywhere, regardless of what I think of it. 😛

**Comment by rhuanjl** [comment]
I’ve been thinking about doing this for a while; but it would be a little messy and would likely involve internally treating any module containing Top Level Await as an asynchronous generator function.

Considering that my Async Geberator function implementation is still not enabled by default that could be problematic.

**Comment by fatcerberus** [comment]
Note that top-level `await` blocks execution of dependent module(s), unlike an async IIFE.  Seems like that might make things tricky, too.

**Comment by rhuanjl** [comment]
I'll be happy to do this once #6312 has landed will be fairly simple.

**Comment by zenparsing** [comment]
@rhuanjl That will be awesome! I'll try to get #6312 merged over the next week.

**Comment by rhuanjl** [comment]
Further to my comment above I have now written an implementation of this, but it still needs some testing before it's ready to merge and it is based on top of #6312 so I cannot open a PR with it until that is merged.

**Comment by fatcerberus** [comment]
The fact that `WScript.LoadScriptFile()` doesn't return a promise complicates this IMO.  I would expect the dynamic `import()` to still reject its promise (as this is well-defined by spec), but what should happen for the `LoadScriptFile` call is less clear and strikes me as a host-specific question.

**Comment by rhuanjl** [comment]
Implementation I've done is here https://github.com/rhuanjl/ChakraCore/tree/TopLevelAwait for anyone interested. I can't open a PR yet due to waiting on 6312 as mentioned above AND needing to set up some tests for it as well.
