### ISSUE TITLE
The `JsModuleEvaluation` method always returns a result equal to `undefined`

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ChakraCore#6266]
I am working on implementing support of the ECMAScript 2015 static modules in a .NET library ([JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) project). I've already read the [API documentation](https://github.com/microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Reference) and [“Steps needed for es6 modules embedding ChakraCore”](https://github.com/Microsoft/ChakraCore/issues/4324) discussion.

But I have not found anywhere information about how to get the result of module evaluation. Suppose there is the following code of root module:

```js
import * as geometry from './geometry/geometry.js';
new geometry.Square(15).area;
```
The expected result of evaluating this module is a numerical value equal to `225`, but the [`JsModuleEvaluation`](https://github.com/microsoft/ChakraCore/wiki/JsModuleEvaluation) method always returns `undefined`.

To make it easier for you to find the reason for this behavior, I created a [.NET Core console application](https://github.com/Taritsyn/TestChakraCoreEsModules).

**Comment by rhuanjl** [comment]
I've done a bit of digging - the ability to get a result value via JsModuleEvaluation appears to be an untested feature (nothing in the test suite looks at it) that either never worked or if it did work it was broken a while ago.

As far as I can see it is not currently possible to retrieve a value from a module unless it's exported. 

Currently in the release branches the result from JsModuleEvaluation will always be `undefined` in the master branch it will always be `{done : true}` neither is useful.

**Comment by Taritsyn** [comment]
Hello, Richard!

Thanks for quick response!

> Currently in the release branches the result from JsModuleEvaluation will always be `undefined` in the master branch it will always be `{done : true}` neither is useful.

I do not know how standard this behavior is, but in the [Microsoft ClearScript](https://github.com/microsoft/ClearScript) during evaluation of the [similar code](https://github.com/microsoft/ClearScript/blob/3f4e25e75c8d0564bea1484d0eb18134763aba09/ClearScriptTest/V8ModuleTest.cs#L69-L77) returns a numerical value.

> I've done a bit of digging - the ability to get a result value via JsModuleEvaluation appears to be an untested feature (nothing in the test suite looks at it) that either never worked or if it did work it was broken a while ago.

Here I would like to receive a comment from @liminzhu.

**Comment by fatcerberus** [comment]
IIRC, as written in the ECMAScript specification, the module evaluation algorithm canonically returns a normal completion of `undefined`, so ChakraCore’s result here is correct.

The only thing you’re meant to be able to extract from a successfully evaluated ES module is its module namespace object (i.e. its export table).

**Comment by rhuanjl** [comment]
@fatcerberus if that's the case I should fix master to return `undefined` again - as there's no test of this return value I hadn't noticed that my work in #6171 changed it until this issue prompted me to look.

However the documentation of JsModuleEvaluation implies that it perhaps provides some kind of useful value - which it obviously doesn't.
