### ISSUE TITLE
I hope to add a JsDisposeContext API . 

### ISSUE THREAD

**Issue by elppas** [microsoft/ChakraCore#6291]
hi, thank you for sharing . 
I have  two questions :
1、I hope to add a JsDisposeContext API , it 's important just like JsDisposeRuntime .

2、report a error , that is a error of division by zero , js syntax doesn't display error , and result is zero .

**Comment by rhuanjl** [comment]
1. A JsContext is meant to be garbage collected when it's both:
a)  no longer in use and
b) no longer referenced on the stack

Assuming that that is working correctly a JsDisposeContext API should be unnecessary

2. With dividing by 0 I see any number / 0 = Infinity, 0 /0 = NaN both of these are correct. Do you have a specific example to show the error you've found?

**Comment by elppas** [comment]
![error](https://user-images.githubusercontent.com/25838091/65478470-6cace980-debc-11e9-86fc-1b0bfdce7f39.png)
ss command is based  on chakracore.dll to execute js code , and right side is result。another question ，when execute new Date().toLocaleString() , there are some unintelligible codes in result .

**Comment by fatcerberus** [comment]
The context is implemented as a GC object internally.  It has to go through the garbage collection machinery to be freed, so the only thing such a function could reasonably be is a refcount decrement on the context—which doesn’t guarantee it’s freed immediately, if something else holds a reference to it directly or indirectly.

I don’t think contexts are fully isolated from each other in the same way runtimes are, so there are probably a lot of ways such a reference could be held.  If you free the context prematurely in that case, you could cause a segfault.

**Comment by rhuanjl** [comment]
Explicitly disposing of a context rather than waiting for GC would be somewhat complex to implement and I can't see a clear benefit.
