### ISSUE TITLE
Is the Wiki outdated?

### ISSUE THREAD

**Issue by amn** [microsoft/ChakraCore#6321]
The Wiki says JsCreateRuntime takes 4 arguments: https://github.com/microsoft/ChakraCore/wiki/JsCreateRuntime

This seems to apply to the frozen IE11 JSRT mode. The edge-mode version of the function takes 3 arguments, why doesn't the Wiki reflect that at all?

**Comment by fatcerberus** [comment]
```c
STDAPI_(JsErrorCode)  /* calling convention + return type */
    JsCreateRuntime(  /* function name */
    _In_ JsRuntimeAttributes attributes,  /* arg 1 */
    _In_opt_ JsThreadServiceCallback threadService,  /* arg 2 */
    _Out_ JsRuntimeHandle *runtime);  /* arg 3 */
```

I count 3 arguments.

**Comment by amn** [comment]
True, I was blind. Apologies. In my defense, having two disparate documentation repositories -- one on the Wiki and another at Microsoft Docs is confusing, to put it mildly.
