### ISSUE TITLE
Incorrect realization of RegExp.prototype.source

### ISSUE THREAD

**Issue by YuanWangC** [microsoft/ChakraCore#6342]
When using `Object.getOwnPropertyDescriptor` to get the descriptor of `regex.source` and `regex.__proto__.source`, I find the property is not defined in RegExp.prototype. According to ES6 and ES10, this property belongs to RegExp.prototype. And the property has been changed into accessor property since ES6. Maybe this is an issue of Chakra.
#### version
[eaaf7ac](https://github.com/microsoft/ChakraCore/commit/eaaf7ac6beca01ab0d80c05959f3868463043c2d)
#### run step
`ChakraCore/out/Release/ch testcase.js`
#### testcase
```
var NISLFuzzingFunc = function(){
    var regex = /nisl/ig;
    print(regex.source);
    var des1 = Object.getOwnPropertyDescriptor(regex,"source");
    var des2 = Object.getOwnPropertyDescriptor(regex.__proto__ , "source");
    print(des1);
    print(des2);
    for(var i in des1){
        print (i + " " + des1[i]);
    }
};
NISLFuzzingFunc();
```
#### output
```
nisl
[object Object]
undefined
value nisl
writable false
enumerable false
configurable false
```
#### expected output
```
nisl
undefined
[object Object]
```

**Comment by rhuanjl** [comment]
Consolidating as part of #6390
