### ISSUE TITLE
impact of icu exclusion from chakra library

### ISSUE THREAD

**Issue by sureshyerva87** [microsoft/ChakraCore#6346]
I am using chakra library on Mac platform. I understand, ICU is for unicode support. Can someone explain what is the impact of excluding ICU from chakra library? Would there be any difference from functionality perspective?

**Comment by rhuanjl** [comment]
Without ICU:
- support for some unicode characters is removed so if your JS attempts to use those characters e.g. in a string it will error. (This is stuff like foreign language letters and so on)
- support for INTL is disabled - this is javascript's globalisation library
