### ISSUE TITLE
Question about reference count, when it's deleted?

### ISSUE THREAD

**Issue by karikera** [microsoft/ChakraCore#6354]
When objects are deleted?

I guessed it's similar to COM.
So I guessed every created object has 1 reference and It will not be deleted
And I released every created object at the end.

But It's crashed sometimes.
So I tried to check the reference count, and the created object had 0 references.

I'm confused.
If created objects have 0 references when they are deleted? 
Can I keep zero referenced objects across JsRunScript?

If I want to keep undefined value, Am I need to JsAddRef after JsGetUndefinedValue?

**Comment by rhuanjl** [comment]
Objects you create have no references however CC scans the C stack and hence detects on-going use of any JS values that are in the C stack and will it free them.

You need to use JsAddRef for anything that you want to hold onto that isn’t going to stay in the stack.

That said I believe that the undefined value is unique to each JsContext and cannot be transferred between contexts - you don’t to JsAddRef undefined BUT once you release the context it will go.

Note also the documentation on the wiki is very good and covers all this stuff.

**Comment by karikera** [comment]
@rhuanjl Thanks for answers :)
I couldn't find about garbage collecting from the wiki. :(

In case, If I create temporal objects in the main function, will they are never deleted?
Am I need to set to JS_INVALID_REFERENCE after using it?

**Comment by rhuanjl** [comment]
Most of this is explained in this article: https://github.com/microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview

Couple of things to note:
1. Most JsObjects you create will be tied to a context and a runtime be very careful with trying to access anything in a different context (it can be done but will take a bit more work)
2. If you create an object in your programme's main function and hold a pointer to it on the stack then it should be live as long as your programme runs.
3. To enable something to be collected without returning from the function that created it you do indeed need to overwrite the pointer to it either with something new OR with JS_INVALID_REFERENCE

**Comment by karikera** [comment]
@rhuanjl Thanks!
