### ISSUE TITLE
Array.prototype.toLocaleString uses comma space separator instead of just comma

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6361]
I run following code in ch 1.11.15, the result of ChakraCore is different from other js engines. Though in specification, “string-concatenation” is not defined clearly, other engines’ output is same.

Code:
```
let arg_0 = ['Fire', '', 'Wind', 'Rain'];
arr2 = arg_0.toLocaleString();

print(JSON.stringify(arr2))
```

output of ch:
"Fire, , Wind, Rain"

output of other engines:
"Fire,,Wind,Rain"

ISec Lab
2019.12.21

**Comment by rhuanjl** [comment]
Per spec this is implementation defined, but:
a) all other engines just use a comma instead of comma & space AND
b) in toString (instead of toLocaleString) we use comma only

Should change be consistent - very easy fix change to use GetCommaDisplayString instead of GetCommaSpaceDisplayString here:
https://github.com/microsoft/ChakraCore/blob/c459fea95931c6736e4decd817f5c4d7ca40efc5/lib/Runtime/Library/JavascriptArray.cpp#L8393

Updating tests that use this may take a little while though - tagging as good first issue.

**Comment by muhdmud** [comment]
Hi, could i work on this?

**Comment by ppenzin** [comment]
@muhdmud, sorry for the late reply - surely you can, let me know if you need any guidance on this.

**Comment by muhdmud** [comment]
@ppenzin yes thank you for the opportunity! I will have a go at it this week

**Comment by muhdmud** [comment]
@ppenzin Can I just submit a WIP pr with that oneliner change, then subsequently work on the tests? I assume the tests that i am suppose to be looking  at is at chakracore/test/string, please correct me if im wrong

**Comment by ppenzin** [comment]
@muhdmud Sorry for late reply. Yes, that would be great!

**Comment by ppenzin** [comment]
@rhuanjl, after taking a look at #6499, there is one more place the space is coming from:

https://github.com/microsoft/ChakraCore/blob/c459fea95931c6736e4decd817f5c4d7ca40efc5/lib/Runtime/Library/JavascriptArray.cpp#L8383
https://github.com/microsoft/ChakraCore/blob/c459fea95931c6736e4decd817f5c4d7ca40efc5/lib/Runtime/Library/JavascriptArray.cpp#L8387-L8390

@muhdmud, we are getting the additional space in the failing tests from `GetLocaleSeparator` when that is defined. To fix that we need to change this function to get rid of the space it appends. It is defined in two places (the code to append the space is at the end of the function):

https://github.com/microsoft/ChakraCore/blob/3daa56768f45594ec3461731e68865323900acf1/lib/Runtime/PlatformAgnostic/Platform/Windows/ArraysUtility.cpp#L15
https://github.com/microsoft/ChakraCore/blob/3daa56768f45594ec3461731e68865323900acf1/lib/Runtime/PlatformAgnostic/Platform/POSIX/ArraysUtility.cpp#L51
