### ISSUE TITLE
Wrong realization of 'minus operation' [maybe] of Date object

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6363]
I run the following code in Characore-1.11.15 and get a very odd output. I do not know why the output is so strange. The two print should be same output, both 0. However, the first is -5 in ch. I think there must be something wrong in ch's realization.
The code:
```
var tmp = new Date() - new((2, function() { return Date })());
print(tmp);

var tmp1 = new Date() - new(Date);
print(tmp1);

print("BT_FLAG");
```
Output
```
-5
0
BT_FLAG
```

The result should be:
```
0
0
BT_FLAG
```

ISec Lab
2019.12.21

**Comment by rhuanjl** [comment]
Done a bit of digging this is not a bug. The difference arrises on creation of the Date objects, not when doing the subtraction.

The numeric value of a Date object is a timestamp in milliseconds - there is a 5 millisecond jitter on timestamps in chakracore - introduced intentionally as a spectre mitigation.
