### ISSUE TITLE
ChakraCore throw an TypeError Incorrectly

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6364]
The bug can reproduce in ch version 1.11.15.0.
Running following code:
```
let arg_0 = /^([^(]+?)=>/;
let handler_0 = {
    get: function(oTarget, sKey) {
        return Reflect.get(oTarget, sKey);
    },
};
let p_0 = new Proxy(arg_0, handler_0);
sym = Symbol.prototype.constructor(p_0);
print("BT_FLAG");
let identifier_array = {
    "console": (typeof(console) === 'undefined' ? 'undefined' : console)
};
print(JSON.stringify(identifier_array));
```

Expected result: execute without error thrown
ch's result: TypeError: RegExp.prototype.toString: 'this' is not a RegExp object

According to ecma manual, IsCallable of OrdinaryToPrimitive() will check whether type of p_0 is object. It seems that ch fail to check the type.

ISec Lab
2019.12.24

**Comment by rhuanjl** [comment]
Consolidated in #6390
