### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by ppenzin** [microsoft/ChakraCore#6392]
As discussed in #6384, there is value in improving CMake experience for non-MSVC developers.

I think we should provide first-class CMake build flow, in addition to the script. This should improve development experience - by using usual CMake patterns, and consolidating everything build-related "under one roof", by including testing in the build.

This should also help with integration with external projects built using CMake and various package management systems.

**Comment by Fly-Style** [comment]
I think I can help you with this issue.

**Comment by rhuanjl** [comment]
Issue #1616 has some discussion of similar points, though is probably somewhat outdate/perhaps no longer relevant - worth reviewing and combining with this issue or closing.

**Comment by ppenzin** [comment]
@Fly-Style Feel free to propose any other changes - you call pull my branch and update in your fork.

@rhuanjl Good point, I should have looked deeper into preexisting issues. What I am proposing is much smaller in scope. I think we do need to "refactor" #1616 into proper Github project dedicated to CMake. I will do that, unless there any objections and roll this issue in.

**Comment by ppenzin** [comment]
I've tried following the conversation in #1616 and linked issues/PRs, but can't say I have read every post there. Big things (that CC does not yet support) that we were mentioned in that thread:

- Full CMake builds
- CPack (for things like Debian packages)
- More configuration options

I've opened #6417 for the builds, we can move the CMake discussion there.
