### ISSUE TITLE
Rearranging WebAssembly project

### ISSUE THREAD

**Issue by ppenzin** [microsoft/ChakraCore#6397]
@Cellule - I've added #6396 and put it up as "bug" [WebAssemply project](https://github.com/microsoft/ChakraCore/projects/1), though it does not necessary a bug (at least from correctness point of view). I am not sure what to do with priority here - what were your thoughts on P1, P2, P3 buckets?

**Comment by Cellule** [comment]
P1, P2, P3 buckets were just a way of prioritizing the work at the time and it probably doesn't reflect the current state priority for the community.
Feel free to reorganize according to your preferred method (label, milestone, other buckets, etc...)

**Comment by ppenzin** [comment]
Thank you, will do!
