### ISSUE TITLE
A issue about Regex with flag 'u'.

### ISSUE THREAD

**Issue by ty5491003** [microsoft/ChakraCore#6398]
###### Test Case
```
print(/\udc00/u.test('\udc00\uDC2A'));
print(/\ud800/u.test('\ud800\uDC2A'));
```

###### Excepted Output
true
false

###### Chakra Output
true
true

###### Other JS Engines Output
true
false

###### Description
Is this a bug in chakra? Or is it just that chakr is coded differently from other engines?
Looking forward your reply, thx.

**Comment by rhuanjl** [comment]
Yes this is a bug - with unicode mode (the 'u' flag) a regular expression should not match lone surrogates.

I hope to fix this for a future release but from having had a quick look it's a not an immediately obvious fix, so I can't give a time scale at the moment.

This bug has been reported before so closing this issue as a duplicate: https://github.com/microsoft/ChakraCore/issues/98

**Comment by ty5491003** [comment]
@rhuanjl I get it, thanks for your reply! 👍
