### ISSUE TITLE
Missing early ReferenceError for some invalid simple assignment targets

### ISSUE THREAD

**Issue by bterlson** [microsoft/ChakraCore#640]
For example:

```
async function foo() {
  (await 1) = 1;
} 
```

Expected: early ReferenceError
Actual: no error

**Comment by bterlson** [comment]
To be clear, this is not just a bug with async functions. We are missing early errors for such things as:

```js
function foo() {
  1++;
}
```

Expected: early ReferenceError
Actual: no error

**Comment by ianwjhalliday** [comment]
@pleath tried making this an early error iirc but ran into problems? And Chrome tried too but also had problems?

**Comment by pleath** [comment]
We used to have an incomplete/inconsistent set of assignments to invalid LHS's that would result in early error. I completed the set, but we had compat issues, particularly with foo() = x. Maybe the best we can do right now is throw early error on all invalid LHS *except* function call result.

**Comment by rhuanjl** [comment]
In master all cases mentioned in this issue have been fixed.
