### ISSUE TITLE
Instant communication

### ISSUE THREAD

**Issue by ppenzin** [microsoft/ChakraCore#6401]
Should we add Gitter or Discord (or both)?

I recall @Fly-Style has some experience with it.

**Comment by rhuanjl** [comment]
Agreed this would be useful. I quite like discord though not as familiar with Gitter so don't know which would be better. If we have both I'd imagine one of the two will receive minimal use - unless one becomes primarily for external questions and the other for team discussion.

**Comment by Fly-Style** [comment]
I'd like to start with Discord. If you both agree, I can create it and share the server address.

@rhuanjl 
@ppenzin

**Comment by ppenzin** [comment]
I think we all agree (judging from +1 emojis). Thank you in advance!

**Comment by Fly-Style** [comment]
[Discord ChakraCore server link](https://discord.gg/v8MSmy).

Welcome everyone!

**Comment by ppenzin** [comment]
We should probably add the link to Readme

**Comment by rhuanjl** [comment]
Link is in the read me and all core team members are in the room so closing this issue.
