### ISSUE TITLE
Decide on the home for the repo

### ISSUE THREAD

**Issue by ppenzin** [microsoft/ChakraCore#6406]
This is mostly to get some clarity on when/if we should move community driven development to a different Github organization, as outlined in #6399.

We have created https://github.com/chakra-core with the members of the community team invited.

Creating a separate repo should involve moving or copying the issues from this one.

@rhuanjl, @fly-style, @zenparsing, @chicoxyzzy, and @divmain

**Comment by ppenzin** [comment]
Also see chakra-core/org#1

I am not sure what GH magic is available for this, seems like options right now are to fork in the new organization or transfer and fork back into here. In the former case we don't get to transfer the issues and I personally haven't tried the latter. I am not sure if creating a blank repo and pushing the history would be of any help (doubt it).

**Comment by Fly-Style** [comment]
I hope that MS folks will be supportive and allow repository transfer (maybe after some discussion). 
We are waiting for you @divmain.

**Comment by lizelive** [comment]
Isn't this still used for like minecraft bedrock edition?

**Comment by rhuanjl** [comment]
@lizelive I don't know what products still use chakracore/chakra.dll BUT following microsoft having announced an intention to discontinue it, we (an open source community team), are taking it on hence discussions like this, see #6384 for more detail

**Comment by rhuanjl** [comment]
I agree we will need to move out to the new org at some point - for now I think we push any code we write here as CI is still in place etc. But put documents and plans in the new org.

**Comment by ppenzin** [comment]
I've added a note for eventual move of the repo to https://github.com/microsoft/ChakraCore/projects/3

 We can close this for now.
