### ISSUE TITLE
instanceof not working with external objects

### ISSUE THREAD

**Issue by adrianpi** [microsoft/ChakraCore#6448]
As one can't give native funcions objects a name (name property of function objects is read only) looks like there is no way to make instanceof to work on external objects. Is there any workaround?

**Comment by rhuanjl** [comment]
This definitely can be done, could you perhaps give me a code example to show what you're doing that doesn't work and I'll suggest how to fix it.

**Comment by rhuanjl** [comment]
To add more info.

1. The function name property actually does not interact with the `instanceof` operator - `instanceof` works off of prototypes not names.
2. As an aside you can change the name of a function object using `Object.defineProperty` within JS or `JsDefineProperty` or `JsObjectDefineProperty` to go via the C API.
3. To make `instanceof` work you'll need a constructor with a prototype there are 2 ways to do that:

    1. You can use `JsCreateExternalObjectWithPrototype` to set a prototype in the first place.
    2. you can use JsDefineProperty or JsObjectDefineProperty or JsObjectSetProperty to set a prototype on a constructor you've already created.

**Comment by adrianpi** [comment]
Hi, thanks for your prompt answer.

Attempting to set a 'name' property to a **JSValue** created with **JsCreateFunction** result in the following runtime-error: 

> Assignment to read-only properties is not allowed in strict mode

So now way to make **object.constructor.name** work on the Javascript side, as stated somewhere here:

https://stackoverflow.com/questions/1249531/how-to-get-a-javascript-objects-class

Objects created with **JsCreateExternalObject** are **instanceof Object**, no matter what prototype is assigned after creation. Will try out **JsCreateExternalObjectWithPrototype** and let you know. I was not aware of this API function.

Thanks

**Comment by adrianpi** [comment]
Oh, there is also a JsCreateNamedFunction API. That's good

**Comment by rhuanjl** [comment]
To change the name of a JavascriptFunction you have to use defineProperty rather than set as I said above, defineProperty allows you to overwrite properties that are not writeable, so within Javascript it would be:

```js
Object.defineProperty(someFunction, 'name', {value : 'newName'});
```
From the C api the same can be done using JsDefineProperty. But as said this won't make instanceof work as it's done on prototypes not names - you can actually specify a name upon creation if you use JsCreateEnhancedFunction.

Note your created objects will likely remain instanceof Object if you do this right BUT they'll be instanceof your constructor as well.

**Comment by rhuanjl** [comment]
To add to the above here's some example code.

Notes:
1. if you want your native class to be subclassable (via `extends` in JS) there are a few more steps to do, the below will work if you don't need subclassing support.
2. There's several places below where you ought to check for error codes out of API calls I've left these checks out to make the code snippet shorter/easier to follow - but you should add them for ay production usage.

```c
// Native constructor method
JsValueRef construct(JsValueRef callee, bool isConstructCall, JsValueRef *arguments, unsigned short argumentCount, void *callbackState)
{
  if (isConstructCall == false)
  {
    // do error handling here
  }

  // create our object, setting the prototype directly from callbackState
  JsValueRef object = JS_INVALID_REFERENCE;
  JsCreateExternalObjectWithPrototype(NULL, NULL, callbackState, &object);
  
  return object;
}

JsErrorCode createConstructor()
{
  // create a prototype object
  JsValueRef proto = JS_INVALID_REFERENCE;
  JsCreateObject(&proto);

  // create the constructor, set the prototype as the callback state
  JsValueRef function = JS_INVALID_REFERENCE;
  JsCreateFunction(construct, proto, &function);

  //now we need to set the prototype onto the function
  JsPropertyIdRef protoId = JS_INVALID_REFERENCE;
  JsCreatePropertyId("prototype", strlen("prototype"), &protoId);
  JsSetProperty(function, protoId, proto, true);
  
  //while we're at it let's store the constructor as prototype.constructor
  JsPropertyIdRef constructorId = JS_INVALID_REFERENCE;
  JsCreatePropertyId("constructor", strlen("constructor"), &constructorId);
  JsSetProperty(proto, constructorId, function, true);
  
  //and lets give our constructor a name
  
  // first make a descriptor object
  JsValueRef descriptor = JS_INVALID_REFERENCE;
  JsCreateObject(&descriptor);
  
  // set the constructor's name as the value property
  // descriptor = { value : 'className' }
  JsPropertyIdRef valueId = JS_INVALID_REFERENCE;
  JsCreatePropertyId("value", strlen("value"), &valueId);

  JsValueRef nameString = JS_INVALID_REFERENCE;
  JsCreateString ("className", strlen("className"), &nameString);
  
  JsSetProperty(descriptor, valueId, nameString, false);
  
  // now use defineProperty with the descriptor to set the name
  JsPropertyIdRef nameId = JS_INVALID_REFERENCE;
  JsCreatePropertyId("name", strlen("name"), &nameId);

  bool result = false;
  JsDefineProperty(function, nameId, descriptor, &result);

  //and finally lets make our constructor accessible on the global object
  JsPropertyIdRef classNameId = JS_INVALID_REFERENCE;
  JsCreatePropertyId("className", strlen("className"), &classNameId);
  JsValueRef globalObject = JS_INVALID_REFERENCE;
  JsGetGlobalObject(&globalObject);
  JsSetProperty(globalObject, classNameId, function, true);
  
  return JsNoError;
}```

**Comment by rhuanjl** [comment]
Here's a slightly enhanced version for creating what should hopefully be a fully features native class, this:
a) should work with `extends` and `Reflect.construct` and
b) uses a couple of newer APIs to make the code neater
c) caches some values as static vars to reduce API calls
d) adds parameters to the createNativeClass method so you can call it with different class names and different constructors

```c
static JsPropertyIdRef protoID = JS_INVALID_REFERENCE;
static JsPropertyIdRef constructorID = JS_INVALID_REFERENCE;
static JsValueRef global = JS_INVALID_REFERENCE;

JsValueRef dummyClassConstructor(JsValueRef callee, JsValueRef *arguments, unsigned short argumentCount, JsNativeFunctionInfo *info, void *callbackState)
{
  if (info->isConstructCall == false)
  {
    // set an exception here for class constructor called without 'new'
  }

  // prototype is available as callbackState
  JsValueRef prototype = callbackState;

  // if newTarget is defined get the prototype from the newTarget
  // this is for 'extends' and Reflect.construct
  if (info->newTargetArg != callee)
  {
    JsGetProperty(info->newTargetArg, protoID, &prototype);
  }

  JsValueRef object = JS_INVALID_REFERENCE;
  // create our object, setting the prototype directly from callbackState
  JsCreateExternalObjectWithPrototype(NULL, NULL, prototype, &object);
  
  return object;
}

JsErrorCode createNativeClass(const char* className, JsValueRef nativeConstructor)
{
  // create a prototype object
  JsValueRef proto = JS_INVALID_REFERENCE;
  JsCreateObject(&proto);

  // create a name for the class
  JsValueRef nameString = JS_INVALID_REFERENCE;
  JsCreatePropertyString(className, strlen(className), &nameString);

  // create the constructor, set the prototype as the callback state
  JsValueRef function = JS_INVALID_REFERENCE;
  JsCreateEnhancedFunction(nativeConstructor, nameString, proto, &function);

  //now we need to set the prototype onto the function
  if (protoID == JS_INVALID_REFERENCE)
  {
    JsCreatePropertyId("prototype", strlen("prototype"), &protoID);
  }
  JsSetProperty(function, protoID, proto, true);
  
  //while we're at it let's store the constructor as prototype.constructor
  if (constructorID == JS_INVALID_REFERENCE)
  {
    JsCreatePropertyId("constructor", strlen("constructor"), &constructorID);
  }
  JsSetProperty(proto, constructorID, function, true);

  //and finally lets make our constructor accessible on the global object
  if (global == JS_INVALID_REFERENCE)
  {
    JsGetGlobalObject(&global);
  }
  JsObjectSetProperty(global, nameString, function, true);
  
  return JsNoError;
}
```

**Comment by adrianpi** [comment]
Hello rhuanjl, by using **JsCreateExternalObjectWithPrototype**  solved the issue:

I do:

`JsApi_Model_Value = JSValue.CreateExternalObjectWithPrototype(IntPtr.Zero, finalizeCallbackDelegate, JsApi_Model_Prototype);`

Where Model_Protype has been setup with all methods and properties.
Then on the Javascript side, doing:

`class Model
{
    constructor() 
    {		
    }

	onStart()
	{
		log(this.constructor.name);
		log(this instanceof Model);
...`

Properly returns:

`Model
true`

Thank you very much! You can close the issue.
