### ISSUE TITLE
Break endless loop

### ISSUE THREAD

**Issue by alimtolman** [microsoft/ChakraCore#6452]
Hi. Is there a way to break an endless loop?
In example, I have some script that contains endless loop, and I can't check it before execution.
I want to destroy a runtime instance after delay, but I'm getting exception with message "A runtime that is still in use cannot be disposed".

**Comment by rhuanjl** [comment]
JsDisposeRuntime doesn't stop execution it only frees the runtime object - which it obviously mustn't do if it's in use.

You should try using `JsDisableRuntimeExecution` to stop execution.

And you'll also want to do `JsSetCurrentContext(JS_INVALID_REFERENCE);` before disposing of the runtime.

**Comment by alimtolman** [comment]
Thanks a lot. To use it I've created a runtime instance with 'JsRuntimeAttributeAllowScriptInterrupt' flag.
