### ISSUE TITLE
toPrecision() with incorrect argument 

### ISSUE THREAD

**Issue by laghim** [microsoft/ChakraCore#6462]
In _test/Error/errorNum.js_ the numvar.toPrecision(0) should have an argument at least 1, but here it has 0. 

![image](https://user-images.githubusercontent.com/22259701/84071649-bb60cc00-a9d6-11ea-8733-0f5e5d8ebf88.png)

**Comment by rhuanjl** [comment]
This is actually a test to confirm that chakracore will throw the correct error for calling toPrecision with an invalid input, it's intentionally doing something invalid.

So this is as it's meant to be.
