### ISSUE TITLE
A question about Data.prototype.setFloat64

### ISSUE THREAD

**Issue by NWU-NISL** [microsoft/ChakraCore#6467]
When performing a differential test about the testcase below, When`setFloat64` only has one argument, other engines like V8, spiderMonkey, and javascriptCore pass a default value  as the second argument, while chakraCore throws a TypeError. Will this situation cause code portability issues?
#### version

```
v1.11.8
```

#### command

```
ChakraCore/out/Debug/ch testcase.js
```

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var a = new DataView(new ArrayBuffer(256));
    print(a.getFloat64(1));
    a.setFloat64(1);
    print(a.getFloat64(1));
};
NISLFuzzingFunc();
```

#### output

```
0
TypeError: Required argument offset or value in DataView method is not specified
```

#### expected output

```
0
NaN
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by rhuanjl** [comment]
Thanks for the report. This is a known bug affecting all current released versions but fixed in the master branch by the following PR: https://github.com/microsoft/ChakraCore/pull/6409
