### ISSUE TITLE
A question about Regular Expression ClassRanges match

### ISSUE THREAD

**Issue by YuanWangC** [microsoft/ChakraCore#6470]
According to ES10, it is a Syntax Error if`IsCharacterClass` of [ClassAtomNoDash](https://tc39.es/ecma262/#prod-ClassAtomNoDash) is true or `IsCharacterClass` of [ClassAtom](https://tc39.es/ecma262/#prod-ClassAtom) is true. But when executing the testcase below, I get the output `h,e,l,l,o,w,o,r,l,d`. So I wonder if there is anything wrong in my understanding of this testcase? How does this regular expression match?

#### version

```
v1.11.8
```

#### command

```
ChakraCore/out/Debug/ch testcase.js
```

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var res = "hello world!".match(/[#-\w]/g);
    print(res);
};
NISLFuzzingFunc();
```

#### output

```
h,e,l,l,o,w,o,r,l,d
```

**Comment by rhuanjl** [comment]
This is altered by annex B, see https://tc39.es/ecma262/#sec-patterns-static-semantics-early-errors-annexb

The syntax error you're expecting is thrown if you use unicode mode: `/[#-\w]/gu`.
