### ISSUE TITLE
A question about Object.prototype.hasOwnProperty

### ISSUE THREAD

**Issue by NWU-NISL** [microsoft/ChakraCore#6477]
When the `obj` is `this` and  the method `Object.prototype.hasOwnProperty` has no arguments, other engines like V8, spiderMonkey, and javascriptCore pass a default value and get an output with a value of `true`, while chakraCore gets a `false`. Is this an issue about the default parameter?

#### version

```
v1.11.8
```

#### command

```
ChakraCore/out/Debug/ch testcase.js
```

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var obj = this;
    var res1 = obj.hasOwnProperty();
    print(res1);
    var res2 = obj.hasOwnProperty(undefined);
    print(res2);
};
NISLFuzzingFunc();
```

#### output

```
false
true
```

#### expected output

```
true
true
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by rhuanjl** [comment]
This is a bug, when no argument is provided hasOwnProperty should supply undefined as a default currently it returns false instead, the error is here:
https://github.com/microsoft/ChakraCore/blob/33db8efd9f02cd528a7305391d7d10765a2e85f3/lib/Runtime/Library/JavascriptObject.cpp#L82-L85

If anyone wishes to fix this, simple enough update to those lines + update test/Object/hasOwnProperty.baseline (compare with test/Object/hasOwnProperty.js) - which currently expects the wrong behaviour.
