### ISSUE TITLE
Remove change-heap support in asm.js 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/ChakraCore#65]
See Luke Wagner's reasoning [here](http://discourse.wicg.io/t/request-for-comments-switching-resizing-heaps-in-asm-js/641/22). 

"While this feature works without issue or slowdown in FF/Edge, the change-heap function interferes with the generic closure analysis that allows V8/JSC to detect and optimize the immutability of the heap view variables [11]. In V8, this causes a drastic performance penalty (see issue 39075). If that was the end of the story, I think it'd make sense to hold out until optimizations improve (e.g., on V8 is planning to do full asm.js optimizations3). However, WebAssembly will have a simpler and more direct form of resizing6 along with cross-browser support. Due to the above V8 issue, I don't think many people are using asm.js heap resizing (ALLOW_MEMORY_GROWTH is off by default in Emscripten and recommended against), so to simplify engines, I'd like to remove support for the change-heap function from SpiderMonkey and have suggested to Chakra folks that they do the same. Of course, Emscripten can still support ALLOW_MEMORY_GROWTH by simply emitting almost-but-not-asm"

**Comment by Shiney** [comment]
Is this still something that needs to be done? I'd like to give it a go if it is.

**Comment by abchatra** [comment]
FYI - @MikeHolman 

Yes this still needs to be done. In first cut, you could add a configuration key in [configflagslist.h](https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/ConfigFlagsList.h) to disable change heap api and return false from [here](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Language/AsmJsModule.cpp#L1089) based on that key. By default this key will be off. 

First step is to disable this feature and second step is to completely remove it.
