### ISSUE TITLE
An issue about the Symbol.split.

### ISSUE THREAD

**Issue by Haobin-Lee** [microsoft/ChakraCore#6502]
When I converted Symbol.split into a string and output it, chakra output "undefined",which is different from other engines,like V8,rhino,etc.According to ES standard,the initial value of Symbol.split is "Symbol.split". So I think there may be a problem here.

**version**

1.11.19

**Command**

```javascript
ChakraCore/out/Debug/ch testcase.js
```

**Test case**

```javascript
var NISLFuzzingFunc = function(){
    print(String(Symbol.split));
}
NISLFuzzingFunc();
```

**Output**

```javascript
undefined
```

**Expected behavior**

```javascript
Symbol(Symbol.split)
```

**Comment by rhuanjl** [comment]
This works when run with the flag ES6RegExSymbols. Issue #6390 already covers this.
