### ISSUE TITLE
Implement RegExp.prototype.flags

### ISSUE THREAD

**Issue by NWU-NISL** [microsoft/ChakraCore#6514]
#### Description

When I try to get the flags of a regExp object, chakra returns `undefined`. Then I found that chakra not fully implements regular expression prototype at [here](https://github.com/microsoft/ChakraCore/issues/6390). Maybe RegExp.prototype.flags should be added too.

#### Testcase

~~~javascript
function f0(){
    return /abc/igm.flags;
}
print(f0());
~~~

#### Version

```
chakra-_1_11_22(release)
```

#### Output

~~~javascript
undefined
~~~

#### Expected Output

~~~javascript
gim
~~~

Contributor:@QuXing9

**Comment by rhuanjl** [comment]
Works with the relevant flag - enabling this feature is covered by #6390
