### ISSUE TITLE
A question about String.prototype.match

### ISSUE THREAD

**Issue by YiWen-y** [microsoft/ChakraCore#6515]
###### Version

chakra-1_11_22

###### Test case

```js
RegExp.prototype.exec=()=>{
    print('run here');
    return null;
}; 
print(String.prototype.match());
```

###### Execution steps

```js
./ChakraCore/out/Debug/ch testcase.js
```

###### Output

```

```

###### Expected behavior

```js
run here
null
```

###### Description

When executing this test case, other engines (such as v8, spiderMonkey, JavaScriptCore, etc.) seemed to associate it with RegExp.prototype.exec when calling the String.prototype.match method, but chakra did not do so. May I know what is the reason?

**Comment by rhuanjl** [comment]
Overwritten versions of RegExp.prototype.exec are not currently invoked when they should be this is one of the points discussed in this existing issue: https://github.com/microsoft/ChakraCore/issues/6390
