### ISSUE TITLE
An issue about the try statement.

### ISSUE THREAD

**Issue by NWU-NISL** [microsoft/ChakraCore#6520]
When I executed the try-catch statement without adding a parameter list to the catch, ChakraCore caused a syntax error. According to the ES10 standard, the parameter list can be omitted after the catch statement. So I think there may be a problem here.

**version**

chakra-1_11_22

**command**

```javascript
ChakraCore/out/Debug/ch testcase.js
```

**testcase**

```javascript
var NISLFuzzingFunc = function(){
    try{
        
    }catch{
        
    }
};
NISLFuzzingFunc();
```

**Output**

```javascript
SyntaxError:Expected '('.
```

**Expected behavior**

```javascript
No SyntaxError occurred.
```

Contributor : @Haobin-Lee

**Comment by rhuanjl** [comment]
Catch statements without parameters are supported in the master branch but not in release 1.11. The test passes in master.
