### ISSUE TITLE
An assertion is triggered when an exception is thrown in WScript.LoadScript()

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6522]
Hello, running following code in ch 1.11.22(debug), an assertion will be thrown.
```
class MyObject_7 {
    constructor(v0) {
        this.toString = v0; 
    }   
}
var sc0_198 = WScript.LoadScript(new MyObject_7('', 'samethread'));
```
output:
```
ASSERTION 40340: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.22\lib\runtime\base\scriptcontext.cpp, line 2742) this->threadContext->GetRecordedException() == nullptr || GetThreadContext()->HasUnhandledException()
 Failure: (this->threadContext->GetRecordedException() == nullptr || GetThreadContext()->HasUnhandledException())
FATAL ERROR: ch.exe failed due to exception code c0000420
```
In release version, ch will throw an Error as expected. In debug version, value of `this->threadContext->GetRecordedException()` is not null, but the value of `GetThreadContext()->HasUnhandledException()` is false, and the contradictory conditions trigger the assertion.

ISec Lab
2020.10.9

**Comment by ppenzin** [comment]
This reproduces on 1.11 branch, but not on master. I've tried this with on both Windows and Linux build, getting `TypeError: String expected`.
