### ISSUE TITLE
Assertion fail in HeapArgumentsObject's contructor

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6525]
Hello, executing following code in ch 1.11.22 (debug), an assertion will be thrown.
```
function opt() {                                           
    var eval = WScript.LoadScript('', 'samethread').eval;
    eval('');     
}

opt();      
opt(); 
```
output:
```
ASSERTION 17636: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.22\lib\runtime\library\argumentsobject.cpp, line 43) !frameObject || ActivationObject::Is(frameObject)
 Failure: (!frameObject || ActivationObject::Is(frameObject))
FATAL ERROR: ch.exe failed due to exception code c0000420
```

When `eval('')` in the first `opt()` is called, `this->localClosure`, which is `frameObject`, is Marshaled into CrossSiteObject type. However, when the latter `opt()` is called, `ActivationObject::Is(frameObject)` does not take the `Js::CrossSiteObject<T>` type into consideration.

ISec Lab
2020.10.11

**Comment by ppenzin** [comment]
Bug reproduces on 1.11, but not on master.
