### ISSUE TITLE
An issue about the new Error().

### ISSUE THREAD

**Issue by NWU-NISL** [microsoft/ChakraCore#6527]
When I create an Error object and give it two parameters, the value of the second parameter will be output when the object is output. But like other engines, such as V8, spidermonkey, the output is the first parameter. Therefore, I think there may be a problem here.

**Version**

chakra-1_11_22

**command**

```javascript
./ChakraCore/out/Debug/ch testcase.js
```

**testcase**

```javascript
var NISLFuzzingFunc = function(){
   	return new Error("1","2");
};
var NISLCallingResult = NISLFuzzingFunc();
print(NISLCallingResult);
```

**Output**

```javascript
Error: 2
```

**Expected behavior**

```javascript
Error: 1
```

Contributor : @Haobin-Lee

**Comment by ppenzin** [comment]
MDN [states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error) that the parameters are message + (optional) file name + (optional) line number, it would make sense that we should print the first parameter.

CC @chicoxyzzy

**Comment by rhuanjl** [comment]
There's a prior issue for this: https://github.com/microsoft/ChakraCore/issues/5443

I think it may be to do with intentional "custom" behaviour that was used in some Windows uses of chakra (see details under that issue).

**Comment by ppenzin** [comment]
Thanks @rhuanjl!

Let's close this as a duplicate of #5443
