### ISSUE TITLE
Typo in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by lukeasrodgers** [Microsoft/ChakraCore#66]
I was looking over the code of conduct, out of curiousity and noticed some odd language:

> We will prioritize marginalized people's safety over marginalized people's comfort.

I assume this is a typo, based on https://github.com/todogroup/opencodeofconduct/blob/gh-pages/index.md:

> Our open source community prioritizes marginalized people’s safety over privileged people’s comfort.

cheers

**Comment by bterlson** [comment]
Thanks so much for pointing this out!
