### ISSUE TITLE
Need Jsrt API to inspect Promise objects

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#671]
For a client (debugger?) to inspect Promise objects, we need APIs to access their "status" and "result".

See https://github.com/nodejs/node-chakracore/issues/41

@liminzhu @agarwal-sandeep

**Comment by agarwal-sandeep** [comment]
Atleast for debugging purpose, in locals windows we need to implement a display and walker for Promise object similar to RecyclableProxyObjectDisplay and RecyclableProxyObjectWalker and add fake properties [status] and [result]

**Comment by agarwal-sandeep** [comment]
In debugger Promise objects now show [Promise] fake node with [status] and [value] as childrens.
