### ISSUE TITLE
React-based site - This page is having a problem loading

### ISSUE THREAD

**Issue by awarberg** [Microsoft/ChakraCore#676]
We have two websites based on React js. They both fail with "This page is having a problem loading". I found a crash event log and related log files but there is little information that I can find to go on.

I've compiled this archive with a static html page (sendsms, saved from Chrome) and the log files.
[msedge.zip](https://github.com/Microsoft/ChakraCore/files/193284/msedge.zip)

The site this page is from has been tested and works in Chrome, Firefox, IE11 and a range of mobile browsers.

I suspect that our javascript (maybe combined with React js) is triggering some error condition in Edge, but I am at a loss how to debug this since the browser crashes.

I would appreciate if anyone could take a look at this bug and give me some pointers.

**Comment by abchatra** [comment]
Hi @awarberg I am able to repro this my windows 10 box. Crash call stack is in edgehtml and not Chakra. This needs to be reported to Edge team. Please file the bug on Edge team here:  https://connect.microsoft.com/IE/Feedback

**Comment by awarberg** [comment]
Thank you for checking this. I've created this issue with Microsoft and am closing the bug at ChakraCore:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7150549/
