### ISSUE TITLE
SIMD.js - RegAlloc may fold SIMD operands

### ISSUE THREAD

**Issue by nmostafa** [Microsoft/ChakraCore#695]
With register pressure, RegAlloc may fold SIMD operands to be loaded from memory. Since we currently don't ensure 16-byte alignment for SIMD stack syms, this might trigger an AV.

```
// Try folding if there are no registers available
 if (!sym->IsConst() && !this->RegsAvailable(regOpnd->GetType()) && EncoderMD::TryFold(instr, regOpnd))
 {
                    return;
}
```

**Comment by abchatra** [comment]
Thanks! Please update with a script test case.

**Comment by rahulchaphalkar** [comment]
Attached a test case, which gives AV for x86 as well as x64 platforms.
[testCase.zip](https://github.com/Microsoft/ChakraCore/files/196735/testCase.zip)

**Comment by abchatra** [comment]
Thanks! Marked it as 1.2
