### ISSUE TITLE
Chakra doesn't throw SyntaxError if function is declared in statement context

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#7]
As per [this](http://tc39.github.io/ecma262/#sec-functiondeclarations-in-ifstatement-statement-clauses) section of ECMA spec, chakra should throw syntax error for below code, but it accepts it without errors.

```javascript
(function() { "use strict"; if (true) function f() { } })()

```

**Comment by ianwjhalliday** [comment]
Fixed by #30
