### ISSUE TITLE
Build URLs in README.md are broken

### ISSUE THREAD

**Issue by jaredfaris** [Microsoft/ChakraCore#70]
Visiting http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/Microsoft_ChakraCore_x86_release/ or any of the other links results in a 404. Also, the images in the Build Status area are missing.

![missing images](https://s3.amazonaws.com/f.cl.ly/items/393b312R021T0n2K3S05/Image%202016-01-13%20at%201.21.52%20PM.png?v=2ee7f17c)

**Comment by liminzhu** [comment]
@dilijev

**Comment by bransorem** [comment]
#68 will fix this once merged.

**Comment by dilijev** [comment]
Now merged. Closing as duplicate.

**Comment by jaredfaris** [comment]
Cool, didn't see the dupe. Sorry about that.
