### ISSUE TITLE
Switch optimizations are not disabled when we rejit because of them.

### ISSUE THREAD

**Issue by rajatd** [Microsoft/ChakraCore#703]
When we rejit (which means that some assumption we made in the jit is no longer true and we have bailed out enough times to realize that we want updated profile info) we disable the optimization that caused the bailouts and the rejit. Otherwise, there is a high chance that we will keep bailing out and rejitting because of the same reason. This is not being done for switch opts.

**Comment by dilijev** [comment]
Resolved by #704
