### ISSUE TITLE
SIMD.js - Store operations return NULL instead of passed value per spec

### ISSUE THREAD

**Issue by nmostafa** [Microsoft/ChakraCore#708]
The current implementation of SIMD store ops erroneously returns NULL (instead of Undefined). This causes a crash when merging ValueTypes during profiled interpretation, if store is used in an assignment. The correct behavior is to return the passed value, instead of Undefined. 

Repro case:
[stDstBug.js.txt](https://github.com/Microsoft/ChakraCore/files/198396/stDstBug.js.txt)

**Repro case**
>
```javascript
function func1()
{
    var buffer = new ArrayBuffer(1000);
    var arr = new Float32Array(buffer);
    var x = SIMD.Float32x4(0,0,0,0);
    var y = x;
    var f = SIMD.Float32x4(1, 2, 3, 4);
    for (var i = 0; i < 100/4; i += 4)
    {
        y = SIMD.Float32x4.store(arr, i, f)
        x = SIMD.Float32x4.add(x, y);
    }    
    return x;
}
print(func1());
print(func1());
```

**Expected Output:**
>
SIMD.Float32x4(7, 14, 21, 28)
SIMD.Float32x4(7, 14, 21, 28)

**Actual Output**
>
ASSERTION 31060: (G:\arun\git\chakra-310\core\lib\Runtime\Language\ValueType.cpp, line 1206) var
 Failure: (var)
FATAL ERROR: ch.exe failed due to exception code c0000420

**Comment by abchatra** [comment]
@nmostafa It would be great if you provide inline script repro something like below:
```js
function func1()
{
    var buffer = new ArrayBuffer(1000);
    var arr = new Float32Array(buffer);
    var x = SIMD.Float32x4(0,0,0,0);
    var y = x;
    var f = SIMD.Float32x4(1, 2, 3, 4);
    for (var i = 0; i < 100/4; i += 4)
    {
        y = SIMD.Float32x4.store(arr, i, f)
        x = SIMD.Float32x4.add(x, y);
    }
    
    return x;
}


print(func1());
print(func1());
```
Also always add an expected and actual output as well.

**Comment by arunetm** [comment]
**Repro case**
>
```javascript
function func1()
{
    var buffer = new ArrayBuffer(1000);
    var arr = new Float32Array(buffer);
    var x = SIMD.Float32x4(0,0,0,0);
    var y = x;
    var f = SIMD.Float32x4(1, 2, 3, 4);
    for (var i = 0; i < 100/4; i += 4)
    {
        y = SIMD.Float32x4.store(arr, i, f)
        x = SIMD.Float32x4.add(x, y);
    }    
    return x;
}
print(func1());
print(func1());
```

**Expected Output:**
>
SIMD.Float32x4(7, 14, 21, 28)
SIMD.Float32x4(7, 14, 21, 28)

**Actual Output**
>
ASSERTION 31060: (G:\arun\git\chakra-310\core\lib\Runtime\Language\ValueType.cpp, line 1206) var
 Failure: (var)
FATAL ERROR: ch.exe failed due to exception code c0000420
