### ISSUE TITLE
Fix scoped enums that are used as an array size.

### ISSUE THREAD

**Issue by Rastaban** [Microsoft/ChakraCore#745]
Scoped enums will not be usable as an array size or index in the future in MSVC.

For example:

enum class Color 
{ Red, Green, Blue };
int data[Color::Blue]; // error C3411: 'Color' is not valid as the size of an array as it is not an integer type

This was allowed in previous releases of MSVC, but will not be in the future (see http://webcompiler.cloudapp.net/ for the behavior of the latest unreleased compiler build).  The best fix is usually to use a cast.

A scoped enum is being used in CompactCounters.h in the members of the Fields struct.

**Comment by ianwjhalliday** [comment]
#751 addressed `CompactCounters.h`.  @Rastaban have you found any other uses of scoped enums in ChakraCore?  Can we resolve this issue as fixed?

**Comment by Rastaban** [comment]
There are no other uses, please resolve the issue as fixed.
