### ISSUE TITLE
SIMD.js: SIMD.Uint16x8.Equal returns incorrect results when optimized through lowerer

### ISSUE THREAD

**Issue by arunetm** [Microsoft/ChakraCore#749]
The SIMD.Uint16x8.Equal() builtin function can return incorrect results when optimized. This happens when the simd values that is being compared has lane values beyond the bounds of uint16 type. 

This issue is caused by the incorrect lowering of the comparison operation. The lowerer uses byte comparison instead of word comparison for reaching the results. 

**Repro Case**
>
```javascript
var a = SIMD.Uint16x8(216   ,     824,  -0.0,  432,   -1065353216, -1073741824,-1082130432, -1082130432);
var b = SIMD.Uint16x8(353216, -492529, -1128, 1085,             0,          -1,         3,           3);
function asmModule(stdlib, imports) {
    "use asm";
    var b8 = stdlib.SIMD.Bool16x8;
    var u8 = stdlib.SIMD.Uint16x8;
    var b8check  = b8.check;
    var u8check  = u8.check;
    var u8equal  = u8.equal;
    var globImportA  = u8check(imports.g1);
    var globImportB  = u8check(imports.g2);
    var gb8 = b8(0,0,0,0,0,0,0,0);
    function func3()
    {
        gb8 = u8equal(globImportA, globImportB);
        return b8check(gb8);
    }
    return {func3:func3};
}
var m = asmModule(this, {g1:a, g2:b});
print(SIMD.Uint16x8.equal(a,b));
print(m.func3());
```

**Execution Flags**
>
-simdjs -maic:0

**Actual Results**
>
Successfully compiled asm.js code
SIMD.Bool16x8(false, false, false, false, true, false, false, false)
SIMD.Bool16x8(false, false, false, false, true, false, true, true)

**Expected Results**
>Successfully compiled asm.js code
SIMD.Bool16x8(false, false, false, false, true, false, false, false)
SIMD.Bool16x8(false, false, false, false, true, false, false, false)

**Comment by dilijev** [comment]
@abchatra Is this okay for Milestone 1.2?

**Comment by abchatra** [comment]
@dilijev Yes its ok for 1.2
