### ISSUE TITLE
Typo in wiki page build chakracore

### ISSUE THREAD

**Issue by ThomsonTan** [Microsoft/ChakraCore#75]
In page https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore, there is a typo in below step. (thtough->through)

Clone ChakraCore thtough git clone https://github.com/Microsoft/ChakraCore.git

**Comment by tcare** [comment]
Thanks for the report @ThomsonTan! fixed in https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore/7a8df67ead61d46dc0a024b1be52b37f3d06530c
