### ISSUE TITLE
Change license to ISC

### ISSUE THREAD

**Issue by jeremiahlee** [Microsoft/ChakraCore#76]
There is no reason for Microsoft to align itself with the institution of MIT. The [ISC License](https://opensource.org/licenses/ISC) is a functionally equivalent license approved by the Free Software Foundation and is compatible with Node core's license. The ISC License is the preferred license of OpenBSD, among other projects.

**Comment by Garbee** [comment]
> is a functionally equivalent license

So what is the benefit of changing the license if it provides the same rights to users and coverage to the producer?

**Comment by DerFlatulator** [comment]
Does adopting a license _really_ imply alignment?

**Comment by taspeotis** [comment]
There is no reason for Microsoft to align itself with the institution of ISC. The MIT License is a functionally equivalent license...

**Comment by jeremiahlee** [comment]
For people who were active in open source advocacy, defense of civil rights online, intellectual property reform, and online privacy in the oughties, [Aaron Swartz](https://en.wikipedia.org/wiki/Aaron_Swartz) was a hero. Unfortunately, his activism led to a situation with MIT that motivated his suicide. For people who care about these issues, there is still great sensitivity with anything associated with MIT.

I recommend this story about Aaron's father and MIT owning up to its part in his son's suicide.
[Boston Magazine: "Losing Aaron" by Janelle Nanos](http://www.bostonmagazine.com/news/article/2014/01/02/bob-swartz-losing-aaron/)

The MIT license is an affirmation of MIT. While the institution has enabled many great things, it has also greatly contributed to one of the greatest losses of my generation. It fought a leader of ideals that I still care about and when it won, humanity lost. The ISC license is functionally equivalent without institutional baggage.

**Comment by Radle241** [comment]
I don't see then need to distance oneself from the people who wrote the MIT license, in order to distance oneself from the people at MIT that Aaron Schwartz was involved in.

MIT was founded 1861, it would be quite difficult to distance oneself from everything that they were involved in.

**Comment by jasnell** [comment]
Equating the use of the MIT license with the circumstances around Aaron's death is ... odd. The MIT license is perfectly suitable.

**Comment by Studio384** [comment]
Someones death is a very weird reason to not use a certain license...

**Comment by gabereiser** [comment]
Keep the MIT license please.

**Comment by liquidboy** [comment]
Terrible reason to move off MIT..

**Comment by Senjai** [comment]
Close this please. Keep politics out of code, it doesn't belong here. OSS is a poor medium to be an activist about completely unrelated things.

**Comment by wmhilton** [comment]
The Aaron Swartz bit is a really interesting argument for using ISC over MIT. I hadn't heard that before. (I'm fine either way though- to me they are equivalent. Maybe ISC is more politically correct these days...)

**Comment by Studio384** [comment]
> The Aaron Swartz bit is a really interesting argument for using ISC over MIT. I hadn't heard that before. (I'm fine either way though- to me they are equivalent. Maybe ISC is more politically correct these days...)

I'm really curious about this: why is this a good argument? Why is this even an argument?

**Comment by gabereiser** [comment]
it's not...  MIT legalese is more specific about sharing/forking/selling/derivatives than ISC and therefore is a better license (imho).  I use it a lot as well.  Bringing up a political/personal reference on why the license should be changed (that has nothing to do with the license) is a straw-man.

**Comment by Flyingmana** [comment]
A lot of very big Projects in the PHP Ecosystem use MIT very successfully and without problems yet.
Its well known by many open source contributors and is also often preferred from from big corporations.
