### ISSUE TITLE
JsDiagGetObjectFromHandle reurns object with JsDiagEvaluate alike properties

### ISSUE THREAD

**Issue by AndiVlad** [Microsoft/ChakraCore#775]
When calling JsDiagGetObjectFromHandle i'd expect the same property structure for the object returned. It seems that when called on handle returned in the locals array of the JsDiagGetStackProperties method, it will return a structure like:

        ///     {
        ///         "name" : "this",
        ///         "type" : "object",
        ///         "display" : "{...}",
        ///         "className" : "Object",
        ///         "propertyAttributes" : 1,
        ///         "handle" : 18
        ///     }

Instead of

        ///     {
        ///         "scriptId" : 24,
        ///          "line" : 1,
        ///          "column" : 63,
        ///          "name" : "foo",
        ///          "type" : "function",
        ///          "handle" : 2
        ///     }	

Is this the intended behavior? If so is there a way to get the information such as line/column from an object returned as locals?

Great work so far!

**Comment by agarwal-sandeep** [comment]
_JsDiagGetStackProperties_ is supposed to return locals, scopes and global properties for give stack frame whereas _JsDiagGetObjectFromHandle_ is supposed to return the object representation of a handle.

_JsDiagGetObjectFromHandle_ is mainly for getting the function representation from _functionHandle_ returned in _JsDiagGetStackTrace_.

The APIs are used in Ch debugger, take a look at [DbgController.js](https://github.com/Microsoft/ChakraCore/blob/JsRTDebugging/bin/ch/DbgController.js)

Thanks for the feedback, I am open to suggestion for improvements.
