### ISSUE TITLE
C++ code should follow the C++ Core Guidelines

### ISSUE THREAD

**Issue by leeter** [Microsoft/ChakraCore#78]
Except where required for performance/API reasons the c++ code should follow the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/) and use the [Guidelines Support Library](https://github.com/Microsoft/GSL) to ensure safer code and reduce complexity and security risks

Related:[C++11 Language features allowed in Chrome](https://chromium-cpp.appspot.com/)

**Comment by leeter** [comment]
@hsutter

**Comment by dilijev** [comment]
General guidelines are great to have. Is there a tool available to detect deficiencies in adhering to the guidelines? That would definitely help in a code base this size.

If you see specific issues you'd like to correct, please open a PR.

**Comment by leeter** [comment]
At this point I wanted to get the conversation started, I have noticed a few spots where the guidelines are being violated. But I didn't want to get started on anything because I had noticed a few things:

* ChakraCore does not seem to reference the C++ standard library at all even when it might be better to do so e.g. `unique_ptr` vs. Chakra's `AutoPtr`
* Other C++11/14 features don't seem to be used such as `noexcept` and `constexpr` even with macros to allow for back compatibility with VS2013. This seemed odd since the primary target compilers (VS2015 and GCC5) both support them and they could have a reasonable performance impact.
* if ChakraCore decides to use the GSL is it going to use it as a submodule? or take drops when convenient?

**Comment by bnavarma** [comment]
Am I missing something https://www.nuget.org/packages/Microsoft.CppCoreCheck. This tool is from MS itself.

**Comment by EdMaurer** [comment]
Our coding conventions are documented here [https://github.com/Microsoft/ChakraCore/wiki/Coding-Convention](https://github.com/Microsoft/ChakraCore/wiki/Coding-Convention). The team is not interested in grand changes to the coding style. However, we would entertain targeted use of some of these constructs provided the change delivered a proven performance win.

**Comment by leeter** [comment]
I'm not recommending a change in coding style per say. I'm recommending having clear resource lifetimes, coding in a way that is less likely to create bugs. What I see is C with classes or at best c++98. It is not even close to safe coding practices.

**Comment by leeter** [comment]
@dilijev based on @EdMaurer 's comment I'm going to close this, I'm very concerned about the security of the code the way it is written. I will not be using ChakraCore in any project I'm involved with as a result.

**Comment by Michael-S** [comment]
I haven't read all of the commits, but according to Microsoft's own official blogs the project was started in 2008, right?  That's a pretty good reason for not using C++11 standard features throughout the project - some of those features didn't exist yet when the project launched.

**Comment by curtisman** [comment]
@Michael-S That's correct.  Actually, some of the code (e.g. parser) are ported over from the old jscript engine, which is even older (late 90's).

We have been introducing C++11 features to the code base (e.g. lambda), but if the existing code is already working, we generally don't go back and update them unless we are going to touch the code for some other reason to avoid the unnecessary risk of introducing new bugs.

**Comment by Michael-S** [comment]
@curtisman  thank you for the response, and the confirmation.  Then I completely understand why ChakraCore is not completely written in idiomatic C++11.
