### ISSUE TITLE
Timeouts can fire even when unset syncronously 

### ISSUE THREAD

**Issue by calvinmetcalf** [Microsoft/ChakraCore#784]
this is likely a bug with setTimeout, so if that's a Edge thing I can reopen there.  As reported defunctzombie/node-process#56 it looks like it's possible to add a setTimeout run synchronous code and then call clearTimeout but have the timeout callback called anyway. If I had to guess my suspicion  would be that certain dom functions may block the thread without blocking the event loop (like [this bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=1202918) in firefox)

**Comment by Yongqu** [comment]
Yes setTimeout is an edge function and please report the issue to edge. thanks.

**Comment by calvinmetcalf** [comment]
ok opened up over there https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7206104/
