### ISSUE TITLE
ChakraCore.jar

### ISSUE THREAD

**Issue by dancingfrog** [Microsoft/ChakraCore#79]
Build solutions is working great to produce ChakraCore.dll, but will there ever be an option to create a Java library so we can use this JS engine in our Java applications? Would love to see a portable version of Chakra (one that runs on OS X, Linux, etc.), similar to V8 and Mozilla's JS engines

**Comment by dilijev** [comment]
We will evaluate the Java layer option.

Re cross-plat: We are working on porting to Linux. See [Roadmap](https://github.com/Microsoft/ChakraCore/wiki/Roadmap) and the [linux branch](https://github.com/Microsoft/ChakraCore/tree/linux).

**Comment by gabereiser** [comment]
There are java based javascript engines already (Rhino), I would rather see linux/osx support first w/ cmake before trying to wrap this for java so you can run javascript.

**Comment by dancingfrog** [comment]
@gabereiser I whole-heartedly agree in terms of priorities, but I was specifically asking if there were any plans for a java implementation and affirming that it would be very useful to a great many devs and system architects.

**Comment by dhusemann** [comment]
Why close this. while a lower priority the community may pick up and write the proposal??

**Comment by dancingfrog** [comment]
Oh, OK. I thought "We will evaluate the Java layer option" meant it would be handled elsewhere, but you're right @dhusemann, this is a community project now, so this seems as good a place as any to continue the conversation.

**Comment by schipplock** [comment]
@gabereiser nashorn is the new rhino in java 8 :).

**Comment by gabereiser** [comment]
> nashorn is the new rhino in java 8 :).

I know that, I was just making a point...

**Comment by schipplock** [comment]
@gabereiser, in fact I just wanted to say the nashorn rhino thing :). Your point is valid as rhino and nashorn offer the best "interface" to java from javascript right now. The other way around works well as well. But I understand the request to have chakra even in the java world as chakra offers more es6 features compared to nashorn e.g. but I read that oracle is working hard to extend nashorn to offer es6 features as well.

**Comment by EdMaurer** [comment]
This has no community traction. The core Chakra team has no plans to do this. That doesn't mean that we wouldn't want to discuss a proposal.
