### ISSUE TITLE
Small typo in Embedding Chakra Wiki: "CharkaCore.h" 

### ISSUE THREAD

**Issue by brakmic** [Microsoft/ChakraCore#80]
Hi,

There's a small typo in the C++ code example at: https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore

"CharkaCore.h" should be "ChakraCore.h".

Was just wondering why my VS2015 couldn't find any classes, functions etc. :)

![charka](https://cloud.githubusercontent.com/assets/56779/12309713/8930123c-ba4c-11e5-9600-0353337e5f3c.png)

Regards and many thanks for the Engine :+1:

**Comment by abchatra** [comment]
Fixed. Thanks a ton @brakmic
