### ISSUE TITLE
JSON.parse("") gives very ambigious "Syntax Error".

### ISSUE THREAD

**Issue by nojvek** [Microsoft/ChakraCore#804]
```javascript
JSON.parse("")
```

```
$ ch.exe jsonParseEmpty.js
SyntaxError: Syntax error
   at Global code (d:\personal\chakracore\build\vcbuild\bin\x64_debug\test.js:1:1)
```

'Syntax Error' is very ambiguous error. It could mean a lot of things. When its part of a large callstack, I would think its a javascript syntax error somewhere in my js files. The callstack doesn't even mention JSON.parse.

Chrome gives
```
VM145:1 Uncaught SyntaxError: Unexpected end of JSON input(…) 
```

Ideal error should mention something like "JSON.parse Syntax error: Empty string" or "JSON.parse Syntax Error: unexpected end of json input."

**Comment by dilijev** [comment]
@nojvek I think this would be relatively straightforward to tackle. Would you like to do the honors?

Exception seems to be coming from:
lib\Runtime\Library\JSONParser.cpp:412 - JSON::JSONParser::ParseObject
See the following for the JSON.parse() entry point:
lib\Runtime\Library\JSON.cpp:22 - JSON::Parse

**Comment by nojvek** [comment]
Sure, I'll take a stab at it Doug.
