### ISSUE TITLE
Use size_t * instead of unsigned int * for JsSerializeScript's bufferSize param

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#825]
See https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCommon.h#L1113

Since this is a buffer size, the most portable type for the parameter would be `size_t` instead of `unsigned int *`.

@liminzhu: @digitalinfinity mentioned this might not be possible because of compat, but could you confirm that and see if we might want to make this change anyway?

**Comment by liminzhu** [comment]
Before we discuss it, @digitalinfinity I remember signature was taking ```unsigned long *``` instead of ```unsigned int *``` and saw you changed it in the https://github.com/Microsoft/ChakraCore/pull/766. It seems to break compat. Any reason why you did this change?

**Comment by Yongqu** [comment]
size_t won't be available in Linux; sizeof(long) is different from sizeof(int) in Linux. changing from unsigned long to unsigned int shouldn't change backwar compat. @liminzhu what is your concern?

**Comment by obastemur** [comment]
> size_t won't be available in Linux..

AFAIK We do use many other 'aliased' types. 'size_t' is available in Linux and it's not different than others. In case we have a problem with these aliases are represented with different sub types on varying platforms, that's something else.

**Comment by dilijev** [comment]
Yep, `size_t` is in the standard. I don't think there's any problem there.

**Comment by curtisman** [comment]
Do we need size_t if we don't support byte code buffer >= 2^32?

**Comment by dilijev** [comment]
Maybe we should define a `ChakraByteCodeBufferSize` type (or something less verbose) to capture the semantic info about the type (the fact that regardless of platform, we have a max buffer size), so that this question doesn't keep coming up?

**Comment by mgetzbw** [comment]
The c++ way to do it would be to do a `using size_type = std::size_t;` (for pre-C++11: `typedef std::size_t size_type;`) on the type itself, and then use the type alias on all the methods. If you're going to do that however I would consider also considering defining a `buffer_traits` template that knows how to get all this information or what to fall back to if the aliases aren't defined for that buffer type. I would consider reaching out to the VC++ Libraries team for guidance here as they've had to deal with these issues quite a lot and may be able to suggest coding standards around these sorts of issues.

**Comment by obastemur** [comment]
Closing this. ChakraCore no longer asks for buffer size.
