### ISSUE TITLE
SIMD.js: Asmjs validation allows returning simd values from functions without coercion. 

### ISSUE THREAD

**Issue by arunetm** [Microsoft/ChakraCore#827]
Asmjs validation should require coercion for return values. Simd values needs to be coreced using the check() builtin before returning from asmjs functions. currently this is not enforced. 

**Repro Case**
```javascript
function module(stdlib) {
    "use asm"
    var b = stdlib.SIMD.Uint8x16;
    function foo() {
        var abc = b(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1);
        return abc;
    }
    return { foo:foo }
}
```

**Expected results**
>	Asm.js Compilation Error function : module::foo
 	Expression for returning simd values must be coerced using check()
  Asm.js compilation failed.

**Actual Results**
Successfully compiled asm.js code

**Comment by MikeHolman** [comment]
We have come to consensus that this coercion should not be required.
