### ISSUE TITLE
Add ChakraCore to http://up-for-grabs.net/

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#83]
http://up-for-grabs.net/ has a curated list of tasks which are simple enough to help the community get involved in open source projects.

Refer to instructions here for how to get our repo added to the list. https://github.com/up-for-grabs/up-for-grabs.net#add-your-project

Thanks to @RichiCoder1 on Gitter for suggesting this.

**Comment by dilijev** [comment]
Opened a PR to add our project to up-for-grabs.net: https://github.com/up-for-grabs/up-for-grabs.net/pull/333

**Comment by MikeHolman** [comment]
What is the advantage of this over tagging issues as "Accepting PRs"?

**Comment by dilijev** [comment]
We will use the tag Accepting PRs. This is yet another avenue for people to look for issues they might want to help solve. It doesn't require any extra work on our part besides getting our repo added to that website, so it seems like a worthwhile one-time effort.

**Comment by dilijev** [comment]
Creating the 'Accepting PRs' issues will be an ongoing effort so there's no need to have an issue tracking it.

**Comment by dilijev** [comment]
We're now visible on up-for-grabs.net.

![image](https://cloud.githubusercontent.com/assets/494055/12316634/cdf7d274-ba3d-11e5-8aa5-8a535b007f61.png)

**Comment by dilijev** [comment]
To see the corresponding issues: https://github.com/Microsoft/ChakraCore/labels/Accepting%20PRs
