### ISSUE TITLE
Running ChakraCore in ASP.NET web api

### ISSUE THREAD

**Issue by varghesep** [Microsoft/ChakraCore#830]
I have a data processing logic (map-reduce) in a _JavaScript file _which currently runs on browser. The user downloads this data processing JS file as part of the html content download, and then the browser runs it.

I currently use _ASP.NET 5 Web API _for data retrieval. I want to move this data processing logic (JS file) **to the server side**. One option I've looked at is running this JS file in NODE.JS. Since I don't want to add another technology of NODE.JS, can I run the ChakraCore in ASP.NET 5 WebAPI and then process the data?

**Comment by bterlson** [comment]
Yes, it is possible. See our wiki on [Embedding ChakraCore](https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore) for some pointers!
