### ISSUE TITLE
Get properties for this

### ISSUE THREAD

**Issue by AndiVlad** [Microsoft/ChakraCore#832]
Hello,

Given a script that looks like:
```
function test1() {
    this.number = 1;
    this.str = "str";
    this.obj = { "a": 1, "b": 2 };
    this.arr = [1, 2, 3, 4];
    this.func = function () {
        var inti = 2;
    };
    debugger;
}

test1.prototype.snumber = 2;
test1.prototype.sstr = "str2";
test1.prototype.sfunc = function () {
    var inti3 = 4;
};

```

I couldn't find a way to get the 'this' value when hitting the debugger line. `eval(test1.prototype) `shows the static members, `eval(this)` shows a bunch of global properties but none defined inside the function, same for eval Object methods such as `keys`, `getOwnPropertyNames`. The stack information gotten via the `JsDiag*` methods doesn't return any locals. Any idea how to get the members and print a proper 'this' ?

Thanks

**Comment by bterlson** [comment]
Are you calling test1 with the `new` operator?

**Comment by AndiVlad** [comment]
A bit more context. Here's the full script:

```
function test1() {
    this.number = 1;
    this.number2 = this.number + 1;
    this.str = "str";
    this.obj = { "a": 1, "b": 2 };
    this.arr = [1, 2, 3, 4];
    this.func = function () {
        var inti = 2;
        this.insidestr = "str2";
        debugger;
    };
    debugger;
}

var t = new test1();
t.func();

test1();
```

1) When calling the constructor, first debugger hit, none of the `this.*` properties come up anywhere in the `JsDiagGetStackProperties` method, either as Local/Global/Scope etc
2) When the second debugger hits inside the func call, the t variable appears in the globals object and has the members initialized properly
3) When  hitting the debugger via the direct test1 call, the members appear in the globals object

Considering the code performs ok, this.number2 is actually initialized to the value 2, i believe there's some issue with how the `JsDiagGetStackProperties` handles the scopes ?

**Comment by agarwal-sandeep** [comment]
Thanks @AndiVlad, There is definitely some issue here I will investigate. Marking as bug and assigning to myself.

**Comment by agarwal-sandeep** [comment]
Fixed in https://github.com/Microsoft/ChakraCore/commit/8a6c56f86abf74b94ce2e29893cd082004ff7fb2
You should be able to get _this_ value by calling _JsDiagEvaluate("this", stackFrameIndex)_

I think we should have a this object handle in _JsDiagGetStackProperties_, similar to globals handle. Will look into it.

**Comment by agarwal-sandeep** [comment]
'_this_' value if available for the frame will be returned by call to _JsDiagGetStackProperties_ under '_thisObject_' property.

https://github.com/Microsoft/ChakraCore/commit/dcc2513af571971e946fa06ced0c0d55ec53c133
