### ISSUE TITLE
Simd.js Bug: Simd type conversions in asmjs sets the dst type incorrectly

### ISSUE THREAD

**Issue by arunetm** [Microsoft/ChakraCore#866]
The helper method used to build IR for simd type conversion operations sets the destination register type to 'TySimd128I4' always. 

**Repro Case**
```javascript
function asmModule(stdlib) {
    "use asm";
    var i4 = stdlib.SIMD.Int32x4;
    var i4check = i4.check;
    var u4 = stdlib.SIMD.Uint32x4;
    var u4swizzle = u4.swizzle;
    var u4shuffle = u4.shuffle;
    var u4fi4 = u4.fromInt32x4Bits;
    var i4fu4 = i4.fromUint32x4Bits;
    function func1(a)
    {
        a = i4check(a);
        var x = u4(0, 0, 0, 0);
        x = u4swizzle(x, 3, 2, 1, 0);
        x = u4shuffle(u4fi4(a), x, 0, 1, 7, 6);
        return i4check(i4fu4(x));
    }
    return {func1:func1};
}
var m = asmModule(this);
var ret2 = m.func1(SIMD.Int32x4(1,2,3,4));
```

**Expected Results**
>Successfully compiled asm.js code
PASS

**Actual Results**
>Successfully compiled asm.js code
ASSERTION 16232: (G:\arun\git\chakra-411\core\lib\Backend\Sym.cpp, line 382) stackSym->GetType() == type
 Failure: (stackSym->GetType() == type)
FATAL ERROR: ch.exe failed due to exception code c0000420

**Comment by abchatra** [comment]
@arunetm Can this issue be closed now?

**Comment by arunetm** [comment]
@abchatra, yes the fix has already been merged.
