### ISSUE TITLE
ActiveX

### ISSUE THREAD

**Issue by kasajian** [Microsoft/ChakraCore#88]
Since Internet Explorer use Chakra, and in Internet Explorer one can new-up an ActiveXObject instance to access safe-COM objects, does that mean that this open source version of Chakra can do the same?   If so, does that mean I can execute that type of code from within version of node that's bound to Chakra?

I want to be able to execute code that looks like this:
    var xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");

**Comment by dilijev** [comment]
We only do maintenance work on old versions of Chakra as needed for security issues (Windows Update patches).

The current version of Chakra (used in Edge) uses the open source version of ChakraCore and does not support ActiveX as that is one of the features we dropped as a legacy feature.

See: https://blogs.windows.com/msedgedev/2015/05/06/a-break-from-the-past-part-2-saying-goodbye-to-activex-vbscript-attachevent/

**Comment by kasajian** [comment]
Okay, thank you.

**Comment by kunalspathak** [comment]
Related discussion out here : microsoft/node#7
