### ISSUE TITLE
toLocaleTimeString returns non-ascii characters

### ISSUE THREAD

**Issue by virdun** [Microsoft/ChakraCore#883]
// Issue in Edge but not in chrome
var t = dt.toLocaleTimeString(); // Say it returns 13:04:26
var tArr = t.split(':');
console.log(parseInt(tArr[0], 10); // returns NaN in Edge, other browsers return 13
console.log(+tArr[0]); // returns NaN in Edge, other browsers return 13
console.log(1 * tArr[0]); // returns NaN in Edge, other browsers return 13

// Solution to the problem for Edge and possibly IE11
function removeNonAscii(str) {
    var regx = new RegExp("[^\u0000-\u007F]", "g");
    return str.replace(regx, '');
}
var t = removeNonAscii(dt.toLocaleTimeString()); // Say it returns 13:04:26
var tArr = t.split(':');
console.log(parseInt(tArr[0], 10); // returns 13
console.log(+tArr[0]); // returns 13
console.log(1 * tArr[0]); // returns 13

**Comment by jianchun** [comment]
This is the same issue as #599

**Comment by virdun** [comment]
Yes, that is correct. I did not find that one before I posted. Sorry.
