### ISSUE TITLE
Simd.js Bug: F32 truncation to be done before bound check for Uint32x4.fromFloat32x4 conversion builtin

### ISSUE THREAD

**Issue by arunetm** [Microsoft/ChakraCore#890]
While converting from float32 to Uint32, the values needs to be truncated before performing bound check to be able to convert float32 values between 0 and -1.0. Only values <= -1.0 should throw.
http://tc39.github.io/ecmascript_simd/#simd-to-timd-logical

**Repro Case** 
```javascript 
function asmModule(stdlib) {
    "use asm";
    var u4 = stdlib.SIMD.Uint32x4;
    var u4check = u4.check;
    var u4ff4 = u4.fromFloat32x4;
    var f4 = stdlib.SIMD.Float32x4;
    var f4check = f4.check;
    function func1()
    {
        var a = f4(1.9, 0.0, -0.9, -0.0);
        return f4check(f4);
    }
    return {func1:func1};
}
var m = asmModule(this);
var ret2 = m.func1();
WScript.Echo(ret2);
```

**Expected Results**
>Successfully compiled asm.js code
SIMD.Uint32x4(1, 0, 0, 0)

**Actual Results**
>Successfully compiled asm.js code
RangeError: argument out of range
   at Global code (g:\bugs\stdstbug.js:15:1)

**Comment by nmostafa** [comment]
@dilijev , this is merged and should be closed.
