### ISSUE TITLE
Building x64_release: ch.exe doesn't do anything

### ISSUE THREAD

**Issue by kasajian** [Microsoft/ChakraCore#90]
Built x64_release Using Visual Studio 2015 Update 1.   When running ch.exe from the command prompt it says:

    Try 'ch.exe -?' for help

When issuing 'ch.exe -?', program reports error:

    The binary chakracore.dll is not test enabled, please use chakracore.dll from debug/test flavor

**Comment by ianwjhalliday** [comment]
Are you building release configuration?  ch.exe does not work with release builds of chakracore.dll, hence the error message.  Test is the same as release except it enables test switches.

**Comment by dilijev** [comment]
Ah I just tried it. It **is** a bit disconcerting that ch.exe builds in the release configuration but it can't even run a JS file, much less display the help message. We should probably remove the `ch.exe` binary from the release build configuration as it's not intended to do anything.

**Comment by ianwjhalliday** [comment]
Removing ch.exe from release build is a good idea

**Comment by ianwjhalliday** [comment]
@MikeHolman and I discussed offline and decided it would be better to improve the error message and then perhaps in the future make ch.exe work with release builds.  I'll submit a PR with a better error message shortly and open a new issue to track allowing ch.exe to work with release builds.

**Comment by dilijev** [comment]
Sounds good all around.

**Comment by kasajian** [comment]
Perfect.  It wasn't immediately obvious to me that I couldn't use it from a release build.   I build debug and it worked.

**Comment by ianwjhalliday** [comment]
Fixed, ch.exe now works in Release builds (without flag support) via #97.
