### ISSUE TITLE
Simd.js Asm.js : Disable Float64x2 and remove SIMD ops not in the spec

### ISSUE THREAD

**Issue by Krovatkin** [Microsoft/ChakraCore#907]
These are the items on our asm.js/simd.js spring cleaning list:

- [x] Disable **Float64x2** and **FromFloat64x2** opcodes
- [x] Remove **"and, or, xor, not"** for float32x4 type
- [x] Remove **"min/max"** for integral types
- [x] Remove/clean-up unit tests
- [ ]  Get a go from MSFT
- [ ] lunch?

Actual Output:

```
Not Available
```

Expected Output:

```
Not Available
```

**Comment by Krovatkin** [comment]
We'll be submitting a PR shortly

**Comment by nmostafa** [comment]
@abchatra , please confirm this is OK for release/1.2, and label accordingly. If we don't have it, then some currently unsupported data types/ops will be exposed in the library along with unused implementation code.

**Comment by Krovatkin** [comment]
@nmostafa ; Arun @arunetm raised an issue that we might need a negative test case in issue's description? Kindly advise if the testcase is indeed needed and what other corrections I should make to the description.

**Comment by abchatra** [comment]
@nmostafa I am ok with cleanup if this doesn't impact anything other than SIMD code. It is a bit late in the cycle for general cleanup. Also, why can't this be merged into master instead of 1.2?

**Comment by nmostafa** [comment]
The cleanup touches only SIMD code, and it is low risk in my opinion. The only issue I see from merging to master is that we will be shipping currently unsupported SIMD types and operations (removed from spec or postponed to phase 2). So we should at least disable those in JavascriptLibrary and AsmJs validation.

**Comment by abchatra** [comment]
Ok sure. I have marked it 1.2
