### ISSUE TITLE
Copyright Check takes a diff of the current branch versus master instead of the target branch.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#962]
It is still correct in the sense that it will get at least all of the files edited by a pull request, but it is checking a much larger set of files than necessary. Would be nice to clean this up.

**Comment by dilijev** [comment]
@mmitche @tcare Do you know if there's any way to detect the base branch of a commit given only that commit hash (which I think is all that is available to Jenkins -- @mmitche correct me if I'm wrong).

I'm thinking this might actually be an impossible issue to solve.

**Comment by mmitche** [comment]
@dilijev Actually a ton of other stuff is available:http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/1194/parameters/

All those are available in the environment while running a task.

**Comment by dilijev** [comment]
@mmitche Excellent! Just what I was looking for!

**Comment by dilijev** [comment]
@mmitche Are those available in both windows and linux environment variables?

**Comment by dilijev** [comment]
Note to self: the ones I will most likely be interested in are:
ghprbTargetBranch
ghprbSourceBranch

**Comment by mmitche** [comment]
Yes, %ghprbTargetBranch% in batch, and $ghprbTargetBranch in shell.  Make sure you escape the $ in the shell steps (in groovy) so that it will resolve at run-time and not generation time

**Comment by dilijev** [comment]
@mmitche Yep, thanks for the reminder -- that's always a good way to trip things up.

**Comment by dilijev** [comment]
@mmitche I was just thinking about this and I wonder if you know offhand if there would be a problem if the $ was used in a single-quoted string, since Jenkins won't interpolate variables in single-quoted strings AFAIK?

**Comment by mmitche** [comment]
@dilijev Nope it won't, so that makes it easy to do some of the shell scripting.  You can also do:

\$fooVar
