### ISSUE TITLE
xplat: examine _WIN64, should it be _M_X64?

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#963]
e.g. CallInfo.h, is following "unused" patch applicable to xplat x64?

```
        CallInfo(CallFlags flags, ushort count)
            : Flags(flags)
            , Count(count)
#ifdef _WIN64
            , unused(0)
#endif
        {
        }

        // Assumes big-endian layout
        // If the size of the count is changed, change should happen at following places also
        //  - scriptdirect.idl
        //  - LowererMDArch::LoadInputParamCount
        //
        unsigned  Count : 24;
        CallFlags Flags : 8;
#ifdef _WIN64
        unsigned unused : 32;
#endif
```

**Comment by obastemur** [comment]
How about `_M_X64_OR_ARM64` instead of `_M_X64` ? Especially for the sample you've shared.

**Comment by jianchun** [comment]
Yes, that may be better. Or maybe a new symbol `BIT64`.

**Comment by LouisLaf** [comment]
I don't like _M_X64 of _M_X64_OR_ARM64 as these are specific CPUs is the defines are just about 64 targets.  BIT64 is better but not that descriptive.  How about TARGET64 or HOST64?

**Comment by jianchun** [comment]
> I don't like _M_X64 of _M_X64_OR_ARM64 as these are specific CPUs is the defines are just about 64 targets.  BIT64 is better but not that descriptive.  How about TARGET64 or HOST64?

+1 TARGET64

**Comment by jianchun** [comment]
We now have `TARGET_64`. But lots of code (including new code) still uses `_WIN64`. Needs to search for all and evaluate which should change to `TARGET_64`.
