### ISSUE TITLE
[Test failure] [Daily] [DisableJIT] [All Branches] testSimdManyVars.js b95.js b108.js failing in Daily DisableJIT builds.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#964]
See daily build statuses for all branches here:
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#disablejit-builds
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28release-1.2%29#disablejit-builds
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28linux%29#disablejit-builds

See logs for example:
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/daily_disablejit_x64_debug/58/console
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/release_1.2/job/daily_disablejit_x64_debug/40/console
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/linux/job/daily_disablejit_x64_debug/9/console

@Krovatkin I believe this is your bug because you're the only person who has touched these files. Please fix with high priority to unblock merging the linux branch into master.

FYI @digitalinfinity

**Comment by Krovatkin** [comment]
@dilijev I think I might be missing a **require_backend** attribute on those tests, but let me double check.  fyi @nmostafa

**Comment by Krovatkin** [comment]
FYI: @dilijev I created a PR in intel's repo for @nmostafa to review a fix. This way Nagy and I can have a quick internal discussion on the fix and as soon as we decide its in a good enough shape I'll create a PR in msft repo.
