### ISSUE TITLE
Crash when a class closes over lexically-bound variables inside an eval

### ISSUE THREAD

**Issue by shicks** [Microsoft/ChakraCore#974]
Steps to reproduce in Edge 13:

Point browser to a page serving the following JS file:
```js
eval('(function(){let a; class A { x() { return a; } } })()');
```

This will cause the page to fail to load, immediately reloading the HTML and JS from the server a second time, and then giving up with a message of "This page is having a problem loading.  We tried to load this page for you a few times ...".

The crash can be averted in any of several different ways:

1. Remove the `eval` - the code itself works fine outside an eval
1. Change `let` to `var` - no problems there [note that changing to `const` (and assigning something, as required) does *not* prevent the crash]
1. Change the method to a function (i.e. remove the class) - ordinary functions have no problems
1. Remove the IIFE - top-level `let`s seem to be fine, too
1. After a crash, open devtools (F12), highlight the URL, and hit enter - may take a few tries before it finally succeeds, but once it does, it continues to succeed

The crash appears to be independent of strict mode - adding `"use strict";` either at the beginning of the eval, or immediately inside the function - neither makes a difference.

**Comment by ianwjhalliday** [comment]
Thanks for reporting this bug @shicks 

It has already been fixed in ChakraCore and will be included in the next release of Edge.  If I am not mistaken it should also be fixed in the latest preview builds of Windows too.
