### ISSUE TITLE
Chakra embedded in UWP application fails WAC tool

### ISSUE THREAD

**Issue by rcosnita** [Microsoft/ChakraCore#989]
I tried to embed Chakra into UWP by following the steps from https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore guide. Everything works fine the appx fails WAC certification for Release_x64 configuration (supported apis). Isn't chakra supposed to run in UWP store application? Below you can find all not supported api reported by WAC tool:

API _CxxThrowException in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __CxxFrameHandler3 in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __telemetry_main_invoke_trigger in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API __telemetry_main_return_trigger in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API wcschr in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API wcsrchr in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API wcsstr in vcruntime140.dll is not supported for this application type. ChakraCore.dll calls this API.
API RegCloseKey in advapi32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RegGetValueW in advapi32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RegOpenKeyExW in advapi32.dll is not supported for this application type. ChakraCore.dll calls this API.
API AddAtomW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API CompareStringW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API DebugBreak in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API DeleteAtom in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API FindAtomW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API FindResourceExW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API FlushInstructionCache in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetConsoleScreenBufferInfo in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetDateFormatW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetEnvironmentVariableW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetLocaleInfoW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetLogicalProcessorInformation in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetProcessIoCounters in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetStdHandle in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetSystemTimeAdjustment in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetTickCount in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetTimeFormatW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetUserDefaultLCID in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GlobalMemoryStatusEx in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API LCMapStringW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API LoadLibraryExA in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API LoadLibraryExW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API LoadResource in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API LockResource in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API QueryThreadCycleTime in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RtlAddFunctionTable in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RtlDeleteFunctionTable in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API SetConsoleTextAttribute in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API SetThreadStackGuarantee in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API SizeofResource in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API TlsAlloc in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API TlsFree in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API TlsGetValue in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API TlsSetValue in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API VerSetConditionMask in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API VerifyVersionInfoW in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API VirtualAlloc in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API VirtualProtect in kernel32.dll is not supported for this application type. ChakraCore.dll calls this API.
API CharLowerBuffW in user32.dll is not supported for this application type. ChakraCore.dll calls this API.
API CharUpperBuffW in user32.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetFileVersionInfoExW in version.dll is not supported for this application type. ChakraCore.dll calls this API.
API GetFileVersionInfoSizeExW in version.dll is not supported for this application type. ChakraCore.dll calls this API.
API VerQueryValueW in version.dll is not supported for this application type. ChakraCore.dll calls this API.

**Comment by rcosnita** [comment]
I apologise for it. I used the Debug configuration instead of Release configuration.

**Comment by brodybits** [comment]
I would like to see this documented. I am not sure when I would get a chance to contribute.

**Comment by rcosnita** [comment]
@brodybits WAC tool fails only if I use the Debug configuration for my app. If I embed Chakra into an UWP app and build the release configuration everything it's fine so there is no issue.
