### ISSUE TITLE
Compiler Error under Windows 7 SP1 32-bit Chinese Simplified

### ISSUE THREAD

**Issue by leejingbo** [Microsoft/ChakraCore#99]
这三个文件：
\lib\common\Memory\PageAllocator.h

\lib\Runtime\Library\ArgumentsObject.h

\lib\Runtime\Library\MathLibrary.cpp

warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

需要修改上述三个文件的编码才能正确编译。

**Comment by MikeHolman** [comment]
Maybe an issue with file encoding? I see that PageAllocator.h and ArgumentsObject.h are ANSI (where as far as I can tell the rest of the files are UTF8). However, MathLibrary.cpp looks to be UTF8, so I don't know what's going on there.

**Comment by leejingbo** [comment]
MathLibrary 原来是 UTF-8 无签名， 我改成 UTF-8带签名 之后就可以编译了。

**Comment by MikeHolman** [comment]
Ok, great. Would you be able to send a pull request with your changes?

**Comment by liminzhu** [comment]
Translating title from "Windows 7 SP1 32位简体中文版下编译出错" to "Compiling Error under Windows 7 SP1 32-bit Chinese Simplified"

**Comment by fcharlie** [comment]
@dilijev @liminzhu  This Bug still exists    
File:  https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/arm/ARMEncode.h
